### ISSUE TITLE
App crashes on close repeatedly

### ISSUE THREAD

**Issue by Scolly88** [qgis/QGIS#31219] opened 2019-08-12 23:48 UTC
After saving project, whenever I close the application it inevitably crashes

Crash ID: 5ad41d6be94809f981e2ec9b06a0e20f1d0b0a87

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.9-Madeira
QGIS code revision: 54585165bb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by NathanW2** [comment] 2019-08-13 03:23
Hi,

Are you able to upgrade to the latest QGIS 2.4.10 release as we should have
this fixed in that version.

- Nathan

>

**Comment by jef-n** [comment] 2019-08-13 06:29
Duplicate of #28104

**Closed** 2019-08-13 06:30 UTC
Labels: Bug

**Comment by Scolly88** [comment] 2019-08-13 07:17
## User Feedback

Same thing repeated after updating to latest version, see stack trace attached

## Report Details

*Crash ID*: 5ad41d6be94809f981e2ec9b06a0e20f1d0b0a87


*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.4.9-Madeira
QGIS code revision: 54585165bb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134
