### ISSUE TITLE
race condition affecting the TilesXYZ MBTiles export plugin

### ISSUE THREAD

**Issue by mash-graz** [qgis/QGIS#32471] opened 2019-10-29 04:46 UTC
[i already reported the bug to original author (https://github.com/lutraconsulting/qgis-xyz-tiles/issues/30), but because the plugin is in the meanwhile a default component of QGIS and the issue could perhaps familiar to the developers of the main application, i try to report it here as well.]

your TilesXYZ MBTiles export plugin (`qgis/python/plugins/processing/algs/qgis/TilesXYZ.py`) included in QGIS 3.10 for linux seems to be plagued by race conditions when it becomes executed in multiple threads.

the issue doesn't appear in case of the DirectoryWriter, but the MBTilesWriter will hardly work at all and produce corrupt files with lots of missing tiles and other defects...

as a symptom of this particular issue, you should often see error messages like this:

    ERROR 5: /tmp/test7.mbtiles: Access window out of range in RasterIO().  Requested (-569088,-368384) of size 256x256 on raster of 512x512.

the strange negative numbers are a side effect of unexpected changed values of the `self._first_tile` variable resp. colliding zoom factors which are running in parallel and overwrite the expected state one another...

i did try to fix the issue by replacing `self._first_tile` and `self._zoom_ds` with dictionaries indexed by the zoom factor to reduce the observable collisions. this had some positive effect, but it doesn't completely fix the issues. :(

unfortunately i do not know, how to fix this kind of thread lock requirements in case of QGIS plugins in a more adequate manner. 

the versions of my affected debian linux installation:

```
QGIS-Version: 3.10.0-A Coruña
QGIS-Codeversion: 6c816b4204
Qt-Version: 5.11.3
GDAL-Version: 2.4.2
GEOS-Version: 3.8.0-CAPI-1.13.1 
PROJ-Version: Rel. 5.2.0, September 15th, 2018
Verarbeite Algorithmus…
Algorithmus XYZ-Kacheln erzeugen (MBTiles) startet…
Eingabeparameter:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '1716053.858612443,1721455.9642655044,5951485.136729757,5955838.399322829 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : '/tmp/test7.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 16, 'ZOOM_MIN' : 12 }

Using 8 CPU Threads:
Pushing all tiles at once: 11 tiles.
Ausführung nach 2.34 Sekunden abgeschlossen
Ergebnisse:
{'OUTPUT_FILE': '/tmp/test7.mbtiles'}
```

**Comment by mash-graz** [comment] 2019-10-29 21:18
here is a little QGIS python script to reproduce the issue more simply -- i.e. it will produce the already described "Error 5: ..." symptoms:

```
from qgis import processing
import os, time
from PyQt5.QtWidgets import QApplication

urlWithParams = 'type=xyz&url=http://a.tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0&crs=EPSG3857'
rlayer = QgsRasterLayer(urlWithParams, 'OpenStreetMap', 'wms')
QgsProject.instance().addMapLayer(rlayer)

QApplication.processEvents()
canvas = qgis.utils.iface.mapCanvas()
QApplication.processEvents()
canvas.setCenter(QgsPointXY(1718997.0,5953640.0))
QApplication.processEvents()
canvas.zoomScale(40000)

if os.path.exists('/tmp/test.mbtiles'):
    os.remove('/tmp/test.mbtiles')

processing.run("qgis:tilesxyzmbtiles", { 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 300, 'EXTENT' : '1715377.499996308,1721632.2500026878,5950914.791663888,5956608.625003029 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : '/tmp/test.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 16, 'ZOOM_MIN' : 12 })
```
i also have to report, that event setting `MAX_THREADS` to `1` as a temporary work around doesn't work, because it will trigger additional bugs... :(

it think, the troubles are related to a few commits from Aug 12, 2019 developed resp. merged by @Isghj5 and @nyalldawson -- https://github.com/qgis/QGIS/commits/6c816b4204162945336c18ccf44ffce7be2bf1b5/python/plugins/processing/algs/qgis/TilesXYZ.py

**Comment by mash-graz** [comment] 2019-10-30 00:25
i hope this fix will solve the issue...
but please take look at it and test it!

**Comment by jrothenberg** [comment] 2019-11-19 20:10
I can confirm that mbtiles export is broken in 3.10 and mash-graz's fix works for me, so it would be nice if it could get merged. Otherwise it would probably be better to at least revert to the single threaded version of the script in the meantime.

**Comment by mash-graz** [comment] 2019-12-05 12:18
> I can confirm that mbtiles export is broken in 3.10 and mash-graz's fix works for me, so it would be nice if it could get merged. Otherwise it would probably be better to at least revert to the single threaded version of the script in the meantime.

thanks for testing the patch!

i would be also happy, if @nyalldawson or someone else of the QGIS core developers could finally review and merge PR #32499 or at least give me any useful feedback concerning necessary improvements, because the suggested code changes are not only waiting for more than a month now,  but there are already other merged commits and open bug reports (e.g. #33228) around, which refer to this module and my repair efforts.

**Closed** 2019-12-06 09:59 UTC
Labels: Bug, Processing
