### ISSUE TITLE
DB Manager does not show anymore query results when there are duplicated field names

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#36205] opened 2020-05-05 13:37 UTC
QGIS master, Ubuntu 18.04

Seems to happen when in the SELECT statement there are >1 table.

![Peek 2020-05-05 14-37](https://user-images.githubusercontent.com/1951107/81072395-ffdfe000-8edd-11ea-9f9c-8472c1d87548.gif)

**Comment by Gustry** [comment] 2020-05-05 13:53
Remove the `;` and it should work. It' a duplicate of https://github.com/qgis/QGIS/issues/34731 ?

**Comment by gioman** [comment] 2020-05-05 14:07
@Gustry with or without ";" does not make any difference.

**Comment by GIS-enthusiast** [comment] 2020-05-06 10:25
I noticed something similar two weeks ago; the SELECT statement results show when running a query in Geopackage or SpatiaLite in DB Manager but not for PostGIS (running Q3.12 on Windows).

**Comment by espinafre** [comment] 2020-05-11 23:53
This is what I get on a debug build (to reproduce with @gioman 's example query, the geometry column must be of Polygon type, and there must be overlapping polygons):

```
src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x7f9ba0005790] 2020-05-11T20:39:49 PostGIS[1] Duplicate field id found
src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x7f9ba0005790] 2020-05-11T20:39:49 PostGIS[1] PostgreSQL layer has no primary key.
```
I was going to suggest adding `row_number() over() as ctid`  to your SELECT fields as a workaround, but it doesn't work either.

What gets sent to the database is:

```sql
SELECT * FROM (SELECT row_number() OVER () AS __rid__, * FROM (select row_number() over() as ctid, * from test_gen_col g1, test_gen_col g2 where st_overlaps(g1.geom, g2.geom) and g1.id <> g2.id) as foo) AS "subQuery_0" LIMIT 0;

```
(my testing table is called "test_gen_col") even with the row_number(). This is what I caught on the PostgreSQL log. The key here is the LIMIT 0. This is worth investigating.

**Comment by espinafre** [comment] 2020-05-12 03:25
Ha! @gioman , try changin your query a little:

```sql
select
	g1.*
from
	test_gen_col g1,
	test_gen_col g2
where
	st_overlaps(g1.geom, g2.geom)
	and g1.id <> g2.id
```

That is, use g1.* instead of simply * on your list of SELECTed fields, otherwise the returned dataset will have repeated duplicated field names, which will make the provider choke.

**Comment by espinafre** [comment] 2020-05-12 03:53
There it is the reason you see this behavior, @gioman :
 
https://github.com/qgis/QGIS/blob/59e1dce7328e76c7c0f6a03d8e4937101587830a/src/providers/postgres/qgspostgresprovider.cpp#L1144-L1148

The provider doesn't actually "choke" as I said earlier, but this behavior is by design: each field name must be unique. What could be done is to make more explicit to the user that there are repeated field names, and that QGIS won't accept none of that nonsense.

As an aside, when testing this issue, I've found that, for this query in particular at least, the DB Manager won't strip semicolons from the end of queries as reported on #35426 as of master 59e1dce7328e76c7c0f6a03d8e4937101587830a .

**Comment by espinafre** [comment] 2020-05-12 04:53
The SpatiaLite provider actually allows this behavior, I've just checked. I think that what could be done for the PostgreSQL provider is to emulate SpatiaLite's behavior by appending :1, :2 etc. to repeated field names. @jef-n , what do you think?

This is not, however, a regression, since this exists for at least 10 years according to git blame (https://github.com/qgis/QGIS/blame/59e1dce7328e76c7c0f6a03d8e4937101587830a/src/providers/postgres/qgspostgresprovider.cpp#L1144-L1148), nor a DB Manager bug, since the origin of the behavior is in the provider.

**Comment by gioman** [comment] 2020-05-12 08:06
> each field name must be unique

@espinafre Olá, thanks for looking into this. But the above should not be necessary in SELECT only queries. In fact is not a requirement in other SQL consoles, and as far as I remember also was't a requirement in the past in QGIS (not 100% sure anyway).

**Comment by gioman** [comment] 2020-05-12 08:08
> This is not, however, a regression

ummm weird... I probably run a similar query a lot of times and can't recall such behavior. I guess that at least DB Manager should raise a warning message.

**Comment by GIS-enthusiast** [comment] 2020-05-12 13:10
In case this helps. Having read your latest conversation today I tried to run my PostGIS query in DB Manger without a semicolon and it worked now. 

select *
from region

I had posted the issue here: https://gis.stackexchange.com/questions/358926/results-not-showing-in-sql-window-in-db-manager-qgis-3-12?noredirect=1#comment587606_358926

**Comment by gioman** [comment] 2020-05-12 22:57
> In case this helps. Having read your latest conversation today I tried to run my PostGIS query in DB Manger without a semicolon and it worked now.
> 
> select *
> from region

the issue reported here is a different one.

**Comment by billjwilliamson** [comment] 2020-05-25 22:52
As far as usability, it is a regression
Do;
`SELECT MAX (event_id), MIN (event_id)
FROM table.records;`
Nothing!

**Comment by espinafre** [comment] 2020-05-25 23:23
@billjwilliamson , nothing only if your table has no records. Otherwise, PostgreSQL will yield two columns, named "max" and "min"; you won't be able to load the resulting query as a new layer because there is no geometry table. I've just tested it.

@gioman , I'm positive that the DB Manager (and the PostgreSQL) hasn't allowed duplicated field names from the same query for at least 10 years. Maybe the labels on this issue should be reconsidered? 

I've taken a shot at allowing the provider to handle repeated column names in selects, but with no luck so far, and frankly, I believe it would be a lot of work for little gain.

**Comment by billjwilliamson** [comment] 2020-05-25 23:33
@espinafre thank you for considering but I mean there is no output in the console (regardless of seeing it as a new layer or not).  Do something, get nothing. No error, no output, only a little report of how long it took to do nothing.

**Comment by espinafre** [comment] 2020-05-25 23:40
@billjwilliamson remove the ";" from your query, but that is another issue, not what is being discussed here; you may refer to #34731 .

**Comment by gioman** [comment] 2020-05-26 08:14
> @gioman , I'm positive that the DB Manager (and the PostgreSQL) hasn't allowed duplicated field names from the same query for at least 10 years. Maybe the labels on this issue should be reconsidered?
> 
> I've taken a shot at allowing the provider to handle repeated column names in selects, but with no luck so far, and frankly, I believe it would be a lot of work for little gain.

@espinafre Olá, well assuming you are right (that was always the case in DB Manager) I don't think it would be "little gain". At this moment just because a user overlooks a detail in its SELECT query (aliasing a column name) it get 0 results instead of a real result (as other SQL consoles) or an error. This can makes the difference between a very wrong, real life, decision and the correct one. I argue that this is indeed a very bad bug.

**Comment by gioman** [comment] 2020-05-26 08:34
@espinafre on 2.18 **it works** as expected, so definitely a regression.

**Comment by elpaso** [comment] 2020-05-29 09:55
@gioman I cannot reproduce on master/linux if I do **not** add a trailing `;`. You mentioned in https://github.com/qgis/QGIS/issues/36205#issuecomment-624077405 that it does not make a difference, do you confirm?

my test query:

```
select w.name, a.fid from world as w, as_areas as a  where w.name = 'ITALY' and a.fid = 1;
```

Can you give me an example of a failing query? Possibly taken from the `qgis_test` DB that we use for all QGIS tests, you can easily create that DB by running: https://github.com/qgis/QGIS/blob/master/tests/testdata/provider/testdata_pg.sh

**Comment by gioman** [comment] 2020-05-29 10:56
@elpaso I run the script you tell me, but anyway I can't see any table called "world" among the ones that were created.

Anyway you can use another table generated by the script, "qgis_test.some_poly_data".

Load it in QGIS, then digitize a polygon in the table that overlaps one of the existing ones.

After that run this in DB Manager, with or without the trailing ";" and then run it in PgAdmin:
```

 SELECT *
 from
 qgis_test.some_poly_data a, qgis_test.some_poly_data b
 where
 ST_Overlaps(a.geom,b.geom) = TRUE
```

0 results in DB Manager, 3 results in PGAdmin.

**Comment by elpaso** [comment] 2020-05-29 14:26
Let's consider the issue in two separate parts:

1. run a query with duplicated field names in DB manager and see the results in the table below
2. create a query layer from the a.m. query

for 1, this is probably a regression, because we are now using QGIS API to run the query instead of the old Python implementation
for 2, I'm pretty sure that it has never been possible to create a query layer from a query that resulted in duplicated names.

2 is not easily fixable an IMO is a won't fix.
1 is not fixable either because it's now basically implemented in the same way as "2" so the best we can do is probably bubble up the error in DB manager and invite the user to write a query with not ambiguous field names.

**Comment by gioman** [comment] 2020-05-29 14:31
@elpaso this ticket is only about 1). I have never said anything about 2) (in this ticket).



> 2 is not easily fixable an IMO is a won't fix.

sound reasonable.





> 1 is not fixable either because it's now basically implemented in the same way as "2" so the best we can do is probably bubble up the error in DB manager and invite the user to write a query with not ambiguous field names.

an error is better than the actual behavior, that is **dangerous**. Anyway is a real regression, in 2.18 I already checked that worked as expected (so it returns results, as in any other SQL console I tested, as psql, pgadmin and dbeaver).

**Comment by elpaso** [comment] 2020-05-29 15:07
@gioman let me see what I can do for "1", there might be a way.

**Closed** 2020-06-02 06:33 UTC
Labels: Bug, DB Manager, Feedback, High Priority, Regression
