### ISSUE TITLE
split vector layer don't work if defaut file is set to gpkg

### ISSUE THREAD

**Issue by geostonemarten** [qgis/QGIS#37351] opened 2020-06-23 12:56 UTC
The geoprocessing name "Split Vector Layer" don't work if GPKG is set as default output vecteur layers type

![image](https://user-images.githubusercontent.com/5580128/85406114-9c7b4180-b561-11ea-9118-8fe25118db46.png)

Global environement
'windows'
'desktop'
'3.10'
'3.10.6-A Coruña'

**Comment by gioman** [comment] 2020-06-23 12:59
@geostonemarten duplicate of https://github.com/qgis/QGIS/issues/36378 ?

**Comment by geostonemarten** [comment] 2020-06-23 15:44
> 
> 
> @geostonemarten duplicate of #36378 ?

Yes It is right! But this comportment is because gpkg is set by defaut in this version. 

GPKG featurelayers haven't a good path format in trace log.

**Comment by gioman** [comment] 2020-06-23 15:44
Closing as duplicate.

**Closed by gioman** 2020-06-23 15:44 UTC
Labels: Bug, Feedback, Processing
