### ISSUE TITLE
Georeferencer -- Blank image ot of canvas when panning

### ISSUE THREAD

**Issue by mimi89999** [qgis/QGIS#42043] opened 2021-03-04 16:37 UTC
**Describe the bug**
When panning the raster in the georeferencer instead of seeing the content outside the canvas, the white background is shown.

**How to Reproduce**

1. Load a raster in georefenrecer
2. Grab and start panning
3. Notice that instead of seeing what was outside the canvas, the white background is shown.
4. Release and notice that the image is reloaded and only then what was outside the canvas is shown.

**QGIS and OS versions**

Version de QGIS | 3.16.4-Hannover | Branche de code de QGIS | Release 3.16
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.2.1 | Utilisé avec GDAL/OGR | 3.2.1
Compilé avec GEOS | 3.9.0-CAPI-1.16.2 | Utilisé avec GEOS | 3.9.0-CAPI-1.16.2
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.34.1
Version du client PostgreSQL | 13.2 (Debian 13.2-1) | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 7.2.1 | Fonctionne avec PROJ | Rel. 7.2.1, January 1st, 2021
Version de l'OS | Debian GNU/Linux bullseye/sid
Extensions Python actives | OSMDownloader; QuickOSM; contour; processing; db_manager; MetaSearch

**Additional context**

**Comment by uclaros** [comment] 2021-03-04 17:17
That's the way mapCanvas works. The same is true for the main map canvas with both raster and vector layers.

**Comment by roya0045** [comment] 2021-03-04 17:20
Georeferencer is independent of canvas, not a bug.

**Comment by mimi89999** [comment] 2021-03-04 18:48
Well, in the main map it's OK

https://user-images.githubusercontent.com/8530546/110013984-8a71b580-7d22-11eb-87ca-78f7a9cfd4e5.mp4

**Comment by gioman** [comment] 2021-03-04 18:51
> Well, in the main map it's OK

@mimi89999 it was a recent improvement (for the map canvas), it probably need to be extended to the georef. This a feature request, not a bug.

**Comment by nyalldawson** [comment] 2021-03-04 20:34
Fixed in 3.18

**Closed by nyalldawson** 2021-03-04 20:34 UTC
Labels: Feature Request, Georeferencer

**Comment by mimi89999** [comment] 2021-03-04 20:43
Could it be backported to 3.16 LTR? What commit fixed it?

**Comment by nyalldawson** [comment] 2021-03-04 20:54
No, it's way too intrusive. It relies on a reworking of the map renderer in canvases which was done in. 3.18.
