### ISSUE TITLE
Dragging a GPKG file into another GPKG file in the Browser Panel causes data corruption

### ISSUE THREAD

**Issue by Teodora18** [qgis/QGIS#45177] opened 2021-09-21 16:13 UTC
### What is the bug or the crash?

Dragging a GPKG file into another GPKG file in the Browser Panel causes data corruption. An error dialogs appears and right after that a green bar on the top says the import was successful. However, it caused a complete data corruption. Then the geometry of the layers in the destination GPKG file are changed and becomes the same as the geometry of the dragged GPKG file.

However, a user would expect the layers from the first GPKG to be imported into the second GPKG without breaking the data in the second one.

### Steps to reproduce the issue

1. Create two GPKG layer in separate files with different attributes and geometries (`layer1.gpkg` and `layer2.gpkg`).
2. Drag the whole GPKG file `layer1.gpkg` into `layer2.gpkg`.
3. An error dialog appears saying it failed to import.
4. A green bar at the top says "successful import".
5. Import the layer from `layer2.gpkg`. It has the geometry of `layer1.gpkg`, as well as attributes. However, the data is heavily corrupted. The browser icon showing the layer geometry type (point, line, polygon) of the layer is not updated.

https://user-images.githubusercontent.com/72937659/134206450-d43c6609-6945-4077-98a5-f3df8026a788.mp4

### Project and layers use
[qgis_bug_gpkg_import.zip](https://github.com/qgis/QGIS/files/7204682/qgis_bug_gpkg_import.zip)

### Versions

3.20.3-Odense on Windows 10

### Additional context

Dragging a single layer from the GPKG file, instead of the file Browser Panel item works as expected.

**Comment by gioman** [comment] 2021-09-21 16:19
I can confirm the error but not the corruption (QGIS master on Ubuntu 20.04).

**Comment by suricactus** [comment] 2021-09-21 16:27
I can confirm the error is happening for me too (Ubuntu 20.04). The data seem to be corrupted in a usable way, but `layer2` contents is completely gone for me.

**Comment by elpaso** [comment] 2021-09-22 13:43
@gioman is this a regression?

**Comment by elpaso** [comment] 2021-09-22 13:54
I cannot reproduce on current master.

Dragging the whole `layer1.gpkg` onto `layer2.gpkg` from "Project Home" browser item produces an error and nothing else:

![immagine](https://user-images.githubusercontent.com/142164/134356935-16388242-6c9b-4106-86e4-41657df1612f.png)

**Comment by gioman** [comment] 2021-09-23 18:12
> @gioman is this a regression?

@elpaso this is my observation on Windows

3.10: not possible to d&d a gpkg into another
3.16: no error message, data corruption
3.20: error message data corruption
master: error message, no corruption

**Comment by Jeroen-GroeneBij** [comment] 2022-08-20 08:31
Hi, I just tested this issue on 3.26.2. on a Windows machine. The error message is still there. Strangely enough telling us some layer is not a raster layer when there is no raster layer at all in both gpkg.
After the error message, no data is added to the second gpgk and no data is corrupted.

Beside this, isn't it considered odd to add an entire gpkg file to another gpkg? Adding layers from one gpkg into another gpkg using the Browser panel works fine. You can even add mutiple layers at once to another gpkg.

**Comment by uclaros** [comment] 2022-09-21 06:47
Fixed by #49867

**Closed by uclaros** 2022-09-21 06:47 UTC
Labels: Bug, Crash/Data Corruption, QGIS Browser, Windows
