### ISSUE TITLE
QT errors in Log panel while copy to clipboard in OS outside QGIS

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#43038] opened 2021-04-30 08:30 UTC
![clipboard bug](https://user-images.githubusercontent.com/874261/116669473-49ef8a80-a9a7-11eb-834e-dddc6e667d55.gif)

When I do Ctrl+C in Operating system outside QGIS app (while QQIS is running) I always get QT error in QGIS Log Panel.
Not critical but very annoying.  Can you confirm it's not my local issue.

QGIS Master(new OSGeo4W installer), clean profile without third party plugins
Windows 10 x64.

**Comment by nicogodet** [comment] 2021-04-30 09:17
Can't reproduce on 3.16.6, 3.18.2 and Master with testing OSGeo4W installer.

**Comment by roya0045** [comment] 2021-04-30 11:16
Yeah that's standard in debug builds.

**Comment by FelisPimeja** [comment] 2021-04-30 12:41
My mistake - it's happening only on master.
Fixed the initial description.

**Comment by gioman** [comment] 2021-04-30 13:50
>  I'm using nightly builds but not debug.

@FelisPimeja nightlies have debug enabled, closing?

**Closed** 2021-04-30 19:18 UTC
Labels: Bug, Feedback, Low priority
