### ISSUE TITLE
Categorized simbolization not assuming hex color.

### ISSUE THREAD

**Issue by AAnderl** [qgis/QGIS#58870] opened 2024-09-25 12:36 UTC
### What is the bug or the crash?

I am trying to set up a categorized symbolization of multipoint layer, but facing problems with color representation. Color is stored in hex format into "Hex" attibute. Color representantion is correct in Map window, but incorrect in Layers panel. Main problem is that Map compositor represents same colors that are displayed in Layers panel (the incorrect ones).

### Steps to reproduce the issue

Select layer -> Go to Layer style panel -> At the top, select "Categorized" from the drop-down menu -> Click on the symbol to edit it -> Bind color to the "Hex" attribute:
![01](https://github.com/user-attachments/assets/89251bc7-ca2e-4a82-8bf5-8659e0c9eead)

As shown below, the representation is correct on the map, but not in the Layers panel:
![02](https://github.com/user-attachments/assets/62727e95-ab4f-426d-9c08-11f8336d075d)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.36.1-Maidenhead | Revisión del código de QGIS | 3e589453
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.18
Versión de GDAL/OGR | 3.8.4
Versión de PROJ | 9.3.1
Versión del registro de base de datos EPSG | v10.098 (2023-11-24)
Versión de GEOS | 3.12.1-CAPI-1.18.1
Versión de SQLite | 3.41.1
Versión de PDAL | 2.6.0
Versión del cliente de PostgreSQL | 16.2
Versión de SpatiaLite | 5.1.0
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.4
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
feature_z | 1.0
flowTrace | 1.1.1
GeometryShapes | 0.7
gistools | 0.3
mmqgis | 2021.9.10
Multi_Ring_Buffer | 1.1
OpenTopography-DEM-Downloader | 2.0
pluginbuilder3 | 3.2.1
qgis-maptiler-plugin | 3.3
QuickOSM | 2.2.3
quick_map_services | 0.19.34
Serval | 3.32.0
TerrainShading | 0.9.5
vector_tiles_reader | 3.2.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Versión de QGIS
3.36.1-Maidenhead
Revisión del código de QGIS
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Versión Qt
5.15.3
Versión de Python
3.9.18
Versión de GDAL/OGR
3.8.4
Versión de PROJ
9.3.1
Versión del registro de base de datos EPSG
v10.098 (2023-11-24)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.41.1
Versión de PDAL
2.6.0
Versión del cliente de PostgreSQL
16.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
feature_z
1.0
flowTrace
1.1.1
GeometryShapes
0.7
gistools
0.3
mmqgis
2021.9.10
Multi_Ring_Buffer
1.1
OpenTopography-DEM-Downloader
2.0
pluginbuilder3
3.2.1
qgis-maptiler-plugin
3.3
QuickOSM
2.2.3
quick_map_services
0.19.34
Serval
3.32.0
TerrainShading
0.9.5
vector_tiles_reader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment] 2024-09-25 17:05
Duplicate of #55038

**Comment by AAnderl** [comment] 2024-09-26 07:52
> Duplicate of #55038

Thank you @roya0045 . There is a way to control the colors that will appear in the map legend? I have a map with hundreds of features and a attribute defining the color they should have in the representation. Map shows right color but leyend shows a random one.
I'm struggling trying to figure out what you meant with "The proper solution would be to create a symbology file and use the color attribute of your feature to define the symbol color. Would be doable with a custom processing tool." Please can you elaborate a little?

**Comment by roya0045** [comment] 2024-09-26 11:46
> > Duplicate of #55038
> 
> Thank you @roya0045 . There is a way to control the colors that will appear in the map legend? I have a map with hundreds of features and a attribute defining the color they should have in the representation. Map shows right color but leyend shows a random one. I'm struggling trying to figure out what you meant with "The proper solution would be to create a symbology file and use the color attribute of your feature to define the symbol color. Would be doable with a custom processing tool." Please can you elaborate a little?

As mentionned in the other issue, the legend symbol itself has no attributes, even if you have only one feature that would be rendered by it. If you want to have the colors match the evaluated color ( this is assuming that all the features for a given symbol have exactly the same color attribute) you either have to modify the attribute manually to match them.

Another option would be to make a processing alg that iterate on your dataset based on the expression used in the symbology to acquire all the potential color values and apply the most frequent value to the QgsSymbol in the live class or in a QML. May I can do this alg and share it if I get enough free time.

**Comment by AAnderl** [comment] 2024-09-26 12:24
> As mentionned in the other issue, the legend symbol itself has no attributes, even if you have only one feature that would be rendered by it. If you want to have the colors match the evaluated color ( this is assuming that all the features for a given symbol have exactly the same color attribute) you either have to modify the attribute manually to match them.
> 
> Another option would be to make a processing alg that iterate on your dataset based on the expression used in the symbology to acquire all the potential color values and apply the most frequent value to the QgsSymbol in the live class or in a QML. May I can do this alg and share it if I get enough free time.

I really appreciate your help, but make it by hand is not an option and getting into some kind of programming mess is beyond me.

I find its really frustrating... I have a raster file with "n" different colors. I just want to insert a legend explaining what each single color means but something as simple as that is turning out to be impossible. You don't want to say its a bug, but for me its a clear one, since there is no way to make a legend to show in Map compositor the same colors that a layer shows in Map canvas.

Brrrr... thanks again.

**Comment by roya0045** [comment] 2024-09-26 13:59
> 
> I really appreciate your help, but make it by hand is not an option and getting into some kind of programming mess is beyond me.
> 
> I find its really frustrating... I have a raster file with "n" different colors. I just want to insert a legend explaining what each single color means but something as simple as that is turning out to be impossible. You don't want to say its a bug, but for me its a clear one, since there is no way to make a legend to show in Map compositor the same colors that a layer shows in Map canvas.
> 
> Brrrr... thanks again.

For a raster file you can use the 'unique palette value' render, that should work. Not the same for vector.

**Comment by roya0045** [comment] 2024-09-27 13:13
For vectors, there is a workaround in #55038 (this issue is also a duplicate of it imo), and I added a tool to 'fix' this problem.

The issue can be closed imo.

**Comment by AAnderl** [comment] 2024-09-28 16:53
I really appreciate your help and I'm sorry to bother you so much with this, but I am unable to find your processing alg that should helps with problem. At the end of #55038 you say "I added a processing alg in the original issue ticket, this should help". I'm sorry, but I have no idea where it is.

Otherwise, I don't agree with closing the ticket because for me this is a bug: You create a layer, assign colors to the different entities in it and then it is impossible (without getting into a mess like this) for those colors to appear in the map legend, instead arbitrary colors appear.

But as is obvious, I am far from being an expert, so your criteria will be correct.

Greetings

**Closed** 2024-09-28 23:20 UTC
Labels: Bug

**Comment by roya0045** [comment] 2024-09-29 13:28
> I really appreciate your help and I'm sorry to bother you so much with this, but I am unable to find your processing alg that should helps with problem. At the end of #55038 you say "I added a processing alg in the original issue ticket, this should help". I'm sorry, but I have no idea where it is.
> 
> Otherwise, I don't agree with closing the ticket because for me this is a bug: You create a layer, assign colors to the different entities in it and then it is impossible (without getting into a mess like this) for those colors to appear in the map legend, instead arbitrary colors appear.
> 
> But as is obvious, I am far from being an expert, so your criteria will be correct.
> 
> Greetings

I pasted the wrong ID, the original is #53065 two solutions are there.

**Comment by AAnderl** [comment] 2024-09-30 07:29
Thanks a lot @roya0045 . I have no idea if that works because I don't know how to get it working, but I'll be looking around the internet until I get it. Thanks again for the time you've put into this.

**Comment by AAnderl** [comment] 2024-10-02 09:50
@roya0045 Processing algorithm is running like a charm. THANK YOU!

**Comment by roya0045** [comment] 2024-10-06 21:49
> @roya0045 Processing algorithm is running like a charm. THANK YOU!

Glad you figured it out and it's helpful!
