### ISSUE TITLE
Layer Properties dialog - unable to resize

### ISSUE THREAD

**Issue by LeneFischer** [qgis/QGIS#53613] opened 2023-06-27 11:59 UTC
### What is the bug or the crash?

In 3.32.0 is it impossible to resize the dialog in the Layer properties.
This makes it impossible for me to see the buttons OK calcen ect.
![dialog](https://github.com/qgis/QGIS/assets/9905437/56a60319-8492-4f21-894b-9de3e44e9cce)

### Steps to reproduce the issue

..

### Versions

3.32.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment] 2023-06-27 13:28
Duplicate of #43276

**Closed** 2023-06-27 15:29 UTC
Labels: Bug
