### ISSUE TITLE
Subprocess error with ArcGIS Python2.7 executable

### ISSUE THREAD

**Issue by sharon92** [qgis/QGIS#56200] opened 2024-02-06 10:09 UTC
### What is the bug or the crash?

Running python scripts in QGIS Python Console using subprocess with ArcGIS Python2.7 interpreter results in syntax error.

### Steps to reproduce the issue

1. Create a temp.py file with this content: print(123213)
2. Open QGIS Console and ` import os, subprocess`
3. run the following:
`p = subprocess.Popen([r"c:\Python27\ArcGIS10.3\python.exe",r"c:\path\to\tmp.py"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)`

```
p.stderr.read()
b'  File "C:\\PROGRA~1\\QGIS33~1.3\\apps\\Python39\\lib\\site.py", line 178\r\n    file=sys.stderr)\r\n        ^\r\nSyntaxError: invalid syntax\r\n'
```

Running the same command on a Python3.9 interpretor works as expected:
```
c:\Python39>python.exe
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, subprocess
>>> p = subprocess.Popen([r"c:\Python27\ArcGIS10.3\python.exe",r"c:\path\to\tmp.py"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)
>>> p.stdout.read()
b'123213\r\n'
>>> p.stderr.read()
b''
```

### Versions

QGIS-Version
3.34.3-Prizren
QGIS-Codeversion
47373234ac
Qt-Version
5.15.3
Python-Version
3.9.18
GDAL-Version
3.8.3
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
15.2
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
HTML_Generator-main
1.2
profiletool
4.2.6
qgis2web
3.17.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment] 2024-02-06 18:56
Closing. Sorry but making QGIS works with obsolete and unsupported Python 2.7 of ArcGIS is asking us too much ;-)

**Closed by rouault** 2024-02-06 18:56 UTC
Labels: Won't fix

**Comment by sharon92** [comment] 2024-02-06 20:59
@rouault I agree it shouldn't be an important issue to solve. I was hoping that someone could point out some basic info I am missing.
With the obsolete arc gis python I could convert arc map projects to qgis projects and win more people for the ecosystem. 
But if its too deep a hole to dig into I agree it should be left undug.

**Comment by rouault** [comment] 2024-02-06 21:09
I guess the issue here is that the QGIS starter batch file must set PYTHONPATH and/or PYTHONHOME to its Python 3.X version, and if you start Python 2.7 with those variables set, obviously it won't understand Python 3 syntax. So it is more a "this can't be fixed by design of Python3 not being backwards compatible with Python2".
Perhaps try os.environ.del("PYTHONPATH") or os.environ.del("PYTHONHOME") but I'm not positive this will help
