### ISSUE TITLE
Print Composer: Sort attribute table objects by non-displayed fields

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27897] opened 2018-10-10 22:37 UTC
Author Name: **Nick Allen** (@nickballen)
Original Redmine Issue: [20075](https://issues.qgis.org/issues/20075)

Redmine category:map_composer/printing

---
*Short version:* Allow Print Composer attribute tables to be sorted by fields that are not selected for display.

*Long version:* In the Print Composer, the Attribute Table item allows you to select table fields to display in a print map. There is a separate "sorting" section that makes it possible to order your displayed data by any field. However, the sorting section drop-down is restricted to fields that have been selected for display, so it is not possible to sort data by "hidden" fields. It would be nice if this restriction were lifted and any field could be used to sort. 

*Example use case*: The end user scans a map of towns in a left-right order and would want to see a table that corresponds to this intuitive order. However, assigning feature numbers is not necessarily useful to that end user, so you would want to hide the sorting field.

*Illustration*

*Displayed | Map Position | Hidden*
 Art | Middle | 2
 Bob | Right  | 3
 Cat | Left   | 1

In the table above, Print Composer should allow you to sort by the hidden field

**Comment by 3nids** [comment] 2019-11-20 12:30
duplicate of 25671

**Closed by 3nids** 2019-11-20 12:30 UTC
Labels: Feature Request, Print Layouts
