### ISSUE TITLE
crash processing tools on vmware guest windows server (Citrix Master Server)

### ISSUE THREAD

**Issue by vowasemp** [qgis/QGIS#32387] opened 2019-10-24 14:05 UTC
Cannot install QGIS 3.4.12 on VMware-Machine (Windows 2008 Server R2, Citrix Master Server for Deployment of Citrix-Apps). I tried different installers (OSGeo4W, Standalone). QGIS ist starting, then crash and disable the processing tool. After I can use QGis but without processing tools. 
Is it not possible to install QGIS on Windows Server 2008 R2 and deploy as Citrix-App?
In annexe the crash dump
[crash_dump.txt](https://github.com/qgis/QGIS/files/3767922/crash_dump.txt)

**Comment by vowasemp** [comment] 2019-10-25 11:33
I did downgrade to 3.4.8, this version is working. The problem seems to be here:
QgsPythonUtilsImpl::evalString qgspythonutilsimpl.cpp:524
QgsPythonUtilsImpl::loadPlugin qgspythonutilsimpl.cpp:610
QgsPluginRegistry::loadPythonPlugin :
QgsPluginRegistry::restoreSessionPlugins :
QgisApp::QgisApp :

Something has changed since version 3.4.9. I don't understand this code. Does anybody know which could be the problem? version 3.4.12 is running on other Windows Clients without problems, the problem persist on the Citrix Master Server (Windows Server 2008 R2).

**Comment by prusswan** [comment] 2019-10-25 12:06
Possibly related: #32374

**Comment by prusswan** [comment] 2019-10-25 12:12
> Something has changed since version 3.4.9. I don't understand this code. Does anybody know which could be the problem? version 3.4.12 is running on other Windows Clients without problems, the problem persist on the Citrix Master Server (Windows Server 2008 R2).

Need input from one of the devs who worked on this portion. This is likely down to some Windows dependency that changed. Do you know what are the operating systems running on the other Windows Clients?

**Comment by vowasemp** [comment] 2019-10-28 06:46
On Windows 7 and Windows 10 Clients there are no problems, the problem persist on Windows Server 2008 R2 (will soon be upgraded, support ends january 2020)

**Comment by jef-n** [comment] 2019-10-30 14:12
https://github.com/conda-forge/openblas-feedstock/issues/60 suggests that it might be fixed by setting the environment variable `OPENBLAS_CORETYPE` to `nehalem`.

**Comment by prusswan** [comment] 2019-11-06 04:09
> [conda-forge/openblas-feedstock#60](https://github.com/conda-forge/openblas-feedstock/issues/60) suggests that it might be fixed by setting the environment variable `OPENBLAS_CORETYPE` to `nehalem`.

@jef-n can you explain further? This workaround seems to work for #32374 as well

**Comment by jef-n** [comment] 2019-11-06 08:01
> @jef-n can you explain further? This workaround seems to work for #32374 as well

I suspect it's a problem with the virtualization (or CPU detection in openblas) - it probably implies features of the detected CPU that the VM later doesn't provide.  Setting the environment variable circumvents the detection, sets it to `nehalem` as CPU and that matches better the provided features.   But I just found the above information and didn't dig any deeper.

**Comment by jef-n** [comment] 2019-11-06 08:04
Duplicate of #32374

**Closed by jef-n** 2019-11-06 08:04 UTC
Labels: Bug, Build/Install

**Comment by prusswan** [comment] 2019-11-06 09:45
BTW, is there any reason why the numpy errors are not reflected in the crash reports? This may need to be addressed as a separate issue
