### ISSUE TITLE
Ability to set "z" in "advanced digiticer" 

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#31105] opened 2019-08-06 06:08 UTC
**Feature description.**
I would like to be abel to set "z" value when using "advanced digiticer", it would way better than assigning "z" values afterwords.

**Additional context**
Name your price.

**Comment by m-kuhn** [comment] 2019-08-06 08:58
Contact info@opengis.ch we've just estimated that for a part of a (not yet public) crowdfunding.

**Comment by DelazJ** [comment] 2019-10-10 21:56
Duplicate of #29415

**Comment by alexbruy** [comment] 2020-04-22 16:32
Duplicates #25865.

**Closed by alexbruy** 2020-04-22 16:32 UTC
Labels: Feature Request
