### ISSUE TITLE
Removed services from datasourcemanager (WMS/WFS) reappear on next startup

### ISSUE THREAD

**Issue by CasperBertelsen** [qgis/QGIS#56713] opened 2024-03-05 07:10 UTC
### What is the bug or the crash?

When adding a WMS service it appears under connections and qgis in the QGIS3.ini:
[connections]
ows\items\wms\connections\items\CONNECTIONNAME
[qgis]
connections-wms\CONNECTIONNAME
connections\WMS\CONNECTIONNAME

When removing a service, it is removed by the [connections] tag but not the [qgis] tag, here comparing old and new ini-file

![image](https://github.com/qgis/QGIS/assets/17768079/67034399-14b6-4d4a-8e59-560a94a13ee7)
![image](https://github.com/qgis/QGIS/assets/17768079/f3ec4e17-50f1-43be-a76d-2eeeae692b2a)

Removing service:
![image](https://github.com/qgis/QGIS/assets/17768079/0e589b73-6142-42ac-a569-c361ad0dfbf7)

![image](https://github.com/qgis/QGIS/assets/17768079/01efb5dd-c5b0-43b6-acfb-6e67a69dd7ae)

QGIS reopened and service reppears:
![image](https://github.com/qgis/QGIS/assets/17768079/c1ff4e7b-944d-477a-8c44-42eafab30d37)

I have noticed trying to remove several services that sometimes only some reappear.

### Steps to reproduce the issue

New profile
Add service
Close QGIS
Open QGIS
Remove service
Close QGIS
Open QGIS

### Versions

QGIS-version
3.34.4-Prizren
QGIS-koderevision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL klient version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Aktive Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2024-03-05 16:33
@CasperBertelsen, thanks for reporting. The issue has been already previously reported and already allegedly recently fixed. The fix will be available in the upcoming QGIS 3.34.5 and 3.36.1 version.

**Comment by agiudiceandrea** [comment] 2024-03-05 16:37
@CasperBertelsen, thanks for reporting. The issue has been already previously reported and already allegedly recently fixed. The fix will be available in the upcoming QGIS 3.34.5 and 3.36.1 version. Please check if it is actually fixed using the new versions which will be available towards the end of this month.

**Comment by MalikAlMaut** [comment] 2024-04-05 09:48
To add to this:
Whenever QGIS is closed the lines under [qgis] are stored in the file. Opening QGIS removes this lines from the ini; closing adds these lines again. 3.36 does this very quickly, whereas 3.34 takes forever (depending on the amount of stored connections).
One can also save the smaller file and open QGIS using the samller file, but upon closing it, the lines are added again.

**Comment by agiudiceandrea** [comment] 2024-04-05 11:50
@MalikAlMaut, what versions of QGIS are you using exactly?

**Comment by MalikAlMaut** [comment] 2024-04-05 12:11
> @MalikAlMaut, what versions of QGIS are you using exactly?

3.36.1-Maidenhead
3.34.5-Prizren

I don't know if this behaviour is new or wrong, but loading and closing QGIS did never take that long. It takes 3.34 LTR more than five minutes to open and close. 
IThere are almost 500 connections stored, for which QGIS writes and deletes over 8000 lines in the ini file.

**Comment by agiudiceandrea** [comment] 2024-04-05 12:14
@3nids it seems the issue still occurs.

**Comment by 3nids** [comment] 2024-04-10 13:47
I just tested this and cannot replicate.

Could it be that you had 2 QGIS open at the same time?

**Comment by PeterDrexel** [comment] 2024-04-19 14:58
<body>

QGIS-Version | 3.34.5-Prizren | QGIS-Codeversion | 4b308492
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.18
GDAL-Version | 3.8.4
PROJ-Version | 9.3.1
EPSG-Registraturdatenbankversion | v10.098 (2023-11-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.41.1
PDAL-Version | 2.6.0
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
dimensioning | 0.2
mapswipetool_plugin | 1.2
MemoryLayerSaver | 5.0.2
pluginbuilder3 | 3.2.1
PluginLoadTimes | 4.0.2
plugin_reloader | 0.9.4
qfieldsync | v4.9.1
qgis_stac | 1.1.2
quick_map_services | 0.19.34
SpreadsheetLayers | 2.1.2
StreetView | 3.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>

It still occurs here with a newly downloaded QGIS 3.34.5 LTR.
QGIS shrinks the qgis3.ini on start und blows up the filesize again on closing. Both tages ages.


It is fine with 3.36 ...
<body>

QGIS-Version | 3.36.1-Maidenhead | QGIS-Codeversion | 3e589453
-- | -- | -- | --

</body>

and also with 
<body>

QGIS-Version | 3.37.0-Master | QGIS-Codeversion | 220abf7aa9
-- | -- | -- | --


</body>

(both OsGeo4W)

Peter

**Comment by stefan-overkamp** [comment] 2024-04-25 09:37
Same problem with 3.34.6-1 
starting QGIS takes many minutes and ending it takes minutes to stop the process.
I can confirm https://github.com/qgis/QGIS/issues/56713#issuecomment-2039364639 for 3.34.6-1

**Comment by PeterDrexel** [comment] 2024-05-21 11:05
QGIS 3.34.7 on Win10 from today:

First try:
- Opening QGIS still takes ages, Size of QGIS3.ini shrinks from 823 KB to 724 KB, all entries starting with "connections-" are removed.
- Closing QGIS again takes ages, Size of QGIS3.ini grows from 724 KB to 823 KB, all entries starting with "connections-" are added again.

Second try:
- Opening QGIS still takes ages, Size of QGIS3.ini shrinks from 823 KB to 724 KB, all entries starting with "connections-" are removed (same as above).
- Closing (Stopping) QGIS using the **Windows-Taskmananger**: QGIS3.ini stays at 724 KB.
- Reopening QGIS takes only seconds, QGIS3.ini stays at ~ 724 KB.
- Closing QGIS (regulary) again takes ages, Size of QGIS3.ini grows from 724 KB to 823 KB, all entries starting with "connections-" are added again.
- Opening QGIS again takes ages, Size of QGIS3.ini shrinks from 823 KB to 724 KB, all entries starting with "connections-" are removed (same as above).
- ...

QGIS 3.36.3:
- Opening QGIS takes only seconds, Size of QGIS3.ini shrinks from 823 KB to 724 KB, all entries starting with "connections-" are removed.
- Closing QGIS takes only seconds, Size of QGIS3.ini grows from 724 KB to 823 KB, all entries starting with "connections-" are added again.

No idea if this helps someone...
Peter

**Comment by agiudiceandrea** [comment] 2024-05-21 13:56
@3nids, I think the latest comment may help to find the root cause of the issue.

**Comment by 3nids** [comment] 2024-05-21 14:59
Described behavior is totally expected.

As previously wrote I cannot replicate the behavior of the OP. I suspect some older bugged versions of QGIS might have brought back some wrong configurations.

**Comment by 3nids** [comment] 2024-06-11 04:39
I could reproduce the issue and proposed a fix in #57727

**Closed** 2024-06-11 07:35 UTC
Labels: Regression, Bug, Configs and Options
