### ISSUE TITLE
Export to PostgreSQL (available connections) broken

### ISSUE THREAD

**Issue by PhilKnight** [qgis/QGIS#42400] opened 2021-03-23 06:26 UTC
When I try to upload layers to a PostGIS database using the GDAL algorithm 'Export to PostgreSQL (available connections) ' in the Model Builder it fails. I get the message 'FAILURE: Unable to open datasource'. If I try the same process using the GDAL algorithm 'Export to PostgreSQL (new connection)' it works fine with the same connection details. The GDAL commands differ slightly, so perhaps this is the source of the issue:

**'Export to PostgreSQL (available connections) '**

cmd.exe /C ogr2ogr.exe -progress --config PG_USE_COPY YES -f PostgreSQL "PG:\"" dbname='name' host=123.456.78.910 port=1234 user='the_user' password='the_password' sslmode=disable active_schema=public "\"" -lco DIM=2 C:/Users/phil/AppData/Local/Temp/processing_ZZNtSz/a06f967298994af8b0e1bff9036854c1/INPUT.gpkg INPUT -overwrite -nlt MULTIPOLYGON -lco GEOMETRY_NAME=geom -lco FID=id -nln public.test_connection -a_srs EPSG:4326 -nlt PROMOTE_TO_MULTI
GDAL command output:
FAILURE:
Unable to open datasource `dbname='name'' with the following drivers.

**Export to PostgreSQL (new connection)**

cmd.exe /C ogr2ogr.exe -progress --config PG_USE_COPY YES -f PostgreSQL "PG:host=123.456.78.910 port=5432 dbname=name password=the_password active_schema=public user=the_user" -lco DIM=2 C:/Users/phil/AppData/Local/Temp/processing_ZZNtSz/adeb3b9f2cdc412da3bbc42f0fe8da4a/INPUT.gpkg INPUT -overwrite -nlt MULTIPOLYGON -lco GEOMETRY_NAME=geom -lco FID=id -nln public.test_connection -a_srs EPSG:4326 -nlt PROMOTE_TO_MULTI
GDAL command output:
0...10...20...30...40...50...60...70...80...90...100 - done.

**QGIS and OS versions**

QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by gioman** [comment] 2021-03-23 08:26
@PhilKnight does it happen only in the context of the model builder? Or also if you run the tool as standalone one?

**Comment by PhilKnight** [comment] 2021-03-23 09:32
@gioman I checked and the same issue occurs when I run the tool standalone.

**Comment by gioman** [comment] 2021-03-23 12:09
Crap, confirmed also on 3.18 on Linux. Regression.

**Comment by nyalldawson** [comment] 2021-03-23 18:39
@gioman isn't this a duplicate of https://github.com/qgis/QGIS/issues/41839, which was already fixed?

**Comment by gioman** [comment] 2021-03-28 09:10
> @gioman isn't this a duplicate of #41839, which was already fixed?

@nyalldawson yes.

**Closed by gioman** 2021-03-28 09:10 UTC
Labels: Bug, Processing, Regression
