### ISSUE TITLE
Export to dxf crash QGIS 3.18

### ISSUE THREAD

**Issue by ReghardNell** [qgis/QGIS#41858] opened 2021-02-26 10:33 UTC
## User Feedback

Hi 

Just installed 3.18.
Used  export project to DXF.

reinstalled fresh install all gives same result crash.

Kind regards

reghard.nell@gmail.com

## Report Details

**Crash ID**: [4d700434d3e0fb460c9a81b63f4166661261d5f8](https://github.com/qgis/QGIS/search?q=4d700434d3e0fb460c9a81b63f4166661261d5f8&type=Issues)

**Stack Trace**
<pre>
QHash<QModelIndex,QHashDummyValue>::clear qhash.h:591
QgsVectorLayerAndAttributeModel::applyVisibilityPreset qgsdxfexportdialog.cpp:360
QgsDxfExportDialog::mVisibilityPresets_currentIndexChanged qgsdxfexportdialog.cpp:512
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QStandardItemModel::insertRows :
QComboBox::insertItems :
QgsDxfExportDialog::QgsDxfExportDialog qgsdxfexportdialog.cpp:484
QgisApp::dxfExport qgisapp.cpp:7356
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.0-Z�rich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment] 2021-02-26 15:03
Confirmed  on master/linux too.

**Comment by roya0045** [comment] 2021-02-26 17:53
could rootgroup be nullptr somehow? https://github.com/qgis/QGIS/blob/f32725658f205af4ac9718d3a3b74f13eaa98d3e/src/app/qgsdxfexportdialog.cpp#L360

**Comment by sigdeletras** [comment] 2021-02-26 18:11
Hello.
I add more information.
I have tested the functionality from the Process Box and it creates the DXF file.
The problem is that it does not open in AutoCAD 2021.
However, it can be loaded into QGIS.

**Comment by nyalldawson** [comment] 2021-06-03 04:57
This was fixed in https://github.com/qgis/QGIS/pull/41918

**Closed by nyalldawson** 2021-06-03 04:57 UTC
Labels: Bug, Crash/Data Corruption, DXF/DWG, High Priority, Regression
