### ISSUE TITLE
Print Composer doesn't show symbols in legend

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28578] opened 2018-12-09 01:35 UTC
Author Name: **John Payne** (@jcpayne)
Original Redmine Issue: [20758](https://issues.qgis.org/issues/20758)
Affected QGIS version: 3.4.2
Redmine category:map_composer/printing

---
I'm trying to implement a workaround for making a Print Composer legend for a symbol that has two characteristics: size (related to one variable) and color (related to another).  The workaround consists of duplicating the layer and showing the characteristics separately.  

In the attached file, you can see that the symbols for "Number of visitors" show correctly in the Legend "Item Properties" dialog, but they don't appear on the Print Composer legend itself. 

I find the Print Composer extremely frustrating to use, because of its multiple bugs and inconsistencies.  

---

- [Screen Shot 2018-12-08 at 4.19.51 PM.png](https://issues.qgis.org/attachments/download/13926/Screen%20Shot%202018-12-08%20at%204.19.51%20PM.png) (John Payne)

**Comment by Stapawe** [comment] 2020-04-13 10:11
I confirm it works as expected on 2.18.28
Funny on 3.12.1 increase in the size of symbols shifts Item Labels in a legend.
Thank you for your great work and be well

**Comment by gioman** [comment] 2020-04-14 08:54
> I confirm it works as expected on 2.18.28
> Funny on 3.12.1 increase in the size of symbols shifts Item Labels in a legend.
> Thank you for your great work and be well

@Stapawe so it is NOT working as expected on QGIS 3, correct?

**Comment by Stapawe** [comment] 2020-04-14 09:42
Yes, it is not working on 3.12.1 as expected, exactly like in the screenshot from the first post - no symbols in a legend, visible in a widget.

**Comment by CaXalee** [comment] 2020-05-14 08:39
Hi all,

I have the same problem also.

**Comment by iahmedani** [comment] 2020-08-24 12:38
same problem

**Comment by Oceanologue** [comment] 2020-11-27 16:31
Same problem for me, is there any fix ? The High priority label has been removed even though there is no answer.

**Comment by gioman** [comment] 2020-11-27 16:35
> Same problem for me, is there any fix ? The High priority label has been removed even though there is no answer.

@Oceanologue 

https://github.com/qgis/QGIS/issues/39882#issuecomment-723669783

**Comment by gioman** [comment] 2020-11-27 16:40
So this seems a duplicate of https://github.com/qgis/QGIS/issues/19761

https://github.com/qgis/QGIS/pull/39909#issuecomment-725764426

or not

https://github.com/qgis/QGIS/pull/39909#issuecomment-726155460

**Closed** 2021-08-10 13:31 UTC
Labels: Regression, Bug, Print Layouts
