### ISSUE TITLE
Incomplete dropdown list (widget type : relation reference)

### ISSUE THREAD

**Issue by plarinier** [qgis/QGIS#51524] opened 2023-01-20 10:23 UTC
### What is the bug or the crash?

When there are too many values in the table which is in relation, de dropdown list is incomplete.
![image](https://user-images.githubusercontent.com/53785518/213672274-34ab38f6-05df-4357-a5c0-1e7cc65ac3ed.png)
![image](https://user-images.githubusercontent.com/53785518/213672408-dd1f8c82-7bbe-41b3-b9c7-030d7c71a12c.png)

### Steps to reproduce the issue

/

### Versions

3.20.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2023-01-20 10:59
3.20.3 is out-dated. Please try on a currently maintained version 3.22.14 or 3.28.3.
And provide a sample project + data to reproduce.

**Comment by plarinier** [comment] 2023-01-20 14:18
Problem's still there in the v3.28.2.

**Comment by plarinier** [comment] 2023-01-20 14:24
[bug_#51524.zip](https://github.com/qgis/QGIS/files/10467047/bug_.51524.zip)

**Comment by agiudiceandrea** [comment] 2023-01-20 16:40
@plarinier the layers are missing in the provided zip file.

**Comment by m-kuhn** [comment] 2023-01-21 18:43
See also https://github.com/qgis/QGIS/issues/37269

**Comment by agiudiceandrea** [comment] 2023-01-22 01:30
@m-kuhn so this is the same as #37269, isn't it?

**Comment by m-kuhn** [comment] 2023-01-22 07:49
I assume yes

**Comment by agiudiceandrea** [comment] 2023-01-22 09:54
@plarinier thanks for reporting the issue. Anyway it seems you have reported an issue already previously reported at https://github.com/qgis/QGIS/issues/37269 and not yet fixed, so I close this issue report as a duplicate of the previous one. If you think the two issue are different, please add a comment explaining why.

**Closed by agiudiceandrea** 2023-01-22 09:54 UTC
Labels: Feedback, Bug

**Comment by plarinier** [comment] 2023-01-23 07:57
It's clearly the same issue. Thanks for your answers.
