### ISSUE TITLE
QGIS VERY SLOW

### ISSUE THREAD

**Issue by JAVIERSIG** [qgis/QGIS#45365] opened 2021-10-02 12:03 UTC
### What is the bug or the crash?

Hello there;
I have had a problem for a long time that I cannot solve. It is about the slowness to operate with any command in qgis. I'm not talking about very heavy projects, but about the qgis environment itself. When selecting any tool, selecting any layer in the layer panel, and even trying to open a project becomes very slow; I always get the message, Qgis No response (No response). I add that it is not a problem with the performance of the pc, because in the ones I test it, they are quite powerful: 32GB RAM, i7; independent graphics card, ssd etc. I'm talking about laptops. I do not know if it could be due to some update of the windows itself; or that some other software is bothering you; for example, have python, 3.7 and 3.9 installed and running in other apps. I add that the computer where I am looking now is very well configured and with very few packages of other things installed; I mean, pc not overloaded at all. The performances of the same are normal in terms of RAM, processor, etc. I know that it is not a problem of the Qgis itself, but of the whole ,,, but I do not know how to determine where the incompatibility comes from. I have located other people who have the same problem, but at the moment we have been unable to resolve this issue.
I also point out that I have tried several versions, from LTR 3.16 to the current 3.20.
Every time I install a new version ,,, I eliminate the previous one even at the windows level and eliminate any trace of third-party plugins, that is, I leave Qgis "virgin" in all its installation; always persisting the same problem.
What could or could we do? ,,, Do you know something about it? ,,
Best regards

### Steps to reproduce the issue

any sample , because is a general problem

### Versions

alls versions, 3.16, 3.18, 3.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment] 2021-10-02 12:13
@JAVIERSIG this is not really the place where to to post questions, as specified here https://github.com/qgis/QGIS/issues/new/choose

anyway... have you **really** tried with a **new** QGIS profile?

settings > user profiles > new profile

**Comment by JAVIERSIG** [comment] 2021-10-02 12:21
Hello there; yes yes ,,, I think I have tried all possible ways. But the symptom persists. From the default profile itself to a new one. I add that in the two profiles there is no plugin that I have installed. Imagine please ,, that you have loaded only two layers, small, gpkg or shp, it is the same ,,, and now you want to change the order of them, putting one on top of the other ,,, well ,,, with the mouse the you would go to select, and the system no longer leaves you, you have to wait a little bit until it reacts. the QGIS NO RESPONSE message is with whatever you try to do. I persist that I know it is not a Qgis problem ,,, but something that slows it down. On the other hand ,,, where can I report this problem? ,,, you tell me that it is not the right place. If you can tell me where to report it, I appreciate it.
Best Regard

**Comment by gioman** [comment] 2021-10-02 12:24
@JAVIERSIG is very unlikely to be a general issue (imagine if this was a general issue how many such reports would be filed here). but rather a local one. You may want to share you situation here

https://gis.stackexchange.com/

or in the users mailing list:  https://lists.osgeo.org/mailman/listinfo/qgis-user

**Comment by JAVIERSIG** [comment] 2021-10-02 12:46
Thank you very much, I have already included the question where you told me. Yes, you're right, it must be something local, but what? I get the impression that it must be some windows update that has slowed it down. I do not know. I keep investigating. Thanks for your answers. Greetings

**Comment by uclaros** [comment] 2021-10-02 13:40
Do you have the *browser panel* visible? If so, try closing it and see if it's any better. Unreachable network shares caused such delays.

**Comment by JAVIERSIG** [comment] 2021-10-02 16:35
Hello there; Well yes, yes ,,,, I have removed the browser panel, and this is going as it should. Indeed ,,, at the moment it works very agile for me. I activate it again and the problem appears. Wow!!!; It will be necessary to investigate if it is the panel itself, or any of the elements that are inside. Thank you very much ,,, at least we are getting closer to the problem. I'm going to ask someone on the web who told me the same thing happened to him, to see if he can solve it anyway.
Thank you very much again.
Best regards

**Comment by gioman** [comment] 2021-10-02 16:41
Closing as duplicate of https://github.com/qgis/QGIS/issues/37324 and of several other similar reports.

**Closed by gioman** 2021-10-02 16:41 UTC
Labels: Feedback, Bug

**Comment by hectorsampi** [comment] 2022-01-07 08:56
yeah. I had the same problem and this was the solution. Thanks!!

**Comment by UMEOmilieuadvies** [comment] 2022-08-01 09:29
I had the same problem. Deleting inactive and reactivate networkconnections was the solution. great help!
