### ISSUE TITLE
QgsPointCloudAttributeComboBox Entry Point Not Found 

### ISSUE THREAD

**Issue by jkariukidev** [qgis/QGIS#42016] opened 2021-03-03 23:13 UTC
I have installed QGIS3..18 using the Network Installer downloaded from QGIS Download Page. The OS used in is Windows 10 (64bit)  20H2 and on running QGIS from osgeo4w shell an error message pops up as shown below.

![image](https://user-images.githubusercontent.com/23359514/109884851-b4799800-7c8e-11eb-9f40-8a6b4d697bc7.png)

And on clicking OK button further shows another common error message as shown below.

![image](https://user-images.githubusercontent.com/23359514/109884970-dbd06500-7c8e-11eb-92e2-f46563ad99b2.png)

Does this have to do with the new QGIS Point Cloud feature and how can I fix it?

**Comment by gioman** [comment] 2021-03-04 10:40
Duplicate of https://github.com/qgis/QGIS/issues/41740

**Closed** 2021-03-04 10:40 UTC
Labels: Bug
