### ISSUE TITLE
QGIS crash when using vrt with python pixel function

### ISSUE THREAD

**Issue by fiedt** [qgis/QGIS#39962] opened 2020-11-11 14:05 UTC
Hi,
i have the following problem and couldn't find a solution:

**Describe the bug**
QGIS crash when accessing a vrt-file with python pixel function.

**How to Reproduce**
1. set GDAL_VRT_ENABLE_PYTHON=YES in the QGIS settings
2. reload QGIS
3. add vrt to project
4. QGIS crashes

**QGIS and OS versions**

QGIS-Version | 3.16.0-Hannover | QGIS-Codeversion | 43b64b13f3
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

**Additional context**
The vrt-python function uses numpy.

Accessing the vrt-file with gdal_translate from the OSGEO4W-shell return a numpy ImportError.
But when py3_env is run before, gdal_translate works.

**Comment by gioman** [comment] 2020-11-11 18:13
> set GDAL_VRT_ENABLE_PYTHON=YES in the QGIS settings

@gioman in settings > system > environment, correct?

If yes then I cannot confirm (win 10 and Linux).

**Comment by fiedt** [comment] 2020-11-12 06:57
> 
> 
> > set GDAL_VRT_ENABLE_PYTHON=YES in the QGIS settings
> 
> @gioman in settings > system > environment, correct?
> 
> If yes then I cannot confirm (win 10 and Linux).

Yes, set up in settings > system > environment with the option 'if defined' in the drop-down menu.

**Comment by luipir** [comment] 2020-11-12 08:15
not confirmed in master (if it can be useful)

QGIS version | 3.17.0-Master | QGIS code revision | 6711edbd7c
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: 829bf4)
PostgreSQL Client Version | 13.0 (Ubuntu 13.0-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager

**Comment by gioman** [comment] 2020-11-12 11:50
> Yes, set up in settings > system > environment with the option 'if defined' in the drop-down menu.

@fiedt please attach data we can use to try replicate.

**Comment by fiedt** [comment] 2020-11-12 14:28
> 
> 
> > set GDAL_VRT_ENABLE_PYTHON=YES in the QGIS settings
> 
> @gioman in settings > system > environment, correct?
> 
> If yes then I cannot confirm (win 10 and Linux).

Yes, set up in settings > system > environment with the option 'if defined' in the drop-down menu.

> 
> 
> > Yes, set up in settings > system > environment with the option 'if defined' in the drop-down menu.
> 
> @fiedt please attach data we can use to try replicate.

I'm trying to generate some test data

**Comment by fiedt** [comment] 2020-11-16 09:17
> @fiedt please attach data we can use to try replicate.

@gioman here are some data. The ndvi.vrt works in older QGIS versions, but not in the 3.16 version. The stack.vrt works in all tested QGIS versions.

[vrt_dataset.zip](https://github.com/qgis/QGIS/files/5545250/vrt_dataset.zip)

**Comment by gioman** [comment] 2020-11-16 16:57
> @gioman here are some data. The ndvi.vrt works in older QGIS versions, but not in the 3.16 version. The stack.vrt works in all tested QGIS versions.

@fiedt carsh confirmed with the provided dataset and the described config.

**Comment by AndreasRabe** [comment] 2020-11-23 08:38
I have the same problem with VRTs using pixel functions. Crashes in QGIS 3.16 (Win10). Here is my minimal example, maybe it helps:


```
<VRTDataset rasterXSize="100" rasterYSize="100">
  <VRTRasterBand dataType="Int16" band="1" subClass="VRTDerivedRasterBand">
    <PixelFunctionLanguage>Python</PixelFunctionLanguage>
    <PixelFunctionType>zeros</PixelFunctionType>
    <PixelFunctionCode>
      <![CDATA[
def zeros(in_ar, out_ar, xoff, yoff, xsize, ysize, raster_xsize, raster_ysize, buf_radius, gt, **kwargs):
    out_ar *= 0
]]>
    </PixelFunctionCode>
  </VRTRasterBand>
</VRTDataset>
```

**Comment by rouault** [comment] 2021-01-31 12:54
Duplicate of #41048

**Closed by rouault** 2021-01-31 12:54 UTC
Labels: Bug, Crash/Data Corruption, High Priority, Regression
