### ISSUE TITLE
Temporal controller widget sets a wrong frame as animation start point.

### ISSUE THREAD

**Issue by Samweli** [qgis/QGIS#40868] opened 2021-01-06 09:13 UTC
During editing the animation temporal range start in the temporal controller widget, the animation start frame is incorrectly set to a randomly selected(at least from my findings) frame. This happens on QGIS master only.

Expected behaviour
![temporal_controller_expected_behaviour](https://user-images.githubusercontent.com/2663775/103750820-63478200-5018-11eb-9471-fe3be956ea62.gif)

Current behaviour
![temporal_controller_issue](https://user-images.githubusercontent.com/2663775/103750883-79edd900-5018-11eb-8095-4e0c2318eda0.gif)

**Comment by Samweli** [comment] 2021-01-11 06:55
Hi @rduivenvoorde, I now wonder if this is an issue or the expected behavior from the finding best frame logic?

**Comment by rduivenvoorde** [comment] 2021-01-12 10:40
@Samweli I cannot exactly see what you are doing in the screencasts. But to me the 'finding best frame' (when switching units) seems to be ok again. 
The most important thing to note, is that (I think) in the 'Frame:....' text the start should stay the same, OR go one step back in case you for example go from minutes 1:30 to hours: should go to 1:00 then (I think)...
The issue with having the slider to to the end I do not see anymore?
If you still see the issue, please describe the steps. Else: let's close it.

**Comment by Samweli** [comment] 2021-01-12 12:42
> The issue with having the slider to to the end I do not see anymore?

For me, it now only happens when using the Temporal controller for the first time after restarting QGIS.

> If you still see the issue, please describe the steps. Else: let's close it.

1 . Open QGIS for first time.
2.  Enable "Animated temporal navigation" . This should show the Temporal controller widget with the temporal extents having exactly the same start and end range.
3.  Edit start range of the temporal extents to an earlier date than of the end range.  The slider will go to the end!.

@rduivenvoorde do you confirm this?

**Comment by rduivenvoorde** [comment] 2021-01-12 12:49
Ah, I see what you mean now.
But I think that is expected behaviour.
As the start timeframe (in my case now): 2021-01-12 00:00:00 - 2021-01-12 00:00:00 
So START==2021-01-12 00:00:00
Now if you try to change the starting point (or the end point of the Range), the guide will try to stick to the old starting point.
Which in this case IS 2021-01-12 00:00:00
So although maybe not intuitive, I think it does what it should do?

**Comment by Samweli** [comment] 2021-01-12 12:58
> So although maybe not intuitive, I think it does what it should do?

Right it works exactly as expected, but I think the issue here is intuition as you have pointed out, as Users probably won't understand why it has skipped to the end while they are just starting to use the Temporal Controller.

**Comment by rduivenvoorde** [comment] 2021-01-12 13:04
But I think that is because it start's with an (what I call "invalid range": being one of zero length) IF we would start with a range of 1 hour (as also the steptime etc defaults to 1 hour) then (I think) this will be a little more intuitive?

**Comment by nyalldawson** [comment] 2021-06-10 00:46
Fix in https://github.com/qgis/QGIS/pull/43660

**Closed** 2021-06-14 03:08 UTC
Labels: Bug, Temporal
