### ISSUE TITLE
BUG WHEN IMPORTING ZIPPED GML FILES: 

### ISSUE THREAD

**Issue by infokartasplit** [qgis/QGIS#49284] opened 2022-07-08 10:58 UTC
### What is the bug or the crash?

BUG WHEN IMPORTING ZIPPED GML FILES
when importing gml layer with geometry, it doesnt import **features** of that layer dont have assigned geometry (some features have geometry some dont)

### Steps to reproduce the issue

File example
[BRELA OSS 2022-0761267 202207051531 - SPP.zip](https://github.com/qgis/QGIS/files/9071393/BRELA.OSS.2022-0761267.202207051531.-.SPP.zip)

When drag and dropping file into qgis **3.26** dialog opens: 
![image](https://user-images.githubusercontent.com/79648611/177978128-b4f88255-d278-42da-9675-d651a73c0f31.png)
Layer NACINI UPORABE has 205 Polygons, and the rest of features are without geometry. when i open it imported layer only has 205 features.

When drag and dropping file into qgis **3.18** dialog opens: 
![image](https://user-images.githubusercontent.com/79648611/177978472-c64438ab-c396-4f59-83be-c180c35bfffd.png)
it loads 3237 features (it shows all features but only 205 have geometry)

**Newer version should also load all 3237 features regardlesly if they have geometry or not. If someone doesn't want features without geometry they can use processing toolbox to filter features with no geometry. 

That way i don't loose data about features with no geometry.**

### Versions

3.18 works fine
3.22 , 3.26 don't work fine

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2022-09-22 10:46
The file you attached loads all 3237 features fine on current master on linux.

Please try with a new profile in order to rule out some rogue plugin.
If the issue persists, paste here your detailed version info
>  Versions
>
> In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here.
> Do not make a screenshot.

**Comment by rouault** [comment] 2022-09-23 13:59
Was fixed just a few days ago per https://github.com/qgis/QGIS/pull/50231
Duplicate of https://github.com/qgis/QGIS/issues/50215

**Closed by rouault** 2022-09-23 13:59 UTC
Labels: Feedback, Regression, Bug, Vectors, Crash/Data Corruption
