### ISSUE TITLE
QGIS crashes when "open directory" is selected from the recent projects contextual menu

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31630] opened 2019-09-09 11:02 UTC
## User Feedback

I open QGIS: no project, no layer loaded
I right-clicked on a recent project and chose to open its directory --> Kaboum

I tried to reproduce and succeeded many times. I got 2-3 crashes with load qgis, right-click --> "Open directory" on different valid projects (btw the folder always opened). Then I tried other options in the contextual menu and failed to have the crash. After some reloads and trials I again got a crash but with another ID [b2e8752cd39468b3be83e51f1c34e92bfdd48cc3](https://github.com/qgis/QGIS/search?q=b2e8752cd39468b3be83e51f1c34e92bfdd48cc3&type=Issues)

Not sure this report would be of any help but... Sorry if it does not help.
Question or bug (to file)?: I used to have a stack trace (i don't know if it was useful) and now I can see I have nothing generated. I don't know why and do not understand what "missing symbols" means nor what I could do to enable it. I have changed nothing in my update process. So I think it could be nice to have more details for testers that are not developers or enable these symbols in testing for us.

## Report Details

**Crash ID**: [58b3dcd0ef8f854269f6e54f486e4d541d3baf5a](https://github.com/qgis/QGIS/search?q=58b3dcd0ef8f854269f6e54f486e4d541d3baf5a&type=Issues)

**Stack Trace**
Stack trace could not be generated due to missing symbols.

**QGIS Info**
QGIS Version: 3.9.0-Master
QGIS code revision: 1b65427fdf
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment] 2019-09-09 11:08
I love the absence of an invalid stack trace, good job @NathanW2 .

That said, could you teach @DelajZ on how to install relevant packages? It'll be an interesting experiment.

**Comment by DelazJ** [comment] 2019-09-09 13:09
OK. There is enough information in your message @nirvn ;). I found the qgis-dev-pdb package in osgeo4w which from my understanding should install debugging symbols. 420 Mo? Anyways, I tried to install but i'm stuck at 19% for tens of minutes now.

**Comment by jef-n** [comment] 2019-09-09 14:07
The latest nightlies should also fetch the symbols from the osgeo4w symbol store (see f78c95cd9 ff)

**Comment by DelazJ** [comment] 2019-09-09 14:15
@jef-n In my case, does it mean that installing qgis-dev (maybe next build) is enough or should I also tick qgis-dev-pdb ?

**Comment by jef-n** [comment] 2019-09-09 14:25
@DelazJ oh right, the qgis-dev that is currently building - should be done rsn (qgis-rel-dev, qgis-ltr-dev are finished for x86 and x86_64 - build just finished a minute ago and it's now uploading)

**Comment by nirvn** [comment] 2019-09-15 09:03
@DelazJ , any luck getting the debug symbols installed to provide a stack trace?

**Comment by DelazJ** [comment] 2019-09-16 08:18
@nirvn Is it this?

## Report Details

**Crash ID**: [33c82919f1c9355f00a4e1425866f24893de4499](https://github.com/qgis/QGIS/search?q=33c82919f1c9355f00a4e1425866f24893de4499&type=Issues)


**Stack Trace**
<pre>
QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsPageSize::operator== :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsMapToolRotateFeature::applyRotation :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.9.0-Master
QGIS code revision: 970e42b7f7
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by nirvn** [comment] 2019-09-16 08:21
Hmm, it should come with source file name and line nb after the called function. For e.g.

QgsMapToolRotateFeature::applyRotation : qgsmaptoolrotatefeature.cpp, 168

**Comment by DelazJ** [comment] 2019-09-16 08:28
You mean there's no symbols in my report?
From what I understood in @jef-n [comment](https://github.com/qgis/QGIS/issues/31630#issuecomment-529500386), updated qgis-dev (as I have) should be enough to get the symbols, so I did not install the pdb one (which was anyways failing to download/install(?) at the time I tried).

**Comment by nirvn** [comment] 2019-09-16 08:29
Oh no, no, you need to install the ~459nb debug symbol package too. I was able to successfully download this package late last week, should be fine now.

**Comment by nirvn** [comment] 2019-09-16 08:30
@NathanW2 , why is @DelazJ seeing a stack trace if he hasn't installed the debug symbol package?

**Comment by DelazJ** [comment] 2019-09-16 08:32
> Oh no, no, you need to install the ~450mb debug symbol package too. I was able to successfully download this package late last week, should be fine now.

OK, will try later. osgeo4w is currently down and I failed to update nightlies today, even with all the mirrors.

**Comment by DelazJ** [comment] 2019-09-16 16:52
## User Feedback

yeah, man! Got another ID but have some line numbers

## Report Details

**Crash ID**: [9567d678146b1fed3b159b6dd8d94708ed3c46cd](https://github.com/qgis/QGIS/search?q=9567d678146b1fed3b159b6dd8d94708ed3c46cd&type=Issues)


**Stack Trace**
<pre>
QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:417
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1578
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.9.0-Master
QGIS code revision: 393e623ba7
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by bellanz80** [comment] 2019-11-09 02:40
I confirm bug. 
QGIS 3.10 Qindows 10 64 bit
![image](https://user-images.githubusercontent.com/38449926/68521561-f4319a80-0267-11ea-94a4-644681f60731.png)

**Comment by lbartoletti** [comment] 2020-02-20 13:28
confirmed too by @kandre 
But I can reproduce it on windows :/ and also with a "non verbose" report

**Comment by lbartoletti** [comment] 2020-02-20 13:44
confirmed on 3.10 and not 3.4 so it's a regression

**Comment by lbartoletti** [comment] 2020-02-20 14:43
FYI, if ( the project exists and ) the folder, where the project is stored, is already open. QGIS doesn't crash

**Comment by ponceta** [comment] 2020-03-26 07:04
Reproduced on QGIS 3.10.3, happens to be fixed on QGIS 3.12.X and newer.

**Comment by ponceta** [comment] 2020-03-26 07:08
Happens on the second right clic interaction on both versions, maybe unstable functionnality. You know your QGIS will crash when you see the loading icon on your cursor.

**Comment by rouault** [comment] 2020-05-26 11:01
If the people affected by this issue and able to build from git could give a try at https://github.com/qgis/QGIS/pull/36738 and report if that helps...

**Comment by bellanz80** [comment] 2020-05-26 15:51
QGIS 3.12.3
Windows 10 64 bit
Same problem
Video insert

[2020-05-26_10h49_48.zip](https://github.com/qgis/QGIS/files/4683371/2020-05-26_10h49_48.zip)

**Comment by gioman** [comment] 2020-05-26 15:54
> QGIS 3.12.3

@bellanz80 to test the patch/fix you must compile this branch https://github.com/rouault/QGIS/tree/fix_31630

**Closed** 2020-05-26 22:17 UTC
Labels: Bug, Crash/Data Corruption, Regression

**Comment by pigreco** [comment] 2020-12-18 19:32
the problem is present in 3.16.1

Crash ID: 5b7d7853716001199e29628e91df8bb8e06ddcdd


Stack Trace


QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by ponceta** [comment] 2021-05-27 05:40
Still crashing on QGIS 3.16.7

Crash ID: 2d95df17a8cc27dff9b7ac412f949b6d07a3c06c

Stack Trace

QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.7-Hannover
QGIS code revision: 0471743889
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

Workaround, load the project, go to project settings, find project folder. 

Sometimes crashes only at the second occurence of right click open folder.
