### ISSUE TITLE
Selecting multiple features to change colour transparency only works on one item.  

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#33732] opened 2020-01-10 18:23 UTC
**Describe the bug**
I have selected features by colour both red and green separately to change the transparency from 50% to 75% . It only changed the middle item only

**How to Reproduce**
![439c755e18ab92e31a104c1bd64ae0c6](https://user-images.githubusercontent.com/54211372/72176289-5196b480-339b-11ea-8fdf-d8dffbd2be17.png)
Arrange Features as follows, ten select by pressing shift key all the features with the same colour. Go to the properties screen and change transparency to effect all in multiple selection. ONly one in the selection changes to the right transparancy.

**QGIS and OS versions**

The current released version of QGIS is 3.10.1. 
We are working on 3.11-Master. It will go into feature freeze on 2020-01-17 12:00:00 UTC and be released as 3.12 on 2020-02-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 
**Additional context**

**Comment by gioman** [comment] 2020-01-12 12:02
@MPN-stack trying to understand here... but I'm not sure if I do.

Do a whatever categorized symbology > in the layer properties, symbology tabm select multiple symbology classes (with shift) > right click the mouse > change opacity > select a whatever opacity level and confirm with ok button > done.

**Comment by MPN-stack** [comment] 2020-01-16 11:24
@geoman it is not doing this  with multiple items  to set layer property symbology to change opacity  it just changes one of them , hope this helps.

**Comment by gioman** [comment] 2020-01-16 12:02
@MPN-stack sorry no, is not clear at all. Please use something like https://screencast-o-matic.com/ to record your screen and show what do you mean.

**Comment by roya0045** [comment] 2020-01-16 16:13
@gioman basically when he selects multiple categories or layers, he go in the property tab of one layer, changes the transparency and wished that it applied to all selected layers instead of the one.

**Comment by roya0045** [comment] 2020-01-16 16:13
Not a bug, basically.

**Comment by alexbruy** [comment] 2020-04-19 14:16
Closing as won't fix.

**Closed by alexbruy** 2020-04-19 14:16 UTC
Labels: Bug, Feedback
