### ISSUE TITLE
Label masks and bloated PDF exports

### ISSUE THREAD

**Issue by gregseitz360** [qgis/QGIS#51054] opened 2022-11-29 14:42 UTC
### What is the bug or the crash?

In QGIS 3.28, when I have label masks implemented and export a print layout as a PDF, the file size becomes 10-20 times larger than if I do the same thing in 3.22. 

I have maps with contour lines, highways, and other line features. I have other points near those lines that are labeled for layout, and use label masks to make them readable over the line features. When I export one of these maps as a PDF in QGIS 3.22, the file size might be 5-10 MBs. When I export it in QGIS 3.28, the file is at least 100 MBs.

### Steps to reproduce the issue

1. Create layer with points and labels (can also work with labels on other types of geometry)
2. Add label mask to new layer
3. Set mask on other layers
4. Create new Print Layout
5. Export as PDF

### Versions

QGIS 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment] 2022-11-29 14:49
Related #50543, not exactly the same issue, see my [comment](https://github.com/qgis/QGIS/issues/50543#issuecomment-1329350009)

**Comment by gregseitz360** [comment] 2022-11-29 14:56
> Related #50543, not exactly the same issue, see my [comment](https://github.com/qgis/QGIS/issues/50543#issuecomment-1329350009)

Thanks, definitely seems like essentially the same issue. Sorry I didn't see that one before reporting.

**Comment by troopa81** [comment] 2022-11-29 16:30
> Thanks, definitely seems like essentially the same issue. Sorry I didn't see that one before reporting

Thank you for reporting, and I'll try to fix this when I find a proper way. 

I close it because It's a duplicate of https://github.com/qgis/QGIS/issues/50543

**Closed by troopa81** 2022-11-29 16:30 UTC
Labels: Bug
