### ISSUE TITLE
QGIS freezes when changing graduated symbology mode to "fixed interval"

### ISSUE THREAD

**Issue by fmeier1995** [qgis/QGIS#52144] opened 2023-03-08 07:28 UTC
### What is the bug or the crash?

When I try to make a graduated symbology for a vector layer and use "fixed interval" (or change to this method after first use another), QGIS freezes.
I think this happens because the default interval size is "1" and I try to use an attribute with the population for the german states. With the default interval size there would be over 17 million classes, no wonder QGIS can't handle this.
If I try to use the ID-attribute (with numbers from 1 to 16), there is no problem.

The default interval size maybe shoud be dynamic e.g. "(Maximum - Minimum) / 5"?

### Steps to reproduce the issue

1. Load any vector data with an attribute with numbers (with big differences)
2. Change the symbology to Graduated and try the mode fixed interval with this attribute

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.4-Firenze | QGIS code revision | fd0fb72ab3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2023-03-08 07:35
Duplicate of #49333

**Closed by uclaros** 2023-03-08 07:35 UTC
Labels: Bug
