### ISSUE TITLE
Warning message: SAGA version 7.8.2 is not officially supported - algorithms may encounter issues

### ISSUE THREAD

**Issue by osgeokr** [qgis/QGIS#46837] opened 2022-01-14 17:42 UTC
### What is the bug or the crash?

I'm using both QGIS 3.16.14 and QGIS 3.22.2. Whenever I run the SAGA tool, I get the following warning message: SAGA version 7.8.2 is not officially supported - algorithms may encounter issues. How can I disable this message?

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/52292818/149560148-663aa41c-d99d-45ab-b5dd-b1d7829d8cf9.png)

### Versions

QGIS version
3.22.2-Białowieża
QGIS code revision
1601ec46d0
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
cartogram3
3.1.1
GroupStats
2.2.5
openlayers_plugin
2.0.0
pointsamplingtool
0.5.3
qgisgbifapi
0.3.2
QNEAT3
1.0.4
SRTM-Downloader
3.1.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

QGIS version
3.16.14-Hannover
QGIS code revision
42791986
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
cartogram3; 
GroupStats; 
openlayers_plugin; 
pointsamplingtool; 
qgisgbifapi; 
QNEAT3; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2022-01-14 18:23
That's not a bug, that's intended.

**Comment by roya0045** [comment] 2022-01-14 18:28
You can try the plugin or remove that version of saga to ensure a supported version is picked, see #33253 and #36800  for some context.

**Comment by agiudiceandrea** [comment] 2022-01-14 20:38
@osgeokr if you understand the meaning of the warning and you really don't like it to be displayed, then you can disable it modifying the following lines of the file SagaAlgorithmProvider.py (in your install_dir/apps/qgis/python/plugins/sagaprovider/ folder)

https://github.com/qgis/QGIS/blob/1601ec46d06e82d953384b541a6004d975cedc57/python/plugins/sagaprovider/SagaAlgorithmProvider.py#L85-L89

```python
    def warningMessage(self):
        #version = SagaUtils.getInstalledVersion(True)
        #if version is not None and version.startswith(BETA_SUPPORT_VERSION):
        #    return self.tr('SAGA version {} is not officially supported - algorithms may encounter issues').format(version)
        return ''
```

**Comment by gioman** [comment] 2022-01-14 21:24
> then you can disable it modifying the following lines of the file SagaAlgorithmProvider.py (

@agiudiceandrea we should remove the warning anyway. The main reason it was added it was when osgeo4w and major linux releases shipped SAGA 2.*. Isn't the case anymore.

**Comment by nyalldawson** [comment] 2022-01-15 03:42
@gioman except it still **isn't** officially supported .. all the description files still relate to 2.x only.

**Comment by agiudiceandrea** [comment] 2022-01-15 06:45
@nyalldawson, QGIS installed via OSGeo4W v2 uses the SAGA provider description files automatically generated by the installed SAGA-GIS 7.8.2 tool "QGIS Tool Interface Generator" (dev_tool 7) and not the ones for SAGA-GIS 2.x:
https://github.com/jef-n/OSGeo4W/blob/426e992b71ae7cc44c427e255b77d15776cc355c/src/qgis/osgeo4w/package.sh#L233-L262

**Comment by nyalldawson** [comment] 2022-01-15 06:47
@agiudiceandrea 

Osgeo4w is patching this downstream, so should also be patching out the warnings

Upstream (here) only supports 2 as of right now.

**Comment by agiudiceandrea** [comment] 2022-01-15 07:08
So, this issue should be better reported in the OSGeo4W [tickets system](https://trac.osgeo.org/osgeo4w/) and addressed by the [OSGeo4W v2 repository](https://github.com/jef-n/OSGeo4W/).

**Comment by gioman** [comment] 2022-01-19 16:28
> Osgeo4w is patching this downstream, so should also be patching out the warnings
> 
> Upstream (here) only supports 2 as of right now.

@nyalldawson @agiudiceandrea @alexbruy  and this is creating some confusion... We are still far away from having SAGA move out of QGIS and live as its own plugin, and I think we should improve the situation and I'm willingly to do something about it. The description files that are taken from the SAGA project are better than the core ones, because they support SAGA 7, but they are not 100% ok (several tools needs to be split because there are parameters that cannot be provided at the same time). Nyall and AlexB plugins have better description files, but I think they also need some correction. For the time being would be ok to take the best of both sides and use them upstream (here) for the time being? I understand is less than ideal, but still better than we have now. We then could remove the warning and have the same description files on all platforms.

**Comment by nyalldawson** [comment] 2022-01-20 23:33
Honestly, at this stage I'm completely done with the SAGA provider and trying to manage this situation. @gioman if you feel it's the right decision to update the description files in QGIS master to the 7.x ones then I won't object. :+1:

**Comment by ARTCON2020** [comment] 2022-03-25 11:01
Still the same warning appears from SAGA cor
![QGIS3 22 5](https://user-images.githubusercontent.com/72500978/160108974-f5381991-ec7c-4824-91b4-b3baff73225e.PNG)
e

**Comment by ARTCON2020** [comment] 2022-03-25 12:09
![Saga Core](https://user-images.githubusercontent.com/72500978/160118202-c91a6ddf-8c37-4a1a-a03c-c62fbf9c3267.PNG)

**Comment by mteora** [comment] 2022-05-20 15:59
Hi there!

I have the same problem with SAGA plugin in both versions, ltr 3.22 and 3.24. 

The issue started when I still had 3.16 version. The plugin wasn't running so I had installed SAGA NEXT GEN, which is running pretty well.

Have there any people who have solved the problem?

**Comment by agiudiceandrea** [comment] 2022-05-23 09:28
@mteora, what issue do you have exactly? You only don't like the warning message to be displayed? If so, then you can follow the advise in my previous comment https://github.com/qgis/QGIS/issues/46837#issuecomment-1013458152

**Comment by diegoerp91** [comment] 2022-07-09 04:58
> Hi there!
> 
> I have the same problem with SAGA plugin in both versions, ltr 3.22 and 3.24.
> 
> The issue started when I still had 3.16 version. The plugin wasn't running so I had installed SAGA NEXT GEN, which is running pretty well.
> 
> Have there any people who have solved the problem?

@mteora  please what version of saga did you install?

**Comment by agiudiceandrea** [comment] 2022-07-09 07:31
@diegoerp91, there is no need to manually install SAGA-GIS from SourceForge. If your SO is Windows and you are installing QGIS using the official OSGeo4W Standalone/Network installers, then SAGA-GIS is already automatically installed and available in QGIS.

**Comment by mteora** [comment] 2022-07-09 10:16
@agiudiceandrea My installations are from OSGeo4W. I have uninstalled several times, even deleting registry to do a clean install of the different versions of QGIS in two different computers and I still have the same problem in both of them.

@diegoerp91 I'm not solve the problem with SAGA but there are other complement named SAGA NEXT GEN which have been developed for North Road. This has worked pretty well for me in both of my computers (laptop and pc).

I provided you some links. 
https://github.com/north-road/qgis-processing-saga-nextgen
https://plugins.qgis.org/plugins/processing_saga_nextgen/
https://youtu.be/VKdaripCups

I hope this will be useful for all of you.

**Comment by alexbruy** [comment] 2022-11-10 07:40
SAGA Provider was not maintained and now remowed from QGIS (see #50834). Users are encouraged to use the 3rd-party plugins instead.

**Closed by alexbruy** 2022-11-10 07:40 UTC
Labels: Bug

**Comment by Andares92** [comment] 2024-03-13 15:47
Tengo un problema similar y no se como solucionarlo:
estoy haciendo un análisis de flujo de cuencas, utilizo la herramienta 
análisis de terrero, canales y orden de corrientes
me dice que la versión no es oficialmente soportada
SAGA V8
Ggis 3.28.10
