### ISSUE TITLE
Layer Styling Labelling panel does not update when the current layer style is switched

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#42310] opened 2021-03-18 12:44 UTC
**Describe the bug**
The Layer Styling Labelling panel does not update when the current layer style is switched, breaking the style switch to and the relationship of undo/redo operations.

**How to Reproduce**

1. Have a map and have the layer styling panel open (e. g. "world" layer in default styling, no labels)
2. Rename the current style to "1"
3. Add a style, name it "2", style it differently (e. g. "world" layer categorized by fid)
4. You can switch between them, change style, undo styling. Everything is fine.
5. Switch to style "2"
6. Switch to labelling in the Layer Styling panel
7. Set a label (e. g. by NAME)
8. Switch back to style "1"
9. ->

- The Layer Styling panel stays on the label options of style "2".
- Undo/redo buttons now apply the operations of style "2" to style "1".
- **The user loses their style** unless they save and reload the project without any further interaction with the Layer Styling panel.

**QGIS and OS versions**

QGIS version | 3.18.0-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.35.0 | Running against SQLite | 3.35.1
PostgreSQL Client Version | 13.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.6 | QScintilla2 Version | 2.12.1
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Arch Linux

**Comment by roya0045** [comment] 2021-03-18 17:06
Possible duplicate of #40467

**Comment by kannes** [comment] 2021-04-03 09:32
Still happening in 3.18.1.

**Comment by gioman** [comment] 2021-04-03 19:17
> Still happening in 3.18.1.

@kannes is a duplicate of #40467 ?

**Comment by kannes** [comment] 2021-04-04 13:08
It sounds like it is at least very closely related but I do not know the internals of those dialogs. For a developer it would make sense to work on both at once I think.

**Closed** 2021-05-22 01:50 UTC
Labels: Bug, Labeling, Symbology
