### ISSUE TITLE
versions 3.16 and 3.17 does not handle geotiff

### ISSUE THREAD

**Issue by mikhailtchernychev** [qgis/QGIS#39808] opened 2020-11-04 16:49 UTC
I have geotiff files, including one saved from QGIS, which exhibit the following:

- add raster layer - works fine.
- double-click on the layer, QGIS crashes.

Running Ubuntu 18.04
Thank you
Mikhail

[martinez_saved.zip](https://github.com/qgis/QGIS/files/5489230/martinez_saved.zip)

**Comment by gioman** [comment] 2020-11-04 16:58
duplicate of https://github.com/qgis/QGIS/issues/39628 and several other recent identical reports.

**Closed by gioman** 2020-11-04 16:58 UTC
Labels: Bug
