### ISSUE TITLE
Moving a panel over another in dual-screen workspace crashes the app

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29928] opened 2019-05-21 14:27 UTC
Author Name: **Piotr Kann** (Piotr Kann)
Original Redmine Issue: [22115](https://issues.qgis.org/issues/22115)
Affected QGIS version: 3.6.3
Redmine category:gui

---
## User Feedback

Just moved "Processing Toolbox" panel to my secondary monitor over another qgis window (a secondary map view window, titled "Map 2"). In the past, the same manipulation (moving a panel over another map window) multiple times caused malfunctioning of the underlaying map window. In general, I had issues with dual-screen workspace until 3.6.3 update (panel layot not properly restored on restart). 

## Report Details

*Crash ID*: c70bcf49e222b2470b89d20dfcc1859a8db5250b

*Stack Trace*
```
QLayout::removeWidget :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QObjectPrivate::setParent_helper :
QWidgetPrivate::setParent_sys :
QWidget::setParent :
QWidget::setParent :
QTabBarPrivate::isAnimated :
QOpenGLWidget::context :
QOpenGLWidget::context :
QMetaObject::activate :
QUnifiedTimer::setSlowdownFactor :
QAbstractAnimation::setCurrentTime :
QUnifiedTimer::updateAnimationTimers :
QUnifiedTimer::updateAnimationTimers :
QAnimationDriver::advance :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
SetWindowTextW :
IsDialogMessageW :
KiUserCallbackDispatcher :
IsDialogMessageW :
IsDialogMessageW :
SetWindowTextW :
DrawThemeParentBackground :
Ordinal69 :
GetWindowDC :
GetWindowDC :
SetWindowTextW :
IsDialogMessageW :
KiUserCallbackDispatcher :
IsDialogMessageW :
IsDialogMessageW :
SetWindowTextW :
DrawThemeParentBackground :
Ordinal69 :
GetWindowDC :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by elpaso** [comment] 2019-06-07 06:50
I cannot reproduce on Linux/Master

**Comment by gioman** [comment] 2020-12-22 15:25
Closing for lack of further feedback.

**Closed by gioman** 2020-12-22 15:25 UTC
Labels: Bug, Crash/Data Corruption, Feedback, GUI/UX, High Priority
