### ISSUE TITLE
QGIS - Not compatible with PostGIS on PostgreSQL 12

### ISSUE THREAD

**Issue by JamesInform** [qgis/QGIS#33109] opened 2019-11-27 23:24 UTC
Hi

I am using PostgreSQL 12 with PostGIS 3.

When I browsing my PostgreSQL database (the geography_column table) , I get the error

`column adef.adsrc does not exist
LINE 8: adef.adsrc AS default_value,
^`

This is due to the fact that PostgreSQL 12 has removed the adsrc column as it was deprecated since over a decade.

See https://www.postgresql.org/docs/11/catalog-pg-attrdef.html and compare with https://www.postgresql.org/docs/12/catalog-pg-attrdef.html

Would be fine if somebody could fix this issue in QGIS, because you cannot work on PostgreSQL 12.

James

**Comment by JamesInform** [comment] 2019-11-28 07:40
I have checked the source code of the current QGIS git Master and there has already been a fix
in the following files:
**- connector.py**
**- postgis.py**

        ad_col_name = 'adsrc' if version_number < 12 else 'adbin'

        sql = u"""SELECT a.attnum AS ordinal_position,
                                a.attname AS column_name,
                                t.typname AS data_type,
                                a.attlen AS char_max_len,
                                a.atttypmod AS modifier,
                                a.attnotnull AS notnull,
                                a.atthasdef AS hasdefault,
                                adef.%s AS default_value,
                                pg_catalog.format_type(a.atttypid,a.atttypmod) AS formatted_type
                        FROM pg_class c
                        JOIN pg_attribute a ON a.attrelid = c.oid
                        JOIN pg_type t ON a.atttypid = t.oid
                        JOIN pg_namespace nsp ON c.relnamespace = nsp.oid
                        LEFT JOIN pg_attrdef adef ON adef.adrelid = a.attrelid AND adef.adnum = a.attnum
                        WHERE
                          a.attnum > 0 AND c.relname=%s %s
                        ORDER BY a.attnum""" % (ad_col_name, self.quoteString(tablename), schema_where)`

But changing adsrc to adbin alone won't do the job. 

The easiest solution, that would work with all PostgreSQL version without having to distinguish between versions >= 12 and versions < 12 would be to substitue
`adsrc` 
with
`pg_get_expr(adbin,adrelid) `

So I think a good fix would be:

```
       sql = u"""SELECT a.attnum AS ordinal_position,
                                a.attname AS column_name,
                                t.typname AS data_type,
                                a.attlen AS char_max_len,
                                a.atttypmod AS modifier,
                                a.attnotnull AS notnull,
                                a.atthasdef AS hasdefault,
                                pg_get_expr(adef.adbin,adef.adrelid)  AS default_value,
                                pg_catalog.format_type(a.atttypid,a.atttypmod) AS formatted_type
                        FROM pg_class c
                        JOIN pg_attribute a ON a.attrelid = c.oid
                        JOIN pg_type t ON a.atttypid = t.oid
                        JOIN pg_namespace nsp ON c.relnamespace = nsp.oid
                        LEFT JOIN pg_attrdef adef ON adef.adrelid = a.attrelid AND adef.adnum = a.attnum
                        WHERE
                          a.attnum > 0 AND c.relname=%s %s
                        ORDER BY a.attnum""" % (ad_col_name, self.quoteString(tablename), schema_where)
```

James

**Comment by gioman** [comment] 2019-11-28 08:54
Duplicate of https://github.com/qgis/QGIS/issues/32321

**Closed by gioman** 2019-11-28 08:54 UTC

**Comment by haytastan** [comment] 2019-12-20 12:58
### In addition to JamesInform's suggestion, 
a second change is required in **connector.py**
(i.e. substitue  "c.consrc" with "c.conbin"). 

### Change the line from
sql = u"""SELECT c.conname, c.contype, c.condeferrable, c.condeferred, array_to_string(c.conkey, ' '), **c.consrc**,

### to 
sql = u"""SELECT c.conname, c.contype, c.condeferrable, c.condeferred, array_to_string(c.conkey, ' '), **c.conbin**,

### You may verify this change at the URL:
https://github.com/qgis/QGIS/tree/master/python/plugins/db_manager/db_plugins/postgis

Regards,
[https://tr.linkedin.com › hayatitastan](url)

**Comment by gioman** [comment] 2019-12-20 19:09
> a second change is required in **connector.py**
> (i.e. substitue "c.consrc" with "c.conbin").

@haytastan can you propose a patch?

**Comment by Zim1-finest** [comment] 2020-06-07 08:23
Hello 
I had the same problem as mentioned above. I followed the solution and substituted the highlighted codes in connector.py but I still encounter the same problem. 

When I run the connector.py script I get the following error
 ```
**from qgis.PyQt.QtCore import QRegExp, QFile
ModuleNotFoundError: No module named 'qgis'**
```
Does anyone have any idea what I should do? I am really a novice when it comes to coding.
