### ISSUE TITLE
geometry generator function make_point (x,y) doesn't work for records with no geometry

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#46399] opened 2021-12-07 12:38 UTC
### What is the bug or the crash?

If I style a point layer and for the symbol I choose the geometry generator and the function make_point, no symbol appears for manually entered points.

### Steps to reproduce the issue

1. create a new geopackage point layer
2. in the table create at least the columns for X and Y coordinate
3.  style the layer and for symbol select geometry generator -> make_point ("X", "Y")
4. enter a custom point with DD coordinate

Nothing happen, no points are created.

### Versions

Versione di QGIS
3.16.6-Hannover
Revisione codice QGIS
bfd36fddc9
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.1.4
Esecuzione con GDAL/OGR
3.1.4
Compilato con GEOS
3.8.1-CAPI-1.13.3
Esecuzione con GEOS
3.8.1-CAPI-1.13.3
Compilato su SQLite
3.29.0
In esecuzione su SQLite
3.29.0
Versione client PostgreSQL
11.5
Versione SpatiaLite
4.3.0
Versione QWT
6.1.3
Versione QScintilla2
2.10.8
Compilato con PROJ
6.3.2
Esecuzione con PROJ
Rel. 6.3.2, May 1st, 2020
Versione SO
Windows 10 (10.0)
Attiva python plugin
AzimuthDistanceCalculator; 
batch_hillshader-master; 
clipper; 
coordinates_converter; 
DigitizingTools; 
latlontools; 
map-coords-plugin; 
points2one; 
profiletool; 
Qgis2threejs; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

If I start from a point layer where table just contain points, the style geometry generator and make_point works, but if I enter manually a new point directly in the table the new one doesn't appear.

I'm still testing point layer; don't know if other geometry generator functions behave in the same way.

**Comment by gioman** [comment] 2021-12-07 13:26
> style the layer and for symbol select geometry generator -> make_point ("X", "Y")

@Forna73 this way I think you are creating a point but has no dimension/size, so is not rendered. Try buffer it, and you'll see it show.

**Comment by Forna73** [comment] 2021-12-07 13:45
The symbol dimension are defined in the symbol characteristics: triangle, border width, dimension, color and so on....
 ...for layers with table that already have points that work fine...

**Comment by gioman** [comment] 2021-12-07 13:49
> ...for layers with table that already have points that work fine...

@Forna73 what do you mean? a record in the table with X and Y values but no geometry?



> The symbol dimension are defined in the symbol characteristics: triangle, border width, dimension, color and so on....

Not for a geometry generated with the geometry generator, I think. If you see there are parameters for the fill of the symbol, but not the size.

**Comment by gioman** [comment] 2021-12-07 13:52
> @Forna73 what do you mean? a record in the table with X and Y values but no geometry?

@Forna73 never mind, I see now what do you mean. It only works if the record has an underlying geometry even if the geometry is not used in the GG expression.

**Comment by Forna73** [comment] 2021-12-07 13:54
So... If I understood.... If you have any geometry in a layer, but you start from scratch with a white table... you'll have no render cause no geometry is present.... Do you confirm?

**Comment by gioman** [comment] 2021-12-07 15:15
> So... If I understood.... If you have any geometry in a layer, but you start from scratch with a white table... you'll have no render cause no geometry is present.... Do you confirm?

@Forna73 what I'm saying is that despite the expression make_point ("X", "Y") do not make use of a geometry, it only works if a record has a geometry. As you reported you can have a point layer but from the table of attributes you can add a record that is orphaned of the geometry. If X and Y columns are populated manually then make_point ("X", "Y")  will not return anything.

**Comment by Forna73** [comment] 2021-12-07 16:51
Ok... so I understood well.... is it expected to work in this way?

**Comment by Forna73** [comment] 2021-12-08 09:23
I was looking for a workaround... but do you confirm that "make_point" function supports only DD coordinates? Is there a way to make it work with DD°MM'SS" coordinates?

**Comment by gioman** [comment] 2021-12-08 09:45
> Is there a way to make it work with DD°MM'SS" coordinates?

https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#to-decimal

https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#to-dms

**Comment by Forna73** [comment] 2021-12-08 12:20
Thanks!

**Comment by m-kuhn** [comment] 2021-12-09 06:39
Unchecked guess:
It's the renderer only fetching features in the current extent for rendering. Unrelated to the expression function.
Changing that will have a strong impact on performance of geometry generators. Might deserve an option.

**Comment by nyalldawson** [comment] 2021-12-09 07:51
For the record I'm -1 to making generators address this use case. Rather we need some type of universal " virtual geometry" support

**Comment by m-kuhn** [comment] 2021-12-09 07:57
> For the record I'm -1 to making generators address this use case. Rather we need some type of universal " virtual geometry" support

For the record, meanwhile anyone can use virtual layers for this

**Comment by m-kuhn** [comment] 2021-12-09 08:06
Duplicate of #38579

**Closed by m-kuhn** 2021-12-09 08:06 UTC
