### ISSUE TITLE
Allow using the native IDW and TIN interpolation tool in a model

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#51082] opened 2022-12-01 11:08 UTC
### Feature description

Currently, the IDW and TIN native interpolation tools can only be used in the modeller if the input is fixed. I suggest using model Inputs or algorithm outputs as input parameters of these interpolation tools:

![image](https://user-images.githubusercontent.com/6665872/205037102-354e3666-30d0-4ac0-9622-4b09a584b411.png)

### Additional context

The workaround is to use external providers' interpolation tools (i.g. GRASS), but these are prone to break from one version of QGIS to the other.

**Comment by nicogodet** [comment] 2022-12-01 13:04
Seems a duplicate of https://github.com/qgis/QGIS/issues/30029

**Comment by baswein** [comment] 2022-12-02 19:40
> Seems a duplicate of #30029

It seems like there are 2 issues here- The one that #30029 covers which is about the ability of using model layer outputs and model input layers as layers in the Interpolation algo. There is also the issue of the ability to add layers during the run process using the Tin Creation Layers input which TIN Mesh Creation currently is able to do. 
I'm not sure which one @andremano is trying to achieve.

**Comment by andremano** [comment] 2022-12-08 22:33
Thanks @baswein and @nicogodet. Yes, I would say it is a duplicate of #30029. It is good to know about the mesh layer workaround, however that still lets the user without the native IDW interpolation tool - an interpolation technique that is quite different than that of TIN.

**Closed** 2022-12-09 06:59 UTC
Labels: Feature Request
