### ISSUE TITLE
Couldn't load SIP module. Python support will be disabled. QGIS 3.10 LTR Windows 10 64-bit

### ISSUE THREAD

**Issue by abhiinav-18** [qgis/QGIS#37783] opened 2020-07-12 21:39 UTC
**I used to work on QGIS 3.4 some months back but then started using Anaconda for python. Recently I got back on QGIS. I downloaded the QGIS 3.10 LTR (64-bit) but ran into an error saying "Couldn't load SIP module.
Python support will be disabled". I am not able to install any plugins because of no python support.**

**Error message on launch: 
Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\PyQt\QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.

Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.10.7-A Coruña 'A Coruña', 7b4ca4c8d0**
[New Text Document.txt](https://github.com/qgis/QGIS/files/4909583/New.Text.Document.txt)

**Comment by nyalldawson** [comment] 2020-07-12 21:53
Did you install qgis using anaconda? If so , this isn't the recommended approach, and there's many known issues like this

**Comment by abhiinav-18** [comment] 2020-07-12 22:37
> Did you install qgis using anaconda? If so , this isn't the recommended approach, and there's many known issues like this

no, I downloaded it from the QGIS website. I also had QGIS 3.4 from before and I got the new verson today.

**Comment by roya0045** [comment] 2020-07-14 10:31
Seems like a syspath issue, though I never encountered any with anaconda and qgis. In you deinstall anaconda, does that fix the problem? I recall there was options to modify path variables when installing conda.

Also does your 3.4 install still works (assuming you didn't remove it)?

**Comment by abhiinav-18** [comment] 2020-07-14 19:33
I have not removed my anaconda yet. If I remove it then do I have to add a library like TensorFlow again? I don't want to lose all that also. 

I had removed QGIS 3.4 when I got 3.10. Although I installed 3.4 again as I had the setup and it has the same error now.
You are right regarding path variables can you tell more.

this link may help solve but I couldn't understand it:
https://gis.stackexchange.com/questions/108458/couldnt-load-sip-module-qgis-doesnt-load-python

**Comment by roya0045** [comment] 2020-07-14 22:20
In your anaconda do you have pyqt installed? Your link made me curious if you have another qt lib that could intercept the one in qgis.

**Comment by abhiinav-18** [comment] 2020-07-15 07:31
Thanks for helping out. 
I did a 'conda list' in anaconda command prompt and found that I've got a PyQt library. I'll add the snap in the command.

interestingly I also found an old version of QGIS on my laptop i.e. QGIS 2.14 Essen. I installed it and found the same problem. Only the python version in error was Python 2.7 there.
![pyqt](https://user-images.githubusercontent.com/53288853/87516543-35056d00-c69b-11ea-9c64-a1a30b598f88.PNG)

**Comment by gioman** [comment] 2020-07-15 10:33
@abhiinav-18 I think this is a local issue and I'm inclined to close this ticket.

**Comment by abhiinav-18** [comment] 2020-07-15 12:23
I think many people suffer from the same problem as I'm. Also, this is my first post on Github so I don't know the rules around here. All I can do is request you not to close the issue without a solution.

**Comment by gioman** [comment] 2020-07-15 13:43
> All I can do is request you not to close the issue without a solution.

@abhiinav-18 no valid **general** issue is closed without a solution, but this do not seems to be a general QGIS issue, but of course I'll leave to more informed persons to take the decision.

**Comment by markjessell** [comment] 2020-07-16 04:28
I have the same problem (using qgis 3.14 but also running older versions). I also am running anaconda. I haven't found a solution yet.

**Comment by markjessell** [comment] 2020-07-16 04:44
> I have the same problem (using qgis 3.14 but also running older versions). I also am running anaconda. I haven't found a solution yet.

to be specific it is slightly different but probably related to the same cause:

Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\__init__.py", line 78, in 
    import qgis.gui
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\gui\__init__.py", line 25, in 
    from qgis._gui import *
RuntimeError: the sip module implements API v12.0 to v12.4 but the qgis._gui module requires API v12.6


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.14.0-Pi 'Pi', 9f7028fd23

**Comment by roya0045** [comment] 2020-07-16 10:31
Out of curiousity, try removing pyqt from your packages

**Comment by markjessell** [comment] 2020-07-16 11:58
thanks for the suggestion, but it didn't change anything (and neither did reinstalling it afterwards)

**Comment by Desiree22** [comment] 2020-08-04 12:01
I also had the same issue! not sure what caused it but I may have made an unintended change to one of the bat files. 

Problem solved by deleting the python 3.7 folder.
Folder python 3.7 is in the directory C:\Users\Admin\AppData\Roaming\Python

This may have other consequences but at least for now I am able to run my QGIS again without the python error. 
I also have anaconda installed and everything is working fine.

QGIS version: 3.14.1
Python Version: 3.7.4
Windows 10 Home Version 2004

**Comment by markjessell** [comment] 2020-08-05 01:22
wow, thank you Desiree, that fixed it for me as well! I just renamed the python directory (just in case!!) in the equivalent path (my user name instead of Admin), so now all is right with the world!

**Comment by gioman** [comment] 2020-08-05 10:46
Closing as a solution has been provided.

**Closed by gioman** 2020-08-05 10:46 UTC
Labels: Bug, Feedback

**Comment by kikislater** [comment] 2020-08-05 10:48
Question remain why qgis is looking in this folder ... May be paths definition could be enhance in some .bat

**Comment by rdejtiar** [comment] 2020-08-09 21:07
![Captura de pantalla_2020-08-09_17-25-19](https://user-images.githubusercontent.com/57047709/89741794-ac47da00-da6a-11ea-8726-7a9254035e1b.png)
I have the same problem and I will try to fix it , but on my system the message is a bit different and refers to an undefined symbol at QtCore.so

**Comment by CRTejaswi** [comment] 2020-09-29 09:11
I had the same problem. I use __pip__ package manager. I got over this issue by removing all PyQt5 packages (I don't use them anyway). On Windows, this came in handy:
```powershell
(pip list) -match 'qt'
python -m pip uninstall pyqt5 pyqt5-sip qtconsole
```

**Comment by msecher** [comment] 2020-10-16 05:25
Hi,

I applied the solution of CRTejaswi of removing PyQt5 packages and it worked for qgis (I have a QGIS 3.14.1 and QGIS 3.10.9 on a debian 10).

My problem is that I have others softwares which need PyQt5 to work. 

Is there any other solution to keep PyQt5 packages and still be able to run QGIS 3 ?

**Comment by roya0045** [comment] 2020-10-16 10:01
@msecher which version of pyqt5 did you have/need?

**Comment by abhiinav-18** [comment] 2020-10-16 12:35
@Desiree22  solution worked for me on QGIS version 3.10.10. I did not remove any PyQt packages and now I've python support in QGIS.

**Comment by msecher** [comment] 2020-10-16 22:40
@roya0045 I need at least PyQt5 5.9.0 and I have PyQt5 5.15.1

@Desiree22 I tried to install QGIS 3.10.10 and it is still not working for me.

**Comment by markjessell** [comment] 2020-10-16 23:36
In the end what worked for me was to write a small script that I run from Cygwin but a bat script would do too:

1) renames my anaconda python directory to python_temp
2) launches qgis
3) pauses for ten seconds until qgis is launched
4) renames the python_temp directory back to python

Stupid but effective, and once qgis has launched it has all the plugins and my other python code runs fine too.



Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E mark.jessell@uwa.edu.au

________________________________

**Comment by markjessell** [comment] 2020-10-17 01:08
The actual script I use is:


#!/bin/bash
mv /cygdrive/c/Users/00073294/AppData/Roaming/Python /cygdrive/c/Users/00073294/AppData/Roaming/Python_xx
"/cygdrive/c/Program Files/QGIS 3.14/bin/qgis-bin.exe" &
sleep 15
mv /cygdrive/c/Users/00073294/AppData/Roaming/Python_xx /cygdrive/c/Users/00073294/AppData/Roaming/Python



obviously paths will have to be changed to get this to work on anyone else computer...

**Comment by CRTejaswi** [comment] 2020-10-17 19:52
> Hi,
> 
> I applied the solution of CRTejaswi of removing PyQt5 packages and it worked for qgis (I have a QGIS 3.14.1 and QGIS 3.10.9 on a debian 10).
> 
> My problem is that I have others softwares which need PyQt5 to work.
> 
> Is there any other solution to keep PyQt5 packages and still be able to run QGIS 3 ?

@msecher is there a system conflict if you install PyQt5 as a `--user` installation or in a virtual environment?
```bash
# User Installation
pip install --user PyQt5
```
```bash
# Virtual-Environment based Installation
python -m venv myProject/venv; cd myProject
source venv/bin/activate
pip install PyQt5
```

**Comment by pepeto** [comment] 2022-04-09 17:32
@fotisAnagnostopoulos I had no PYTHONPATH variable declared and I created it with the value c:\Program Files\Python39\ and it worked.
THANK YOU for the idea!

**Comment by Bookervsky** [comment] 2022-08-01 13:35
@Desiree22 It  did work , appreciate it!

**Comment by Cezembre** [comment] 2022-08-11 08:26
Hello All,

I face the same issue for me with QGis 3.18 on Linux Debian : 

```
The SIP module could not be loaded. 
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/lib/python3/dist-packages/qgis/__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "/usr/lib/python3/dist-packages/qgis/PyQt/QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/johndoe/.local/lib/python3.7/site-packages/PyQt5/QtCore.abi3.so)


Python Version :
3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]

Version de QGIS :
3.18.3-Zürich 'Zürich', 735cc85be9

Python path :
['/usr/share/qgis/python', '/home/johndoe/.local/share/QGIS/QGIS3/profiles/default/python', '/home/johndoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/johndoe/.local/lib/python3.7/site-packages', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

Any help to fix it ?
Thanks !

**Comment by kikislater** [comment] 2022-08-11 08:39
Why do you need 3.18 ? 3.22 is released now

**Comment by Cezembre** [comment] 2022-08-11 09:03
Just fixed !

I unistall Qt and Qgis, then reinstall Qgis.
It seems to work for me.

Hope it will help other Linux user...

**Comment by Philanoe** [comment] 2022-09-17 09:02
Hi, I had the same problem on Ubuntu 22. Using a conda virtual environment with sip did not solve the problem.
Finally, I just used "sudo qgis" instead of "qgis" to launch the application from the terminal, and it worked.

**Comment by do4sch** [comment] 2023-02-01 13:48
I have some kind of the same problem on Windows Server 2022 and QGIS Server  3.28.3

``14:19:01 WARNING Python error[10088]: An error occurred during execution of following code:
os.environ['HOME']=os.environ['USERPROFILE']


Traceback (most recent call last):
  File "", line 1, in 
  File "C:\OSGeo4W\apps\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'USERPROFILE'

Python version:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

QGIS version:
3.28.3-Firenze 'Firenze', c12bcb2f76c

Python path:
['C:\\OSGeo4W\\apps\\Python39', 'C:\\OSGeo4W\\apps\\Python39\\Scripts', 'C:\\OSGeo4W\\bin\\python39.zip', 'C:\\OSGeo4W\\apps\\Python39\\DLLs', 'C:\\OSGeo4W\\apps\\Python39\\lib', 'C:\\OSGeo4W\\apps\\qgis\\bin', 'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages', 'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\win32', 'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\win32\\lib', 'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\Pythonwin']
14:19:01 WARNING Python error[10088]: Couldn't load SIP module.
Python support will be disabled.``

**Comment by BinoyKadakkal** [comment] 2023-03-22 05:25
> I had the same problem. I use **pip** package manager. I got over this issue by removing all PyQt5 packages (I don't use them anyway). On Windows, this came in handy:
> 
> ```powershell
> (pip list) -match 'qt'
> python -m pip uninstall pyqt5 pyqt5-sip qtconsole
> ```

It worked for me.

**Comment by filchos** [comment] 2023-04-26 07:47
The approach of sean-44 worked for me as well. I'm on Linux (Ubuntu)

I retrieved the value for `PYTHONPATH` from 

```sh
which python3
```

and added it in QGIS to Settings > Options … > System > Environment.

After a restart the error did not pop up again.

**Comment by GregDeakin** [comment] 2023-07-25 14:03
Same problem here.

I have Ubuntu on Windows WSL2. Anaconda install of Python 3.9 and apt install of Python 3.8.

I've fixed by purging 3.9 and QGIS. Then reinstalling QGIS and removing PyQt5* from ~/.local/lib/Python3.8/site-packages.

I suspect just removing the the the PyQt5 stuff from site-packages would have been sufficient

**Comment by Inna949Festchuk** [comment] 2023-10-03 00:06
1. узнаю путь
which python 
2. в настройках QGIS (как было выше) > переменные среды > добавить его в начало PATH
3. Всем спасибо!

**Comment by arturitorv** [comment] 2023-11-18 18:17
> I ran into this problem today and didn't want to uninstall anything so searched around. In QGIS, Go to Settings > Options >System >Environment. I selected the 'Use custom variables' checkbox and for the Variable PYTHONPATH, I changed to the Python within OSGEO4W like so: VALUE = C:\OSGeo4W\apps\Python39\Lib\site-packages;C:\OSGeo4W\apps\Python39\Lib;C:\OSGeo4W\apps\Python39
> 
> Initially it was in my other Python folder on my root drive that I use Anaconda on. This fixed the issue for me and I didn't need to remove anything or create a batch file. Hope it helps.

It worked for me, Thank U!!

**Comment by stibinator** [comment] 2023-11-22 23:05
On Ubuntu Jammy, adding the `PYTHONPATH` to the environment variables didn't work, what did work was `pip uninstall pyqt5.`

**Comment by anisometropie** [comment] 2024-02-27 09:18
To document this case on linux, this error happened when I tried to start qgis from a shell (which I didn’t see) was a poetry shell. 
it works ok when I start qgis from a normal shell.

Couldn't load SIP module.<br>Python support will be disabled.</font><br><pre><br>Traceback (most recent call last):<br>&nbsp; File \"<string>\", line 1, in <module><br>ModuleNotFoundError: No module named 'qgis'<br><br></pre>Python version:<br>3.11.6 (main, Oct&nbsp; 8 2023, 05:06:43) [GCC 13.2.0]<br><br>QGIS version:<br>3.28.14-Firenze 'Firenze', exported<br><br>Python path:<br>['/usr/share/qgis/python', '/home/ut/.local/share/QGIS/QGIS3/profiles/default/python', '/home/ut/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload']

**Comment by davidoclubb** [comment] 2024-06-26 11:00
> Ubunt

Thanks, this also worked for me on Fedora

**Comment by davidoclubb** [comment] 2024-06-26 11:01
> Hi, I had the same problem on Ubuntu 22. Using a conda virtual environment with sip did not solve the problem. Finally, I just used "sudo qgis" instead of "qgis" to launch the application from the terminal, and it worked.

This also worked for me on Fedora, thanks!

**Comment by LTeder** [comment] 2024-09-05 16:15
I'm encountering this issue when invoking `qgis_process` at the end of a Python program which invokes GDAL and geopandas, among other libraries (numpy, scipy, skimage, shapely). Running it with sudo works as a temporary fix. This is in EndeavourOS using a conda environment with QGIS installed via pacman. I can invoke `subprocess.run("qgis_process", shell=True)` without issue, but testing my command isolated in a similar fashion reproduces the error:
```python
import subprocess

qgis_process_cmd = [
    "qgis_process", "run", "native:clip", "--INPUT=lines.shp",
    "--OVERLAY=bounding-box.shp", "--OUTPUT=clipped-lines.shp"
 ]

subprocess.run(" ".join(qgis_process_cmd),shell=True)
```

<br></pre>Python version:<br>3.12.5 (main, Aug&nbsp; 9 2024, 08:20:41) [GCC 14.2.1 20240805]<br><br>QGIS version:<br>3.38.2-Grenoble 'Grenoble', exported<br><br>Python path:<br>['/usr/share/qgis/python', '/home/user/.local/share/QGIS/QGIS3/profiles/default/python', '/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/home/user/miniforge3/lib/python312.zip', '/home/user/miniforge3/lib/python3.12', '/home/user/miniforge3/lib/python3.12/lib-dynload', '/home/user/miniforge3/lib/python3.12/site-packages']

**Comment by Aneifer** [comment] 2024-10-26 12:40
> Hi, I had the same problem on Ubuntu 22. Using a conda virtual environment with sip did not solve the problem. Finally, I just used "sudo qgis" instead of "qgis" to launch the application from the terminal, and it worked.

WOW! Tried now for hours to fix the problem, that just did it. Thanks!

**Comment by LIANG180828** [comment] 2025-05-08 08:26
Downgrade Python，python<3.12

**Comment by smitty1eGH** [comment] 2025-05-13 02:26
Under Arch Linux/Python 3.13.3, qgis starts fine as root.
I get this error as a regular user.
What permissions issue would trigger this?

**Comment by kavigupta** [comment] 2025-05-30 00:43
Can reproduce this issue, I also have conda installed, root also works for me. Is anyone trying to fix this?
