### ISSUE TITLE
Unable to load point cloud layer

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#50585] opened 2022-10-18 06:09 UTC
### What is the bug or the crash?

When I try to load a point cloud layer, I get the following error from terminal. The layer opens correctly in QGIS 3.26 but fails to open in master.

```
untwine: /home/saber/apps/QGIS/external/untwine/bu/../untwine/GridKey.hpp:28: untwine::GridKey::GridKey(int, int, int): Assertion `j < (std::numeric_limits<uint8_t>::max)()' failed.
src/core/qgsmessagelog.cpp:29 : (logMessage) [184118ms] 2022-10-18T07:53:57 [1] Failed to calculate statistics of the point cloud PARQUE_ABELARDO_2
untwine: /home/saber/apps/QGIS/external/untwine/bu/../untwine/GridKey.hpp:27: untwine::GridKey::GridKey(int, int, int): Assertion `i < (std::numeric_limits<uint8_t>::max)()' failed.
src/core/qgsmessagelog.cpp:29 : (logMessage) [459411ms] 2022-10-18T08:01:36 [1] Failed to calculate statistics of the point cloud PARQUE_ABELARDO_1
```

### Steps to reproduce the issue

Date can be provided for testing the issue.

### Versions

master (3.27 https://github.com/qgis/QGIS/commit/6f9da191b4)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by wonder-sk** [comment] 2022-10-18 07:53
Looks like upstream issue: https://github.com/hobuinc/untwine/issues/125

**Comment by wonder-sk** [comment] 2022-10-18 08:00
A quick look at the file causing problems indicates that the bounding box given in the file header does not match the true bounding box of data, causing this issue. While untwine could have a better way to report such mismatch, in fact the input file is incorrect and should be fixed.

Bounding box as reported in the LAZ file header:
```
    "minx": -145,
    "miny": -137,
    "minz": -7,

    "maxx": 96,
    "maxy": 85,
    "maxz": 35,
```
    
True bounding box of data:
```
    "minx": -145.317,
    "miny": -137.38,
    "minz": -6.574,

    "maxx": 96.3397,
    "maxy": 85.0856,
    "maxz": 34.9464,
```

**Comment by wonder-sk** [comment] 2022-10-18 08:05
(not a regression as the 3.26 test was done using release build - asserts do not get triggered)

**Comment by alexbruy** [comment] 2023-10-27 16:11
Is this still an issue?

**Closed** 2024-02-22 14:37 UTC
Labels: Bug, Upstream, Point Clouds
