### ISSUE TITLE
Error if user CRS contains non-ASCII characters in name and is used as project crs.

### ISSUE THREAD

**Issue by dr1542** [qgis/QGIS#33458] opened 2019-12-18 09:57 UTC
There is not displayed USER:CRS_ID in qgis status bar, but crs name displayed in tooltip. 
![CRS-screen](https://user-images.githubusercontent.com/58694010/71074677-c22f2480-2193-11ea-8a11-5c3e5f1fac04.png)

It is not only UI error - unable to switch to another user CRS with non-ASCII characters in name. If try to switch to EPSG crs or user crs with only ASCII characters in name and then to second CRS with non-ASCII characters coordinate panel in status bar continues display coordinates of first user CRS with non-ASCII name.

I checked this in Qgis 3.11.0-Master (0d84e35839) and 3.10.0-A CoruÃ±a (6c816b4204)
OS - Windows 7

Qgis 2.18.28 works fine

**Comment by gioman** [comment] 2019-12-18 10:02
> Qgis 2.18.28 works fine

tagging as regression.

**Comment by Dkrav-UA** [comment] 2020-01-23 10:06
In 3.10.1 version everything was fine. It was broken in 3.10.2 version.

**Comment by gioman** [comment] 2020-01-23 11:17
> was broken

"was" or "is"?

**Comment by Dkrav-UA** [comment] 2020-01-23 11:47
> "was" or "is"?

3.10.1 - ok
3.10.2 - broken

**Comment by troopa81** [comment] 2020-02-03 15:50
I don't reproduce with current 3.10.x
![Uploading erreur_crs.png…]()

you can install it with OSGEO4W installer [qgis-rel-dev](https://www.qgis.org/en/site/forusers/alldownloads.html#windows).

If OK, it would be delivered in 3.10.3

**Comment by nyalldawson** [comment] 2020-02-04 01:53
I can't reproduce. Can you post more detailed steps to reproduce please?

**Comment by dr1542** [comment] 2020-02-04 07:06
I can't reproduce this too. But only after I was created new user profile with empty qgis.db crs database. In new session i was created some crs definitions and qgis works as expected. When I opened this issue, I used my old qgis.db, because I use a lot of custom crs.
At first glance, I don't find any difference in the table formats in the old and new qgis.db but it seems to be there.

**Comment by Dkrav-UA** [comment] 2020-02-04 07:47
I confirm that with a new user profile everything is ok. But with the old profile problem is more than just show USER:XXXXX in the corner. For example, I can't delete or edit existing CRS's. I get an error.
![Screenshot_20200204_094515](https://user-images.githubusercontent.com/16414895/73724070-36695b80-4733-11ea-962a-85a145b74c32.png)
But validation check returns OK.

**Comment by nirvn** [comment] 2020-02-04 08:06
@nyalldawson , here's what might be happening here: some saved user projections that were valid under gdal2/proj5 are not in gdal3/proj6 (due to positive match with known CRS), which is preventing users with successfully clicking on [ OK ].

Possible solutions:
- use a different db name for gdal2/proj5 vs gdal3/proj6 in the user profile directory (we could adopt what we have in the source tree, srs.db vs srs6.db)
- auto change proj string to wkt instead of throwing a warning dialog 

@Dkrav-UA , if you follow the advice given to you by QGIS and change the bing string format to a WKT string (using the combo box), do you still see an error or not for that saved projection? If not, do that for the other projections too.

**Comment by Dkrav-UA** [comment] 2020-02-04 08:13
> @nyalldawson , here's what might be happening here: some saved user projections that were valid under gdal2/proj5 are not in gdal3/proj6 (due to positive match with known CRS), which is preventing users with successfully clicking on [ OK ].
> 
> Possible solutions:
> 
>     * use a different db name for gdal2/proj5 vs gdal3/proj6 in the user profile directory (we could adopt what we have in the source tree, srs.db vs srs6.db)
> 
>     * auto change proj string to wkt instead of throwing a warning dialog
> 
> 
> @Dkrav-UA , if you follow the advice given to you by QGIS and change the bing string format to a WKT string (using the combo box), do you still see an error or not for that saved projection? If not, do that for the other projections too.

The problem persists in all available variants (WKT, PROJ). But with a slightly different error message.
![Screenshot_20200204_101053](https://user-images.githubusercontent.com/16414895/73725827-e2f90c80-4736-11ea-9802-8c66af2cc8e3.png)

![Screenshot_20200204_101138](https://user-images.githubusercontent.com/16414895/73725852-f4daaf80-4736-11ea-9d01-1989406731b1.png)

**Comment by nirvn** [comment] 2020-02-04 08:14
@Dkrav-UA , can you paste the WKT string you have for bing?

**Comment by Dkrav-UA** [comment] 2020-02-04 08:15
PROJCS["unnamed",GEOGCS["unnamed ellipse",DATUM["unknown",SPHEROID["unnamed",6378137,0],EXTENSION["PROJ4_GRIDS","@null"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Mercator_2SP"],PARAMETER["standard_parallel_1",0],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"]]

**Comment by Dkrav-UA** [comment] 2020-02-04 08:17
The problem is not with the definition. Something wrong with old profiles. In new profile this string works ok.

**Comment by nirvn** [comment] 2020-02-04 08:17
OK, try this: remove the _second_ saved projection right below 'Bing', I can see the proj string is identical to bing.

**Comment by nirvn** [comment] 2020-02-04 08:18
That one:
![Screenshot from 2020-02-04 15-18-03](https://user-images.githubusercontent.com/1728657/73726210-924ad900-4761-11ea-9667-e07f60aef873.png)

**Comment by Dkrav-UA** [comment] 2020-02-04 08:20
> OK, try this: remove the _second_ saved projection right below 'Bing', I can see the proj string is identical to bing.

Wrong. They are different. There is a shift by X and Y.

**Comment by nirvn** [comment] 2020-02-04 08:21
Can you then switch that to WKT and paste the string here too?

**Comment by Dkrav-UA** [comment] 2020-02-04 08:24
PROJCS["unnamed",GEOGCS["unnamed ellipse",DATUM["unknown",SPHEROID["unnamed",6378137,0],EXTENSION["PROJ4_GRIDS","@null"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Mercator_2SP"],PARAMETER["standard_parallel_1",0],PARAMETER["central_meridian",0],PARAMETER["false_easting",-7],PARAMETER["false_northing",-10],UNIT["Meter",1],EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=-7.0 +y_0=-10.0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"]]

**Comment by nirvn** [comment] 2020-02-04 08:25
Also, can you attach your qgis.db file here? Access it via Settings -> User Profiles -> Open Active Profile Folder.

**Comment by Dkrav-UA** [comment] 2020-02-04 08:27
[qgis.db.zip](https://github.com/qgis/QGIS/files/4152107/qgis.db.zip)

**Comment by nirvn** [comment] 2020-02-04 08:33
OK, I can see the bing definition, whether using a proj or wkt string, matches a known EPSG:
![Screenshot from 2020-02-04 15-29-31](https://user-images.githubusercontent.com/1728657/73727033-46009880-4763-11ea-9c3d-64ccd20a62f2.png)

So if you get rid of Bing and use the proper EPSG code, you'll be able to move ahead. Then, on my machine, if I change all other CRSes to WKT format, I can click on OK just fine.

**Comment by nirvn** [comment] 2020-02-04 08:37
Note: I've identified a side, related problem here, looking into it.

**Comment by Dkrav-UA** [comment] 2020-02-04 08:40
I use Bing projection to shift images when there is a difference.

I FOUND SOLUTION:
I manually deleted auto-generated crs's from qgis.db. And set to NULL every empty cell. And now it works.

**Comment by dr1542** [comment] 2020-02-04 09:15
I created all my old custom CRS in new qgis.db and then tried test it in different qgis versions in windows.  I used
QGIS 2.18.28 / GDAL 2.4.1 / PROJ.4 520
QGIS 3.10.0 (6c816b4204) / GDAL 2.4.1 / PROJ 5.2.0
QGIS 3.10.2 (d4cd3cfe5a) / GDAL 3.0.3/ PROJ 6.3.0
QGIS 3.11.0-Master (efe59758e1) /GDAL 3.1.0dev /PROJ 7.0.0
All versions works fine.

Life seems to be getting better.

**Comment by gioman** [comment] 2020-02-04 09:18
Closing?

**Comment by nirvn** [comment] 2020-02-04 09:19
@gioman , yep.

**Closed by nirvn** 2020-02-04 09:19 UTC
Labels: Bug, Feedback, Projections/Transformations, Regression
