### ISSUE TITLE
Issue with 'ILIKE' queries in the filter dialog

### ISSUE THREAD

**Issue by stevefaeembra** [qgis/QGIS#51375] opened 2023-01-04 23:32 UTC
### What is the bug or the crash?

Found an issuw with ILIKE not working in QGIS version 3.28.2-Firenze, in the Query Builder dialog when applying a filter. Case dependent LIKE does work

### Steps to reproduce the issue

- load a geopackage layer
- add a filter using the query bulder dialog on a text field. Use an expression like "field" ILIKE 'foo'
- click test, or apply. You'll get an error in the first case, or no features in the second case.

![image](https://user-images.githubusercontent.com/4268610/210669377-34f40a06-4bd9-4875-aa39-ca0f9bbc2fef.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.2-Firenze | QGIS code revision | b47e00ba601
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.1
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
Beeline | 0.2.0
GlobeBuilder | v0.6.0
isochrones | 0.1.2
latlontools | 3.6.7
leastcostpath | 1.1
LoadQSS | 1.4.2
MagneticDeclination | 2.3.1
Multi_Ring_Buffer | 1.1
OSMDownloader | 1.0.3
pointsamplingtool | 0.5.4
processing_wbt | 1.3.1
Projestions | 1.0.1
qchainage | 3.0.1
Qgis2threejs | 2.7.1
qgis_resource_sharing | 1.0.0
quick_map_services | 0.19.32
rvt-qgis | 0.9.4.1
SRTM-Downloader | 3.1.17
TerrainShading | 0.9.4
valuetool | 3.0.15
vector_tiles_reader | 3.2.2
ViewshedAnalysis | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.2-Firenze
QGIS code revision
[b47e00ba601](https://github.com/qgis/QGIS/commit/b47e00ba601)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Beeline
0.2.0
GlobeBuilder
v0.6.0
isochrones
0.1.2
latlontools
3.6.7
leastcostpath
1.1
LoadQSS
1.4.2
MagneticDeclination
2.3.1
Multi_Ring_Buffer
1.1
OSMDownloader
1.0.3
pointsamplingtool
0.5.4
processing_wbt
1.3.1
Projestions
1.0.1
qchainage
3.0.1
Qgis2threejs
2.7.1
qgis_resource_sharing
1.0.0
quick_map_services
0.19.32
rvt-qgis
0.9.4.1
SRTM-Downloader
3.1.17
TerrainShading
0.9.4
valuetool
3.0.15
vector_tiles_reader
3.2.2
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment] 2023-01-05 01:21
AFAIK this bug was already reported https://github.com/qgis/QGIS/issues/35698 and already allegedly fixed with https://github.com/qgis/QGIS/pull/35706 by @jef-n.

**Comment by agiudiceandrea** [comment] 2023-02-09 06:07
@troopa81 It seems to me the issue does still occur although the previous issue report https://github.com/qgis/QGIS/issues/35698 was closed by @jef-n as "completed" after merging https://github.com/qgis/QGIS/pull/35706.
The issue is due to the fact that `ILIKE` is not an SQLite operator, but the issue may be fixed in QGIS as mentioned in https://github.com/qgis/QGIS/issues/35698#issuecomment-611983463.

**Comment by jef-n** [comment] 2023-02-09 23:31
> #35698 was closed by @jef-n as "completed" after merging #35706. 

No.  The issue was closed before merging the commit, as there is no issue.  ILIKE is not supported by the provider/backend and the filter string is provider specific and the help/manual states:

> The filter is made at the data provider (OGR, PostgreSQL, MS SQL Server…) level. So the syntax depends on the data provider (DateTime is for instance not supported for the ESRI Shapefile format).

The commit is related to another issue mentioned there and just refs it, but doesn't close it.

**Comment by jef-n** [comment] 2023-02-09 23:32
Duplicate of #35698

**Closed by jef-n** 2023-02-09 23:32 UTC
Labels: Feedback, Data Provider, Bug
