### ISSUE TITLE
MDAL: crashes when zooming on EPSG:4326

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29330] opened 2019-03-07 19:16 UTC
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [21513](https://issues.qgis.org/issues/21513)
Affected QGIS version: 3.6.0
Redmine category:mesh_layers
Assignee: Peter Petrik

---
* open QGIS 3.6
* type 'woorld' in the ccod box, to load a world map in 4326
* load the file: https://www.faunalia.eu/~paolo/20190307_190528_GFS_P25_.grb2
* QGIS crashes
All from Debian sid, up  to date.

---

- [Schermata del 2019-03-08 14-55-28.png](https://issues.qgis.org/attachments/download/14557/Schermata%20del%202019-03-08%2014-55-28.png) (Alberto Grava)

**Comment by PeterPetrik** [comment] 2019-05-31 10:34
probably duplicate of #28827

**Closed** 2020-02-28 06:57 UTC
Labels: Bug, Crash/Data Corruption, High Priority
