### ISSUE TITLE
Unable to use offered layer variable in aggregate function in Field Calculator under Graphical Modeller

### ISSUE THREAD

**Issue by tschmetzer** [qgis/QGIS#37347] opened 2020-06-23 08:59 UTC
**Bug description**
The use case is to use the aggregate function in a field calculator expression in the graphical modeler. 
I want to count a number of points within each polygon of another layer. This works without any problems when using the field calculator on existing and "reachable" layers.
However when including this aggregate function into the Graphial Modeler the offered input layers (referred to by @layer variables) in the expression tab seem to be unavailable to the algorithm. The error returned is _Cannot find layer with name or ID ''_.

This is the aggregate expression used in the field calculator:
 aggregate(
 layer:= @polygoninput ,
 aggregate:='count',
 expression:=$id,
 filter:=intersects($geometry, geometry(@parent))
 )

I will attach screenshots, the model file and example data.

**Log output**
QGIS version: 3.12.3-București
QGIS code revision: 8234261527
Qt version: 5.11.2
GDAL version: 3.0.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'MyAggregate' starting…
Input parameters:
{ 'pointinput' : 'C:/Users/Tobias/Documents/GIS DataBase/ExamplePointLayer.shp', 'polygoninput' : 'C:/Users/Tobias/Documents/GIS DataBase/ExamplePolygonLayer.shp' }

Prepare algorithm: qgis:fieldcalculator_2
Running Field calculator count [1/1]
Input Parameters:
{ FIELD_LENGTH: 7, FIELD_NAME: 'Count', FIELD_PRECISION: 3, FIELD_TYPE: 1, FORMULA: ' aggregate(\r\n layer:= @polygoninput ,\r\n aggregate:=\'count\',\r\n expression:=$id,\r\n filter:=intersects($geometry, geometry(@parent))\r\n )', INPUT: 'C:\\Users\\Tobias\\Documents\\GIS DataBase\\ExamplePointLayer.shp', NEW_FIELD: True, OUTPUT: 'memory:Calculated' }
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
Cannot find layer with name or ID ''
OK. Execution took 0.247 s (1 outputs).
Model processed OK. Executed 1 algorithms total in 0.348 s.
Execution completed in 0.40 seconds
Results:
{}

Loading resulting layers
Algorithm 'MyAggregate' finished

**QGIS and OS versions**

QGIS version | 3.12.3-București | QGIS code revision | 8234261527
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | nominatim; QuickOSM; db_manager; MetaSearch; processing

![qgis_aggregate_Graph_Model](https://user-images.githubusercontent.com/67278094/85383334-1f8ba000-b540-11ea-9f5f-54730ca44529.PNG)
[AggregateExample.zip](https://github.com/qgis/QGIS/files/4818294/AggregateExample.zip)

**Comment by tschmetzer** [comment] 2020-06-23 09:08
![qgis_aggregate_run_log](https://user-images.githubusercontent.com/67278094/85384789-c886ca80-b541-11ea-971d-efea5752136b.png)
![qgis_aggregate_run_parameters](https://user-images.githubusercontent.com/67278094/85384797-c9b7f780-b541-11ea-9b4f-22adb8b92fef.png)

**Comment by nyalldawson** [comment] 2020-06-25 21:23
Duplicate of #30397

**Closed by nyalldawson** 2020-06-25 21:23 UTC
Labels: Bug, Modeller, Processing
