### ISSUE TITLE
Vector tile data exceed map frame limits in Print Layour PDF export.

### ISSUE THREAD

**Issue by timotay07** [qgis/QGIS#37687] opened 2020-07-08 16:10 UTC
| ![Print Layout Screen](https://user-images.githubusercontent.com/12573689/86939227-4f759e80-c10f-11ea-85c1-9b67afb78fb2.PNG) | ![PDF Export](https://user-images.githubusercontent.com/12573689/86938980-09b8d600-c10f-11ea-9b5b-f1ce72eade4b.PNG) |
|:---:|:---:|
| Print Layout Map | [PDF Export](https://github.com/qgis/QGIS/files/4891749/PDF.Export.pdf) |

**Describe the bug**

Vector tile data set exceeds the map frame bounds when exported to PDF (Print Layout).  A vector tile layer was added via the MapTiler plugin and displays correctly in the main QGIS window.  Print Layout PDF exporting was tested in Windows 10 and a fresh install of QGIS on Ubuntu 20.04 LTS.

**How to Reproduce**
1.  Load vector tile layer in QGIS.
2.  Create empty Print Layout page 150 dpi (Ledger paper size).
3.  Add map window with frame.
4.  Export PDF with default settings.  Exporting with simplified geometry and GeoPDF produce similar results. 

**QGIS and OS versions**

QGIS version | 3.14.0-Pi | 9f7028fd23
-- | -- | -- 
OS Version | Windows 10 (10.0) | Ubuntu 20.04 LTS

**Comment by gioman** [comment] 2020-07-08 16:14
@timotay07 duplicate of https://github.com/qgis/QGIS/issues/37443

**Closed by gioman** 2020-07-08 16:14 UTC
Labels: Bug

**Comment by timotay07** [comment] 2020-07-08 16:23
Ah sorry.  I searched for open issues reguading this bug and missed #37443 prior to submitting.
