### ISSUE TITLE
Ubuntu Groovy - can't install QGIS 3.16 (no repository)

### ISSUE THREAD

**Issue by sokolic** [qgis/QGIS#40118] opened 2020-11-17 09:35 UTC
**Describe the bug**
I can't install QGIS 3.16 on Ubuntu Groovy Gorilla 20.10 as there is no repository available. If I set the repository to _focal_ I get the following dependency errors:

<pre><font color="#26A269"><b>frank@frank-laptop</b></font>:<font color="#12488B"><b>~</b></font>$ sudo apt install qgis qgis-plugin-grass
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqgis-app3.16.0 : Depends: libgsl23 (&gt;= 2.5) but it is not installable
 libqgis-core3.16.0 : Depends: libprotobuf-lite17 but it is not installable
 qgis-plugin-grass : Depends: grass-core but it is not going to be installed
                     Depends: grass782 but it is not installable
 qgis-providers : Depends: qtbase-abi-5-12-8 but it is not installable
<font color="#C01C28"><b>E: </b></font>Unable to correct problems, you have held broken packages.
</pre>

**How to Reproduce**

1. Follow the Quickstart instructions for Debian/Ubuntu on the QGIS Installers web page.
2. Note: The Quickstart instructions automatically insert _groovy_ into the sources list but this repository doesn't exist yet so I manually changed this to _focal_.

**QGIS and OS versions**

Ubuntu Groovy Gorilla 20.10; QGIS 3.16.

**Additional context**

I am able to successfully install QGIS 3.17 Master.

**Comment by vpavic** [comment] 2020-11-24 11:32
This appears to be a duplicate of #39764.

**Closed** 2020-11-24 11:51 UTC
Labels: Build/Install, Feature Request
