### ISSUE TITLE
QGIS keeps freezing then crashes

### ISSUE THREAD

**Issue by Shirleyzh** [qgis/QGIS#38639] opened 2020-09-08 04:49 UTC
I use Windows 10 and proxy server. Because the old QGIS (I forgot the version) started crashing when I tried to load data, I decided to remove everything from the computer and reinstall it from scratch. So I downloaded the latest OSGEO4W from the OSGEO4W website. After the installation, whenever I try to load data, or use browser to browse data, or config setting, QGIS freezes then gives the crash message. I tried on QGIS 3.14.15 and QGIS 3.10.9; then tried removing the data under AppData/Roaming/QGIS and AppData/Local/QGIS to have a new start, QGIS still has the same issue. 

Could you please help? Thanks.

Here is the report:
Crash ID: 67d946f7e16887bfd939dfe454d37ea8d66bc49c

Stack Trace

QSslKey::operator!= :
QSslKey::operator!= :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.9-A Coru�a
QGIS code revision: bf47e9d3e1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2020-09-08 08:08
@Shirleyzh does it happens on a different machine?

**Comment by Shirleyzh** [comment] 2020-09-10 02:12
Sorry for the late reply. I was out of the office in the last couple of days. 

Yes, it happens on another machine too.

**Comment by gioman** [comment] 2020-09-10 10:13
> Yes, it happens on another machine too.

@Shirleyzh this is not a general issue, of course. What have in common the machine that you have tested? an aggressive AV software? Is the proxy a factor in the crashes?

**Comment by uclaros** [comment] 2020-09-10 12:06
Same or related with: #37121, #38346

**Comment by Shirleyzh** [comment] 2020-09-11 06:30
Thanks. I am able to solve the start-up crash by changing the proxy server settings and clearing network authentication cache after talking to one of my workmates who experienced the same issue. Now QGIS seems okay after start-up but it still crashes when I try to install plugins. 

I use QGIS fair bit and in the past I had never experienced such issue - we always use proxy server to access internet.  Is there any other settings that I can change? 

Thanks.

**Comment by gioman** [comment] 2020-09-11 12:31
> but it still crashes when I try to install plugins

@Shirleyzh duplicate of https://github.com/qgis/QGIS/issues/33919 ?

**Comment by Shirleyzh** [comment] 2020-09-14 00:09
Yep same problem. It happens when I click on the name of a plugin in the list.

**Closed** 2020-09-14 09:02 UTC
Labels: Bug, Feedback
