### ISSUE TITLE
WFS QgsVectorLayer doesn't honor restrictToRequestBBOX setting

### ISSUE THREAD

**Issue by symbioquine** [qgis/QGIS#40826] opened 2021-01-03 06:28 UTC
**Describe the bug**

The documentation at https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.selectedFeatures seems to indicate pretty clearly that passing `restrictToRequestBBOX=1` in the parameters should enable BBOX filtering for the layer.

![image](https://user-images.githubusercontent.com/30754460/103472299-e3cc6100-4d40-11eb-8af4-8f55ed7c73ba.png)

Unfortunately, it looks like the way the `QgsWFSDataSourceURI` constructor [lowercases all the parameters](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/providers/wfs/qgswfsdatasourceuri.cpp#L50-L56) prevents the `restrictToRequestBBOX` parameter from being honored in the [`QgsWFSDataSourceURI::isRestrictedToRequestBBOX` method](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/providers/wfs/qgswfsdatasourceuri.cpp#L343-L354).

Interestingly, as a work-around passing the undocumented `bbox=1` parameter/value does cause BBOX filtering to be enabled because of [this code](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/providers/wfs/qgswfsdatasourceuri.cpp#L101-L102).

This also means that the parameter [munging for backwards compatibility here](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/providers/wfs/qgswfsdatasourceuri.cpp#L349-L351) has been broken for 2 years since [this commit](https://github.com/qgis/QGIS/commit/669f6bb4b7f6a4c244a577a9ad2c95f10bc2b6bd) and (if nobody has complained) could probably be removed.

**How to Reproduce**

```Python
QgsExpressionContextUtils.globalScope().variable('qgis_version')

QgsSettings().value("Windows/WFSSourceSelect/FeatureCurrentViewExtent", None)

QgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))

vlayer = QgsVectorLayer('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326&restrictToRequestBBOX=1', 'mapserver_demo_cities', 'WFS')

vlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117.5639140180201565 32.16946998906087174, -92.70254915457967115 32.16946998906087174, -92.70254915457967115 47.62573361642623126, -117.5639140180201565 47.62573361642623126, -117.5639140180201565 32.16946998906087174))'))
```

```Python
>>> QgsExpressionContextUtils.globalScope().variable('qgis_version')
'3.16.0-Hannover'
>>> QgsSettings().value("Windows/WFSSourceSelect/FeatureCurrentViewExtent", None)
'true'
>>> QgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))
<PyQt5.QtCore.QMetaObject.Connection object at 0x7fc82c693f20>
>>> vlayer = QgsVectorLayer('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326&restrictToRequestBBOX=1', 'mapserver_demo_cities', 'WFS')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&MAXFEATURES=1&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=cities')
>>> vlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117.5639140180201565 32.16946998906087174, -92.70254915457967115 32.16946998906087174, -92.70254915457967115 47.62573361642623126, -117.5639140180201565 47.62573361642623126, -117.5639140180201565 32.16946998906087174))'))
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&RESULTTYPE=hits')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
```

Notice how no `BBOX` parameter appears in the `GetFeature` requests which are being made.

**QGIS and OS versions**

3.16.0-Hannover

**Additional context**

Happy to send a PR for a fix if this issue can serve to determine whether the correct outcome is.

My inclination would be to;
* Update the constructor of `QgsWFSDataSourceURI` to honor all the case sensitive parameters [documented here](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/core/vector/qgsvectorlayer.h#L185-L191)
* Update [the documentation for `QgsVectorLayer`](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/core/vector/qgsvectorlayer.h#L185-L191) to explain that passing either `restrictToRequestBBOX=1` or `bbox=[^&]+` will enable BBOX filtering
* Remove [these lines](https://github.com/qgis/QGIS/blob/1dd80e93f10d930eb8ac071778db12369242e2b1/src/providers/wfs/qgswfsdatasourceuri.cpp#L349-L351) since they have been broken for 2 years

**Comment by roya0045** [comment] 2021-01-03 10:37
If you provide a PR for an existing it would be appreciated! We just need to make sure that other server users can confirm the sam thing or if this issue is still present in the latest version.

**Comment by symbioquine** [comment] 2021-01-03 15:35
Thanks for the quick reply @roya0045!

> We just need to make sure that other server users can confirm the sam thing

I may be misunderstanding but if you're referring to QGIS Server, I think that may not be relevant. The issue here affects QGIS acting as a WFS client.

> or if this issue is still present in the latest version.

Here's a one-liner to demonstrate the problem in a docker container;

> `printf "from console.console_output import writeOut\n\ndef _write(self, m):\n    sys.__stdout__.write(m)\n\nwriteOut.write = _write\nQgsExpressionContextUtils.globalScope().variable('qgis_version')\n\nQgsSettings().value('Windows/WFSSourceSelect/FeatureCurrentViewExtent', None)\n\nQgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))\n\nvlayer = QgsVectorLayer('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326&restrictToRequestBBOX=1', 'mapserver_demo_cities', 'WFS')\n\nvlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117 32, -92 32, -92 47, -117 47, -117 32))'))\n\ninput('')\n\nfrom qgis.core import QgsApplication\napp = QgsApplication.instance()\nimport os, signal\nos.kill(app.applicationPid(), signal.SIGTERM)\n" > qgis_issue_40826_repro.py && docker run -it --rm --name qgis -v $(pwd)'/qgis_issue_40826_repro.py:/qgis_issue_40826_repro.py' qgis/qgis:latest sh -c '/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp & qgis_setup.sh && QGIS_DEBUG=1 PYTHONUNBUFFERED=1 DISPLAY=:99 qgis --nologo --noversioncheck  --code /qgis_issue_40826_repro.py'`

**qgis/qgis:release-3_16;**

```sh
$ printf "from console.console_output import writeOut\n\ndef _write(self, m):\n    sys.__stdout__.write(m)\n\nwriteOut.write = _write\nQgsExpressionContextUtils.globalScope().variable('qgis_version')\n\nQgsSettings().value('Windows/WFSSourceSelect/FeatureCurrentViewExtent', None)\n\nQgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))\n\nvlayer = QgsVectorLayer('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326&restrictToRequestBBOX=1', 'mapserver_demo_cities', 'WFS')\n\nvlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117 32, -92 32, -92 47, -117 47, -117 32))'))\n\ninput('')\n\nfrom qgis.core import QgsApplication\napp = QgsApplication.instance()\nimport os, signal\nos.kill(app.applicationPid(), signal.SIGTERM)\n" > qgis_issue_40826_repro.py && docker run -it --rm --name qgis -v $(pwd)'/qgis_issue_40826_repro.py:/qgis_issue_40826_repro.py' qgis/qgis:release-3_16 sh -c '/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp & qgis_setup.sh && QGIS_DEBUG=1 PYTHONUNBUFFERED=1 DISPLAY=:99 qgis --nologo --noversioncheck  --code /qgis_issue_40826_repro.py'
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&MAXFEATURES=1&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=cities')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&RESULTTYPE=hits')

Terminated
```

**qgis/qgis:latest (Digest: sha256:a54dcc064dfa8a9d58fe14e4c53d63eb9299a542740f0b337d2df2582816ebf7);**

```sh
$ docker pull qgis/qgis:latest
latest: Pulling from qgis/qgis
Digest: sha256:a54dcc064dfa8a9d58fe14e4c53d63eb9299a542740f0b337d2df2582816ebf7
Status: Image is up to date for qgis/qgis:latest
docker.io/qgis/qgis:latest
$ printf "from console.console_output import writeOut\n\ndef _write(self, m):\n    sys.__stdout__.write(m)\n\nwriteOut.write = _write\nQgsExpressionContextUtils.globalScope().variable('qgis_version')\n\nQgsSettings().value('Windows/WFSSourceSelect/FeatureCurrentViewExtent', None)\n\nQgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))\n\nvlayer = QgsVectorLayer('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326&restrictToRequestBBOX=1', 'mapserver_demo_cities', 'WFS')\n\nvlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117 32, -92 32, -92 47, -117 47, -117 32))'))\n\ninput('')\n\nfrom qgis.core import QgsApplication\napp = QgsApplication.instance()\nimport os, signal\nos.kill(app.applicationPid(), signal.SIGTERM)\n" > qgis_issue_40826_repro.py && docker run -it --rm --name qgis -v $(pwd)'/qgis_issue_40826_repro.py:/qgis_issue_40826_repro.py' qgis/qgis:latest sh -c '/usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset -nolisten tcp & qgis_setup.sh && QGIS_DEBUG=1 PYTHONUNBUFFERED=1 DISPLAY=:99 qgis --nologo --noversioncheck  --code /qgis_issue_40826_repro.py'
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&MAXFEATURES=1&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=cities')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?restricttorequestbbox=1&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=cities&SRSNAME=urn:ogc:def:crs:EPSG::4326')

Terminated
```

*Note how the outgoing requests include the `restricttorequestbbox=1` param and do not include the `BBOX` param.*

**Comment by roya0045** [comment] 2021-01-03 15:47
@symbioquine sorry I badly expressed myself regarding the server.

**Comment by rduivenvoorde** [comment] 2021-01-04 12:11
@symbioquine nice analysis! Thanks for diving into this!

But, myself I cannot reproduce the issue in QGIS itself:

- if you create a WFS server in QGIS, with https://demo.mapserver.org/cgi-bin/wfs as server, and make sure you tick the 'Only request features overlapping the view extent' checkbox. 
Then:
1) zooming in on some area you will see the BBOX param in the networklogger
2) hovering over the layer you see the datasource-uri has a **restrictToRequestBBOX='1'**
See
![Screenshot-20210104110834-1672x836](https://user-images.githubusercontent.com/731673/103524267-91dd2580-4e7d-11eb-8050-4a698fda7713.png)

Also I think there is some confusion about what a 'uri' is in QGIS-lingua.
Historically this was a 'path' or 'connection uri to a db', later the 'http-uri's' were added.. So this works:

```
qgis.utils.iface.addVectorLayer(
"https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=bestuurlijkegrenzen:provincies&SRSNAME=EPSG:28992",
"wfs example",
"WFS")
```
 But it is better to split it up in the real 'url' and the other (dataprovider specific) 'uri-elements'.

So: do the same but then with an url part in the uri:

```
qgis.utils.iface.addVectorLayer(
"typename=bestuurlijkegrenzen:provincies url=https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&VERSION=1.0.0",
"wfs example",
"WFS")
```

OR with your restrictToRequestBBOX parameter:
```

qgis.utils.iface.addVectorLayer(
"restrictToRequestBBOX='1' typename=bestuurlijkegrenzen:provincies url=https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&VERSION=1.0.0",
"wfs example",
"WFS")
```
In the last 2 examples above you see that QGIS rightfully adds the BBOX=param in the last example.

So: not sure about your other conclusions, but can it be that the mixed wording of uri and url in QGIS datasource params can be the result of your confusion?
So: restrictToRequestBBOX is not supposed to be an URL-query-parameter, but an QGIS-datasource-uri element?

**Comment by symbioquine** [comment] 2021-01-04 18:15
@rduivenvoorde thanks for the detailed response!

> But, myself I cannot reproduce the issue in QGIS itself

I wondered about that too since the behavior was only appearing when creating vector layers via the Python API.

With your insight I was able to create the following Python snippet which does exhibit the correct BBOX filtering behavior;

```python
QgsExpressionContextUtils.globalScope().variable('qgis_version')

QgsSettings().value('Windows/WFSSourceSelect/FeatureCurrentViewExtent', None)

QgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))

vlayer = QgsVectorLayer("pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:4326' typename='continents' url='https://demo.mapserver.org/cgi-bin/wfs' version='1.1.0'", 'mapserver_demo_cities', 'WFS')

vlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117 32, -92 32, -92 47, -117 47, -117 32))'))
```

Which produced:

```
QgsExpressionContextUtils.globalScope().variable('qgis_version')
'3.16.0-Hannover'
QgsSettings().value('Windows/WFSSourceSelect/FeatureCurrentViewExtent', None)
'true'
QgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(lambda request_params: print(request_params.request().url()))
<PyQt5.QtCore.QMetaObject.Connection object at 0x7f05e191feb0>
vlayer = QgsVectorLayer("pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:4326' typename='continents' url='https://demo.mapserver.org/cgi-bin/wfs' version='1.1.0'", 'mapserver_demo_cities', 'WFS')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=continents&MAXFEATURES=1&SRSNAME=urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=1.1.0')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=continents')
vlayer.selectByRect(QgsRectangle.fromWkt('POLYGON((-117 32, -92 32, -92 47, -117 47, -117 32))'))
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=continents&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=32,-117,47,-92,urn:ogc:def:crs:EPSG::4326')
PyQt5.QtCore.QUrl('https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=continents&RESULTTYPE=hits&BBOX=32,-117,47,-92,urn:ogc:def:crs:EPSG::4326')
```

> Also I think there is some confusion about what a 'uri' is in QGIS-lingua.
> Historically this was a 'path' or 'connection uri to a db', later the 'http-uri's' were added.. So this works:

I think this is the heart of the issue since (as far as I can tell) it doesn't have anything to do with the [formal definition of a URI](https://tools.ietf.org/html/rfc3986).

I reread the `QgsWFSDataSourceURI` code with this understanding in mind and I think I figured out what's going on. The "true url/uri parameters" are lowercased as I described previously, but those space-delimited parameters survive by way of [this member initializer](https://github.com/qgis/QGIS/blob/82dd4fcbbc92ad6b1f1527aae1a6ce6437f56551/src/providers/wfs/qgswfsdatasourceuri.cpp#L25).

> So: not sure about your other conclusions, but can it be that the mixed wording of uri and url in QGIS datasource params can be the result of your confusion?
> So: restrictToRequestBBOX is not supposed to be an URL-query-parameter, but an QGIS-datasource-uri element?

Yes to both of these.

At this point this issue *could* be closed as "working as expected", however I think that would miss a big opportunity to at least make the documentation clearer if not also make the behavior less surprising. I'm happy to help make the changes if we can agree on the strategy...

I would recommend one or both of the following;
1. Documentation updates;
  * Update the documentation for `QgsVectorLayer` to include some example "QGS-datasource-uri" including the "non-url" parameters and a note indicating that the URIs the class documentation describes aren't RFC compliant.
  * Update the documentation for `QgsDataSourceUri` to explain that the URIs it parses/creates aren't RFC compliant, but are instead an internal "QGIS-only URI concept".
2. Also accept the documented WFS parameters as URL parameters - this would make the behavior more closely follow the principle of least surprise since users could bring their existing knowledge of what valid URLs/URIs are without learning a QGIS-specific definition of them. Users who skim the documentation to find the `restrictToRequestBBOX` parameter can add it to their URLs normally without switching to using the `QgsDataSourceUri` class to construct the "URI". I believe the resulting URLs in that case would be within the bounds of the WFS specs because WFS allows for vendor-specific URL parameters.

**Comment by rduivenvoorde** [comment] 2021-01-06 07:47
@symbioquine if you ask my personal opinion:

1) doc updates: YES please do! not only in the source-docs, but also (a new) part in the QGIS pyqgis cookbook

2) accept those params in the url: I would not do that, as we are mixing up two concepts of uri/url's here from 2 different worlds. 
Another argument not to do it is that I think(!) that the logic to take in the start/capabilities url tries to be a little forgiving too, so when somebody uses a GetMap request (instead of a GetCapabilities request), OR even only the server url, QGIS tries to remove all redundant query-params and only use the server-url and adding &service=w*s&request=getcapabilities (where w*s can be wms, wfs or wcs).

So yes please help :-) 
Thanks!

**Comment by symbioquine** [comment] 2021-01-06 15:56
@rduivenvoorde thanks for the response!

> 2\. [...] Another argument not to do it is that I think(!) that the logic to take in the start/capabilities url tries to be a little forgiving too, so when somebody uses a GetMap request (instead of a GetCapabilities request), OR even only the server url, QGIS tries to remove all redundant query-params and only use the server-url and adding &service=w_s&request=getcapabilities (where w_s can be wms, wfs or wcs).

My impression is that you're making an argument that there would be a potential functionality downside to also accepting these parameters as URL parameters, but I'm not quite following it. Can you please elaborate?

> 2\. [...] QGIS tries to remove all redundant query-params and only use the server-url and adding &service=w_s&request=getcapabilities (where w_s can be wms, wfs or wcs).

There already seems to be [precedent for taking a bunch of parameters](https://github.com/qgis/QGIS/blob/82dd4fcbbc92ad6b1f1527aae1a6ce6437f56551/src/providers/wfs/qgswfsdatasourceuri.cpp#L58-L64) from the URL; SRSNAME, BBOX, TYPENAME, etc. There's even precedent for taking non-WFS/OGC parameters from the URL like AUTHCFG, USERNAME, USER, PASSWORD.

> 2\. accept those params in the url: I would not do that, as we are mixing up two concepts of uri/url's here from 2 different worlds.

Would it actually be "mixing up [the] two concepts" or just making more of the parameters supported under both worlds?

I'm curious whether we can come up with a hypothetical QGIS/WFS user who *benefits* from maintaining the artificial separation where some parameters work via either the URL or the "QGIS URI" and other parameters only work via the "QGIS URI"?

**Comment by rduivenvoorde** [comment] 2021-01-06 16:07
I think the average QGIS user does not even know how WFS requests/parameters look like :-)
They 'just use it as a dataprovider'.... preferably not even knowing the url's...

So I think we are talking about a hypothetical WFS-PyQGIS user here, which (I think) should be able to read api/code and find out that there should be option params.
Here https://qgis.org/pyqgis/master/core/QgsVectorLayer.html?highlight=qgsvectorlayer#module-QgsVectorLayer I read: "The url can be a HTTP url to a WFS server (legacy, e.g. http://foobar/wfs?TYPENAME=xxx&SRSNAME=yyy[&FILTER=zzz]), or, starting with QGIS 2.16, a URI constructed using the QgsDataSourceUri class with the following parameters :"... So I think the 'single'-uri way is actually depricated...
Maybe discuss this on the developers mailing list? To attract more eye-balls? I'm just telling you what I personally think :-)

**Comment by rouault** [comment] 2021-01-23 17:55
> So I think the 'single'-uri way is actually depricated...

Yes using a WFS URL as the Datasource URI was only for backward compatibility. We could probably retire it at some point. And we do definitely not want to add QGIS specific things like a restrictToRequestBBOX URL query parameter.

**Comment by gioman** [comment] 2021-06-14 07:56
@symbioquine what is the status of this ticket?

**Comment by symbioquine** [comment] 2021-06-14 15:13
I still find the choice to use a custom format but call it a URI/URL when it doesn't follow rfc3986 frustrating and I'd bet many other users will also find this frustrating/confusing moving forward.

That said, I don't personally intend to pursue this further.

**Comment by gioman** [comment] 2021-06-14 16:35
@rduivenvoorde @rouault what about this then?

**Comment by rduivenvoorde** [comment] 2021-06-14 18:53
I was hopng @symbioquine would do some doc pull requests :-)
But else: let's close it

**Closed** 2021-06-14 21:05 UTC
Labels: Bug, Feedback, WFS data provider
