### ISSUE TITLE
Union geoprocessing error

### ISSUE THREAD

**Issue by py-qgis-user** [qgis/QGIS#37032] opened 2020-06-08 07:11 UTC
**Describe the bug**
See dataset for behavior.
Trying to run the union on the dataset causes a "GEOS geoprocessing error difference failed".
Other processes, like Intersection and Difference work.

I first suspected faulty geometries and used 'Check Validity' to check for mistakes. None are found for GEOS or QGIS. I also tried the plugins 'Geometry Checker' and 'Topology Checker'. The first one makes Qgis crash on this dataset. The latter does not crash, and finds some overlap etc.

I found some similar threads (e.g. [#29400](https://github.com/qgis/QGIS/issues/29400)), but from these I do understand how I could resolve the issue.

I also tried 'Fix geometries', which doesn't solve the issue.

The problem does not seem to be related to a specific feature. Using two methods of elimination (1) pasting 1/2 of the features and checking whether or not the error remains, splitting up the part giving the error, etc...
 and 2) deleting features until the error disappears) I was not able to isolate the problem. There seems to be no logic; The error does disappear at a certain moment, but repeating the process and removing/copying different parts does as well. From this I concluded the error is not related to a single feature.

If not a bug, how do we best handle this error? Should we be worried other methods (e.g. intersection) to have a faulty return although it doesn't throw errors?

_EDIT:_ [#31552](https://github.com/qgis/QGIS/issues/31552) might be the same problem. I am however afraid snapping might alter my data to much?

**How to Reproduce**
Run Union on the dataset (input: polygon; overlay: overlay

**QGIS and OS versions**
Error occurs for me and my colleagues
OS:
Windows 10 enterprise 64bit

QGIS:
QGIS version
3.4.5-Madeira
QGIS code revision
89ee6f6e23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.0
Running against GDAL/OGR
2.4.0
Compiled against GEOS
3.7.0-CAPI-1.11.0
Running against GEOS
3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0

**Faulty data**
[test.zip](https://github.com/qgis/QGIS/files/4744423/test.zip)
EPSG 31370

**Comment by gioman** [comment] 2020-06-08 10:42
@py-qgis-user what is the CRS of your data? .prj files are missing.

**Comment by py-qgis-user** [comment] 2020-06-08 10:52
> @py-qgis-user what is the CRS of your data? .prj files are missing.

@gioman EPSG 31370

**Comment by gioman** [comment] 2020-06-08 11:06
Issue confirmed even after passing inputs in "fix geometries" first.

GRASS (v.overlay) and SAGA polygon union are ok.

**Comment by wburt** [comment] 2020-06-18 16:08
I have also been getting this error with union and intersection tools when running largish (100,000 rows) and messy (many resulting slivers) overlays even after running fix geometries. I get the same GEOS geoprocessing error in 3.8.4 and 3.10.5 .

**Comment by nyalldawson** [comment] 2020-06-18 23:43
This is an upstream issue/limitation in the GEOS library, which QGIS uses for performing the union operation (along with PostGIS, GDAL, and almost all other major opensource GIS applications!)

We can't fix it in QGIS, but it **is** being fixed in GEOS. See e.g. http://lin-ear-th-inking.blogspot.com/2020/05/jts-overlay-next-generation.html

**Closed by nyalldawson** 2020-06-18 23:43 UTC
Labels: Bug, Processing

**Comment by py-qgis-user** [comment] 2020-06-19 05:48
@nyalldawson Thanks for the response

Is there a kind of temporary workaround? I understand that JTS Overlay's issues are "notorious in geometric algorithms using floating-point numerics". Does this correspond to the node x/y/z locations or to other geometric aspects or internal computations?

E.g.: if i round the location of the nodes of polygons to the closest mm, would that mitigate the issue?

Any suggestions?

**Comment by gioman** [comment] 2022-02-17 16:01
> I am trying to use union processing on a number of overlapping polygons (approx 50-100) in the same layer. This raises the error discussed in this thread, "GEOS geoprocessing error: intersection failed

@dhasselol please attach/link your dataset.

**Comment by dhasselol** [comment] 2022-02-17 20:58
> > I am trying to use union processing on a number of overlapping polygons (approx 50-100) in the same layer. This raises the error discussed in this thread, "GEOS geoprocessing error: intersection failed
> 
> @dhasselol please attach/link your dataset.

Here is an example that gives me the "intersection failed"-error. Thanks for taking a look.

[ExamplePolygons.zip](https://github.com/qgis/QGIS/files/8092147/ExamplePolygons.zip)

**Comment by gioman** [comment] 2022-02-18 08:33
> Here is an example that gives me the "intersection failed"-error. Thanks for taking a look.

@dhasselol no errors here, both union and intersection.

**Comment by dhasselol** [comment] 2022-02-18 08:50
> > Here is an example that gives me the "intersection failed"-error. Thanks for taking a look.
> 
> @dhasselol no errors here, both union and intersection.

Can you see if I am doing anything incorrect in these images? I am new to QGIS so please excuse me if I'm making a silly error...

I created a new project, loaded the ExamplePolygons-file and opened the union tool. No other steps taken.

![img1](https://user-images.githubusercontent.com/65972113/154649233-76f68a4b-b399-491c-a2bb-2ffcdf34b035.png)
![img2](https://user-images.githubusercontent.com/65972113/154649229-e5522062-162d-4c6d-a9a9-f9e7ed80ee1c.png)

**Comment by dhasselol** [comment] 2022-02-18 19:48
> > Can you see if I am doing anything incorrect in these images?
> 
> @dhasselol it returns the error if you just use a single input. If you use the same layer also for the "overlay layer" it works. Not sure of this has to be considered a bug or not. Probably you can open a new ticket (with your sample data) and see what others say.

Using it as overlay yields a very different result, it doesn't resolve the overlaps as new polygons, which is what I need in this case. Here is an example of a simpler case (since that doesn't give me the error), one with overlay and one without. The one without gives a lot more polygons.

![image](https://user-images.githubusercontent.com/65972113/154751684-6af30ab2-0ce9-407c-9f8c-be8beb5ee54c.png)
![image](https://user-images.githubusercontent.com/65972113/154751757-13daf7ed-ecd7-42b8-89a0-ebba6b110d22.png)

**Comment by gioman** [comment] 2022-02-19 18:50
> Using it as overlay yields a very different

@dhasselol yes, for this reason please open a new ticket, attaching your dataset.
