### ISSUE TITLE
QGIS 3.22.4 - Sort values in attribute table by clicking in field header doesn't always work

### ISSUE THREAD

**Issue by GeoGyro** [qgis/QGIS#47843] opened 2022-03-17 15:45 UTC
### What is the bug or the crash?

Version : QGIS 3.22.4-Białowieża

In the attribute table, it's possible to sort the content of the columns by clicking on the field header (ascending/descending order). Sometimes when sorting on a field, it's impossible to apply another sorting on another column.

It's an unstable behavior because it's not systematic and independent of the type of field (uuid, var char, numeric, integer...).

### Steps to reproduce the issue

- Load a layer
- Open attributes tables
- Sort values by clicking on a field header
- Sort values by clicking on an other field header

### Versions

QGIS 3.22.4-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment] 2022-03-17 15:51
I can also reproduce this on 3.22.4 and 3.24.0.

**Comment by elpaso** [comment] 2022-03-17 15:52
Duplicate of https://github.com/qgis/QGIS/issues/47613

**Closed by elpaso** 2022-03-17 15:52 UTC
Labels: Attribute Table, Bug
