### ISSUE TITLE
Keyboard Shortcuts - Search for Keyboard Shortcut in addition to actions

### ISSUE THREAD

**Issue by Intuos5** [qgis/QGIS#44098] opened 2021-07-09 11:02 UTC
**Feature description.**
When configuring Keyboard Shortcuts, it is very helpful to search for the shortcut strings (e.g. Ctrl + Shift + R). Other software (Blender) have a button to switch between the name of the function and the keyboard string. Preferably, the input box then registers the keys that are pressed down (as opposed to having to type "ctrl shift r" manually.

Here's how it's done in Blender:
![afbeelding](https://user-images.githubusercontent.com/63149655/125068408-bb3d6f00-e0b5-11eb-9208-4e9ded9d9ecc.png)

That allows you to see which inputs are already in use and by what function, without the need to go through conflict pop-up windows.

**Comment by YoannQDQ** [comment] 2023-01-15 22:25
If I'm not mistaken, the search bar already look for the shortcut string (and has been since 2017, cf https://github.com/qgis/QGIS/pull/3925).
I think this issue should be closed as invalid.

**Comment by DelazJ** [comment] 2023-01-16 05:46
Confirmed

**Closed by DelazJ** 2023-01-16 05:46 UTC
Labels: GUI/UX, Feature Request
