### ISSUE TITLE
Crash on Exit 3.8.2 [duplicate,proj_lpz_dist]

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#31465] opened 2019-08-28 10:32 UTC
## User Feedback

first of all: this is a duplicate and as far as I understand this open/closed-issue-thing closed means resolved. Since all other duplicates link to an closed issue I would assume that this issue is already is resolved, which it isn't.

So please keep one issue open, to show that this issue is known, worked on and not resolved yet

description: while closing qgis

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by NathanW2** [comment] 2019-08-28 11:12
I agree.  We can leave this one open if it's still happening.   I am trying to hunt it down on my build but as it doesn't happen all the time it's a bit tricky.  

Did you install using the standalone installers off the main site?  If so it's possible to also install the debug symbols which will give us a better crash report next time.  If you would like I can get you some notes on how to do that.

**Comment by NathanW2** [comment] 2019-08-28 13:57
I'm not sure it's plugin related though. maybe, but I have seen it on clean
installs with no plugins.  I run a clean profile a lot of the times as I
don't really use any plugins for the most part so I'm not sure it is that.

**Comment by Meibes** [comment] 2019-08-28 16:45
I'm using the standalone-installers from the main site, I have always the latest version, the latest ltr version and the last 2.18 version installed. When I install new versions I always uninstall old versions first.

Can you tell me how to install the debug symbols?

I have two plugins installed, one is "[First Aid](https://plugins.qgis.org/plugins/firstaid/)" and the second is "[norGIS ALKIS](https://plugins.qgis.org/plugins/alkisplugin/)". QGIS does crash even if I didn't use any of those two plugins and as far as I understand it, First Aid should fire when there are problems within norGIS.

I have the feeling that the crash does occur more often when I use WMS, but I'm not sure, could be unrelated.

Thanks for the amazing work on QGIS so far, it really is an amazing program!

**Comment by Meibes** [comment] 2019-08-28 18:44
2.18 is outdated like you said but for me some plugins that didn't make it to QGIS3 are still working and I see no reason why I should stop using those plugins. I won't report issues I find there unless they still exist in the current version too

3.8.2 is the current version according to the main site - I'm a normal user, not a senior software engineer or something like that so don't expect me to nightly the compile out of github or the like ;P

this is totally off-topic and you don't have to answer this question to keep this thread clean, but if we are at the "outdated" topic: the current builds on windows are bundled with gdal 2.4+, on linux using flakpak (is this still maintained?) qgis is bundled with gdal 2.3.1 - what is the reason for this? are there complications with packages on linux? just to better understand it

**Comment by Meibes** [comment] 2019-08-29 05:46
By deactivating plugins do you mean the ones I downloaded or also the pre-installed DB Manager, MetaSearch, Processing and others?

**Comment by jef-n** [comment] 2019-08-29 07:11
Related to #28104

**Comment by gioman** [comment] 2019-08-29 12:04
> the ones I downloaded

yes, the 3rd party ones. But deactivating them is at times not enough, better try with a new QGIS profile, which guarantees a clean state.

**Comment by rouault** [comment] 2019-09-17 18:35
I strongly suspect this is the same as https://github.com/qgis/QGIS/issues/31762 (even if the stack traces aren't completely identical, there are common points, the main critical one being QgsCoordinateTransform::invalidateCache() being called by exitQgis())  and will be fixed by the associated pull requests. Closing this once because #31762 has a reproducer attached so is more actionable.

**Closed by rouault** 2019-09-17 18:35 UTC
Labels: Bug
