### ISSUE TITLE
Can't edit embedded models after upgrading to 3.12

### ISSUE THREAD

**Issue by ccamara** [qgis/QGIS#34920] opened 2020-03-06 16:50 UTC
**Describe the bug**

After upgrading to QGIS 3.12 I can't edit any of my embedded models in the QGIS' project, as I used to do before.

**How to Reproduce**

1. Create a new blank profile
1. Open the graphical modeller
2. Create a graphical model with just one simple algorithm and all required inputs and outputs. 
3. Test that algorithm works 
4. On the Processing Toolbox toolbar, right clic on the model just created
5. Only menu for running the model is displayed, with no option to edit it, as it used to be in previous persion

**QGIS and OS versions**

Versió del QGIS | 3.12.0-București | Revisió del codi QGIS | 409bcf8eaa
-- | -- | -- | --
Compilat per Qt | 5.9.5 | S'executa amb Qt | 5.9.5
Compilat per GDAL/OGR | 2.2.3 | S'executa amb GDAL/OGR | 2.2.3
Compilat per GEOS | 3.6.2-CAPI-1.10.2 | S'executa amb GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Versió del client PostgreSQL | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | Versió de SpatiaLite | 4.3.0a
Versió del QWT | 6.1.3 | Versió de QScintilla2 | 2.10.2
Versió del PROJ.4 | 493
Versió OS | Ubuntu 18.04.4 LTS
Active python plugins | processing; MetaSearch; db_manager

**Comment by gioman** [comment] 2020-03-06 17:13
@ccamara duplicate of https://github.com/qgis/QGIS/issues/34627 ?

**Comment by ccamara** [comment] 2020-03-07 00:13
Indeed. Sorry for the duplicate: I promise I searched before, but didn't find it. Feel free to close this one

**Closed** 2020-03-07 09:16 UTC
Labels: Bug, Feedback
