### ISSUE TITLE
QGIS 3.18 export crash

### ISSUE THREAD

**Issue by gexristo** [qgis/QGIS#41892] opened 2021-02-27 09:08 UTC
## User Feedback

QGIS 3.18 keeps crashing whenever I try to export to dfx through the Project drom menu.

## Report Details

**Crash ID**: [4d700434d3e0fb460c9a81b63f4166661261d5f8](https://github.com/qgis/QGIS/search?q=4d700434d3e0fb460c9a81b63f4166661261d5f8&type=Issues)

**Stack Trace**
<pre>
QHash<QModelIndex,QHashDummyValue>::clear qhash.h:591
QgsVectorLayerAndAttributeModel::applyVisibilityPreset qgsdxfexportdialog.cpp:360
QgsDxfExportDialog::mVisibilityPresets_currentIndexChanged qgsdxfexportdialog.cpp:512
QMetaObject::activate :
QWidgetLineControl::`default constructor closure' :
QComboBox::setCurrentIndex :
QComboBox::setCurrentIndex :
QWidgetLineControl::`default constructor closure' :
QMetaObject::activate :
QAbstractItemModel::endInsertRows :
QStandardItemModel::insertRows :
QComboBox::insertItems :
QgsDxfExportDialog::QgsDxfExportDialog qgsdxfexportdialog.cpp:484
QgisApp::dxfExport qgisapp.cpp:7356
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:471
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.0-Zurich
QGIS code revision: bdef9fb328
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by agiudiceandrea** [comment] 2021-02-27 09:49
This seems a duplicate of https://github.com/qgis/QGIS/issues/41858

**Closed** 2021-02-27 11:40 UTC
Labels: Bug
