### ISSUE TITLE
Feature request #12099 not solved, after few years.

### ISSUE THREAD

**Issue by Bandersnatchie** [qgis/QGIS#51407] opened 2023-01-09 13:51 UTC
### Feature description

It is still not possible to export the "Topology Checker" output. And we get the answer it's fixed.

**Comment by DelazJ** [comment] 2023-01-09 13:57
> And we get the answer it's fixed.

Not true. Closed does not mean fixed. And speaking of 12099 (which actually is #20294 in this platform), it is closed due to duplicate. The issue is still there at #16653. So this one is one more duplicate that should get closed.

**Comment by Bandersnatchie** [comment] 2023-01-09 14:04
Aha, so it’s still open? Strange it’s a feature many want to have I think.

Met vriendelijke groet,
Erik van der Knaap

Mobiel: 06 25 68 84 85



Van: Harrissou Sant-anna ***@***.***>
Verzonden: Monday, January 9, 2023 14:58
Aan: qgis/QGIS ***@***.***>
CC: Knaap, van der, Erik ***@***.***>; Author ***@***.***>
Onderwerp: Re: [qgis/QGIS] Feature request #12099 not solved, after few years. (Issue #51407)


And we get the answer it's fixed.

Not true. Closed does not mean fixed. And speaking of 12099 (which actually is #20294<https://github.com/qgis/QGIS/issues/20294> in this platform), it is closed due to duplicate. The issue is still there at #16653<https://github.com/qgis/QGIS/issues/16653>. So this one is one more duplicate that should get closed.

**Comment by nicogodet** [comment] 2023-01-09 14:15
@Bandersnatchie 

I will quote someone here :

"Things don't happen "magically". It always needs someone to do the work or contract with someone else to do the work. Once done, it is shared with everybody.

In this case it seems it never seemed important enough for someone to take the initiative.

Note that by opening this feature request, it won't be implemented automagically either, unless someone does it or contracts someone to do the work. It is different with bug reports. Bug reports, esp. the ones that trigger a crash or data corruption are usually addressed if they can be reproduced and fixed.

See also http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ and http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis-a-follow-up/

Feature requests are still welcome though, as they might trigger someone's interest and it can also be discussed with others - and if you contract with someone to do the implementation work for you, you can reference such a feature request."

**Comment by DelazJ** [comment] 2023-01-09 14:22
So true, @nicogodet 
I'm closing this as a duplicate. If anything else, let's discuss in #16653.

**Comment by Bandersnatchie** [comment] 2023-01-09 14:22
Yes, it’s not “magically” resolved. I looked in the code for myself but my skills are not that good anymore. ☹
Thank you for the answers.

Met vriendelijke groet,
Erik van der Knaap

Mobiel: 06 25 68 84 85



Van: Nicolas Godet ***@***.***>
Verzonden: Monday, January 9, 2023 15:15
Aan: qgis/QGIS ***@***.***>
CC: Knaap, van der, Erik ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [qgis/QGIS] Feature request #12099 not solved, after few years. (Issue #51407)


@Bandersnatchie<https://github.com/Bandersnatchie>

I will quote someone here :

"Things don't happen "magically". It always needs someone to do the work or contract with someone else to do the work. Once done, it is shared with everybody.

In this case it seems it never seemed important enough for someone to take the initiative.

Note that by opening this feature request, it won't be implemented automagically either, unless someone does it or contracts someone to do the work. It is different with bug reports. Bug reports, esp. the ones that trigger a crash or data corruption are usually addressed if they can be reproduced and fixed.

See also http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ and http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis-a-follow-up/

Feature requests are still welcome though, as they might trigger someone's interest and it can also be discussed with others - and if you contract with someone to do the implementation work for you, you can reference such a feature request."

**Closed by DelazJ** 2023-01-09 14:22 UTC
Labels: Feedback, Feature Request
