### ISSUE TITLE
 QGIS is crashing every time I try to "Save As"

### ISSUE THREAD

**Issue by smkraushaar** [qgis/QGIS#35314] opened 2020-03-24 21:48 UTC
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by smkraushaar** [comment] 2020-03-24 21:53
Crash ID: 818d81928994f1817fc9b37e96f865eaf596d8d4


Stack Trace


RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1027
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1855
CApartmentActivator::CreateInstance actvator.cxx:2323
CProcessActivator::CCICallback actvator.cxx:1786
CProcessActivator::AttemptActivation actvator.cxx:1673
CProcessActivator::ActivateByContext actvator.cxx:1519
CProcessActivator::CreateInstance actvator.cxx:1417
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1855
CClientContextActivator::CreateInstance actvator.cxx:713
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1907
ICoCreateInstanceEx objact.cxx:1645
CComActivator::DoCreateInstance immact.hxx:376
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CDrivesFolder::_GetIconOverlayInfo :
CDrivesFolder::GetOverlayIndex :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by smkraushaar** [comment] 2020-03-24 21:54
Please help!

**Comment by nyalldawson** [comment] 2020-03-24 22:00
This particular crash is caused by another piece of software on your computer which has installed a buggy file explorer extension.

**Comment by smkraushaar** [comment] 2020-03-24 22:12
Is there any way to know which program or software is causing the crash? I've uninstalled a few programs but it still won't work.  Thanks so much.

**Comment by roya0045** [comment] 2020-03-24 22:29
Related to #33881

**Comment by roya0045** [comment] 2020-03-24 22:30
And also #32239

**Comment by gioman** [comment] 2020-03-25 09:25
Closing as duplicate of https://github.com/qgis/QGIS/issues/32239

**Closed by gioman** 2020-03-25 09:25 UTC
Labels: Bug
