### ISSUE TITLE
Remove bug ridden & questionable user profiles functionality

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#47000] opened 2022-01-25 20:24 UTC
### Feature description

The user profile capability appears to be poorly supported and maintained to the point that upgrades to a new version of the software frequently break due to issues that disappear when a new user profile is created. This raises the question of what is actually being achieved with user profiles and whether this functionality creates more problems than it is worth.
e.g. I have just updated from 3.22 to 3.23 and found a new problem which disappeared as soon as a new profile was created.

The situation of user profiles breaking and having to be replaced with new ones is, in my opinion, a far more significant issue on Qgis than on any other software that I have ever used in 40 years of computing. For example, user profiles in Firefox browser (the nearest equivalent I can think of) almost never break. Other pieces of software like Gimp that I use every day never have problems with their settings files corrupting.

**Comment by gioman** [comment] 2022-01-25 20:26
> I have just updated from 3.22 to 3.23 and found a new problem which disappeared as soon as a new profile was created.

@enzedrailmaps have you considered/checked if it was because of a buggy 3rd party plugin? usually the problem is there. I don't think that this functionality is going anywhere...

**Comment by nyalldawson** [comment] 2022-01-25 20:28
Ehhh... You're **completely** missing the point. The qgis profile support isn't buggy, but 3rd party plugins frequently are. Making a new profile is just the easiest way to restart from a clean slate with no buggy plugins installed.

So if anything, this request should be "remove 3rs party plugins support", which is a wontfix.

**Closed by nyalldawson** 2022-01-25 20:28 UTC
Labels: Feedback, Feature Request

**Comment by enzedrailmaps** [comment] 2022-01-26 06:26
This is not the case.

I don't use any plugins.

This just pops up randomly every so often when a new version of the software is installed.

**Comment by enzedrailmaps** [comment] 2022-01-26 06:47
Hey look no offence I don't know anything about plugins because I don't use any of them. certainly wasn't using plugin functionality, unless you mean it could just happen if a plugin was installed, as opposed to actually using it.

If you can outline how a plugin would cause that even when not being used and how I can test for this that could help a lot. Thanks.

**Comment by gioman** [comment] 2022-01-26 08:42
> unless you mean it could just happen if a plugin was installed, as opposed to actually using it

@enzedrailmaps yes, that is what we meant.

**Comment by enzedrailmaps** [comment] 2022-02-16 23:37
No I am pursuing this because it is not caused by a plugin. I have replicated the issue in my current installation and there are no plugins installed except for the default ones that can't be removed, so there is definitely an issue in the software due to the profile that doesn't appear to be in the user's ability to correct or due to specific plugins installed.
