### ISSUE TITLE
Digitize Vector by Defined Symbology

### ISSUE THREAD

**Issue by asgharibraheembaloch** [qgis/QGIS#33593] opened 2020-01-03 12:33 UTC
I want a feature or plugin which can digitize my vector data defined by my "symbology", means which can directly digitize my symbols which i defined in layers->properties->symbology

![image](https://user-images.githubusercontent.com/46741864/71723376-41884d80-2e4e-11ea-92b7-f3f3f6e7fc0e.png)

![image](https://user-images.githubusercontent.com/46741864/71723601-14886a80-2e4f-11ea-8a23-0c63c4edb256.png)

**Comment by roya0045** [comment] 2020-01-03 12:36
I'm not too sure I get what you want, basically you would like to be able to select a symbol and generate a feature with the proper attributes without having to set them yourself simply by selecting the symbol that you desire?

**Comment by gioman** [comment] 2020-01-03 12:47
> I want a feature or plugin which can digitize my vector data defined by my "symbology", means which can directly digitize my symbols which i defined in layers->properties->symbology

@asgharibraheembaloch your symbology is data defined, so when digitizing are you filling the attributes that drive your symbols?

**Comment by nyalldawson** [comment] 2020-01-03 21:15
Duplicate of #22257

**Closed by nyalldawson** 2020-01-03 21:15 UTC
Labels: Feature Request, Feedback
