### ISSUE TITLE
SVG-Option not showing in layer styling panel options dropdown

### ISSUE THREAD

**Issue by CodeMoraa** [qgis/QGIS#59434] opened 2024-11-13 08:41 UTC
### What is the bug or the crash?

SVG Option is not showing up in the layer styling panel. And I cant download more symbols from resource sharing plugin cs it shows no host.

![Screenshot 2024-11-13 113413](https://github.com/user-attachments/assets/907523bf-7ecf-46a8-91ad-630dff585ea4)
![Screenshot 2024-11-13 113459](https://github.com/user-attachments/assets/87fa5285-33f4-40b8-ac8b-97ff77bc6e86)

### Steps to reproduce the issue

Re installed QGIS
Checked on active user profile deleted it and restarted qgis it still has the same issue.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/b56115d874">b56115d874</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>anyways_impact_toolbox</td><td>0.9.6</td></tr><tr><td>autoSaver</td><td>2.9</td></tr><tr><td>BatchHeatmaps-master</td><td>1.1</td></tr><tr><td>HCMGIS</td><td>24.10.20</td></tr><tr><td>locationiq-qgis</td><td>3.0.6</td></tr><tr><td>map_tile_loader</td><td>0.2.0</td></tr><tr><td>mmqgis</td><td>2024.11.8</td></tr><tr><td>nominatim</td><td>1.4.5</td></tr><tr><td>OnlineRoutingMapper</td><td>1.0</td></tr><tr><td>ORStools</td><td>1.9.0</td></tr><tr><td>OSMDownloader</td><td>1.0.3</td></tr><tr><td>pyqgis_resource_browser</td><td>0.3.0</td></tr><tr><td>qfieldsync</td><td>v4.11.0</td></tr><tr><td>qgis-maptiler-plugin</td><td>3.3.2</td></tr><tr><td>qgis2web</td><td>3.23.0</td></tr><tr><td>qgis_resource_sharing</td><td>1.0.0</td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>quick_map_services</td><td>0.19.34</td></tr><tr><td>random_points</td><td>1.0.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by NyakudyaA** [comment] 2024-11-13 10:21
Did you check if your internet connection is working properly? I tried the same and was able to download 
![Screenshot 2024-11-13 at 12 19 34](https://github.com/user-attachments/assets/7a733fd3-1b94-444b-9d45-5cb9f31c6f9a)

Also please try with a new profile and see if the issue persists

**Comment by CodeMoraa** [comment] 2024-11-13 11:47
![image](https://github.com/user-attachments/assets/e1369374-3952-480c-b09f-b52d24d65971)
seems to be aproblem with this plugin then

**Comment by agiudiceandrea** [comment] 2024-11-14 17:13
Duplicate of https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/332.

**Closed by agiudiceandrea** 2024-11-14 17:13 UTC
Labels: Bug
