### ISSUE TITLE
Ooops looks like an error loading QGIS

### ISSUE THREAD

**Issue by RossFF80** [qgis/QGIS#49159] opened 2022-06-26 14:00 UTC
### What is the bug or the crash?

Detail:

Could not load qgis_app.dll
Windows Error: Adynamic link library (DLL) initialization routine failed.

Help:

Check C:\Program Files\QGIS 3.22.8\bin\qgis-ltr-bin.env for correct environment pathway.

I keep getting this when I try and download all versions of QIS I need it for my job and nothing is working. I'm losing the will to live. QGIS for idiots

Thanks
Ross Fergusson

### Steps to reproduce the issue

Cannot access QGIS

### Versions

Can't access QGIS

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I've tried to find all files, it says to add in command line. but i'm not sure where the command line is..

**Comment by roya0045** [comment] 2022-06-26 15:37
Insulting others is a great way to get help. just cleanup your installs, use the standalone installer or fix your dependencies by using something like https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency

**Comment by RossFF80** [comment] 2022-06-26 16:18
Many thanks Alex, I was referring to myself knowing nothing about these things.. I will hopefully resolve this issue, with your much appreciated help

**Comment by agiudiceandrea** [comment] 2022-06-26 16:21
Similar to a recently already reported bug https://github.com/qgis/QGIS/issues/49148.

**Comment by jef-n** [comment] 2022-06-27 08:32
duplicate of #49148

**Closed by jef-n** 2022-06-27 08:32 UTC
Labels: Bug
