### ISSUE TITLE
Python console emits qgis._3d import error if built with WITH_3D=off

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#49987] opened 2022-08-28 09:36 UTC
### What is the bug or the crash?

I built master on Ubuntu 22.04 with `ccmake` and `make`. In `ccmake` I disabled various `WITH_` options, one of them `WITH_3D`. QGIS built fine but once I open the Python console I get the following traceback in the (external) terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/me/QGIS/build/output/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis._3d'
```

QGIS and QGIS' Python seem to work fine so I guess this is a non-fatal issue. But I am not sure if it is a safe failure or should get some `try`/`except` around it so I thought I'd file this bug.

I don't know where the resulting `ccmake` configuration is stored. As I disabled other `WITH_` options as well there might be some side effects. If someone tells me how to find it, I can share it.

### Steps to reproduce the issue

1. Clone the QGIS repo
2. `mkdir build; cd build; ccmake ../`
3. Disable WITH_3D
4. `make`
5. Launch built binary from a terminal and open the Python console
6. See the traceback in the terminal

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment] 2022-08-28 20:17
This issue seems similar to the previously reported issue https://github.com/qgis/QGIS/issues/41855.
That issue was fixed with two PR: https://github.com/qgis/QGIS/pull/42634 and https://github.com/qgis/QGIS/pull/42865.
@kannes, is the whole Python error message the one you reported, or is it longer like in https://github.com/qgis/QGIS/issues/41855#issuecomment-816573696?

**Comment by kannes** [comment] 2022-08-29 18:26
Thanks!

It is the full message.

**Comment by agiudiceandrea** [comment] 2022-08-29 20:02
@kannes looking better at your report, it seems to me this is probably not actually a bug. In your case the Python console opens without issue and the error message is correctly reported only in the terminal (to stderr) as it is probably intended by design.

In the case of https://github.com/qgis/QGIS/issues/41855, on Windows (MinGW build without 3d support), the Python console didn't open at all: the issue was in the Write function which used stderr to write the qgis._3d import error without previously checking its availability.

**Comment by kannes** [comment] 2022-09-01 15:53
If it was fully intentional I would have expected for the exception to be caught somewhere?
I imagine there are other code paths that also have to check if 3D support was built in and not run if not but maybe it is different for the Python module?

**Comment by agiudiceandrea** [comment] 2022-09-01 16:47
The error is caught in the `runsource` function https://github.com/qgis/QGIS/blob/0c577f07ba45e3903eb09b5239d2d5da572e8f6c/python/console/console_sci.py#L549-L561 then it is formatted using `traceback.format_exception function` and then it is sent to stderr using the `write` function.

**Comment by kannes** [comment] 2022-09-01 18:53
Ah! And that gets called for qgis._3d because of 
https://github.com/qgis/QGIS/blob/0c577f07ba45e3903eb09b5239d2d5da572e8f6c/python/console/console_sci.py#L72-L76
iterating over
https://github.com/qgis/QGIS/blob/0c577f07ba45e3903eb09b5239d2d5da572e8f6c/python/console/console_sci.py#L43-L48

We could change that to:
```

_init_commands = [
	# Python
	"import sys",
	"import os", 
	"from pathlib import Path",
	"import re", 
	"import math", 
	# QGIS
	"from qgis.core import *",
    "from qgis.gui import *",
	"import processing",
	"import qgis.utils",
	"from qgis.utils import iface",
	# Qt
	"from qgis.PyQt.QtCore import *",
	"from qgis.PyQt.QtGui import *",
	"from qgis.PyQt.QtWidgets import *",
	"from qgis.PyQt.QtNetwork import *",
	"from qgis.PyQt.QtXml import *"
]
# some parts of QGIS might not have been compiled in
if importlib.util.find_spec("qgis.analysis"):
    _init_commands.append("from qgis.analysis import *")
if importlib.util.find_spec("qgis._3d"):
    _init_commands.append("from qgis._3d import *")
``` 

but that would automatically import `qgis` as well (https://docs.python.org/3/library/importlib.html#importlib.util.find_spec) and I am not sure if it is a good idea...

**Comment by kannes** [comment] 2022-09-01 19:33
grayshade in IRC had the great idea to put the optional module imports into `try/except` blocks right within the `_init_commands`:

```
_init_commands = [
	# Python
	"import sys",
	"import os", 
	"from pathlib import Path",
	"import re", 
	"import math", 
	# QGIS
	"from qgis.core import *",
    "from qgis.gui import *",
    ## analysis might not be compiled in
    """
try:
    from qgis.analysis import *
except ModuleNotFoundError:
    pass
""",
    ## 3D might not be compiled in
    """
try:
    from qgis._3d import *
except ModuleNotFoundError:
    pass
""",
	"import processing",
	"import qgis.utils",
	"from qgis.utils import iface",
	# Qt
	"from qgis.PyQt.QtCore import *",
	"from qgis.PyQt.QtGui import *",
	"from qgis.PyQt.QtWidgets import *",
	"from qgis.PyQt.QtNetwork import *",
	"from qgis.PyQt.QtXml import *"
]
```
works like a charm.

I'll make a PR some of the coming days.

**Closed** 2022-09-03 20:05 UTC
Labels: Build/Install, Bug, Python Console
