### ISSUE TITLE
Crash when export to PDF

### ISSUE THREAD

**Issue by ingfzamora** [qgis/QGIS#37079] opened 2020-06-10 02:59 UTC
I got a crash when export to PDF it was working well yesterday but now there is a problem

Crash ID: ID not generated due to missing information.

Your version of QGIS install might not have debug information included or we couldn't get crash information.

Stack Trace
Stack trace could not be generated.

QGIS Info

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment] 2020-06-10 10:01
@ingfzamora please try with a new QGIS profile.

**Comment by gioman** [comment] 2020-06-11 08:13
@ingfzamora please add all the requested infos




**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**

**Comment by gioman** [comment] 2020-06-11 08:14
Related to https://github.com/qgis/QGIS/issues/36927 ?

**Comment by jgrocha** [comment] 2020-06-12 14:27
> Well at the end I decided to reinstall windows and qgis now it works fine

Since the issue is no longer valid after reinstall, I'll close this issue.

**Closed by jgrocha** 2020-06-12 14:27 UTC
Labels: Bug, Feedback
