### ISSUE TITLE
Crash when viewing point cloud

### ISSUE THREAD

**Issue by jaspermowatt** [qgis/QGIS#42830] opened 2021-04-17 11:14 UTC
Qgis Crashes when point cloud (34mb) is loaded as a .laz file and I try to rotate in the 3D viewer. Initally works for a few seconds, then freezes and crashes. Repeatable.

Dropbox file containing the data: https://www.dropbox.com/sh/wypm2l8ihkonuup/AAC0LEKvbcIB7GhQi9zMspdka?dl=0

Steps to reproduce:

New QGIS
Navigate to: odm_georeferencing --> select odm_georeferenced_model.laz and drag and drop into QGIS
Open a new 3D map view
Rotate 3D map and it crashes.

Link to pdf QGIS log: https://www.dropbox.com/s/4w54hl9is0vmvle/qgis%20error.pdf?dl=0

Process:               QGIS [20027]
Path:                  /Applications/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis3
Version:               3.18.1 (3.18.1 [])
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           QGIS [20027]
User ID:               504

Date/Time:             2021-04-17 12:09:19.435 +0100
OS Version:            macOS 11.2.3 (20D91)

Thanks
[qgis error.pdf](https://github.com/qgis/QGIS/files/6329119/qgis.error.pdf)

**Comment by gioman** [comment] 2021-04-17 17:57
On master/linux I could not replicate the crash, but CPU usage rocketed.

**Comment by tz2436** [comment] 2021-04-23 14:40
Same issue. Attached the full stack trace.
[210423_QGIS Problem Report.docx](https://github.com/qgis/QGIS/files/6366045/210423_QGIS.Problem.Report.docx)

**Comment by wonder-sk** [comment] 2021-05-04 14:09
This looks like a duplicate of #42734 - the error logs are the same.

**Closed by wonder-sk** 2021-05-04 14:09 UTC
Labels: Bug, MacOS, Point Clouds
