### ISSUE TITLE
Crash changing font marker size on Windows

### ISSUE THREAD

**Issue by danzig666** [qgis/QGIS#34056] opened 2020-01-27 13:17 UTC
**Describe the bug**
QGIS 3.10.2 hangs for minutes and sometimes crashes to desktop without showing the crash report screen when zooming/panning with the attached project. Layer symbology is the most likely culprit. 

**How to Reproduce**

Load the attached project zoom in and out a few times.

**QGIS and OS versions**

Windows 10 (1909 x64)

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

[crash.zip](https://github.com/qgis/QGIS/files/4117266/crash.zip)

**Comment by saberraz** [comment] 2020-01-27 13:32
Seems like duplicate of https://github.com/qgis/QGIS/issues/33902

Could you try QGIS master/nightly?

**Comment by roya0045** [comment] 2020-01-27 13:58
Does it only occur with a specific layer or combination of layers ?

**Comment by danzig666** [comment] 2020-01-27 14:02
> Seems like duplicate of #33902
> 
> Could you try QGIS master/nightly?

I just did try the latest nightly, same outcome.

**Comment by danzig666** [comment] 2020-01-27 14:04
> Does it only occur with a specific layer or combination of layers ?

Only with the attached layer and another one with similar symbology (containing font markers)

**Comment by danzig666** [comment] 2020-01-27 21:55
> Seems like duplicate of #33902
> 
> Could you try QGIS master/nightly?

It's not a duplicate, #33902 is fixed in 3.10.2

**Comment by nyalldawson** [comment] 2020-01-28 01:04
I can't reproduce. Do you have a crash report handy?

**Comment by danzig666** [comment] 2020-01-28 07:51
> I can't reproduce. Do you have a crash report handy?

There's no crash report:
![TMv6bV5PMa](https://user-images.githubusercontent.com/5346511/73244822-21c51a80-41ab-11ea-90be-71676225bf09.gif)

**Comment by gioman** [comment] 2020-01-28 11:27
@danzig666 I also can't confirm on 3.10.2 and master on Windows. Have you tried with a new QGIS profile?

**Comment by danzig666** [comment] 2020-01-28 11:50
> @danzig666 I also can't confirm on 3.10.2 and master on Windows. Have you tried with a new QGIS profile?

Yes, I created the video above with a clean profile.
I tried it on multiple PCs too, all with the same result. Sometimes it just hangs for 10-15 seconds, sometimes it crashes.

**Comment by i-s-o** [comment] 2020-01-28 21:32
> Layer symbology is the most likely culprit.

I think @danzig666 got it right. The root cause of the problem isn't zooming in and out. It is just that while zooming, the font becomes too large for Windows (or Qt5) to handle. To reliably crash QGIS:
* Open the example project
* `Configure Symbol...` for one of the categories
* Click on symbol layer `Font marker`
* Highlight the value in the `Size` box and type over a large number e.g. `2000`.
* Keep typing one zero at a time until you get the following error message in QGIS: `CRITICAL    Qt : DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="MS Shell Dlg 2", pointsize=150000, pixelsize=200000, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Tahoma", lfWidth=0, lfHeight=-200000) dpi=96`
* Type one more zero and QGIS disappears!
![2020-01-28_16-13-22](https://user-images.githubusercontent.com/1661549/73306086-7b4c3a00-41e9-11ea-8ccb-b4ab029f682e.gif)

@nyalldawson this is what I see in DebugView++:
```
1	18.798730	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
2	18.799224	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
3	18.799875	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
4	18.800613	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
5	22.564573	22700	qgis-dev-bin-g7.exe	Warning: DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="MS Shell Dlg 2", pointsize=150000, pixelsize=200000, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Tahoma", lfWidth=0, lfHeight=-200000) dpi=96
6	22.569641	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
... [same message repeats many times]
516	25.986442	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
517	25.986868	22700	qgis-dev-bin-g7.exe	Critical: QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
518	25.987843	22700	qgis-dev-bin-g7.exe	Fatal: createDIB: CreateDIBSection failed (761905x2285714, format: 4)
```
Here is the call stack in VS while following the above procedure:

```
ucrtbase.dll!00007ff8a1f0e91e()	Unknown
qgis_app.dll!myMessageOutput(QtMsgType type, const QMessageLogContext & __formal, const QString & msg) Line 442	C++
Qt5Core.dll!qt_message_print(QtMsgType msgType, const QMessageLogContext & context, const QString & message) Line 1797	C++
Qt5Core.dll!qt_message(QtMsgType msgType, const QMessageLogContext & context, const char * msg, char * ap) Line 366	C++
Qt5Core.dll!QMessageLogger::fatal(const char * msg, ...) Line 877	C++
qwindows.dll!createDIB(HDC__ * hdc, int width, int height, QImage::Format format, unsigned char * * bitsIn) Line 109	C++
qwindows.dll!QWindowsNativeImage::QWindowsNativeImage(int width, int height, QImage::Format format) Line 120	C++
qwindows.dll!QWindowsFontEngine::drawGDIGlyph(HFONT__ * font, unsigned int glyph, int margin, const QTransform & t, QImage::Format mask_format) Line 1032	C++
qwindows.dll!QWindowsFontEngine::alphaMapForGlyph(unsigned int glyph, const QTransform & xform) Line 1080	C++
qwindows.dll!QWindowsFontEngine::alphaMapForGlyph(unsigned int t) Line 112	C++
Qt5Gui.dll!QFontEngine::addBitmapFontToPath(double x, double y, const QGlyphLayout & glyphs, QPainterPath * path, QFlags<enum QTextItem::RenderFlag> flags) Line 805	C++
qwindows.dll!QWindowsFontEngine::addOutlineToPath(double x, double y, const QGlyphLayout & glyphs, QPainterPath * path, QFlags<enum QTextItem::RenderFlag> flags) Line 861	C++
Qt5Gui.dll!QFontEngineMulti::addOutlineToPath(double x, double y, const QGlyphLayout & glyphs, QPainterPath * path, QFlags<enum QTextItem::RenderFlag> flags) Line 2111	C++
Qt5Gui.dll!QPainterPath::addText(const QPointF & point, const QFont & f, const QString & text) Line 1192	C++
Qt5Gui.dll!QPainterPath::addText(double x, double y, const QFont & f, const QString & text) Line 363	C++
qgis_core.dll!QgsFontMarkerSymbolLayer::renderPoint(QPointF point, QgsSymbolRenderContext & context) Line 3242	C++
qgis_core.dll!QgsMarkerSymbolLayer::drawPreviewIcon(QgsSymbolRenderContext & context, QSize size) Line 459	C++
qgis_core.dll!QgsSymbolLayerUtils::symbolLayerPreviewIcon(const QgsSymbolLayer * layer, QgsUnitTypes::RenderUnit u, QSize size, const QgsMapUnitScale & __formal) Line 865	C++
qgis_gui.dll!SymbolLayerItem::updatePreview() Line 160	C++
qgis_gui.dll!QgsSymbolSelectorWidget::updateLayerPreview() Line 473	C++
qgis_gui.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsSymbolSelectorWidget::*)(void) __ptr64>::call(void(QgsSymbolSelectorWidget::*)() f, QgsSymbolSelectorWidget * o, void * * arg) Line 134	C++
qgis_gui.dll!QtPrivate::FunctionPointer<void (__cdecl QgsSymbolSelectorWidget::*)(void) __ptr64>::call<QtPrivate::List<>,void>(void(QgsSymbolSelectorWidget::*)() f, QgsSymbolSelectorWidget * o, void * * arg) Line 168	C++
qgis_gui.dll!QtPrivate::QSlotObject<void (__cdecl QgsSymbolSelectorWidget::*)(void) __ptr64,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 397	C++
Qt5Core.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3759	C++
qgis_gui.dll!QgsLayerPropertiesWidget::changed() Line 169	C++
qgis_gui.dll!QgsLayerPropertiesWidget::emitSignalChanged() Line 325	C++
qgis_gui.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsLayerPropertiesWidget::*)(void) __ptr64>::call(void(QgsLayerPropertiesWidget::*)() f, QgsLayerPropertiesWidget * o, void * * arg) Line 134	C++
qgis_gui.dll!QtPrivate::FunctionPointer<void (__cdecl QgsLayerPropertiesWidget::*)(void) __ptr64>::call<QtPrivate::List<>,void>(void(QgsLayerPropertiesWidget::*)() f, QgsLayerPropertiesWidget * o, void * * arg) Line 168	C++
qgis_gui.dll!QtPrivate::QSlotObject<void (__cdecl QgsLayerPropertiesWidget::*)(void) __ptr64,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 397	C++
Qt5Core.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3759	C++
qgis_gui.dll!QgsSymbolLayerWidget::changed() Line 154	C++
qgis_gui.dll!QgsFontMarkerSymbolLayerWidget::setSize(double size) Line 3421	C++
qgis_gui.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<0>,QtPrivate::List<double>,void,void (__cdecl QgsFontMarkerSymbolLayerWidget::*)(double) __ptr64>::call(void(QgsFontMarkerSymbolLayerWidget::*)(double) f, QgsFontMarkerSymbolLayerWidget * o, void * * arg) Line 134	C++
qgis_gui.dll!QtPrivate::FunctionPointer<void (__cdecl QgsFontMarkerSymbolLayerWidget::*)(double) __ptr64>::call<QtPrivate::List<double>,void>(void(QgsFontMarkerSymbolLayerWidget::*)(double) f, QgsFontMarkerSymbolLayerWidget * o, void * * arg) Line 168	C++
qgis_gui.dll!QtPrivate::QSlotObject<void (__cdecl QgsFontMarkerSymbolLayerWidget::*)(double) __ptr64,QtPrivate::List<double>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 397	C++
Qt5Core.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3759	C++
Qt5Widgets.dll!QDoubleSpinBoxPrivate::emitSignals(EmitPolicy ep, const QVariant & old) Line 1115	C++
Qt5Widgets.dll!QAbstractSpinBoxPrivate::setValue(const QVariant & val, EmitPolicy ep, bool doUpdate) Line 1743	C++
Qt5Widgets.dll!QAbstractSpinBoxPrivate::_q_editorTextChanged(const QString & t) Line 1508	C++
Qt5Core.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3773	C++
Qt5Widgets.dll!QLineEdit::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 371	C++
Qt5Core.dll!QMetaObject::activate(QObject * sender, int signalOffset, int local_signal_index, void * * argv) Line 3773	C++
Qt5Widgets.dll!QWidgetLineControl::finishChange(int validateFromState, bool update, bool edited) Line 739	C++
Qt5Widgets.dll!QWidgetLineControl::processKeyEvent(QKeyEvent * event) Line 1939	C++
Qt5Widgets.dll!QLineEdit::keyPressEvent(QKeyEvent * event) Line 1735	C++
Qt5Widgets.dll!QWidget::event(QEvent * event) Line 8968	C++
Qt5Widgets.dll!QLineEdit::event(QEvent * e) Line 1488	C++
qgis_gui.dll!QgsFilterLineEdit::event(QEvent * event) Line 215	C++
Qt5Widgets.dll!QAbstractSpinBox::keyPressEvent(QKeyEvent * event) Line 1108	C++
Qt5Widgets.dll!QWidget::event(QEvent * event) Line 8968	C++
Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3728	C++
Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3121	C++
qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 418	C++
Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1048	C++
Qt5Widgets.dll!QWidgetWindow::handleKeyEvent(QKeyEvent * event) Line 700	C++
Qt5Widgets.dll!QWidgetWindow::event(QEvent * event) Line 274	C++
Qt5Widgets.dll!QApplicationPrivate::notify_helper(QObject * receiver, QEvent * e) Line 3728	C++
Qt5Widgets.dll!QApplication::notify(QObject * receiver, QEvent * e) Line 3690	C++
qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 418	C++
Qt5Core.dll!QCoreApplication::notifyInternal2(QObject * receiver, QEvent * event) Line 1048	C++
Qt5Gui.dll!QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent * e) Line 2224	C++
Qt5Gui.dll!QWindowSystemInterface::sendWindowSystemEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 1038	C++
Qt5Core.dll!qt_internal_proc(HWND__ * hwnd, unsigned int message, unsigned __int64 wp, __int64 lp) Line 239	C++
[External Code]	
Qt5Core.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 630	C++
qwindows.dll!QWindowsGuiEventDispatcher::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 75	C++
Qt5Core.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 213	C++
Qt5Core.dll!QCoreApplication::exec() Line 1336	C++
qgis_app.dll!main(int argc, char * * argv) Line 1600	C++
qgis.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 170	C++
[External Code]	
```

**Comment by roya0045** [comment] 2020-01-28 22:46
@i-s-o thanks for looking into this!

**Comment by roya0045** [comment] 2020-03-23 22:01
I cannot seem to replicate on master 
![image](https://user-images.githubusercontent.com/12854129/77367319-49aaa780-6d30-11ea-8bdd-601c2eb8c0a5.png)

**Comment by danzig666** [comment] 2020-03-24 08:49
> I cannot seem to replicate on master
Try the attached project. It crashes on Windows 10 build 1909 with QGIS 3.12.1.
The weird thing is that is does not seem to crash on Windows 7.

![0jJUiM49BD](https://user-images.githubusercontent.com/5346511/77405753-ef532a80-6db3-11ea-8f0d-08f8f5b96d22.gif)

Project file: [crash_0324.zip](https://github.com/qgis/QGIS/files/4374185/crash_0324.zip)

**Comment by roya0045** [comment] 2020-03-24 11:50
@danzig666 new logic was implemented in master regarding the font symbology. Could you test master to validate if it has been fixed accidentally, as I only have access to window OS. Thanks.

**Comment by gioman** [comment] 2020-03-24 12:24
> @danzig666 new logic was implemented in master regarding the font symbology. Could you test master to validate if it has been fixed accidentally, as I only have access to window OS. Thanks.

@roya0045 this issue is still valid on master/Windows.

**Comment by danzig666** [comment] 2020-03-24 14:10
Ok I found something:
![image](https://user-images.githubusercontent.com/5346511/77434562-56d39f00-6de1-11ea-9a3d-1383eb39fce7.png)
The unicode character displayed here as "RS" shouldn't be there. Deleting it in the project file manually stops the crashes.

**Comment by PeterPetrik** [comment] 2020-10-08 13:36
Unable to reproduce on MacOS/nightly

**Comment by Pedro-Murteira** [comment] 2022-01-25 15:56
@danzig666 Hello, i've tested this issue on QGIS 3.22.3. on Windows 10 and I'm not being able to reproduce it. Did you come across this issue more recently?

**Comment by danzig666** [comment] 2022-01-27 11:19
> @danzig666 Hello, i've tested this issue on QGIS 3.22.3. on Windows 10 and I'm not being able to reproduce it. Did you come across this issue more recently?

Hi! I can't reproduce it on 3.22.3.

**Closed** 2022-01-27 11:33 UTC
Labels: Feedback, High Priority, Bug, Crash/Data Corruption, Windows
