### ISSUE TITLE
QGIS crashes when opening a certain attribute table

### ISSUE THREAD

**Issue by BoswachterMarc** [qgis/QGIS#33518] opened 2019-12-25 08:01 UTC
When opening a certain layer-attribute table, QGIS crashes.
With DBManager I can open the table and export the fields.
I use the project in combination with a mobile QFIeld project and the layer that crashes is edited in the QField app. No problem appears in the QFIeld app.

These are the details

  Gebeurtenisnaam van probleem:	APPCRASH
  Naam van de toepassing:	qgis-ltr-bin.exe
  Versie van toepassing:	0.0.0.0
  Tijdstempel van toepassing:	5c99eb61
  Naam van foutmodule:	Qt5Core.dll
  Versie van foutmodule:	5.11.2.0
  Tijdstempel van foutmodule:	5b99e97e
  Uitzonderingscode:	c0000005
  Uitzonderingsmarge:	0007d993
  Versie van besturingssysteem:	6.1.7601.2.1.0.256.48
  Landinstelling-id:	2067
  Aanvullende informatie 1:	73a9
  Aanvullende informatie 2:	73a9f3b41667b53493b5fad3bb0af995
  Aanvullende informatie 3:	b8a8
  Aanvullende informatie 4:	b8a8aa39da30595f26dd64653a09f1c3

I already tried to make an new profile without plugins but this doesn't solve the problem.

Regards,
Marc

**Comment by gioman** [comment] 2019-12-27 16:15
> When opening a certain layer-attribute table, QGIS crashes.

@BoswachterMarc please attach a sample project+data.

**Comment by roya0045** [comment] 2019-12-27 19:42
Could the qfield data somehow be corrupted?

**Comment by BoswachterMarc** [comment] 2019-12-29 10:42
@Gioman The layer that crashes is the survey_P_BomenEnBos
[SurveyHeverleebosMeerdaalwoud.zip](https://github.com/qgis/QGIS/files/4007959/SurveyHeverleebosMeerdaalwoud.zip)

In the meantime I found that the field 'created' contains different date formats (@roya0045). When I change the field type from date to text string it no longer crashes...
The reason having different date formats lies in the configuring of the QField project and the defining of QField input forms in a sometimes different way (using for example $now as a standard value/format mm:dd:yyyy hrs:min:sec while this was not the case in the beginning of the project...). See printscreen field 'created'.
![Knipsel](https://user-images.githubusercontent.com/57868975/71555768-a3e8e480-2a2f-11ea-9608-f5dfe42a8a26.PNG)

**Comment by gioman** [comment] 2019-12-29 12:05
> When I change the field type from date to text string it no longer crashes...

@BoswachterMarc in the attached project that field is text, so it does not really help to try replicate the problem (as it does not crash here, both on Linux and Windows).

**Comment by BoswachterMarc** [comment] 2019-12-29 13:34
@gioman Excuse me, in this version it crashes again. In the widget for forms I changed the field 'created' to a Date/Time type widget (see printscreen). When trying to open the attribute table QGIS crashes (see second printscreen).

[SurveyHeverleebosMeerdaalwoud.zip](https://github.com/qgis/QGIS/files/4008072/SurveyHeverleebosMeerdaalwoud.zip)

![Knipsel2](https://user-images.githubusercontent.com/57868975/71557546-d30b5000-2a47-11ea-81cc-dc39ba0215c8.PNG)
![Knipsel](https://user-images.githubusercontent.com/57868975/71557547-d30b5000-2a47-11ea-8cd5-d668bfa045c3.PNG)

**Comment by gioman** [comment] 2019-12-29 13:57
Confirmed the crash on 3.10 but not on 3.4.

**Comment by roya0045** [comment] 2019-12-29 20:21
> @gioman The layer that crashes is the survey_P_BomenEnBos
> [SurveyHeverleebosMeerdaalwoud.zip](https://github.com/qgis/QGIS/files/4007959/SurveyHeverleebosMeerdaalwoud.zip)
> 
> In the meantime I found that the field 'created' contains different date formats (@roya0045). When I change the field type from date to text string it no longer crashes...
> The reason having different date formats lies in the configuring of the QField project and the defining of QField input forms in a sometimes different way (using for example $now as a standard value/format mm:dd:yyyy hrs:min:sec while this was not the case in the beginning of the project...). See printscreen field 'created'.
> ![Knipsel](https://user-images.githubusercontent.com/57868975/71555768-a3e8e480-2a2f-11ea-9608-f5dfe42a8a26.PNG)

Thanks for checking, this should be helpful to solve the bug. Though in this case I'm still not sure if qfield is to blame or if something else is as the content of a datetime field should contain specific data and should be interpretable in QGIS regardless of the display format.

**Comment by gioman** [comment] 2019-12-29 22:17
> Though in this case I'm still not sure if qfield is to blame or if something else is as the content of a datetime field should contain specific data and should be interpretable in QGIS regardless of the display format.

I don't think QField has anything to do with this problem, regardless QGIS should not crash (and it does not on 3.4).

**Comment by BoswachterMarc** [comment] 2019-12-30 12:05
It crashed in my 3.4 version...
And indeed, I don't think QField is part of the problem.

![image](https://user-images.githubusercontent.com/57868975/71581333-fc3de600-2b04-11ea-9f96-21b45274e110.png)

**Comment by gioman** [comment] 2019-12-30 12:06
> It crashed in my 3.4 version...

@BoswachterMarc 
can you try the 64bit version? also can you try with a new QGIS profile (no 3rd party plugins installed)?

**Comment by BoswachterMarc** [comment] 2019-12-30 20:52
Perhaps on my son's pc. This is a work pc (without administrator rights...). I already tried a clean QGIS profile but that didn't change anything.

**Comment by elpaso** [comment] 2020-01-23 13:21
I cannot reproduce on current master/linux

**Comment by gioman** [comment] 2020-06-12 14:55
Also does not crash anymore on master. Assuming it was something that was fixed in the meantime. Please reopen if necessary.

**Closed by gioman** 2020-06-12 14:55 UTC
Labels: Bug, Crash/Data Corruption, Feedback
