### ISSUE TITLE
 Data defined override centroid fill marker font characters don't appear in the Layout legend

### ISSUE THREAD

**Issue by 9ls1** [qgis/QGIS#42025] opened 2021-03-04 10:21 UTC
**Describe the bug**
The data defined override centroid fill marker font doesn't appear in the patches in the legend in the Layout

**How to Reproduce**
Add a shape file with an attribute table including a string field with signatures and integer fields for the RGB-values of the signature color.
![image](https://user-images.githubusercontent.com/10632163/109948779-edd7f500-7cda-11eb-847d-c686c2fba12e.png)

In Layer Styling, use Fill as Simple Fill and Centroid Fill with Font marker. Use data defined override for both fill color and the Character(s).
![image](https://user-images.githubusercontent.com/10632163/109948289-76a26100-7cda-11eb-923a-1a063a8dc7d4.png)

![image](https://user-images.githubusercontent.com/10632163/109948634-d0a32680-7cda-11eb-9a55-91ef2018f7f8.png)

![image](https://user-images.githubusercontent.com/10632163/109948683-dac52500-7cda-11eb-8e20-22cd08fac7ea.png)

Create a Layout with a map with the shape file as map source and add the corresponding legend. The patches do not show the data defined override characters. In the Item Properties - Legend Item Properties - Symbol settings has the same setup as in Layer Styling. However the Legend patch is either missing the actual Font Marker character (if a blank character is "activated") or showing an "A" (A seems to be the default selected character) in the default color red.
![image](https://user-images.githubusercontent.com/10632163/109948863-047e4c00-7cdb-11eb-9903-e39a66335d4a.png)

**QGIS and OS versions**

QGIS 3.18 on Windows 10.

**Additional context**

**Comment by gioman** [comment] 2021-03-04 10:23
> Add a shape file

@9ls1 can you attach a sample? thanks.

**Comment by 9ls1** [comment] 2021-03-04 10:32
@gioman man: [nin_testsignatur.zip](https://github.com/qgis/QGIS/files/6082855/nin_testsignatur.zip)

**Comment by roya0045** [comment] 2021-03-04 12:44
Possibly related to the meter_at_scale size setting?

**Comment by 9ls1** [comment] 2021-03-04 13:22
@roya0045 I have tried all the other size options as well – with the same sad result.

**Comment by 9ls1** [comment] 2021-03-19 09:13
Feedback? I believe this is a bug?!? See my posts and zip-file.
I had hoped the QGIS-project would address this bug.
It is crucial that the legend matches the symbols in the map!

**Comment by roya0045** [comment] 2021-03-19 10:18
You have a blank character selected, so nothing is shown. Just select the right character you want as a preview.

**Comment by 9ls1** [comment] 2021-03-19 13:16
@roya0045 Hm, I can't just select the characters, can I? That will give me a "static result".
I want to use the characters (string) found in my attribute table in the field "signatur". That's why I'm using "Data defined override". The characters (the string) in the polygons will vary (correspond to the vegetation type in the polygon).
I tried  both to have a character selected (A is the default) and then I tried "blank" character. Both give me the wring symbol in the patch in the legend (se the screen dump posted earlier). 
I want the symbol in the legend patch to be e.g. |k or ()E (that is: correspond to the symbol in the polygons in the map).

**Comment by roya0045** [comment] 2021-03-19 13:24
@9ls1 Ok this is clearly not a bug, You either have to place the label in the symbol legend to be static and display staticly in the legend.

When using data defined to control the displayed text it is impossible to know that all label are the exact same for a given symbol and display that.

The alternative is to go in the vector property legend tab and set the text there.

@gioman I'd suggest closing this as this is not a bug.

**Comment by 9ls1** [comment] 2021-03-19 15:52
@roya0045 Thanks for your time!
Sorry for being slow. I can't quite follow you. 
I'm _not_ using any labels (the label is set to "No labels" in the Layer styling for the polygon vector layer).

All the different classes will always have the same "character signature", e.g class (field "gtype") T3-C-14 will always have |k in the "signatur"-field as a **Centroid fill - Font marker**. And instead of one/the same Font marker for ALL classes in the vector layer, I want to retrieve the characters to be used as Centroid Fill - Font Marker from the vector layer attribute table.

Anyway, thanks for mentioning "the vector property legend tab and set the text there". Didn't think of that since I'm not using labels. I have just tried to use different symbol Simple fill together with Font marker as Centroid fill.

So if this is not a bug, and the label-alternative you mention, don't solve my issue, may this be marked with the label "Feature Request"?

**Comment by roya0045** [comment] 2021-03-19 16:11
I'm pretty sure the text on symbol is that feature already. ;) Give it a try.

**Comment by andreasneumann** [comment] 2021-03-19 16:26
@9ls1 - data defined properties never show up in legends in QGIS. This doesn't work in any of the symbologies and their legends.

How could QGIS know what values you want to see in the legend? It could be a very large number of legend entries as a complex expression in a data-defined override can generate lots and lots of combinations. Also, consider the case not only, one, but 2,3,4,5 properties have data-defined overrides ... it could generate a legend with many hundred entries!

I would say, this would be a feature request and not  trivial to add.

However, I would also like to see support for legends that expose certain combinations of values in data-defined properties. It would need a study how to best expose data-defined properties in the legend. As a said, you need to consider the case where many symbology aspects are controlled by expressions ...

**Comment by roya0045** [comment] 2021-03-19 16:30
@andreasneumann Text on Symbols already support expressions. I am 99% sure that there is nothing to add at this point.
See
![image](https://user-images.githubusercontent.com/12854129/111812734-c5d9bb80-88ae-11eb-8adf-e28d77615789.png)

**Comment by roya0045** [comment] 2021-03-19 16:41
@andreasneumann The way I understood it was that each symbol is for a given class of feature. Those classes have the same label/character font at the center. He just want to display the corresponding class text in the legend over the symbol.

**Comment by andreasneumann** [comment] 2021-03-19 16:42
> @andreasneumann The way I understood it was that each symbol is for a given class of feature. Those classes have the same label/character font at the center. He just want to display the corresponding class text in the legend over the symbol.

I agree that this would already be possible.

**Comment by andreasneumann** [comment] 2021-03-19 16:53
> @andreasneumann The way I understood it was that each symbol is for a given class of feature. Those classes have the same label/character font at the center. He just want to display the corresponding class text in the legend over the symbol.

Not sure ...

He says "Hm, I can't just select the characters, can I? That will give me a "static result".
I want to use the characters (string) found in my attribute table in the field "signatur". That's why I'm using "Data defined override"."

That means that @9ls1 expects that QGIS magically creates legend entries for any combination of data-defined of overrides, which is not supported by QGIS yet (and would be complicated to implement as I mentioned)

**Comment by 9ls1** [comment] 2021-03-19 19:08
@roya0045, @andreasneumann: Thanks a lot for your response.
Yes, equal classes should have the same Centroid fill Font marker at the center. And this is the case in the QGIS canvas (and in the map in the Layout view) by the means of data defined override settings in Layer styling. 

I thought this would be possible in the legend as well since I in the Layout have the same options in the **Legend Items Properties > Symbol Settings** for characters as in the **Layer Styling** (both provide data defined override and the fill symbol in the map is correctly retrieved from the vector layer's attribute table).

**Legend Items Properties > Symbol Settings**
![image](https://user-images.githubusercontent.com/10632163/111830346-17ee0180-88ee-11eb-916a-a34090536b98.png)
vs.
**Layer Styling**
![image](https://user-images.githubusercontent.com/10632163/111830199-ed03ad80-88ed-11eb-90da-309d8ca6d281.png)

Regardless, I will try Text on Symbols.

**Comment by roya0045** [comment] 2021-03-19 19:33
@andreasneumann as a sidenote it might be a decent feature request to improve the expression dialog in the Test on Symbol, we could easily add symbol scope and make use of my old pending PR to perform aggregate calculations.

**Comment by 9ls1** [comment] 2021-03-20 09:28
The text on symbol did the trick - almost... But not 100 %. I get the different signatures from the field "signatur" from the attribute table. However, again the colors are the same regardless my Text format expression.
![image](https://user-images.githubusercontent.com/10632163/111865185-ced99400-8965-11eb-8f4f-854768608583.png)

Clicking the Data defined override:
![image](https://user-images.githubusercontent.com/10632163/111865211-ec0e6280-8965-11eb-9043-082bbc5d37a7.png)
and using the expression:
![image](https://user-images.githubusercontent.com/10632163/111865229-0ea07b80-8966-11eb-93eb-485153b37350.png)
for retrieving the rgb-values from the attribute table.
Again it works in the Layer Styling, but not in the legend:
![image](https://user-images.githubusercontent.com/10632163/111865298-8cfd1d80-8966-11eb-87aa-d96cd30c042f.png)

But I'm getting closer.

**Comment by m4x300** [comment] 2021-05-05 16:06
From a logical point of view it makes perfectly sense to exclude data driven properties from legend rendering but I recently encountered two rather common use case scenarios, both involving nominative data in conjunction with a categorized layer renderer, where a little bit more flexibility on legend rendering would have  come in handy.

First: 
![categrized_font_marker](https://user-images.githubusercontent.com/8156616/117168704-b2d06b80-adc8-11eb-8104-c4e5679ea8c0.PNG)
The text-on-symbols functionality suffices but it's not perfect: the categorized layer renderer sorts the items lexically, so manual sorting is required every time after a change: number 9 with the code 90201027 would be the first legend entry by default in this example.

Second: That's where @9ls1 is stuck now according to the last post:  [matching-legend-symbology-with-data-driven-symbology](https://gis.stackexchange.com/questions/341043/matching-legend-symbology-with-data-driven-symbology)

It clearly isn't a bug and I'd turn it into a feature request as well. Hard to implement? Idk but I imagine enabeling a data driven legend symbology for example with the user defining a reference feature by id. Or imagine my map from above having the actual feature geometries as legend symbols, how cool would that be!

**Comment by roya0045** [comment] 2021-05-05 16:17
@m4x300 The fundamental issue here is scope mixing. In most cases layers don't just have one feature and are a 1:n relation, where you have one expression for n features. When it comes to symbols, the whole layer is used and not only the subset represented by the symbol.

Without a way to convert the 1:n to a 1:1 it becomes hazardous to expect any reliable answer.

Now if you want one legend entry per feature as you suggest, you can simply use the fid to generate the classes. But the expressions will still be evaluated on the whole dataset.

**Comment by m4x300** [comment] 2021-05-05 16:41
I am totally aware this is about 1:n - I thought "nominative data in conjunction with a categorized layer renderer" would imply just that.

"A way to convert the 1:n to a 1:1:"  data driven legend symbology via defining reference feature. what's so hazardous about it?

"simply use the fid to generate the classes": Not if I want legend entries other than the  fid. Besides fid != row number, also what if another sequence (eg icons) is to be used?

**Comment by gioman** [comment] 2021-06-14 21:21
@9ls1 feel free to make this into a feature request.

**Closed by gioman** 2021-06-14 21:21 UTC
Labels: Bug, Feedback, Symbology
