### ISSUE TITLE
no Rasters from gpkg in 3.26

### ISSUE THREAD

**Issue by ghgeosnap** [qgis/QGIS#49366] opened 2022-07-14 15:58 UTC
### What is the bug or the crash?

no Raster visible from gpkg in 3.26.  8Bit, 2,5GB, RGB, 4Chanals, 4Pyramids, 190000x100000 Pix, EPSG25832,        in  V 3.24 OK. 

### Steps to reproduce the issue

drag and drop the gpkg (with one Pikture) to the map.    no raster is in the map (3.26).    in 3.24 OK.   

### Versions

3.26

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment] 2022-07-14 17:09
@ghgeosnap Can you try and replicate it on a new profile?

**Comment by nicogodet** [comment] 2022-07-14 17:22
OS ? 
If windows, use latest .msi or run updates in network installer

**Comment by agiudiceandrea** [comment] 2022-07-14 23:46
> OS ? If windows, use latest .msi or run updates in network installer

@nicogodet, if the OS is Windows and if the issue is related to the fact that the raster in GPKG contains WEBP tiles, then installing QGIS using the latest .msi doesn't fix the issue: see https://trac.osgeo.org/osgeo4w/ticket/754.

**Comment by agiudiceandrea** [comment] 2022-07-17 07:27
Issue fixed with QGIS 3.26.1 and 3.22.9 OSGeo4W Standalone Installers (*.-1.msi) and OSGeo4W Network Installer.

**Closed** 2022-07-18 08:50 UTC
Labels: Feedback, Raster, Project, Bug
