### ISSUE TITLE
Default project CRS is overridden by data

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29304] opened 2019-03-05 20:18 UTC
Author Name: **Andy Harfoot** (Andy Harfoot)
Original Redmine Issue: [21487](https://issues.qgis.org/issues/21487)
Affected QGIS version: 3.6.0
Redmine category:projection_support

---
If the default CRS for new projects is set in the QGIS settings, this takes effect when a new project is created, however the project CRS is overridden as soon as a layer is added to it, rendering the default setting irrelevant. Observed in 2.18.28, 3.4.5 and 3.6.0

**Comment by nyalldawson** [comment] 2019-05-27 00:23
Duplicate of #27516

**Closed by nyalldawson** 2019-05-27 00:23 UTC
Labels: Bug, Projections/Transformations
