### ISSUE TITLE
Editing scale in bottom bar: QGis ended unexpectetly

### ISSUE THREAD

**Issue by marius711997** [qgis/QGIS#53111] opened 2023-05-15 11:45 UTC
### What is the bug or the crash?

Qgis crashes: Qgis ended unexpectetly

## User Feedback

i was clicking on "Maßstab"(scale in german) , on the down-arrow of the combo-box and edit-field in the bottom command bar

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002c20 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QString::toInt :
QgsScaleComboBox::showPopup :
QComboBox::showPopup :
QComboBox::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

simply opened qgis and pressed on the "Scale"-Editing-Combobox-Arrow in the bottom bar.

### Versions

QGIS-Version
3.30.1-'s-Hertogenbosch
QGIS-Codeversion
9035a01e
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.3
PROJ-Version
9.2.0
EPSG-Registraturdatenbankversion
v10.082 (2023-02-06)
GEOS-Version
3.11.2-CAPI-1.17.2
SQLite-Version
3.41.1
PDAL-Version
2.5.2
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment] 2023-05-16 07:50
Duplicate of #52383

**Closed by YoannQDQ** 2023-05-16 07:50 UTC
Labels: Feedback, Bug
