### ISSUE TITLE
Memory layer - Delete field and re-use it's name

### ISSUE THREAD

**Issue by fuzzysolutions** [qgis/QGIS#33488] opened 2019-12-20 14:06 UTC
**Describe the bug**

When I re-name a field for a memory layer and then create another field using the old name of the first field, QGIS crashes or doesn't create the field.

**How to Reproduce**
1. Create a memory layer
2. Open layer properties dialog
3. Create a field with the name "name", save changes
4. Enter editing mode again, rename it to "other name", save changes
5. Enter editing mode, create a new field "name" -> QGIS crashes

Doing the same steps using the attribute table instead of the properties dialog doesn't crash QGIS, but the field is not being created.

**QGIS and OS versions**

QGIS-Version | 3.10.1-A Coruña | QGIS-Codeversion | ef24c526da
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.2.1 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing

**Additional context**
Occured in previous QGIS versions already. Goes along with some other issues regarding the renaming of fields which are less easy to reproduce.

**Comment by gioman** [comment] 2019-12-20 19:33
Crash confirmed here.

**Comment by gioman** [comment] 2019-12-21 10:05
@fuzzysolutions duplicate of https://github.com/qgis/QGIS/issues/32350 ?

**Comment by fuzzysolutions** [comment] 2019-12-23 10:21
> 
> 
> @fuzzysolutions duplicate of #32350 ?

Not sure, as it seems to depend on the layer / file type. I can't reproduce with shapefile (as #32350). Tried the same steps with a GeoJSON file, no crash either.

**Comment by obrix** [comment] 2020-01-22 14:22
I can reproduce this bug on 3.11 master. The issue appears right after the editing button is toggled after the renaming. The fields data structure of QgsVectorLayer seems to become corrupted, it keep some of the old names in its nameToIndex HashMap.

**Closed** 2020-01-25 21:54 UTC
Labels: Bug, Crash/Data Corruption, High Priority
