### ISSUE TITLE
3.10 crashing when out of focus

### ISSUE THREAD

**Issue by Ohtaror** [qgis/QGIS#32886] opened 2019-11-15 12:15 UTC
## User Feedback

Qgis was out of focus and not doing any calculations or anything active. This has happened at least once an hour since I've updated QGIS to 3.10.0, always when out of focus. This never occurred to me in 3.8 or older versions. I have some standard plugins but did not add any new ones after updating. One more difference is that I used the OSGeo4W installer this time (downloaded from qgis.org).

Furthermore, I had a few warnings by avast antivirus that QGIS would contain "idp.generic", but I found online that this was often a false flag caused by python scripts so I added exceptions.

## Report Details

**Crash ID**: [029bc1a9b819dfb49a1342291172e44f3c1f8e53]('https://github.com/qgis/QGIS/search?q=029bc1a9b819dfb49a1342291172e44f3c1f8e53&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup<QgsOgrConn * __ptr64>::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

EDIT: I'd like to add: thank you to everyone for all the hard work, QGIS really has become an amazing piece of software.

**Comment by roya0045** [comment] 2019-11-15 13:23
Might be another issue with Proj6, is your projection valid and supported in Proj6? Some had issues where their old projection were not supported anymore.

**Comment by Ohtaror** [comment] 2019-11-15 13:28
I'm using EPSG:4326 as a project CRS. 

I disabled autosave plugin since that's the only ongoing activity I could imagine and since then no more crashes, but that might be coincidence too. Anyway, didn't have any problems with that plugin before (and in my personal opinion it should be a core plugin).

**Comment by roya0045** [comment] 2019-11-15 13:55
Ok so autosave could be the cause of the instability. If your case is resolve I would suggest you to close this ticket if everything seem stable for some time, and reopen if the issue arise again without the plugin activated.

**Comment by Ohtaror** [comment] 2019-11-15 14:26
Since deactivating the autosave plugin, the problem hasn't repeated, so it is likely to be the culprit. Thank you for your help and apologies for not trying that first.

**Closed** 2019-11-15 14:27 UTC
Labels: Bug, Crash/Data Corruption, High Priority

**Comment by roya0045** [comment] 2019-11-15 14:29
No worries, thanks for identifying the culprit!
