### ISSUE TITLE
error creating new location in Grass

### ISSUE THREAD

**Issue by Jairofe** [qgis/QGIS#31545] opened 2019-09-04 02:57 UTC
Hello:
When I try to create a new directory of maps of grass (inside qgis), in the second window that appears to create the location, I get an error window of qgis and I close the program (see at the end):

When installing Madeira version I give enter to the Icon (QGIS Desktop 3.4.11 with GRASS 7.6.1)
And it tells me the same error mentioned above
That is what happened with the Madeira 3.4.9 version

Please if there is any way to solve it.
I thank you beforehand.
(I am interested in using the Grass function of delimiting a basin from a point, which I have not seen elsewhere.)

That shows 

Report Details:  
Crash ID: 5712c8a0e4e400a00a6e3554ef942439c58976d3

Stack Trace

EtwSetMark :
setjmp :
malloc :
QString::indexOf :

QGIS Info
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: i386
Kernel Type: winnt
Kernel Version: 6.1.7601

Thanks in advance for the help

**Comment by nirvn** [comment] 2019-09-04 03:23
@Jairofe , unfortunately, the QGIS GRASS provider is essentially in an abandoned state and will crash when attempting to use it on Windows. 

A functional alternative -  one which is actively supported by the development team - is to access GRASS functions through processing algorithms. For e.g., r.watershed, r.stream.extract, etc.

**Comment by gioman** [comment] 2019-09-04 11:08
Duplicate of https://github.com/qgis/QGIS/issues/30317

**Closed by gioman** 2019-09-04 11:08 UTC
Labels: Bug

**Comment by Jairofe** [comment] 2019-09-05 15:57
Hi. Thanks for answering.

Uninstall version Madeira 3.4.9 and install 3.4.11
And the error remained the same.

Then install 3.8.2. with OSGeo4W

And it remains the same.


1. Enter (Qgis Desktop 3.8.2)

I open a DEM .tiff file


Pulse In Processing Toolbox> Grass> Raster> r.fill.dir
   And this message appears

This algorithm cannot be run :-( 
The specified GRASS 7 folder "C:\OSGeo4W\bin\bin" 
does not contain a valid set of GRASS 7 modules. 
Please, go to the Processing settings dialog, and
 check that the GRASS 7 folder is correctly 
configured.







2. Enter (Qgis Desktop 3.8.2 with Grass 7.6.1)

Pulse In Processing Toolbox> Grass> Raster> r.fill.dir
   And the screen to select the DEM file comes out

And I leave (Output aspect direction format (optional)
> in grass

  after a moment he hangs up (he says he doesn't answer)

 
this message appears on a screen

qgis-bin-g7.exe does not respond



Right there I gave him details of the problem
and showed this.


Descripción:
  Este programa dejó de interactuar con Windows por un problema.

Firma con problemas:
  Nombre del evento de problema:	AppHangB1
  Nombre de aplicación:			qgis-bin-g7.exe
  Versión de la aplicación:		0.0.0.0
  Marca de tiempo de la aplicación:	5d570307
  Firma de bloqueo:			ffb1
  Tipo de bloqueo:			0
  Versión del sistema operativo:	6.1.7601.2.1.0.256.1
  Id. de configuración regional:	1033
  Firma adicional de bloqueo 1:	ffb1a4b1ee21fddcf9dded4280250fb0
  Firma adicional de bloqueo 2:	e937
  Firma adicional de bloqueo 3:	e93770d119e1007c1addb69b116d99a4
  Firma adicional de bloqueo 4:	ffb1
  Firma adicional de bloqueo 5:	ffb1a4b1ee21fddcf9dded4280250fb0
  Firma adicional de bloqueo 6:	e937
  Firma adicional de bloqueo 7:	e93770d119e1007c1addb69b116d99a4


>>>

I'm surely doing something wrong.
My system is Windows 7 Ultimate 32bit.


If you can help me, I appreciate it.

**Comment by Jairofe** [comment] 2019-09-05 15:59
The qgis when I use the SAGA functions performs them well so far
