### ISSUE TITLE
Application Crash on 'Export Map to Image'

### ISSUE THREAD

**Issue by erawlins** [qgis/QGIS#31814] opened 2019-09-16 22:28 UTC
I'm a new QGIS user (as of today) so apologies in advance if I omitted anything. This is, so far, a 100% reproducible crash.

[Test TIFF File (Google Drive Link)](https://drive.google.com/file/d/1Ewzzs77sXCiy8vjS4zWcDa7OOSPX_soe/view?usp=sharing)

Reproduction Information:
- Create a new project

- Add a new raster layer using the attached (via google drive link) test.tiff. Note: This is a manipulated image that no longer includes geographical reference data. The original file is 1.4 GB but has the same resolution; the crash is identical. This file was created for easier reproduction of the crash. Once loaded, QDIS will display a single layer, which is a mostly black image

- Right-click the layer and select 'Zoom to Native Resolution'

- Select Project -> Import/Export -> Export Map to Image

- Select 'Calculate From Layer' and 'test'

This has an output resolution of 96 dpi, width of 58591 px, height of 21163 px. In the original image the scale is 1:37 with the same resolution, width, and height - plus correct coordinates, however it seems to be the width & height that cause the crash. Exporting smaller portions of the original image were successful.

- Click save, and enter a filename. I've reproduced the crash with PNG, JPG, TIF. I haven't tested other formats. 

Application will crash shortly. Additional notes:
- Application version 3.8.3
- No additional plugins installed. QGIS was just installed today
- Watching task manager it never uses more than about 4.6GB of ram; 32GB available in my test PC
- The purpose of attempting to export such a large file was to overlay a large GeoTIFF of high-resolution images over a lower-resolution google map with a vector layer of several labeled points, then export the combined 3 layers into a single high-resolution image that can be zoomed-in to great detail. Everything is good so far up to the export.
- As noted above, this is 100% reproducible for me. I'd be happy to try a dev build or additional troubleshooting steps if a developer has a suggestions. I've ruled out as much as possible by generating a much smaller test file.

## Report Details

*Crash ID*: 398a16312b863d7f5bc29f092bc5dadba3499d4c

*Stack Trace*
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::fillRect :
QRasterPaintEngine::drawImage :
QgsRasterDrawer::drawImage qgsrasterdrawer.cpp:172
QgsRasterDrawer::draw qgsrasterdrawer.cpp:103
QgsRasterLayerRenderer::render qgsrasterlayerrenderer.cpp:271
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:270
QgsMapRendererCustomPainterJob::start qgsmaprenderercustompainterjob.cpp:94
QgsMapRendererCustomPainterJob::renderSynchronously qgsmaprenderercustompainterjob.cpp:194
QgsMapRendererTask::run qgsmaprenderertask.cpp:129
QgsTask::start qgstaskmanager.cpp:72
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment] 2019-09-16 22:53
duplicate of #31100

**Comment by erawlins** [comment] 2019-09-16 23:01
Sorry for the duplicate; I did search but didn't find that one.

**Comment by roya0045** [comment] 2019-09-16 23:30
No worries! Though I would recommend that you close this issue and migrate your case to the existing thread. 
Judging from the thread I'm not sure when it will be solved but your participation on the other thread helps the official devs to prioritise things.

**Closed** 2019-09-17 00:15 UTC
Labels: Bug
