### ISSUE TITLE
Points are not rendered in 3D view on systems with Intel graphics

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28507] opened 2018-11-30 15:56 UTC
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [20687](https://issues.qgis.org/issues/20687)
Affected QGIS version: 3.5(master)
Redmine category:3d

---
Tested with Win7, Intel Graphics, both QGIS 3.4 and master: 3D points are not rendered, 3D lines and the DEM surface work.

**Comment by wonder-sk** [comment] 2019-05-27 11:35
What shape did you use? Have you tried to increase symbol size? Sometimes the symbol is just too small initially to be visible...

**Comment by anitagraser** [comment] 2019-06-11 14:21
I'm trying to reproduce this issue but currently I don't event get that far because QGIS crashes when I enable 3D symbology:

h2. User Feedback

Enabling 3D Symbols (Single symbol) causes this crash

h2. Report Details

*Crash ID*: bc697b87286953744202887f3bfbcae029c35107


*Stack Trace*
<pre>
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
DrvSetLayerPaletteEntries :
DrvSetLayerPaletteEntries :
RegisterProcTableCallback :
QOpenGLFunctions_3_3_Compatibility::glDrawElementsInstancedBaseVertex :
Qt3DRender::Render::Renderer::performDraw :
Qt3DRender::Render::Renderer::executeCommandsSubmission :
Qt3DRender::Render::Renderer::submitRenderViews :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by wonder-sk** [comment] 2019-06-12 14:46
@anitagraser looks like duplicate of #25213

**Comment by gioman** [comment] 2020-08-01 21:21
Closing as duplicate, reopen if necessary.

**Closed by gioman** 2020-08-01 21:21 UTC
Labels: 3D, Bug, Feedback
