### ISSUE TITLE
Expression dialog should not allow to click OK if the expression is invalid

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31757] opened 2019-09-14 06:40 UTC
Screenshot might say all
![image](https://user-images.githubusercontent.com/7983394/64904488-30fb6e00-d6cb-11e9-9806-f6126962dd30.png)

master 3.9 cdd3a55e9e

**Comment by nyalldawson** [comment] 2019-09-14 08:38
I disagree. It's so frustrating to enter most of an expression, but then need to confirm something outside the dialog and be forced to lose your expression. There's no harm in allowing users to accept an invalid expression, when they have a good reason to want to do so...

**Comment by roya0045** [comment] 2019-09-14 12:20
" It's not a bug, it's a feature!"  This was not an intended behaviour but  I think that the warning message should be sufficient.

**Comment by elpaso** [comment] 2019-09-16 09:29
@nyalldawson just curious, what's the use case for entering an invalid expression?

**Comment by nyalldawson** [comment] 2019-09-16 09:33
@elpaso 

Because i spend 5 mins entering a complex expression, then realise i need to check a field name from a relation or some thing else which isn't available in the dialog. You've no choice but to lose your partial expression (or cut it away) before you can close the dialog.

There's also times when you want to create an expression which uses fields, which for some reason or other aren't currently present in the layer.

Overall, I think it's just overstepping the bounds of helpful UI into unhelpful ui. We already warn people when an expression is invalid, so they MUST have a good reason to want to enter this, and it's annoying to have QGIS stand in your way when you have a valid reason to want to do something...

**Comment by m-kuhn** [comment] 2019-09-16 10:03
Didn't we have the Ok button disabled back in the days?
And then enabled it, because in some occasions it was actually blocking expressions which couldn't be validated at build time because

> There's also times when you want to create an expression which uses fields, which for some reason or other aren't currently present in the layer.

Actually, the screenshot above is a really good example for exactly this. The variable `@symbol_label` is not known to the expression builder but will be there at evaluation time.

**Comment by NathanW2** [comment] 2019-09-16 10:52
Yes originally when I added the expression builder I had it block button on
a invalid expression however now I'm ok with letting them go though, there
is a lot less impact these days due to multi-threaded rendering and smarter
handing of invalid expressions in things like the attribute table.

So +1 on allowing invalid expressions though the dialog.

**Comment by nirvn** [comment] 2019-09-21 06:46
I'm also +1 to allow OK on invalid expression, for reasons mentioned above. Closing as majority has spoken :)

**Closed by nirvn** 2019-09-21 06:46 UTC
Labels: Bug
