### ISSUE TITLE
QGIS crashes when exiting.

### ISSUE THREAD

**Issue by traficus** [qgis/QGIS#30006] opened 2019-05-29 12:53 UTC
h2. User Feedback

This happens almost all the time I press save and then press the "X" for exit. Happens for my colleagues as well.

h2. Report Details

*Crash ID*: 5ad41d6be94809f981e2ec9b06a0e20f1d0b0a87

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment] 2019-05-29 13:48
Duplicate of tens of similar reports with the same trace. Also already fixed.

**Closed by gioman** 2019-05-29 13:48 UTC

**Comment by gioman** [comment] 2019-05-29 13:53
> how to fix this?

wait for the next round of point releases.
