### ISSUE TITLE
Split vector layer-Temp layer not added to Layers Panel.

### ISSUE THREAD

**Issue by Darko325** [qgis/QGIS#56386] opened 2024-02-16 17:48 UTC
### What is the bug or the crash?

As my tittle is pointing out that Split Vector Layer tool runs but doesn`t add Temp or any other output file type to the Layer Panel. Everything else works fine, but if you export in temp layers you have to search them in the Temp folder, a little annoying.  

### Steps to reproduce the issue

The default steps for Split vector layer tool 

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.3.1
buntinglabs-qgis-plugin
1.7
changeDataSource
3.1
clipper
1.2
DigitizingTools
1.5.2
geo_sim_processing
1.2.0
HCMGIS
24.1.12
ntv2_transformations
0.20
processing_saga_nextgen
1.0.0
qad
3.0.4
quick_map_services
0.19.34
splitmultipart
1.0.0
SplitPolygon-master
1.2
SplitPolygonShowingAreas
0.13
Submission
0.7
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment] 2024-02-17 20:20
This is more of a feature request, as _Split vector layers_ does not have an _Open output file after running algorithm_ checkbox, probably because of the potential huge number of output files.

**Comment by alexbruy** [comment] 2024-02-18 06:35
The algorithm does not have such an option, because it produces directory output, not layer output.

And this is a duplicate of #20462.

**Closed by alexbruy** 2024-02-18 06:35 UTC
Labels: Processing, Bug
