### ISSUE TITLE
Unable to launch application V3.28 LTR

### ISSUE THREAD

**Issue by amj1711** [qgis/QGIS#54977] opened 2023-10-18 14:49 UTC
### What is the bug or the crash?

Hi, when I try and launch the Macbook, running Catalina V10.15.7, I get the following error "QGS-LTR could not be opened as Apple cannot check it for malicious software. This software needs to updated. Contact the developer for more information".
![image](https://github.com/qgis/QGIS/assets/148360249/2474a96e-764e-4ec3-948b-0063af4e0e60)

### Steps to reproduce the issue

Launch newly installed app from applications menu

### Versions

QGIS 3.28 LTR for MacOS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment] 2023-10-18 15:07
duplicate of #52097

**Closed by jef-n** 2023-10-18 15:07 UTC
Labels: Bug

**Comment by agiudiceandrea** [comment] 2023-10-18 16:06
@amj1711, please follow the instruction available in the QGIS download page for macOS

![image](https://github.com/qgis/QGIS/assets/16253859/662b00d1-8330-4b9e-96ef-8dfac9985456)

"QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please control-click on the icon and choose Open from the context menu, after which a confirmation dialog is shown and you need to click the Open button."
