### ISSUE TITLE
QGIS 3.4.11: Clicking a PDF URL in GetFeatureInfo response generates error

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [qgis/QGIS#31542] opened 2019-09-03 13:08 UTC
**Describe the bug**

PDF URLs in the GetFeatureInfo response generate a "Frame load interrupted by policy change" error when they are clicked.

Test WMS GetCapabilities: https://test.haleconnect.de/ows/services/org.82.ead8c7a9-cd09-4a19-b382-64a0c33b1b78_wms/org.82.6fa6fc1f-d404-4f84-ba58-f594c6270cf0?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

**How to Reproduce**

Load the WMS in QGIS and click on a feature using the Identify tool. 
Select HTML format in the Identify results dialog. 
Click on the "Details Anzeigen" button for the selected feature. 
In the window that opens, click on a PDF URL.
See error:
![grafik](https://user-images.githubusercontent.com/36956461/64175806-664ac500-ce5c-11e9-859e-fc61b409c4e9.png)

**QGIS and OS versions**

QGIS version | 3.4.11-Madeira | QGIS code revision | 9a8a6d4687
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Additional context**

URLs to HTML pages open without issue

**Comment by gioman** [comment] 2019-09-04 11:19
>  Click on the "Details Anzeigen" button for the selected feature.

this sound similar to https://github.com/qgis/QGIS/issues/31226 at least I cannot get any button when identifying a feature from the provided service, just a link and when clicking on it QGIS crashes (on 3.8.2). @elpaso

**Comment by elpaso** [comment] 2019-09-09 12:56
I cannot reproduce this on current Linux/master, @Kate-Lyndegaard  would you be able to test the latest development versions of QGIS and verify if the issue was fixed?

@gioman  regarding #31226 it was not backported to 3.4, but it should be fixed for >= 3.8.

**Comment by Kate-Lyndegaard** [comment] 2019-09-09 13:35
Hi @elpaso 
I tested #31226 in QGIS 3.8.2 however QGIS 3.8.2 still crashes when I attempt to open the pop-up from the GetFeatureInfo response.  The PDF links that will not open are contained within the pop-up, so unfortunately I cannot test whether they are opening as long as the pop-up crashes the latest version of QGIS. 
The pop-up works as expected in QGIS 3.4.11, however the PDF links do not open.
Kind regards,
Kate

**Comment by elpaso** [comment] 2019-09-09 14:13
@Kate-Lyndegaard the patch it's not in 3.8.2 but it will be in the next 3.8 release.
So, in order to test if the issue has been resolved, you should test the qgis-dev nightlies builds from osgeo4w, see: 
https://qgis.org/en/site/forusers/download.html
and:
    OSGeo4W Network Installer (64 bit) 
In the installer choose Desktop Express Install and select QGIS to install the latest release.
To get the bleeding-edge development build choose Advanced Install and select qgis-dev-full


I'm asking you to test because I believe that the patch  #31226 also fixes this issue.

**Comment by gioman** [comment] 2019-09-10 10:07
> Load the WMS in QGIS and click on a feature using the Identify tool.
> Select HTML format in the Identify results dialog.
> Click on the "Details Anzeigen" button for the selected feature.
> In the window that opens, click on a PDF URL.

on master the button shows correctly, clicking it does not open a pop up in QGIS but rather a web page in the browser where the pdf links work as expected.

**Comment by Kate-Lyndegaard** [comment] 2019-09-10 10:21
@elpaso @gioman 
Yes, I can confirm that this issue and #31226 are resolved in the bleeding edge dev build.
Thank you very much!
Kind regards,
Kate

**Comment by elpaso** [comment] 2019-09-10 10:34
@Kate-Lyndegaard  You're welcome :)

**Closed** 2019-09-10 10:34 UTC
Labels: Bug, Feedback
