### ISSUE TITLE
QGIS crashes on pressing the Vertex tool button

### ISSUE THREAD

**Issue by himem** [qgis/QGIS#31809] opened 2019-09-16 15:46 UTC
## User Feedback

- added some layers from S-57 file (don't know if it relates to the crash somehow)
- added a new temporary layer with 'point' geometry
- added 2 points
- edited the 1st point
- pressed the 'vertex tool' button on the toolbar

## Report Details

*Crash ID*: 4736cd0a56fd1d2e0b86810b9ef8100c2a06e12e

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nirvn** [comment] 2019-09-17 02:40
@himem , can you be more precise in your steps to reproduce. E.g., what do you mean by 'edited the 1st point'? Edited via attribute table panel, via identify tool's attribute form?

**Comment by cuitlahuachs** [comment] 2019-09-18 15:30
In my case, after using vertex tool and editing the last point, then it crashed trying to save.

Crash ID: ba721d685d1f0418bff58dbd3f0dd4a5f6f6ceb2
Stack Trace
QList::size :
QAbstractTableModel::index :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyMethodDef_RawFastCallKeywords :
PyMethodDef_RawFastCallKeywords :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyMethodDef_RawFastCallDict :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by nirvn** [comment] 2019-09-19 07:49
@cuitlahuachs , please be more precise. What layer type did you edit, what kind of editing (moving a vertex, using the vertex panel table view, etc?), how did you try to save your layer (via toolbar, via layer right click menu, attribute table?)

**Comment by nyalldawson** [comment] 2019-09-19 07:57
I've seen this too - it's quite broken at the moment. I suspect it's likely due to the snapping threading changes...

**Comment by nirvn** [comment] 2019-09-19 07:59
The snapping threading changes are likely not related to this (these?) vertex editor crash(es) since it's reportedly on 3.4 and 3.8.

**Comment by nyalldawson** [comment] 2019-09-19 08:06
I missed that part!

**Comment by cuitlahuachs** [comment] 2019-09-19 13:31
Hi Mathieu, sorry that I didn't specify these details:
It was a single line shapefile, after extending the vertices of both
endings by one node, using the vertex tool (icon), and trying to save
through the toolbar.

**Comment by 3nids** [comment] 2019-11-07 12:11
fixed by #32703

**Closed by 3nids** 2019-11-07 12:11 UTC
Labels: Bug, Feedback
