### ISSUE TITLE
 A widget size error when resizing dialogs

### ISSUE THREAD

**Issue by bachns** [qgis/QGIS#37149] opened 2020-06-12 04:04 UTC
I am currently using QGIS 3.10.4 and I found an error that widgets do not fill the parent dialog when resize of the dialog (make larger) then reopen dialog.

![2020-06-12_103034](https://user-images.githubusercontent.com/26644599/84462273-cb0f3780-ac98-11ea-9aac-353424ad1fc5.png)

The order of my actions is as follows:
1. Open Data Source Manager dialog (Layer/Add Layer/Add Raster Layer...)
2. Make this dialog larger then close it. 
3. Reopen (Layer/Add Layer/Add Raster Layer...)

**Comment by gioman** [comment] 2020-06-12 10:55
@bachns Operating system/Desktop manager?

**Comment by bachns** [comment] 2020-06-12 11:04
I am using a laptop running windows 10 64bit.

**Comment by Gustry** [comment] 2020-06-12 11:54
It looks quite similar to https://github.com/qgis/QGIS/issues/33318 ?

**Comment by gioman** [comment] 2020-06-12 11:56
@bachns also I can't replicate on windows 10 and QGIS master.

**Comment by elpaso** [comment] 2020-06-12 12:03
@Gustry it's a duplicate of that one. I've tried to fix this issues three times already and I gave up, I also cannot reproduce it in my windows VM, I'm sorry for that.

**Closed by elpaso** 2020-06-12 12:03 UTC
Labels: Bug, Feedback, GUI/UX
