### ISSUE TITLE
QGIS crashes When Setting Up GRASS location/mapset

### ISSUE THREAD

**Issue by jcdavids** [qgis/QGIS#30317] opened 2019-06-21 16:33 UTC
h2. User Feedback

I was just setting up a new GRASS location and when I pressed Next after naming the location QGIS crashed!  Happy debugging!

h2. Report Details

*Crash ID*: d76ef2dff745d2aba152da6d1350374fbeb23cff

*Stack Trace*
<pre>
RtlRaiseStatus :
longjmp :
longjmp :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: commit:0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by haubourg** [comment] 2019-07-11 11:30
Confirmed in QGIS. 3.4.5 and 3.8 when using the grass plugin

**Comment by blazek** [comment] 2019-09-19 07:58
Duplicate of #28148

**Closed by blazek** 2019-09-19 07:58 UTC
Labels: Bug, Crash/Data Corruption, GRASS, Regression

**Comment by blazek** [comment] 2019-09-19 09:16
Commented in  #28148. But this is fresh so maybe you can tel us:

- Is it installed using OSGeo4W network installer or QGIS standalone installer 
- Can you verify if GISBASE environment variable is set correctly? You can try in Python Console in QGIS
```
import os
os.environ['GISBASE']
```

**Comment by jcdavids** [comment] 2019-09-19 16:25
Hi Radim,

 

*	Installed with OSGeo4W network installer
*	GISBASE does not appear to be configured correctly (and from a quick search I’m not sure how to fix that or why it matters)

 

import os

os.environ('GISBASE')

Traceback (most recent call last):

  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode

    exec(code, self.locals)

  File "<input>", line 1, in <module>

TypeError: '_Environ' object is not callable

**Comment by DelazJ** [comment] 2019-09-19 16:39
Hi,
> os.environ('GISBASE')

not `()` but `[]`

**Comment by jcdavids** [comment] 2019-09-19 16:49
Thanks for catching that (rookie mistake).  That executes without an error as seen below.

 

import os

os.environ['GISBASE']

'C:/OSGEO4~1/apps/grass/grass76'

**Comment by blazek** [comment] 2019-09-19 17:23
> os.environ['GISBASE']
> 'C:/OSGEO4~1/apps/grass/grass76'

Thanks, so it is set. Does it still crash when you try to create new location?
