### ISSUE TITLE
qgis3.x when open file dialog will crash

### ISSUE THREAD

**Issue by iwashereys** [qgis/QGIS#30667] opened 2019-07-11 01:58 UTC
i found qgis3.x will crash when i try to open a file dialog. such as:
Project-->Open
Project-->Save As

Crash ID: 36650c470329a406805bad42da8025475c5403db

Stack Trace

memset :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CoWaitForMultipleHandles :
WindowsConcatString :
InternalCAggIdRelease :
CoGetErrorInfo :
GetHGlobalFromStream :
CoTaskMemRealloc :
CoWaitForMultipleHandles :
WindowsConcatString :
CoWaitForMultipleHandles :
WindowsConcatString :
CoCreateInstance :
CoCreateInstance :
CoCreateInstance :
DllGetClassObject :
SHEnableServiceObject :
SHEnableServiceObject :
SHEnableServiceObject :
Ordinal660 :
Ordinal201 :
Ordinal201 :
SHEvaluateSystemCommandTemplate :
SHEvaluateSystemCommandTemplate :
SHELL32_IconOverlayManagerInit :
SHChangeNotification_Unlock :
SHBindToFolderIDListParent :
SHBindToFolderIDListParent :
Ordinal129 :
DllGetClassObject :
Ordinal129 :
ILClone :
ILClone :
ILClone :
CreateRandomAccessStreamOnFile :
LdrUnloadDll :
RtlInitializeResource :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-07-11 11:10
@iwashereys try with a new/clean QGIS profile.

**Comment by iwashereys** [comment] 2019-07-12 14:10
> @iwashereys try with a new/clean QGIS profile.

i create an App of QFileDialog, using qt5 and run it , then it will crash with release version. but debug version is ok. my win10 can't run QFileDialog of qt5 in release version.

**Comment by nyalldawson** [comment] 2019-10-13 19:42
This is a local issue, caused by other software installed on the machine which has registered a buggy icon handler. It's not qgis issue or something which can be fixed in qgis.

**Closed by nyalldawson** 2019-10-13 19:42 UTC
Labels: Bug, Feedback
