### ISSUE TITLE
Does not properly form SQL queries to insert or update into PostGIS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29277] opened 2019-03-03 23:50 UTC
Author Name: **Cory Albrecht** (@CoryAlbrecht)
Original Redmine Issue: [21460](https://issues.qgis.org/issues/21460)
Affected QGIS version: 3.7(master)
Redmine category:data_provider/postgis

---
After editing a feature in a PostGIS and trying to save the layer, QGIS gives the warning that it could not commit the changes to the layer. The following error in the PostGIS messages tab.

```
2019-03-03T18:18:05     WARNING    Erroneous query: UPDATE "Balance of Power"."timeline-countries" SET "main_rgb"='E1BE48',"border_rgb"='D9B023',"info_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"successors"=E'{""}' WHERE "feature_uuid"::text='e0471e92-82e6-484c-92e2-1538eb6e0adb' returned 7 [ERROR: invalid input syntax for uuid: ""
             LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
              ^
             ]

```

The column it is complaining about is predecessors, which in PostGIS is an array of UUID. The column is empty, but QGIS appears to be trying to save it as an array with a single empty string but that column for that row is empty (NULL).

The schema for the table is:

```
CREATE TABLE "Balance of Power"."timeline-countries"
(
    geom geometry(MultiPolygon,4326),
    name text COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    main_rgb character varying(8) COLLATE pg_catalog."default",
    feature_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    country_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    stripe_rgb character varying(8) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_rgb character varying(8) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_shade numeric DEFAULT 0.085,
    sovereign text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    info_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::character varying[],
    flag_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::character varying[],
    predecessors uuid[] DEFAULT ARRAY[]::uuid[],
    successors uuid[] DEFAULT ARRAY[]::uuid[],
    visible boolean DEFAULT true,
    alternate_name text[] COLLATE pg_catalog."default",
    full_name text[] COLLATE pg_catalog."default",
    full_names json,
    CONSTRAINT "timeline-countries_pkey" PRIMARY KEY (feature_uuid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

```

I cannot edit several fields (info_url, flag_ur, predecessors, successors) in the form view for the feature that cannot be updated, but can do so for other features.

---

- [Screenshot from 2019-03-10 11-22-25.png](https://issues.qgis.org/attachments/download/14563/Screenshot%20from%202019-03-10%2011-22-25.png) (Cory Albrecht)

**Comment by CoryAlbrecht** [comment] 2020-02-15 16:42
This is still happening in the latest 3.10.

2020-02-15T11:31:26     CRITICAL    Layer timeline-countries : PostGIS error while changing attributes: ERROR: invalid input syntax for type uuid: ""
             LINE 1: ...fo_url"=E'{""}',"flag_url"=E'{""}',"predecessors"=E'{""}',"s...
              ^

2020-02-15T11:32:27     WARNING    Erroneous query: UPDATE "Balance of Power"."timeline-countries" SET "end_date"='1898-08-31',"info_url"=NULL,"flag_url"=NULL,"predecessors"=E'{""}',"successors"=E'{""}',"alternate_name"=E'{}',"full_name"=E'{}' WHERE "feature_uuid"::text='0192e315-55d4-40b8-9d08-9517be80d8f9' returned 7 [ERROR: invalid input syntax for type uuid: ""
             LINE 1: ...1',"info_url"=NULL,"flag_url"=NULL,"predecessors"=E'{""}',"s...
              ^
             ]

**Comment by CoryAlbrecht** [comment] 2020-02-15 16:45
@gioman

**Comment by gioman** [comment] 2020-02-15 17:46
@CoryAlbrecht You may want to add the dump of a PostGIS table that shows this behavior. Thanks.

**Comment by CoryAlbrecht** [comment] 2020-02-16 17:00
And 3.11

**Comment by CoryAlbrecht** [comment] 2020-02-16 17:12
> @CoryAlbrecht You may want to add the dump of a PostGIS table that shows this behavior. Thanks.

Anything with a NULL value in the fields as described.
[table.zip](https://github.com/qgis/QGIS/files/4210340/table.zip)

**Comment by gioman** [comment] 2020-02-16 18:07
> Anything with a NULL value in the fields as described.
> [table.zip](https://github.com/qgis/QGIS/files/4210340/table.zip)

@CoryAlbrecht I cannot cleanly restore this dump:

psql:table/table.sql:443: ERROR:  relation "Balance of Power.timeline-countries" does not exist

**Comment by CoryAlbrecht** [comment] 2020-02-16 18:22
> > Anything with a NULL value in the fields as described.
> > [table.zip](https://github.com/qgis/QGIS/files/4210340/table.zip)
> 
> @CoryAlbrecht I cannot cleanly restore this dump:
> 
> psql:table/table.sql:443: ERROR: relation "Balance of Power.timeline-countries" does not exist

You're going to have to give me more than that. Where did it fail? In the create table part? In the COPY FROM stdin?

**Comment by CoryAlbrecht** [comment] 2020-02-16 18:27
[table-1.tar.gz](https://github.com/qgis/QGIS/files/4210536/table-1.tar.gz)

**Comment by gioman** [comment] 2020-02-16 18:48
> [table-1.tar.gz](https://github.com/qgis/QGIS/files/4210536/table-1.tar.gz)

@CoryAlbrecht restoring this will create a new db (was not expecting that, and should not be necessary), it does not restore postgis (that must be added manually), do no create the necessary schema "Balance of Power" and eventually still ends with

```
psql:table-1/restore.sql:93: ERROR:  function public.uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:table-1/restore.sql:100: error: $$PATH$$/4956.dat: No such file or directory
psql:table-1/restore.sql:107: ERROR:  relation "Balance of Power.timeline-countries" does not exist
psql:table-1/restore.sql:114: ERROR:  relation "Balance of Power.timeline-countries" does not exist
```

**Comment by CoryAlbrecht** [comment] 2020-02-16 23:18
You'll have to cat or copy /b these back together  into a single tar file after unzipping each of them because GitHub doesn't seem to recognise xz compressed files or like files bigger than 10MB.

[ah.tar.ae.zip](https://github.com/qgis/QGIS/files/4211220/ah.tar.ae.zip)
[ah.tar.ah.zip](https://github.com/qgis/QGIS/files/4211223/ah.tar.ah.zip)
[ah.tar.af.zip](https://github.com/qgis/QGIS/files/4211221/ah.tar.af.zip)
[ah.tar.ag.zip](https://github.com/qgis/QGIS/files/4211222/ah.tar.ag.zip)
[ah.tar.aa.zip](https://github.com/qgis/QGIS/files/4211216/ah.tar.aa.zip)
[ah.tar.ab.zip](https://github.com/qgis/QGIS/files/4211217/ah.tar.ab.zip)
[ah.tar.ac.zip](https://github.com/qgis/QGIS/files/4211218/ah.tar.ac.zip)
[ah.tar.ad.zip](https://github.com/qgis/QGIS/files/4211219/ah.tar.ad.zip)

**Comment by CoryAlbrecht** [comment] 2020-02-16 23:21
/usr/bin/pg_dump --file "/home/cory/Downloads/ah.tar" --host "pg1.db.cory.albrecht.name" --port "5432" --username "cory" --no-password --verbose --quote-all-identifiers --role "postgres" --format=t --blobs --no-owner --create --clean --section=pre-data --section=data --section=post-data --inserts --column-inserts --disable-dollar-quoting "Alternate History"

**Comment by djes** [comment] 2020-04-03 12:02
Bump. On QGIS 3.10.4, when I'm trying to save a PostgreSQL layer with a double float8 field containing a null value, I get
```
ERROR: invalid input syntax for type double precision: ""
             LINE 1: ...wkb($1::bytea,3950)),$2,$3,'Test',$4,$5,'','',$6,$...
```
As said in this ticket https://trac.osgeo.org/qgis/ticket/988 : 

> The problem with saving the null values is when sending the INSERT or UPDATE statement to the PostgreSQL database the value is quoted, which is okay for numbers and must be for special values like 'NAN' or 'Infinity', but quotes with zero or more spaces is not accepted. The value needs to be NULL (no quotes) or the comma separators with nothing but whitespace between.

QGIS shouldn't quote NULL value when forming the request.

**Comment by gioman** [comment] 2020-04-03 17:34
> Bump. On QGIS 3.10.4, when I'm trying to save a PostgreSQL layer with a double float8 field containing a null value, I get

@djes can you post the SQL statement to create the table that is giving you this problem? Thanks.

**Comment by djes** [comment] 2020-04-03 19:20
After several tests, I'm now unable to reproduce the bug. I had copied several entities from another QGIS and was unable to save. I had to make a SQL request to update the required fields to NULL. Now it works like a charm. I'll make further tests in the future. Sorry for the bug report as it seems to need more research.

As it's my server, here's the PGAdmin SQL dump :
```
CREATE TABLE insp.bouc
(
    fid integer NOT NULL DEFAULT nextval('insp.bouc_fid_seq'::regclass),
    geom geometry(MultiPoint,3950),
    pk_cati character varying COLLATE pg_catalog."default",
    fk_insp character varying COLLATE pg_catalog."default",
    comm character varying COLLATE pg_catalog."default",
    photo character varying COLLATE pg_catalog."default",
    altsurf double precision,
    altfond double precision,
    altciel double precision,
    CONSTRAINT bouc_pk PRIMARY KEY (fid)
)
```
And the full bug report :
```
2020-04-03T13:04:49     CRITICAL    Couche insp bouc : Erreur PostGIS lors de l'ajout d'entité : ERROR: invalid input syntax for type double precision: ""
             LINE 1: ...wkb($1::bytea,3950)),$2,$3,'VENCHEMFERR000',$4,$5,'','','',$...
```

**Comment by stev-0** [comment] 2020-10-01 23:05
Duplicate of #39106

**Closed** 2020-10-03 10:02 UTC
Labels: Bug, Data Provider
