### ISSUE TITLE
Processing "split with lines" creates (wrong) sliver polygons

### ISSUE THREAD

**Issue by coefficient1900** [qgis/QGIS#49726] opened 2022-08-10 12:24 UTC
### What is the bug or the crash?

When using the tool "Split with lines" to split polygons with a line feature, more than the expected number of polygon features are created in the resulting layer .

A simple project ist provided by the following .gpkg:
[split_polygons_lines.zip](https://github.com/qgis/QGIS/files/9299919/split_polygons_lines.zip)

### Steps to reproduce the issue

1.: Use a topological correct polygon layer with at least two features.
![starting_point](https://user-images.githubusercontent.com/86417466/183898070-701cde60-dc29-4f77-b902-cb9175c1073b.jpg)

2.: Produce a line feature that covers the created polygons.

3.: Utilise the "Split with lines" tool from vector overlay with the input from 1 and 2.

4.: Look in the the attribute table of the resulting layer. After splitting there **can** be more the the expected number of features.

![result](https://user-images.githubusercontent.com/86417466/183898871-127ee800-388a-49cb-b7b2-54ae88640e2d.jpg)
(in this example, fid 4 should not be there and is not shown in the map canvas, although it has geometry properties like an area)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.16-Hannover | QGIS code revision | f5778a89
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.4.1 | Running against GDAL/OGR | 3.4.1
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.1 | Running against PROJ | Rel. 8.2.1, January 1st, 2022
OS Version | Windows 10 Version 2009
Active python plugins | db_manager; MetaSearch; processing

</body></html>QGIS version
3.16.16-Hannover
QGIS code revision
[f5778a89](https://github.com/qgis/QGIS/commit/f5778a89)
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.1
Running against GDAL/OGR
3.4.1
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.1
Running against PROJ
Rel. 8.2.1, January 1st, 2022
OS Version
Windows 10 Version 2009
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I reported this issue with 3.16.16, but the geopackage with the test data was created with 3.26.1 and the problem still exists with that current version.

**Comment by gioman** [comment] 2022-08-11 17:50
@coefficient1900 yep, for some reason the tool creates a tiny sliver polygon


![image](https://user-images.githubusercontent.com/1951107/184201235-c9a94e67-a214-46d7-b47f-189876ba6e4a.png)

**Comment by coefficient1900** [comment] 2022-08-28 07:44
@gioman thanks for confirmation, it tested it with a single shape file polygon, same incorrect result.

![shape_split](https://user-images.githubusercontent.com/86417466/187063618-aa76c3ac-0b17-43f1-9a2a-b0f1e4d249f4.jpg)

**Comment by elpaso** [comment] 2022-09-22 10:08
@strk can you have a look at this? I can confirm on current master/linux but it falls deep into GEOS.

**Comment by strk** [comment] 2022-09-23 14:52
I'm looking. Added some debug lines to a file and building again (takes forever).
When I went taking a deeper look while the build was in progress, `git status` could not help me find which file I've added debug lines to, because many files are modified from last time I've run the testsuite, as per #25830 -- This will slow down operations.

**Comment by strk** [comment] 2022-09-23 15:43
The problem doesn't seem to be in GEOS but in the way QGIS calls it.
At least, I get exactly 4 polygons if I split each of the 2 polygons by the given line in PostGIS:
```
# Import the geopackage to default PostGIS database:
$ ogr2ogr pg: split_polygons_lines.gpkg
# Run ST_Split:
$ psql -c 'select id, st_summary(ST_Split(geom, ( select geom from line ) )) from polygons'
 id |               st_summary                
----+-----------------------------------------
  1 | GeometryCollection[BS] with 2 elements:+
    |   Polygon[S] with 1 ring:              +
    |    ring 0 has 10 points                +
    |   Polygon[S] with 1 ring:              +
    |    ring 0 has 7 points
  2 | GeometryCollection[BS] with 2 elements:+
    |   Polygon[S] with 1 ring:              +
    |    ring 0 has 11 points                +
    |   Polygon[S] with 1 ring:              +
    |    ring 0 has 8 points
(2 rows)
```

**Comment by strk** [comment] 2022-09-23 18:14
Debugging lines suggest that the line is being used to iteratively split not only the original polygons but ALSO the polygons which resulted from the split. I'd expect just 2 invocations of `splitGeometry` but instead I see 7 of them !

```
XXX calling splitGeometry against geom Polygon ((565288.39593541610520333 5495162.7689863434061408, 565304.4615965272532776 5495164.10779143590480089, 565548.12412337958812714 5495186.19807546399533749, 565636.48525949090253562 5495177.49584236182272434, 565706.10312430583871901 5495129.29885902814567089, 565739.57325162074994296 5495046.29294328764081001, 565684.01284027798101306 5495042.27652801014482975, 565657.9061409723944962 5495126.62124884314835072, 565588.28827615745831281 5495164.10779143590480089, 565552.14053865743335336 5495173.47942708432674408, 565289.73474050872027874 5495146.03392268624156713, 565288.39593541610520333 5495162.7689863434061408))
XXX calling splitGeometry against geom Polygon ((565621.19987859146203846 5495146.38615935575217009, 565639.90803626773413271 5495175.1262276703491807, 565706.10312430583871901 5495129.29885902814567089, 565739.57325162074994296 5495046.29294328764081001, 565684.01284027798101306 5495042.27652801014482975, 565657.9061409723944962 5495126.62124884314835072, 565621.19987859146203846 5495146.38615935575217009))
XXX calling splitGeometry against geom Polygon ((565639.90803626773413271 5495175.1262276703491807, 565621.19987859146203846 5495146.38615935575217009, 565588.28827615745831281 5495164.10779143590480089, 565552.14053865743335336 5495173.47942708432674408, 565289.73474050872027874 5495146.03392268624156713, 565288.39593541610520333 5495162.7689863434061408, 565304.4615965272532776 5495164.10779143590480089, 565548.12412337958812714 5495186.19807546399533749, 565636.48525949090253562 5495177.49584236182272434, 565639.90803626773413271 5495175.1262276703491807))
XXX calling splitGeometry against geom Polygon ((565289.73474050872027874 5495146.03392268624156713, 565552.14053865743335336 5495173.47942708432674408, 565588.28827615745831281 5495164.10779143590480089, 565657.9061409723944962 5495126.62124884314835072, 565684.01284027798101306 5495042.27652801014482975, 565667.27777662058360875 5495040.26832037046551704, 565659.24494606500957161 5495063.02800694480538368, 565638.49346712976694107 5495119.92722338065505028, 565596.32110671303234994 5495144.02571504656225443, 565553.47934374993201345 5495159.42197361215949059, 565520.00921643513720483 5495152.72794814873486757, 565414.24361412005964667 5495138.00109213031828403, 565293.75115578656550497 5495127.9600539356470108, 565289.73474050872027874 5495146.03392268624156713))
XXX calling splitGeometry against geom Polygon ((565621.19987859146203846 5495146.38615935575217009, 565613.33481411228422076 5495134.30359653290361166, 565596.32110671303234994 5495144.02571504656225443, 565553.47934374993201345 5495159.42197361215949059, 565520.00921643513720483 5495152.72794814873486757, 565414.24361412005964667 5495138.00109213031828403, 565293.75115578656550497 5495127.9600539356470108, 565289.73474050872027874 5495146.03392268624156713, 565552.14053865743335336 5495173.47942708432674408, 565588.28827615745831281 5495164.10779143590480089, 565621.19987859146203846 5495146.38615935575217009))
XXX calling splitGeometry against geom Polygon ((565613.33481411216780543 5495134.30359653290361166, 565621.19987859134562314 5495146.38615935575217009, 565621.19987859146203846 5495146.38615935575217009, 565613.33481411228422076 5495134.30359653290361166, 565613.33481411216780543 5495134.30359653290361166))
XXX calling splitGeometry against geom Polygon ((565621.19987859134562314 5495146.38615935575217009, 565613.33481411216780543 5495134.30359653290361166, 565596.32110671303234994 5495144.02571504656225443, 565553.47934374993201345 5495159.42197361215949059, 565520.00921643513720483 5495152.72794814873486757, 565414.24361412005964667 5495138.00109213031828403, 565293.75115578656550497 5495127.9600539356470108, 565289.73474050872027874 5495146.03392268624156713, 565552.14053865743335336 5495173.47942708432674408, 565588.28827615745831281 5495164.10779143590480089, 565621.19987859134562314 5495146.38615935575217009))
```

**Comment by strk** [comment] 2022-09-23 18:34
Confirmed: each geometry is split by the line, and then each component of the split is split again.
When splitting one component of the SECOND geometry by the line, a new "slice" is generated.

GEOS does not expose a splitGeometry function so this algorithm is fully inside qgis.


I've a fix for this specific case, but no idea what it breaks. Will file a pull request to discuss and maybe you can test it @coefficient1900 ?

```
diff --git a/src/analysis/processing/qgsalgorithmsplitwithlines.cpp b/src/analysis/processing/qgsalgorithmsplitwithlines.cpp
index 65f21bdbe17..47288e8cfbb 100644
--- a/src/analysis/processing/qgsalgorithmsplitwithlines.cpp
+++ b/src/analysis/processing/qgsalgorithmsplitwithlines.cpp
@@ -222,8 +231,8 @@ QVariantMap QgsSplitWithLinesAlgorithm::processAlgorithm( const QVariantMap &par
                 }
                 else
                 {
-                  inGeoms.append( inGeom );
-                  inGeoms.append( newGeometries );
+                  outGeoms.append( inGeom );
+                  outGeoms.append( newGeometries );
                 }
               }
               else
```

**Comment by strk** [comment] 2022-09-29 16:43
This issue should have been fixed by https://github.com/qgis/QGIS/pull/50279
Feel free to re-open if you cannot confirm

**Closed by strk** 2022-09-29 16:43 UTC
Labels: Processing, Bug
