### ISSUE TITLE
Vector tiles exported with Print Layout not clipped to map extent

### ISSUE THREAD

**Issue by Bananastand-Money** [qgis/QGIS#37696] opened 2020-07-09 02:46 UTC
**Describe the bug**

When using a vector tile basemap, in my case from both the MapTiler plugin and manually connecting to their servers, the vector lines are not clipped at the edges of the map box, leading to roads and contours in the whitespace surrounding it. Additionally, other shapefiles I had are no longer clipped to the box and they too extend into the whitespace.

**How to Reproduce**

1. Create simple map with vector tile basemap
2. Create simple layout in Print Layout with a mapbox
3. Export to PDF/image/SVG
4. Exported map will have vector lines extending into whitespace surrounding map.

I'm having trouble uploading images to Github but will come back later on a different connection.

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

I tried:

Using Vector tile as it was
Connecting manually to each layer
Using a new profile

As soon as the vector tile layer is off, my original shapefiles were clipped as they should be and there were no problems.
When I export to image or PDF it appears that just the vector lines and shapes extended into the whitespace, while the SVG option the entire map extended into the space, but they both were cut off at the same point which appear to be a couple cm outside of the map box.

**Comment by Gustry** [comment] 2020-07-09 05:39
Duplicate of https://github.com/qgis/QGIS/issues/37443

**Closed by Gustry** 2020-07-09 05:39 UTC
Labels: Bug
