### ISSUE TITLE
Crash Trying to export to pdf or print to pdf

### ISSUE THREAD

**Issue by getspatial** [qgis/QGIS#39489] opened 2020-10-20 01:03 UTC
## User Feedback

I am trying to print a 96x78 inch map.  I have a number of auto placed and manual placed labels.  This crash happened upon trying to print as raster to a pdf printer.  The same issue has happened when trying to export to pdf.

## Report Details

**Crash ID**: [aeb471d6ec218be1234485c937f3cb4269a1e0c9](https://github.com/qgis/QGIS/search?q=aeb471d6ec218be1234485c937f3cb4269a1e0c9&type=Issues)

**Stack Trace**
<pre>
memcpy_repmovs memcpy.asm:114
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon qgssymbollayer.cpp:783
QgsSimpleFillSymbolLayer::renderPolygon qgsfillsymbollayer.cpp:314
QgsFillSymbol::renderPolygonUsingLayer qgssymbol.cpp:2227
QgsFillSymbol::renderPolygon qgssymbol.cpp:2182
QgsLayoutItemPage::draw qgslayoutitempage.cpp:286
QgsLayoutItem::paint qgslayoutitem.cpp:411
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion qgslayoutexporter.cpp:261
QgsLayoutExporter::renderRegionToImage qgslayoutexporter.cpp:300
QgsLayoutExporter::renderPageToImage qgslayoutexporter.cpp:207
QgsLayoutExporter::printPrivate qgslayoutexporter.cpp:1249
QgsLayoutExporter::print qgslayoutexporter.cpp:870
QgsLayoutDesignerDialog::print qgslayoutdesignerdialog.cpp:2011
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:439
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1618
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.14.16-Pi
QGIS code revision: df27394552
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment] 2020-10-20 07:29
Duplicate of https://github.com/qgis/QGIS/issues/35929

**Closed by gioman** 2020-10-20 07:29 UTC
Labels: Bug
