### ISSUE TITLE
Crash on rendering atlas map

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27736] opened 2018-09-21 12:17 UTC
Author Name: **nicolas sauzay** (nicolas sauzay)
Original Redmine Issue: [19912](https://issues.qgis.org/issues/19912)
Affected QGIS version: 3.2.3
Redmine category:unknown

---
## User Feedback

When oppening project created with 2.18.xx in version 3.2.3, i'm openning the composer which basically defines an atlas based on a layer which contains map definition (scale, layer view, name of map ...) All attribute are used to compose the atlas map.
When activating the atlas view, first map is view correctly, second one lead to app crash.

## Report Details

*Crash ID*: b8eab24505967c265177634bcfcf25d51c2a68ce

*Stack Trace*
```
QRasterPaintEngine::transformChanged :
QPainter::translate :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QMainWindow::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: 9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by rouault** [comment] 2020-01-23 19:20
Assuming this was due to a WFS layer, and thus closing as a duplicate of #32913

**Closed by rouault** 2020-01-23 19:20 UTC
Labels: Bug, Crash/Data Corruption
