### ISSUE TITLE
Topological editing does not interpolate z-coordinate

### ISSUE THREAD

**Issue by vjaaskel** [qgis/QGIS#49105] opened 2022-06-21 10:13 UTC
### What is the bug or the crash?

When polygon feature is split with topological editing on, vertex added to adjacent geometry has z-coordinate with value nan.

### Steps to reproduce the issue

1. Open attached project
2. Set topological editing on
3. Split feature with fid=1 so that a vertex in created in feature with fid=2
4. Vertex that is created in feature 2 has z-coordinate value nan
[project.zip](https://github.com/qgis/QGIS/files/8947862/project.zip)

### Versions

QGIS version
3.22.7-Białowieża
QGIS code revision
5a65627a
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
numericalDigitize
0.4.7
plugin_reloader
0.8.2
qgis_espa_integration
0.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lbartoletti** [comment] 2022-06-21 11:46
@Koyaani is haven't been fixed recently? or maybe it's a duplicate issue?

**Comment by Koyaani** [comment] 2022-06-28 07:39
@lbartoletti It's hard to say... The problems with z or m coordinates that end up with a nan value are similar... However, there is a possibility that this issue is due to my PR #46357 because I modified the condition that activates or deactivates the interpolation...

**Comment by JuhoErvasti** [comment] 2023-03-27 12:26
This issue can be reproduced in 3.28.4 and 3.30.0 versions.

**Comment by ismogis** [comment] 2023-07-03 11:50
It seems that this issue can not be reproduced in 3.32.0. If I'm correct #53526 fixes also this one. The fix hasn't been backported to the LTR version.

**Comment by troopa81** [comment] 2023-08-09 07:11
@ismogis the fix has been backported and exist in 3.28.9 released the 21th of July. Could you test and confirm me that you no longer get the issue with 3.28.9 ?

**Comment by ismogis** [comment] 2023-08-09 10:44
@troopa81 I tested in 3.28.9 and I didn't get the issue anymore. Thx!

**Comment by troopa81** [comment] 2023-08-09 13:40
Thank you for testing, good to hear

**Closed by troopa81** 2023-08-09 13:40 UTC
Labels: Editing, Bug, Digitizing
