### ISSUE TITLE
Georeferenced Rasterimage misaligned

### ISSUE THREAD

**Issue by jonnycastaway** [qgis/QGIS#34761] opened 2020-02-28 08:44 UTC
Hello,
with QGIS Desktop 3.8 i started a little Project.
I only show a Google Map and then import some raster images (Floorplans) with Georeferencing. In 3.8 it's all ok but open the Project with 3.12 all the referenced floorplans are shown ~30km of in the north direction.

Any hints?

**Comment by nirvn** [comment] 2020-02-28 09:34
You'll need to add more details in this issue, like steps to reproduce, sample images to georeference, etc.

**Comment by roya0045** [comment] 2020-02-28 13:13
Floorplans? Could this be caused by the smallness of the raster and the changes to proj?

**Comment by jonnycastaway** [comment] 2020-03-02 06:59
Some more details:
Opened QGIS 3.8 with a new project. From the browser imported the OpenStreetMap layer.
Zoomed to a building. Opened the georeferencing from raster menu. Opened a raterimage there.
Set reference points with button "from Map". Set the transformation settings. And then let qgis do his work with the playbutton. At the end there is a nice floorplan on the building. Saved and closed project. Opened this project with QGIS 3.12 and voila, the floormap layer showed ~30km north.

The ratser image is a png with 10000x5255 pixels, 32bit depth and transparency (alpha).

If someone can tell me how to upload an video i can take one and share.

**Comment by nirvn** [comment] 2020-03-02 07:09
@jonnycastaway , can you provide a test project with sample data?

**Comment by jonnycastaway** [comment] 2020-03-02 07:12
yes, of course.
but how to upload?

**Comment by nirvn** [comment] 2020-03-02 07:13
@jonnycastaway , you can attach compressed zip files in github directly (drag and drop the zip file onto the text area). Or you can paste a dropbox URL, etc.

**Comment by jonnycastaway** [comment] 2020-03-02 07:31
ok, i use the fast way (zip).
i didn't know that thsi is possible in github :-/
attention, the georeferenced floorplan (.tif) is really big after decompressions (~310MB). but i need the details to zoom in.
[allrad24_test.zip](https://github.com/qgis/QGIS/files/4273955/allrad24_test.zip)

**Comment by nirvn** [comment] 2020-03-02 08:44
@jonnycastaway , OK, first, the workaround: manually change the CRS of your foorplan tif to EPSG:3857 , things will align perfectly. You do that by right click on the layer in the layers panel.

The possible problem here is that the projection data attached to the tif has gdal/proj attribute a different project (EPSG:54004). 

Are you willing to do a few more tests? If so, please do the following:
a/ open the floorplan tif in QGIS 3.8, and tell us back what project the layer is set to (EPSG:3857 or EPDG:54004)
b/ try to re-geoference the floorplan _within_ QGIS 3.12 and see if the resulting tif opens as EPSG:3857

**Comment by jonnycastaway** [comment] 2020-03-02 10:27
First things first: thank you for the workaround. It's now working as expected.

And now to your topics a and b.

a/ in QGIS 3.8 this is the output:
![image](https://user-images.githubusercontent.com/25009091/75667276-ac4fdc80-5c77-11ea-9979-d37bfc628cbe.png)

b/ and the newly georefenced raster in QGIS 3.12
![image](https://user-images.githubusercontent.com/25009091/75667704-60e9fe00-5c78-11ea-95f3-fe21202037b9.png)

The transformation settings in the georeferecer where the same in QGIS 3.8 and QGIS 3.12.
So maybe it's a fixed bug between these versions and i didn't know?

**Comment by nirvn** [comment] 2020-03-02 11:26
@jonnycastaway , where is this "*Erzeugtes KBS" projection (in QGIS 3.8) coming from? Is it a user saved custom projecton? If so, that's likely the root cause of this variance in behavior between PROJ pre-6 (which wouldn't be a bug in itself).

I'm closing this now as the issue - if there actually is any - is clearly not on the QGIS side of things.

Glad manually setting the CRS for those self georeferenced rasters is a workable solution for you.

**Closed by nirvn** 2020-03-02 11:26 UTC
Labels: Bug, Feedback

**Comment by jonnycastaway** [comment] 2020-03-02 13:47
This comes automaticallly from the georeferencer.
The Transformation Settings are the same as in QGIS 3.12.
Also the Project Settings:
![image](https://user-images.githubusercontent.com/25009091/75681841-addbcd80-5c94-11ea-8940-2a2217160dbf.png)

So, i don't know where this is coming from.
Anyway, thank for your help, it's all ok now!

**Comment by jonnycastaway** [comment] 2020-03-02 13:51
![image](https://user-images.githubusercontent.com/25009091/75682004-fa270d80-5c94-11ea-9085-619b764da34b.png)

Is this the problem? First point say "CRS from ther first layer". Seconds point say "USW EPSG:4326".
But the first layer was OpenStreetMap with EPSG:3857.

I think thats the answer.
