### ISSUE TITLE
very very slow layout view (3.22.2)

### ISSUE THREAD

**Issue by Espressorite** [qgis/QGIS#47033] opened 2022-01-27 13:30 UTC
### What is the bug or the crash?

Dear All,

Since upgrading to 3.22.2 I have been experiencing very slow operations within the layout window. For example, changing the scale from 25,000 to 5,000 can take up to 5 minutes to render (if ever). I have never experienced QGIS to be this slow in the past. I am running on a 64gb desktop designed for high intensity workflows so its not the machine.

Any ideas why this is happening? 

Thanks

### Steps to reproduce the issue

n.a

### Versions

3.22.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2022-01-27 14:27
This is not helping to know what might be causing this slowdown. Finding out of the issues comes from a specific layer/layertype or is related to a code change would be helpful, but that's too generic to be of any help.

**Comment by gioman** [comment] 2022-01-27 19:13
> Any ideas why this is happening?

@Espressorite hard to day without a project+data we can test ourselves. 

Does it happens with any project/layout, regardless of the data?

If you open the project/layout in 3.16.17 or 3.22.3, how it works?

Have you tried on a new QGIS profile?

**Comment by samaritakis** [comment] 2022-02-04 11:38
I have the same issues since the version 3.18  and on. The same projects and data that work propelry  when on QGIS 3.16.17, can't be worked properly with the newer versions. This doesn't happen when the layout is simple or one paged but on more complicated layouts with many pages, atlas and heavy data. But the same projects work fine when working my layout on QGIS 3.16.

**Comment by nyalldawson** [comment] 2022-02-06 22:24
Is an xyz or WMS layer present in the project?

**Comment by samaritakis** [comment] 2022-02-06 22:29
I have a google satellite xyz layer in my project but it;'s not enabled in the layout. In the layout composer i have a vrt raster as basemap. The thing is that it works perfectly in QGIS 3,16.

**Comment by nyalldawson** [comment] 2022-02-06 22:32
> In the layout composer i have a vrt raster as basemap

if you setup the project so that this layer isn't visible in the layout do things improve?

**Comment by samaritakis** [comment] 2022-02-06 23:00
I removed all the rasters and xyz layers and yes it did improve.

**Comment by nyalldawson** [comment] 2022-02-06 23:01
@samaritakis 
another question -- if you change the "dpi" property in the layout settings, does things work well even with the xyz and raster layers?

**Comment by samaritakis** [comment] 2022-02-06 23:49
@nyalldawson No, not really. It keeps redrawing the maps. It's a heavy project (17maps in 11 pages). When I zoom in/out or pan, it redraws the maps again.

**Comment by JamieS-VPA** [comment] 2022-02-15 00:05
We are experiencing the same issue across multiple projects.
Currently using v3.22.1. 

The issue seems to have started since updating from 3.20.x

@nyalldawson - I'm not sure if this additional information might help find the root cause:

- The problem is most significant with layouts that contain Atlas's and where the legend is set to "filter to current map". 
- It is not just the re-drawing of the map or exporting - just selecting, moving, changing any layout item can take minutes. 
- If we un-check "filter legend items to current map" things generally improve significantly, then if we re-check the box in order to do the export, it returns being slow.
- While a layout with such at Atlas that runs slow is open, it basically makes the rest of QGIS run hideously slow also.

This is making many of our projects that have had significant time/effort to develop basically un-usable. 
I thought it was just one project in particular, but have since discovered the problem exists with anything with Atlas's and lots of layers.

**Comment by gioman** [comment] 2022-02-28 18:38
> Definitively the issue is with the legend.

@cesarkero can you provide a sample project+data that shows the issue?

**Comment by cesarkero** [comment] 2022-03-01 08:16
It is weird but that laggy behavior and crushes just goes away activating the atlas and making a full zoom. In may case, that solves the problem and now I can export the full atlas with filtering layers in the leyend.

**Comment by mlseguin** [comment] 2022-04-07 07:54
I have the same issue on almost all my projects. It comes indeed from the legend item and occure when the "atlas" & "filter legend items to current map" options are activated. The full zoom view does not improve Qgis behavior but when I zoom to 400% or more (when very few thinks are visible in the composer windows).

I will try to make you an sample project which is not too heavy

**Comment by mlseguin** [comment] 2022-05-11 15:07
J'ai modifié un projet et l'ai partagé sur mon [drive](https://drive.google.com/drive/folders/1OVKnB0QTy2XFA5zEVPUQgH9-_-JwZmY3?usp=sharing). A priori c'est très lent sur le composeur nommé ENJEU (enfin chez moi)

**Comment by stafoo** [comment] 2022-05-20 10:55
With QGIS 3.22.7 the problem related to filtered legend items when activating Atlas in still here.

In my projects:
- if Atlas is not activated, QGIS 3.22 and 3.16 layout performances are comparable;
- once activated, Atlas slows down the whole program if "filter legend items to current map" is checked; closing the print layout window doesn't help and QGIS must be closed to restore previous performances;
- if "filter legend items to current map" is not checked, Atlas performs well in QGIS 3.22, without crashes.

Hope it helps

**Comment by nyalldawson** [comment] 2022-05-23 04:09
Testing of https://github.com/qgis/QGIS/pull/48686 would be very much appreciated -- for me it fixes at least the issue with the project linked in https://github.com/qgis/QGIS/issues/47033#issuecomment-1123905278

**Comment by mlseguin** [comment] 2022-05-23 12:34
Thank you for this. How / where do you apply it?

**Comment by roya0045** [comment] 2022-05-23 12:45
> Thank you for this. How / where do you apply it?

Compile it or alternatively if you are on windows just test the mig artefact at https://github.com/qgis/QGIS/actions/runs/2368915142

**Comment by roya0045** [comment] 2022-05-23 15:44
@stafoo You did exactly what needed to be done. ;)

**Closed** 2022-05-23 20:44 UTC
Labels: Bug, Print Layouts

**Comment by legnad** [comment] 2022-08-05 06:17
The Problem is still present for me in 3.22.9. Should it be fixed by now? 

For me it is still clearly connected to the legend element. I figured I can boost performance when not selecting a related map (or selecting an empty dummy map) within the properties of the legend. 

By doing this I can also edit the name of the individual items without having it freeze with every char.

**Comment by stafoo** [comment] 2022-08-05 07:03
In my projects the problem in fixed with QGIS 3.22.9: layouts with filtered legends that use atlas feature are now enough responsive.
With multipage layouts I suggest to "zoom" and view only one page at a time (1:1 icon zoom), then activating atlas and print layouts.

That said, it is true that:
- editing a legend in "big" layouts is slow;
- changing resolution (dpi) is slow too.
However in my projects deactivaging atlas feature does not help to make both editings faster...

**Comment by djbiggs** [comment] 2022-11-30 04:56
Working on layouts has become a pain. Generally legends are painfully slow to update when typing into them ( no atlas activated)

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009




Active Python plugins
AnotherDXF2Shape
CalculateGeometry
FreehandRasterGeoreferencer
geoscience
mask
pointsamplingtool
profiletool
qfieldsync
QPackage
SimilarityPlugin-main
ViewshedAnalysis
db_manager
MetaSearch
processing

**Comment by djbiggs** [comment] 2022-11-30 04:57
Colleague has tried the latest build as well to no avail. ( 3.22.2)

**Comment by weca-theo** [comment] 2022-12-13 15:07
Can confirm with QGIS 3.22.8 LTR. Unchecking the "only show items inside linked map" is a life saver, which speeds up operations such as:
- adding a layer to the legend
- renaming a layer in the legend

yet to see if the setting improves Layout View opening or not. Layers shown are VTS basemap and POLYGON PostGIS layer with ~1000 features.

**Comment by stafoo** [comment] 2022-12-15 11:44
QGIS 3.22.13 here:

- filtered legends still slow down QGIS (such as editing legend items, texts, symbols, interacting with interface)
- unchecking the "filter" speeds up thigs

This is no more related to Atlas, that now works as expected in my case

**Comment by fischerteamplan** [comment] 2023-01-11 21:15
am experiensing the same problem, even in QGIS 3.22.10 (filtered legends slow down Layout View)

- does anyone know in which Version of QGIS this issue got solved?

**Comment by nmaysgs** [comment] 2023-01-18 23:33
The issue is present on 3.22.14 for me, not an issue on 3.16. Have to turn off the legend element to make any changes to layout without significant performance issues. 

There has always been an issue using a filtered legend with 20+ layers, but this issue the legend is not connected to the Map and just the items itself are causing a bug.

**Comment by nyalldawson** [comment] 2023-01-19 01:10
I'll take a look at this during the 3.30 bug fixing period. A sample project would be appreciated !

**Comment by mlseguin** [comment] 2023-01-19 08:10
My project might still be available in one of the message above. The issue was fixed in a version of qgis 3.25 (not released as an official version) -see above- but the patch was not put into qgis 3.26

**Comment by mlseguin** [comment] 2023-01-19 08:13
The problem increase with the number of layers and when using Wfs and/or postgis layers

**Comment by fischerteamplan** [comment] 2023-01-19 08:57
> I'll take a look at this during the 3.30 bug fixing period. A sample project would be appreciated !

thanks. I'll send you mine via email.

**Comment by frafra** [comment] 2023-06-23 10:24
@nyalldawson it is not fixed in 3.22.14, which include the backported patch (see #48704).
Just adding a single character to the legend makes QGIS unresponsive for minutes.

**Comment by AlisterH** [comment] 2023-07-07 02:18
FWIW I still find things in the layout window surprisingly slow, although the worst problems only occur when there are WMS/WFS/etc layers (apart from slowness due to web services being throttled and/or timing out, I think there are problems with QGIS making unnecessary requests e.g. when I have a WFS layer the layout window spends enormous amounts of time loading that layer, generating lots of network traffic - I wonder if it is downloading the whole layer rather than using a BBOX, and perhaps this only occurs if the map CRS doesn't match the layer CRS - I'm not sure)

I've also noticed that various actions in the layout window often cause the main canvas to redraw when there seems to be no need for this (perhaps they are accidentally redrawing the main canvas rather than the layout).  But testing it now I'm having trouble reproducing.

**Comment by roya0045** [comment] 2023-07-07 15:54
> FWIW I still find things in the layout window surprisingly slow, although the worst problems only occur when there are WMS/WFS/etc layers (apart from slowness due to web services being throttled and/or timing out, I think there are problems with QGIS making unnecessary requests e.g. when I have a WFS layer the layout window spends enormous amounts of time loading that layer, generating lots of network traffic - I wonder if it is downloading the whole layer rather than using a BBOX, and perhaps this only occurs if the map CRS doesn't match the layer CRS - I'm not sure)
> 
> I've also noticed that various actions in the layout window often cause the main canvas to redraw when there seems to be no need for this (perhaps they are accidentally redrawing the main canvas rather than the layout). But testing it now I'm having trouble reproducing.

As far as I'm aware, web layers are always fully loaded and cached locally and any subsequent request is done on the cached version. I've tried to look into building a smaller cache by including bbox and only append new elements but didn't have time to finish debuging the implementation.
