### ISSUE TITLE
QGIS is using a custom TMPDIR variable

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#48244] opened 2022-01-28 11:24 UTC
I have troubles when using grass processing tools. I discovered that it's using a custom cache path `/private/var/folders/gs/gzbw4skj6_s7qnb9j96gw9h80000gn/T/`

After looking at the QGIS settings, I finally discovered that QGIS was loading a TMDIR directory path variable.
![Capture d’écran 2022-01-28 à 11 55 29](https://user-images.githubusercontent.com/2520948/151538736-d5d1eb64-0d85-4e77-b204-ea19fa7fe648.png)

I cannot find a way to remove this once for all.

**Comment by agiudiceandrea** [comment] 2022-09-18 11:54
Duplicate of #47048.

**Closed by agiudiceandrea** 2022-09-18 11:54 UTC
