### ISSUE TITLE
Crash trying to create a folder

### ISSUE THREAD

**Issue by wqgis** [qgis/QGIS#30804] opened 2019-07-19 02:33 UTC
<Crash ID: d76ef2dff745d2aba152da6d1350374fbeb23cff

Stack Trace

RtlRaiseStatus :
longjmp :
longjmp :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601
!--
Bug fixing and feature development is a community responsibility, and not the responsibility of the QGIS project alone.
If this bug report or feature request is high-priority for you, we suggest engaging a QGIS developer or support organisation and financially sponsoring a fix

Checklist before submitting

- [ ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [ ] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

If the issue concerns a **third party plugin**, then it **cannot** be fixed by the QGIS team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description). -->

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by jgrocha** [comment] 2019-07-19 22:29
This bug report does not provide any useful information. 
Can you describe what you were doing before QGIS crash?
How can I reproduce the bug?

Please provide more feedback about this issue.

**Comment by wqgis** [comment] 2019-07-19 23:35
Hi Jorge,
When I try to create a Grass folder this is the screen that appears

**Comment by m-kuhn** [comment] 2019-07-20 13:42
Please provide a step by step description including any possibly relevant information to reproduce this problem.

QGIS 3.6.0 is no longer supported. Please also verify if this problem exists in a currently supported version (latest 3.4 release or latest 3.8 release or master/nightly).

**Comment by gioman** [comment] 2019-07-20 13:54
> When I try to create a Grass folder this is the screen that appears

@wqgis do you mean creating a GRASS location/mapset with the QGIS/GRASS plugin?

**Comment by wqgis** [comment] 2019-07-23 12:41
Hi,
I started going to Complements->Grass->New maps directory
[image: grass 1.jpg]
then
[image: grass2.jpg]
and
[image: grass3.jpg]

after "Next" the error screen appear
[image: grass4.jpg]

I try to do it in my notebook with win7 64b and in my desktop with win7 32b

**Comment by gioman** [comment] 2019-07-23 12:42
Can't see any image in your reply.

**Comment by gioman** [comment] 2019-07-23 12:42
anyway seems duplicate of https://github.com/qgis/QGIS/issues/30317

**Comment by gioman** [comment] 2019-08-25 09:15
Closing as duplicate.

**Closed by gioman** 2019-08-25 09:15 UTC
Labels: Bug, Feedback, GRASS
