### ISSUE TITLE
If the scale is locked and the view rotated, magnifier level changes when panning.

### ISSUE THREAD

**Issue by bru500** [qgis/QGIS#53480] opened 2023-06-15 13:00 UTC
### What is the bug or the crash?

If the scale is locked and the view rotated, magnifier level changes when panning.
Magnifier level should not change.
The problem only occurs, if a map rotation is set.

### Steps to reproduce the issue

1. Open an new empty project.
2. Set the Rotation at the bottom right to 45° (Current clockwise map rotation in degrees)
3. Check the lock between scale and magnifier at the bottom (Lock the scale to use magnifier to zoom in or out)
4. Note, that magnifier level is set to 100%.
5. Pan the map or click in the map with activated Pan tool.
6. Note that the magnifier level changes (first it changes from 100% to 114%, then to 131%, 149%, etc.)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.7-Firenze | QGIS code revision | fedae0eb52
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geodata2envimet | 1.5
menu_from_project | v2.0.8
qfieldsync | v4.5.0
slyr | 6.2.1
slyr_community | 5.0.0
swiss_locator | 2.0.6
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99
StreetView | 3.2

</body></html>QGIS version
3.28.7-Firenze
QGIS code revision
[fedae0eb52](https://github.com/qgis/QGIS/commit/fedae0eb52)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geodata2envimet
1.5
menu_from_project
v2.0.8
qfieldsync
v4.5.0
slyr
6.2.1
slyr_community
5.0.0
swiss_locator
2.0.6
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
StreetView
3.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by YoannQDQ** [comment] 2023-06-18 11:29
Duplicate of #43275

**Comment by YoannQDQ** [comment] 2023-06-18 11:32
Fixed by #52069 (3.30). Should have been back ported to 3.28 though.

**Closed** 2023-06-18 11:32 UTC
Labels: Map and Legend, Map Tools, Bug

**Comment by agiudiceandrea** [comment] 2023-06-18 19:54
Thanks @YoannQDQ.

**Comment by bru500** [comment] 2023-06-19 04:52
Sorry for my duplicate and thanks for fixing!
Is it still possible to backport to ltr?

**Comment by YoannQDQ** [comment] 2023-06-19 05:24
Yes, I created #53493, waiting for approval.

**Comment by agiudiceandrea** [comment] 2023-06-19 05:45
@YoannQDQ, since it was backported to the queued_ltr_backports branch and not directly to the release-3_28 branch, I think the first QGIS LTR version in which the fix will be available is QGIS 3.28.9. Isn't it?

**Comment by YoannQDQ** [comment] 2023-06-19 17:27
You're probably right. I'm not that familiar with the release cycle. My bad.
