### ISSUE TITLE
"Advanced Python Field Calculator " in modeller is missing the "Only update selected features" option

### ISSUE THREAD

**Issue by arx-it** [qgis/QGIS#37946] opened 2020-07-23 13:38 UTC
Description :
In Model Designer, the processing "Field Calculator Advanced Python" does not contain the option "Only update selected features", with LTR QGIS Version 3.14.1-Pi :
![image](https://user-images.githubusercontent.com/12830337/88292319-ca3ade00-ccf9-11ea-8d7b-4428fc488c3d.png)

Whereas the option is included in the geoprocessing only :
![image](https://user-images.githubusercontent.com/12830337/88292515-02dab780-ccfa-11ea-9f76-43994fba72af.png)

So the Field Calculator is executed on all entities.

Workaround :
I need to create a request in the Field Calculator :
_CASE
    WHEN  "id"  = 1 THEN 'A'
    WHEN  "id"  = 2 THEN 'B'
END_

Version de QGIS
3.14.1-Pi
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
qgis2web; 
simplesvg; 
db_manager; 
MetaSearch; 
processing

**Comment by alexbruy** [comment] 2020-07-23 13:46
This is not a bug. Selection exists only in project layers, while models operate on generic inputs. If you need to use only subset of features use one of the "Extract…" algorithms to extract them.

**Comment by gioman** [comment] 2020-07-23 13:51
Closing?

**Comment by alexbruy** [comment] 2020-07-23 13:52
I'd say yes.

**Closed** 2020-07-23 13:59 UTC
Labels: Bug, Feedback, Modeller, Processing

**Comment by arx-it** [comment] 2020-07-23 14:18
Ok thank you for your replies
