### ISSUE TITLE
Maybe change color of Point Cloud icon?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#41344] opened 2021-02-03 21:29 UTC
If others agree, we could change the Point Cloud icon color to one more like the other colors in the Datasource Manager?

![Screenshot-20210203144843-140x203](https://user-images.githubusercontent.com/731673/106811229-5301e180-666e-11eb-91e1-538b73e01422.png)

See this thread on dev list:
https://lists.osgeo.org/pipermail/qgis-developer/2021-February/063020.html

Charles there also proposed (and attached!)  an (in my view) alternative icon of point clouds:

![Screenshot-20210203222526-128x134](https://user-images.githubusercontent.com/731673/106811510-b986ff80-666e-11eb-967a-6d82dcd20667.png)

As asked I'll assign this to @SrNetoChan

**Comment by nyalldawson** [comment] 2021-02-03 21:36
Duplicate of https://github.com/qgis/QGIS/issues/41040

**Closed by nyalldawson** 2021-02-03 21:36 UTC
Labels: Feature Request, GUI/UX
