### ISSUE TITLE
Duplicate Layer changes Field type and name

### ISSUE THREAD

**Issue by garvamel** [qgis/QGIS#44087] opened 2021-07-08 14:31 UTC
Imported a CSV and then copied the data to a new layer to be able to edit it. After that, I duplicated the copied layer, as I needed different visual representations. The duplicated layer has an issue where the first field "Pozo", type Qstring text, is duplicated as "Pozo:text(0,0)" type Qstring string, which creates some issues with symbology filters already in place from the original layer.

This is the source layer (copied layer from CSV layer):
<img width="893" alt="Original" src="https://user-images.githubusercontent.com/17742377/124937004-00d63b00-dfd5-11eb-99a0-daa3dd08b1b8.png">

This is the duplicate layer (duplicated from the copied layer):
<img width="937" alt="Duplicate" src="https://user-images.githubusercontent.com/17742377/124937028-059aef00-dfd5-11eb-9a22-2ad14e5650c0.png">

This is the dataset:
[BP-004.csv](https://github.com/qgis/QGIS/files/6785245/BP-004.csv)

This are the import settings I used:
<img width="1078" alt="Import" src="https://user-images.githubusercontent.com/17742377/124939363-0896df00-dfd7-11eb-8f9b-9da65a4d556d.png">

My system is a Macbook Pro Retina 2013 with macOS Big Sur 11.4 and QGIS info is the following:

<img width="1067" alt="Info" src="https://user-images.githubusercontent.com/17742377/124937056-0a5fa300-dfd5-11eb-97e2-8827785da3d6.png">

Steps I followed:

1. Imported dataset
2. Selected layer, selected all, and copied with CMD+A followed by CMD+C
3. Pasted copied data onto a new temporary layer with OPTION+CMD+V (this temporary layer has the correct field name)
4. Duplicated the newly created layer by right clicking and selecting "duplicate layer" (this duplicate layer has the incorrect field name)

I hope that's enough info. Thank you in advance.

**Comment by gioman** [comment] 2021-07-08 17:41
> * Pasted copied data onto a new temporary layer with OPTION+CMD+V (this temporary layer has the correct field name)
> 
> * Duplicated the newly created layer by right clicking and selecting "duplicate layer" (this duplicate layer has the incorrect field name)

@garvamel can't replicate on 3.16.8 on Windows. But I guess that it could also depend on how you created the temp layer (step 3).

**Comment by garvamel** [comment] 2021-07-08 18:28
@gioman I used the "Paste Features As > Temporary scratch layer" keybinding.

Still, the layer created in step 3 is identical to the imported CSV, it's the duplicated one (step 4) that displays the issue.

These are the fields of the imported CSV, as you see, identical to the first picture (the copied layer):

![image](https://user-images.githubusercontent.com/17742377/124972738-b666b580-dff8-11eb-8eeb-2e11749e669a.png)

Thanks.

**Comment by agiudiceandrea** [comment] 2021-07-08 18:37
I can replicate on Windows:
- select all the feature of the csv layer (Edit - Select - Select All Features)
- copy the features (Edit - Copy Features)
- past the features in a new memory layer (Edit - Paste Features As - Temporary Scratch Layer)
- duplicate the newly created memory layer (Layer - Duplicate Layer(s))

Anyway a think the issue is in the duplicate layer process.

**Comment by gioman** [comment] 2021-07-08 18:38
> @gioman I used the "Edit > Paste Features As > Temporary scratch layer" keybinding.

I can replicate using this method.

**Comment by agiudiceandrea** [comment] 2021-07-08 18:45
Maybe related to this PR https://github.com/qgis/QGIS/pull/43916 by @domi4484

**Comment by agiudiceandrea** [comment] 2021-07-08 19:53
> Anyway a think the issue is in the duplicate of memory layer process.

I can confirm the issue is in the duplicate (clone) process of a memory layer and it is not related to the copy and paste as a new memory layer process.

To reproduce the issue using only a memory layer:
- create a new memory layer (New Temporary Scratch Layer)
- open the attribute table of the layer, add a new field with type "Text, unlimited length (text)" and name "Test_name", toggle off the editing mode
- duplicate the memory layer
- in the duplicated layer, the field name is "Test_name:text(-1,0)" instead of "Test_name"

The issue occurs with the following field types:
- Whole number (smallint - 16bit)
- Whole number (integer - 32bit)
- Decimal number (numeric)
- Decimal number (decimal)
- Decimal number (double)
- Text, unlimited length (text)

In the duplicated memory layer not only the fields names are changed, but also the fields types: they are all changed to Type "QString", Type name "string", regardless of the fact that the original field type was numeric int or double.

**Comment by garvamel** [comment] 2021-07-08 20:08
> Maybe related to the issue described and fixed with the PR #43916 by @domi4484

Seems related enough. Considering the PR is about the MemoryProvider specifically, I just attempted duplicating the CSV layer directly (and not the copied layer) and I can confirm there's no issue.

**Comment by domi4484** [comment] 2021-07-08 20:26
>     * in the duplicated layer, the field name is "Test_name:text(-1,0)" instead of "Test_name"
This is what I wanted to fix with #43916, but apparently something as gone wrong sorry. I'll take a look!

**Comment by garvamel** [comment] 2021-07-08 20:27
> > Anyway a think the issue is in the duplicate of memory layer process.
> 
> I can confirm the issue is in the duplicate (clone) process of a memory layer and it is not related to the copy and paste as a new memory layer process.
> 
> To reproduce the issue using only a memory layer:
> 
> * create a new memory layer (New Temporary Scratch Layer)
> * open the attribute table of the layer, add a new field with type "Text, unlimited length (text)" and name "Test_name", toggle off the editing mode and save the changes
> * duplicate the memory layer
> * in the duplicated layer, the field name is "Test_name:text(-1,0)" instead of "Test_name"
> 
> The issue occurs with the following field types:
> 
> * Whole number (smallint - 16bit)
> * Whole number (integer - 32bit)
> * Decimal number (numeric)
> * Decimal number (decimal)
> * Decimal number (double)
> * Text, unlimited length (text)
> 
> In the duplicated memory layer not only the fields names are changed, but also the fields types: they are all changed to Type "QString", Type name "string", regardless of the fact that the original field type was numeric int or double.

Curious enough is that my "doubles" didn't get changed.

**Comment by garvamel** [comment] 2021-07-08 20:40
In case it helps further, this is the Source from each layer's properties

Copied layer:

`Point?crs=EPSG:32718&uid={14681d35-1586-4255-b319-b98b0ef3b520}`


Cloned/duplicated layer:

`memory?geometry=Point&crs=EPSG:32718&field=Pozo:text(0,0)&field=Este:integer(0,0)&field=Norte:integer(0,0)&field=Ceramica:integer(0,0)&field=Malacologico:integer(0,0)&field=Total:integer(0,0)&field=Superficie:double(0,0)&field=Profundidad:double(0,0)&field=Volumen:double(0,0)&field=Densidad%20Ceramica:double(0,0)&field=Densidad%20Malacologico:integer(0,0)&field=Densidad%20Total:double(0,0)&uid={923dc09b-0169-4f78-9ee0-044738097357}`

**Comment by agiudiceandrea** [comment] 2021-07-08 20:57
> Curious enough is that my "doubles" didn't get changed. It might be a "first field" thing.

@garvamel your "double" fields are of Type "double" and Type name "double" and they are properly duplicated, while a field created as "Decimal number (double)" in a memory layer is of Type "double" and Type name "double precision" and it is not properly duplicated.

@domi4484 the issue occurs in 3.16.8, but your patch was merged after 3.16.8 and anyway only in master branch.
Could you test if your patch fixes this issue? If yes, I think yur patch should be backported to the 3.16 branch and probably also to the 3.20 branch.

**Comment by domi4484** [comment] 2021-07-08 21:09
I have found one part of the problem: this regex does not search for `text` typename:
https://github.com/qgis/QGIS/blob/f0838764b87568e4c3f7968e51ee2960c82df314/src/core/providers/memory/qgsmemoryprovider.cpp#L123
But there seems to be more issues... I'll dig a little more tomorrow

**Comment by domi4484** [comment] 2021-07-08 21:48
I am a bit confused by all these types of doubles... apparently there is one with typename `double precision` which is also missing from the regex above.

![image](https://user-images.githubusercontent.com/9881900/124994574-5696fb80-e046-11eb-9f8d-b7caa00916eb.png)

**Comment by agiudiceandrea** [comment] 2021-07-08 22:22
The "unrecognised" types that could be added to a memory layer are:
- Whole number (smallint - 16bit) | Type name: `int2` (
- Whole number (integer - 32bit) | Type name: `int4`
- Decimal number (numeric) | Type name: `numeric`
- Decimal number (decimal) ! Type name: `decimal`
- Decimal number (double) | Type name: `double precision`
- Text, unlimited length (text) | Type name: `text`

Those Type names are, in fact, not in the regex string.

Anyway it seems also to me the "double/real" types field are a bit confusing...

There are two "Decimal number (real)": the first one creates a Type `double` and Type name `double` field (!), while the second one creates a Type `double` and a Type name `real` field.

**Comment by agiudiceandrea** [comment] 2021-07-08 22:34
I guess also the new "list" types will not be properly cloned:
```c++
<< QgsVectorDataProvider::NativeType( tr( "String list" ), QStringLiteral( "stringlist" ), QVariant::StringList, 0, 0, 0, 0, QVariant::String )
<< QgsVectorDataProvider::NativeType( tr( "Integer list" ), QStringLiteral( "integerlist" ), QVariant::List, 0, 0, 0, 0, QVariant::Int )
<< QgsVectorDataProvider::NativeType( tr( "Decimal (real) list" ), QStringLiteral( "doublelist" ), QVariant::List, 0, 0, 0, 0, << QgsVectorDataProvider::NativeType( tr( "Integer (64bit) list" ), QStringLiteral( "doublelist" ), QVariant::List, 0, 0, 0, 0, QVariant::Double )
```

**Comment by domi4484** [comment] 2021-07-09 08:29
> I guess also the new "list" types will not be properly cloned:
> 
> ```c++
> << QgsVectorDataProvider::NativeType( tr( "String list" ), QStringLiteral( "stringlist" ), QVariant::StringList, 0, 0, 0, 0, QVariant::String )
> << QgsVectorDataProvider::NativeType( tr( "Integer list" ), QStringLiteral( "integerlist" ), QVariant::List, 0, 0, 0, 0, QVariant::Int )
> << QgsVectorDataProvider::NativeType( tr( "Decimal (real) list" ), QStringLiteral( "doublelist" ), QVariant::List, 0, 0, 0, 0,
> << QgsVectorDataProvider::NativeType( tr( "Integer (64bit) list" ), QStringLiteral( "doublelist" ), QVariant::List, 0, 0, 0, 0, QVariant::Double )
> ```

I think there is also an error in the list types, the typename for "Integer (64bit) list" should probably be something like "longlist" and not "doublelist"

**Comment by agiudiceandrea** [comment] 2021-07-09 08:32
> I think there is also an error in the list types, the typename for "Integer (64bit) list" should probably be something like "longlist" and not "doublelist"

Yes, I've already reported the typo about the field type https://github.com/qgis/QGIS/pull/42421/files#r666529986

**Comment by garvamel** [comment] 2021-07-09 21:07
Thank you everyone, I wish I knew more Python and the inner workings of QGIS to be of help. I can only open issues about the problems I encounter using the software.

**Comment by garvamel** [comment] 2021-07-09 21:29
> > Curious enough is that my "doubles" didn't get changed. It might be a "first field" thing.
> 
> @garvamel your "double" fields are of Type "double" and Type name "double" and they are properly duplicated, while a field created as "Decimal number (double)" in a memory layer is of Type "double" and Type name "double precision" and it is not properly duplicated.
> 

I see, why are there 2 types of double? I'm guessing it's because QGIS supports lot's of external DBs. and formats.

To me it would make more sense to convert to some standardized data types upon import and creation, and convert back only upon export or save (this so that QGIS works with a biunivocal datatype-data relationship; it would make data type handling more modular). Idk if it's feasible memory-wise or implementation-wise, though.

**Closed** 2021-07-12 13:05 UTC
Labels: Bug, Digitizing, Editing
