### ISSUE TITLE
New Layer From Selection

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [qgis/QGIS#40666] opened 2020-12-18 19:43 UTC
As someone who's migrating from ArcGIS, I'm missing a way of creating a new layer filtered with selected features. Currently, one can create a completely new layer with selected features but changes in this new layer won't reflect in the original source layer. I created a button wich duplicate selected layer, and filter by the ObjectID or ID or FID collected from the selection, but this assumes that one of these fields exists. This could be simplified if we could filter the layer by the @id token, but apparently, we cannot.

So, my request is the possibility to quickly create a new layer in wich changes will reflect the original layer, just like ArcGIS.

Thanks.

**Comment by gioman** [comment] 2020-12-18 20:06
> I'm missing a way of creating a new layer filtered with selected features.

@ItaloCunhaBueno the "extract selected features" tool does not work for you?

**Comment by nyalldawson** [comment] 2020-12-18 20:10
@gioman the ArcGIS functionality is closer to a virtual layer in operation -- it's just a view showing a subset of the original layer, not a copy.

**Comment by ItaloCunhaBueno** [comment] 2020-12-18 20:13
> > I'm missing a way of creating a new layer filtered with selected features.
> 
> @ItaloCunhaBueno the "extract selected features" tool does not work for you?

This algo creates a new layer in wich changes does NOT reflect the original layer, in ArcGIS, the "new layer from selection" works more like a view from the original layer, just like @nyalldawson said. That means any changes in this layer occurs in the original layer too.

**Comment by gubuntu** [comment] 2023-04-17 11:18
duplicate of https://github.com/qgis/QGIS/issues/17246 and https://github.com/qgis/QGIS/issues/36646

implemented in https://plugins.qgis.org/plugins/create_layer_from_selected_features/, would be nice if it were in core

**Comment by alexbruy** [comment] 2023-12-03 14:50
Duplicates #17246.

**Closed by alexbruy** 2023-12-03 14:50 UTC
Labels: Feature Request
