### ISSUE TITLE
GeoJSON: edits are not saved

### ISSUE THREAD

**Issue by freeshrugsxd** [qgis/QGIS#58261] opened 2024-07-29 12:26 UTC
### What is the bug or the crash?

In QGIS 3.38.1: when editing the geometry of a geojson feature with the vertex tool, hitting the "Save Layer Edits" button discards all changes to the geometry.

![geojson_edit_bug](https://github.com/user-attachments/assets/1ecbf13f-54c5-4c72-b355-8d5081649c91)

Edit 2024-08-06: **all edits are affected -- not only those to geometries.**

### Steps to reproduce the issue

1. load geojson into project
2. start edit session
3. make a change
4. try to save the edits

See this sample project for your convenience: [geojson_edits_not_saved_bug.zip](https://github.com/user-attachments/files/16412872/geojson_edits_not_saved_bug.zip)

### Versions

QGIS-Version | 3.38.1-Grenoble
-- | --
QGIS-Codeversion | 3d4177afc6
Qt-Version | 5.15.13
Python-Version | 3.12.4
GDAL-Version | 3.9.1
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.2-CAPI-1.18.2
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 10 Version 2009

Name | Version
-- | --
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It works without a problem on QGIS 3.34.9

**Comment by agiudiceandrea** [comment] 2024-07-29 16:41
I can confirm the issue occurs using QGIS 3.38.1 (from OSGeo4W, with GDAL/OGR 3.9.1) on Windows, while it doesn't occur using QGIS 3.34.9 (from OSGeo4W, with GDAL/OGR 3.9.1) on the same system.

**Comment by freeshrugsxd** [comment] 2024-08-06 10:17
It somehow completely slipped my attention that edits to attributes are also affected.

I remember testing adding new attributes, which works without a problem. Same goes for adding new geometries / features -- but once these are created, further updates are not saved. I will adjust the title of this issue to reflect that.

This issue makes it impossible to work with GeoJSON in 3.38.1.

**Comment by agiudiceandrea** [comment] 2024-08-06 10:31
Hi @nyalldawson @rouault, have you seen this regression report? It may be related to https://github.com/qgis/QGIS/pull/57736 and https://github.com/OSGeo/gdal/pull/10197.

**Comment by agiudiceandrea** [comment] 2024-09-14 06:27
Fixed by https://github.com/qgis/QGIS/pull/58740 since QGIS 3.40.

**Closed by agiudiceandrea** 2024-09-14 06:27 UTC
Labels: Data Provider, Regression, Bug, Digitizing
