### ISSUE TITLE
QGIS 3.10 unable to load PostGIS-table on MacOS Catalina

### ISSUE THREAD

**Issue by geomoes** [qgis/QGIS#32558] opened 2019-10-31 20:07 UTC
I just updated to the QGIS 3.10 release under MacOS Catalina. In 3.8 I had no problem using PostGIS-data. When I now try to load the same PostGIS-layer in 3.10 it fails. When testing the connection, it tells me that the connection is openend successfully. When I try to access the data, QGIS hangs on 'load tables from ...'(displayed at the bottom of the window), but the PostGIS-connection window, where schemas and tables are displayed usually stays empty?

Any ideas?

**Comment by gioman** [comment] 2019-10-31 20:15
it is the same for all 3 most common ways to load postgis layers (db manager, qgis browser, qgis data source manager)?

**Comment by Dan-Knott** [comment] 2019-11-01 00:30
I have also come across this issue running QGIS 3.10 on Windows 10. I've checked on all three methods you've suggested @gioman 

1. Via the qgis browser the connection opens successfully, however on loading the list of layers it hands and displays the message "Failed to get raster layers". In the log messages console for PostGIS there are the following messages: 
```
Erroneous query: SELECT l.f_table_name,l.f_table_schema,l.f_geometry_column,upper(l.type),l.srid,l.coord_dimension,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1 FROM geometry_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND n.nspname='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.f_table_name,l.f_table_schema,l.f_geography_column,upper(l.type),l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1 FROM geography_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND n.nspname='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.table_name,l.schema_name,l.feature_column,CASE WHEN l.feature_type = 1 THEN 'MULTIPOINT' WHEN l.feature_type = 2 THEN 'MULTILINESTRING' WHEN l.feature_type = 3 THEN 'MULTIPOLYGON' WHEN l.feature_type = 4 THEN 'GEOMETRYCOLLECTION' END AS type,(SELECT srid FROM topology.topology t WHERE l.topology_id=t.id),2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1 FROM topology.layer l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.table_name AND l.schema_name=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND n.nspname='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l."r_table_name",l."r_table_schema",l."r_raster_column",'RASTER',l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','topogeometry','raster') THEN 1 ELSE NULL END) , 1 FROM raster_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l."r_table_name" AND l."r_table_schema"=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege('"'||n.nspname||'"."'||c.relname||'"','select') AND n.nspname='public' GROUP BY 1,2,3,4,5,6,7,c.oid,11 ORDER BY 2,1,3 returned 7 [ERROR: permission denied for relation layer]
WARNING Unable to get list of spatially enabled tables from the database
```
2. Via the qgis data source manager, clicking connect doesn't produce any result in the interface, but also produces the above messages.
3. Via the db manager I am able to view the schema and open the layers as normal.

**Comment by gioman** [comment] 2019-11-01 11:14
maybe related to https://github.com/qgis/QGIS/issues/32523 ?

**Comment by thelferty** [comment] 2019-11-01 17:55
This seems to be similar to the problem described here: https://github.com/qgis/QGIS/issues/32483

We found a workaround for it. It only seems to be an issue for PG10.10.

**Comment by geomoes** [comment] 2019-11-03 14:47
I've tried the different ways to open PostGIS-layer in QGIS:
1. As described above opening the PostGIS-layer via the data source manager is not possible (no schemas are displayed).
2. Trying to add a layer using the browser, I get at least the schemas list. But the layers do not show up. There is an error:  couldn't retrieve layer.
3. Using the db manager the schemas are displayed and I'm able to open the layers as normal.

PostgreSQL is 11.5 running on Ubuntu 11.5
PostGIS is 2.5.3

**Comment by wdicks** [comment] 2019-11-27 06:46
I also have this problem of GQiS 3.10 not loading DBs tables. I've tried to give it time, but after about 20 minutes I gave up. I clicked the Stop button, but nothing happened. After about 10 minutes waiting for it to stop, I had to kill QGiS. I can only connect to tables via the browser.

I'm running QGiS on Windows 10, PostGres 11.0, PostGis 2.5.3.

**Comment by gioman** [comment] 2020-01-08 17:33
No issues here on Catalina with QGIS 3.10.1 and PostgreSQL 10/PostGIS 2.4.

Please give it a try with the latest installers.

**Comment by ponceta** [comment] 2020-02-19 09:11
I do have same behaviour here on QGIS 3.10.2, it might not be linked to the postgres/postgis version since I reproduce it differently on two different databases :

![image](https://user-images.githubusercontent.com/8614223/74818232-8d0f9180-52fe-11ea-9659-cf680e32a81b.png)

And working on :

![image](https://user-images.githubusercontent.com/8614223/74818286-a6184280-52fe-11ea-9b50-5d132a016221.png)

Both databases are stored on the same postgres 9.6 server / postgis 2.3

If I set the postgis log I have a warning here which is probably related on reading public.geometry_columns, public.geography_columns, which in that case are identical.

This works fine on QGIS 3.4.15

`2020-02-19T10:02:33     WARNING    Requête erronée : SELECT l.f_table_name,l.f_table_schema,l.f_geometry_column,upper(l.type),l.srid,l.coord_dimension,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','raster') THEN 1 ELSE NULL END) , 1 FROM geometry_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege(c.oid,'select') GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l.f_table_name,l.f_table_schema,l.f_geography_column,upper(l.type),l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','raster') THEN 1 ELSE NULL END) , 1 FROM geography_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l.f_table_name AND l.f_table_schema=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege(c.oid,'select') GROUP BY 1,2,3,4,5,6,7,c.oid,11 UNION SELECT l."r_table_name",l."r_table_schema",l."r_raster_column",'RASTER',l.srid,2,c.relkind,obj_description(c.oid),array_agg(a.attname), count(CASE WHEN t.typname IN ('geometry','geography','raster') THEN 1 ELSE NULL END) , 1 FROM raster_columns l,pg_class c,pg_namespace n,pg_attribute a,pg_type t WHERE c.relname=l."r_table_name" AND l."r_table_schema"=n.nspname AND NOT a.attisdropped AND a.attrelid=c.oid AND a.atttypid=t.oid AND a.attnum>0 AND n.oid=c.relnamespace AND has_schema_privilege(n.nspname,'usage') AND has_table_privilege(c.oid,'select') GROUP BY 1,2,3,4,5,6,7,c.oid,11 ORDER BY 2,1,3 a retourné 7 [ERREUR: droit refusé pour la relation raster_columns
             ]
2020-02-19T10:02:33     WARNING    ATTENTION: ATTENTION: aucune transaction en cours
2020-02-19T10:02:33     WARNING    Impossible d'obtenir une liste des tables spatialisées depuis la base de données`

**Comment by ponceta** [comment] 2020-02-19 09:29
I found my issue, QGIS 3.10.X is now checking postgis view public.raster_columns which was not publicly visible in some of my postgres db :

`GRANT SELECT ON TABLE public.raster_columns TO PUBLIC;`

**Comment by ponceta** [comment] 2020-02-19 09:42
On an older postgres database I had to grant public select on `geography_columns `

GRANT SELECT ON TABLE geography_columns TO public;

**Comment by lbartoletti** [comment] 2020-02-20 05:30
Seems to be already resolved by postgis https://trac.osgeo.org/postgis/ticket/4576 ? cc @strk

**Comment by strk** [comment] 2020-02-20 08:44
Those who have this problem: can you check out #34575 please ?

**Closed** 2020-02-21 18:00 UTC
Labels: Bug, Feedback
