### ISSUE TITLE
Unicode texts are not rendered properly when the mode is changed to Curved.

### ISSUE THREAD

**Issue by nabazgharib** [qgis/QGIS#53675] opened 2023-07-01 06:52 UTC
### What is the bug or the crash?

A gentle reminder to an issue still exists with new update ted of both LTR and current version of QGIS.

[https://github.com/qgis/QGIS/issues/49517#issue-1323091820](url)

I hope you put a bit of effort into it to fix, because this bug affects the maps we produce. (●'◡'●)

### Steps to reproduce the issue

everything is mentioned in the link.

### Versions

QGIS Version 3.32.0 Lima
QGIS Version 3.28.8

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment] 2023-07-01 07:05
Closing as duplicate of https://github.com/qgis/QGIS/issues/21940.

**Closed by nirvn** 2023-07-01 07:05 UTC
Labels: Bug
