### ISSUE TITLE
Click on scale on bottom kills instantly the program

### ISSUE THREAD

**Issue by jojo-gfx** [qgis/QGIS#52572] opened 2023-04-06 07:02 UTC
### What is the bug or the crash?

If I klick on scale on the bottom (because it's too small and can't read it so, the program is instantly run into an error.

Greetings

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000018e0 (most recent call first):

Stack Trace

QLocale::numberOptions :
QCalendarBackend::standaloneWeekDayName :
QString::toInt :
QgsScaleComboBox::showPopup :
QComboBox::showPopup :
QComboBox::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

click on scale on bottom of the screen

### Versions

3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2023-04-06 07:29
duplicate of https://github.com/qgis/QGIS/issues/52383

**Closed by nicogodet** 2023-04-06 07:29 UTC
Labels: Bug

**Comment by agiudiceandrea** [comment] 2023-04-06 14:23
The crash has been fixed with https://github.com/qgis/QGIS/pull/52511.
@jojo-gfx QGIS 3.30.2 and later versions will not crash in such situation. To workaround the issue with QGIS 3.30.1, please go to the "Settings->Options..." -> "Map Tools" -> "Predefined Scales" and click on the "Reset to default scales" button in order to restore the predefined scales, populate the scale listbox and avoid the crash.
