### ISSUE TITLE
Exporting labels to SVG <textPath>

### ISSUE THREAD

**Issue by superrache** [qgis/QGIS#36978] opened 2020-06-04 14:47 UTC
**Feature description.**

When exporting to SVG street labels on curved streets, we get separated letters. So it's not easy to edit manually with Inkscape or Illustrator.

![image](https://user-images.githubusercontent.com/4458770/83770786-cdaed300-a681-11ea-857e-04dc45628c9b.png)

SVG format has <textPath> element feature, that could be used in this case, for each word or each label sentence.

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath

It requires to define a parallele path to the street, then reference this path to define the text element. Maybe this parallele path already exists internally in QGIS and could be used in the SVG export.

**Additional context**

QGIS 3.12 on Windows and Mac.
Illustrator CC and Inkscape

**Comment by nyalldawson** [comment] 2020-06-08 00:40
Duplicate of #24369

**Closed by nyalldawson** 2020-06-08 00:40 UTC
Labels: Feature Request
