### ISSUE TITLE
QGIS Importing Geospatial PDF Without Background Image

### ISSUE THREAD

**Issue by PinQ235** [qgis/QGIS#46224] opened 2021-11-26 04:31 UTC
### What is the bug or the crash?

When dragging a geospatial PDF into QGIS, the background image is not shown. This happens to versions 3.22.0, 3.22.1, and 3.16.14.

### Steps to reproduce the issue

Just try the attached file, by dragging it into QGIS.
[sub.pdf](https://github.com/qgis/QGIS/files/7606280/sub.pdf)
 

### Versions

Happens on versions 3.22.0, 3.22.1, and 3.16.14. However, in version 3.16.11, it works just fine by showing the Google image. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment] 2021-11-26 08:21
Duplicate of https://github.com/qgis/QGIS/issues/44522

**Closed by gioman** 2021-11-26 08:21 UTC
Labels: Bug
