### ISSUE TITLE
 Error with GRASS tools in processing

### ISSUE THREAD

**Issue by Labros89** [qgis/QGIS#33997] opened 2020-01-23 11:15 UTC
Hi, I faced some problems with the GRASS toolbox yesterday. I followed some instructions from people who had similar problems. I changed the language in regional settings of Windows. So, I run again some tools from GRASS toolbox and it seems that somehow the problem have solved but still I cannot have an output. I got the following error:

Execution completed in 2.34 seconds
Results:
{'flowaccumulation': <QgsProcessingOutputLayerDefinition {'sink':C:/Advance GIS/Workspace/flow_accum.tif, 'createOptions': {'fileEncoding': 'System'}}>,
'flowlength': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>,
'flowline': <QgsProcessingOutputLayerDefinition {'sink':TEMPORARY_OUTPUT, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
**The following layers were not correctly generated**.<ul><li>C:/Advance GIS/Workspace/flow_accum.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

I am checking the Log Message Panel I got this error: 

  File "C:\OSGEO4~1\apps\grass\grass78\etc\grass78.py", line 2216, in 
             
              main()
             
              File "C:\OSGEO4~1\apps\grass\grass78\etc\grass78.py", line 2092, in main
             
              create_initial_gisrc(gisrc)
             
              File "C:\OSGEO4~1\apps\grass\grass78\etc\grass78.py", line 728, in create_initial_gisrc
             
              writefile(filename, s)
             
              File "C:\OSGEO4~1\apps\grass\grass78\etc\grass78.py", line 225, in writefile
             
              f.write(s)
             
              File "C:\OSGEO4~1\apps\Python37\lib\encodings\cp1252.py", line 19, in encode
             
              return codecs.charmap_encode(input,self.errors,encoding_table)[0]
             
             UnicodeEncodeError: 'charmap' codec can't encode characters in position 34-40: character maps to 
             
             Press any key to continue . . . 

What else do I need to do in order to fix the problem?

Thanks in advance.

**Comment by gioman** [comment] 2020-01-23 11:43
@Labros89 
seems really duplicate of https://github.com/qgis/QGIS/issues/29845 ...

anyway

>     * C:/Advance GIS/Workspace/flow_accum.tif

could you please check if your inputs (and output) point to files that do *not* have spaces of special chars in their path?

**Comment by Labros89** [comment] 2020-01-23 11:54
> @Labros89
> seems really duplicate of #29845 ...
> 
> anyway
> 
> > ```
> > * C:/Advance GIS/Workspace/flow_accum.tif
> > ```
> 
> could you please check if your inputs (and output) point to files that do _not_ have spaces of special chars in their path?

I check it, I tried to store files without spaces or special chars as well as I change "Advance GIS" to "AdvanceGIS" but again the same I having the same issue.

**Comment by gioman** [comment] 2020-01-23 11:55
> I check it, I tried to store files without spaces or special chars as well as I change "Advance GIS" to "AdvanceGIS" but again the same I having the same issue.

ok sorry it didn't helped. I'm closing this anyway as is duplicate of https://github.com/qgis/QGIS/issues/29845 add your comment there, thanks.

**Closed by gioman** 2020-01-23 11:55 UTC
Labels: Bug, Feedback, Processing
