### ISSUE TITLE
Can't print (with PDFCreator) Print Composer layouts created on 2.18

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#34505] opened 2020-02-17 12:41 UTC
I'm used to print my maps with PDFCreator Tool.
In old Qgis 2.18 is working like a charme
Now I'm trying with Qgis 3.8.3
When I import an old print composer model, the Layout shows to me correctly, but when I print it using the PDFCreator Tool it puts out a tabloid format in low resolution.
I tryied changing options and dimensions but the result is always a tabloid format output.

The PDFCretor tool works if I make a new layout from scratch... please... don't tell me I must redo all the 32 old print composers....

**Comment by gioman** [comment] 2020-02-17 12:51
@Forna73 3.8 is EOLed, you must test on 3.10.2 (as it is becoming LTR) anyway.

**Comment by Forna73** [comment] 2020-02-17 13:10
ok... I'll wait for it.... in case I'll report about this problemin this post...

**Comment by gioman** [comment] 2020-02-17 13:51
>  I'll wait for it..

3.10.2 is already out

**Comment by Forna73** [comment] 2020-02-17 19:02
few days for 3.12....

**Comment by Forna73** [comment] 2020-04-21 21:02
tried on 3.10.5... but nothing changed... the problem still persists...

**Comment by nyalldawson** [comment] 2020-04-21 21:27
What exactly is the "pdf creator" tool? is that a plugin?

**Comment by roya0045** [comment] 2020-04-21 21:36
@nyalldawson I'm guessing he's talking about export PDF since there is no plugin with that name and he mentioned the composer.

**Comment by roya0045** [comment] 2020-04-21 21:41
@Forna73 could you share the layout templates or a project?

**Comment by Forna73** [comment] 2020-04-22 07:17
The Pdfcreator is a free software that create a virtual printer to create a
pdf from any program....
I tried to export in pdf but the program always crash or get freezed....

Il mar 21 apr 2020, 23:36 Alex <notifications@github.com> ha scritto:

**Comment by Forna73** [comment] 2020-04-22 07:21
I mean the export in pdf on qgis...

Il mer 22 apr 2020, 09:17 Forna <s.forna73@gmail.com> ha scritto:

**Comment by gioman** [comment] 2020-04-22 09:05
> Pdfcreator is a free software that create a virtual printer

@Forna73 link?

Also attach one of your problematic projects/layouts (with the necessary sample data).

**Comment by Forna73** [comment] 2020-04-22 14:04
this is the link....  https://www.pdfforge.org/pdfcreator

Sorry man, I can't attach files... :-(

I really think the problem is something related to compatibility between
Qgis 2.18 and 3.x... because if I recreate the same layout from scratch,
everything works well.... almost since now... I don't use the export pdf
off Qgis, because I find pdfcreator more suitable for my task
I guess, since we are now in Covid time... I've time to redo everything
from scratch...

Il giorno mer 22 apr 2020 alle ore 11:05 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-04-22 14:07
> Sorry man, I can't attach files... :-( 

@Forna73 well this mean that we don't have a way ti replicate this issue...

Can't you create a sample one, using 2.18, that shows the same behavior?

**Comment by Forna73** [comment] 2020-04-22 14:11
the 2.18 last version works well without problems... that's why I'm still
using it as main version and I'm keeping the 3.10 as a version over which I
execute tests...

Il giorno mer 22 apr 2020 alle ore 16:07 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-04-22 14:13
> the 2.18 last version works well without problems... 

what I asked is different: provide us a sample 2.18 project that shows the same symptoms when opened on 3.10 (when trying to export as PDF with that software).

**Comment by Forna73** [comment] 2020-04-22 14:16
Sorry, I misunderstood... no other projects here... so... again I can't...

Il giorno mer 22 apr 2020 alle ore 16:13 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-04-22 14:17
>  no other projects here..

can't you **create** one you can share?

**Comment by Forna73** [comment] 2020-04-22 14:45
So... Just know I'm experiencing it in 3.10.5 simply by creating a new
layout without putting it nothing, but simply by creating the page:

1. I create a new layout
2. right click on it to get page setup
3. custom settings
4. 1485 x 800 Horizontal
5. printed with the PDF Creator without any content

I'm getting always a vertical output even I set it horizontal...
The problem now is in the layout created from scratch also....


Il giorno mer 22 apr 2020 alle ore 16:18 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by Forna73** [comment] 2020-04-22 14:47
What's the max dpi in layout properties? I see 300... is this
independent from the file format I wish to export to?

Il giorno mer 22 apr 2020 alle ore 16:44 Forna <s.forna73@gmail.com> ha
scritto:

**Comment by nirvn** [comment] 2020-04-22 14:53
I think the real problem here is using PDFCreator to begin with.

Out of curiosity, what advantage(s) do you see in going down the path of using a 3rd party PDF export software and *not* QGIS' own, well tested export to PDF option?

If it's merely a habit thing, you are probably better taking time to train yourself into using QGIS' export to PDF instead of redoing layouts from scratch. If there are features that you don't find in the native PDF export, what are those?

**Comment by Forna73** [comment] 2020-04-22 15:16
I'm seeing:
1. if I use PDFCreator for a map 1485x800mm at 720dpi it makes a 27Mb file
2.  with the pdf export in QGis, if I set up more than 300dpi the process
freeze and leaving 300dpi for a 1485x800mm I've a 227Mb file
...quite 10 times bigger....

Il giorno mer 22 apr 2020 alle ore 16:54 Mathieu Pellerin <
notifications@github.com> ha scritto:

**Comment by Forna73** [comment] 2020-04-22 15:18
...and a worst visual quality...

Il giorno mer 22 apr 2020 alle ore 17:15 Forna <s.forna73@gmail.com> ha
scritto:

**Comment by nirvn** [comment] 2020-04-22 15:24
Are you rasterizing the layout when exporting to PDF using QGIS? The size difference is insane, AFAIK, QGIS exports PDF in a lossy format, you shouldn't see that large a difference. 

It's likely you are exporting a huge amount of vector data you're clearly not interested in. 

Try forcing a rasterization, it might be what you are looking for.

That said, I'd be keen to see a PDFCreator vs QGIS set of PDF files so compare first-hand. Could you share a pair of the same layout?

**Comment by Forna73** [comment] 2020-04-22 15:39
Can't do now... the pdf created with QGis now results corrupted and doesn't
open...
I rebooted the PC and I tried to export it again, but now always crash,
even with standard 300dpi
...OMG...
Sorry Guys.... but at the moment, this is a total NO GO for me with 3.x...

Il giorno mer 22 apr 2020 alle ore 17:30 Forna <s.forna73@gmail.com> ha
scritto:

**Comment by gioman** [comment] 2020-04-22 16:04
> 1. I create a new layout

@Forna73 where, in QGIS 2.18 or 3.10?

**Comment by gioman** [comment] 2020-04-22 16:06
> If I check the rasterize option QGis crash...

@Forna73 it seems to me that you also have local issues (issues specific to your machine/installation).

**Comment by gioman** [comment] 2020-04-22 16:08
> Sorry Guys.... but at the moment, this is a total NO GO for me with 3.x...

@Forna73 sorry, but you are not giving us the necessary information (a sample project) that would allow us to 1) confirm the issue (or not) 2) troubleshoot the issue.

What we should do?

**Comment by roya0045** [comment] 2020-04-22 16:41
The corrupted pdf issue is often caused by an incomplete creation of the PDF, either the driver stopped or you opened the file too soon and blocked the process.

Judging by this it seem like your pdf drivers have issues.

**Comment by Forna73** [comment] 2020-04-22 17:46
Don't know guys.... It sounds me strange that an old version of Qgis works
like a charme and this new one is giving me all these issues.
I keep my PC updated and monitored and at this moment Qgis 3 is the only
one giving me troubles.
I wish to be clear that it's only the layout part that's making me crazy. I
still find the old print composer more intuitive than the new Layout
manager, above all in the general setting.
It's very difficult to me create a sample because the project is made of
tens of .shp, .csv, Dem (several Gb), .wms also a couple of .vrt....

I'll continue updating the LTR version but my main is and will be 2.18

Il mer 22 apr 2020, 18:09 Giovanni Manghi <notifications@github.com> ha
scritto:

**Comment by Forna73** [comment] 2020-04-22 17:51
When I start an export I don't 'do nothing... simply waiting till Qgis
crash or after about 25minutes ( that's the time the old 2.18 get to create
the pdf via pdfcreator) I obtain this strange vertical format....

Il mer 22 apr 2020, 19:46 Forna <s.forna73@gmail.com> ha scritto:

**Comment by roya0045** [comment] 2020-04-22 18:02
In the Layout menu you can do save as template for problematic layouts,( at least in qgis 3.x,) export a few of them, zip them and post them here so we can validate.

**Comment by gioman** [comment] 2020-04-22 20:15
@Forna73 you have dodged some questions, so I had to do some work for you.

On a clean Windows testing machine:

- created a project in QGIS 2.18, loaded it with a "ton" of data
- installed "pdf creator"
- created a layout using your indications: https://github.com/qgis/QGIS/issues/34505#issuecomment-617824025

1) printing "as raster" bug is confirmed: https://github.com/qgis/QGIS/issues/35929

2) printing with "pdf creator" result in smaller PDF (with the same QGIS settings) but it takes much longer (minutes) than the integrated QGIS PDF export tool (which in my case exported almost instantly)

3) when exporting with "pdf creator" it eats up a lot of memory... QGIS "freezes" but if you leave it alone it finishes. Possibly if the project has really a **lot** of data it can take really a long time to finish.

4) Despite all the above I can't see any issues with the results obtained with "pdf creator".

**Comment by gioman** [comment] 2020-04-22 20:17
>  I still find the old print composer more intuitive than the new Layout manager, above all in the general setting.

> but my main is and will be 2.18

if it works best for you, continue to use it. Meanwhile I don't think there is an issue here other than https://github.com/qgis/QGIS/issues/35929

**Comment by Forna73** [comment] 2020-04-22 22:23
@gioman  Thank you man, sorry but I'm quite a noob in this and I'm not so GIS profesional :-(
I can confirm you that PDFCreator take much longer time, but sincerely it doesn't mind because I need a good quality. I've 32Gb RAM with an i7 4790.... it takes me 25' but I've a 1485x800mm 720dpi pdf in 27Mb and while the pdf process is running I can work with other software without problems....
I've read the post you created and I saw Nyall answer about something has been done in QT 5.13... so in which Qgis version do you think it will be implemented?

At this moment with 3.10.5 with its internal export to pdf I succeeded in:
1. getting 1485x800mm 300dpi "no rasterized" 78Mb but real poor quality
2. getting 1485x800mm 600dpi "no rasterized" 227Mb but quality appear same as the 300 dpi, really nothing better!?

If I set "rasterized" it crash
Any higher dpi setting crash with or without "rasterized" option

PDFCreator is unusable giving an output format I can't understand. It's always vertical ignoring any setting I put in layout properties in Qgis or in the PDF printer setting...bha?!

**Comment by nirvn** [comment] 2020-04-23 02:06
@Forna73 , can you provide us a PDFCreator PDF export and a QGIS PDF export of your layout with the settings that doesn't crash (1485x800mm @ 300dpi)?

**Comment by Forna73** [comment] 2020-04-23 08:30
Ok! here it is a comparison.

![comparison](https://user-images.githubusercontent.com/12034365/80077019-39fbca00-854d-11ea-9431-7adc5fcb5512.png)

**Comment by gioman** [comment] 2020-04-23 08:34
@Forna73 can we try to clear a bit this ticket? is the issue about printing quality? or the issue is another? If there are multiple issues (other than the "print as raster" one that has been already reported) we ask to keep 1 issue per ticket.

**Comment by Forna73** [comment] 2020-04-23 08:46
You can do whatever you need for clarity...
You are right... things calls other things... so at the moment the issues I'm experienceing are:
1. unable to use third party PDFCreator tool to print layouts
2. unable to get pdf higher than 600 dpi
3. "rasterize option" causes Qgis to crash
4. poor quality in PDF export tool

**Comment by Forna73** [comment] 2020-04-23 08:50
ah... and now... looking the comparison I can add another issues:
5. Qgis export tool doesn't export all layers.... see the 2 chimneys, the lattice towers, the vertical magenta line ecc...

**Comment by nirvn** [comment] 2020-04-23 08:54
@Forna73 , again, can you please provide PDFs so we can compare outputs?

**Comment by Forna73** [comment] 2020-04-23 10:51
I did it....

Il gio 23 apr 2020, 10:55 Mathieu Pellerin <notifications@github.com> ha
scritto:

**Comment by nirvn** [comment] 2020-04-23 10:56
Doh, it was right in my face.

@Forna73 , the chimneys gone missing -> are those missing when you look at the canvas on QGIS' main window (that is, QGIS 3.10, having opened the 2.X project file)?

Ideally, it'd be good if you can share the actual PDFs here. Just zip them, you can attach ZIP files to github comments.

**Comment by Forna73** [comment] 2020-04-23 11:12
In the canvas there's everything...

Il giorno gio 23 apr 2020 alle ore 12:56 Mathieu Pellerin <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-04-23 16:10
> unable to use third party PDFCreator tool to print layouts

@Forna73 does this happens **only** with projects/layout that were created on 2.18 and opened in 3.10? What about if you resave this projects on 3.10? And what abut if you re-do the project from scratch in 3.10?



> unable to get pdf higher than 600 dpi

This is only with PDF creator or also with the internal PDF exporter?



> poor quality in PDF export tool

same question as above, this happens only in projects/layouts created in 2.18 or also on ones created from scratch in 3.10?

**Comment by Forna73** [comment] 2020-04-23 21:08
tomorrow I'll do other tests and I'll update you...

**Comment by gioman** [comment] 2020-06-12 14:39
@Forna73 where do we stand with this report?

**Comment by Forna73** [comment] 2020-06-12 15:58
Hi!
Sorry... I'm still stopped cause Covid, so I didn't get much time to this...
Last time I tried to get the pdf I still have all the problem above.
If I use the pdf export feature in QGis I have poor quality, as you can see in my example above.
I recently read about a PDFCreator update with new Ghostscript... I don't know if this matter, but I'm waiting to update the App to retry exporting.

**Comment by Forna73** [comment] 2020-06-12 16:05
I'm thinking.... is it possible is there anything related with this way to have several pages for one layout?
Still now I'm confused about this feature.... probably the App look for page settings in a place where now there is a generic layout setting cause each page in it have different settings.... Bho... I'm not sure to make you understand...

**Comment by gioman** [comment] 2020-06-12 16:06
@Forna73 this ticket has become a little messy. As far as I understand you are reporting two separate issues, each one would need its own ticket. Please see below and confirm:

1) poor quality of PDF exports comparing the native QGIS tool and this 3rd party "PDFCreator Tool"

2) a project (and layouts) created in 2.18 and opened in QGIS 3 fail to print correctly as PDF using  "PDFCreator Tool", but they are ok if the layouts are created in QGIS 3

correct?

**Comment by gioman** [comment] 2020-06-12 16:07
@Forna73 is yes you should really attach here a sample project (with data and layouts) that proves this issue.

**Comment by Forna73** [comment] 2020-06-12 16:10
ok for the 1
No for the 2nd... even if I create a new layout with Qgis 3.10 I've wrong print with PDFCreator...

I really have tens of shape file, mixed with .cvs and postgis layer, with a WMS layer also... can't make a sample.

**Comment by gioman** [comment] 2020-06-12 16:15
> can't make a sample.

@Forna73 so how you want us to troubleshoot this?

**Comment by gioman** [comment] 2020-06-12 16:16
>  No for the 2nd... even if I create a new layout with Qgis 3.10 I've wrong print with PDFCreator...

@Forna73 by the way this is not coherent with what you stated here at the end of the description: https://github.com/qgis/QGIS/issues/34505#issue-566273876

**Comment by roya0045** [comment] 2020-06-12 16:33
So, just don't use this 'PDFCreator' if the outputt is bad. Otherwise is the output from QGIs is bad increase DPI. I have no clue if this should even still be opened at this point..

**Comment by Forna73** [comment] 2020-06-12 16:57
if I increase above 300dpi qgis crash
I MUST use it cause all my job is set up on it...

**Comment by gioman** [comment] 2020-06-12 16:59
> if I increase above 300dpi qgis crash (I'm used to print at 720dpi at least)

one more reason to provide us with a sample project+data+layouts

**Comment by Forna73** [comment] 2020-06-14 20:38
Why don't you install it...? It's freeware.... and Try it?
I can't do a sample...

**Comment by gioman** [comment] 2020-06-17 11:52
> Why don't you install it...? It's freeware.... and Try it?

@Forna73 done, see attached results. Export to PDF as vector with QGIS and PDF creator, from QGIS 3.12.

[Landscape A4_1200_vector.pdf](https://github.com/qgis/QGIS/files/4792261/Landscape.A4_1200_vector.pdf)

[Landscape A4_1200_vector_QGIS.pdf](https://github.com/qgis/QGIS/files/4792263/Landscape.A4_1200_vector_QGIS.pdf)

**Comment by gioman** [comment] 2020-06-25 22:57
@Forna73 seen my last comment and its attachments?

**Comment by Forna73** [comment] 2020-06-26 09:39
I've seen!
I'm now in production period and I've no time making experiments...
From a rapid test I'm quite sure the problem seems to be related to "custom size".
From a blank project I created:
- 1485 lengh x 800 height horizontal (test.pdf)
- 1485 lengh x 400 height horizontal (test2.pdf)
I made a rettangle and triangle with the word "alto" as reference and all should be horizontal. Printed with PDFCreator as you can see the page is printed vertical and the word horizontal. With the export tool in Qgis there's no problem, 
I tried all kinds of combination but the page aligneament is always different from the text...
So... at this time it seems PDFCreator can't understand how to print page and its content in 3.10.5

[test.pdf](https://github.com/qgis/QGIS/files/4836117/test.pdf)
[test2.pdf](https://github.com/qgis/QGIS/files/4836119/test2.pdf)

**Comment by gioman** [comment] 2020-06-26 13:22
>     * So... at this time it seems PDFCreator can't understand how to print page and its content

@Forna73 so it is a pdf creator issue, correct?

**Comment by Forna73** [comment] 2020-06-26 17:29
I haven't any other software to make pdf.... so I think so.  I will
continue with Qgis 2.18 cause 3 still crash to me with more than 300dpi and
quality is poor respect the creator one (as per images above)

Il ven 26 giu 2020, 15:22 Giovanni Manghi <notifications@github.com> ha
scritto:

**Comment by gioman** [comment] 2020-12-21 18:58
> I haven't any other software to make pdf.... so I think so.

closing then.

**Closed by gioman** 2020-12-21 18:58 UTC
Labels: Bug, Feedback, Print Layouts
