### ISSUE TITLE
Crashing on Save and Exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29922] opened 2019-05-20 19:38 UTC
Author Name: **Chris Dainton** (Chris Dainton)
Original Redmine Issue: [22109](https://issues.qgis.org/issues/22109)
Affected QGIS version: 3.6.3
Redmine category:actions

---
## User Feedback

saving on save & exit. 

latest version 3.6.3

## Report Details

*Crash ID*: 5ad41d6be94809f981e2ec9b06a0e20f1d0b0a87

*Stack Trace*
```
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.3-Noosa
QGIS code revision: 0c5774c068
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by PeterPetrik** [comment] 2019-05-30 09:20
Would it be possible to add some testcase and steps how to reproduce the issue?

**Comment by jef-n** [comment] 2019-06-17 18:21
Duplicate of #28104

**Closed by jef-n** 2019-06-17 18:21 UTC
Labels: Bug, Crash/Data Corruption, Feedback
