### ISSUE TITLE
QGIS froze when selecting a font on print layout.

### ISSUE THREAD

**Issue by PeterBrodersen** [qgis/QGIS#38554] opened 2020-09-02 14:13 UTC
## User Feedback

Clicked on the font select drop down for a text block on print layout.

## Report Details

**Crash ID**: [44d6677f8795999c8fa04e7018c5afde80b847b0](https://github.com/qgis/QGIS/search?q=44d6677f8795999c8fa04e7018c5afde80b847b0&type=Issues)

**Stack Trace**
<pre>
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserPeekMessage :
_PeekMessage :
PeekMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QFontDialog::getFont :
QFontDialog::getFont :
</pre>

**QGIS Info**
QGIS Version: 3.14.15-Pi
QGIS code revision: d5114d2cfa
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.20197

**Comment by gioman** [comment] 2020-09-02 14:15
@PeterBrodersen does it happen in a replicable way?

**Comment by PeterBrodersen** [comment] 2020-09-02 14:23
Unfortunately not that I can reproduce.

**Comment by gioman** [comment] 2020-09-02 14:25
> Unfortunately not that I can reproduce.

@PeterBrodersen then it will be hard to find the root cause of the crash.

**Comment by gioman** [comment] 2020-10-04 09:20
Closing as not replicable.

**Closed by gioman** 2020-10-04 09:20 UTC
Labels: Bug, Feedback, Print Layouts
