### ISSUE TITLE
Using a Field Attribute (Variable) in Font Marker, Symbol appears correctly in Map, but not in Legend

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27449] opened 2018-08-14 11:02 UTC
Author Name: **Tobias Wolff** (Tobias Wolff)
Original Redmine Issue: [19622](https://issues.qgis.org/issues/19622)
Affected QGIS version: 3.2.1
Redmine category:map_composer/printing

---
When using a variable for Font Marker Symbol to label points, the variable is not interpreted in print composer's legend.

I guess it's not a quick fix, as the font marker variable is not necessarily linked to a categorized field and symbols might need to be repeated within an already categorized field. But typical use case will be "categorized value == shown field attribute".

Using labels is no option here, as labels won't show up as a symbol in legend by design. 

---

- [layer_properties.jpg](https://issues.qgis.org/attachments/download/13138/layer_properties.jpg) (Tobias Wolff)
- [print_composer_legend.jpg](https://issues.qgis.org/attachments/download/13139/print_composer_legend.jpg) (Tobias Wolff)

**Comment by nyalldawson** [comment] 2019-09-26 05:38
Duplicate of #19761 (same underlying feature request)

**Closed by nyalldawson** 2019-09-26 05:38 UTC
Labels: Bug, Print Layouts
