### ISSUE TITLE
Meta Search fails to add OWS layers

### ISSUE THREAD

**Issue by FroehDo** [qgis/QGIS#37478] opened 2020-06-29 12:32 UTC
The Meta Search plugin in QGIS 3.10.7-ltr does connect to the geocatalog without issues and can search it. However, if I try to add any item, it will crash reporting (e.g.for WMS):

```
AttributeError: 'NoneType' object has no attribute 'addRasterLayer' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\MetaSearch\dialogs\maindialog.py", line 757, in add_to_ows
    ows_provider.addRasterLayer.connect(self.iface.addRasterLayer)
AttributeError: 'NoneType' object has no attribute 'addRasterLayer'


Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.10.7-A Coruña A Coruña, 7b4ca4c8d0 

Python-Pfad:
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python
C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python
C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3\profiles\Freiburg/python/plugins\DataDrivenInputMask
C:/Users/FroehDo/AppData/Roaming/QGIS/QGIS3/profiles/Freiburg
```

or for WFS:
```
AttributeError: 'NoneType' object has no attribute 'addVectorLayer' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins\MetaSearch\dialogs\maindialog.py", line 763, in add_to_ows
    ows_provider.addVectorLayer.connect(addVectorLayer)
AttributeError: 'NoneType' object has no attribute 'addVectorLayer'
```

It seems there is a problem with ows_provider, created in maindialog.py (751f):
```
# open provider window
ows_provider = QgsProviderRegistry.instance().createSelectionWidget(stype[2],
                                                                            self)
```

**Comment by gioman** [comment] 2020-06-29 22:13
@FroehDo duplicate of https://github.com/qgis/QGIS/issues/35560 ?

**Comment by FroehDo** [comment] 2020-06-30 06:21
@gioman seems like it. Sorry!

**Closed** 2020-06-30 06:26 UTC
Labels: Bug, Feedback
