### ISSUE TITLE
Connect tools in graphical modeler by drag and drop rather that select

### ISSUE THREAD

**Issue by vincentvd1** [qgis/QGIS#55005] opened 2023-10-20 13:48 UTC
### Feature description

Currently, to connect tools in the graphical modeler, you have to open the tool, set the input to for example `algorithm output` and select the output of another tool. The problem is that for larger models, this list can become very large and chaotic. Just like software like FME or Arcgis it would be nice if you can drag the output of one tool to the input of another tool.

![Screenshot from 2023-10-20 15-41-40](https://github.com/qgis/QGIS/assets/10993040/11323d65-6b66-4b85-82da-bc97c82935cc)

### Additional context

Here you see a screenshot of FME. Pressing the little yellow or green triangles, you can drag a line to the input of another transformer (tool). This is much more convenient that selecting from a list as QGIS currently supports. This also allows you to quickly restucture models by just re-connecting tools.

![Screenshot from 2023-10-20 15-46-03](https://github.com/qgis/QGIS/assets/10993040/8532e835-84f4-453e-97db-a2faea48e358)

**Comment by uclaros** [comment] 2023-10-21 17:17
That would be a lovely feature indeed. It's a duplicate of #21545

**Closed by uclaros** 2023-10-21 17:17 UTC
Labels: Feature Request, Modeller
