### ISSUE TITLE
cannot run GRASS plugin on macOS

### ISSUE THREAD

**Issue by leonmvd** [qgis/QGIS#33206] opened 2019-12-03 13:04 UTC
**Describe the bug**

I can not run GRASS tools on my Mac from QGIS processing. I get the following error: 

> WARNING: Unsupported shell <fish>: /Users/leon/.grass7/bashrc

Grassgis is working fine from my terminal using the CLI

I've tried the following things:
1. ReInstalling new qgis version
2. Uninstalling fish
3. Removing grassgis rc files

**How to Reproduce**

Start any grass tools from toolbox

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | qtiles3; OSMtools; DataPlotly; layerGroupFilter; quick_map_services; db-style-manager; cartolinegen; pdokservicesplugin; LAStools; RuimtelijkePlannen; attributePainter; NearShoreBathymetry; qgis2web; networks; czml_generator; Qgis2threejs; gribdownloader; OSMDownloader; autoSaver; visualist; timemanager; processing; db_manager; MetaSearch

**Comment by gioman** [comment] 2019-12-03 13:07
@leonmvd duplicate of https://github.com/qgis/QGIS/issues/32511 ?

**Comment by leonmvd** [comment] 2019-12-06 09:01
@gioman  Could be. I've tried the solution mentioned there, but no success.

**Comment by leonmvd** [comment] 2019-12-09 10:21
I came across this Interesting solution. Toggle editing mode on the layer you are processing and the tool will work https://gis.stackexchange.com/questions/63000/how-to-resize-shapefile-features-proportionally-in-qgis

**Comment by gioman** [comment] 2020-01-08 16:20
No issues here with GRASS tools in processing using QGIS 3.10.1 on Catalina.

**Comment by gioman** [comment] 2020-07-06 14:50
Tested on 3.14.0 and 3.10.7 on macOS Catalina:

`GRASS init error: GRASS was not found in '/usr/local/osgeo-grass/grass-base' (GISBASE), provider and plugin will not work.`

**Comment by gioman** [comment] 2020-07-07 12:41
merging with https://github.com/qgis/QGIS/issues/32511

**Closed by gioman** 2020-07-07 12:41 UTC
Labels: Bug, GRASS, MacOS
