### ISSUE TITLE
[QGIS 3.16-5] Issue with PDF export : transparency not taken into account

### ISSUE THREAD

**Issue by DavidBAZIN** [qgis/QGIS#42765] opened 2021-04-12 09:33 UTC
**Describe the bug**

When I'm exporting my map in the Composer to a .pdf file, the transparency in my principal vector layer is not taken into account in my final .pdf file, whereas all is good when I'm exporting it to an image file.

**QGIS and OS versions**

QGIS version | 3.16.5-Hannover
OS version | Windows 10 (10.0)

**Comment by gioman** [comment] 2021-04-12 09:43
@DavidBAZIN duplicate of https://github.com/qgis/QGIS/issues/42698 ?

**Comment by DavidBAZIN** [comment] 2021-04-12 09:52
> 
> 
> @DavidBAZIN duplicate of #42698 ?

Yes thank you, I'm closing the topic

**Comment by DavidBAZIN** [comment] 2021-04-12 10:00
> 
> 
> @DavidBAZIN duplicate of #42698 ?

I saw #42698 but in my case I manage the transparency in the layer rendering, not the symbol, but it's still not working

**Closed** 2021-04-12 10:02 UTC
Labels: Bug, Feedback, Print Layouts
