### ISSUE TITLE
Labels in the export are in a different position than in the print layout

### ISSUE THREAD

**Issue by niera87** [qgis/QGIS#41476] opened 2021-02-10 14:49 UTC
QGIS 3.16 32-bit Windows 7

When I export a map to a PNG or other format, the value labels are in a different position than they were shown in the print layout. The exception is labels whose position was set manually.

Map in print layout: 
![układ pierwotny](https://user-images.githubusercontent.com/40465076/107525611-4eca4c80-6bb7-11eb-8c80-5d0effe73030.PNG)

Map in PNG export:
![Układ wydruku 3](https://user-images.githubusercontent.com/40465076/107525159-d794b880-6bb6-11eb-9d2c-c5dd567a6cef.png)

**Comment by rduivenvoorde** [comment] 2021-02-10 16:18
@niera87 out of curiosity: is it a problem that the labels change (a little)? Because the labeling is a dynamic process, so my guess is that for the export it starts a fresh labeling job, maybe in another scale (to be able to for example being able to get a certain dpi).

Is it possible to add a (this?) project to the issue, and some information about how you exactly create the export (dpi params etc etc)?

**Comment by roya0045** [comment] 2021-02-10 19:18
Pretty sure this is a resolution thing. In non-pdf export you set the resolution something similar to 92 and by default pdf export at 300.

**Comment by niera87** [comment] 2021-02-11 08:32
@rduivenvoorde I use a scale of 1: 1,000,000 and 300 DPI. Labels are relocated by about 1-2 cm in the preview. Same thing in pdf.
Is the .qgz file alone enough to check?
[mapa kujawsko-pomorskie.zip](https://github.com/qgis/QGIS/files/5963780/mapa.kujawsko-pomorskie.zip)
Settings for PNG
![png](https://user-images.githubusercontent.com/40465076/107614414-90580780-6c4a-11eb-95d6-75800c4d0194.PNG)
Settings for PDF
![PDF](https://user-images.githubusercontent.com/40465076/107614502-b8e00180-6c4a-11eb-8716-08f0887e571a.PNG)

Another bug I think - sometimes, but not every time in the same project, labels whose position was manually set in the map editing window show up elsewhere in the print layout - where they were before being manually moved in the edit window.

@roya0045 I use 300 dpi in png. Same thing (relocated labels) is in PDF export.

**Comment by rduivenvoorde** [comment] 2021-02-11 08:51
@niera87 but as asked earlier (let me state I'm not a cartographer :-) ), how bad is it that the labeling slightly changes? In essence by changing the dpi you are creating a new map, so the labeling is done again with even another environment. Not sure if QGIS can fix/freeze such randomness/unpredictable processes...

One solution I can think of: you export your labeling-points as a separate (point) layer, create your labels based on those points using settings in which you keep/fix as much of the 'automagic' placements yourself. Or even fix their position using the labeling tools of QGIS, see for example: https://oslandia.com/en/2017/10/17/auxiliary-storage-support-in-qgis-3/

**Comment by niera87** [comment] 2021-02-11 09:06
I am also not a cartographer :-) As I said - labels are relocated by about 1-2 cm in the preview. Sometimes it doesn't really matter, but sometimes it causes the label to shift out of the polygon or the labels overlap, which is a problem.
Is it possible to export the position of labels that have been automatically placed on the map? Do you know any tutorial on how to do it?

**Comment by rduivenvoorde** [comment] 2021-02-11 09:14
That is that oslandia link, and maybe: https://www.igismap.com/pin-unpin-labels-move-labels-and-diagrams-resize-labels-of-layer-using-qgis-3-2-1/ ?

**Comment by niera87** [comment] 2021-02-11 09:34
OK thank you. It is a pity that there is no other way to freeze these labels permanently so that they do not change anymore, either after going to the print layout or during export. This functionality would be useful, it would shorten the work on maps.

**Comment by gioman** [comment] 2021-02-11 16:58
>  Is the .qgz file alone enough to check?

@niera87 I can't replicate the issue with my own project, can you share yours (with the necessary data)? thanks.

**Comment by niera87** [comment] 2021-02-12 11:45
@gioman Ok, files are here (on google drive because it is about 30MB):
https://drive.google.com/file/d/1MJGuO6MhWyiqvwmAaxV46zkDlx-BRcZM/view?usp=sharing

**Comment by niera87** [comment] 2021-02-12 13:30
@rduivenvoorde Unfortunately the Auxiliary Storage functionality does not help to "freeze" the label positions. After opening the print layout, they are shifted anyway, even labels that were shifted manually are shown in the old position - before shifting. Also, when I save the file and reopen it, the manual positioning of the labels is not saved - they appear in their old positions - before being moved.

**Comment by TurboGraphxBeige** [comment] 2021-02-12 14:20
Are you using the same scale in both places (the map in the layout and the map canvas in main window)?

**Comment by niera87** [comment] 2021-02-12 14:29
> Are you using the same scale in both places (the map in the layout and the map canvas in main window)?

Yes

**Comment by gioman** [comment] 2021-02-12 14:48
> @gioman Ok, files are here (on google drive because it is about 30MB):
> https://drive.google.com/file/d/1MJGuO6MhWyiqvwmAaxV46zkDlx-BRcZM/view?usp=sharing

@niera87 in the zip you have only added the .shp file of the shapefile, you must add also the  .shx the .dbf and the .prj

**Comment by niera87** [comment] 2021-02-12 15:07
> > @gioman Ok, files are here (on google drive because it is about 30MB):
> > https://drive.google.com/file/d/1MJGuO6MhWyiqvwmAaxV46zkDlx-BRcZM/view?usp=sharing
> 
> @niera87 in the zip you have only added the .shp file of the shapefile, you must add also the .shx the .dbf and the .prj

Sorry - here is missing files:
https://drive.google.com/file/d/1mnVzzRGGNZ8vZAGr3E90C5eKoUY8p803/view?usp=sharing

**Comment by gioman** [comment] 2021-02-12 15:14
> Sorry - here is missing files:

@niera87 the project does not open cleanly

![Screenshot_20210212_151355](https://user-images.githubusercontent.com/1951107/107785828-f9bc4100-6d44-11eb-8121-4086c0fdfe72.png)

Please attach a zip with a fully contained project+data that we can open cleanly.

**Comment by pjshelton** [comment] 2021-02-14 23:00
I suspect that this recalculating of the labels on export is by design.  #28174 describes a use case where it makes making maps difficult. That issue and #28386 are feature requests for the ability to lock the calculated label position for a given layer.

**Comment by pjshelton** [comment] 2021-02-15 02:14
for me, an oddity is that the save as image (png, jpg) finds space for the road name, 
![image](https://user-images.githubusercontent.com/39154868/107897493-e5668700-6f84-11eb-831d-73c36a9386b9.png)
but save as image (tiff) and save as PDF give priority to the road volumes.
![image](https://user-images.githubusercontent.com/39154868/107897954-35921900-6f86-11eb-977c-fd56674f707b.png)
And none of them can find the space for the label 5,795 that the composer does.
![image](https://user-images.githubusercontent.com/39154868/107898109-a1748180-6f86-11eb-819c-dc574b7b1982.png)
vs 
![image](https://user-images.githubusercontent.com/39154868/107898126-afc29d80-6f86-11eb-83d6-236c2fb035bb.png)
Having said that, the composer can only find space for that 5,795 if the scale for the composer view is 100%. If it is anything else, the composer does not display it either.

**Comment by niera87** [comment] 2021-02-15 13:28
> > Sorry - here is missing files:
> 
> @niera87 the project does not open cleanly
> 
> ![Screenshot_20210212_151355](https://user-images.githubusercontent.com/1951107/107785828-f9bc4100-6d44-11eb-8121-4086c0fdfe72.png)
> 
> Please attach a zip with a fully contained project+data that we can open cleanly.

Sorry for delay. I have this files on my office PC. In this ZIP I attatched all files. I just don't know how to transfer virtual layers because they don't save as a separate file.
https://drive.google.com/file/d/1WXktq2-vEw8xHEV-gam7HZYwYpRrc0Up/view?usp=sharing

**Comment by niera87** [comment] 2021-02-15 13:39
> for me, an oddity is that the save as image (png, jpg) finds space for the road name,
> but save as image (tiff) and save as PDF give priority to the road volumes.
> And none of them can find the space for the label 5,795 that the composer does.
> vs
> Having said that, the composer can only find space for that 5,795 if the scale for the composer view is 100%. If it is anything else, the composer does not display it either.

These are the cases of label shift I mean. Even the Auxiliary Storage - manually positioning the labels - doesn't help. After closing the file, the labels return to their original positions. The permanent locking of the label position would completely solve the problem. Should I open a "pull request"?

**Comment by roya0045** [comment] 2021-02-15 13:48
@niera87 if you know how to improve the code you are welcome to submit a PR for review.

**Comment by gioman** [comment] 2021-02-15 14:14
> Sorry for delay. I have this files on my office PC. In this ZIP I attatched all files. I just don't know how to transfer virtual layers because they don't save as a separate file.
> https://drive.google.com/file/d/1WXktq2-vEw8xHEV-gam7HZYwYpRrc0Up/view?usp=sharing

@niera87 it still does not open cleanly. The virtual layers are... virtual, so you don't need to look to save them as files, they are defined and saved at a project level... but the project must be able to access the datasources the virtual layers are based on.

![Screenshot_20210215_141241](https://user-images.githubusercontent.com/1951107/107957147-18fedc80-6f98-11eb-9c5f-2af9a29185e5.png)

**Comment by niera87** [comment] 2021-02-22 07:29
> @niera87 if you know how to improve the code you are welcome to submit a PR for review.

Unfortunately I can't write code. I thought that the idea of a change or a new functionality was enough to open a PR. Nevertheless, the function - the permanent locking of the label position - is very much needed in my opinion.

**Comment by niera87** [comment] 2021-02-22 07:34
> > Sorry for delay. I have this files on my office PC. In this ZIP I attatched all files. I just don't know how to transfer virtual layers because they don't save as a separate file.
> > https://drive.google.com/file/d/1WXktq2-vEw8xHEV-gam7HZYwYpRrc0Up/view?usp=sharing
> 
> @niera87 it still does not open cleanly. The virtual layers are... virtual, so you don't need to look to save them as files, they are defined and saved at a project level... but the project must be able to access the datasources the virtual layers are based on.
> 
> ![Screenshot_20210215_141241](https://user-images.githubusercontent.com/1951107/107957147-18fedc80-6f98-11eb-9c5f-2af9a29185e5.png)

I already sent the file "powiaty.shp", so as I understand it is missing the file "unemployment2.csv". I am sending it in the attachment. I'm sorry for the trouble. I am a very beginner in qgis.
[bezrobocie2.zip](https://github.com/qgis/QGIS/files/6020184/bezrobocie2.zip)

**Comment by SrNetoChan** [comment] 2021-02-22 07:39
You can use the QConsolidade plugin to store the full project and data ready to share with others.

**Comment by niera87** [comment] 2021-02-22 08:04
> You can use the QConsolidade plugin to store the full project and data ready to share with others.

Thanks, very usefull.

@gioman Here is full project export by QConsolidade plugin.
https://drive.google.com/file/d/1ISzyBkFrl0vo8Ysz7Etjn14UL_2niL_0/view?usp=sharing
To repeat the problem, it is worth moving some labels manually and observing the position of these labels in the print layout and in the export.

**Comment by gioman** [comment] 2021-02-22 11:00
> Here is full project export by QConsolidade plugin.

@niera87 it still does not open cleanly on other systems

![Screenshot_20210222_105947](https://user-images.githubusercontent.com/1951107/108699468-2e768800-74fd-11eb-8aa0-63715e48b093.png)

**Comment by niera87** [comment] 2021-02-22 12:30
I don't know what could be the source of the problem. I checked, the last set of files I can easily open on another computer with a different operating system. So all the files are there. Maybe it is a matter of language - sign coding and the use of Polish diacritical signs "ś ź ż ć ś ą ę"?

**Comment by gioman** [comment] 2021-02-22 12:35
> I don't know what could be the source of the problem.

@niera87 try create a simple project that demonstrates the issue and have the project file saved into a folder with all the necessary data in it, then zip and attach.

**Comment by pjshelton** [comment] 2021-02-22 22:54
[test.zip](https://github.com/qgis/QGIS/files/6025702/test.zip)
here is my test case.  The feature IDs of interest is 9539 and 9555

I tried to make it smaller and in my initial tests was unable to make a smaller project fail the same way.

**Comment by pjshelton** [comment] 2021-03-13 21:11
This is the same issue as #33560

**Comment by gioman** [comment] 2021-03-13 21:37
Closing as duplicate.

**Closed by gioman** 2021-03-13 21:37 UTC
Labels: Bug, Print Layouts
