### ISSUE TITLE
Default CRS for new projects not working as expected

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27224] opened 2018-07-11 20:51 UTC
Author Name: **Matthew Baker** (@dpsspatial)
Original Redmine Issue: [19396](https://issues.qgis.org/issues/19396)
Affected QGIS version: 3.2
Redmine category:projection_support

---
In version 2.18, setting the 'Default CRS for new projects' to an 'on the fly' option enabled maps to be set to that CRS, rather than the CRS of the data added to the map.

In version 3.2 (potentially earlier versions of 3.x), when the 'Default CRS for new projects' layer is set and a table added in another CRS (in our case from PostGIS), the map CRS changes to that of the layer, overriding the 'Default CRS for new projects' option.

**Comment by nyalldawson** [comment] 2019-05-27 00:24
Duplicate of #27516

**Closed by nyalldawson** 2019-05-27 00:24 UTC
Labels: Bug, Projections/Transformations
