### ISSUE TITLE
Project Transformation Not Available

### ISSUE THREAD

**Issue by jcm36** [qgis/QGIS#44061] opened 2021-07-06 03:08 UTC
**Describe the bug**
Project Transformation Not Available Error when opening a previous project created under 3.18

**How to Reproduce**
Open an existing project created in a previous version of QGIS that uses the EPSG:27200 - NZGD49 and EPSG:2193 NZGD2000 transformation.  It appears the transformation grid is no longer included in QGIS 3.20 RC 

An error message appears with a link to download the .tif transformation grid, and a button to copy it to relevant folder.  However, even once doing this and restarting QGIS the same error keeps occruing

![2021-07-06 15_02_30-320 Ngati Maru Highway — QGIS](https://user-images.githubusercontent.com/9682969/124536340-ee8cbd80-de6b-11eb-9b79-c421bb30efc0.png)

**QGIS and OS versions**
QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

**Comment by gioman** [comment] 2021-07-06 09:37
Maybe @rouault can tell us of this is expected or not.

**Comment by rouault** [comment] 2021-07-06 10:11
> can tell us of this is expected or not.

I suspect this might be a project from an older version of QGIS that used PROJ < 7 since it refers to the NTv2 grid, and not the corresponding GeoTIFF one. Probably that updating the project to use the newer transformation would fix this. Or installing manually the older NTv2 grid

**Comment by jcm36** [comment] 2021-07-06 10:47
How would I go about upgrading the project to the newest transformation? I'll give that a test and see if it fixes the error. Thanks.

**Comment by jcm36** [comment] 2021-07-21 02:20
Bumping to keep open, as not yet resolved

**Comment by gioman** [comment] 2021-07-21 10:12
> Bumping to keep open, as not yet resolved

@jcm36 have you updated the project?

**Comment by jcm36** [comment] 2021-07-21 10:16
> > Bumping to keep open, as not yet resolved
> 
> 
> 
> @jcm36 have you updated the project?

What do you mean by update the project? Doing a save as? 

I suspect that will cause backwards compatibility issues?

**Comment by gioman** [comment] 2021-07-21 10:20
Try recreate your project from scratch on 3.20.

**Comment by jcm36** [comment] 2021-07-21 10:23
> Try recreate your project from scratch on 3.20.

Ok, I'll give that a go when I get a moment.   

That doesn't really seem like a fix though? I've got quite a large number of projects saved using this projection

**Comment by gioman** [comment] 2021-07-21 10:25
It is unclear to me of there is really anything to fix.

**Comment by jcm36** [comment] 2021-07-21 10:31
> It is unclear to me of there is really anything to fix.

Can you please elaborate on which part of my original post is unclear? 

In QGIS 3.20 I receive an error saying the transformation is not available for any project I open which uses the NZTM CRS

When following the instructions and installing the specified grid, the grid does not install and it brings up the error message again for every project.

**Comment by FiggieNewton** [comment] 2021-07-29 19:13
I am having the same issue as jcm36.  And when I try to install conus from file, I get the failure error concerning folder permissions.  Am I crazy when I see mixed whacks in the statement - all forward but two show up as backwhacks...

![InstallGridFile](https://user-images.githubusercontent.com/88161524/127550243-dc44b543-674c-4d15-ae58-a83539d55daf.PNG)

I tried the workaround of creating a new project and that seemed to work.  The project was created in Coruna, but I replaced my computer and installed Hannover.  PROJ is 8.0.1.  The problem with recreating my projects is that the layouts have to be exported as a template and then pulled into the recreated project.  That works, but doing it that way makes me feel like I might lose something????

But still the initial problem with the conus install - are the back slashes real?  Or is that just the way qgis has been coded to respond?

**Comment by FiggieNewton** [comment] 2021-08-16 18:02
please keep open until question by jcm36 and myself are responded to.
1) how do you install the specified grid?
2) the install response shows a file locator that has forward and backward slashes in the address - is that the source of the problem?

**Comment by tkershaw** [comment] 2021-09-16 21:00
I am having this same problem with my projects when attempting to use a transformation from UTM to state plane

![Screenshot 2021-09-16 135233](https://user-images.githubusercontent.com/1372859/133684203-2b379b70-2c1d-42b4-a251-18781d58b5db.jpg)

Anyone that can help with FiggieNewton's questions above would be much appreciated

This occurs when I open a project in 3.20 that was created in QGIS 2.18 (no error message in 2.18)
________________________________________________________________________________________________________
QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

**Comment by arcivanov** [comment] 2021-10-04 20:09
Same issue here. The problem "resolves" itself if the tiff file in question is deleted from the target destination and then installed every time. I'm not entirely sure why the tiff file cannot overwritten either (permissions are not an issue).

Fedora 34 Linux. QGIS 3.20.3.

**Comment by agiudiceandrea** [comment] 2021-10-04 22:33
@jcm36 have you managed to fix the issue?
Anyway, it seems to me your issue is caused by the fact that the transformation method for your project needs a file named `nzgd2kgrid0005.tif` in the `proj` directory in your profile path, but the link makes you download a file named `nz_linz_nzgd2kgrid0005.tif` and then the file is copied with the same name `nz_linz_nzgd2kgrid0005.tif` in the `proj` dir.

I think you could workaround the issue just renaming the file `nz_linz_nzgd2kgrid0005.tif` to `nzgd2kgrid0005.tif` just after downloading it and then let the dialog copy it in the `proj` directory, or you could directly rename the file `nz_linz_nzgd2kgrid0005.tif` to `nzgd2kgrid0005.tif` in he `proj` directory.

**Comment by jcm36** [comment] 2021-10-04 22:36
I've reverted back to 3.18 as I was having a number of other issues with 3.20, which haven't been fixed just yet

**Comment by FiggieNewton** [comment] 2021-10-04 23:23
I was copying the requested TIF with the correct name even though that TIF already existed in the proj folder.  I even tried renaming and even deleting the original TIF, but I still got the same results.I go back to my thought that the "error" message showed the file name location  not with a forward slash but a back slash.  See my original screenshot.  It made me think there was a coding error in the application.Sent via the Samsung Galaxy A11, an AT&T 4G LTE smartphone
-------- Original message --------From: Andrea Giudiceandrea ***@***.***> Date: 10/4/21  5:33 PM  (GMT-06:00) To: qgis/QGIS ***@***.***> Cc: FiggieNewton ***@***.***>, Comment ***@***.***> Subject: Re: [qgis/QGIS] Project Transformation Not Available (#44061) 
@jcm36 have you managed to fix the issue?
Anyway, it seems to me your issue is caused by the fact that the transformation method for your project needs a file named nzgd2kgrid0005.tif in the proj directory in your profile path, but the link makes you download a file named nz_linz_nzgd2kgrid0005.tif and then the file is copied with the same name nz_linz_nzgd2kgrid0005.tif in the proj dir.
I think you could workaround the issue just renaming the file nz_linz_nzgd2kgrid0005.tif to nzgd2kgrid0005.tif just after downloading it and then let the dialog copy it in the proj directory, or you could directly rename the file nz_linz_nzgd2kgrid0005.tif to nzgd2kgrid0005.tif in he proj directory.

**Comment by agiudiceandrea** [comment] 2021-10-05 07:03
@FiggieNewton there was an oversight... the grid file name is `nzgd2kgrid0005.gsb`

**Comment by agiudiceandrea** [comment] 2021-10-07 21:37
> This is the Install Grid File message I get once I attempt to load the conus file – Could not copy conus to C:/Users/stoll/AppData/Roaming/QGIS/QGIS3\profiles\default/proj/us_noaa_conus.tif. Please check folder permissions and retry. notice the / and \ in the path? Also, my folder permissions are fine. I am in the Administrators group. This is the path as found in the file properties, and notice the whack direction – C:\Users\stoll\AppData\Roaming\QGIS\QGIS3\profiles\default\proj

@FiggieNewton Is the file us_noaa_conus.tif already present in the folder `C:\Users\stoll\AppData\Roaming\QGIS\QGIS3\profiles\default\proj`?
If yes, then the error messages is due to the fact that the code used by the dialog cannot overwrite an already existent file.
In this case, delete the file us_noaa_conus.tif in the folder `C:\Users\stoll\AppData\Roaming\QGIS\QGIS3\profiles\default\proj` and try again the Install Grid File procedure: I suppose this time it will succeed.

**Comment by arcivanov** [comment] 2021-10-07 22:39
> But when I close and reopen, it still throws up the red error box.  I see the installed file in the user…proj folder.  But there is a hitch in the git-along somewhere.

Same here on Linux.

**Comment by Grgsj** [comment] 2021-12-14 01:17
I am having the same issues as above with the red error box upon opening my project file or when using the QField plugin where I get the same error and a Python error.  

I tried renaming the .TIF to .gsb as recommended above and it it appeared to be successful. But once I closed and reopened QGIS as it indicated after installing the WO TIF file, I had the same error – “Cannot use project transform between EPSG: 26910 and EPSG: 4326.

There is no problem with permissions.

I thought the issue seemed to be related to version 3.22 so I re-installed 3.16 but am getting the same error there now.

![image](https://user-images.githubusercontent.com/96092842/145914122-159dff00-b047-424f-af47-ae13e8eb72d2.png)

**Comment by agiudiceandrea** [comment] 2021-12-14 05:39
@Grgsj the recommendation was not to just modify the file extension, but to modify the whole file name (both name and extension) to the one expected. In your case, as it is written in screeshot (<<This transformation requires the grid file "WHO">>), the expected filename is "WHO", without any extension.

**Comment by Grgsj** [comment] 2021-12-14 17:21
Thank you for the quick response.  So renaming the file to WO with no extension worked for v3.16 - no red error box on loading.

I tried v3.22 again and now get a yellow error box on loading a project file:

Used ballpark transform from EPSG:26910 to EPSG:4326.

![image](https://user-images.githubusercontent.com/96092842/146047159-56560b19-7756-48f8-905b-bff8269a189b.png)

Any suggestion? Not sure what the preferred operation means here?

**Comment by FiggieNewton** [comment] 2021-12-14 17:33
Check that layers properties and the CRS for possible choices.  Maybe select a different available option.

 

Or, remove the layer, save and close, reopen and load the layer again.  Sometimes that fixes problems for me.

 

Figgie

**Comment by jlayt** [comment] 2022-01-20 12:21
See my comment https://github.com/qgis/QGIS/issues/45470#issuecomment-1017436019 where I track this down to PROJ not telling QGIS that it should use the new .tif file instead of the old .gsb file. We'll probably need a fix in PROJ first before QGIS can know to use the new .tif transform.

**Comment by rouault** [comment] 2022-01-20 17:11
Closing as duplicate of #45470

**Closed by rouault** 2022-01-20 17:11 UTC
Labels: Project, Bug, Projections/Transformations
