### ISSUE TITLE
Processing gdal:pcttorgb returning error code 1

### ISSUE THREAD

**Issue by pedro-mar** [qgis/QGIS#45344] opened 2021-09-30 16:53 UTC
### What is the bug or the crash?

When trying to run gdal:pcttorgb processing it fails and return "Process returned error code 1" (see attachment).
It works correctly on QGIS 3.16.4-Hannover or if pct2rgb.py file in QGIS 3.20.3 is replaced by pct2rgb.py file from QGIS 3.16.4

### Steps to reproduce the issue

1. Launch QGIS
2. Open the processing toolbox panel
3. Open GDAL -> Raster conversion -> PCT to RGB
4. Fill Parameters
5. Run
6. See error in Log

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![pcttorgberror](https://user-images.githubusercontent.com/79644720/135496548-719a5e85-363f-4a3a-b22d-c1655573add9.png)

**Comment by gioman** [comment] 2021-09-30 17:24
The problem seems to be in GDAL, no QGIS.

If the "-of GTiff" parameter is used than it works. In fact it seems that is not accept any value for "-of".

**Comment by agiudiceandrea** [comment] 2021-10-02 13:41
I can confirm the issue is in GDAL 3.3.1 (in every 3.3.x GDAL version), which is installed by OSGeo4W on Windows.

It seems to me the bug is at line 71 of the [pct2rgb.py](https://github.com/OSGeo/gdal/blob/v3.3.1/gdal/swig/python/gdal-utils/osgeo_utils/pct2rgb.py#L71) script provided by GDAL, which normally is located in `C:\Program Files\QGIS 3.20.0\apps\Python39\Lib\site-packages\osgeo_utils\pct2rgb.py`

@pedro-mar to workaround the issue, you need to change the line 71 from:

```python
        if arg == '-ct':
```

to 

```python
        elif arg == '-ct':
```

**Comment by gioman** [comment] 2021-10-02 16:47
I see that your upstream patch has already been merged, closing this?

**Comment by alexbruy** [comment] 2022-01-22 19:13
Fixed upstream

**Closed by alexbruy** 2022-01-22 19:13 UTC
Labels: Processing, Bug, Upstream

**Comment by jack-tuna** [comment] 2023-11-22 23:03
Hi I've had this same issue on macOS Sonoma 14.11 running QGIS 3.34.0-Prizren. (GDAL 3.3.2)

I've added the else-if fix mentioned by @agiudiceandrea to the pct2rgb.py script but now getting the following output error in the log.

`QGIS version: 3.34.0-Prizren
QGIS code revision: b77936ec947
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2023-11-23T09:24:04
Algorithm 'PCT to RGB' starting…
Input parameters:
{ 'BAND' : 1, 'INPUT' : '/Users/jacktuna/DATAROCK/Repos/GCAS-Prospectivity/data/interim/00_Preprocessing/02_Transformed/GCAS_TMI_AS.tif', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RGBA' : False }

GDAL command:
pct2rgb.py /Users/jacktuna/DATAROCK/Repos/GCAS-Prospectivity/data/interim/00_Preprocessing/02_Transformed/GCAS_TMI_AS.tif /private/var/folders/3w/7bbtb2616_s559g15vs75th80000gn/T/processing_rRwFyd/00f8641d923645438fba029e5589f24b/OUTPUT.tif -of GTiff -b 1
GDAL command output:
Traceback (most recent call last):
File "/Applications/QGIS.app/Contents/MacOS/bin/pct2rgb.py", line 4, in <module>
__import__('pkg_resources').run_script('GDAL==3.3.2', 'pct2rgb.py')
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
exec(code, namespace, namespace)
File "/Applications/QGIS.app/Contents/Resources/python/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg/EGG-INFO/scripts/pct2rgb.py", line 11, in <module>
sys.exit(main(sys.argv))
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg/osgeo_utils/pct2rgb.py", line 96, in main
_ds, err = doit(src_filename, pct_filename, dst_filename, band_number, out_bands, driver)
File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg/osgeo_utils/pct2rgb.py", line 133, in doit
ct_size = ct.GetCount()
AttributeError: 'NoneType' object has no attribute 'GetCount'
Process returned error code 1
Execution completed in 0.55 seconds
Results:
{'OUTPUT': '/private/var/folders/3w/7bbtb2616_s559g15vs75th80000gn/T/processing_rRwFyd/00f8641d923645438fba029e5589f24b/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• /private/var/folders/3w/7bbtb2616_s559g15vs75th80000gn/T/processing_rRwFyd/00f8641d923645438fba029e5589f24b/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

It appears to be associated with the colour palette? any ideas? cheers in advance
