### ISSUE TITLE
Any .parquet layer with active filters chrashes QGIS

### ISSUE THREAD

**Issue by PossibleSolutions** [qgis/QGIS#56028] opened 2024-01-26 13:36 UTC
### What is the bug or the crash?

Any .parquet layer with active filters chrashes QGIS. Basic panning, zooming etc. is possible out the box with a parquet file, but as soon as any active filters are applied, QGIS chrashes. Probably enabling certain labels also does the trick. This has been happening with several different layers (tens of) during a timespan of months. Fix geometries>Create a temporary layer or just using the identical layer as a geopackage has solved the problem every time, so it is highly probable that the issue is with the file format. Thanks

### Steps to reproduce the issue

1. Add any .parquet file (more complex layers might result in a quicker chrash)
2. Add a filter (Query builder)
3. Open Attribute Table
4. Pan and zoom around, or do basically anything
5. Wait for a chrash

### Versions

QGIS version
3.28.4-Firenze
QGIS code revision
fd0fb72ab3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment] 2024-01-27 17:21
Given the GDAL version you use (3.6.2) and the fact it is related to filters, I strongly believe this is a duplicate of #53301 which got fixed per https://github.com/OSGeo/gdal/pull/7889 in GDAL 3.7.1

**Closed by rouault** 2024-01-27 17:21 UTC
Labels: Bug
