### ISSUE TITLE
Allow "fallback" non-preferred transforms if the preferred coordinate operation fails

### ISSUE THREAD

**Issue by SteveLowman** [qgis/QGIS#33929] opened 2020-01-20 17:37 UTC
**Describe the bug**

In QGIS 3.8 and 3.10, with the high-precision transformation file 'OSTN15_NTv2_OSGBtoETRS.gsb' installed into the OSGeo4W64\share\proj folder, the transformation is not working correctly, and the behaviour is very different to the older, less precise transformations available for EPSG:27700

**How to Reproduce**

1. Use QGIS 3.10.2, including proj 7.0.0 and gdal 3.1.0dev, and ensure that OSTN15_NTv2_OSGBtoETRS.gsb is pasted into the OSGeo4W64\share\proj folder
2. Download, unzip, and open the .qgz file with data, as attached
[27700_Transformation_issue_Jan_2020.zip](https://github.com/qgis/QGIS/files/4087123/27700_Transformation_issue_Jan_2020.zip)
3. You should see three layers in the Layers Panel; they have the same identical rectangle, covering part of the UK and its vicinity, but only the EPSG:27700 layer is visible on the map canvas, because OSTN15_NTv2_OSGBtoETRS.gsb is preventing the other two layers from rendering.
![Three_layers](https://user-images.githubusercontent.com/8450382/72746711-b4155f00-3baa-11ea-999c-609d42c6403d.png)

![One_feature](https://user-images.githubusercontent.com/8450382/72746724-bb3c6d00-3baa-11ea-8b27-6c111e0e824a.png)

4. In 'Project Properties > CRS > Datum Transformations', edit the transformations for EPSG:3857 and EPSG:4326, in each case choosing the second available transformation (it has 2 metre precision).
![Edit Datum Transformations](https://user-images.githubusercontent.com/8450382/72746752-d14a2d80-3baa-11ea-9487-66ca5b2d5d9f.png)

![Select Datum Transformations](https://user-images.githubusercontent.com/8450382/72746848-11a9ab80-3bab-11ea-9300-1046d1d29531.png)

5. Refresh the map canvas, and you should see that the two transformed layers (test_3857 & test_4326) will appear as diagonal hatched polygons with identical dimensions over the solid colour of the EPSG:27700 polygon.
![Three_features](https://user-images.githubusercontent.com/8450382/72746871-22f2b800-3bab-11ea-9705-44be38620fe6.png)

6. Repeat Step 4, but (for both of the transformations) choose the first available option, which has a precision of 1 metre (this uses the OSTN15_NTv2_OSGBtoETRS.gsb file).
7. Refresh the map canvas again, and you should observe that the two transformed layers lose their visibility, although they are still set to 'visible' in the Layers Panel.
8. Use the Identify Features tool, set to 'Layer Selection' mode, and you should be able to see the attributes for all three layers, even though two of them are failing to render on the canvas; here is an image showing the comparison of derived attributes for the three features, using the two transformations:
![Identify_results_comparison](https://user-images.githubusercontent.com/8450382/72744938-7b738680-3ba6-11ea-9a64-0fdb859e89d9.png)
9. With the Datum Transformations set to the OSTN15_NTv2_OSGBtoETRS.gsb option, try adding an EPSG:3857 WMS layer, and you get it rendering only a narrow strip along the west coast of Scotland, as illustrated by @david-laverty in this image from #33154:
![WMS_layers_issue](https://user-images.githubusercontent.com/8450382/72745406-a0b4c480-3ba7-11ea-97eb-2afc09d0cb84.png)

10. With the less precise transformation, the EPSG:3857 WMS layer will render, although I have had some problem with tiles failing to render at large scales (possibly a different bug).

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
8e4fe02b4a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.0.0
Running against PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
pluginbuilder3; 
plugin_reloader; 
quick_map_services; 
realcentroid; 
timemanager; 
db_manager; 
MetaSearch; 
processing

My installation is not completely clean, but others in comments for related bug reports have reported the same issue with a clean install.

**Additional context**

Other possibly related bug reports include:
#33154 #30643 #33916 and there may be more, too.

**Comment by gioman** [comment] 2020-01-20 17:40
> In QGIS 3.8 and 3.10

@SteveLowman for QGIS 3.8 it does not really matter, is EOLed. The onlly one that matters is QGIS 3.10 and in particular only 3.10.2 and future releases.

**Comment by SteveLowman** [comment] 2020-01-20 17:43
Okay, thanks @gioman. I am happy with your title change. Is there any further feedback required for now?

**Comment by gioman** [comment] 2020-01-20 17:45
> Is there any further feedback required for now?

@SteveLowman this report is super detailed, I don't think is possible to improve it :) There is clearly something going on here, not sure if is QGIS, one of the underlying libraries or the NTV2 grid.

**Comment by nyalldawson** [comment] 2020-01-21 04:47
This issue is very complex -- QGIS isn't completely at fault here.

The vertices of the polygons in the attached file fall outside of the valid bounds for the grid shift file. Proj reports these as:

```
USAGE[
        SCOPE["unknown"],
        AREA["UK - Britain and UKCS 49°46'N to 61°01'N, 7°33'W to 3°33'E"],
        BBOX[49.75,-9.2,61.14,2.88]]]
```

Here we have vertices at:
 -11.3, 59.36 
5.36, 59.83
-11.70, 49.7
5.46, 49.43

So all four coordinates are outside of the bounds of the grid shift file. When the coordinates are reprojected, they rightly get returned as n/a values (couldn't be transformed). This means that the polygon can't be reprojected for display -- it has no vertices to draw.

Using the non-grid shift based transform, we don't get the n/a values for coordinates outside the bounds -- there's no grid being used, so the mathematical transform still works.

So the root cause is that the data falls outside the area of use of the coordinate operation.

I agree that it's not an ideal result, but it's not strictly a regression here -- you'd see exactly the same thing if you used that grid shift file in earlier QGIS versions. It's just that now QGIS is pushing people to use the grid shift files and making it easy to do so that it's become an issue...

As far as a fix goes I think the best approach would be to add a setting "allow fallback to other coordinate operations if the preferred operation fails". We could never make this a default setting, because it would silently cause unknown projection differences -- users could never be sure if QGIS was actually using the selected coordinate operation or just doing some other random operation. For rendering at the scale of the attached project this probably isn't an issue, but for larger scale maps it certainly WOULD be...

**Comment by nyalldawson** [comment] 2020-01-21 04:48
For now, the take away is not to use the grid shift file in these circumstances. That's a workable solution in existing QGIS versions. I'm tagging the other enhancements as a feature request for potential future work.

**Comment by SteveLowman** [comment] 2020-01-21 10:10
@nyalldawson Thanks, complex indeed. I had not noticed that my polygon vertices were outside of the bounds, so thanks for pointing this out. I now digitised a polygon within the bounds, and it renders for all three CRS layers (27700, 3857, and 4326).

I am a little worried that I might have caused a distraction with this attempt to test with vector layers, although it does show us something perhaps useful.

The problem with the WMS layers rendering only a strip along the Scottish west coast is still occurring, even when the WMS image is completely within the bounds, such as this one:
![nls 1892](https://user-images.githubusercontent.com/8450382/72794662-4ada2e00-3c34-11ea-8998-3913d2c3a753.png)

Regarding locally sourced rasters, @gioman contributed this EPSG:3857 tif file, which extends beyond the bounds but still renders okay, unlike the 3857 beyond-the-bounds vector features or WMS layers,
[test.zip](https://github.com/qgis/QGIS/files/4090404/test.zip)

We can manually choose the fallback less precise transformations when the .gsb fails as in this case, but the reduced precision does cause us some practical problems for detailed work at large scales.

I realise this is not likely to be resolved quickly, but I hope there is some chance of a proper fix eventually.

**Comment by SteveLowman** [comment] 2020-01-24 11:00
I am quite surprised and pleased to see that on doing the upgrade to 3.10.2-2 with the default libraries, the reprojection is actually working with OSTN15_NTv2_OSGBtoETRS.gsb. I am a bit worried that it may not work with proj 7, but it is working great with proj 6.3 and gdal 3.0.3.

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows Server 2012 R2 (6.3)

**Comment by JBambers** [comment] 2020-01-29 13:56
Hello, I've been having the same issue (e.g. osm only rendering strip of tiles near scotland) with the standalone windows installer, remains problematic with the present 3.10.2 version (Compiled against PROJ 6.3.0, GDAL 3.0.3).

Is this OSTN15 transformation 'built-in' since 3.10? It shows up in the list of choices (and fails to render properly) regardless of whether the 'OSTN15_NTv2_ETRStoOSGB.gsb' files are present in the \share\proj folder.

In previous versions of qgis this transformation has always worked fine as long as the .gsb file was in the proj folder.

**Comment by nyalldawson** [comment] 2020-02-17 22:42
Should now be fixed in master

**Comment by nyalldawson** [comment] 2020-02-26 01:46
This should be fixed in 3.12 (and will be fixed in 3.10.4). Can you please test and confirm?

**Comment by JBambers** [comment] 2020-02-28 17:57
The transform does now work but it doesn't seem to fail as gracefully as 3.6 if the view is panned outside the extent:

This is all with map projection in 27700 and with a 3857 web basemap (e.g. google)

In 3.6.3 if the view is panned past the stated extent of the transform then it renders and responds though some warnings (<20) about map tiles timing out (eg 'WARNING    Network request https://mt1.google.com/vt/lyrs=m&x=23&y=23&z=6 timed out') occur. If zoomed very far out then the backing fails to render and 'WARNING    Could not reproject view extent: Could not transform bounding box to target CRS' is logged. Everything otherwise continues to operate.

In 3.12, if fallback is selected then beyond the stated extent it notifies about falling back and renders ok, however larger number (~100) of map tile failed warnings crop up a minute or two after. Very far out (at the extent at which 3.6 logged the bounding box error) it seems to still attempt to render with the fallback at after about 10min of status bar activity there are a 100s of map tile timeouts followed by a QGIS becoming unresponsive.

If allow fallback is not selected then even only beyond the stated extent (i.e. west ireland within the canvas) 100s of map tile timeout warnings occur and QGIS becomes unresponsive.

**Comment by nyalldawson** [comment] 2020-02-28 18:35
Ok. I'm inclined to class that as a different error, in the XYZ tile handling.

**Closed by nyalldawson** 2020-02-28 18:35 UTC
Labels: Feature Request, Feedback, Projections/Transformations

**Comment by Robinlovelace** [comment] 2020-02-29 19:05
Follow-up question: does this also relate to (and I imagine fix) https://github.com/qgis/QGIS/issues/33154 ?
