### ISSUE TITLE
QGIS Crashes when trying to view 3D map

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29479] opened 2019-03-24 16:43 UTC
Author Name: **Kerstyn Perrett** (Kerstyn Perrett)
Original Redmine Issue: [21663](https://issues.qgis.org/issues/21663)
Affected QGIS version: 3.6.0
Redmine category:3d

---
## User Feedback

I tried to load a 3D map view

## Report Details

*Crash ID*: 9bf34d4a608073e8e5d14b8e04b6fab14ad83201

*Stack Trace*
```
QgsCoordinateTransform::transformBoundingBox :
QgsMapRendererJob::reprojectToLayerExtent :
QgsMapRendererJob::prepareJobs :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererSequentialJob::start :
QgsTerrainGenerator::typeToString :
QgsTerrainGenerator::typeToString :
QgsFlatTerrainGenerator::createChunkLoader :
QgsCameraController::camera :
QgsCameraController::camera :
Qgs3DMapScene::updateScene :
Qgs3DMapScene::createTerrainDeferred :
Qgs3DMapScene::Qgs3DMapScene :
QgsMeshCalculatorDialog::useFullLayerExtent :
QgsMeshCalculatorDialog::useFullLayerExtent :
QgisApp::new3DMapCanvas :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by wonder-sk** [comment] 2019-05-27 11:27
Duplicate of #29480

**Closed by wonder-sk** 2019-05-27 11:27 UTC
Labels: 3D, Bug, Crash/Data Corruption, High Priority
