### ISSUE TITLE
Add a variable returning the current map theme

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27594] opened 2018-09-04 16:45 UTC
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19769](https://issues.qgis.org/issues/19769)

Redmine category:expressions

---
Use case:
I have a print layout with a map item  and a legend.
Depending on the current map theme, i'd like to hide the legend (eg, if i'm using the particular map theme that shows only aerial photography, i don't need a legend)

---

Related issue(s): #27499 (relates)
Redmine related issue(s): [19674](https://issues.qgis.org/issues/19674)

---

**Comment by nyalldawson** [comment] 2020-04-02 04:51
Duplicate of #29581

**Closed by nyalldawson** 2020-04-02 04:51 UTC
Labels: Expressions, Feature Request
