### ISSUE TITLE
label properties will not saved to project files (buffer and background)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29882] opened 2019-05-14 06:52 UTC
Author Name: **Michael Kuerbs** (Michael Kuerbs)
Original Redmine Issue: [22069](https://issues.qgis.org/issues/22069)
Affected QGIS version: 3.4.7
Redmine category:labelling

---
I used a rule based labelling.

qgis is not keeping puffer and background settings after project saving and reopening.

**Comment by Mi-Kbs-gis** [comment] 2019-05-27 11:05
I note this fact while using rulebased labelling. Just see the screens.
![rulebased labels](https://user-images.githubusercontent.com/25895003/58415740-b9ec8c00-807f-11e9-86db-37afe8f1b4f7.png)
![label settings_background before saving project](https://user-images.githubusercontent.com/25895003/58415747-bd801300-807f-11e9-84c1-0cf929531234.png)
![label_settings _background after saving and reloading project](https://user-images.githubusercontent.com/25895003/58415754-c1ac3080-807f-11e9-9808-043ce286ab6c.png)
![label settings_puffer_before saving project](https://user-images.githubusercontent.com/25895003/58415757-c4a72100-807f-11e9-8398-ebc6a84152ec.png)
![label settings_puffer_after saving and reloading project](https://user-images.githubusercontent.com/25895003/58415762-c83aa800-807f-11e9-9a8e-800ed42fd1f3.png)

**Comment by nyalldawson** [comment] 2019-05-28 01:07
Still cannot reproduce - please share a self contained project demonstrating this issue.

**Comment by Mi-Kbs-gis** [comment] 2019-05-28 08:45
[sample_project_label properties on rulebased layers.zip](https://github.com/qgis/QGIS/files/3226411/sample_project_label.properties.on.rulebased.layers.zip)

Just make the settings like in the screens. Save the project and reopen.

**Comment by gioman** [comment] 2019-05-28 13:21
> Just make the settings like in the screens. Save the project and reopen.

works as expected here on QGIS master.

**Comment by Mi-Kbs-gis** [comment] 2019-05-28 14:25
I used **QGIS 3.4.7** LTR in 3.6 it works very well!

**Comment by elpaso** [comment] 2019-06-07 07:28
I cannot reproduce even on current `release-3_4` branch, it must have been fixed in the meantime.

**Closed by elpaso** 2019-06-07 07:28 UTC
Labels: Bug, Feedback, High Priority, Labeling, Regression
