### ISSUE TITLE
GeoPDF export returns error message "Could not create print device"

### ISSUE THREAD

**Issue by mrt248** [qgis/QGIS#40528] opened 2020-12-09 16:14 UTC
**Describe the bug**
Trying to export a GeoPDF from Map Composer including layers with non-ascii characters in layer id value generates "Could not create print device" error. Normal PDF export works flawlessly, GeoPDF export works as long as there are no objects from this layer in your current map extent.

**How to Reproduce**

Add a data source which has non-ascii characters (Coruña.shp or ÜberJäger.shp, for example) in its name to your QGIS project, then try to export a GeoPDF. 
Error message => "Could not create print device".

**QGIS and OS versions**

QGIS and OS versions
QGIS 3.10 on Windows 10

**Additional context**

Quick fix (but not a solution) - open project file in a text editor and replace all non-ascii characters in layer id's.

**Comment by gioman** [comment] 2020-12-09 16:56
@mrt248 are you sure you are using the latest release of 3.10? this has been fixed: https://github.com/qgis/QGIS/issues/35242

**Comment by mrt248** [comment] 2020-12-09 17:34
Tested it on 3.10.10 and 3.10.12, got the same error message.

**Comment by gioman** [comment] 2020-12-09 17:38
> Tested it on 3.10.10 and 3.10.12, got the same error message.

I think there was a fix about this issue recently, maybe has net been backported. You should try also 3.16.1 and/or master.

**Comment by agiudiceandrea** [comment] 2020-12-12 21:02
It seems a duplicate of https://github.com/qgis/QGIS/issues/40106.
I hopefully fixed it with https://github.com/qgis/QGIS/pull/40156.
The fix is available in master, 3.16.1 and will be available in 3.10.13 too.

**Closed** 2020-12-13 11:12 UTC
Labels: Bug, Feedback, Print Layouts

**Comment by mseilis** [comment] 2021-02-10 18:47
Not fixed in a stable way.  Still an issue with qgis 3.16.3 Hannover.  Using Win10 pro os.  Sometimes works, sometimes fails with "cannot create print device" and sometimes (often) seems to make a pdf that is incomplete, throws errors when trying to load in adobe acrobat.  Anyone else still having this problem?

**Comment by agiudiceandrea** [comment] 2021-02-10 19:06
@mseilis are there data source which has non-ascii characters in your map?

**Comment by mseilis** [comment] 2021-02-10 19:45
Hi Andrea,  That could be a good question.  The map and layout contains shapefiles and geopackage files, a png picture and a label box that has pasted and edited text.  None of the source filenames have non -ascii text in the names, all are windows comliant.  Not sure how I would tell if there are problem characters contained inside some of those files.  I have tried removing some of the layers, but that has not changed the output.  Here's a snip of what my latest map looks like, most are similar in format.  

The times when loading in acrobat fails, generally most of the layers load, sometimes not all and usually the ther map layout items (eg labels, legend) are absent at the point that acrobat throws the error box.
<img width="1056" alt="snip" src="https://user-images.githubusercontent.com/78829489/107562591-e10d2900-6b94-11eb-9cc8-65fd9e1ad684.PNG">

**Comment by agiudiceandrea** [comment] 2021-02-10 20:16
> None of the source filenames have non -ascii text in the names, all are windows comliant. 

So I think your issue is not related with this bug report. Maybe it could be better to open a new bug report with all the needed info and steps to reproduce the issue providing a minimal project in which the issue occurs.

**Comment by mseilis** [comment] 2021-02-10 20:48
Ok, thanks.  Appreciate the response.

**Comment by davidlgalt** [comment] 2021-02-16 17:38
I encountered this exact error. I recently started using Postgres much more, and I was able to trace my issue to a layer that when it was export to Postgres, it was assigned a new UID, but it still kept a column called fid. When I renamed it to fid2 I was able to export GeoPDFs again.
