### ISSUE TITLE
Unable to save to Auxiliary Storage 

### ISSUE THREAD

**Issue by Joseph161020** [qgis/QGIS#43293] opened 2021-05-20 06:40 UTC
![image](https://user-images.githubusercontent.com/72951858/118931010-d0d1ca80-b989-11eb-90f4-015c0e5101de.png)
I get this message if I have been using QGIS for a while (several hours) and don't save the project frequently. Suggest setting an automatic save function to prevent the issue occurring.

**Comment by Houska1** [comment] 2021-05-20 09:09
Joseph, what version of QGIS are you using? And I assume from the directory structure, this is Windows 10?

This seems to be an ongoing bug which for some reason is hard to fix. See https://github.com/qgis/QGIS/issues/26365, which also provides some workarounds.

Many but not all reporters on Windows seem to encounter this more often when their computer has hibernated/gone to sleep in the meanwhile, and seems related to the operating system "cleaning up" the `.../Local/whatever` temporary directory in the background. 

To the devs: We really need to fix this ongoing bugbear. Maybe it's Windows' "fault" not QGIS, but it causes QGIS users' data loss, and at the very least a more informative error message with suggested workarounds (save temporarity as a .qgs not .qgz, then save as) would prevent data loss.

**Comment by gioman** [comment] 2021-05-20 09:38
Duplicate of https://github.com/qgis/QGIS/issues/26365

**Closed by gioman** 2021-05-20 09:38 UTC

**Comment by Joseph161020** [comment] 2021-05-20 22:23
Hi Martin,

3.16 Hanover – Long Term Release Version. Yes Windows 10 – Version 20H2.

It often happens while I’m working in a project and have QGIS running in the background for ready reference or to make  changes to the data. It would be useful for QGIS to have an autosave function which would be a workaround for MS windows other foibles.

Thank you for the information.

Joseph Adair
Senior Ecologist
M: +61 (0)428 120 930
PO Box 416, Rockhampton, QLD 4700
PO BOX 282 Morayfield QLD 4506
***@***.******@***.***>
www.greentapesolutions.com.au<http://www.greentapesolutions.com.au/>
