### ISSUE TITLE
QGIS 3.10 Projected CRS do not display properly

### ISSUE THREAD

**Issue by CharlesPetersen** [qgis/QGIS#33129] opened 2019-11-28 15:12 UTC
In QGIS 3.10, projected CRSs do not display properly. For example, the attached project file shows how the popular Gall Stereographic proj
[Projected CRS Bug.zip](https://github.com/qgis/QGIS/files/3902235/Projected.CRS.Bug.zip)
ection is mangled in version 3.10.

**Comment by gioman** [comment] 2019-11-28 15:13
@CharlesPetersen duplicate of https://github.com/qgis/QGIS/issues/30569 ?

**Comment by CharlesPetersen** [comment] 2019-11-28 15:44
Looks like the same problem reported in #30569 and #33121 .
My OS: Windows 10 Enterprise N Version 1809

**Closed** 2019-11-28 16:43 UTC
Labels: Bug, Feedback
