### ISSUE TITLE
qGIS sends wrong WFS version on save WFS layer

### ISSUE THREAD

**Issue by DmitriyVTitov** [qgis/QGIS#49975] opened 2022-08-26 21:49 UTC
### What is the bug or the crash?

qGIS sends HTTP request with version 1.0.0 for WFS layer with manual or autodetected version 2.0.0, when I save edited WFS layer (WFS Transaction request).
However it sends WFS 2.0.0 version tag with GetCapabilities and GetFeatures requests with same WFS datasource.

### Steps to reproduce the issue

1. Add WFS connection
2. Set WFS version to 2.0.0
3. Toggle edit layer
4. Add Feature
5. Press "Save Layer Edits"

### Versions

QGIS version
3.26.1-Buenos Aires
QGIS code revision
b609df9ed4d
Qt version
6.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
7.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rduivenvoorde** [comment] 2022-08-28 10:54
@DmitriyVTitov do you maybe have a publid/demo wfs-t available? I'm happy to try/reproduce but it would be much easier if you have one available :-)

**Comment by DmitriyVTitov** [comment] 2022-08-28 11:30
No, it's my companies private instance.
Probably that question is connected with current one: https://gis.stackexchange.com/questions/378448/correct-wfs-transaction-response 

Here is my local connection:
![image](https://user-images.githubusercontent.com/38575605/187071665-12361f4a-3704-4ac8-accd-fbd8272948c7.png)

GetFeatures request:
```
curl 'http://localhost:8081/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=category_3&STARTINDEX=0&COUNT=100&SRSNAME=urn:ogc:def:crs:EPSG::3857&BBOX=-5611840.70072418544441462,-3916598.59782896563410759,5320367.88501308392733335,4806996.86489273980259895,urn:ogc:def:crs:EPSG::3857' -H 'User-Agent: Mozilla/5.0 QGIS/32601/Windows 10 Version 2009'  --compressed
```
**VERSION=2.0.0**

Here is WFS-T request on save edited layer:
```
curl 'http://localhost:8081/wfs?SERVICE=WFS' -H 'Content-Type: text/xml' -H 'User-Agent: Mozilla/5.0 QGIS/32601/Windows 10 Version 2009'  --data '<Transaction xmlns="http://www.opengis.net/wfs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" service="WFS" xsi:schemaLocation="http://ogr.maptools.org/ http://localhost:8081/wfs?SERVICE=WFS&amp;REQUEST=DescribeFeatureType&amp;VERSION=1.0.0&amp;TYPENAME=category_3" xmlns:gml="http://www.opengis.net/gml" version="1.0.0"><Insert xmlns="http://www.opengis.net/wfs"><category_3 xmlns="http://ogr.maptools.org/"><desc xmlns="http://ogr.maptools.org/">desc</desc><label xmlns="http://ogr.maptools.org/">label</label><subcategory xmlns="http://ogr.maptools.org/">1</subcategory><cadastralcode xmlns="http://ogr.maptools.org/">50</cadastralcode><geoloc xmlns="http://ogr.maptools.org/"><gml:Point srsName="urn:ogc:def:crs:EPSG::3857"><gml:coordinates ts=" " cs=",">323274.10089292842894793,470781.52491816785186529</gml:coordinates></gml:Point></geoloc></category_3></Insert></Transaction>' --compressed
```
**VERSION=1.0.0**

**Comment by rduivenvoorde** [comment] 2022-08-28 11:40
Ah, if it is still the case as @rouault states here: https://github.com/qgis/QGIS/issues/34608
Then WFS-T (edit) capabilities are just not implemented for WFS version 2.0.0 (anybody can confirm?)
(but the normal GetFeatures etc request ARE implemented, so you cannot edit a 2.0.0 server)

Maybe a better solution then would be that IF a layer is specified as WFS 2.0.0 then the edit capabilties should not be enabled?

@DmitriyVTitov will it work if you force the layer to be a WFS 1.x.x layer? So at least you can edit? Or do you need specific WFS 2.0.0 capabilities/features?

**Comment by DmitriyVTitov** [comment] 2022-08-28 12:35
Well thanks for explanation @rduivenvoorde
I've implemented WFS 2 with great struggle. Then i've adjusted my code to accept WFS 1 requests from qGis.
I need edit capabilities anyways, but since my server does not declare V1 support I think it's a bug or inconsistency in qGis.
My system is goning to production next year and my users are going to use qGIS. So I wonder if qGIS is going to change reported behaviour.
Summary: don not disable editing anyway please :)

**Comment by DmitriyVTitov** [comment] 2022-08-28 12:40
To be clear: my WFS insance declare WFS 2.0.0 support only with GetCapabilities response.

**Comment by rouault** [comment] 2022-09-17 15:25
Closing as duplicate of #34608

**Closed by rouault** 2022-09-17 15:25 UTC
Labels: Bug, WFS data provider
