### ISSUE TITLE
Legend in layer tree is often broken when using map units

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#38606] opened 2020-09-04 15:06 UTC
**Describe the bug**
When using map units, the legend rendering in the layer tree is often totally broken, depending on the map scale, because the minimum or maximum sizes or stroke-widths are often way too big or too small. The result is either a broken symbol or nothing at all.

![image](https://user-images.githubusercontent.com/884476/92253737-2c2d5c80-eed0-11ea-8f2c-1957b5de0891.png)

@mhugent fixed a similar issue but concerning legends in layout. See also discussion in this [separate PR](https://github.com/qgis/QGIS/pull/37474).
@nyalldawson suggested to hard-code some reasonable numbers for min/max sizes/stroke-widths in legends in layer tree for the use in combination with map units. I agree with him. This would avoid additional UI and settings.

**Comment by Jean-Roc** [comment] 2021-04-19 12:38
hi @andreasneumann did you find a workaround ? The most curious part is that it is seems to have a sane maximum size when a single symbol is used but not when you use a category.

![symbol_datadefined_mapunit_1](https://user-images.githubusercontent.com/736212/115237187-8e179b00-a11c-11eb-9db1-0272be993d95.JPG)

![symbol_datadefined_mapunit_2](https://user-images.githubusercontent.com/736212/115237234-a12a6b00-a11c-11eb-9d75-52e2fc78a52a.JPG)

**Comment by Pedro-Murteira** [comment] 2022-03-02 15:04
Still valid on QGIS 3.22.4 and 3.24.0.

**Comment by alexbruy** [comment] 2022-05-12 09:51
Related issue #33755.

**Comment by troopa81** [comment] 2022-09-12 16:16
> hi @andreasneumann did you find a workaround ? The most curious part is that it is seems to have a sane maximum size when a single symbol is used but not when you use a category.

Parent legend node (node used for layer) have fixed  size (16 x 16) but children node (categorized or rule children node for instance) have variable size and change with the size you give in symbology properties. 

I think this is the wanted behavior, not an issue.

It's still possible to control their min/max size in application *options > Canvas & legend > Maximum/Minimum legend symbol size*.
You can set 5mm in both min/max for instance to have approximately the same fixed size.

It has been fixed in #39777 and backported in 3.16. I tested it on master and it works, so I close the issue. Please let me know if you think otherwise.

**Closed by troopa81** 2022-09-12 16:16 UTC
Labels: Map and Legend, Bug

**Comment by Jean-Roc** [comment] 2022-09-13 08:46
@troopa81 these parameters don't seem to be applied in our case (qgis 3.24.2 and master [b0d60567e5](https://github.com/qgis/QGIS/commit/b0d60567e5), screenshot below)

![example_oversized_symbol](https://user-images.githubusercontent.com/736212/189841883-8694460c-5f73-4559-ac41-571911b8dbcc.JPG)

it seems to be caused by the use of a geometry generator, you can find a QGIS project with his style and data (WFS) on our [opendata portal](https://open.isogeo.com/s/6e41e99659bf4b558003dbbb4dcd6d89/knzotVb4wTxg84nBFZtVul5oFo-v0/r/3367a658b12641b1b01703efeb2c9e1c?).

**Comment by troopa81** [comment] 2022-09-13 11:54
@Jean-Roc Yes, Indeed there is still an issue with geometry generator, reported in #33755 . I'll try to fix it.
