### ISSUE TITLE
No valid datum transformations for custom CRSes

### ISSUE THREAD

**Issue by jekhor** [qgis/QGIS#33323] opened 2019-12-10 21:44 UTC
**Describe the bug**
QGIS propose only invalid datum transformation for custom CRS (+towgs84 parameter is ignored).

**How to Reproduce**
1. Create a new project.
2. Create a custom CRS by copying of existing CRS definition with non-WGS84 datum (I use EPSG:3352 "Pulkovo 1942 / CS63 zone C2).
3. Select WGS84-based CRS for project (EPSG:32635 UTM zone C35N in my example).
4. Try to add datum transformations. There are many variants for EPSG:3352->EPSG:32635 will be proposed, but for created user CRS to EPSG:32635 only one variant with ignored +towgs84 parameters will be in list (see screnshots).
5. Add any vector layer twice, set EPSG:3352 for first, set created custom CRS for second. Layers will not aligned.

Expected result: datum transformation for custom CRS take +towgs84 parameter in account, features at vector layers has same positions.

![2019-12-11_00-41](https://user-images.githubusercontent.com/117467/70571639-46d7dc80-1baf-11ea-8c18-baa8a8b37c2a.png)
![2019-12-11_00-42](https://user-images.githubusercontent.com/117467/70571641-47707300-1baf-11ea-94ad-cd7c1f4af312.png)
![2019-12-11_00-43](https://user-images.githubusercontent.com/117467/70571642-47707300-1baf-11ea-97b2-66e22660ec3c.png)

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 2.4.3 | Running against GDAL/OGR | 2.4.3
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.30.1 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 12.1 (Debian 12.1-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | quick_map_services; nextgis_connect; firstaid; batch_gps_importer; Hotlink; qgis2web; qconsolidate3; QuickOSM; QuickPrint; SRTM-Downloader; vector_tiles_reader; Coordtransform; latlontools; cartolinegen; ImageServerConnector; processing; MetaSearch; db_manager

It's probably duplicate of #32928

**Comment by gioman** [comment] 2019-12-11 09:18
@jekhor I guess it works as expected on a QGIS version that uses proj 4 instead of proj 6, correct?

**Comment by kerkovits** [comment] 2019-12-11 09:55
I also assume that it is a duplicate of https://github.com/qgis/QGIS/issues/32928, as exactly the same behaviour can be reproduced in my use case. QGIS definitely ignores the towgs84 parameter, however there is no other possibility to define transforms for a custom CRS.

**Comment by jekhor** [comment] 2019-12-11 10:07
@gioman I got similar behaviour with 3.4 LTR standalone build on Windows with proj 5.2 but I need to re-check to prove.

**Comment by nyalldawson** [comment] 2019-12-11 22:32
This is actually a feature request for the proj library. To demonstrate:

`projinfo -s EPSG:3352 -t EPSG:32635 --spatial-test intersects` gives 6 candidates

`projinfo -s "+proj=tmerc +lat_0=0.1 +lon_0=27.95 +k=1 +x_0=2250000 +y_0=0 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs +type=crs" -t EPSG:32635` gives only the single candidate

@gioman proj builds < 6 just don't even have any concept of this kind of thing for comparison! 😆

**Comment by nyalldawson** [comment] 2019-12-11 22:37
I've submitted a ticket at proj (https://github.com/OSGeo/PROJ/issues/1792), but I suspect this is impossible using just proj string definitions of CRS. The QGIS solution would be to switch from using a proj string for the custom projection to using a WKT string.

**Comment by nyalldawson** [comment] 2019-12-11 23:08
See comments in the proj ticket -- this isn't a bug

**Closed by nyalldawson** 2019-12-11 23:08 UTC
Labels: Bug, Feedback, Projections/Transformations

**Comment by jekhor** [comment] 2019-12-12 07:53
I rechecked with qgis 3.4.13 compiled against proj 5.2.0 – there are no datum transformation variants proposed for custom projection but all points are aligned properly, +towgs84 seems to be used.

![2019-12-12_10-34](https://user-images.githubusercontent.com/117467/70692721-feaedc00-1ccc-11ea-9b72-6ac29f564738.png)
![2019-12-12_10-52](https://user-images.githubusercontent.com/117467/70692994-97ddf280-1ccd-11ea-8ae3-6f66aba693d4.png)
![2019-12-12_10-43](https://user-images.githubusercontent.com/117467/70692723-feaedc00-1ccc-11ea-9f44-66f5bbe4bbff.png)
![2019-12-12_10-43_1](https://user-images.githubusercontent.com/117467/70692724-ff477280-1ccc-11ea-9ef2-6839e78cc8ae.png)
