### ISSUE TITLE
QGIS Crash on exit (3.8.2 Zanzibar)

### ISSUE THREAD

**Issue by Corydalus** [qgis/QGIS#31431] opened 2019-08-26 19:59 UTC
This type of crash happens almost every time I close the program. It was happening with 3.4.2 and it is happening now with 2.8.2. It does not seem that i lose any data, everythings seems to save successfully. But then, the program crashes when I try to close it.

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-08-26 21:05
Try with a new/clean QGIS profile, without installing any 3rd party plugin.

**Comment by jef-n** [comment] 2019-08-27 12:14
Duplicate of #28104

**Closed** 2019-08-27 14:37 UTC
Labels: Bug, Feedback
