### ISSUE TITLE
GDAL clip of PostGIS rasters do not work anymore

### ISSUE THREAD

**Issue by David-laverty2** [qgis/QGIS#43030] opened 2021-04-29 20:30 UTC
Since upgrading QGIS to version 3.18 I am unable to run the 'clip raster by extent' tool on any of the rasters saved in my PostGIS DB's. 

I have noticed that the GDAL command is saying something different since upgrading from 3.10 which I'm not sure makes a difference but both can be seen below

3.10
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'PG: dbname=\'NI_Data\' host=10.0.0.6 port=5432 user=\'David\' password=\'pass\' sslmode=disable mode=2 schema=\'1m_LiDAR\' column=\'rast\' table=\'ardstraw_02_02_2012\'', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PROJWIN' : '233392.02821059752,234518.20498931917,386404.26908763463,387114.25010030693 [EPSG:29903]' }

3.18
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'dbname=\'NI_Data\' host=10.0.0.6 port=5432 user=\'David\' password=\'pass\' sslmode=disable srid=0 table=\"1m_LiDAR\".\"ballinmallard_05_03_2012\" (rast)',
 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'C:/Users/david.laverty/Desktop/RASTER CLIP DELETE.tif', 'OVERCRS' : False, 'PROJWIN' : '225567.441900000,226358.139500000,351688.372100000,352181.395300000 [EPSG:29903]' }

I just noticed that instead of saying schema=\'example' column = \'rast' table='etc'... it now (in 3.18) calls table =\'schema.table (rast)

this now gives the following error instead of clipping my raster as before

GDAL command output:
ERROR 4: `dbname='test1' port=5432 user='David' password=XXXXXXXXXX sslmode=disable srid=27700 table="public"."raster1_test" (rast)' does not exist in the file system, and is not recognized as a supported dataset name.
Process returned error code 1

to reproduce
1-  upload a raster to a postgis enabled DB using the following raster2pgsql command 

raster2pgsql -s 27700 -F -t auto -C -r "C:\Users\David\Desktop\LiDAR Test Data\SP26ne_DTM_1m.tif"  Raster1_test | psql -h localhost -p 5432 -U David -d test1

2- try and run the clip raster by extent command using 'draw on canvas' method

**QGIS and OS versions**

QGIS version
3.18.0-Zürich
QGIS code revision
bdef9fb328
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
go2streetview; 
MemoryLayerSaver; 
pointsamplingtool; 
profiletool; 
Qgis2threejs; 
qgis2web; 
vector_tiles_reader; 
db_manager; 
MetaSearch; 
processing

**Additional context**

System is running on windows 10 OS

**Comment by gioman** [comment] 2021-04-30 13:52
>  3.18.0-Zürich

@David-laverty2 you must test on the most recent release, 3.18.0 is too old.

**Comment by David-laverty2** [comment] 2021-04-30 15:05
ok, I can download the latest version from OSGEO4W this evening and report back. Cheers for your reply

**Comment by David-laverty2** [comment] 2021-05-04 13:53
I have downloaded and tested this issue with the latest 3.18.2 from OSGEO4W

QGIS and OS versions


QGIS version
3.18.2-Zürich
QGIS code revision
515138c171
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
go2streetview; 
MemoryLayerSaver; 
pointsamplingtool; 
profiletool; 
Qgis2threejs; 
qgis2web; 
vector_tiles_reader; 
db_manager; 
MetaSearch; 
processing

It appears this ERROR4, does not exist in the file system, still exists.  Below is a copy of my log when running the 'clip raster by extent' command

QGIS version: 3.18.2-Zürich
QGIS code revision: 515138c171
Qt version: 5.11.2
GDAL version: 3.1.4
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 6.3.2, May 1st, 2020
Processing algorithm…
Algorithm 'Clip raster by extent' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'dbname=\'test1\' port=5432 user=\'David\' password=\'David123\' sslmode=disable srid=27700 table=\"public\".\"raster1_test\" (rast)', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERCRS' : False, 'PROJWIN' : '426084.392100000,428601.046600000,267300.651300000,268735.451300000 [EPSG:27700]' }

GDAL command:
gdal_translate -projwin 426084.3921 268735.4513 428601.0466 267300.6513 -of GTiff "dbname='test1' port=5432 user='David' password='Imola859' sslmode=disable srid=27700 table="""public"""."""raster1_test""" (rast)" C:/Users/David/AppData/Local/Temp/processing_qWDATx/4562ed2bf7fe47408b51b3bb70c745aa/OUTPUT.tif
GDAL command output:
ERROR 4: `dbname='test1' port=5432 user='David' password=XXXXXXXXXX sslmode=disable srid=27700 table="public"."raster1_test" (rast)' does not exist in the file system, and is not recognized as a supported dataset name.
Process returned error code 1
Execution completed in 0.09 seconds
Results:
{'OUTPUT': 'C:/Users/David/AppData/Local/Temp/processing_qWDATx/4562ed2bf7fe47408b51b3bb70c745aa/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/David/AppData/Local/Temp/processing_qWDATx/4562ed2bf7fe47408b51b3bb70c745aa/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.


If you require any further info please don't hesitate to ask

**Comment by gioman** [comment] 2021-05-04 14:50
Same on master/Linux, seems a regression. The GDAL do not seems right.

**Comment by jgrocha** [comment] 2021-05-08 15:29
Confirmed. Fixing manually the generated GDAL command works. Seems that the problem is related with the generation of the connection string.

**Comment by David-laverty2** [comment] 2021-06-22 09:50
Hi, I have tested this issue using the latest 3.20 version of QGIS and it still exists. Is there anyway to fix this manually myself as I really would like the clip functionality returned on my PostGIS rasters. The last working version of this was 3.10. It was mentioned above that manually fixing the generated GDAL command works, could someone please explain to me how this would be done?

Kind regards,

David
 
QGIS version: 3.20.0-Odense
QGIS code revision: decaadbb31
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.0
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.0.1, March 5th, 2021
PDAL version: 2.3.0 (git-version: eac774)
Processing algorithm…
Algorithm 'Clip raster by extent' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'dbname=\'NI_Data\' host=10.0.0.6 port=5432 user=\'David\' password=\'Imola85\' sslmode=disable srid=0 table=\"1m_LiDAR\".\"ardstraw_02_02_2012\" (rast)', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERCRS' : False, 'PROJWIN' : '233759.812500000,234177.187500000,387023.625000000,387307.125000000 [EPSG:29903]' }

GDAL command:
gdal_translate -projwin 233759.8125 387307.125 234177.1875 387023.625 -of GTiff "dbname='NI_Data' host=10.0.0.6 port=5432 user='David' password='Imola85' sslmode=disable srid=0 table="""1m_LiDAR"""."""ardstraw_02_02_2012""" (rast)" C:/Users/David/AppData/Local/Temp/processing_unYYaP/aa4dcdb215f4426892d50e878e8f72f9/OUTPUT.tif
GDAL command output:
ERROR 4: `dbname='NI_Data' host=10.0.0.6 port=5432 user='David' password=XXXXXXXXX sslmode=disable srid=0 table="1m_LiDAR"."ardstraw_02_02_2012" (rast)' does not exist in the file system, and is not recognized as a supported dataset name.
Process returned error code 1
Execution completed in 0.07 seconds
Results:
{'OUTPUT': 'C:/Users/David/AppData/Local/Temp/processing_unYYaP/aa4dcdb215f4426892d50e878e8f72f9/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/David/AppData/Local/Temp/processing_unYYaP/aa4dcdb215f4426892d50e878e8f72f9/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by elpaso** [comment] 2021-06-22 10:15
The problem here is the missing `PG:` prefix before the connection string, @jgrocha had a solution but it seems like he closed the PR. IMHO the `gdalConnectionString()` (or similar API) approach was a valid one.

**Comment by David-laverty2** [comment] 2021-06-22 11:15
Would you have the time to explain to me what that means and / or how to implement it into my version of QGIS? I very much rely on this functionality and as of now I am stuck on version 3.10 as it was the last version where this command was working properly. Sorry for being a nuisance, I just thought as it was flagged as a regression that it would be fixed in this latest release

**Comment by gioman** [comment] 2021-06-22 11:21
> I just thought as it was flagged as a regression that it would be fixed in this latest release

@David-laverty2 there is no guarantee that a regression will be fixed in time for a new release.

**Comment by jgrocha** [comment] 2021-06-22 11:29
@David-laverty2 You can try the changes in PR mentioned in this thread. The PR was just a quick fix. I'll try to submit a proper fix, based on the PR feedback, but it takes some time to enhance the raster API.

**Comment by David-laverty2** [comment] 2021-06-22 12:02
I will try to add the additional code. Again , thank you very much for your time regarding this matter. Is this just a matter of removing the red lines of code and adding in the additional ones to the relevant python script?

Sorry for all the questions, I have never attempted anything like this before so I am not too sure of what to do

**Comment by David-laverty2** [comment] 2023-06-02 14:27
This is still an issue on version 3.30

Is there any update on a fix?

QGIS version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.0
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.1, June 1st, 2023
PDAL version: 2.5.3 (git-version: 7ec4e6)
Algorithm started at: 2023-06-02T15:16:56
Algorithm 'Clip raster by extent' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : 'dbname=\'NI_Data\' host=10.0.0.6 port=5432 user=\'David\' sslmode=disable authcfg=65p878b srid=0 table="1m_LiDAR"."ardstraw_02_02_2012" (rast)', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'OVERCRS' : False, 'PROJWIN' : '234637.450700000,234976.872500000,387550.525600000,387749.211600000 [EPSG:29903]' }

GDAL command:
gdal_translate -projwin 234637.4507 387749.2116 234976.8725 387550.5256 -of GTiff "dbname='NI_Data' host=10.0.0.6 port=5432 user='David' sslmode=disable authcfg=65p878b srid=0 table="""1m_LiDAR"""."""ardstraw_02_02_2012""" (rast)" C:/Users/david.laverty/AppData/Local/Temp/processing_VllZCw/e5bc2c0c51014f2cb3025b4090bff31d/OUTPUT.tif
GDAL command output:
ERROR 4: `dbname='NI_Data' host=10.0.0.6 port=5432 user='David' sslmode=disable authcfg=65p878b srid=0 table="1m_LiDAR"."ardstraw_02_02_2012" (rast)' does not exist in the file system, and is not recognized as a supported dataset name.
Process returned error code 1
Execution completed in 1.13 seconds
Results:
{'OUTPUT': 'C:/Users/david.laverty/AppData/Local/Temp/processing_VllZCw/e5bc2c0c51014f2cb3025b4090bff31d/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/david.laverty/AppData/Local/Temp/processing_VllZCw/e5bc2c0c51014f2cb3025b4090bff31d/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by effjot** [comment] 2023-07-31 09:26
This issue doesn’t seem to only apply to clipping, but all GDAL raster algorithms.

**Comment by effjot** [comment] 2024-07-04 15:08
The issue still persists in 3.34.6. For example, the Contour processing algorithm calls (according to the log output):

    gdal_contour -b 1 -a elev -i 0.25 -f "GPKG" "dbname='xxxx_db' host=xxxx port=5432 sslmode=disable table="""public"""."""test_raster""" (rast)" C:/Users/Jenn/AppData/Local/Temp/processing_dxEUSq/2469de98951a4e23a315b7cd2c9b0ed7/OUTPUT.gpkg

But the correct call would be:
    gdal_contour -i 1 -f "GPKG"  "PG:dbname=xxx_db host=xxxx port=5432 schema=public table=test_raster" testout.gpkg
   
So, the `PG:` is still missing and the table is addressed by schema.table dot notation instead of separate schema and table parameters.

**Comment by effjot** [comment] 2024-07-04 15:09
oh, sorry, I’ve seen that @uclaros is preparing a PR already. Thanks!

**Closed** 2024-07-10 22:37 UTC
Labels: Processing, Regression, Bug

**Comment by 84seb** [comment] 2024-11-30 07:10
I still have this issue in 3.34.13-Prizren

GDAL command:
gdalwarp -overwrite -of GTiff -cutline AIO.shp -cl AIO -crop_to_cutline "type=xyz&url=https://mt1.google.com/vt/lyrs%3Ds%26x%3D%7Bx%7D%26y%3D%7By%7D%26z%3D%7Bz%7D" /tmp/processing_tgmfcc/b1a84a582b57405cba10ccb8388aabab/OUTPUT.tif
GDAL command output:
ERROR 4: type=xyz&url=https://mt1.google.com/vt/lyrs%3Ds%26x%3D%7Bx%7D%26y%3D%7By%7D%26z%3D%7Bz%7D: No such file or directory
Process returned error code 2
Execution completed in 0.08 seconds
Results:
{'OUTPUT': '/tmp/processing_tgmfcc/b1a84a582b57405cba10ccb8388aabab/OUTPUT.tif'}

**Comment by nyalldawson** [comment] 2024-11-30 07:32
@84seb that's not a postgis raster, it's the Google tiles layer.

**Comment by 84seb** [comment] 2024-11-30 08:54
Ok, that's good to hear. Apologies to ask here further, how do I resolve this? and how do i see the issue is from gmaps layer? sorry stil new to qgis and python
