### ISSUE TITLE
QGIS 3.8.3-Zanzibar Unnespected ended - saving project to an empty geopackage

### ISSUE THREAD

**Issue by pecard** [qgis/QGIS#31967] opened 2019-09-23 16:12 UTC
**Describe the bug**
QGIS just crashed while trying to save the project to an empty geopackage.

**How to Reproduce**
Load some vector layers from a local driver
Create a geopackage following exactly this example:https://www.sigterritoires.fr/index.php/en/geopackage-format-and-qgis-3/

**QGIS and OS versions**
HP Probook with Windows 7 x64

**Additional context**

> Crash ID: e8299d5956e559c8be8d467ea7cad030710d9110
> 
> Stack Trace
> 
> QString::multiArg :
> QString::arg :
> QgsGeoPackageProjectStorage::writeProject qgsgeopackageprojectstorage.cpp:241
> QgsProject::write :
> CPLStringList::operator[] :
> QMetaObject::activate :
> QAction::activate :
> QMenu::actionGeometry :
> QMenu::actionGeometry :
> QMenu::mouseReleaseEvent :
> QWidget::event :
> QMenu::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify :
> QCoreApplication::notifyInternal2 :
> QApplicationPrivate::sendMouseEvent :
> QSizePolicy::QSizePolicy :
> QSizePolicy::QSizePolicy :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify :
> QCoreApplication::notifyInternal2 :
> QGuiApplicationPrivate::processMouseEvent :
> QWindowSystemInterface::sendWindowSystemEvents :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> QGIS Info
> QGIS Version: 3.8.3-Zanzibar
> QGIS code revision: 685d8b15d2
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 2.4.1
> Running against GDAL: 2.4.1
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 6.1.7601

**Comment by gioman** [comment] 2019-09-23 16:13
Please try with a new/clean QGIS profile.

**Comment by elpaso** [comment] 2019-09-23 16:17
@PauloEduardoCardoso duplicate of https://github.com/qgis/QGIS/issues/31310 ?

**Comment by nirvn** [comment] 2019-09-24 11:05
@elpaso , looking at the code, specifically https://github.com/qgis/QGIS/blob/master/src/core/providers/ogr/qgsgeopackageprojectstorage.cpp#L205

Shouldn't both failures creating a new file (missing driver or unable to create the file) return false? It's pointless to continue forward with either of these errors, and it'll likely patch the crash.

It could be that the shared drive (or the folder) is read-only or has some advanced permission scheme preventing QGIS from writing files.

Anyhow, play safe, return false :)

**Comment by m-kuhn** [comment] 2020-12-30 06:18
Is this still an issue with the latest QGIS release?

**Comment by gioman** [comment] 2020-12-30 09:54
I think we can safely assume this is duplicate of https://github.com/qgis/QGIS/issues/31310. Please reopen if necessary.

**Closed** 2020-12-30 09:54 UTC
Labels: Bug, Feedback
