### ISSUE TITLE
Crash when editing fields

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29200] opened 2019-02-26 07:00 UTC
Author Name: **Nicu Tofan** (Nicu Tofan)
Original Redmine Issue: [21383](https://issues.qgis.org/issues/21383)
Affected QGIS version: 3.6.0
Redmine category:editing

---
## User Feedback

Polygon layer in edit mode
Using a custom form for editing
Just edited a value switched focus to (clicked in) a different text edit widget in same custom form.

## Report Details

*Crash ID*: dbd69a76cf5ba4fd682524cd2740c8a497140fed

*Stack Trace*
```
QObject::metaObject :
QMetaObject::cast :
QgsLayerTreeModel::parent :
QModelIndex::parent :
QTreeView::drawRow :
QTreeView::drawTree :
QTreeView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.4-Madeira
QGIS code revision: f6ddc62fdb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

---

- [Crash Report.zip](https://issues.qgis.org/attachments/download/14463/Crash%20Report.zip) (Nicu Tofan)

---

Related issue(s): #29203 (duplicates)
Redmine related issue(s): [21386](https://issues.qgis.org/issues/21386)

---

**Comment by PeterPetrik** [comment] 2019-05-29 13:30
unable to reproduce on MacOS

**Comment by gioman** [comment] 2019-08-25 09:03
Closing as duplicate.

**Closed by gioman** 2019-08-25 09:03 UTC
Labels: Bug, Crash/Data Corruption, Editing, Feedback, High Priority, Regression
