### ISSUE TITLE
3.20 does not have QGIS Desktop

### ISSUE THREAD

**Issue by naf140230** [qgis/QGIS#43825] opened 2021-06-22 01:10 UTC
I just installed QGIS 3.20 on Windows and for some reason it does not include QGIS Desktop. Could someone please explain what is going on?

**Comment by agiudiceandrea** [comment] 2021-06-22 06:18
Duplicate of https://github.com/qgis/QGIS/issues/43819?

**Comment by gioman** [comment] 2021-06-22 07:50
> Duplicate of #43819?

I think it is.

**Closed by gioman** 2021-06-22 07:50 UTC
Labels: Feedback
