### ISSUE TITLE
conditional formatting in composer's attribute tables

### ISSUE THREAD

**Issue by ADAMKEPES** [qgis/QGIS#31042] opened 2019-08-01 21:35 UTC
**Feature description.**

conditional formatting in composer's attribute tables (by expressions)... would be great to have it, yeah!

**Additional context**

**Comment by Gustry** [comment] 2019-08-06 01:00
Duplicate of https://github.com/qgis/QGIS/issues/25712

**Closed** 2019-09-24 23:31 UTC
Labels: Feature Request
