### ISSUE TITLE
QGIS import multiple file filepath field character length

### ISSUE THREAD

**Issue by ansonl** [qgis/QGIS#52581] opened 2023-04-06 19:45 UTC
### What is the bug or the crash?

When importing multiple raster files, QGIS separates each filepath with double quotes. When too many files are selected in the file selection dialog, QGIS will truncate the combined filepath and cut off the files without indication. 

### Steps to reproduce the issue

1. Go to import raster file dialog
2. Open file selection dialog
3. Select lots (ex:2000) of files with a long filepath from `C:/`.
4. See that QGIS file imports filename field contains multiple files and filepaths at the end are cut off. 

### Versions

3.28-4 on windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment] 2023-04-07 09:18
Duplicate of #51294

**Closed by YoannQDQ** 2023-04-07 09:18 UTC
Labels: Bug

**Comment by ansonl** [comment] 2023-04-07 15:38
For those running into this length constraint, you can get around the limitation by dragging all the files into QGIS at once.

I was merging 2000 HGT files and the Merge tool has an input option within the tool to select an entire directory if you have prepared a directory with only the files you need.
