### ISSUE TITLE
Updating parent symbol results in undefined fill color at child symbols

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28957] opened 2019-01-31 07:40 UTC
Author Name: **Simon Gröchenig** (@SGroe)
Original Redmine Issue: [21139](https://issues.qgis.org/issues/21139)
Affected QGIS version: 3.4.4
Redmine category:symbology

---
I observe a bug in the categorized symbology. I prepare a parent symbol and create the child symbols afterwards. If I have to modify the parent symbol afterwards (e.g. line width), the fill color of all child symbols resets to black (attachment 'qgis_parent_symbol_bug.png') or maybe undefined (attachment 'qgis_empty_color.png').

It sometime works as expected in the first parent update, but it fails in the second one.

Expected behavior: Child symbol fill color should not change after updating the parent.

---

- [qgis_parent_symbol_bug.png](https://issues.qgis.org/attachments/download/14217/qgis_parent_symbol_bug.png) (Simon Gröchenig)
- [qgis_empty_color.PNG](https://issues.qgis.org/attachments/download/14218/qgis_empty_color.PNG) (Simon Gröchenig)

**Comment by nyalldawson** [comment] 2021-09-21 06:16
Duplicate of https://github.com/qgis/QGIS/issues/38377

**Closed by nyalldawson** 2021-09-21 06:16 UTC
Labels: Symbology, Bug
