### ISSUE TITLE
Crash or freeze with COPC point cloud and 3D view

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#53626] opened 2023-06-28 07:42 UTC
### What is the bug or the crash?

Loading this COPC point cloud crashes or freezes when a 3D view is involved: https://hannes.enjoys.it/copc/DOM1_XYZ_HH_2020_04_30-colored.copc.laz (Built from https://suche.transparenz.hamburg.de/dataset/digitales-hoehenmodell-hamburg-bdom4, license: Datenlizenz Deutschland Namensnennung 2.0 Namensnennung, Freie und Hansestadt Hamburg, Landesbetrieb Geoinformation und Vermessung (LGV))

#### Freeze
- Add https://hannes.enjoys.it/copc/DOM1_XYZ_HH_2020_04_30-colored.copc.laz as layer
- Open new 3D view
- QGIS freezes with full CPU usage, I did not wait more than 1-2 minutes for it to finish whatever it is doing. There is no network traffic.
- Nothing interesting is logged to the terminal

#### Crash
- Have open 3D view
- Add https://hannes.enjoys.it/copc/DOM1_XYZ_HH_2020_04_30-colored.copc.laz as layer
- QGIS crashes
- Terminal shows:
```
...
[New Thread 0x7fff233ff640 (LWP 19047)]
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
Warning: FBO incomplete
[New Thread 0x7fff227fe640 (LWP 19048)]
...
```
- gdb says:
```
#0  0x00007ffff534a084 in Qt3DCore::QSceneChange::type() const () at /lib/x86_64-linux-gnu/libQt53DCore.so.5
#1  0x00007ffff5338dae in Qt3DCore::QChangeArbiter::distributeQueueChanges(std::vector<QSharedPointer<Qt3DCore::QSceneChange>, std::allocator<QSharedPointer<Qt3DCore::QSceneChange> > >*) () at /lib/x86_64-linux-gnu/libQt53DCore.so.5
#2  0x00007ffff5338fcb in Qt3DCore::QChangeArbiter::syncChanges() () at /lib/x86_64-linux-gnu/libQt53DCore.so.5
#3  0x00007ffff5346a25 in Qt3DCore::QAspectManager::processFrame() () at /lib/x86_64-linux-gnu/libQt53DCore.so.5
#4  0x00007ffff5346c4a in  () at /lib/x86_64-linux-gnu/libQt53DCore.so.5
#5  0x00007ffff48f1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff46b29dc in QAbstractAnimation::stop() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff46b2bfc in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff46b1493 in QUnifiedTimer::updateAnimationTimers(long long) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff46b3271 in QAnimationDriver::advanceAnimation(long long) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff48e733f in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff556c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff2fa2ca3 in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd5b0, receiver=0x555557d91688, event=0x7fffffffcf80)
    at ./src/core/qgsapplication.cpp:580
#13 0x00007ffff48b9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff49123eb in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff4912cec in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fffea720d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fffea776258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fffea71e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff49130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff48b875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff48c0cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x0000555555562002 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ./src/app/main.cpp:1817
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.32.0-Lima | QGIS-Codeversion | 311a8cb8a6
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.10.6
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Ubuntu 22.04.2 LTS
  |   |   |  
Aktive Python-Erweiterungen
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I encountered it with QGIS 3.32 on Ubuntu 22.04.2 from the qgis.org repository and also reproduced it with 3.28.4 from conda.

I could not reproduce it with https://na-c.entwine.io/st-helens/ept.json nor with https://s3.amazonaws.com/grid-public-ept/20210421-FLW-Trestle-low-attitude.copc.laz

**Comment by newcomb-d** [comment] 2023-06-29 16:58
I have been seeing this on Windows 10 with QGIS 3.28.7 Standalone Installer

**Comment by wonder-sk** [comment] 2023-10-15 20:56
Duplicate of #53941

**Closed by wonder-sk** 2023-10-15 20:56 UTC
Labels: 3D, Bug, Crash/Data Corruption, Point Clouds
