### ISSUE TITLE
3D Viewer Crashes QGIS Every Time I Change the View Angle

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28564] opened 2018-12-06 14:45 UTC
Author Name: **Kevin Garcia** (Kevin Garcia)
Original Redmine Issue: [20744](https://issues.qgis.org/issues/20744)
Affected QGIS version: 3.4.2
Redmine category:3d

---
It look like I'm having the same issue as in #17315

In 3D map view, QGIS crashed while trying to change from overhead to an oblique-angle view. This happens every time I use the 3D renderer and change the view angle. I previously had QGIS 3.2.2 installed and had the same problem.
 
*Crash ID*: 4204a1ddb6dd872a885fd5204602826f03b7a5f8

*Stack Trace*
DrvGetLayerPaletteEntries :
DrvGetLayerPaletteEntries :
DrvGetLayerPaletteEntries :
DrvGetLayerPaletteEntries :
DrvGetLayerPaletteEntries :
DrvGetLayerPaletteEntries :
Qt3DRender::Render::Renderer::performDraw :
Qt3DRender::Render::Renderer::executeCommandsSubmission :
Qt3DRender::Render::Renderer::submitRenderViews :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
 
*QGIS Info*
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2
 
*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

---

Related issue(s): #25213 (relates)
Redmine related issue(s): [17315](https://issues.qgis.org/issues/17315)

---

**Comment by wonder-sk** [comment] 2019-05-27 11:55
Duplicate of #25213

**Closed by wonder-sk** 2019-05-27 11:55 UTC
Labels: 3D, Bug, Crash/Data Corruption
