### ISSUE TITLE
Tranformation dialog is sometimes too high and not resizeable

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#42090] opened 2021-03-07 21:55 UTC
As seen on 3.16 on a 1600x900 display

![Capturar](https://user-images.githubusercontent.com/1951107/110256262-c8274600-7f8f-11eb-9f66-7dad79cee94a.PNG)

**Comment by roya0045** [comment] 2021-03-07 22:36
I'm 99% there was already an issue about this.

**Comment by roya0045** [comment] 2021-03-08 16:07
Yep duplicate of #39589 ;)

**Closed** 2021-03-08 21:59 UTC
Labels: Bug, GUI/UX
