### ISSUE TITLE
Performance enhancement of rendering vector tiles

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#35633] opened 2020-04-06 14:22 UTC
Making the performance even better. Not sure how we can set the baseline to compare the performance against?

Maybe the same layer in vector format with same/similar style applied to it? Perhaps it has to be local, as online services are subject to all sorts of other parameters.

**Comment by nyalldawson** [comment] 2020-09-15 00:58
Let's close this -- as discussed in https://github.com/qgis/QGIS/pull/38725 the problem is the ridiculous level of detail present in the openstack tiles. https://github.com/qgis/QGIS/pull/38725 does what we can to improve this, but the real fix lies in the data provider.

**Closed by nyalldawson** 2020-09-15 00:58 UTC
Labels: Data Provider, Feature Request, Vector tiles
