### ISSUE TITLE
crash on osgeo::proj::datum::Datum::conventionalRS

### ISSUE THREAD

**Issue by antanisabboni** [qgis/QGIS#33178] opened 2019-12-01 15:44 UTC
Crash ID: 029bc1a9b819dfb49a1342291172e44f3c1f8e53

Stack Trace

osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:3885
QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:373
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1542
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.13-Madeira
QGIS code revision: 567300ccf1
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-12-02 08:57
@antanisabboni this bug report is largely incomplete, please add detailed steps to replicate add attach/link sample project and data.

**Comment by Gustry** [comment] 2019-12-02 12:54
Checking the crash ID, there are already 2 other tickets which are closed : https://github.com/qgis/QGIS/search?q=029bc1a9b819dfb49a1342291172e44f3c1f8e53&type=Issues

IS-it a duplicate of https://github.com/qgis/QGIS/issues/32925 ?

**Comment by nyalldawson** [comment] 2019-12-09 04:23
Fixed in 3.10.1

**Closed by nyalldawson** 2019-12-09 04:23 UTC
Labels: Bug, Digitizing
