### ISSUE TITLE
Crash when duplicating a layout 

### ISSUE THREAD

**Issue by Energeo1** [qgis/QGIS#54012] opened 2023-08-01 13:38 UTC
### What is the bug or the crash?

When I want to start editing a layout that I just duplicated, QGIS gets stuck for a moment and then crashes.
This happens often with any project I am working on. 

Here ar the Report Details: 

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005de0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserPeekMessage :
_PeekMessage :
PeekMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

1. Create a layout in your project
2. Duplicate the layout
3. Try editing the duplicated layout

### Versions

**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2023-08-02 16:39
@Energeo1 thanks for reporting. Could you please specify if the issue does occur every time a duplicated layout is edited or only some times? Could you please provide a sample project and exact steps in order to replica the issue? Have you tried if the issue does occur using a new QGIS user profile with no external plugin installed?

**Comment by Energeo1** [comment] 2023-08-03 14:03
@agiudiceandrea thank you for your feedback! 

Strangely the issue does not occur every time I edit a duplicated layout, only sometimes. Unfortunately I cannot relate the issue to a prior common step, because there is none. 
I open the duplicated layout and either zoom in or try to change an inserted element in the map layout and then qgis crashes. Sometimes it also crashes directly without trying to edit anything. Then in some cases the window "QGIS ended unexpectedly" occurs and in others QGIS crashes without any information. 
The issue does not occur when using a new QGIS user profile, but unfortunately I cannot get my work done without any external plugins installed. 
Creating a comparable example project is difficult because I have a lot of layers, also different layers in the project, and I cannot share the data I'm working with because they are sensitive. 
The working flow is the following:
1. Create a layout
2. Close this layout an duplicate it in the layout manager
3. Open the duplicated layout and try to edit

I hope this helps to understand the issue as well.
Does anyone else know this problem? 

Thank you!

**Comment by nyalldawson** [comment] 2023-10-03 21:36
Related to https://github.com/qgis/QGIS/issues/52079

**Comment by nyalldawson** [comment] 2023-10-04 04:25
Duplicate of https://github.com/qgis/QGIS/issues/52079

**Closed by nyalldawson** 2023-10-04 04:25 UTC
Labels: Bug, Crash/Data Corruption, Print Layouts
