### ISSUE TITLE
Cannot save project: "unable to save auxiliary storage"

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#34462] opened 2020-02-13 18:05 UTC
**Describe the bug**

QGIS 3.10.2 seems to have a saving issue refusing to save work you have done. This happens if you are called away from your desk for several hours when you try to save your work you will have the following unhelpful message pop up and cannot save your work. Leading you to quit QGIS and loose it all which is incredibly frustrating. Save As has the same result. And there is no way that i can find to recover

![ae85db0d7fbf4c0ece5361461c2f1124](https://user-images.githubusercontent.com/54211372/74463918-d9b32280-4e4f-11ea-88ba-dcd8e5c1e5a8.png)

The directory contents its looking in do not hold this directory at all!

![4d7a7cf0f6aea4525a8d910d70c06898](https://user-images.githubusercontent.com/54211372/74464049-13842900-4e50-11ea-82a0-160f7c189c36.png)

**How to Reproduce**
**1) It is easy to reporoduce start QGIS with your project open in the morning
2) get called to a meeting for 4 hours
3) come back make some more changes and try and save them pressing the save disk button  results in you being not able to save the work from QGIS**

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
aderyn; 
agknow_qgis; 
floodrisk2; 
ImageServerConnector; 
latlontools; 
LecoS; 
qgis_resource_sharing; 
rivergis; 
VectorBender; 
ZoomToPostcode; 
MetaSearch; 
processing

**Additional context**

This has been ongoing some time  and is getting the point of bewilderment . I love QGIS but guys this is fundamental

**Comment by roya0045** [comment] 2020-02-13 18:17
Don't put your things in the temps folder as they will be removed by your system. The fault is not on qgis.

**Comment by MPN-stack** [comment] 2020-02-13 18:23
I haven't put anything in a temp folder @roya0045 .My file is located on a different drive connected to the system. QGIS chooses this directory  have not used it before. Hope this clarifies.

**Comment by roya0045** [comment] 2020-02-13 18:35
You might have connection issues to that drive. I never had such problem and I always work on shared networks.

**Comment by MPN-stack** [comment] 2020-02-13 19:01
@roya0045  nope the drive is internal on the  same bus as the C drive so no problems there . This is  
 a QGIS fault its doing something it should not,  but if its searching in a temporary folder for something then it should not have placed it there as you stated already as windows will remove it . Why then s it placing something there that my project cannot  locate C:\Users\BLAGMOSWHAT\AppData\Local\Temp\QGIS3\qt-jl-icons

**Comment by MPN-stack** [comment] 2020-02-13 19:17
@roya0045,  Just saying it lost all my work today. It creates this temporary folder item when you load a project.  I am not sure why it places it here when it has its own directory when the project is loaded it then creates  two directories in ...\AppData\Local\Temp\QGIS3-AIZuNG and \AppData\Local\Temp\QGIS3-AQOHtj . The latter holds a copy of the .qgd file i am not sure why : See below :

[file47158.pdf](https://github.com/qgis/QGIS/files/4200523/file47158.pdf)
 IF this is created as is in the temporary folder which you stated was not a good idea placing a project file there as windows routinely deletes things why is QGIS doing this and is this not a BUG?

**Comment by nyalldawson** [comment] 2020-02-13 23:07
This **is** a bug

**Comment by roya0045** [comment] 2020-02-14 00:35
@MPN-stack thanks for the details, this should be helpful to anyone that will tackle this.

**Comment by gioman** [comment] 2020-02-15 10:16
Closing as duplicate of https://github.com/qgis/QGIS/issues/26365

**Closed by gioman** 2020-02-15 10:16 UTC
Labels: Bug, Project

**Comment by MPN-stack** [comment] 2020-02-17 17:08
This is still is doing this . It did this again today exactly the same message  and failure to save i set my home directory as specified and it does exactly the same creating QGIS items in temporary director which windows purges. why is @gioman closing items still unresolved ? This is preventing QGIS getting better

**Comment by MPN-stack** [comment] 2020-02-17 17:11
> This **is** a bug

Yes @nyalldawson  its unresolved and  this idiotic person on here above closed it again why is he working for you no disrespect intended. But you are not going to get anything fixed which is a bug if this is all this person does for you .

**Comment by MPN-stack** [comment] 2020-02-17 17:14
It is quite apparant to me that this is creating these temporary files as my data project is on a non c drive . Why is it copying it to a temporary area  in the first place when @roya0045 told me i should not even keep my own projects here ? You do not seem to be providing any support . Do i have to start posting in forums to wake you all up ?

**Comment by MPN-stack** [comment] 2020-02-17 17:36
@gioman  YOu have now closed #20828 , #34462 and #34462 stating they are all duplicate with no master record still being pen . How are you resolving this issue just closing it?

**Comment by DelazJ** [comment] 2020-02-17 17:37
@MPN-stack 
> why is @gioman closing items still unresolved ?

Probably because (quoting @gioman )
> Closing as duplicate of #26365

@MPN-stack 
> This is preventing QGIS getting better

Keeping the same issue reported multiple times won't make it better neither. Better put all the information at a single place.
But being disrespectful and insulting would certainly make people feel less concerned about your issue.
> Do i have to start posting in forums to wake you all up ?

Feel free if you think it would bring a positive outcome for your problem.

**Comment by MPN-stack** [comment] 2020-02-17 17:44
@DelazJ  Well at least 3 people have this same problem ave now closed #20828 , #34462 and #34462 so its not just me @gioman  has closed everyone suggesting there is more.  

Further more 1 found 9 open and 16 closed https://github.com/qgis/QGIS/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+auxiliary+storage


This means that you have potential **### 28 users with this problem** if they are all duplicates. Why is no support being given . Why is this QGIS procedure copying this project to a folder the QGIS team know it will get deleted from . Is that not extraordinary to you it is to me!

**Comment by alexbruy** [comment] 2020-02-17 17:54
@MPN-stack please stop spamming the same message in all related tickets. As you was told many times, opening multiple tickets does not help at all, this only makes it difficult to developers and other users to find information about the problem. It is enough to open only single ticket and put all information in it.

Closing duplicate tickets is a normal practice.

Also as pointed by @DelazJ being disrespectful and insulting would certainly make people feel less concerned about your issue.

**Comment by MPN-stack** [comment] 2020-02-17 17:55
@alexbruy , Please stop renaming my data

**Comment by MPN-stack** [comment] 2020-02-17 17:58
There is no point closing a ticket if you have provided no solution to potential 28 other people. That is called ignoring a problem .I will stop Spamming which is what you call it, when i call it informing people of whats happening when you provide a solution. and stop ignoring it.

**Comment by DelazJ** [comment] 2020-02-17 18:01
@nyalldawson  stated
> This **is** a bug

So yes, this is a bug to fix. Now as you have noticed, there are around 3400 open issues so this one fall in the group and will get fixed when it will. If it's a priority for you, you can finance it. Please go and read http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ to understand a bit how things work in open source.
And it's closed because there's already the same issue reported by someone else. Not because nobody cares.

@MPN-stack 
> Further more 1 found 9 open and 16 closed https://github.com/qgis/QGIS/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+auxiliary+storage

> This means that you have potential ### 28 users with this problem if they are all duplicates.

My sum made 25 but that's not a big deal. Issue is that you are mixing different kind of issues in your list and also, if you have read each of them, you'd notice that some are closed because they are fixed.

**Comment by gioman** [comment] 2020-02-17 18:05
> YOU have now closed #20828 , #34462 and #34462 stating they are all duplicate with no master record still being open . How are you resolving this issue just closing it?

@MPN-stack please make an effort and try to understand how things work:

#20828 is completely unrelated to all the fuss you are doing and it was closed as no feedback was given by the time we shipped a new major release. 


 #34462 was closed because *IS* duplicate of #26365 and the policy is to try keep 1 (*ONE*) ticket open for the same issue, usually the oldest one.




> and this idiotic person

thank you for calling me idiot, I will propose your suspension or ban from this platform.



> But you are not going to get anything fixed

you clearly do NOT understand the rules of the game: there is NO guarantee that any of the tickets/issues that have been reported will be fixed in time for any release, regardless of the number of persons can be impacted by it. This is open source, so if something bothers/blocks you you should ask yourself what you can do to have the issue sorted sooner than later.

> Further more 1 found 9 open and 16 closed https://github.com/qgis/QGIS/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+auxiliary+storage

this does not means that this tickets are all about the same issue. If there are duplicates open, then some of them should be closed.

>  Why is no support being given .

If you want support other than the free/gratis one that a lot of QGIS members put in the communities each day, look at QGIS commercial/professional support page.



> Why is this QGIS procedure copying this project to a folder the QGIS team know it will get deleted from . Is that not extraordinary to you it is to me!

it is a few millions lines of code, shit happens.

> Yes i must agree I feel insulted too its very disrespectful to waste someones time when they enter in information in the hope of a solution to have it closed and ignored under the pretext that a solution has been given out that suits all duplicates when it does not.

then one who insulted other was you. I'm just trying to do my "job" which is to try keep this bug tracker as less cluttered as possible. If you open an issue that was already be reported it will always be closed, this does not means that is a useless effort as tickets are always cross-referenced.

**Comment by MPN-stack** [comment] 2020-02-17 18:06
Please stop changing my data @gioman gioman

**Comment by gioman** [comment] 2020-02-17 18:08
> Please stop changing my data @gioman gioman

please stop spamming and make an effort to understand the "rules".

**Comment by MPN-stack** [comment] 2020-02-17 18:09
@gioman  lease either provide a solution or stop editing my data.

**Comment by gioman** [comment] 2020-02-17 18:13
> @gioman Please either provide a solution or stop editing my data.

@MPN-stack look, we don't know how to explain it in a simpler way: IS A BUG. It must be solved, right. You have a few choices about it:

1) wait for the fix

2) do whatever is in your power to make the fix happen sooner than later. Among the other options: submit a patch or hire a developer.

**Comment by DelazJ** [comment] 2020-02-17 18:13
> Yes i must agree I feel insulted too its very disrespectful to waste someones time when they enter in information in the hope of a solution to have it closed and ignored **under the pretext that a solution has been given out** that suits all duplicates when it does not.

@MPN-stack When did you get the feeling of what i put in bold in your comment above?

**Comment by nyalldawson** [comment] 2020-02-17 21:47
@jef-n do you have rights to block @MPN-stack from the QGIS repos? I don't seem to have the github permissions to do this, but the abuse they've directed at @gioman should never be tolerated and is completely against the project's code of conduct.

**Comment by jef-n** [comment] 2020-02-17 23:29
> @jef-n do you have rights to block @MPN-stack from the QGIS repos?

Apparently I do.

**Comment by sfreeborne** [comment] 2021-12-01 23:53
Sooo... does anybody know if there is a fix for this problem yet?

**Comment by 0verlord84** [comment] 2021-12-10 13:32
If it can help, this error popped up right after when I copied/pasted the style from another QGIS instance.
ver 3.16.14
