### ISSUE TITLE
Bold and italic attributes of labels that reinitialize

### ISSUE THREAD

**Issue by Geoscope19** [qgis/QGIS#46896] opened 2022-01-19 17:58 UTC
### What is the bug or the crash?

Suivant les polices utilisées (et beaucoup d'entre-elles) pour afficher les étiquettes, la configuration manuelle du gras et de l'italique tend à se désactiver dès lors que l'on retourne configurer le style de l'étiquette (quelque soit l'un des 8 onglets de configuration de l'étiquette). si on ne fait pas attention, l'apparence de l'étiquette saute en "normal" au lieu du gras et/ou italique.
Le basculement automatique vers normal "sans mon consentement" est bizarrement assez aléatoire !

Je rencontre ce problème par exemple pour les polices Swis721 Cn BT et la série Noto Sans display. 
Je suis sous W10 et je rencontre ce problème depuis que j'utilise q-gis (3.XXX) et encore dans la dernière version téléchargée (3.22)

Au cas où, la police Swis721 est téléchargeable ici : www.geoscope.fr/extranet/swiss.zip

### Steps to reproduce the issue

1. dans étiquette / abc 
2. police : Swis721 Cn BT / style --> gras
3. je bascule par exemple dans symbologie et je reviens dans étiquette
4.  le style est passé en normal

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.2-Białowieża | Révision du code | 1601ec46d0
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.4.0
Version de Proj | 8.2.0
Version de la base de données du registre EPSG | v10.038 (2021-10-21)
Version de GEOS | 3.10.0-CAPI-1.16.0
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 13.0
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3
Version de QScintilla2 | 2.11.5
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
cadastre | 1.13.5
DigitizingTools | 1.5.1
GeometryShapes | 0.7
ImportPhotos | 3.0.3
plaingeometryeditor | 3.0.0
PluginLoadTimes | 3.0.1
Qgis2threejs | 2.6
TerrainShading | 0.9.3
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment] 2022-01-19 18:00
@Geoscope19 In English please (edit title and description).

**Comment by Geoscope19** [comment] 2022-01-19 18:02
I'm sorry, I don't speack english :-(

**Comment by roya0045** [comment] 2022-01-19 19:50
@gioman Basically "Font style are resent when opening the label configuration" He's mostly referring to the bald and italic font style that seem to get reset whenever someone opens any widget that shows the label configuration.

**Comment by Geoscope19** [comment] 2022-01-19 20:00
yes is it this problem, if I understand Reverso’s translation ;-)

**Comment by gioman** [comment] 2022-01-19 20:31
> * dans étiquette / abc
> 
> * police : Swis721 Cn BT / style --> gras
> 
> * je bascule par exemple dans symbologie et je reviens dans étiquette
> 
> * le style est passé en normal

@Geoscope19 cannot replicate here on 3.22.3 on Windows 10. I used the font that is described on a line layer. 
Please still translate the title.

**Comment by nicogodet** [comment] 2022-01-20 07:00
@Geoscope19 Do you use the Layer Styling Panel ? 
Est-ce que tu utilise le panneau Style de Couche ?
![image](https://user-images.githubusercontent.com/39594821/150288910-a1b2a7f6-b282-4b30-8164-692200fb0a91.png)

@gioman I'm able to reproduce this issue in Layer Styling Panel:
![export7](https://user-images.githubusercontent.com/39594821/150289237-bec41e5a-17ae-423a-adf4-a6682dbe9402.gif)

But not in layer properties

**Comment by Geoscope19** [comment] 2022-01-20 07:49
@nicogodet Oui, c'est exactement ici
@gioman yes it is here

**Comment by elpaso** [comment] 2022-01-21 13:43
Works for me on Linux/master:
![bug_46896](https://user-images.githubusercontent.com/142164/150537068-01b5b099-7d63-4301-bc4b-57ea90abb77d.gif)

**Comment by elpaso** [comment] 2022-01-21 13:47
Notice I don't have "Bold Italic", I tested "bold" and "italic".

**Comment by roya0045** [comment] 2022-01-21 14:56
> Works for me on Linux/master: ![bug_46896](https://user-images.githubusercontent.com/142164/150537068-01b5b099-7d63-4301-bc4b-57ea90abb77d.gif)

Windows specific?

**Comment by elpaso** [comment] 2022-01-21 15:01
> Windows specific?

That's what I thought, but I'm not sure.

**Comment by gioman** [comment] 2022-01-21 15:03
> That's what I thought, but I'm not sure.

I'm checking that.

**Comment by gioman** [comment] 2022-01-21 15:26
> Notice I don't have "Bold Italic", I tested "bold" and "italic".

same here, beside that is OK on windows too using the styling panel.

**Comment by roya0045** [comment] 2022-01-24 13:28
Could the language settings be in play? If the 'style' is translated and not found back in the english setting it would reset to the first option? Could this be what's happening?

**Comment by nicogodet** [comment] 2022-01-24 13:33
@roya0045 Just tested.
My OS is in french and QGIS with new profile overrided in UI "American english" and locale "English UK (en_GB)", some style are displayed in french !

![image](https://user-images.githubusercontent.com/39594821/150792038-6cc89c85-7961-4876-a25a-dffb47392632.png)

Should be "bold"

**Comment by nicogodet** [comment] 2022-01-24 13:35
With "Arial" no issue
With "Swis721 Cn BT", i reproduce the issue

**Comment by Geoscope19** [comment] 2022-01-24 13:41
@nicogodet Yes, I confirm that this issue does not affect all policies at home either

**Comment by danzig666** [comment] 2022-04-06 11:24
This might be a duplicate of [#44418](https://github.com/qgis/QGIS/issues/44418) I submitted last year.

**Comment by alexbruy** [comment] 2023-10-13 12:41
Duplicates #44418.

**Closed by alexbruy** 2023-10-13 12:41 UTC
Labels: Labeling, Bug
