### ISSUE TITLE
Identify and select tools don't work with geometry-based query layers

### ISSUE THREAD

**Issue by Isaacson33** [qgis/QGIS#50242] opened 2022-09-19 08:29 UTC
### What is the bug or the crash?

Layers loaded into a Qgis project which are the result of a query made in spatialite load correctly, but the identify tool and the select tool both seem to select/identify polygons that are nowhere near the pointer. This problem is restricted to those tools as both 'select all' and 'zoom to feature' in the attribute tables works as expected.

### Steps to reproduce the issue

1. create a spatialite layer and add some polygons with a few arbitrary field values (score_1, score_2 for example)
2. run a query (I use DB manager) like ```select pkuid, {your geometry field}, score_1 + score_2 as score_3 from {your initial spatialite layer}```
4. click on 'create a view'
5. load the layer into a qgis project
6. try to select or identify a polygon

I've created a test project exhibiting the behaviour
[Test Project.zip](https://github.com/qgis/QGIS/files/9597219/Test.Project.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.26.2-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Qt version | 5.15.5
Python version | 3.10.6
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.2 | Running against SQLite | 3.39.3
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
qfieldsync | v4.1.1
geo_sim_processing | 1.2.0
refFunctions | 1.6
TomBio | 3.4.1
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment] 2022-09-20 07:36
Can you please attach a sample project and data to reproduce the issue?

**Comment by nicogodet** [comment] 2022-09-20 07:46
@elpaso 

> I've created a test project exhibiting the behaviour
> [Test Project.zip](https://github.com/qgis/QGIS/files/9597219/Test.Project.zip)

**Comment by elpaso** [comment] 2022-09-20 14:40
Cannot reproduce on current master.

**Comment by fmeier1995** [comment] 2023-03-09 15:03
I have the same issue but only with the map selecting tool, identify works. It happens with every SpatiaLite View I created via DB Manager.

Selecting any feature in this view always selects the same one feature, selecting any two features always selects the same two features, ...

Only map selecting fails, select via attribute table is fine.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS-Version | 3.28.4-Firenze | QGIS-Codeversion | fd0fb72ab3
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.6.2
PROJ-Version | 9.1.1
EPSG-Registraturdatenbankversion | v10.076 (2022-08-31)
GEOS-Version | 3.11.1-CAPI-1.17.1
SQLite-Version | 3.39.4
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

**Comment by alexbruy** [comment] 2023-10-27 12:34
There are errors in the console when trying to select features in the view
```
SpatiaLite[1] SQLite error: no such column: ROWID
SQL: SELECT 0,"score_3" FROM "combined" WHERE ROWID=1
```

**Comment by alexbruy** [comment] 2023-10-27 12:51
Digging more, it seems that this is not a QGIS bug, but data issue. The view does not have an entry in the `views_geometry_columns` table. Once view correctly registered in the SpatiaLite tables everything works fine.

Closing.

**Closed by alexbruy** 2023-10-27 12:51 UTC
Labels: Map Tools, Bug
