### ISSUE TITLE
Adding Postgis rasters from DB Manager ask for password for each add

### ISSUE THREAD

**Issue by mazingaro** [qgis/QGIS#31162] opened 2019-08-08 08:34 UTC
In QGIS 3.4 (I tested 3.4.8 and 3.4.10 in Ubuntu 18.4), when adding Postgis rasters to canvas (Add to Canvas) from DB Manager there is a prompt for user credentials (of the database) for each add. It simply ignores the keyring and it asks for credentials stating "Couldn't establish a database connection".

**Comment by gioman** [comment] 2019-08-08 15:42
possibly related to https://github.com/qgis/QGIS/issues/30392 ?

**Comment by mazingaro** [comment] 2019-08-09 10:40
Yes, i is the same issue as in the second part of the thread. I missed it.

Cheers,
Alen

**Comment by strk** [comment] 2019-09-17 10:00
Closing as duplicate of  #30392 - as per last comment

**Closed by strk** 2019-09-17 10:00 UTC
Labels: Bug
