### ISSUE TITLE
QGIS Desktop 3.30 on Mac crashes when Scale is clicked in status bar

### ISSUE THREAD

**Issue by sarahandrews** [qgis/QGIS#52820] opened 2023-04-21 17:23 UTC
### What is the bug or the crash?

With a basic map open, clicking the Scale drop down in the bottom bar causes immediate crash.

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 447e8d717a

### Steps to reproduce the issue

1. On Mac, open a project
2. Click the drop down arrow on the Scale in the status bar
3. App crashes

### Versions

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 447e8d717a
-- | -- | -- | --

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[447e8d717a](https://github.com/qgis/QGIS/commit/447e8d717a)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment] 2023-04-21 17:44
Duplicate of #52580

**Closed by YoannQDQ** 2023-04-21 17:44 UTC
Labels: Bug
