### ISSUE TITLE
QGIS 3.10 Rotation Tool

### ISSUE THREAD

**Issue by jridout1234** [qgis/QGIS#32872] opened 2019-11-14 18:44 UTC
The rotation tool in the advanced digitizing toolbar causes QGIS 3.10 to freeze after clicking to accept a rotation.  QGIS doesn't recover and needs to force quit.

Windows 10

**Comment by roya0045** [comment] 2019-11-14 19:00
Duplicate of #32123

**Closed** 2019-11-14 19:13 UTC
Labels: Bug
