### ISSUE TITLE
Snapping not possible in new project with new layer

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [qgis/QGIS#32969] opened 2019-11-20 12:31 UTC
When opening a new project and adding an existing or creating a new layer, it is not possible to snap to existing features while digitizing, no matter which snapping options are chosen.

The only way to get snapping activated is saving the project and restarting QGIS.

QGIS version | 3.11.0-Master | QGIS code revision | 129165a100
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Linux Mint 19.2 | This copy of QGIS writes debugging output.
Active python plugins | joinmultiplelines; OSMDownloader; quick_map_services; qNote; processing_saga; QNEAT3; processing_r; MemoryLayerSaver; refFunctions; ClusterPoints; db_manager; processing

**Comment by gioman** [comment] 2019-11-20 15:21
I just tested on master on a clean Windows installation and I can't confirm.

**Comment by denchat** [comment] 2019-12-30 14:50
Confirm this #33553 

**QGIS and OS versions**
3.11.0-43 (OSGeo4W) 64-bit 578f32a9b6
Windows 10 64-bit

```
QGIS version 3.11.0-Master
Compiled against Qt 5.11.2
Compiled against GDAL/OGR 3.1.0dev
Compiled against GEOS 3.8.0-CAPI-1.13.1
Compiled against SQLite 3.29.0
PostgreSQL Client Version 11.5
QWT Version 6.1.3
Compiled against PROJ 6.3.0
OS Version Windows 10 (10.0)
QGIS code revision 578f32a9b6
Running against Qt 5.11.2
Running against GDAL/OGR 3.1.0dev
Running against SQLite 3.29.0
SpatiaLite Version 4.3.0
QScintilla2 Version 2.10.8
Running against PROJ Rel. 6.3.0, January 1st, 2020
This copy of QGIS writes debugging output.
```

**Comment by denchat** [comment] 2019-12-30 16:00
It affects only
- memory layers
- newly created layers
- all zero-counted feature layers  this case there is a workaround by "unzeroing" (create a feature and reopen project)

**Comment by denchat** [comment] 2020-01-02 09:24
@gioman I can confirm that complete purging the user folder
`%AppData%\QGIS`
or a fresh installation on the machine both fixes this issue.

*** Or just renaming old `QGIS` folder is better. This way you can always restore to retrieve what you forget. ***

I guess this can be closed in some degree.

Anyway I'm not sure taking this workaround is the way to go. Because there will be most users migrate directly from `v3.10.1` to `v3.11.0` on the next three weeks. I'm not sure this will affect how much proportion of users.

**Comment by denchat** [comment] 2020-01-03 16:21
@gioman 
> I just tested on master on a clean Windows installation and I can't confirm.

Follow these steps to see whether you can reproduce with fresh installation:-
1. New project
2. Create 2 polygon memory layers
3. Turn on snapping all layers
4. See whether both layers can snap to one another.

**Comment by gioman** [comment] 2020-01-03 16:41
> See whether both layers can snap to one another.

they do, I have tested on 3.10.1 (not master) on Linux.

**Comment by denchat** [comment] 2020-01-03 18:08
@gioman 
> they do, I have tested on 3.10.1 (not master) on Linux.

If you still have access to master on a clean Windows installation, please try it again with those 2 memory layers.

**Comment by gioman** [comment] 2020-01-03 18:45
> If you still have access to master on a clean Windows installation, please try it again with those 2 memory layers.

@denchat it works as expected.

**Comment by denchat** [comment] 2020-01-04 04:22
@gioman 
> it works as expected.

Other than `%APPDATA%\QGIS`, where else can I delete remnants of previous installed QGIS to simulate a fresh installation?

**Comment by denchat** [comment] 2020-01-13 20:37
@gioman Please test this file to see whether or not node tools and snapping tools work on memory layers?

[test.zip](https://github.com/qgis/QGIS/files/4055655/test.zip)

**Comment by gioman** [comment] 2020-01-14 17:23
> @gioman Please test this file to see whether or not node tools and snapping tools work on memory layers?

@denchat works as expected. Please not that in the project you attached snapping was *not* active.

**Comment by denchat** [comment] 2020-01-19 11:34
OSGeo4W QGIS 3.11.0-59 Nightly seem not to have this issue.

You may close this.

**Comment by troopa81** [comment] 2020-01-20 08:22
Duplicate of #33449

**Closed by troopa81** 2020-01-20 08:22 UTC
Labels: Bug, Digitizing, Feedback
