### ISSUE TITLE
[Processing] 'Extract Layer Extent' as batch process does not recognize open raster layers

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#30739] opened 2019-07-16 09:05 UTC
**Bug Description**

Processing 'Extract Layer Extent' algorithm generates a new vector layer with the minimum bounding box that covers the input layer, both vector or raster layer.

![Extract_Layer_Extent](https://user-images.githubusercontent.com/1331581/61280746-572a8d80-a7b0-11e9-999b-e255d4ec250f.jpg)

However, running it as batch process, the option 'Select from Open Layers' only show vector layers. 

![Extract_Layer_Extent_batch](https://user-images.githubusercontent.com/1331581/61280765-5c87d800-a7b0-11e9-8ce8-91113656652e.jpg)

Using 'Select Files' or 'Select Directory', it picks raster layers as expected, and works fine.

So, the problem is only in the Multiple Selection window, that only shows vector layers from the Open Layers.

**QGIS and OS versions**

QGIS version 3.8.0-Zanzibar
Compiled against Qt 5.11.2
Compiled against GDAL/OGR 2.4.1
Compiled against GEOS 3.7.2-CAPI-1.11.0
PostgreSQL Client Version 9.2.4
QWT Version 6.1.3
Compiled against PROJ 5.2.0
This copy of QGIS writes debugging output.
OS Version Windows 10 (10.0)

**Comment by gioman** [comment] 2019-07-16 10:07
@PedroVenancio is this a regression?

**Comment by PedroVenancio** [comment] 2019-07-16 10:46
Hi @gioman 

I'm not sure, because this algorithm comes from the fusion of two old algorithms, "polygon from vector extent" and "polygon from raster extent". 

So, this issue in batch mode may have been inherited from these two different approaches.

**Comment by AlexanderAllan** [comment] 2019-08-06 16:45
At 3.8.1, it seems that when using QgsProcessingParameterMapLayer as single input parameter, you can select vector or raster in single use mode, but when switched to batch, the raster has disappears from the  'Select from open Layers' dialog.  You can navigate using 'select files' but this adds an extra step, finding that data again.

A previous bug in 3.8.0 meant that due to a problems in the wrappers.py it wouldn't pick up anything in batch mode, now fixed at 3.8.1 thankfully-  but it looks like elsewhere there is an issue with raster layers getting picked up in batch mode.  Note when using QgsProcessingParameterRasterLayer, rasters are correctly picked up in batch mode but I want to limit my parameters to make it simple for the user.

I see similar case that appears to be closed so I'm wondering if this will this be fixed or is being worked on?

**Closed** 2019-08-06 23:58 UTC
Labels: Bug, Feedback, Processing
