### ISSUE TITLE
Crash when accessing Layer Properties.

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#39720] opened 2020-10-30 15:47 UTC
## User Feedback

Attempting to access the Layer's properties. Just prior, I had created/closed a rather complex 3D View (4096px texture resolution, 4096px terrain resolution).

Data are being loaded from an exFAT-formatted USB Drive.

## Report Details

**Crash ID**: [db8a2b70acc598fff216f84778581531565fe631](https://github.com/qgis/QGIS/search?q=db8a2b70acc598fff216f84778581531565fe631&type=Issues)

**Stack Trace**
<pre>
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QDialog::setVisible :
QgisApp::showLayerProperties qgisapp.cpp:15943
QgisApp::layerProperties qgisapp.cpp:9163
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:170
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment] 2020-10-30 15:49
@Saijin-Naib duplicate of https://github.com/qgis/QGIS/issues/39693 and https://github.com/qgis/QGIS/issues/39692 ?

**Comment by Saijin-Naib** [comment] 2020-10-30 15:53
> @Saijin-Naib duplicate of #39693 and #39692 ?

It seems like similar behavior. I can't read the Stack Trace well enough to say either way.

Your call on whether to close this as dupe or not.

**Comment by Saijin-Naib** [comment] 2020-10-30 15:59
## User Feedback

Right-clicked layer to access properties, with having had success numerous times prior in the same session.

## Report Details

**Crash ID**: [c6ea636e34135bb899f8096fa2230d55a232295c](https://github.com/qgis/QGIS/search?q=c6ea636e34135bb899f8096fa2230d55a232295c&type=Issues)


**Stack Trace**
<pre>
QObject::isWidgetType :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QDialog::setVisible :
QgisApp::showLayerProperties qgisapp.cpp:15943
QgisApp::layerProperties qgisapp.cpp:9163
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent qgslayertreeview.cpp:170
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by roya0045** [comment] 2020-10-31 13:37
I assume your QGIS install is in english?

**Comment by Saijin-Naib** [comment] 2020-10-31 13:40
> I assume your QGIS install is in english?

yes, en_us, installed via OSGeo4W upgrade from older versions

**Comment by roya0045** [comment] 2020-10-31 13:44
Just trying to see if its language specific or just unrelated from the tr function...

**Comment by gioman** [comment] 2020-11-03 09:30
> Right-clicked layer to access properties, with having had success numerous times prior in the same session.

is the same as https://github.com/qgis/QGIS/issues/39692#issuecomment-718870927

**Closed by gioman** 2020-11-03 09:30 UTC
Labels: Bug, Feedback
