### ISSUE TITLE
GDAL is not at latest stable (3.1.x) when bundled in binary installers

### ISSUE THREAD

**Issue by bjornharrtell** [qgis/QGIS#37384] opened 2020-06-24 14:21 UTC
Seems to be stuck at GDAL 3.0.4 for fx. Windows binary dists (both network and standalone installer) while GDAL 3.1.0 was released May 7.

Disclaimer: As the author of FlatGeobuf I have a self interest in this issue in that GDAL 3.1 is the minimum requirement to enable support for FlatGeobuf in QGIS and it would be sad if that will not happen any time soon for what I guess is one of the most common ways of installing and using QGIS.

**Comment by agiudiceandrea** [comment] 2020-06-24 21:46
See also http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-gdal-3-1-in-OSGeo4W-QGIS-3-14-td5438599.html

**Comment by bjornharrtell** [comment] 2020-07-22 11:47
Seems to be multiple bugs related to this and GDAL 3.1 was it even mentioned as far back as in the QGIS 3.10 changelog (https://www.qgis.org/en/site/forusers/visualchangelog310/index.html#feature-read-write-support-for-shz-and-shp-zip) as a requirement for some features. I'm not aware of any explanation or blocker for why QGIS is still using GDAL 3.0.x where applicable, can anyone provide any enlightenment?

**Comment by jef-n** [comment] 2020-07-22 12:25
proj-data of proj7 is 500MB - which is too huge for the the standalone NSIS installer (which is also why the weekly standalone fail to build).

**Comment by bjornharrtell** [comment] 2020-07-22 14:09
Not sure I follow here. proj7 is not a requirement of GDAL 3.1. I'm not even sure GDAL 3.1 supports proj7 as it is mainly tested against proj6.

**Comment by rouault** [comment] 2020-07-22 16:18
> I'm not even sure GDAL 3.1 supports proj7 as it is mainly tested against proj6.

GDAL doesn't care much about proj7 vs proj6 differences as they are implementation details from its point of view. One of the CI conf of GDAL tests against PROJ 7.0 branch

**Comment by nyalldawson** [comment] 2020-07-22 18:54
@jef-n couldn't we remove proj-data as a dependency for qgis? It's not mandatory, and we should have enough warnings in the application itself to prompt users to manually download grids when required. (We could possibly then make a seperate installer with just these to make it easy for users to install all grids in one go...)

**Comment by bjornharrtell** [comment] 2020-07-22 20:45
I don't understand why PROJ upgrade is discussed in relation to GDAL upgrade (or blocking it even?), at least for 3.0.x to 3.1.x. Unless I'm mistaken QGIS stable is at PROJ 6 which is what GDAL 3.1 is more commonly used and tested with.

**Comment by jef-n** [comment] 2020-07-23 17:09
Because I want to update both - the nightlies are using gdal and proj master already for quite some time.  But proj-data breaks the NSIS installer - which IMHO is ok for the weekly, but skipping the release standalones is is not an option (to many at least - I never really understood what the advantage of a heavy standalone is).  And I don't want to completely skip it as it contains stuff that was previously shipped with QGIS and so skipping it might break some things.  But AFAIK there is no - non-biased - way to split it either.  I was hoping we would adopt the automatic downloading of grids, but that's apparently not going to happen.   But as I didn't find the time to do it or at least dig into it, I'm not complaining.  We could however do standalones without proj-data - but that's kludgy too.

**Comment by nyalldawson** [comment] 2020-07-23 18:29
@jef-n so what's the solution moving forward? Seems like the issue is in the nsis installer... Maybe we need to look seriously at alternatives like an MSI package, which would also avoid the ongoing virus scanner issues with nirsoft. 🤔

**Comment by bjornharrtell** [comment] 2020-07-23 19:03
Still failing to see why (a more involved) upgrade for PROJ should hold back the GDAL upgrade that fixes several known issues and required for features announced as far back as QGIS 3.10.

**Comment by rouault** [comment] 2020-07-23 19:11
An interim solution, pending a better one, could be to ship PROJ 7.1 with the "old" proj-datumgrid-1.8 package. Not the ideal solution, but should work.

**Comment by peetw** [comment] 2020-07-24 07:24
Excuse my ignorance on the matter, but to somewhat echo @bjornharrtell , I'm curious as to why GDAL can't be updated to 3.1, if not for QGIS 3.10, then at least for QGIS 3.14, given that those releases are still using PROJ 6, not PROJ 7 (as far as I'm aware)?

**Comment by alexhass** [comment] 2020-07-29 14:21
I was asked to install this software, but AD deployment is not possible with suxxx NSIS. Would you guys accept an MSI installer based on WiX? Where is the current installer code located?

**Comment by bjornharrtell** [comment] 2020-09-17 12:06
@nyalldawson and @jef-n I'm unsure about the status of this issue. Specifically, is a GDAL upgrade planned for windows installers in next QGIS release (3.15?) or next LTS release (3.16?) ?. Is there anything I can do to help?

**Comment by jef-n** [comment] 2020-09-17 13:47
There won't be a 3.15 release.

**Comment by bjornharrtell** [comment] 2020-09-17 14:15
@jef-n ok, I may be misunderstanding your roadmap or the status at the front page:
![image](https://user-images.githubusercontent.com/141030/93483217-e5445b80-f900-11ea-9375-2486f6211c89.png)

Anyway, what about 3.16 then?

**Comment by jef-n** [comment] 2020-09-17 16:30
odd minor versions are for the development versions (in master), even for the release branches.

**Comment by peetw** [comment] 2020-09-19 13:52
> Anyway, what about 3.16 then?

Since GDAL 3.1 has been incorporated into the master branch, I would assume the answer is "yes"? Unless I've misunderstood the branching workflow (quite possible 😄)

Is there any chance that GDAL 3.1 can be backported into the existing QGIS LTR (3.10), given that GDAL 3.1 fixes a number of fairly serious, known issues? That would be really appreciated by our organisation (and others I'm sure!) since QGIS 3.16 won't become the new LTR until 2021-02-19 (according to the [QGIS Roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html) at least).

**Comment by jef-n** [comment] 2020-09-19 22:11
QGIS works with various GDAL version - but it's doesn't include it.   Which version is used depends on the platform.   When GDAL enters OSGeo4W all version of QGIS in it will be rebuilt to use it.  On other platforms like Debian/Ubuntu it depends on which version those have - which varies on the versions of the distribution - some have 3.1.

**Comment by nyalldawson** [comment] 2020-09-19 22:21
We should close this -- it's not a qgis bug.

**Closed by nyalldawson** 2020-09-19 22:21 UTC
Labels: Feature Request

**Comment by peetw** [comment] 2020-09-20 09:44
@jef-n Thank you for the update/clarification - much appreciated. I was aware that QGIS/GDAL were packaged separately for OSGeo4W, but wasn't sure what the process was for the standalone installers.

WRT to replacing the current NSIS installer with an MSI-based one, I do have some experience building MSI installers using WiX, so if there's anything I can do, I'd be happy to help 👍

> BTW QGIS 3.16 becomes LTR on release. We normally build the current release, the current LTR release and master. As there's not much value in building a version twice, we built the previous LTR release, when the current release is also a LTR release. So once a new version is released that is not LTR, the current LTR takes the previous LTR release's place.

Indeed, but as far as I'm aware, the `qgis-ltr` package in OSGeo4W won't point to 3.16 until 3.18 is released, which means that organisations that require the use of `qgis-ltr` effectively have to wait an additional 4 months before they can use 3.16.

**Comment by jef-n** [comment] 2020-09-20 21:36
> WRT to replacing the current NSIS installer with an MSI-based one, I do have some experience building MSI installers using WiX, so if there's anything I can do, I'd be happy to help +1

That's probably already done in #38102 (except for the artwork).

> Indeed, but as far as I'm aware, the `qgis-ltr` package in OSGeo4W won't point to 3.16 until 3.18 is released, which means that organisations that require the use of `qgis-ltr` (instead of `qgis`) effectively have to wait an additional 4 months before they can use 3.16.

They choose to wait for 4 months, if they require `qgis-ltr`.  Except for the 4 months worth of fixes, there's no difference between 3.16 as `qgis` and `qgis-ltr`

**Comment by idanmiara** [comment] 2020-09-26 18:51
@jef-n 
> That's probably already done in #38102 (except for the artwork).
I see that #38102 is stale. 
Is the current plan to complete #38102 and to include the latest stable Proj and GDAL in QGIS 3.16 by using MSI to allow including complete proj-data?
Thanks!

**Comment by jef-n** [comment] 2020-09-27 21:54
sure.
