### ISSUE TITLE
3.22 crashes on loading a geological quadrangle shapefile directory; 3.10-does not

### ISSUE THREAD

**Issue by GeoJMac** [qgis/QGIS#49257] opened 2022-07-06 20:56 UTC
### What is the bug or the crash?

[OGQ-71_Broken_Arrow_24K.zip](https://github.com/qgis/QGIS/files/9057926/OGQ-71_Broken_Arrow_24K.zip)

Loaded to a new project - crashes after window to select shapefile layers appears

Crash ID: [e9b03e629dc3eef38f4301b06ea939c8a5e0aa23](https://github.com/qgis/QGIS/search?q=e9b03e629dc3eef38f4301b06ea939c8a5e0aa23&type=Issues)

Stack Trace

tiledb_serialize_group_metadata :
tiledb_serialize_group_metadata :
tiledb_serialize_group_metadata :
tiledb_serialize_group_metadata :
tiledb_serialize_group_metadata :
tiledb_ctx_alloc :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
QgsArcGisRestUtils::parseEsriPictureMarkerSymbolJson :
QgsRasterIdentifyResult::params :
QgsProviderRegistry::querySublayers :
QgsProviderSublayerTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Load the attached directory in a new 3.22 project and watch it crash immediately

Loads fin in 3.10

[OGQ-71_Broken_Arrow_24K.zip](https://github.com/qgis/QGIS/files/9057953/OGQ-71_Broken_Arrow_24K.zip)
y

### Versions

QGIS Info
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-07-07 06:21
Can't reproduce on 3.22.8 and 3.26.0 using OSGeo4W

**Comment by agiudiceandrea** [comment] 2022-07-07 13:29
@nicogodet it seems the issue is cause by the tiledb.dll library loaded by GDAL.
This happens if QGIS 3.22.8 was installed using the previous (QGIS-OSGeo4W-3.22.8-3.msi) OSGeo4W Standalone Installer or using the OSGeo4W Network Installer before Jul the 1st without updating subsequently.
I can reproduce the same issue in such situation.
The issue doesn't occur if QGIS is installed using the latest (QGIS-OSGeo4W-3.22.8-4.msi) OSGeo4W Standalone Installer or using the OSGeo4W Network Installer just updating all the package to the latest version.

**Comment by nyalldawson** [comment] 2022-07-11 01:38
Closing as fixed upstream (in newer QGIS installer)

**Closed by nyalldawson** 2022-07-11 01:38 UTC
Labels: Bug, Crash/Data Corruption
