### ISSUE TITLE
assistant.exe does not exists

### ISSUE THREAD

**Issue by tonyrsutton** [qgis/QGIS#49183] opened 2022-06-28 12:55 UTC
### What is the bug or the crash?

Help file assistant.exe does not exist when you try to open it up

### Steps to reproduce the issue

Launch via shortcut - "Qt Designer with QGIS 3.26.0 custom widgets" and create a new Project

Go to Help -> Qt Designer Help (and also Current Widget Help)

Observe error message

```
---------------------------
Assistant
---------------------------
The binary 'C:/PROGRA~1/QGIS32~1.0/apps/qt5/bin/bin\assistant.exe' does not exist.
---------------------------
OK   
---------------------------
```

### Versions

Qt Designer 5.15.3 (came with QGIS Desktop 3.26.0)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I have checked C:\Program Files\QGIS 3.26.0\apps\qt5\bin directory and the file do exist.

I think it's because of the incorrect forward/backward slash of the path (see error message)

**Comment by agiudiceandrea** [comment] 2022-06-29 07:29
@tonyrsutton, this is an OSGeo4W specific issue which should be reported in the OSGeo4W [trac ](https://trac.osgeo.org/osgeo4w/) system.
The issue is due to the `/bin/bin/` part of the path, while it should be only `/bin/`. If you create a `bin` subfolder into the `C:\Program Files\QGIS 3.26.0\apps\qt5\bin\` directory and copy the `assistant.exe` into it, then the Qt Designer Help assistant will start.

**Comment by agiudiceandrea** [comment] 2022-07-22 06:13
This issue is fixed now in OSGeo4W with qt5-libs package version 5.15.3-3. The fix will also be available in the next coming OSGeo4W Standalone Installers.
See https://trac.osgeo.org/osgeo4w/ticket/756, https://github.com/jef-n/OSGeo4W/commit/e83454ee55b69a8c91021c67f0d51b5491ec7da9.

**Closed** 2022-07-22 06:59 UTC
Labels: Downstream
