### ISSUE TITLE
Ubuntu 22.03.3 LTS // error while loading shared libraries: libpdal_base.so.13: cannot open shared object file

### ISSUE THREAD

**Issue by image80** [qgis/QGIS#55129] opened 2023-11-02 13:35 UTC
### What is the bug or the crash?
Seems to be similar to : https://github.com/qgis/QGIS/issues/52433

I work on **unbuntu** 22.04.03 LTS.
I succeed many weeks ago to install/use qgis Lima 3.32.2 on this station. 
But i was facing to several error message when i tried to install/use some plugins (dataPlotly, spectral library tools). 
Those  error messages dealed with error ModuleNotFoundError: No module named 'mock' or no module named panda...

So i decided to uninstall/reinstall qgis.
i would like to install the last release for ubuntu.

I make : 
sudo apt-get purge qgis
sudo apt update 
sudo apt install qgis qgis-plugin-grass

But i have this error message when i lauch qgis : 
`/usr/bin/qgis.bin: error while loading shared libraries: libpdal_base.so.13: cannot open shared object file: No such file or directory`

I paste the whole message when i make :
```
sudo apt-get purge qgis
sudo apt update
sudo apt install qgis qgis-plugin-grass
```

```
(base) xxxxxxx~$ sudo apt install qgis
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Paquets suggérés :
  gpsbabel
Paquets recommandés :
  qgis-plugin-grass
Les NOUVEAUX paquets suivants seront installés :
  qgis
0 mis à jour, 1 nouvellement installés, 0 à enlever et 1 non mis à jour.
2 partiellement installés ou enlevés.
Il est nécessaire de prendre 0 o/8 117 ko dans les archives.
Après cette opération, 11,1 Mo d'espace disque supplémentaires seront utilisés.
Sélection du paquet qgis précédemment désélectionné.
(Lecture de la base de données... 273453 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../qgis_1%3a3.34.0+36jammy_amd64.deb ...
Dépaquetage de qgis (1:3.34.0+36jammy) ...
Paramétrage de qgis-providers (1:3.34.0+36jammy) ...
/usr/lib/qgis/crssync: error while loading shared libraries: libpdal_base.so.13: cannot open shared object file: No such file or directory
dpkg: erreur de traitement du paquet qgis-providers (--configure) :
 installed qgis-providers package post-installation script subprocess returned error exit status 127
dpkg: des problèmes de dépendances empêchent la configuration de qgis :
 qgis dépend de qgis-providers (= 1:3.34.0+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de python3-qgis :
 python3-qgis dépend de qgis-providers (= 1:3.34.0+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.

dpkg: erreur de traitement du paquet python3-qgis (--configure) :
 problèmes de dépendances - laissé non configuré
Aucun rapport « apport » n'a été créé car le message d'erreur indique une erreur consécutive à un échec précédent.
                                                                                                                  Aucun rapport « apport » n'a été créé car le message d'erreur indique une erreur consécutive à un échec précédent.
                                                                        Traitement des actions différées (« triggers ») pour shared-mime-info (2.1-2) ...
Traitement des actions différées (« triggers ») pour mailcap (3.70+nmu1ubuntu1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.26-1ubuntu3) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.10.2-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 qgis-providers
 qgis
 python3-qgis
E: Sub-process /usr/bin/dpkg returned an error code (1)

For information, i share below the content of file located under /etc/apt/sources.list.d/qgis.sources:

```
Types: deb deb-src
URIs: https://qgis.org/debian
Suites: jammy
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
```


### Steps to reproduce the issue

1.sudo apt-get purge qgis
2.sudo apt update 
3.sudo apt install qgis qgis-plugin-grass

### Versions

Types: deb deb-src
URIs: https://qgis.org/debian
Suites: jammy


### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by image80** [comment] 2023-11-03 10:27
I paste the whole message when i make :
```
sudo apt-get purge qgis
sudo apt update
sudo apt install qgis qgis-plugin-grass
```

```
(base) xxxxxxx~$ sudo apt install qgis
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Paquets suggérés :
  gpsbabel
Paquets recommandés :
  qgis-plugin-grass
Les NOUVEAUX paquets suivants seront installés :
  qgis
0 mis à jour, 1 nouvellement installés, 0 à enlever et 1 non mis à jour.
2 partiellement installés ou enlevés.
Il est nécessaire de prendre 0 o/8 117 ko dans les archives.
Après cette opération, 11,1 Mo d'espace disque supplémentaires seront utilisés.
Sélection du paquet qgis précédemment désélectionné.
(Lecture de la base de données... 273453 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../qgis_1%3a3.34.0+36jammy_amd64.deb ...
Dépaquetage de qgis (1:3.34.0+36jammy) ...
Paramétrage de qgis-providers (1:3.34.0+36jammy) ...
/usr/lib/qgis/crssync: error while loading shared libraries: libpdal_base.so.13: cannot open shared object file: No such file or directory
dpkg: erreur de traitement du paquet qgis-providers (--configure) :
 installed qgis-providers package post-installation script subprocess returned error exit status 127
dpkg: des problèmes de dépendances empêchent la configuration de qgis :
 qgis dépend de qgis-providers (= 1:3.34.0+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de python3-qgis :
 python3-qgis dépend de qgis-providers (= 1:3.34.0+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.

dpkg: erreur de traitement du paquet python3-qgis (--configure) :
 problèmes de dépendances - laissé non configuré
Aucun rapport « apport » n'a été créé car le message d'erreur indique une erreur consécutive à un échec précédent.
                                                                                                                  Aucun rapport « apport » n'a été créé car le message d'erreur indique une erreur consécutive à un échec précédent.
                                                                        Traitement des actions différées (« triggers ») pour shared-mime-info (2.1-2) ...
Traitement des actions différées (« triggers ») pour mailcap (3.70+nmu1ubuntu1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.26-1ubuntu3) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.10.2-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 qgis-providers
 qgis
 python3-qgis
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by maxfagotto** [comment] 2023-11-03 11:09
With this Ubuntu version libpdal_base.so.15 is available, try to run "locate libpdal_base.so". For me:
/usr/lib/libpdal_base.so
/usr/lib/libpdal_base.so.15
/usr/lib/libpdal_base.so.15.0.0
So libpdal_base.so.13 is not found

**Comment by image80** [comment] 2023-11-03 11:13
Thanks for your help. on my side, when i type 
(base) xxxxxx@xxxxxxxxxxxx:~$ locate libpdal_base.so
/usr/lib/libpdal_base.so.15
/usr/lib/libpdal_base.so.15.0.0

**Comment by jef-n** [comment] 2024-02-09 13:04
duplicate of #52433

**Closed by jef-n** 2024-02-09 13:04 UTC
Labels: Packaging, Build/Install, Bug, Linux
