### ISSUE TITLE
IDW Interpolation in processing doesn't accept manual changes in extent

### ISSUE THREAD

**Issue by glaroc** [qgis/QGIS#32997] opened 2019-11-21 15:51 UTC
In the IDW Interpolation dialog, it is possible to select the extent of the output raster by selecting on the canvas. However, after selecting on the canvas, it seems like the user cannot make manual changes to the extent from the Extent form element. The changes appear to be ignored. It is thus impossible to create a raster that has a exact desired pixel resolution. 

**How to Reproduce**
1. Go to the IDW interpolation dialog in processing. 
2. Use select extent on canvas to define the extent of the output raster
3. Manually change the extent by, for example, removing decimals or trying to adjust the extent to obtain a fixed desired pixel resolution. 
4. Proceed with the interpolation and verify the raster extents and resolutions in the layer properties. They won't correspond to what was set in step 3. 

**QGIS and OS versions**

3.10 on all platforms

**Comment by alexbruy** [comment] 2020-01-21 16:27
What do you mean by "user cannot make manual changes to the extent from the Extent form element"?
Just tested and if I reduce extent manually these values are used to create output.

**Comment by glaroc** [comment] 2020-01-21 17:12
I mean that if you start by selecting an area on the canvas to give you an approximate extent, and then you try to play with the numbers for extent, rows, columns and resolution to try to obtain an EXACT resolution of your choice, you won't be able to do it, as the ouput rasters' properties won't match the ones that you specify.

**Comment by gioman** [comment] 2020-01-21 17:13
> I mean that if you start by selecting an area on the canvas to give you an approximate extent, and then you try to play with the numbers for extent, rows, columns and resolution to try to obtain an EXACT resolution of your choice, you won't be able to do it, as the ouput rasters' properties won't match the ones that you specify

So this would be a feature request, I guess.

**Comment by alexbruy** [comment] 2020-01-21 17:15
Well then it is not about "cannot make manual changes to the extent". Looks like duplicate of #31970.

**Comment by glaroc** [comment] 2020-01-21 17:21
Technically you can make manual changes to the extent, but they won't be matched in the output, so that's one and the same.

**Closed** 2020-01-21 17:23 UTC
Labels: Bug, Feedback, Processing
