### ISSUE TITLE
QGIS response time issue, unusable software within a company

### ISSUE THREAD

**Issue by AliciaSdn** [qgis/QGIS#52978] opened 2023-05-02 21:55 UTC
### What is the bug or the crash?

Hello, following a general malfunction issue with the QGIS software during professional use (territorial community), I am contacting you for assistance in debugging this problem.
Multiple versions of QGIS are being used, including version 3.28 LTR, 3.22.5, and 3.10. The problem occurs in all three versions on PCs using a Windows operating system. It affects 15 staff members in the company, who work in the fields of natural resource management and protection, for example.

The problem encountered is as follows:
When the staff members work remotely (outside of the company's premises) from their work laptops, the response time of QGIS (opening the basic software, loading a QGIS project, or any other interaction with the user interface, such as opening a drop-down menu) is excessively long and renders the software unusable. This problem, which seems to affect the general functioning of QGIS, occurs:

    - When the staff member connects to an external internet network (for example, a WiFi box or a connection to a telephone network)
    - On work laptops: the staff members connect to their machines using their work Windows session
    - When the staff member uses QGIS projects whose data sources come from various locations: PostGIS database (PostgreSQL 9.6 on a locally hosted LINUX server), NAS disk, and flat files on their personal computer. However, the slowing down of QGIS occurs before loading a project, at the software launch level.

Tests have identified that the problem is not present when:

    - The laptop is put "offline," without an internet connection
    - The laptop is connected to the company's Active Directory domain (the company does not have a VPN)
    - One connects to the laptop from an AD administration Windows session
    - The staff member uses only QGIS projects whose data has been stored locally (on their personal external hard drive).

The problem seems to be located around the Internet network/user session Windows/QGIS/data source interaction.
In the logs, no information is displayed in the QGIS debugging/development tool. At startup, there is a long response time at "Show main window."

Tests have been conducted by creating a new user from a QGIS session: the session opened with the new user crashes, and the associated Windows logs are attached.

How can this problem be debugged ? Is there a QGIS configuration file (startup.py?) that could be causing interference and creating this problem ?

Thank you in advance for your assistance.
Best regards,
Alicia Sedani
[logs.pdf](https://github.com/qgis/QGIS/files/11377956/logs.pdf)

### Steps to reproduce the issue

    1. Professional Windows user authentication
    2. Internet connection through a phone's tethering
    3. Launching QGIS from an .exe file
    4. "QGIS not responding" error message or long waiting time

### Versions

3.28, 3.22.5, 3.10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment] 2023-05-02 23:38
Duplicate of #51710

You may be interested in the workaround described in https://github.com/qgis/QGIS/issues/33164#issuecomment-708651902

**Closed by YoannQDQ** 2023-05-02 23:38 UTC
Labels: Bug

**Comment by Klaus-PVA** [comment] 2023-05-03 07:30
Closing the Browser Panel helped me. And in the Datasource-Manager dont click on the Browser Symbol.
