### ISSUE TITLE
Atlas generation/Print Layout should respect EXIF image orientation

### ISSUE THREAD

**Issue by ocurious** [qgis/QGIS#38611] opened 2020-09-05 14:22 UTC
When using Print Layout/Atlas generation in, exif corrected orientation of images placed using the Picture tool is ignored. I've attached an image to show Atlas generated images. You can see some images with landscape view, when it should be portrait.

These images where initially captured in landscape, and the image orientation was corrected using Windows Photos app. This orientation appears to be respected in some photo editing applications (e.g IrfanView, but not Libre Office Draw) and thumbnails in Windows Explorer show the corrected image rotation.

I believe this is a bug, because the image orientation has been edited in a user-typical manner and the Atlas/Layout editor should recognise that.

I have seen this issue raised and closed, but I do not think the issue was addressed. 

To reproduce the issue
- take a landscape photo (iphone in this case),
- on PC using Windows Photos app rotate image to Portrait orientation. 
- Place the image in a Print Layout, orientation will NOT be portrait

Windows 10
QGIS version  3.10.9-A Coruña
QGIS code revision
bf47e9d3e1

![explorer_Ra8unbCnX3](https://user-images.githubusercontent.com/5725356/92306213-ba890780-efd0-11ea-94de-3db4ec71b068.png)

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by nicogodet** [comment] 2021-03-24 13:29
On 3.16.5 and 3.18.1, it seems that picture are always displayed in landscape even if the original picture was taken in portrait.

![image](https://user-images.githubusercontent.com/39594821/112318276-2866f900-8cad-11eb-9796-898366fa3987.png)

**Comment by andreasneumann** [comment] 2021-03-24 13:37
@nicogodet - did this work previously in QGIS? If yes, please indicate the version where it worked. If not, then it is not a bug, but a feature request.

I totally agree with you that it would be desirable that QGIS would honor the image orientation tag, btw. But we treat bugs (regressions) different than feature requests ...

**Comment by nicogodet** [comment] 2021-03-24 13:50
Same behavior on 2.18.17

Exif metadata are correct
![image](https://user-images.githubusercontent.com/39594821/112321374-3a966680-8cb0-11eb-84f8-f01aa286a443.png)

So feature request...

**Comment by nicogodet** [comment] 2021-03-24 14:05
I'm quite surprised that this was not implemented earlier

**Comment by andreasneumann** [comment] 2021-03-24 14:33
> I'm quite surprised that this was not implemented earlier

Things don't happen "magically". It always needs someone to do the work or contract with someone else to do the work. Once done, it is shared with everybody.

In this case it seems it never seemed important enough for someone to take the initiative.

Note that by opening this feature request, it won't be implemented automagically either, unless someone does it or contracts someone to do the work. It is different with bug reports. Bug reports, esp. the ones that trigger a crash or data corruption are usually addressed if they can be reproduced and fixed.

See also http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ and http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis-a-follow-up/

Feature requests are still welcome though, as they might trigger someone's interest and it can also be discussed with others - and if you contract with someone to do the implementation work for you, you can reference such a feature request.

**Closed** 2021-09-27 22:57 UTC
Labels: Feature Request, Print Layouts
