### ISSUE TITLE
Cannot create New (GRASS GIS) Mapset

### ISSUE THREAD

**Issue by NikosAlexandris** [qgis/QGIS#32323] opened 2019-10-19 18:32 UTC
### Steps to reproduce:

1. Load the GRASS(7) plugin
2. Through the Plugins (menu) > GRASS > New Mapset

The (QGIS) program ends up not responding.

### Report Details

*Crash ID*: aa1782169d7106ee74da471dbb5d764ca8270d8d

*Stack Trace*
```
RtlRaiseStatus :
RtlUnwindEx :
_longjmp_internal :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
QgsGrassNewMapset::setGrassProjection qgsgrassnewmapset.cpp:474
QgsGrassNewMapset::pageSelected qgsgrassnewmapset.cpp:1395
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
```

*QGIS Info*
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by NikosAlexandris** [comment] 2019-10-19 18:33
Installation via the https://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe installer.

**Comment by gioman** [comment] 2019-10-20 16:12
Duplicate of https://github.com/qgis/QGIS/issues/28148

**Closed by gioman** 2019-10-20 16:12 UTC
Labels: Bug
