### ISSUE TITLE
OGC API Features client always use limit=1000

### ISSUE THREAD

**Issue by armin11** [qgis/QGIS#38666] opened 2020-09-09 15:58 UTC
normally you can define maxfeatures and features per page when configuring the wfs connection. when you alter the values in the configuration, the request should also be adopted, but in case of ogc api features, the limit parameter is always 1000. this is problematic if the server has very big objects and may only allow less than 1000 with one request. 

**QGIS and OS versions**

qgis 3.14.1-Pi - debian 10

**Comment by rouault** [comment] 2020-09-14 14:33
I can't replicate. Can you describe exactly the procedure you follow ? 
Here's mine:
I've tried with https://services.interactive-instruments.de/t15/daraa
In the WFS connection window, I click "Autodetect". It sets a page size of 1000. Then I change this to 2, validate. And add the layer "Hydrography (surfaces"). Enabling QGIS_DEBUG=5 traces, I can see request with limit=2 being emitted.
If I also set the "Max. number of features" setting to 4, only 4 features are retrieved

**Comment by armin11** [comment] 2020-09-15 12:02
hi rouault,

thanx for the feedback, maybe the problem will be, that i use 3.14.1-Pi. our ogc api features interfaces are here:

https://www.geoportal.rlp.de/spatial-objects/

maybe you can test a point layer:
https://www.geoportal.rlp.de/spatial-objects/542
and a polygon layer:
https://www.geoportal.rlp.de/spatial-objects/557

both work under 3.14.1 but with the limit=1000 as it is stated in the debugging/development tools request table.
i should update to 3.14.15 i think ;-)

best regards from germany,
armin

**Comment by rouault** [comment] 2020-09-15 14:18
I've tried with QGIS master and https://www.geoportal.rlp.de/spatial-objects/542 , and if I override the page size to 10, it is properly honored.
However I'd note that this end point has several non conformities to the spec.

**Comment by armin11** [comment] 2020-09-16 06:58
hi rouault,

can you give me some hints to remove the non-conformities? - i developed the proxy last year but i mostly look for the functionality for the f=html variant.

thanx in advance ;-)

armin

**Comment by rouault** [comment] 2020-09-16 08:18
> can you give me some hints to remove the non-conformities?

Goes a bit beyond my mandate, but here a few ones:
- curl -v https://www.geoportal.rlp.de/spatial-objects/542 -H "Accept: application/json"   returns "Content-Type: application/vnd.geo+json" header, whereas it should just be "Content-Type: application/json"
- it is arguable that the landing page https://www.geoportal.rlp.de/spatial-objects/542 contains a collections[] array. This should rather be only in https://www.geoportal.rlp.de/spatial-objects/542/collections, but I guess this is OK
- similarly "https://www.geoportal.rlp.de/spatial-objects/542/collections/ms:windenergieanlagen_rlp_an" returns a  "Content-Type: application/json" and the GeoJSON items, whereas it should be just the metadata of the collection. It particularly lacks the "extent" member.  "collectionId", "collectionName", "collectionTitle" should probably be respectively "id", "title", "description"
I'd suggest you do an extensive review of https://docs.opengeospatial.org/is/17-069r3/17-069r3.html

**Comment by armin11** [comment] 2020-09-16 08:53
hi even,

thanx a lot - i will do an extensive review of the spec, when i get time . for the first implementation i looked at the ldproxy of clemens portele (https://www.ldproxy.nrw.de/) and try to reverse engineer it in simple way ;-) .
it may become better the next weeks.

for the future we will migrate to https://pygeoapi.io/ cause our new backend is based on python and django:

https://git.osgeo.org/gitea/GDI-RP/MrMap

best regards from germany,

armin

**Comment by rouault** [comment] 2020-09-16 09:15
Closing as I can't reproduce an issue on the QGIS side.

**Closed by rouault** 2020-09-16 09:15 UTC
Labels: Bug, Data Provider, Feedback
