### ISSUE TITLE
QGIS ends unexpectedly with every minor operation. 

### ISSUE THREAD

**Issue by AAronsson19** [qgis/QGIS#34811] opened 2020-03-02 02:01 UTC
Copy of crash report below.

QGIS ends expectantly with any minor operation. 

If I start a new session and select "Save As", It crashes. (this operation caused the below error report). 

If I open an existing file and drag and drop a shapefile into the workspace, QGIS crashes. 

The only operation I can do without it crashing is zooming in and out. Ever other QGIS operation available, if I select it, it causes QGIS to crash. 

Crash ID: 686598fe74bb163b78e42796f10664e214f48368

Stack Trace

RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
ICoCreateInstanceEx objact.cxx:1397
CComActivator::DoCreateInstance immact.hxx:343
CoCreateInstanceEx actapi.cxx:175
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgisApp::fileSaveAs :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment] 2020-03-02 12:02
>  QGIS Version: 3.4.12-Madeira

@AAronsson19 too old, upgrade to 3.10.3, if the problem persist please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by AAronsson19** [comment] 2020-03-02 22:20
Thank you gioman for your feedback! Downloaded the latest version and same issue happened again. Wondering if it could be McAfee blocking it in the background or something else that triggers a crash?
Ideas?

**Comment by AAronsson19** [comment] 2020-03-02 22:21
Crash ID: 686598fe74bb163b78e42796f10664e214f48368


Stack Trace


RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
ICoCreateInstanceEx objact.cxx:1397
CComActivator::DoCreateInstance immact.hxx:343
CoCreateInstanceEx actapi.cxx:175
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getSaveFileUrl :
QFileDialog::getSaveFileName :
QgisApp::fileSaveAs qgisapp.cpp:6466
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1607
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.3-A Coru�a
QGIS code revision: 0e1f846438
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment] 2020-03-02 22:22
Making sure that the program is not blacklisted by anything is usually a good first step. This would also mean that the problem might not come from QGIS if such is the case.

**Comment by roya0045** [comment] 2020-03-29 13:58
@AAronsson19 is it fine now? Have you found the issue?

**Comment by roya0045** [comment] 2020-04-01 22:34
duplicate of #34891 #34880 and #32239

**Comment by gioman** [comment] 2020-04-02 10:36
closing as duplicate.

**Closed by gioman** 2020-04-02 10:36 UTC
Labels: Bug, Feedback
