### ISSUE TITLE
QGIS-server 3.X tiles wrong clipped

### ISSUE THREAD

**Issue by Abelon38** [qgis/QGIS#33078] opened 2019-11-26 10:33 UTC
Hi guys!

I am using QGIS server 3.10. I have a problem when creating a WMTS från a WMS. The  generated tiles shows as they where wrong clipped. Take a look att the image bellow.

![image](https://user-images.githubusercontent.com/12575941/69622003-6d8b0480-1040-11ea-8fce-ce996e5c67ff.png)

Thanks for any help!
Abel

**Comment by gioman** [comment] 2019-11-26 10:43
> QGIS server 3.10

is a regression (works ok on 3.4?)? On what platform?

**Comment by rldhont** [comment] 2019-11-26 11:08
It is not wrong clipped. The QGIS Server does not wait for all remote images to return rendered image.

**Comment by rldhont** [comment] 2019-11-26 11:15
It is the same in 3.4.*

**Comment by rldhont** [comment] 2019-11-26 11:16
We need a renderer that waits for all layer rendered.

**Comment by Abelon38** [comment] 2019-11-26 17:54
Hi! 

This happens even with QGIS 3.4 LTR. I have tested on Windows server 2012-2016. Is there a way to fix this issue or is QGIS server 3.x not ready yet for WMTS?

Thanks a lot for your time!

BR/Abel

**Comment by elpaso** [comment] 2019-11-27 08:11
@rldhont is that caused by the multi-threaded downloader in WMS (xyz) provider?

**Comment by rldhont** [comment] 2019-11-27 08:16
@elpaso I think so

**Comment by nyalldawson** [comment] 2019-11-27 08:36
I think this is a server only issue -- the provider works fine in a blocking way when printing layouts for instance

**Comment by Abelon38** [comment] 2019-11-27 15:35
Hi there!
Elpaso is right, WMS is working fine. The problem is only with SERVICES=WMTS.

BR/Abel

**Comment by elpaso** [comment] 2019-11-27 15:40
@Abelon38 would you mind sharing a project that we can test with?

**Comment by Abelon38** [comment] 2019-11-28 13:27
Hi Elpaso!

I will share the projekt later today. Now i see that the problem is related to JPEG format and not to PNG. I get it working with WMS från OSM the, tile version.. 

I will be back with the project soon. Thansk for your help!

Br/Abel

**Comment by Abelon38** [comment] 2019-11-28 14:54
Hi!

Here comes the qgs-project. You will be able to reproduce the issue when calling the projects WMTS in jpeg format. 
[bing.zip](https://github.com/qgis/QGIS/files/3902169/bing.zip)

Best regards!
Abel

**Comment by elpaso** [comment] 2019-11-28 15:30
No issues here when I configure the layer tiles to 256x256.

**Comment by Abelon38** [comment] 2019-11-28 17:55
Hi Elpaso!

I tested adjusting the tile sizwe and I get the sam result. take alook at the picture. Plese note the the issue is when using JPEG format.
![image](https://user-images.githubusercontent.com/12575941/69825748-9b26a800-1210-11ea-9245-cf88ab67dd67.png)

Br/Abel

**Comment by elpaso** [comment] 2019-11-28 18:04
Sorry, I cannot reproduce it. How is your server configuration?

**Comment by Abelon38** [comment] 2019-11-28 18:13
Hi!

Do you mean the Project configution? Does it work for you if choos WMTS and jpeg format? 

This my WMTS request to get my projects tiles: http://osmap.sokigo.com:16000/cgi-bin/qgis_mapserv.fcgi.exe?&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities&MAP=/qgisprojekt/bing/bing.qgs

**Comment by gioman** [comment] 2019-11-28 18:14
> This my WMTS request to get my projects tiles: http://osmap.sokigo.com:16000/cgi-bin/qgis_mapserv.fcgi.exe?&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities&MAP=/qgisprojekt/bing/bing.qgs

so a Windows server. Have you tried on a Linux one?

**Comment by Abelon38** [comment] 2019-11-28 18:23
Hi, no I havent tried yet, but the thing is that my clients use to use Windows environment. 
So, this problem is fixed on Linus ?

Regards, Abel

**Comment by gioman** [comment] 2019-11-28 21:14
> So, this problem is fixed on Linus ?

@Abelon38 
no issues here using linuS ;) http://95.216.164.220/cgi-bin/qgis_mapserv.fcgi?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities&MAP=/var/www/html/bing.qgs

**Comment by rldhont** [comment] 2019-11-29 10:43
@gioman @Abelon38 @elpaso We have encountered this issue on Debian with a low connection...

**Comment by Abelon38** [comment] 2019-11-29 12:52
Hi Gioman!

You WMTS link works super fast and well! Do you think this issue may have something to do with Apache modules configuration?  is that possible for you to send a list of those modules you have anabled on your Apache? 

Too bad I can not use Linux environment in my company, so I really need to find a solution to this issue.
Best regards!
Abel

**Comment by rldhont** [comment] 2020-01-08 09:47
I have produced some logs:
```
../src/core/qgsmessagelog.cpp:29 : (logMessage) [3ms] 2020-01-08T10:09:52 Server[0] ******************** New request ***************
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] SERVER_NAMEqgis-server.localhost
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] REQUEST_URI/cgi-bin/qgis_mapserv.fcgi
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] REMOTE_ADDR::1
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] CONTENT_TYPEapplication/x-www-form-urlencoded
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] HTTP_USER_AGENTTest
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 [1] Warning: error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 [1] formatString is: image/jpeg
../src/server/qgsserver.cpp:157 : (configPath) [0ms] MAP:/srv/qgis/projects/test-wmts-layer-rendering.qgs
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 wfsOutputExtension[0] WFSFilter.requestReady
../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2020-01-08T10:09:52 Server[0] BBOX:955016.249513,6716861.049191,962054.180256,6723898.979934
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] CRS:EPSG:2154
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] DPI:96
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] EXCEPTIONS:application/vnd.ogc.se_inimage
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] FORMAT:image/jpeg
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] HEIGHT:266
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] LAYERS:WMTSLayer
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] MAP:/srv/qgis/projects/test-wmts-layer-rendering.qgs
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] REQUEST:GetMap
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] SERVICE:WMS
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] STYLES:default
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:09:52 Server[0] VERSION:1.3.0
../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2020-01-08T10:09:52 Server[0] WIDTH:266../src/core/qgsmessagelog.cpp:29 : (logMessage) [69ms] 2020-01-08T10:40:19 Server[0] WMS Request parameters:
../src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] 2020-01-08T10:40:19 Server[0]  - CRS : EPSG:2154
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - WIDTH : 266
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - HEIGHT : 266
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - BBOX : 955016.249513,6716861.049191,962054.180256,6723898.979934
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - LAYERS : WMTSLayer
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - STYLES : default
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - FORMAT : image/jpeg
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - DPI : 96
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0]  - VERSION : 1.3.0
../src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] 2020-01-08T10:40:19 server[0] Parallel rendering deactivated
../src/core/qgsellipsoidutils.cpp:114 : (ellipsoidParameters) [2ms] setEllipsoid: no row in tbl_ellipsoid for acronym ''
../src/providers/wms/qgswmsprovider.cpp:108 : (QgsWmsProvider) [1ms] constructing with uri 'contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/jpeg&layers=ortho&password=*********&styles=default&tileMatrixSet=EPSG:3857&url=https://my-wmts-server.test?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities&username=admin'.
../src/providers/wms/qgswmscapabilities.cpp:40 : (parseUri) [0ms] uriString = contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/jpeg&layers=ortho&password=*********&styles=default&tileMatrixSet=EPSG:3857&url=https://my-wmts-server.test?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities&username=admin
../src/providers/wms/qgswmscapabilities.cpp:86 : (parseUri) [0ms] mBaseUrl = https://my-wmts-server.test?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities
../src/providers/wms/qgswmscapabilities.cpp:98 : (parseUri) [1ms] Entering: layers:ortho, styles:default
../src/providers/wms/qgswmscapabilities.cpp:101 : (parseUri) [0ms] Setting image encoding to image/jpeg.
../src/providers/wms/qgswmscapabilities.cpp:151 : (parseUri) [0ms] Contextual legend: 0
../src/providers/wms/qgswmsprovider.cpp:314 : (addLayers) [0ms] Entering: layers:ortho, styles:default
../src/providers/wms/qgswmsprovider.cpp:326 : (addLayers) [0ms] set visibility of layer 'ortho' to true.
../src/providers/wms/qgswmsprovider.cpp:335 : (addLayers) [0ms] Exiting.
../src/providers/wms/qgswmsprovider.cpp:1172 : (retrieveServerCapabilities) [0ms] entering: forceRefresh=0
../src/providers/wms/qgswmsprovider.cpp:1197 : (retrieveServerCapabilities) [0ms] exiting.
../src/providers/wms/qgswmsprovider.cpp:395 : (setImageCrs) [0ms] Setting image CRS to EPSG:3857.
../src/providers/wms/qgswmsprovider.cpp:411 : (setImageCrs) [0ms] mTileLayersSupported.size() = 2
../src/providers/wms/qgswmsprovider.cpp:1559 : (calculateExtent) [0ms] Skip CRS:84 [EPSG:3857]
../src/providers/wms/qgswmsprovider.cpp:1578 : (calculateExtent) [0ms] ct: CRS:84 => EPSG:3857
../src/providers/wms/qgswmsprovider.cpp:1598 : (calculateExtent) [0ms] exiting with '591523.9442027567420155,5975091.7832376919686794 : 767085.9131328298244625,6115443.5334146982058883'.
../src/providers/wms/qgswmsprovider.cpp:169 : (QgsWmsProvider) [0ms] exiting constructor.
../src/providers/wms/qgswmsprovider.cpp:1655 : (capabilities) [1ms] Tiled.
../src/providers/wms/qgswmsprovider.cpp:1688 : (capabilities) [0ms] capability = 0
../src/providers/wms/qgswmsprovider.cpp:1559 : (calculateExtent) [0ms] Skip CRS:84 [EPSG:3857]
../src/providers/wms/qgswmsprovider.cpp:1578 : (calculateExtent) [0ms] ct: CRS:84 => EPSG:3857
../src/providers/wms/qgswmsprovider.cpp:1598 : (calculateExtent) [0ms] exiting with '591523.9442027567420155,5975091.7832376919686794 : 767085.9131328298244625,6115443.5334146982058883'.
../src/providers/wms/qgswmsprovider.cpp:1655 : (capabilities) [1ms] Tiled.
../src/providers/wms/qgswmsprovider.cpp:1688 : (capabilities) [0ms] capability = 0
../src/providers/wms/qgswmsprovider.cpp:620 : (draw) [0ms] Trying to draw a WMS image on the main thread. Stop it!
../src/providers/wms/qgswmsprovider.cpp:697 : (draw) [0ms] layer extent: 591523.94420275674201548,5975091.78323769196867943 175562x140352
../src/providers/wms/qgswmsprovider.cpp:705 : (draw) [0ms] view extent: 710716.22480838361661881,6023615.69700725562870502 11800.6x11836.9  res:43.868479
../src/providers/wms/qgswmsprovider.cpp:712 : (draw) [0ms] tile matrix -2.00375e+7,2.00375e+7 res:38.2185 tilesize:256x256 matrixsize:4096x4096 id:12
../src/providers/wms/qgswmsprovider.cpp:729 : (draw) [0ms] tile number: 2x2 = 4
../src/providers/wms/qgswmsprovider.cpp:1085 : (createTileRequestsWMTS) [0ms] tileRequest 1 0/4 (1431,2120): https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1431&TILECOL=2120
../src/providers/wms/qgswmsprovider.cpp:1085 : (createTileRequestsWMTS) [0ms] tileRequest 1 1/4 (1431,2121): https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1431&TILECOL=2121
../src/providers/wms/qgswmsprovider.cpp:1085 : (createTileRequestsWMTS) [0ms] tileRequest 1 2/4 (1432,2120): https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1432&TILECOL=2120
../src/providers/wms/qgswmsprovider.cpp:1085 : (createTileRequestsWMTS) [0ms] tileRequest 1 3/4 (1432,2121): https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1432&TILECOL=2121
../src/providers/wms/qgswmsprovider.cpp:3828 : (tileReplyFinished) [151ms] expirationDate:
../src/providers/wms/qgswmsprovider.cpp:3851 : (tileReplyFinished) [1ms] tile reply 1 (1) tile:1(retry 0) rect:714227.592297,6036690.745850 724011.531917,6026906.806229) fromcache:0  url:https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1431&TILECOL=2121
../src/providers/wms/qgswmsprovider.cpp:3896 : (tileReplyFinished) [0ms] contentType: image/jpeg
../src/providers/wms/qgswmsprovider.cpp:3944 : (tileReplyFinished) [0ms] tile reply: length 38055
../src/providers/wms/qgswmsprovider.cpp:3828 : (tileReplyFinished) [36ms] expirationDate:
../src/providers/wms/qgswmsprovider.cpp:3851 : (tileReplyFinished) [0ms] tile reply 1 (1) tile:3(retry 0) rect:714227.592297,6026906.806229 724011.531917,6017122.866609) fromcache:0 error: Error transferring https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1432&TILECOL=2121 - server replied: Internal jelix error url:https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1432&TILECOL=2121
../src/providers/wms/qgswmsprovider.cpp:3828 : (tileReplyFinished) [36ms] expirationDate:
../src/providers/wms/qgswmsprovider.cpp:3851 : (tileReplyFinished) [0ms] tile reply 1 (1) tile:0(retry 0) rect:704443.652676,6036690.745850 714227.592297,6026906.806229) fromcache:0  url:https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1431&TILECOL=2120
../src/providers/wms/qgswmsprovider.cpp:3896 : (tileReplyFinished) [0ms] contentType: image/jpeg
../src/providers/wms/qgswmsprovider.cpp:3944 : (tileReplyFinished) [0ms] tile reply: length 36407
../src/providers/wms/qgswmsprovider.cpp:3828 : (tileReplyFinished) [12ms] expirationDate:
../src/providers/wms/qgswmsprovider.cpp:3851 : (tileReplyFinished) [0ms] tile reply 1 (1) tile:2(retry 0) rect:704443.652676,6026906.806229 714227.592297,6017122.866609) fromcache:0  url:https://my-wmts-server.test?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ortho&STYLE=default&FORMAT=image/jpeg&TILEMATRIXSET=EPSG:3857&TILEMATRIX=12&TILEROW=1432&TILECOL=2120
../src/providers/wms/qgswmsprovider.cpp:3896 : (tileReplyFinished) [0ms] contentType: image/jpeg
../src/providers/wms/qgswmsprovider.cpp:3944 : (tileReplyFinished) [0ms] tile reply: length 33185
../src/providers/wms/qgswmsprovider.cpp:876 : (draw) [4ms] TILE CACHE total: 3 / 256
../src/providers/wms/qgswmsprovider.cpp:902 : (readBlock) [0ms] image height = 270 bytesPerLine = 1076
../src/core/qgsmaprenderercustompainterjob.cpp:338 : (drawLabeling) [40ms] Draw labeling took (seconds): 0
../src/providers/wms/qgswmsprovider.cpp:197 : (~QgsWmsProvider) [0ms] deconstructing.
../src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] 2020-01-08T10:40:19 wfsOutputExtension[0] WFSFilter.responseComplete
../src/server/qgsserverfilter.cpp:42 : (responseComplete) [0ms] QgsServerFilter plugin default responseComplete called
../src/server/qgsserverfilter.cpp:42 : (responseComplete) [0ms] QgsServerFilter plugin default responseComplete called
../src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] 2020-01-08T10:40:19 Server[0] Request finished in 1455 ms
```

I have used a WMTS layer and we can see that to draw the image I need 4 tiles and only 3 retruns image/jpg. The one failed has no retry.

**Comment by Pedro-Murteira** [comment] 2022-04-26 11:09
@Abelon38 Hello, is this issue still valid on recent releases?

**Comment by sweco-seabgo** [comment] 2022-05-11 06:42
Hi! I think this issue is fixed on new QGIS versions. Thanks a lot!

Regards, Abel

**Closed** 2022-05-11 09:36 UTC
Labels: Feedback, Bug, Server
