### ISSUE TITLE
Crash when turning on bounding boxes for layer styling for point cloud

### ISSUE THREAD

**Issue by PeterBrodersen** [qgis/QGIS#49203] opened 2022-06-30 09:47 UTC
## User Feedback

I turned on bounding boxes for a layer styling for 3D View for a point cloud

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00004118 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

1. Open a 3D view for a point cloud
2. Go to Layer Styling for the point cloud
3. Click 3D View tab
4. Click "Show bounding boxes" checkbox at the bottom

The crash is repeatable here and only happens when the 3D view is active. If it is not active there is no crash.

Data source is point cloud `PUNKTSKY_1km_6174_726` from [Dataforsyningen](https://dataforsyningen.dk/data/3931)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AddressToolsDK | 0.1
Datafordeler | 1.2
Dataforsyningen | 0.3
debug_vs | 0.7
geosearch_dk | 1.2.0
JSONEater | 0.3
Kortforsyningen | 2.9
MagneticDeclination | 2.3.1
plugin_reloader | 0.9.1
qgis-maptiler-plugin | 3.0.3
QuickOSM | 2.0.1
QuickWKT | 3.1
sparqlunicorn | 0.12.2
timemanager | 3.6
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AddressToolsDK
0.1
Datafordeler
1.2
Dataforsyningen
0.3
debug_vs
0.7
geosearch_dk
1.2.0
JSONEater
0.3
Kortforsyningen
2.9
MagneticDeclination
2.3.1
plugin_reloader
0.9.1
qgis-maptiler-plugin
3.0.3
QuickOSM
2.0.1
QuickWKT
3.1
sparqlunicorn
0.12.2
timemanager
3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by wonder-sk** [comment] 2022-08-15 09:29
Looks like a duplicate of https://github.com/qgis/QGIS/issues/47409

**Closed by wonder-sk** 2022-08-15 09:29 UTC
Labels: 3D, Bug, Crash/Data Corruption, Point Clouds
