### ISSUE TITLE
"custom crs definition" Press OK - does not work

### ISSUE THREAD

**Issue by jazzoom** [qgis/QGIS#33038] opened 2019-11-23 19:28 UTC
Hi,

I follow instructions to create [something similar to Joy Divisions Cover](https://cartographicperspectives.org/index.php/journal/article/view/1536/1726) . In this process there is a step of PCS (projected coordinate system).

 In "Сustom Coordinate Reference System Definition" window:
1. I filled data in_ "Define"
Name: CLNP_sinus_w122
Parameters: +proj=sinu +lon_0=-122.1492 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs
2. I filled data in "Test" and tested it. Pressed "Calculate" and it worked as I expected.
3.  So I clicked OK -- Nothing happens. Window did not close.

![screen](https://user-images.githubusercontent.com/58082506/69484127-334f1680-0e38-11ea-843c-c925d298b379.jpg)

So  I  went to Project -> Properties  where in CRS  my "CLNP msinus w122"  had to appear. And it did not.

So Custom CRS Adding does not work.

I use Windows 7, QGIS 3.8.1 .

**Comment by nyalldawson** [comment] 2019-11-25 06:46
I can't reproduce on either proj 4 or 6 based builds. Please re-test with QGIS 3.10

**Comment by jazzoom** [comment] 2019-11-25 18:55
> I can't reproduce on either proj 4 or 6 based builds. Please re-test with QGIS 3.10

Nyal, thanks for reply.
I installed QGIS 3.10

And now QGIS interacts in some other way. I filled the same date and Press "Calculate"  -- QGIS shows "Error". I aslo presse "OK"
![screen2](https://user-images.githubusercontent.com/58082506/69568964-5bb84b80-0fc5-11ea-8411-9d4003b56448.jpg)

I  also checked to Project -> Properties where in CRS my "CLNP sinus w122" had to appear. And it did not.
It does not work.

**Comment by jazzoom** [comment] 2019-12-05 12:18
Nyal, thanks for reply.
I installed QGIS 3.10

And now QGIS interacts in some other way. I filled the same data and Press
"Calculate" -- QGIS shows "Error". I aslo presse "OK"
[image: qgis-issue.jpg]

I also checked to Project -> Properties where in CRS my "CLNP sinus w122"
had to appear. And it did not.
It does not work.

Help me, please

Have a nice day,
Rodion

пн, 25 лист. 2019 о 08:46 Nyall Dawson <notifications@github.com> пише:

**Comment by npvl** [comment] 2019-12-15 15:42
I confirm, that OK button doesn't work and therefore there is no way to add custom coordinate reference system definition, however I can test it in that window.
QGIS version: 3.10.1-A Coruña
Revision: ef24c526da

The same behavior occurs in QGIS-OSGeo4W-3.10.0-1-Setup-x86_64.exe, QGIS-OSGeo4W-3.8.3-1-Setup-x86_64.exe and QGIS-OSGeo4W-3.4.14-1-Setup-x86_64.exe.

OS: Windows Server 2012 (build 9200) 64-bit

**Comment by nirvn** [comment] 2019-12-16 02:32
This will be fixed in the next point release (ie 3.10.2).

**Closed by nirvn** 2019-12-16 02:32 UTC
Labels: Bug, Projections/Transformations, Regression
