### ISSUE TITLE
Upscales window and crashes on exit 3.22

### ISSUE THREAD

**Issue by GeoJMac** [qgis/QGIS#49339] opened 2022-07-12 16:54 UTC
### What is the bug or the crash?

Cannot get QGIS to display other than large scale unreadable UI

[c75c55065a871141ec3af1daa567e663c18d58da](https://github.com/qgis/QGIS/search?q=c75c55065a871141ec3af1daa567e663c18d58da&type=Issues)

Stack Trace

PyInit_QtCore :
QObject::~QObject :
QMainWindow::`default constructor closure' :
QMainWindow::`default constructor closure' :
QApplication::~QApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.2.9200
![7-12-2022 10-27-43 AM](https://user-images.githubusercontent.com/86692679/178548916-7882e0ee-8ef9-4556-998b-c1c7a62bea9d.jpg)

Reinstalled 3.22 - no help

### Steps to reproduce the issue

Produces large unreadable UI upon starting

Only program on my computer to do this

![7-12-2022 10-27-43 AM](https://user-images.githubusercontent.com/86692679/178549320-90b49410-b353-46f4-a89c-9e92e1b77397.jpg)

### Versions

3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment] 2022-07-13 10:37
@GeoJMac can you still replicate this on a new profile?

**Comment by Pedro-Murteira** [comment] 2022-07-13 13:09
@GeoJMac Since it seems to be caused by a third-party plugin, we can close the issue.

**Closed by Pedro-Murteira** 2022-07-13 13:09 UTC
Labels: Feedback, GUI/UX, Bug, Crash/Data Corruption, Configs and Options

**Comment by GeoJMac** [comment] 2022-07-13 16:47
Thanks for your help. I changed my new profile to the default.
    On Wednesday, July 13, 2022, 08:09:43 AM CDT, pmurteira ***@***.***> wrote:  
 
 


@GeoJMac Since it seems to be caused by a third-party plugin, we can close the issue.
