### ISSUE TITLE
Raster calculator in Graphical Modeler Fails in Spanish, works in English

### ISSUE THREAD

**Issue by mudomau** [qgis/QGIS#33317] opened 2019-12-10 14:55 UTC
**Describe the bug**

I was trying to automatize a series of processing steps using the Graphical Modeler. The steps worked OK when performed one by one outside the graphical modeler, but when I tried to replicate them inside the modeler the raster calculator (final step) would return the following error: 

![imagen](https://user-images.githubusercontent.com/2564029/70540342-5df1dc80-1b65-11ea-8e22-9a034d2dab50.png)

The process is the following:
1) Calculate slope for a DEM
2) Calculate aspect for a DEM
3) Extract North-South slopes using the raster calculator with the expression: Slope*cos((3.141592/180)*Aspect)^2

After changing the locale to English_Canada and User Interface Translation to American English, the process works.

**How to Reproduce**

1) In QGIS 3.8 or 3.10, set locale to Spanish Spain and User interface translation to Español de España

2) Open Processing->Graphical Modeler

2) Create one raster layer input,

3) Calculate the Slope and Aspect of the input (using the default processing algorithms), then use the raster calculator to calculate any expression

This fails for as long as the language is set to spanish, for all expressions tried in the Raster calculator.

![imagen](https://user-images.githubusercontent.com/2564029/70540394-77932400-1b65-11ea-94e8-d15622bd9ce0.png)

**QGIS and OS versions**

Tested in Windows 10, QGIS 3.8 and 3.10

**Additional context**

**Comment by gioman** [comment] 2019-12-10 15:15
@mudomau duplicate of https://github.com/qgis/QGIS/issues/32753 ?

**Comment by elpaso** [comment] 2019-12-10 16:15
I've found the source of the issue and it's a translation problem.

I must say that the underlying implementation is extremely weak:  it relies on the fact that two strings in two different places of the code are translated exactly in the same way.

I'm checking if is there a way to make it more robust.

**Comment by elpaso** [comment] 2019-12-10 16:24
Our experienced developer @luipir has accepted the challenging task to fix this nasty bug, I'm happily passing it to him :)

btw, the offending commit is faf9716a52e (Luigi Pirelli      2018-07-21 17:28:40 +0100) and the source of the problem is in `modeler/ModelerParametersDialog.py:                return self.tr("'{0}' from algorithm '{1}` and `RasterCalculator.py:                translatedDesc = self.tr("Output '%1' from algorithm '%2'")`

The output name is constructed like `"'Aspect' from algorithm 'Aspect'"` and that string is later on translated back into something that the alg can understand as a raster reference `OUTPUT_Aspect@1`, this fails if the translation of the two strings does not match exactly.

**Comment by mudomau** [comment] 2019-12-11 08:45
@gioman It does seem to be the same issue. Glad it's been ID'd and someone's on it.

**Comment by gioman** [comment] 2019-12-11 09:04
> @gioman It does seem to be the same issue. Glad it's been ID'd and someone's on it.

closing as duplicate.

**Closed by gioman** 2019-12-11 09:04 UTC
Labels: Bug, Feedback

**Comment by luipir** [comment] 2019-12-11 15:56
the string self.tr("Output '%1' from algorithm '%2'") is not translated at all (result translatedDesc) is not translated :(
![Screenshot from 2019-12-11 16-50-22](https://user-images.githubusercontent.com/3344634/70636979-bf35b080-1c36-11ea-8026-86da22cd4358.png)

The code was aware of translation and would manage it... now checking why translation is not returned calling self.tr()... result should be "Salida '%1' del algoritmo '%2'"

**Comment by luipir** [comment] 2019-12-11 17:32
@mudomau moving comments to to https://github.com/qgis/QGIS/issues/32753
