### ISSUE TITLE
QGIS 3.8 crash when closing program

### ISSUE THREAD

**Issue by jmacura** [qgis/QGIS#31676] opened 2019-09-10 20:57 UTC
## Intro

As I search through the issues here, it looks like a recurring rotten bug (i.e #30494, #30753, #31474, #31465, #28104 etc.). It is randomly happening to me since 3.0 (see https://issues.qgis.org/issues/20806 or https://issues.qgis.org/issues/20511). I still believe it is a good habit to report the bug, even though it probably won't shine a new light onto the problem...

## User Feedback

I was just closing the QGIS window. But instead of quit, it reports crash...

## Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

## Additional Info
This bug seems really tricky, so I'd like to at least provide as much info as possible.
* The project I've been working on currently has 20 layers, 3 of them being WMS layers and 17 vector layers of various formats.
* I am working in EPSG:5514 CRS
* I have 20 plugins installed, 14 activated (Contour plugin, DB Manager, eVis, Geometry Checker, Georeferencer GDAL, GRASS 7, Metasearch Catalog Client, mmqgis, OpenLayers Plugin, OSMDownloader, Processing, Qgis2threejs, QNEAT3 and Topology Checker). Yet non of them was used during the session.

Not sure what else might help you.. I will share more info if you request it. Thanks!

**Comment by jef-n** [comment] 2019-09-11 06:43
Duplicate of #31465

**Closed by jef-n** 2019-09-11 06:43 UTC
Labels: Bug
