### ISSUE TITLE
Export to DXF issue in both 3.16 and 3.18 (after 3.10)

### ISSUE THREAD

**Issue by os-ai** [qgis/QGIS#42218] opened 2021-03-12 06:29 UTC
In version 3.18 - Export Project to DXF crashes (unable to load the selection window)

In version 3.16 - Export Project to DXF - Symbols do not appear identical. Unable to export multiple vectors that have different CRS's (eg. mix of WGS, pseudo-mercator and UTM)s, only the vectors with the same CRS as the output DXF CRS selected will appear. i.e. reprojecting error. This is reproducible.

In version 3.10.14 - Export Project to DXF works fine - reprojecting multiple CRS's works fine. Symbols in both QGIS and DXF appear the same.

_Originally posted by @tmcgill26 in https://github.com/qgis/QGIS/issues/39799#issuecomment-755275105_

**Comment by gioman** [comment] 2021-03-13 11:33
@os-ai the crash issue is duplicate of https://github.com/qgis/QGIS/issues/41858

**Comment by gioman** [comment] 2021-03-13 11:34
@os-ai and there are several reports about the export not being correct, see https://github.com/qgis/QGIS/labels/DXF%2FDWG

**Comment by os-ai** [comment] 2021-03-13 14:55
Thanks. I do see the other posts that have specific examples, but the CRS transformation error (the tool regression) when changing crs was not clearly mentioned. A number if issues/posts may have stemmed from this transformation failure. 
Made a link to #39799 that was closed.
Happy to close this if deemed a duplicate. Thanks

**Comment by AlisterH** [comment] 2021-06-03 02:56
I suggest closing this ticket in favour of the tickets that describe each issue separately: #41858 (crash in 3.18) and #43449 (reprojection failing in 3.16).

**Comment by nyalldawson** [comment] 2021-06-03 04:58
Closing as duplicate

**Closed by nyalldawson** 2021-06-03 04:58 UTC
Labels: Bug, DXF/DWG, Regression
