### ISSUE TITLE
Unable to input Chinese in the code editor

### ISSUE THREAD

**Issue by Schalal** [qgis/QGIS#53784] opened 2023-07-11 08:30 UTC
### What is the bug or the crash?

I can't input Chinese characters in the Field calculator or in the Python console code editor through Microsoft Chinese Pinyin Input after updating QGIS to 3.32.0 but I can paste Chinese characters into both. I think this is a bug.
![unable to input](https://github.com/qgis/QGIS/assets/52227792/6a7b358c-7398-42a3-9392-11665bd968b1)
![able to paste](https://github.com/qgis/QGIS/assets/52227792/2b140cb9-be48-4e33-bb72-2b4efe402bc1)

### Steps to reproduce the issue

1. Shift the input mothod to Microsoft Chinese Pinyin Input Method;
2. Open field calculator or Python console code editor;
3. Type some Chinese characters;
4. See error.

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a65
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
colorselector
0.1
color_conversion_preview
0.1
geohey_toolbox
0.4
MemoryLayerSaver
4.0.4
network_gt
1.0
OSMDownloader
1.0.3
qgis-maptiler-plugin
3.2
QGIS_DBToMap
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment] 2023-07-16 22:19
Duplicate of https://github.com/qgis/QGIS/issues/53427

**Closed by nyalldawson** 2023-07-16 22:19 UTC
Labels: Bug

**Comment by jef-n** [comment] 2023-09-11 09:53
https://trac.osgeo.org/osgeo4w/ticket/803
