### ISSUE TITLE
DBManager cannot execute a SQL query on a virtual table whose name begins with numbers 

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#30457] opened 2019-06-28 06:16 UTC
To reproduce:
Create a virtual table and give it a name starting with numbers
Make a SQL request on this virtual table in DBManager.
Error message: 
Query execution error on DROP TABLE IF EXISTS "2019_mytable"; CREATE VIRTUAL TABLE "2019_mytable" USING QgsVLayer(2019_mytable_55424896_8ff2_48d9_8424_0ab2361b6d04);: 1 - **unrecognized token**: "2019_mytable_55424896_8ff2_48d9_8424_0ab2361b6d04"

**Comment by elpaso** [comment] 2019-06-28 07:14
Quoting table identifier is probably required in this case.

**Comment by FERRATON** [comment] 2019-06-28 07:28
I forgot to mention that it doesn't work with quotation marks either.

**Comment by elpaso** [comment] 2019-06-28 07:38
I meant that the plugin python code should take care of the correct quoting, not the user.

**Comment by gioman** [comment] 2021-01-31 15:50
> I forgot to mention that it doesn't work with quotation marks either.

@FERRATON works here with quotes (QGIS master on Ubuntu 20.04) which is totally expected to me.

**Comment by FERRATON** [comment] 2021-02-01 09:00
I still see the issue (QGIS 3.16.0 windows 10)

**Comment by gioman** [comment] 2021-02-01 11:02
> QGIS 3.16.0

@FERRATON can you kindly add the exact steps to replicate? If possible also try on a updated version of QGIS, 3.16.0 is outdated. Thanks!

**Comment by FERRATON** [comment] 2021-02-17 10:23
create a virtual layer, whose name starts with numbers, from any table (see capture1)
make a simple query on this virtual layer in DBManager (see capture2)
QGIS 3.16.3 (windows 10)
![capture1](https://user-images.githubusercontent.com/2129643/108190618-7a4abb00-7112-11eb-8e39-3d85be7c0bcc.png)
![capture2](https://user-images.githubusercontent.com/2129643/108190623-7b7be800-7112-11eb-955c-63f9e7838af4.png)

**Comment by Jakob-Lanstorp** [comment] 2021-03-31 14:45
This problem, a table name starting with a number, used in a virtual layer query, also exists in QGIS 3.18.1

**Comment by Jakob-Lanstorp** [comment] 2021-06-24 06:45
Still a problem in Windows 10 - OSGEO QGIS 3.18.3-Zürich. Wrapping table name with quotation marks won't work, throwing an "1 - unreconized token ...", when making a virtual layer from a table starting with a number.  

It is the same using Python:

```
from qgis.core import QgsVectorLayer
vlayer = QgsVectorLayer( '?query=SELECT * from "8100_Paleogen_Kalk_Bund"', 'vlayer', 'virtual' )
QgsProject.instance().addMapLayer(vlayer)
```
throwing:

CRITICAL    Layer vlayer : Error while executing feature count request : Query preparation error on SELECT Count(*),Min(MbrMinX("")),Min(MbrMinY("")),Max(MbrMaxX("")),Max(MbrMaxY("")) FROM : incomplete input

**Comment by decheu** [comment] 2022-01-04 11:16
Still an issue on Windows 10 QGIS 3.16.11 OSGEO install

The query
```
SELECT "007_ABWASSERKNOTEN"."geometry" 
FROM "007_ABWASSERKNOTEN", "008__VORFLUTEREINLAUF"
WHERE "007_ABWASSERKNOTEN""007_ABWASSERKNOTEN"."GlobalId" = "008__VORFLUTEREINLAUF"."KNOTEN_REF"
```
results in 
```
Query execution error on DROP TABLE IF EXISTS "007_ABWASSERKNOTEN"; CREATE VIRTUAL TABLE "007_ABWASSERKNOTEN" USING QgsVLayer(004a_421dcb47_6093_40a3_b43f_d195c1bfdfaa);: 1 - unrecognized token: "004a_421dcb47_6093_40a3_b43f_d195c1bfdfaa"
```
As mentioned above, quotation marks (also suggested here: https://trac.osgeo.org/gdal/ticket/5738) don't help.

**Comment by lbartoletti** [comment] 2022-02-24 07:05
@FERRATON I cannot reproduce on QGIS 3.22

![image](https://user-images.githubusercontent.com/7521540/155474939-a80fe6cd-118e-467b-884f-f0243d8b78e1.png)


2012test is a virtual layer based on tic_cable via "SELECT * FROM tic_cable"

**Comment by Jakob-Lanstorp** [comment] 2022-02-24 07:29
Indeed this issue seems to be solved now. Cannot reproduce anymore on Windows 10 with OSGEO QGIS 3.22.3

**Comment by FERRATON** [comment] 2022-02-24 08:45
The issue is not resolved in QGIS 3.22.3 (package MSI - windows 10).

**Comment by lbartoletti** [comment] 2022-02-24 08:49
> The issue is not resolved in QGIS 3.22.3 (package MSI - windows 10).

Mmm it's weird, since @Jakob-Lanstorp said it's solved on Win10. The only difference is MSI vs OSGEO...

**Comment by gioman** [comment] 2022-02-24 09:37
Works fine on master/win10 (osgeo4w and standalone build from last commit).

**Comment by Jakob-Lanstorp** [comment] 2022-02-24 09:47
Had a colleague test it on a Win 10 MSI standalone QGIS 3.22.3 installation and it still fails there. But appear fixed in the OSGEO QGIS 3.22.3 version.

**Comment by gioman** [comment] 2022-02-24 11:17
> Had a colleague test it on a Win 10 MSI standalone QGIS 3.22.3 installation and it still fails there. But appear fixed in the OSGEO QGIS 3.22.3 version.

@Jakob-Lanstorp works fine here on standalone 3.22.4 msi

**Comment by FERRATON** [comment] 2022-02-24 15:57
no... if I give a name without numbers and with the same dataset
it works...

**Comment by lbartoletti** [comment] 2022-02-24 16:06
> Sorry! I correct... if you put the name between "" it works with QGIS 3.22 MSI or QGIS 3.22.4 osgeo4w

So, it's OK?

**Comment by FERRATON** [comment] 2022-02-24 17:23
Yes for me.

**Closed** 2022-02-24 18:07 UTC
Labels: Feedback, DB Manager, Bug

**Comment by kleenkanteen** [comment] 2023-11-20 00:51
Just happened to me, joining a .shp file and a .dbf file:

![image](https://github.com/qgis/QGIS/assets/67878058/ddc8a22f-3ee4-446c-8126-582a44c271c4)

QGIS version: 3.32.3-Lima

![image](https://github.com/qgis/QGIS/assets/67878058/97c8078d-08b2-4f36-88e6-d6a2de4cfc5f)

Latest version of w10
