### ISSUE TITLE
postgresql layer that worked in 3.18 does not work anymore in 3.20

### ISSUE THREAD

**Issue by beerockxs** [qgis/QGIS#44272] opened 2021-07-20 15:40 UTC
A custom SQL layer that worked just fine in version 3.18 stopped worked in 3.20.
I simplified the SQL a bit, it's as follows:
select 'bla' as test, ST_polygonfromtext(  'POLYGON((-1514025  2323008, 2326217 6188976, 6272585 6129712, 10008341 2170209, -1514025 2323008 ))', 3035) as geom
In 3.18 this worked fine, in 3.20 it works fine in DB Manager and the query executes, but when I try to Update the existing layer in the project or add it as a new layer, I get this message in the postgis log:

2021-07-20T17:38:14     WARNING    Erroneous query: SELECT 0, array_agg(DISTINCT st_srid("geom")::text || ':' || UPPER(geometrytype("geom")) || ':' || ST_Zmflag("geom")) FROM (SELECT "geom" from (SELECT "geom" FROM "(select 'bla' as test, ST_polygonfromtext( 'POLYGON((-1514025 2323008, 2326217 6188976, 6272585 6129712, 10008341 2170209, -1514025 2323008 ))', 3035) as geom
             ) AS ""subQuery_0""" WHERE "geom" IS NOT NULL LIMIT 100) AS t LIMIT 100) as _unused returned 7 [ERROR: relation "(select 'bla' as test, ST_polygonfromtext( 'POLYGON((-1514025 " does not exist
             LINE 1: ...")) FROM (SELECT "geom" from (SELECT "geom" FROM "(select '...
              ^
             ]
2021-07-20T17:38:14     WARNING    Invalid PostgreSQL layer

**Comment by jef-n** [comment] 2021-07-20 18:15
Duplicate of #43963

**Closed by jef-n** 2021-07-20 18:15 UTC
Labels: Bug
