### ISSUE TITLE
 QGIS 3.18 unable to open datasource postgresql even when the driver is in the list

### ISSUE THREAD

**Issue by Inrap** [qgis/QGIS#41862] opened 2021-02-26 13:45 UTC
**Intro**
From qgis 3.18, I try to import a shp in an existing postgis database (PostgreSQL 13, PostGIS 3.0), using Export to PostgreSQL (connexion available).

**Describe the bug**
Import failed cause 
> Unable to open datasource 'dbname='activite' with the following drivers

I checked with OSGEO4W installer that all gdal libs were installed.
Thus,I installed again the libpg with OSGEO4W as well and started the import.
Same message was returned and import failed even if the PostgreSQL driver is in the list of drivers .
![image](https://user-images.githubusercontent.com/32261793/109306861-10cc5a00-7840-11eb-8886-ebcb0fc39855.png)
 
**QGIS and OS versions**

Version de QGIS | 3.18.0-Zürich | Révision du code | bdef9fb328
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 3.1.4 | Utilisé avec GDAL/OGR | 3.1.4
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.29.0 | Fonctionne avec SQLite | 3.29.0
Version du client PostgreSQL | 11.5 | Version de SpatiaLite | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | Windows 10 (10.0)
Extensions Python actives | BezierEditing; DataPlotly; FeatureGridCreator; french_locator_filter; nominatim; openlayers_plugin; pointsamplingtool; QGeoloGIS; qgis_hats; qgis_resource_sharing; qNote; QuickOSM; SelectByRelationship; VectorBender; volume_calculation_tool; db_manager; MetaSearch; processing

Thanks

**Comment by gioman** [comment] 2021-02-26 14:37
duplicate of https://github.com/qgis/QGIS/issues/41839

**Closed by gioman** 2021-02-26 14:37 UTC
Labels: Bug
