### ISSUE TITLE
Qgis 3.16 crash when wanting to open Layer properties

### ISSUE THREAD

**Issue by rcoura54** [qgis/QGIS#39745] opened 2020-11-02 07:18 UTC
Hi there, 

I've got an issue when opening properties of raster files (*.TIF).

Qgis crashes/closes without any message, it just stops as soon as I am opening the "Properties" of raster (like to change Symbology of the raster or anything else).

-> Left-click on the raster layer -> right-click on "Properties" -> Qgis automatically crashes/stops/disappears 

Please note that :
1) No problems when this is about opening vector/shapefile properties 
2) That issue works for any raster / TIF file  
 
System features are : 
- Intel Xeon 3.6 GHz, 32 Go RAM, HDD 1 To
- Ubuntu 18.04.5 LTS, MATE 1.20
- Qgis 3.16 Hanover

How to repair that issue? I 

tried uninstalling/reinstalling Qgis 3.16 but it's still crashing.

Thanks in advance,

**Comment by Gustry** [comment] 2020-11-02 07:22
> tried uninstalling/reinstalling Qgis 3.16 but it's still crashing.

This is not enough.
As mentioned in the bug report template, you should try with a new QGIS profile.

**Comment by rcoura54** [comment] 2020-11-02 07:38
> > tried uninstalling/reinstalling Qgis 3.16 but it's still crashing.
> 
> This is not enough.
> As mentioned in the bug report template, you should try with a new QGIS profile.

@Gustry Unfortunately the same goes with a new QGIS profile.

Plus the issue appears even when I want to set the Parameters of QGIS (Menu bar -> Settings -> Options)

**Comment by gioman** [comment] 2020-11-03 08:26
> Ubuntu 18.04.5 LTS, MATE 1.20

@rcoura54 duplicate of https://github.com/qgis/QGIS/issues/39628

**Closed by gioman** 2020-11-03 08:26 UTC
Labels: Bug, Feedback

**Comment by samvedya** [comment] 2020-12-02 04:49
Hello,

I have a similar issue. The QGIS keeps on crashing when attempting to load a raster layer. I couldn't load a raster.

The version is 3.16.1 - Hannover on windows.
