### ISSUE TITLE
Vertex tool - Postgis Bug

### ISSUE THREAD

**Issue by Mariosmsk** [qgis/QGIS#30749] opened 2019-07-16 15:08 UTC
**Describe the bug**

![qgis_bug](https://user-images.githubusercontent.com/2945956/61305757-0c326980-a7f4-11e9-8bb9-cf1204201dcc.gif)

**How to Reproduce**

When I add layers from PostGIS DB using QTask then I have problem with vertex tool.

**QGIS and OS versions**

QGIS version
3.8.0-Zanzibar

**Additional context**

**Comment by gioman** [comment] 2019-07-16 16:02
it may be just me but I fail to understand the issue.

**Comment by mhugo** [comment] 2019-07-16 16:39
@gioman I think the problem is the geometry displayed by the vertex tool (in red) and the geometry displayed by the layer (in yellow) are not in sync

**Comment by nyalldawson** [comment] 2019-07-16 18:01
Sounds like you're adding layers in a background thread. This is a tricky thing, you need to ensure the letters are transferred correctly to the mein thread before adding to the project. It's not an issue though, it's a question for stackexchange or the developer list.

**Closed by nyalldawson** 2019-07-16 18:01 UTC
Labels: Bug, Digitizing
