### ISSUE TITLE
Interger overflow error creating raster layer unique values report

### ISSUE THREAD

**Issue by jecogeo** [qgis/QGIS#49819] opened 2022-08-17 14:52 UTC
### What is the bug or the crash?

Feature could not be written to C:/path/output.shp: Error converting value (21345402912) for attribute field count: Value "21345402912" is too large for integer field. Could not write feature into OUTPUT_TABLE
Execution failed after 586.70 seconds (9 minutes 47 seconds)

### Steps to reproduce the issue

1. Take the age of secondary vegetation for entire Brazil [here](https://onewri-my.sharepoint.com/:i:/g/personal/jefferson_ferreira_wri_org/EeV-vW1GsJ9FucKaruN7qXIB3wEzyYK-Wn2ubEPod7ryog?e=iAVNQf)
2. open Processing Toolbox > Raster Analysis > Raster layer unique values report
3. in the `unique values table [optional]` enter a file output
4. run

### Versions

QGIS version
3.24.1-Tisler
QGIS code revision
5709b824
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
ana_data_acquisition
1.0
cluz
2020.3.18
dados_censo
0.40
mapbiomascollection
1.4
OpenTopography-DEM-Downloader
1.0
OSMDownloader
1.0.3
pg_raster_import
1.0.10
PLUGIN
1.2.1
quick_map_services
0.19.29
searchlayers
3.0.7
SemiAutomaticClassificationPlugin
7.10.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

ALSO TESTED WITH

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
ana_data_acquisition
1.0
cluz
2020.3.18
dados_censo
0.40
mapbiomascollection
1.4
OpenTopography-DEM-Downloader
1.0
OSMDownloader
1.0.3
pg_raster_import
1.0.10
PLUGIN
1.2.1
quick_map_services
0.19.29
searchlayers
3.0.7
SemiAutomaticClassificationPlugin
7.10.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It seems to be related to #40503

**Comment by elpaso** [comment] 2022-09-22 09:24
The download doesn't complete for me, could you attach a smaller raster to reproduce the issue?

**Comment by agiudiceandrea** [comment] 2023-01-13 15:57
@jecogeo the provided link doesn't work. @elpaso the correct URL to download the raster layer is https://onewri-my.sharepoint.com/personal/jefferson_ferreira_wri_org/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjefferson%5Fferreira%5Fwri%5Forg%2FDocuments%2Fshare&ga=1

**Comment by agiudiceandrea** [comment] 2023-01-14 07:33
@jecogeo the resource is no longer accessible. Please provide a reliable resource.

**Comment by agiudiceandrea** [comment] 2023-01-15 09:32
@elpaso, I can provide two little zipped TIFF raster layers with which the algorithm fails.

It seems to me the issue is due to the fact that the "Unique values table" layer (whatever it is a temporary memory layer or ESRI Shapefile or Geopackage or ...) created by the algorithm has the "count" field of `int` \ `Integer` \ 32 bit type instead of Integer 64 bit type and it cannot correctly store values grater than 2147483647.

See attached: 

1) [example_47000_47000.zip](https://github.com/qgis/QGIS/files/10419828/example_47000_47000.zip) (226KB)
This layer contains 22090000 pixels of value 127.
The algorithm fails to create the "Unique values table" output layer if the output layer is a Temporary (memory) layer or if an ESRI Shapefile or Geopackage or other layer type are specified using the "Save to file" option with the following error:

```
Feature could not be written to Unique_values_table_2fa423a8_36e9_40a4_8a05_d95ee4a77708: Could not store attribute "count": Value "2209000000" is too large for integer field
Could not write feature into OUTPUT_TABLE
```

If an output GeoPackage layer is specified using the "Save to GeoPackage" option, the following output layer is generated but it contains incorrect values:

[output_table_47000x47000.zip](https://github.com/qgis/QGIS/files/10419845/output_table_47000x47000.zip)

```
fid	value	count
1	127	-2085967296
```


2) [example_93000x93000.zip](https://github.com/qgis/QGIS/files/10419827/example_93000x93000.zip) (508 KB)
The same happens with this layer which contains 8649000000 pixels of value 127.
The following generated output GeoPackage layer also contains incorrect values:

[output_table_93000x93000.zip](https://github.com/qgis/QGIS/files/10419857/output_table_93000x93000.zip)

```
fid	value	count
1	127	59065408
```

**Comment by nyalldawson** [comment] 2023-01-16 23:43
This was fixed by https://github.com/qgis/QGIS/pull/50964

**Closed by nyalldawson** 2023-01-16 23:43 UTC
Labels: Processing, Bug
