### ISSUE TITLE
Apply map canvas rotation to layout map item

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38850] opened 2020-09-17 21:29 UTC
I don't know whether it's a bug or a feature, and failed to find any reference to this.

If I apply a rotation to the map canvas (in the status bar), and I create a layout map item, the latter shows the map with no rotation. I'd expect to get the rotated map.

If this is not desirable, can we add a variable, eg "map_canvas_rotation", to use with data-define widget here?

**Comment by nyalldawson** [comment] 2020-09-17 21:31
I'd say this is entirely expected behavior, much like how the layout map doesn't follow the canvas extent. Possibly the newly created map should default to taking the canvas rotation as an initial value, but after that they should be completely independent.

**Comment by roya0045** [comment] 2020-09-17 21:56
This could be problematic if we added a hard link. Also linking the rotation but havinng independent views and projection makes no sense. Though the variable would be fine.

**Comment by nyalldawson** [comment] 2020-09-17 22:19
Actually a variable isn't straightforward either. A project can have multiple canvases, and a layout isn't linked to any one in particular. I'd say we close this and let a plugin address this use case.

**Comment by roya0045** [comment] 2020-09-17 22:35
@nyalldawson as a side question. regarding situations where we have multiple items, let's say maps in a layout. What would be the best way to expose variable of those, scopes are used for distinct elements but would it be possible to group the variable for map 1 and map 2 or add a prefix to work around those issues. Such as with multiple canvas?

**Comment by nyalldawson** [comment] 2020-09-17 22:49
@roya0045 The "item_variables" function in layouts allows you access to another layout item's variables/context. So you can do something like

    map_get( item_variables('Map 0'), 'map_rotation')

to get the rotation of the map with id "Map 0" and insert it into a label's text

**Comment by roya0045** [comment] 2020-09-17 23:03
@nyalldawson right I forgot about this, but since it available for layout something similar whouls be doable for qgis as a whole. Thanks for reminding me of this!

**Closed** 2020-10-06 21:48 UTC
Labels: Feature Request
