### ISSUE TITLE
Spliting a QgsGeometry doesn't match any overloaded

### ISSUE THREAD

**Issue by trsbar** [qgis/QGIS#50012] opened 2022-08-30 08:12 UTC
### What is the bug or the crash?

Documentation says that QgsGeometry with first parameter as QgsPointXY is deprecated 
 : https://qgis.org/pyqgis/3.22/core/QgsGeometry.html?highlight=qgsgeometry#qgis.core.QgsGeometry.splitGeometry

- Using QgsPoint iterable to split a QgsGeometry outputs an error : 

points = [QgsPoint(-0.57154300779810807,46.23909102622299372),QgsPoint(-0.56557962478150436,46.23758244787522642)]
t = feature.geometry().splitGeometry(points)

**TypeError: QgsGeometry.splitGeometry(): arguments did not match any overloaded call:
overload 1: not enough arguments
overload 2: not enough arguments
overload 3: argument 1 has unexpected type 'list'**

- If i paste the example give in documentation, i get this error : 

**TypeError: index 0 has type 'QgsPoint' but 'QgsPointXY' is expected**

### Steps to reproduce the issue

Copy and paste the example here in console (or any python file) : https://qgis.org/pyqgis/3.22/core/QgsGeometry.html?highlight=qgsgeometry#qgis.core.QgsGeometry.splitGeometry

### Versions

Version de QGIS | 3.22.10-Białowieża | Révision du code | [6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.5.1
Version de Proj | 9.0.1
Version de la base de données du registre EPSG | v10.064 (2022-05-19)
Version de GEOS | 3.10.3-CAPI-1.16.1
Version de SQLite | 3.38.1
Version de PDAL | 2.4.2
Version du client PostgreSQL | 14.3
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
plugin_reloader | 0.9.1
sig_safer | 22.07.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.22.10-Białowieża
Révision du code
[6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.1
Version de Proj
9.0.1
Version de la base de données du registre EPSG
v10.064 (2022-05-19)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.38.1
Version de PDAL
2.4.2
Version du client PostgreSQL
14.3
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
plugin_reloader
0.9.1
sig_safer
22.07.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-08-30 09:55
I can confirm on 3.26.2 too.

**Comment by lbartoletti** [comment] 2022-08-30 10:02
It's a duplicate of https://github.com/qgis/QGIS/issues/37821

**Closed by lbartoletti** 2022-08-30 10:02 UTC
Labels: PyQGIS, Bug
