### ISSUE TITLE
Confusing error message when applying a filter on layer that is in edit mode.

### ISSUE THREAD

**Issue by robinjonesuk** [qgis/QGIS#44055] opened 2021-07-05 15:17 UTC
**Describe the bug**

Editing the filter for a layer that is in edit mode results in this confusing error message:

"Error in query. The subset string could not be set."

**How to Reproduce**

When you've either clicked on the filter icon or used filter on the right-click context menu and make a change to the filter for a layer that is in edit mode and then click  ok

The result is "Error in query. The subset string could not be set.", rather than something meaningful like "You cannot change the layer filter while editing in progress".

[test.zip](https://github.com/qgis/QGIS/files/6765161/test.zip)

4. See error -->

**QGIS and OS versions**
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

</body></html>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.0-Odense | QGIS code revision | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.3 (Debian 13.3-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins | latlontoolsMemoryLayerSaverqfieldsyncqgiscloudTomBioImportPhotosSpreadsheetLayersgis_cloud_publisherMetaSearchdb_managerprocessing

</body></html>
**Additional context**

**Comment by troopa81** [comment] 2023-02-16 16:57
Duplicate of #51816

**Closed by troopa81** 2023-02-16 16:57 UTC
Labels: Data Provider, Bug
