### ISSUE TITLE
orfeotoolbox provider plugin not available in qgis 3.36.0

### ISSUE THREAD

**Issue by thomas-szczurek** [qgis/QGIS#56663] opened 2024-03-03 12:01 UTC
### What is the bug or the crash?

OrfeoTooBox provider plugin should be available from scratch qgis installation, however it is not in qgis 3.36.0 downloaded from either debian and ubuntu repository. Tested with 3.34.3 from conda-forge and the plugin is available from scratch install.

Sorry if it's in the wrong channel, as it's realated to third party tool,  but as it's not something you have to download I was unsure

### Steps to reproduce the issue

Download qgis 3.36.0 on linux

### Versions

3.36.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment] 2024-03-03 12:18
This is intended. Duplicate of https://github.com/qgis/QGIS/issues/56508 / see #55406

**Closed by rouault** 2024-03-03 12:18 UTC
Labels: Bug
