### ISSUE TITLE
How I can fix "QNEAT3" Error?

### ISSUE THREAD

**Issue by Navid61** [qgis/QGIS#36488] opened 2020-05-16 09:51 UTC
When I tried close QGIS while it was connec to wfs service I got this error:

Error while unloading plugin QNEAT3 

KeyError: 'QNEAT3' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1115, in __iter__
  File "", line 1103, in _recalculate
  File "", line 1099, in _get_parent_path
KeyError: 'QNEAT3'

Python version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0] 
QGIS version: 3.10.5-A Coruña A Coruña, 984615fe1e 

Python Path:
/usr/share/qgis/python
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/home/sigma/.local/lib/python3.7/site-packages
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.7/dist-packages
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/isochrones/iso/utilities

**Comment by andreasneumann** [comment] 2020-05-16 10:13
Hi Navid,

You can remove the QNEAT3 plugin normally through the plugin manager (if 
you don't need it anymore) or by removing the respective folder at 
/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins (if 
you are still on the default profile). If you are on a different 
profile, you can use the python/plugins folder of that other profile.

Greetings,

Andreas


Am 16.05.20 um 11:52 schrieb Navid:

**Comment by root676** [comment] 2020-05-16 14:39
Hi, I have been receiving this error too lately. For reference: QGIS reports this error when closing the application (not uninstalling). Unfortunately I have not been able to detect the cause of the error yet (especially since I didn't change the plugin code and the error occurred out of nowhere). I will keep you posted on this problem. Please open a ticket in my [QNEAT3 repository](https://github.com/root676/QNEAT3) as this seems to be related to the plugin and not QGIS itself.

**Comment by root676** [comment] 2020-05-16 14:58
@Navid61 do you notice any pattern for that error? I cannot reproduce it every time on closing QGIS.

**Comment by gioman** [comment] 2020-05-17 08:20
@Navid61 closing as the error is from a 3rd party plugin, must be reported in plugin's tracker.

**Closed by gioman** 2020-05-17 08:20 UTC
Labels: Won't fix
