### ISSUE TITLE
DB Manager: SQL SELECT query skip fields when having fields with identical names

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#39530] opened 2020-10-21 14:29 UTC
When executing a SELECT query in the DB Manager, if by chance two successive fields have the same name (as possibly in a JOIN) , the second name is replaced by the name of the next field whose content is in turn deleted.  Here's a simple example: 

`select 1 as a, 2 as b , 3 as b, 'xxy' as test;`

Gives :

> a        b        test
> 1        2             3

I noticed this strange behaviour in QGis 3.14.16 in Mac OS.
`

Version de QGIS | 3.14.16-Pi | Révision du code | a235a149f0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS High Sierra (10.13)
`
![Capture d’écran 2020-10-21 à 16 28 54](https://user-images.githubusercontent.com/6814394/96734193-9172d980-13ba-11eb-8ebc-b23fc8d88d11.png)

**Comment by Gustry** [comment] 2020-10-21 18:05
I'm pretty sure there is already a ticket for this one.

**Comment by dd-a** [comment] 2020-10-21 18:09
ok, sorry I probably did not search long enough !

**Comment by Gustry** [comment] 2020-10-21 18:16
Hum, I was thinking about ticket #36205 and PR #36831

**Comment by gioman** [comment] 2020-10-21 19:06
> Hum, I was thinking about ticket #36205 and PR #36831

@Gustry but that seems has been backported to 3.14 so this should be fixed. But apparently is not.

What I see here are 3 different things on Windows and 3.10, 3.14 and master

3.10: results of the above query are ok

3.14 (wong):

a b
1 2

master (wrong):

a b b(2)
1 2 3

@elpaso

**Comment by elpaso** [comment] 2020-10-22 07:33
@gioman master is not wrong. 

It's all we can do now that the implementation is based on `QgsFields` which does not admit duplicate names for fields. 

IMO having a query return duplicate names is confusing anyway, SQL provides `AS` for overcome the ambiguity.

**Comment by gioman** [comment] 2020-10-22 07:47
> @gioman master is not wrong.

@elpaso it is acceptable that master shows the repeated column as name(2), but is not that do not show the columns after that ("xxy" in the above example).

**Comment by gioman** [comment] 2020-10-22 07:54
> ("xxy" in the above example)

@elpaso sorry I meant "test".

**Comment by elpaso** [comment] 2020-10-22 08:05
@gioman that's what was fixed in  #36831 or am I missing something?

**Comment by elpaso** [comment] 2020-10-22 09:05
I see, I was missing `test` and the `xyz` value. I'll have a look.

**Comment by gioman** [comment] 2020-10-22 09:09
> I see, I was missing `test` and the `xxy` value. I'll have a look.

yes, I was about to comment with a screencast. Thanks for having a look.

**Comment by elpaso** [comment] 2020-10-22 09:40
I cannot reproduce in current master:

![immagine](https://user-images.githubusercontent.com/142164/96854028-54125880-145b-11eb-8ea2-c997da80dd81.png)

**Comment by gioman** [comment] 2020-10-22 10:11
@elpaso latest master on Windows:

![Screenshot_20201022_111051](https://user-images.githubusercontent.com/1951107/96857770-4955c480-1457-11eb-8f11-027f836bfc0b.png)

**Comment by elpaso** [comment] 2020-10-22 10:27
Sorry, I have no idea what could be possibly different on windows.

**Comment by gioman** [comment] 2020-10-22 10:38
> Sorry, I have no idea what could be possibly different on windows.

I'll reopen and tag this ticket as "windows".

**Comment by gioman** [comment] 2020-10-22 11:20
> Sorry, I have no idea what could be possibly different on windows.

@elpaso it is not Windows, it is the PostgreSQL version. With a 9.6 PostgreSQL backend it skips the column, with a 12 one it return the correct result.

**Comment by elpaso** [comment] 2020-10-22 12:03
interesting ...

**Closed** 2020-10-23 05:47 UTC
Labels: Bug, DB Manager, Regression
