### ISSUE TITLE
Error when saving project QGis 310

### ISSUE THREAD

**Issue by iafe-eng** [qgis/QGIS#33267] opened 2019-12-06 13:20 UTC
[Qgis310 issue 20191206.txt](https://github.com/qgis/QGIS/files/3932308/Qgis310.issue.20191206.txt)

## User Feedback

I was closing the application trying to save a complex project obtained with the r.slope.aspect GRASS algorithm.

## Report Details

**Crash ID**: [8d49324082b24616856054d616946d742879ac28]('https://github.com/qgis/QGIS/search?q=8d49324082b24616856054d616946d742879ac28&type=Issues')

**Stack Trace**
<pre>
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::~OGRSpatialReference :
GDALRegister_GenBin :
GDALRegister_GenBin :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by roya0045** [comment] 2019-12-06 14:30
wat

**Comment by iafe-eng** [comment] 2019-12-06 16:28
READ the attached txt_ contains the qgis report

**Comment by roya0045** [comment] 2019-12-06 16:30
Anyway this issue is often related to plugins, try with a clean profile and no 3rd party plugins.

**Comment by roya0045** [comment] 2019-12-06 16:32
Also duplicate of #33178

**Comment by gioman** [comment] 2019-12-07 19:22
> I was closing the application trying to save a complex project obtained with the r.slope.aspect GRASS algorithm.

@iafe-eng can you please add detailed steps to replicate? also have you tried with a new QGIS profile?

**Comment by iafe-eng** [comment] 2019-12-07 21:17
I will try next monday in a 345 ltr qgis and will inform you.

I processed a tiff selecting all results of the algorthim r.slope.aspect.
Screen capture previous to the failure attached.

Ing. Inés Fuentes Elgide

**Comment by roya0045** [comment] 2019-12-10 13:48
Nyall said that this should be fixed in 3.10.1, please test and if the issue was solved please close this ticket.

**Comment by iafe-eng** [comment] 2019-12-10 16:06
ok. I will wait to the new version then.

**Comment by gioman** [comment] 2020-03-02 15:56
Closing for lack of feedback. Please reopen if necessary.

**Closed by gioman** 2020-03-02 15:56 UTC
Labels: Bug, Feedback

**Comment by iafe-eng** [comment] 2020-03-02 22:27
Thank you. Haven't been able to reinstall qgis 310.
