### ISSUE TITLE
Crash on deleting a circle object in layout mode

### ISSUE THREAD

**Issue by ThomasStruller** [qgis/QGIS#53534] opened 2023-06-21 09:10 UTC
## User Feedback

Deleting a circle object in layout-mode Qgis crashes

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006090 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::topLevelItem :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsScene::wheelEvent :
QGraphicsSceneEvent::widget :
QGraphicsSceneEvent::widget :
QGraphicsScene::items :
QGraphicsScene::destroyItemGroup :
QGraphicsScene::mouseMoveEvent :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGraphicsViewPrivate::mouseMoveEventHandler :
QgsLayoutView::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

open a layout with objects (circle) in it
deleting the circle
crash

### Versions

**QGIS Info**
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by weca-theo** [comment] 2023-06-24 22:51
have also found something similar- I have text/label rectangles in a layout. The text within is plain, no expressions used. When I delete one of these rectangles, QGIS crashes.

**Comment by nyalldawson** [comment] 2023-10-04 04:27
Duplicate of https://github.com/qgis/QGIS/issues/52079

**Closed by nyalldawson** 2023-10-04 04:27 UTC
Labels: Bug, Crash/Data Corruption, Print Layouts
