### ISSUE TITLE
Browser Panes freezing when network connections not present, Windows

### ISSUE THREAD

**Issue by GGDRriedel** [qgis/QGIS#52530] opened 2023-04-04 11:36 UTC
### What is the bug or the crash?

Anything related to a browser, be it opening layers or through 3rd party plugins using a browser hangs QGIS. 

The problem seems to be related to network connections not being present. 
The problem is further described here: 
https://github.com/qgis/QGIS/issues/33778

However, this was closed prematurely without any real fix. 

### Steps to reproduce the issue

I can recreate this by turning off my VPN.
Once this is the case, even on a fresh project, QGIS hangs for 10 to 20 minutes. 
If the VPN is enabled, everything works fine

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.2-Firenze | QGIS code revision | b47e00ba601
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.6.0 | Running against GDAL/OGR | 3.6.1
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.2.5
batchvectorlayersaver | 0.9
DEMto3D | 3.51
GarminCustomMap | 3.4.2
GeoCoding | 2.18
go2mapillary | 2.3
GTFS-GO-develop | 3.0.1
inspireatomclient | 0.8.1
openlayers_plugin | 2.0.0
processing_fusion | 3.5
profiletool | 4.2.2
qad | 3.0.4
qgis-fit-plugin | 0.3
Qgis2threejs | 2.7.1
qgis2web | 3.16.0
qProf | 0.5.0
QuickOSM | 2.1.1
quick_map_services | 0.19.33
raster_tracer | 0.3.2
slyr_community | 4.0.6
SpreadsheetLayers | 2.1.0-alpha1
SRTM-Downloader | 3.1.17
travel_time_platform_plugin | 1.8.0
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.28.2-Firenze
QGIS code revision
[b47e00ba601](https://github.com/qgis/QGIS/commit/b47e00ba601)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.0
Running against GDAL/OGR
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.5
batchvectorlayersaver
0.9
DEMto3D
3.51
GarminCustomMap
3.4.2
GeoCoding
2.18
go2mapillary
2.3
GTFS-GO-develop
3.0.1
inspireatomclient
0.8.1
openlayers_plugin
2.0.0
processing_fusion
3.5
profiletool
4.2.2
qad
3.0.4
qgis-fit-plugin
0.3
Qgis2threejs
2.7.1
qgis2web
3.16.0
qProf
0.5.0
QuickOSM
2.1.1
quick_map_services
0.19.33
raster_tracer
0.3.2
slyr_community
4.0.6
SpreadsheetLayers
2.1.0-alpha1
SRTM-Downloader
3.1.17
travel_time_platform_plugin
1.8.0
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pathmapper** [comment] 2023-04-05 07:18
duplicate of https://github.com/qgis/QGIS/issues/51710

**Closed** 2023-11-03 16:53 UTC
Labels: Bug, QGIS Browser
