### ISSUE TITLE
Unable to print or export

### ISSUE THREAD

**Issue by C4pT4in0bvi0u5** [qgis/QGIS#50734] opened 2022-10-28 20:05 UTC
### What is the bug or the crash?

When attempting to print or export my map, QGIS works for a long time (193 seconds in the recorded case), then crashes abruptly. No warnings, no errors, just blip and the entire program disappears. If an output file is created, it has 0 size.

I have successfully exported exactly once to a 96 dpi PDF in Letter size, but I need 600 dpi and much larger paper size as there is more data to be added to this map yet.

I have tried exporting to PDF with multiple different options, exporting to PNG, and printing directly. All of the above fail in the same way.

I have tried reducing the canvas and layer sizes drastically by creating new layers with only the polygons etc. that I need, and removing the country-scale original layers.

This is not a hardware issue. QGIS doesn't ***even*** use a full 2 CPU threads of the 40 available, and only uses 324 MB of the available 96 GB RAM. Yes, the QGIS max thread count is set to 40 . . . as if that mattered.

The only crash output from DebugView is the following:
[14804] Warning: QObject::killTimer: Timers cannot be stopped from another thread
[14804] Warning: QObject::~QObject: Timers cannot be stopped from another thread

Here's the project: [temp QGIS project.zip](https://github.com/qgis/QGIS/files/9891365/temp.QGIS.project.zip)

### Steps to reproduce the issue

Try printing or exporting the attached project.

### Versions

Have tried QGIS versions 3.26 and 3.28.
Windows 10 build 19044.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Clean install, no QGIS plugins installed.

**Comment by agiudiceandrea** [comment] 2022-10-29 09:31
@C4pT4in0bvi0u5, are you trying to print/export the map canvas or a layout?
In the provided project there are 3 print layouts (1 is empty) and all of them in A4 size and no one in Letter size.
I've exported the "Cropped 1" layout as a 600 dpi PNG image without any issue.
![Cropped 1](https://user-images.githubusercontent.com/16253859/198824318-815c627e-4173-4704-aa83-7e317dbc00c2.png)
Could you please share more detailed info in order to replicate the issue?

**Comment by agiudiceandrea** [comment] 2022-10-29 13:45
@C4pT4in0bvi0u5, are you trying to print/export the map canvas or a layout? In the provided project there are 3 print layouts (1 is empty) and all of them in A4 size and no one in Letter size.

Anyway, on Windows 10, the issue doesn't occur using QGIS 3.22.12, while it does using QGIS 3.28.0 and the latest QGIS 3.29.0-Master (2a3cdfd4c5).

I've exported the "Cropped 1" layout as a 600 dpi PNG image without any issue using QGIS 3.22.12.
![Cropped 1](https://user-images.githubusercontent.com/16253859/198824318-815c627e-4173-4704-aa83-7e317dbc00c2.png)

**Comment by C4pT4in0bvi0u5** [comment] 2022-10-29 19:05
Confirmed working in v3.22.12. Exporting the canvas directly to PDF works, printing from layout works. Everything just works. So the issue is with the QGIS versions that I tried (3.26 and 3.28).

In versions 3.26 and 3.28, I tried exporting both map canvas and layout. Program would crash before completing layout export, but leave an empty layout behind, which is why there are some residual empty layouts with QGIS's default A4 paper size. This file was a work in progress, not a tidied up "final" version of anything, so I guess I forgot to delete all the detritus before I sent it out into the world.

FWIW, GIMP is also experiencing an issue in their development version where it won't process large PDF files. Not sure if QGIS and GIMP share any libraries. Over on the GIMP site, there's speculation that a 32-bit variable may have been used instead of a 64-bit variable for some sort of "offset" when loading the image. I'm not a programmer, hopefully that means something to somebody.

**Comment by C4pT4in0bvi0u5** [comment] 2022-10-31 19:37
Yes, this map uses masks extensively. The land Section layer (small numbers) is laid over top of the land Quarters layer (visible grid), with a mask around the numbers so each number doesn't have a crosshairs through it.

**Comment by dgreenewalt** [comment] 2022-10-31 20:08
Will the map export properly if you remove the masks or use buffers rather than masks for your labels?  Not as good for display, but I'm curious if that resolves the print/export problem.

**Comment by agiudiceandrea** [comment] 2022-10-31 22:37
So, probably similar to https://github.com/qgis/QGIS/issues/50543.

**Comment by C4pT4in0bvi0u5** [comment] 2022-10-31 23:19
@dgreenewalt Yes, tried with v3.28, and it will now print from layout and export to PNG & PDF after disabling the text mask on the Sections layer, using text buffer instead.

The project file is posted above, so feel free to experiment on your own with it.

**Comment by agiudiceandrea** [comment] 2022-11-02 11:27
@C4pT4in0bvi0u5, is this issue the same already reported at https://github.com/qgis/QGIS/issues/50543?

**Comment by C4pT4in0bvi0u5** [comment] 2022-11-02 17:24
@agiudiceandrea It appears that they are the same, yes.

**Comment by agiudiceandrea** [comment] 2022-11-02 18:53
Closing as duplicate of https://github.com/qgis/QGIS/issues/50543.

**Closed by agiudiceandrea** 2022-11-02 18:53 UTC
Labels: Regression, Bug, Print Layouts

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-23 06:01
This issue appears to be resolved in QGIS v3.38.0.
