### ISSUE TITLE
Projection issue for vector and raster layers similar to QGIS 3.22 wrongly displays raster #47158

### ISSUE THREAD

**Issue by jarrettinho** [qgis/QGIS#50784] opened 2022-11-03 14:43 UTC
### What is the bug or the crash?

Projection information for raster and vector (shp and geopackage) files 'unknown' in QGIS 3.22.11 (GDAL 3.5.1). No issue in 3.18 (GDAL 3.4.0)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/117367748/199751935-177e4e5a-9d78-4d49-812f-2c05534aea23.png)
Examples of vector and raster layers where projection not recognised

### Versions

QGIS version
3.22.11-Białowieża
QGIS code revision
106d33d7
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
()
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
BoundingBox
2.1
crayfish
3.6.0
DataPlotly
3.8.1
GroupStats
2.2.5
IPyConsole
version 2.0
latlontools
3.6.3
LocatePoints
0.3.4
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
pointsamplingtool
0.5.3
profiletool
4.2.2
qfieldsync
v4.1.1
qgis-maptiler-plugin
2.0.0
Qgis2threejs
2.7.1
qgis_resource_sharing
0.16.0
QPackage
1.5
QRectangleCreator
0.3
QuickOSM
2.1.1
SemiAutomaticClassificationPlugin
7.10.5
shapetools
3.4.4
SRTM-Downloader
3.1.17
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-11-03 14:49
Can you try with a new profile ?

If it still happens, could you share the data ?

**Comment by jarrettinho** [comment] 2022-11-03 14:59
Still the same issue with a new profile. 
[DEM_Cockhaise_Brook_Catchment.zip](https://github.com/qgis/QGIS/files/9930382/DEM_Cockhaise_Brook_Catchment.zip)

**Comment by rouault** [comment] 2022-11-03 18:59
QGIS behaviour is appropriate. The GeoTIFF information in the file is too loose:
```
$ listgeo DEM_Cockhaise_Brook_Catchment.tif
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         532414.2452       132879.4957       0                
      ModelPixelScaleTag (1,3):
         32.6763486725664  32.676348630137   0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,8): "unknown"
      GeographicTypeGeoKey (Short,1): User-Defined
      GeogCitationGeoKey (Ascii,106): "GCS Name = unknown|Datum = Unknown based on Airy 1830 ellipsoid|Ellipsoid = Airy 1830|Primem = Greenwich|"
      GeogGeodeticDatumGeoKey (Short,1): User-Defined
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      GeogEllipsoidGeoKey (Short,1): User-Defined
      GeogSemiMajorAxisGeoKey (Double,1): 6377563.396      
      GeogInvFlatteningGeoKey (Double,1): 299.3249646      
      GeogPrimeMeridianLongGeoKey (Double,1): 0                
      ProjectedCSTypeGeoKey (Short,1): User-Defined
      ProjectionGeoKey (Short,1): User-Defined
      ProjCoordTransGeoKey (Short,1): CT_TransverseMercator
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      ProjNatOriginLongGeoKey (Double,1): -2               
      ProjNatOriginLatGeoKey (Double,1): 49               
      ProjFalseEastingGeoKey (Double,1): 400000           
      ProjFalseNorthingGeoKey (Double,1): -100000          
      ProjScaleAtNatOriginGeoKey (Double,1): 0.9996012717     
      End_Of_Keys.
   End_Of_Geotiff.

Projection Method: CT_TransverseMercator
   ProjNatOriginLatGeoKey: 49.000000 ( 49d 0' 0.00"N)
   ProjNatOriginLongGeoKey: -2.000000 (  2d 0' 0.00"W)
   ProjScaleAtNatOriginGeoKey: 0.999601
   ProjFalseEastingGeoKey: 400000.000000 m
   ProjFalseNorthingGeoKey: -100000.000000 m
Projection Linear Units: 9001/metre (1.000000m)
```

Particularly the "Datum = Unknown based on Airy 1830 ellipsoid".  Based on the following I guess the intent was it to be detected as EPSG:27700, but the file should be coded in a more straightforward way to include the EPSG:27700 code or have the datum field to be set to "Ordnance Survey of Great Britain 1936"

```
$ gdalsrsinfo  -e DEM_Cockhaise_Brook_Catchment.tif 
Confidence in this match: 70 %

EPSG:27700

PROJ.4 : +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs

OGC WKT2:2019 :
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore."],
        BBOX[49.75,-9,61.01,2.01]],
    ID["EPSG",27700]]
```

Closing as works as intended

**Closed by rouault** 2022-11-03 18:59 UTC
Labels: Bug

**Comment by jarrettinho** [comment] 2022-11-04 07:13
I've reinstalled using standalone 3.22.12 rather than OSGEO4W set up and all seems ok with this file and others which I had problems with.

    On Thursday, 3 November 2022 at 18:59:27 GMT, Even Rouault ***@***.***> wrote:  
 
 


QGIS behaviour is appropriate. The GeoTIFF information in the file is too loose:
$ listgeo DEM_Cockhaise_Brook_Catchment.tif
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         532414.2452       132879.4957       0                
      ModelPixelScaleTag (1,3):
         32.6763486725664  32.676348630137   0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,8): "unknown"
      GeographicTypeGeoKey (Short,1): User-Defined
      GeogCitationGeoKey (Ascii,106): "GCS Name = unknown|Datum = Unknown based on Airy 1830 ellipsoid|Ellipsoid = Airy 1830|Primem = Greenwich|"
      GeogGeodeticDatumGeoKey (Short,1): User-Defined
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      GeogEllipsoidGeoKey (Short,1): User-Defined
      GeogSemiMajorAxisGeoKey (Double,1): 6377563.396      
      GeogInvFlatteningGeoKey (Double,1): 299.3249646      
      GeogPrimeMeridianLongGeoKey (Double,1): 0                
      ProjectedCSTypeGeoKey (Short,1): User-Defined
      ProjectionGeoKey (Short,1): User-Defined
      ProjCoordTransGeoKey (Short,1): CT_TransverseMercator
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      ProjNatOriginLongGeoKey (Double,1): -2               
      ProjNatOriginLatGeoKey (Double,1): 49               
      ProjFalseEastingGeoKey (Double,1): 400000           
      ProjFalseNorthingGeoKey (Double,1): -100000          
      ProjScaleAtNatOriginGeoKey (Double,1): 0.9996012717     
      End_Of_Keys.
   End_Of_Geotiff.

Projection Method: CT_TransverseMercator
   ProjNatOriginLatGeoKey: 49.000000 ( 49d 0' 0.00"N)
   ProjNatOriginLongGeoKey: -2.000000 (  2d 0' 0.00"W)
   ProjScaleAtNatOriginGeoKey: 0.999601
   ProjFalseEastingGeoKey: 400000.000000 m
   ProjFalseNorthingGeoKey: -100000.000000 m
Projection Linear Units: 9001/metre (1.000000m)

Particularly the "Datum = Unknown based on Airy 1830 ellipsoid". Based on the following I guess the intent was it to be detected as EPSG:27700, but the file should be coded in a more straightforward way to include the EPSG:27700 code or have the datum field to be set to "Ordnance Survey of Great Britain 1936"
$ gdalsrsinfo  -e DEM_Cockhaise_Brook_Catchment.tif 
Confidence in this match: 70 %

EPSG:27700

PROJ.4 : +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs

OGC WKT2:2019 :
PROJCRS["OSGB36 / British National Grid",
    BASEGEOGCRS["OSGB36",
        DATUM["Ordnance Survey of Great Britain 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore."],
        BBOX[49.75,-9,61.01,2.01]],
    ID["EPSG",27700]]

Closing as works as intended
