### ISSUE TITLE
Debugging/development tools panel do not record any requests/traffic from Metasearch

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46247] opened 2021-11-27 16:05 UTC
### What is the bug or the crash?

Subject say it all.

Requests from other services are recorded, but nothing shows when using Metasearch.

### Steps to reproduce the issue

Open the Debugging/development tools panel

Start recording

Use metasearch

### Versions

3.16.14 
3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Gustry** [comment] 2021-11-28 09:31
Duplicate of #24214

**Closed by Gustry** 2021-11-28 09:31 UTC
Labels: Bug, MetaSearch
