### ISSUE TITLE
PROJ version not updated in QGIS 3.16?

### ISSUE THREAD

**Issue by Golok** [qgis/QGIS#40284] opened 2020-11-26 00:16 UTC
Hello,

Referring to the issue #35512 regarding the Winkel Tripel projection and the changes on PROJ 7.1, it looks like the version that QGIS 3.16 is compiled and running against is 6.3.2, and not 7.1 as expected.

![QGIS-3-16_PROJ_6-3-2](https://user-images.githubusercontent.com/278053/100293676-bb548880-2f84-11eb-8f33-4cd0aeb9426d.png)

Could this be the reason why I still cannot output raster layer with this projection?

**QGIS and OS versions**

Mac OS Mojave 10.14.6
QGIS 3.16

Thank you in advance for any help.

**Comment by gioman** [comment] 2020-11-26 08:15
> and not 7.1 as expected.

@Golok the fact that some upstream bug is fixed does not means that QGIS can immediately jump and use the library patched version.

**Comment by roya0045** [comment] 2020-11-26 11:13
This is not a bug.

**Comment by gioman** [comment] 2020-11-26 11:40
> This is not a bug.

agree, closing?

**Comment by roya0045** [comment] 2020-11-26 11:47
Your call Gio.

**Comment by Golok** [comment] 2020-11-26 11:58
Does closing mean no step will be taken to fix this?

**Comment by gioman** [comment] 2020-11-26 12:03
> Does closing mean no step will be taken to fix this?

@Golok there is nothing to fix, you must wait a new QGIS releases that will use proj 7

**Comment by gioman** [comment] 2020-11-26 12:03
or build yourself QGIS using the dependencies you want/need

**Comment by DelazJ** [comment] 2020-11-26 12:14
Or check whether a [nightly build](https://qgis.org/downloads/macos/) uses that version of dependency...(eg windows nightly uses a more recent proj version)
@PeterPetrik Is it normal that the latest nightly is 2 weeks old? Or that is not the page to look at?

**Comment by PeterPetrik** [comment] 2020-11-26 12:20
mac is proj6 too. nightlies are broken, I will try to fix tomorrow.

**Closed** 2020-11-30 21:41 UTC
Labels: Bug, Feedback

**Comment by PeterPetrik** [comment] 2020-12-01 07:13
nightlies are fixed as of today
