### ISSUE TITLE
Export curved labels to SVG in one peace

### ISSUE THREAD

**Issue by nextstopsun** [qgis/QGIS#38876] opened 2020-09-19 14:22 UTC
Currently exporting a project which contains curved labels to SVG results in each letter being exported as a separate SVG group. This makes it nearly impossible to edit label text in exported SVG. You have to go through each and every letter.

It would be way more convenient to have whole label exported as a single text object with text following along a path.

**Comment by nyalldawson** [comment] 2020-09-20 22:13
Duplicate of #24369

**Closed by nyalldawson** 2020-09-20 22:13 UTC
Labels: Feature Request
