### ISSUE TITLE
project predefined scales not working

### ISSUE THREAD

**Issue by Wernerehl** [qgis/QGIS#52952] opened 2023-04-30 20:11 UTC
### What is the bug or the crash?

Bug: for version 3.30 the Scale feature at the bottom shows the appropriate current scale, however none of the predefined scales show. They appear in the general options under Map Tools, but not in the project. This was not the case for 3.26.1. I am running Mac OS 12.6.5 Monterey

### Steps to reproduce the issue

    Go to bottom of the screen below the map
    Click on the Scale box small black arrow on the right
    attempt to scroll to see different predefined scales
    Only the current map scale appears and stays the same. 
<img width="519" alt="Screen Shot 2023-04-30 at 4 09 38 PM" src="https://user-images.githubusercontent.com/132228413/235374138-bac11604-65ea-45fb-a3d4-d598eb30fe68.png">

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | b609df9ed4
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.6
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.7
slyr_community | 4.0.7
kmltools | 3.1.28
quick_map_services | 0.19.33
ImageServerConnector | 2.1.1
GeoCoding | 2.19
latlontools | 3.6.9
filter_master | 0.1
plugin_reloader | 0.9.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code revision
[b609df9ed4](https://github.com/qgis/QGIS/commit/b609df9ed4)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.6

Active Python plugins
numericalDigitize
0.4.7
slyr_community
4.0.7
kmltools
3.1.28
quick_map_services
0.19.33
ImageServerConnector
2.1.1
GeoCoding
2.19
latlontools
3.6.9
filter_master
0.1
plugin_reloader
0.9.3
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment] 2023-05-01 08:11
Duplicate of #52383

**Closed** 2023-05-01 08:12 UTC
Labels: Bug
