### ISSUE TITLE
Impossible to connect Oracle Database 11g in QGIS 3.20.0

### ISSUE THREAD

**Issue by Crapaud04** [qgis/QGIS#43997] opened 2021-06-30 16:04 UTC
**Describe the bug**
Is Impossible to connect Oracle Database 11g in QGIS 3.20.0.
The same connection is valide in QGIS 3.16.7.

**How to Reproduce**

1. Go to Data Source Manager in Oracle connection
2. Click on connect
3. See error 
![image](https://user-images.githubusercontent.com/37582771/123994065-4ee3b100-d9cd-11eb-81df-f2d5babb7310.png)

**QGIS and OS versions**

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.20.0-Odense | Révision du code | decaadbb31
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.0
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins | autoSaverDataPlotlyign_espace_collaboratifInvisibleLayersAndGroupsisochroneslizmapmaskpg_metadatapointsamplingtoolprofiletoolqgis-maptiler-pluginqgis2webqProfQuickOSMrectanglifyrefFunctionsselectThemesSpreadsheetLayerstrail_elevation_statsdb_managerMetaSearchprocessing

</body></html>

Version Oracle : Oracle Database 11g Release 11.1.0.7.0 - Production

**Comment by gioman** [comment] 2021-06-30 16:37
@Crapaud04 duplicate of https://github.com/qgis/QGIS/issues/43843 ?

**Comment by Crapaud04** [comment] 2021-07-01 07:06
Yes, is same problem. 
I am sorry for duplicate.
I have test a new version QGIS for validate this close of ticket #39370.

I close the ticket #43997 or no ?

**Closed** 2021-07-01 15:45 UTC
Labels: Bug, Feedback, Oracle data provider
