### ISSUE TITLE
When I try to open the data source manager to add a new WFS, it crashes.

### ISSUE THREAD

**Issue by Panarria** [qgis/QGIS#55891] opened 2024-01-19 10:18 UTC
### What is the bug or the crash?

When I try to open the data source manager to add a new WFS, it crashes.

### Steps to reproduce the issue

1. Click on Data source manager

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.34.2-Prizren | Revisión del código de QGIS | 7d199797fc
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.5
Versión de GDAL/OGR | 3.8.2
Versión de PROJ | 9.3.1
Versión del registro de base de datos EPSG | v10.041 (2021-12-03)
Versión de GEOS | 3.12.1-CAPI-1.18.1
Versión de SQLite | 3.41.1
Versión de PDAL | 2.6.0
Versión del cliente de PostgreSQL | 15.2
Versión de SpatiaLite | 5.1.0
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.4
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
andalusianpopulation | 1.3
layer_tree_tools | 1.1
MultiDistanceBuffer | 3.2.4
Multi_Ring_Buffer | 1.1
ORStools | 1.7.0
polystrip | 3.0.1
QGISRed | 0.16
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Versión de QGIS
3.34.2-Prizren
Revisión del código de QGIS
[7d199797fc](https://github.com/qgis/QGIS/commit/7d199797fc)
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.8.2
Versión de PROJ
9.3.1
Versión del registro de base de datos EPSG
v10.041 (2021-12-03)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.41.1
Versión de PDAL
2.6.0
Versión del cliente de PostgreSQL
15.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
andalusianpopulation
1.3
layer_tree_tools
1.1
MultiDistanceBuffer
3.2.4
Multi_Ring_Buffer
1.1
ORStools
1.7.0
polystrip
3.0.1
QGISRed
0.16
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## User Feedback

When I try to open the data source manager to add a new WFS, it crashes.

## Report Details

**Python Stack Trace**
```
Fatal Python error: Aborted

Thread 0x00003244 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Thread 0x00003244 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

RtlEnterCriticalSection :
NCS::CMutex::Lock :
NCS::CMultiLock::LockExclusive :
NCS::CView::Close :
NCS::CView::Close :
NCS::CView::~CView :
NCS::CView::operator= :
CPLJSONArray::ConstIterator::operator* :
CPLJSONArray::ConstIterator::operator* :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
raise :
Py_gitversion :
raise :
abort :
terminate :
FindHandler<__FrameHandler4> frame.cpp:682
__InternalCxxFrameHandler<__FrameHandler4> frame.cpp:352
__CxxFrameHandler4 risctrnsctrl.cpp:290
RtlpExecuteHandlerForException :
RtlDispatchException :
RtlRaiseException :
RaiseException :
__FrameHandler4::CxxCallCatchBlock frame.cpp:1391
RcConsolidateFrames :
QgsCoordinateTransform::transform qgscoordinatetransform.cpp:334
QgsGeoPackageProviderConnection::searchLayerMetadata qgsgeopackageproviderconnection.cpp:456
QgsOgrLayerMetadataProvider::search qgsogrlayermetadataprovider.cpp:48
QgsMetadataResultsFetcher::fetchMetadata qgslayermetadataresultsmodel.cpp:230
QObject::qt_static_metacall :
QThread::started :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.2-Prizren
QGIS code revision: 7d199797fc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.2
Running against GDAL: 3.8.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by kitzberdo** [comment] 2024-02-07 09:20
I have the same issue. QGIS crashes when I try to open the data souce manager.
Can I provide some additional information to solve this problem?

**Comment by rouault** [comment] 2024-02-08 22:03
Seeing the following in the stack trace,

> QgsCoordinateTransform::transform qgscoordinatetransform.cpp:334
> QgsGeoPackageProviderConnection::searchLayerMetadata qgsgeopackageproviderconnection.cpp:456
> QgsOgrLayerMetadataProvider::search qgsogrlayermetadataprovider.cpp:48

I'm reasonably confident this has been fixed per https://github.com/qgis/QGIS/pull/56210

@kitzberdo If you have a chance, please try nightly qgis-dev builds to confirm that the issue is no longer there

**Comment by rouault** [comment] 2024-02-08 22:10
or if you have GeoPackage connections in the browser, try to remove them one by one. There's likely a "faulty" one

**Comment by kitzberdo** [comment] 2024-02-09 09:51
> or if you have GeoPackage connections in the browser, try to remove them one by one. There's likely a "faulty" one

Thank you! It worked, now I can open the data source manager without problems.

**Comment by rouault** [comment] 2024-02-09 09:55
ok, so closing as a duplicate of #56203

**Closed by rouault** 2024-02-09 09:55 UTC
Labels: Bug, Crash/Data Corruption
