### ISSUE TITLE
Crash when adding Vector layer (.shp file)

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29817] opened 2019-05-06 12:18 UTC
Author Name: **David van Eekelen** (David van Eekelen)
Original Redmine Issue: [22002](https://issues.qgis.org/issues/22002)
Affected QGIS version: 3.6.2
Redmine category:unknown

---
I have installed QGIS 3.6.2 on a Windows Server 2008 R2 system. A couple of users in our corporate environment login on this system via Remote Desktop, and use QGIS.

After a fresh install of QGIS, everything works fine, however, after about 1 day, QGIS crashes when adding a .shp file as a vector layer. The source of this .shp file is locally on the system, so no network/database connections there.

I have also tried the 3.4.7 LTR version, this has the same problems.

Crash ID: 7009b0fe8dc6e45a983a30d4e92444e870732db6

Stack Trace

QGIS Info
QGIS Version: 3.6.2-Noosa
QGIS code revision: 656500e0c4
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by jef-n** [comment] 2019-08-27 12:13
Duplicate of #28104

**Closed by jef-n** 2019-08-27 12:13 UTC
Labels: Bug, Crash/Data Corruption, High Priority
