### ISSUE TITLE
import scipy.interpolate on python console will throw ImportError: DLL load failed

### ISSUE THREAD

**Issue by piMoll** [qgis/QGIS#38462] opened 2020-08-26 14:12 UTC
**Describe the bug**
When trying to import scipy.interpolate on the python console an error message is thrown: 
`ImportError: DLL load failed: The specified module could not be found.`

This worked in QGIS 3.10.1 but somewhere between 3.10.1 and 3.10.9 it stopped working.

**How to Reproduce**
On QGIS python console:
`from scipy import interpolate as ipol`

**QGIS and OS versions**
I installed QGIS with the Standalone installer for Windows. I am on Windows 10. 

Not working in QGIS versions:
3.10.9
3.14.15

Working in:
3.10.1

**Additional context**
It seems this has happened before, see this issue on OSGeo4W 4 years ago:
[import scipy.special gives ImportError DLL load failed: The specified module could not be found.](https://trac.osgeo.org/osgeo4w/ticket/511?cversion=0&cnum_hist=3). 

**Traceback**
Traceback (most recent call last):
  File "C:\PROGRA\~1\QGIS3\~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA\~1/QGIS3\~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA\~1\QGIS3\~1.10\apps\Python37\lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from .interpolate import *
  File "C:/PROGRA\~1/QGIS3\~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA\~1\QGIS3\~1.10\apps\Python37\lib\site-packages\scipy\interpolate\interpolate.py", line 15, in <module>
    import scipy.special as spec
  File "C:/PROGRA\~1/QGIS3\~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA\~1\QGIS3\~1.10\apps\Python37\lib\site-packages\scipy\special\__init__.py", line 634, in <module>
    from . import _ufuncs
  File "C:/PROGRA\~1/QGIS3\~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.

**Comment by gioman** [comment] 2020-08-26 14:34
@piMoll duplicate of https://github.com/qgis/QGIS/issues/38398 ?

**Comment by piMoll** [comment] 2020-08-26 15:09
Yes, looks like it. Sorry, didn't find that one.

**Closed** 2020-08-26 15:11 UTC
Labels: Bug, Feedback, PyQGIS
