### ISSUE TITLE
$X, $Y exist. why not $Z?

### ISSUE THREAD

**Issue by xsaiama** [qgis/QGIS#32196] opened 2019-10-10 19:45 UTC
Hello.
If I want to update the X coordinate column, I use $X. Same principle for Y coordinates with $Y.
I would like you to add $Z to update the Z coordinates. It would be simpler and more efficient.

**Comment by DelazJ** [comment] 2019-10-10 21:59
Duplicate of #28069

**Closed** 2019-10-11 12:26 UTC
Labels: Feature Request
