### ISSUE TITLE
Specify min/max bounds for graduated classification symbology

### ISSUE THREAD

**Issue by dshean** [qgis/QGIS#31146] opened 2019-08-07 23:08 UTC
I often use QGIS to quickly display numerical attributes at point feature locations.  When I do this in Python using matplotlib scatterplot, I specific min and max limits for a linear color ramp.

The closest thing I can find in QGIS is under Layer Properties, select Graduated with Equal Interval for linear scaling.  One can then specify the number of classes, but the full min and max range for the classes are automatically computed.  I realize that one can manually edit class boundaries, but this is tedious.

I would like to specify the min and max values, so I can clip the full linear color ramp to these values, and then either specify 1) the desired interval (automatically calculating number of classes) or 2) number of classes (automatically calculating interval).  

This functionality is already available for rasters.  It would be very useful to allow similar functionality for vector data values.

Hopefully a straightforward addition.  Thanks for developing and maintaining such a fantastic tool!

**Comment by roya0045** [comment] 2019-08-08 18:45
You could also create a virtual field with an expression to limit the min and max values.

**Comment by kannes** [comment] 2019-09-23 08:32
This would a very useful feature and I was just going to make the same request.

It is often needed to scale a classification to externally given breaks, not to the "data-driven" breaks of the sample that you happen to be mapping.

For example if you map percentages (0-100) you might need to adjust your colors so that the range goes up to 100, while the data might just have e.g. 74% as highest value and 23% as the lowest.

**Comment by kannes** [comment] 2019-09-23 08:42
Oh this is a dupe of https://github.com/qgis/QGIS/issues/20637

If you close this, please add a note on https://github.com/qgis/QGIS/issues/20637 that the discussion here is worth reading. Thanks!

**Comment by alexbruy** [comment] 2020-08-12 12:19
Duplicates #20637.

**Closed by alexbruy** 2020-08-12 12:19 UTC
Labels: Feature Request, Symbology, Vectors

**Comment by kannes** [comment] 2020-08-13 19:41
@alexbruy I nicely asked for a comment to be added at #20637 when this one were closed. :<

**Comment by porterdf** [comment] 2020-11-22 17:50
I second this request (for same reason as @kannes )

**Comment by kannes** [comment] 2020-11-22 19:51
Better add your thoughts on #20637, there is little chance anyone will read comments over here.
