### ISSUE TITLE
Exporting a raster layer to the "Geospatial PDF" format doesn't work

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#58883] opened 2024-09-26 17:16 UTC
### What is the bug or the crash?

Trying to export a single band raster layer to Geospatial PDF using the "Save Raster Layer as,,," dialog window (either as "Raw data" or "Rendered image"), the following error is displayed:
![image](https://github.com/user-attachments/assets/b7e886b8-446d-4d54-be4d-af78710cb52c)

```
Save Raster
Cannot write raster. Error code: data source creation
Cannot create new dataset PDFWriteableVectorDataset::Create() can only be called with nBands = 0 to create a vector-only PDF

```

### Steps to reproduce the issue

1. add a raster layer
2. export the raster layer using the "Save Raster Layer as,,," dialog window as "Geospatial PDF"

### Versions

On Windows, QGIS 3.38.3 and QGIS 3.34.11 with GDAL 3.9.2 and QGIS 3.39.0-Master with GDAL 3.10.0dev.

<table width='100%' align='center'><tr><td colspan="2"><b>Libraries</b></td><tr><td>QGIS version</td><td>3.39.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/e95907d1bf">e95907d1bf</a></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.6</td></tr><tr><td>GDAL/OGR version</td><td>3.10.0dev-75671414fe (Compiled)<br/>3.10.0dev-5ed310e955 (Running)</td></tr><tr><td>PROJ version</td><td>9.4.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.004 (2024-02-24)</td></tr><tr><td>GEOS version</td><td>3.12.2-CAPI-1.18.2</td></tr><tr><td>SQLite version</td><td>3.45.1</td></tr><tr><td>PDAL version</td><td>2.6.3</td></tr><tr><td>PostgreSQL client version</td><td>16.2</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 1903</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment] 2024-09-28 01:07
Closing as duplicate of #58891 (even if I see you've created that one first! just didn't notice)

**Closed by rouault** 2024-09-28 01:07 UTC
Labels: Data Provider, Bug
