### ISSUE TITLE
PDF raster data do not show, is ok on builds with older GDAL releases

### ISSUE THREAD

**Issue by JoonyDee** [qgis/QGIS#44522] opened 2021-08-02 22:21 UTC
### What is the bug or the crash?

While importing a PDF on a Rasterlayer,  the rasterdata are not shown any longer. 

### Steps to reproduce the issue

Drag PDF-File into Canvas

### Versions

3.18; 3.20, standalone and OSGeo4w-Installation; Full Deinstall and Newinstall

**Comment by gioman** [comment] 2021-08-03 07:36
> Drag PDF-File into Canvas

@JoonyDee please attach/link sample data.

**Comment by JoonyDee** [comment] 2021-08-03 08:48
![grafik](https://user-images.githubusercontent.com/88351431/127986536-5834df4c-fbe8-4f7b-a1f3-dac6fbb0629d.png)

**Comment by JoonyDee** [comment] 2021-08-03 08:49
so I installed BETA2007 an then all pixeldatas - even from older project dissapeared. 
After this I deleted QGIS 3.16 fully, deleted de_adv_Beta2007.tif manually and reinstalled. But the problem still exists.

**Comment by gioman** [comment] 2021-08-03 08:53
>  After this I deleted QGIS 3.16 fully, deleted de_adv_Beta2007.tif manually and reinstalled. But the problem still exists.

@JoonyDee add sample data.

**Comment by JoonyDee** [comment] 2021-08-03 11:40
[testpdf.pdf](https://github.com/qgis/QGIS/files/6923724/testpdf.pdf)

**Comment by gioman** [comment] 2021-08-03 11:45
> [testpdf.pdf](https://github.com/qgis/QGIS/files/6923724/testpdf.pdf)

@JoonyDee isn't this the expected result?

![image](https://user-images.githubusercontent.com/1951107/128009872-d5eb93e2-db19-4f44-8b52-3d618a0455d8.png)

**Comment by JoonyDee** [comment] 2021-08-03 12:13
Maybe something is wrong with GDAL PDF driver? IF I import this file, there is only a white Sqare instead of image-data.
So I installed QGIS 3.14 it works and looks lik yours.
but in QGIS 3.16 LTRit looks like that:
![grafik](https://user-images.githubusercontent.com/88351431/128013446-021947e0-01ad-43e9-a50b-a64a1f6b4b06.png)

**Comment by gioman** [comment] 2021-08-03 12:34
@JoonyDee it seems to be the case, I see what you see also, on QGIS 3.20 Windows that ships with a more recent GDAL version than on Ubuntu 20.04.

**Comment by JoonyDee** [comment] 2021-08-03 12:44
is it possibel to "Downgrade" GDAL-version?

**Comment by JoonyDee** [comment] 2021-08-03 14:36
latest stable Version:
![grafik](https://user-images.githubusercontent.com/88351431/128034346-e1c7db6e-8e1f-40dc-8c06-9c341f3160cb.png)
![grafik](https://user-images.githubusercontent.com/88351431/128034475-be72a8ba-a1c3-410e-aa24-db1fd32d2d76.png)

**Comment by JoonyDee** [comment] 2021-08-03 14:41
![grafik](https://user-images.githubusercontent.com/88351431/128035297-af98015e-adb5-49a1-8bfa-e961b2c57427.png)

**Comment by agiudiceandrea** [comment] 2021-08-03 15:03
@JoonyDee if the problem is related to the GDAL version, and the functionality works for you with GDAL 3.1.4, then you should be able to use any QGIS 3.16.x version (including the latest 3.16.9) installed using the standalone installers (*.exe installers) or the network installers (v1) from the **old OSGeo4W repository**:
![image](https://user-images.githubusercontent.com/16253859/128038625-186fb2f7-8e37-438a-8d81-16cc9b28fe9e.png)

**Comment by jef-n** [comment] 2021-11-16 16:32
Thought #45657 was a duplicate of #46065, but this one is even - much - older.

**Comment by bierdosenhalter** [comment] 2022-03-11 13:52
i have the same problem on windows 10. after upgrading from .16 to .18 lts all geopdf files render white. how to solve this?

**Comment by JoonyDee** [comment] 2022-03-11 15:21
Downgrade to older Gdal-version. No other solvation so far found.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: be de ha ***@***.***> Datum: 11.03.22  14:52  (GMT+01:00) An: qgis/QGIS ***@***.***> Cc: JoonyDee ***@***.***>, Mention ***@***.***> Betreff: Re: [qgis/QGIS] PDF raster data do not show, is ok on builds with
  older GDAL releases (#44522) 
i have the same problem on windows 10. after upgrading from .16 to .18 lts all geopdf files render white. how to solve this?

**Comment by alexbruy** [comment] 2023-10-06 07:04
Works fine with the latest master (3642c9cc40). Can we close?

**Comment by JoonyDee** [comment] 2023-10-07 23:38
yes, works fine. thank you for asking. cold case.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Alexander Bruy ***@***.***> Datum: 06.10.23  08:05  (GMT+00:00) An: qgis/QGIS ***@***.***> Cc: JoonyDee ***@***.***>, Mention ***@***.***> Betreff: Re: [qgis/QGIS] PDF raster data do not show, is ok on builds with
  older GDAL releases (#44522) 
Works fine with the latest master (3642c9c). Can we close?

**Closed** 2023-10-08 05:02 UTC
Labels: Feedback, Bug, Upstream
