### ISSUE TITLE
QGIS 3.10.10 and 3.14.16 report a python error on startup

### ISSUE THREAD

**Issue by gespiel** [qgis/QGIS#38720] opened 2020-09-13 20:38 UTC
Hi,
new releases report python error on startup

2020-09-13T22:30:44     WARNING    Python-Fehler : Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).

2020-09-13T22:30:44     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 777, in _import
              new_path = os.environ['PATH']
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 675, in __getitem__
              value = self._data[self.encodekey(key)]
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 744, in encodekey
              return encode(key).upper()
             RecursionError: maximum recursion depth exceeded

BS: win10

**Comment by nyalldawson** [comment] 2020-09-13 21:41
@jef-n this was likely caused by https://github.com/qgis/QGIS/pull/38420 -- can you investigate?

**Comment by PedroVenancio** [comment] 2020-09-13 21:54
@nyalldawson Duplicate of https://github.com/qgis/QGIS/issues/38483

**Comment by gioman** [comment] 2020-09-14 10:34
Closing as duplicate.

**Closed by gioman** 2020-09-14 10:34 UTC
Labels: Bug
