### ISSUE TITLE
(Polygonal) vector layer is displayed incorrectly with OTF EPSG:3574

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#32303] opened 2019-10-17 19:16 UTC
**Describe the bug**
Regions where there is no actual coverage from features on a polygon layer are shown "filled in" if I look at it in EPSG:3574 (North Pole LAEA). That's broken, corrupted rendering with artifacts (just filling keywords for the search here ;) ).

![image](https://user-images.githubusercontent.com/7661092/67039862-90adc480-f122-11e9-858c-c29927358f99.png)

**How to Reproduce**

1. Enter `world` in the coordinates box or load ne_110m_land.shp
2. Set the OTF CRS to EPSG:3574
3. Oceans will be filled with fake data

**QGIS and OS versions**

QGIS version | 3.8.3-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.13.1 | Running against Qt | 5.13.1
Compiled against GDAL/OGR | 3.0.1 | Running against GDAL/OGR | 3.0.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.2.0 | Running against PROJ | Rel. 6.2.0, September 1st, 2019
OS Version | Arch Linux |   |  

**Additional context**
Same(?) issue occurs in EPSG:102006 if you have the anti-meridian in your canvas.

**Comment by gioman** [comment] 2019-10-18 08:22
@kannes duplicate of https://github.com/qgis/QGIS/issues/30686 (point 6)?

**Comment by kannes** [comment] 2019-10-18 14:07
That's highly probable, I would support merging this issue to it.

**Comment by nyalldawson** [comment] 2019-10-25 06:14
Closed as duplicate

**Closed by nyalldawson** 2019-10-25 06:14 UTC
Labels: Bug, Feedback
