### ISSUE TITLE
Plombles with Raster Pixels to Points

### ISSUE THREAD

**Issue by spariyar** [qgis/QGIS#52587] opened 2023-04-07 07:25 UTC
### What is the bug or the crash?

While extracting points of each pixels of a raster for 12 hours, I got the following error:

Feature could not be written to F:/FCC/Modelling/Pixel_Points.shp: Feature creation error (OGR error: Failed to write shape object. The maximum file size of 4294967280 has been reached. The current record of size 28 cannot be added.)
Could not write feature into OUTPUT
Execution failed after 45770.10 seconds (12 hours 42 minutes 50 seconds)

I would be great if you could provide a solution for it.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/47468496/230562686-ad22909a-607e-416c-a4c7-68b987eb00fd.png)

### Versions

![image](https://user-images.githubusercontent.com/47468496/230562595-cc7bf8d8-c897-4333-8b5a-34e10ff36914.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2023-04-07 08:19
Shapefiles have a size limit of 2GB, though OGR can extend that to 4GB and you're hitting this limit. Exporting to a Geopackage instead should work, but at that size, I'd also question the need to export to vector format (maybe your processing could be faster using the raster files)

If you absolutely need the shapefile points, you can check that your raster has noData set for areas without usable data so they are skipped from the output and consider resampling your raster to a lower resolution or splitting it to smaller tiles and export those individually.

I'm closing this as it's not a bug, it's a limitation of the selected output format

**Closed by uclaros** 2023-04-07 08:19 UTC
Labels: Bug
