### ISSUE TITLE
QGIS 3.12.3 on OS X 10.13.6: control-click does not end adding feature on line layer

### ISSUE THREAD

**Issue by fgfletcher** [qgis/QGIS#36501] opened 2020-05-17 23:35 UTC
QGIS 3.12.3 
OS X 10.13.6
Layer > Create Layer > New Shapefile Layer, select Line layer type
enable editing
click click click - each click adds a new segment as it should
control-click (right-click on Macs) should end the addition, but it does not.
only way to exit the line creation mode is via Escape which also deletes the entire line.

**Comment by fgfletcher** [comment] 2020-05-18 01:52
Further information:
The standard Mac mouse only has 1 button (primary button) which is equivalent to left-click in Windows.  The convention is to treat control-click on Mac as a right-click (secondary button).  Some, but not all, Mac mice have extra buttons which can be used as a secondary button.
QGIS almost everywhere correctly treats control-click as a secondary button press - for example in bringing up menus for layer options.  It also did do correctly as late as QGIS 3.8 when adding features to shapefile layers.
However, in QGIS 3.12 it appears that this has not been implemented in the case of editing a line layer (or a polygon layer?).  This makes it impossible for Mac users who do not have a multi-button mouse to add features to such layers.
This should be easy to fix and should be given a high priority.

**Comment by gioman** [comment] 2020-05-18 12:36
@fgfletcher not sure why you closed this ticket, but it was duplicate of another one with the same report.

**Comment by fgfletcher** [comment] 2020-05-18 14:25
Closed in error...

**Comment by fgfletcher** [comment] 2020-05-18 14:26
Reopened

**Comment by gioman** [comment] 2020-05-18 14:26
> Closed in error...

Still duplicate :)

**Comment by fgfletcher** [comment] 2020-05-18 14:27
Duplicate of which report?

**Closed by gioman** 2020-05-18 14:26 UTC
Labels: Bug

**Comment by gioman** [comment] 2020-05-18 14:30
https://github.com/qgis/QGIS/issues/31279
