### ISSUE TITLE
Scale listbox do not working in QGIS version 3.30.0-'s-Hertogenbosch

### ISSUE THREAD

**Issue by micdeluca** [qgis/QGIS#52383] opened 2023-03-25 09:45 UTC
### What is the bug or the crash?

Scale listbox do not working in QGIS version 3.30.0-'s-Hertogenbosch.
![Scale_listbox](https://user-images.githubusercontent.com/65657745/227709664-0758d66b-6b48-4112-bd33-41180d5eec8a.gif)

### Steps to reproduce the issue

Open QGIS and click on scale listbox.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment] 2023-03-26 14:09
I confirm

## OSGeo4W 64 Win 10 64

**Comment by nicogodet** [comment] 2023-03-27 06:48
It seems that default scale are not listed anymore.
In project properties, you can define predefined project scale and they are listed in combobox.
![image](https://user-images.githubusercontent.com/39594821/227861998-af704d5f-f702-498d-a6ae-ee8b85cdbbbb.png)
![image](https://user-images.githubusercontent.com/39594821/227862037-909c7f27-b194-481d-b1f0-e01bc41cba58.png)

**Comment by micdeluca** [comment] 2023-03-27 07:16
True, if you define the default scales at the individual project level the listbox works.
However, you would expect the listbox to already work with the default scales at the general options level, and this does not happen.

**Comment by agiudiceandrea** [comment] 2023-03-27 19:19
It seems to me this issue is related to PR https://github.com/qgis/QGIS/pull/51728.

**Comment by pigreco** [comment] 2023-04-03 14:23
The problem is still present!!!
It seems that default scale are not listed anymore.

**Comment by 3nids** [comment] 2023-04-03 14:41
It works for me.

Do you have predefined scales in application settings (or is it blank)?  if not, can you try again with a new profile
in your project properties? if not, I guess they were deleted somehow.

**Comment by pigreco** [comment] 2023-04-03 14:52
@3nids @micdeluca 

The problem is that they look like this:
![image](https://user-images.githubusercontent.com/7631137/229546890-7023f5c5-3f9d-486b-95a4-e38b10ae251e.png)

**Comment by agiudiceandrea** [comment] 2023-04-03 15:10
Using the same user profile created in QGIS 3.28

in QGIS 3.28 the Predefined Scales (Setting->Option->Map Tools) are listed as:
![image](https://user-images.githubusercontent.com/16253859/229550109-5a0c65c6-4af3-467b-8bbf-eb71e4f0c169.png)

while in QGIS 3.30 are listed as:
![image](https://user-images.githubusercontent.com/16253859/229550590-a98416d1-95d9-4530-a1c8-5d42d3a703be.png)

Creating a new user profile with QGIS 3.30, the Predefined Scales list is empty:
![image](https://user-images.githubusercontent.com/16253859/229551598-1de9b2df-ab89-479a-a85c-37e4e4e562e8.png)

**Comment by 3nids** [comment] 2023-04-03 17:51
If I delete the predefined scales in the app settings and re-open QGIS they are set back to default.
Can you try this?

And which commit are you using?

**Comment by agiudiceandrea** [comment] 2023-04-03 19:44
@3nids, QGIS 3.30.1 on Windows (OSGeo4W).

Using QGIS 3.30 with a new user profile, the Predefined Scales list (in Setting->Option->Map Tools) is empty, while it should contain the predefined scales like using QGIS 3.28 and previous versions with a new user profile.

QGIS 3.30 stores the scales in QGIS3.ini as `scales=1:1000000, 1:500000, 1:250000, 1:100000, 1:50000, 1:25000, 1:10000, 1:5000, 1:2500, 1:1000, 1:500` while QGIS 3.28 and previous versions as  `scales="1:1000000,1:500000,1:250000,1:100000,1:50000,1:25000,1:10000,1:5000,1:2500,1:1000,1:500"`.

**Comment by agiudiceandrea** [comment] 2023-04-03 20:21
See also https://github.com/qgis/QGIS/pull/52511.

**Comment by 3nids** [comment] 2023-04-04 12:50
The scales are saved as a QStringList and not a QString anymore. The change in the ini file is expected (see https://stackoverflow.com/a/27558297/1548052)

Can you go to the advanced settings, delete the scale setting:
![image](https://user-images.githubusercontent.com/127259/229795725-a4d588a1-e639-4518-99b6-5b88f0ca1c9d.png)
save and reopen QGIS?

**Comment by agiudiceandrea** [comment] 2023-04-04 14:30
- Creating and using a new QGIS user profile with QGIS 3.30.1, the Predefined Scales list (in Setting->Option->Map Tools) is empty, while it should contain the predefined scales like using QGIS 3.28 and all previous versions.
![image](https://user-images.githubusercontent.com/16253859/229810396-25cbcb9d-0bf7-4769-9bd1-58ea8e78d929.png)
Is this expected? It seems to me this is a bug.
In the Advanced Settings, the `scales` setting is an empty QStringList
![image](https://user-images.githubusercontent.com/16253859/229810864-31e465b6-ef27-4b69-9aa9-187ab7975cf2.png)
Deleting such setting (using the "Delete Settings..." command) and restarting QGIS doesn't fix the issue: the Predefined Scales list is empty.
In this case, in order to restore the predefined scales, an user should go to Setting->Option->Map Tools and click on the "Reset to default scales" button.

- Using QGIS 3.30.1 with an user profile created by QGIS 3.28 and previous versions, using the "Delete Settings..." command in Advanced Settings to delete the `scales` setting doesn't actually delete the scale setting and doesn't fix the issue even restarting QGIS.
In such situation, in order to fix the issue, an user should either
  - remove the `1:1000000,1:500000,1:250000,1:100000,1:50000,1:25000,1:10000,1:5000,1:2500,1:1000,1:500` scale in the Predefined Scales list (Setting->Option->Map Tools) using the "Remove selected scale" button and restart QGIS (then the `scale` setting is displayed as of type `Invalid` and value `<Invalid>` in the Advanced Settings panel and as `scales=@Invalid()` in the QGIS3.ini file)
  - or reset the Predefined Scales list using the "Reset to default scales" button.

- "The scales are saved as a QStringList and not a QString anymore": this means the QGIS user Profile <= 3.28 are incompatible with QGIS 3.30 and vice versa at least for the predefined map scales setting and the map scales list combobox. Is this expected? If yes, I think the users should be informed about such incompatibility. Anyway I would have preferred no incompatibility.

**Comment by 3nids** [comment] 2023-04-05 09:39
> "The scales are saved as a QStringList and not a QString anymore": this means the QGIS user Profile <= 3.28 are incompatible with QGIS 3.30 and vice versa at least for the predefined map scales setting and the map scales list combobox. Is this expected? If yes, I think the users should be informed about such incompatibility. Anyway I would have preferred no incompatibility.

There is a migration of setting in place, so going from 3.28 to 3.30 should come without any issue to the user.

I wonder if you could try with https://github.com/qgis/QGIS/pull/52511 being merged now? (that might explain why I don't have any issue on my machine)

**Comment by agiudiceandrea** [comment] 2023-04-05 11:14
> I wonder if you could try with #52511 being merged now?

Testing the MinGW64 Windows Build from PR https://github.com/qgis/QGIS/pull/52511:

- Creating and using a new QGIS user profile with QGIS:
  - clicking on the scale listbox doesn't make QGIS crash, the scale listbox only displays the current scale
  - the Predefined Scales list (in Setting->Option->Map Tools) is empty
  - in Advanced Settings there is an empty `scales` QStringList setting, in QGIS3.ini there is a `scales=` setting

- Using QGIS with a QGIS user profile created by QGIS 3.28: same incorrect behaviour as before.

The author of the PR https://github.com/qgis/QGIS/pull/52511 it does not fix this issue.

**Comment by GvdDool** [comment] 2023-04-09 08:53
Question: Does the change from QString to QStringList change/affect the dropdown box's construction in the status bar? 

I am working on a Windows 13'' laptop with Full HD 1080 and have to disable the mScaleWidget in the Status bar to read the other elements in the bar because the width of the dropdown box is claiming all the space on the bar, compressing all the other items.     

<img width="941" alt="image" src="https://user-images.githubusercontent.com/54751004/230763412-e958263c-0366-4803-8df2-afeb93998676.png">

**Closed** 2023-04-19 19:21 UTC
Labels: GUI/UX, Regression, Project, Bug
