### ISSUE TITLE
Creating 3D View from raster

### ISSUE THREAD

**Issue by igh08191** [qgis/QGIS#37163] opened 2020-06-12 11:28 UTC
## User Feedback

I was trying to generate a 3D view from a raster image

## Report Details

**Crash ID**: [804cdac8c51c15dbb538ae7ef8302e112d3974cf](https://github.com/qgis/QGIS/search?q=804cdac8c51c15dbb538ae7ef8302e112d3974cf&type=Issues)

**Stack Trace**
<pre>
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
RegisterProcTableCallback :
Qt3DRender::Render::Renderer::performDraw :
Qt3DRender::Render::Renderer::executeCommandsSubmission :
Qt3DRender::Render::Renderer::submitRenderViews :
Qt3DRender::Render::Renderer::doRender :
Qt3DRender::Render::Renderer::render :
Qt3DRender::Render::AbstractRenderer::~AbstractRenderer :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.3-Bucure?ti
QGIS code revision: 8234261527
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment] 2020-06-12 11:31
@igh08191 please attach the offending project+data. Also try with a new QGIS profile.

**Comment by pjshelton** [comment] 2020-07-21 02:25
## User Feedback

Loaded two vector layers, one a LINESTRINGZ and the other a POINTZ.
Both given a 3D symbol. with elevation set to Vertices and absolute.
This maps fine with in the default 3D view. I can zoom and pan all I want.  it also works on both my screens. 
One driven by NVIDIA Quadro M1200 and the other Intel (R) HD Graphics P630. 

I add a dem raster and this works fine on both screens.

I then go into the 3D window attributes and set the terain to the dem and on accepting this change, QGIS crashes. This happens every time. 

## Report Details

**Crash ID**: [92ba7dbf94170c5a2e0269e64718c383c8318a33](https://github.com/qgis/QGIS/search?q=92ba7dbf94170c5a2e0269e64718c383c8318a33&type=Issues)


**Stack Trace**
<pre>
QByteArray::reallocData :
QgsDemHeightMapGenerator::heightAt qgsdemterraintileloader_p.cpp:284
QgsDemTerrainGenerator::heightAt qgsdemterraingenerator.cpp:70
Qgs3DUtils::extractPointPositions qgs3dutils.cpp:357
QgsInstancedPoint3DSymbolHandler::processFeature qgspoint3dsymbol_p.cpp:115
<lambda_658571170e9bb80885fc69fa9096f85e>::operator() qgsvectorlayerchunkloader_p.cpp:106
QtConcurrent::StoredFunctorCall0<void,<lambda_658571170e9bb80885fc69fa9096f85e> >::runFunctor qtconcurrentstoredfunctioncall.h:70
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.15.0-Master
QGIS code revision: 3af038f861
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.2.0dev
Running against GDAL: 3.2.0dev



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763


[testcrash.zip](https://github.com/qgis/QGIS/files/4950644/testcrash.zip)



[SunshineCoast_2014_LGA_SW_500000_7048000_1K_DEM_1m.zip](https://github.com/qgis/QGIS/files/4950931/SunshineCoast_2014_LGA_SW_500000_7048000_1K_DEM_1m.zip)


The 3D window also has trouble with the number of points in the vertices layer.

Below is the trace from the attempt to check with the smaller dem.  my real dem is too large to post, even after compression.

Crash ID: cf08beb76c1daed7d67a474b2a1033e499a6d50c


Stack Trace


QVector::first :
QgsDemHeightMapGenerator::heightAt qgsdemterraintileloader_p.cpp:292
QgsDemTerrainGenerator::heightAt qgsdemterraingenerator.cpp:70
Qgs3DUtils::extractPointPositions qgs3dutils.cpp:357
QgsInstancedPoint3DSymbolHandler::processFeature qgspoint3dsymbol_p.cpp:115
::operator() qgsvectorlayerchunkloader_p.cpp:106
QtConcurrent::StoredFunctorCall0 >::runFunctor qtconcurrentstoredfunctioncall.h:70
QtConcurrent::RunFunctionTask::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by pjshelton** [comment] 2020-07-21 02:30
and here is the geopackage with the point and line data 
[QTT20010-GS.zip](https://github.com/qgis/QGIS/files/4950957/QTT20010-GS.zip)

**Comment by PeterPetrik** [comment] 2020-10-09 15:47
duplicate of https://github.com/qgis/QGIS/issues/35483

**Closed by PeterPetrik** 2020-10-09 15:47 UTC
Labels: 3D, Bug, Crash/Data Corruption
