### ISSUE TITLE
Google satelite DON´T VIEW

### ISSUE THREAD

**Issue by jfrancamacho** [qgis/QGIS#40640] opened 2020-12-17 09:26 UTC
I can´t see de google satelite in my project.

Why??

Yesterdey, it´s ok, but today is wrong.

Bug fixing and feature development is a community responsibility, and not the responsibility of the QGIS project alone.
If this bug report or feature request is high-priority for you, we suggest engaging a QGIS developer or support organisation and financially sponsoring a fix

Checklist before submitting

- [ ] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [ ] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue
-->

**Describe the bug**

**How to Reproduce**

4. See error -->

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment] 2020-12-17 09:30
duplicate of https://github.com/qgis/QGIS/issues/40636

**Closed by gioman** 2020-12-17 09:30 UTC
Labels: Bug
