### ISSUE TITLE
Show Feature Count shows wrong numbers with Rule based classification

### ISSUE THREAD

**Issue by mirouml** [qgis/QGIS#39318] opened 2020-10-12 01:21 UTC
Show Feature Count shows wrong numbers with Rule based classification.

![number_of_features_wrong](https://user-images.githubusercontent.com/8064130/95695856-27e92180-0c7c-11eb-8455-5cbcd5de8512.png)

1. Load vector (postrges) layer into QGIS.
2. Right click on layer to "Show Feature Count"
3. In properties change Symbology to Rule-based
4. Create your rules based filter on attribute values
5. Click Test - gives correct value
6. Click ok
7. After closing the layer gets Rule-based symbology but the values for features count are wrong.

QGIS 3.14.15-Pi, Windows 10

**Comment by gioman** [comment] 2020-10-12 08:51
@mirouml related/duplicate of https://github.com/qgis/QGIS/issues/27893 ?

**Comment by mirouml** [comment] 2020-10-12 11:40
> @mirouml related/duplicate of #27893 ?

It might be related. But in my case funnily enough the ELSE value actually gives correct number - same as I obtain via sql query directly on database. So it is randomly some of the other rules - sometimes it is correct, sometimes it is more, never seen less, than what test returns - and test returns the same numbers as direct sql query.

**Comment by roya0045** [comment] 2020-10-12 21:37
are they wrong or assigned to the wrong symbol?

**Comment by mirouml** [comment] 2020-10-13 00:15
> are they wrong or assigned to the wrong symbol?

Definitely wrong. I have tested it now with similar data, and everything looks correct there. So it might be something very specific about these attributes or features. Will do more testing, and provide more feedback later.

**Closed** 2020-10-15 03:53 UTC
Labels: Bug, Feedback

**Comment by mirouml** [comment] 2020-10-15 03:58
I can't replicate it with other layers, so closing it for now, and possibly forever, unless I find out it is QGIS issue, and not data issue.

**Comment by roya0045** [comment] 2020-10-15 10:03
could you share the offending data if someone else would like to validate?
