### ISSUE TITLE
QGIS crashes when opening form / attribute table with reference relations

### ISSUE THREAD

**Issue by fahuber** [qgis/QGIS#35544] opened 2020-04-03 06:47 UTC
QGIS (3.10 LTR and 3.12 too) crashes immediately after opening the attribute table of postgis layers. 
The project (Layers, Froms, Relations) was generated by the plugin "Model Baker", but it not seems to be the origin of the problem.
All the layers have 1 or multiple reference relations to other tables (with and without geometries), inherited from Postgis («Discover Relations») and allocated the relation reference to the particular attributes in the form. If I remove the reference relations in the form, QGIS doesn’t crash.  I tested it on different PCs (Win 7 an Win 10) and clean QGIS profile, always the same problem. Also tried with GPKG-Layers -> same problem. 
With the same QGIS-project on QGIS 3.4, there is no problem with opening the attribute tables, but it's very slow.

## Report Details

**Crash ID**: [4decdae32da027e9adbe864b9f07094543bbe996]('https://github.com/qgis/QGIS/search?q=4decdae32da027e9adbe864b9f07094543bbe996&type=Issues')

**Stack Trace**
<pre>
QgsPostgresConn::PQgetResult qgspostgresconn.cpp:1402
QgsPostgresFeatureIterator::fetchFeature qgspostgresfeatureiterator.cpp:275
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:68
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:416
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:68
QgsFieldExpressionValuesGatherer::run qgsfeaturefiltermodel_p.h:63
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.4-A Coru�a
QGIS code revision: 10bc9f2ff2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by m-kuhn** [comment] 2020-04-03 07:53
There have been a lot of fixes for similar issues recently. Do you have a chance to test this on a nightly build of QGIS 3.12 or master (installed via OSGEO4W)?

**Comment by fahuber** [comment] 2020-04-03 09:07
I testet it with 3.13.0-Master (eef58e6e4f) and QGIS does not crash. 
But there is always a Critical Error when I open a form:
2020-04-03T11:03:04     CRITICAL    Qt : QLayout: Cannot add a null widget to QGridLayout/

**Comment by m-kuhn** [comment] 2020-04-03 09:14
Thanks for the feedback.
In this case it's likely fixed, relevant fixes have been backported to 3.12 and 3.10 and will appear in the next patch release towards end of April.
Meanwhile you can confirm this by opening the qgis-ltr-dev or qgis-release-dev versions via OSGEO4W.
Awaiting final confirmation before closing this issue.

**Comment by fahuber** [comment] 2020-04-03 09:49
Thank you. I testet it again with:
qgis-ltr-dev -> Crash
qgis-release-dev -> no Crash

**Comment by m-kuhn** [comment] 2020-04-03 09:55
Thanks

@troopa81 does this make sense to you? I don't think it was related to the missing https://github.com/qgis/QGIS/pull/34758 ?

**Comment by troopa81** [comment] 2020-04-06 07:36
> I don't think it was related to the missing #34758 ?

I also think its not related

But it could be this one #35198. I didn't want to backport those because there were a lot of modifications to be backported in LTR. 

@fahuber Do you have a project example and data sample. I could test backporting #35198 in 3.10 and check if it fixes the issue.

**Comment by fahuber** [comment] 2020-04-07 09:41
Here a project and data sample (GPKG):
[datasample.zip](https://github.com/qgis/QGIS/files/4443284/datasample.zip)

**Comment by m-kuhn** [comment] 2020-04-07 10:17
Thanks. Can you reproduce the issue with the GPKG? I think it is specific to postgres.

**Comment by fahuber** [comment] 2020-04-07 11:14
I have the same issue with GPKG as with postgres. Do you need the Interlis data for importing it into postgres with Model Baker?

**Comment by m-kuhn** [comment] 2020-04-07 11:24
If you can confirm with GPKG, that's perfect for now, thanks.

**Comment by troopa81** [comment] 2020-04-07 16:20
@fahuber I failed to reproduce on Linux with current QGIS-3.10

Here is how I try to reproduce

![refrel](https://user-images.githubusercontent.com/14358135/78693933-35ec6d00-78fc-11ea-8232-7b9df95dbdfe.gif)

Is it different from what you're doing? 

Or maybe the issue is Windows specific

**Comment by gioman** [comment] 2020-04-07 16:46
> Or maybe the issue is Windows specific

@troopa81 maybe, crash replicated on Windows here, no crash on Ubuntu 18.04. Both systems with QGIS LTR.

**Comment by troopa81** [comment] 2020-04-08 06:28
@gioman , Thanks, I'll try on Windows

**Comment by troopa81** [comment] 2020-04-15 07:44
Ok, I reproduce the crash and it appears that my modifications in master backported in 3.12 fixes it. So I backported them in 3.10.

**Comment by troopa81** [comment] 2020-04-16 07:36
@fahuber the PR has been merged, I close the issue. Please let me know, if you meet other issues with this widget.

**Closed by troopa81** 2020-04-16 07:36 UTC
Labels: Bug, Crash/Data Corruption, Relations
