### ISSUE TITLE
QGIS 3.10 crashes when trying to set location in GRASS project

### ISSUE THREAD

**Issue by borisforestal** [qgis/QGIS#34556] opened 2020-02-19 18:19 UTC
Crash ID: c6e2bc479940601b86c0f70aa8db49ca9e53ee75

Stack Trace

 ?? ::FNODOBFM::`string' :
gDispatchTableValues :
_C_specific_handler :
RtlpExecuteHandlerForUnwind :
RtlUnwindEx :
_C_specific_handler :
RtlpExecuteHandlerForException :
RtlDispatchException :
RtlRaiseStatus :
 ?? ::FNODOBFM::`string' :
longjmp :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
QgsGrassNewMapset::setGrassProjection qgsgrassnewmapset.cpp:476
QgsGrassNewMapset::pageSelected qgsgrassnewmapset.cpp:1397
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment] 2020-02-19 19:53
duplicate of https://github.com/qgis/QGIS/issues/28148

**Closed by gioman** 2020-02-19 19:53 UTC

**Comment by borisforestal** [comment] 2020-02-20 18:35
Thanks You Giovanni, I couldn't find answers about this crash, specially if
it have solution.
Boris

**Comment by gioman** [comment] 2020-02-20 18:38
> specially if it have solution.

@borisforestal unfortunately at the moment there is no solution implemented solution.

The solution has been proposed actually here

https://github.com/blazek/QGIS/commit/8707affbd

but has this bug affects only Windows it would mean to test this patch on Windows, and I'm not able to compile QGIS source code on such platform.

In general the GRASS plugin in QGIS is pretty much abandoned, is suggested to use GRASS using the QGIS processing toolbox.
