### ISSUE TITLE
Connecting to MSSQL with QGIS 3.14 on Windows 10

### ISSUE THREAD

**Issue by fzzylogic** [qgis/QGIS#37684] opened 2020-07-08 15:17 UTC
**Describe the bug**

When creating a new MSSQL connection with QGIS 3.14 on Windows 10, the OK button is greyed out unless Provider/DSN is entered. If that field is left blank though, the connection works, but can't be saved because OK is greyed out.

**How to Reproduce**
See bug description above.

1. In browser bar on the right, right click 'MSSQL' and select 'New connection'.
2. Add connection name, host and list databases. It will work if you have a local
   instance of MSSQL correctly configured. 
3. Click 'Test Connection' and that works too.
4. But OK is greyed out.
5. Add something (anything) in the Provider/DSN field.
6. OK is no longer greyed out.
7. Click OK to save the connection.
8. The connection won't work because of the value in Provider/DSN..

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
pluginbuilder3; 
plugin_reloader; 
QuickOSM; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing; 
save_attributes_processing

**Additional context**

**Comment by gioman** [comment] 2020-07-08 16:00
@fzzylogic is this a regression compared to previous QGIS releases?

**Comment by nyalldawson** [comment] 2020-07-08 20:24
Duplicate of https://github.com/qgis/QGIS/issues/37427

**Closed by nyalldawson** 2020-07-08 20:24 UTC
Labels: Bug, Feedback

**Comment by yeshibpc** [comment] 2021-05-31 10:28
I have an SDE database and want to connect to the MSQL database from QGIS. I have been trying to connect to MSQL. I can see my Database in List but the connection couldn't be done as I am getting an error message. I am getting the following error:

> Error opening connection: [Microsoft][ODBC SQL Server Driver]Cannot generate SSPI context [Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed QOD
![12](https://user-images.githubusercontent.com/85107722/120180079-2d0bd880-c22d-11eb-913a-66d69508d545.JPG)
![13](https://user-images.githubusercontent.com/85107722/120180097-2f6e3280-c22d-11eb-9a03-36729dacafa7.JPG)

BC3: Unable to c
![12](https://user-images.githubusercontent.com/85107722/120180122-35fcaa00-c22d-11eb-83d5-d70172c18251.JPG)
![13](https://user-images.githubusercontent.com/85107722/120180143-3bf28b00-c22d-11eb-82bd-78993498d08b.JPG)

onnect
