### ISSUE TITLE
.gov.uk WMS links - failure to load

### ISSUE THREAD

**Issue by nealgunn** [qgis/QGIS#33728] opened 2020-01-10 15:16 UTC
Hello,

I have recently transferred from QGIS version 3.6 to 3.10.
Previously I had a series of WMS links to UK Government environmental data. This included layers such as geology, coal mining risk, historical landfills, road layout, flood risk.

In the new version a number of these links still work, however, a number are inactive. The links on the government websites are still the same and when I removed and create a new WMS link the error message is the same. 

![QGIS WMS error message](https://user-images.githubusercontent.com/59736723/72163377-a5b19100-33bb-11ea-8165-684c52e98147.png)

How to Reproduce

An example of one of the WMS links that does not connect under the new QGIS version is

1) https://data.gov.uk/dataset/cf494c44-05cd-4060-a029-35937970c9c6/flood-map-for-planning-rivers-and-sea-flood-zone-2
2) Click on FloodMapForPlanningRiversAndSeaFloodZone2_WMS
3) Copy the address of the above page
4) Paste this into QGIS data source manager, WMS/WMTS as normal

Many thanks for your help in this

Neal

**Comment by i-s-o** [comment] 2020-01-10 19:27
I can confirm that this is an issue with 3.10.1 on Windows.

Your best option is to use the latest LTR (3.4.14).

Also, it looks like the issue is fixed in the development branch (as of 3.10.1-18), so it will work again in the next point release (3.10.2). If you *really* need this functionality in 3.10, you can side-install the nightly version (`rel-dev`) from OSGeo4W.

**Comment by uclaros** [comment] 2020-01-10 20:27
The problem is that the request to the server has a User-Agent set to `Mozilla/5.0 QGIS/3.10.0-A CoruÃ±a` and the server doesn't seem to like the accented letters and returns a 400 bad request.

**Comment by i-s-o** [comment] 2020-01-11 01:00
This is a duplicate of #32740, and it was fixed about two months ago by #32766.

> When it becomes `3.10.2-A CoruÃ±a` the bug will be back!

As I understand it, the `city name` part of the version string is no longer included in the User-Agent, so I don't think it will come back (as I mentioned, the nightly version of 3.10 works fine).

**Comment by gioman** [comment] 2020-01-12 11:40
@nealgunn confirmed it works on the nigthly release of 3.10.

**Closed by gioman** 2020-01-12 11:40 UTC
Labels: Bug
