### ISSUE TITLE
Crash when loading a Shapefile with NaN coordinates

### ISSUE THREAD

**Issue by Sjlver** [qgis/QGIS#41739] opened 2021-02-22 15:28 UTC
QGIS crashes when trying to open a ShapeFile where any of the coordinates is a NaN value.

I've attached an example. It can be created as follows:

```python
import geopandas as gpd
import pandas as pd
import numpy as np

df = pd.DataFrame({'title': ['Bern, Switzerland', 'NaLocation'],
                   'x': [7.447819, np.NaN],
                   'y': [46.947820, np.NaN] })
gdf = gpd.GeoDataFrame(df,
                       geometry=gpd.points_from_xy(df['x'], df['y']),
                       crs='EPSG:4326')
gdf.to_file('shapefile_with_nans.shp')
```

[shapefile_with_nans.zip](https://github.com/qgis/QGIS/files/6022996/shapefile_with_nans.zip)

Below is data from the crash reporting tool:

```
Crash ID: b541c228e3becd06d17a7cd04bfeaf46b1f8083d

Stack Trace

geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
SHPPartTypeName :
QgsOgrFeatureIterator::fetchFeature qgsogrfeatureiterator.cpp:387
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerFeatureIterator::fetchFeature qgsvectorlayerfeatureiterator.cpp:442
QgsAbstractFeatureIterator::nextFeature qgsfeatureiterator.cpp:63
QgsVectorLayerRenderer::drawRenderer qgsvectorlayerrenderer.cpp:346
QgsVectorLayerRenderer::render qgsvectorlayerrenderer.cpp:317
QgsMapRendererParallelJob::renderLayerStatic qgsmaprendererparalleljob.cpp:353
QtConcurrent::MapKernel::iterator,QtConcurrent::FunctionWrapper1 >::runIteration qtconcurrentmapkernel.h:69
QtConcurrent::MapKernel::iterator,QgsImageOperation::ProcessBlockUsingPixelOperation >::runIterations qtconcurrentmapkernel.h:78
QtConcurrent::IterateKernel::iterator,void>::forThreadFunction qtconcurrentiteratekernel.h:256
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :


QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4


System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
```

**Comment by roya0045** [comment] 2021-02-22 18:02
Seems like geos is crashing. Though having only one coord not nan is impossible as usually they all must be nan.

**Comment by agiudiceandrea** [comment] 2021-02-22 21:17
The "[ESRI Shapefile Technical Description](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf)" states that:

> Numeric Types - A shapefile stores integer and double-precision numbers. The remainder of this document
> will refer to the following types:
> - Integer: Signed 32-bit integer (4 bytes)
> - Double: Signed 64-bit IEEE double-precision floating point number (8 bytes)
> 
> Floating point numbers must be numeric values. Positive infinity, negative infinity, and Not-a-Number (NaN) values are not allowed in shapefiles.

and

> Point - A point consists of a pair of double-precision coordinates in the order X,Y.
> Point
> {
> Double X // X coordinate
> Double Y // Y coordinate
> }

So, it seems NaN values for coordinates are invalid in shapefile format.

**Comment by Sjlver** [comment] 2021-02-22 21:47
I absolutely agree that NaNs are probably not valid in a Shapefile. The point is, *it shouldn't crash*! An error message is fine; a crash however is a bug in my opinion.

**Comment by nyalldawson** [comment] 2021-02-22 21:50
Actually in this case it looks like the crash is happening within gdal itself. If you run ogrinfo on the dataset do you also see a crash?

**Comment by agiudiceandrea** [comment] 2021-02-22 22:05
GDAL/OGR 3.1.4 from OSGeo4W shell doesn't crash:

```
ogrinfo shapefile_with_nans\shapefile_with_nans.shp shapefile_with_nans
INFO: Open of `shapefile_with_nans.shp'
      using driver `ESRI Shapefile' successful.

Layer name: shapefile_with_nans
Metadata:
  DBF_DATE_LAST_UPDATE=2021-02-22
Geometry: Point
Feature Count: 2
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
title: String (80.0)
x: Real (24.15)
y: Real (24.15)
OGRFeature(shapefile_with_nans):0
  title (String) = Bern, Switzerland
  x (Real) = 7.447819000000000
  y (Real) = 46.947820000000000
  POINT (7.447819 46.94782)

OGRFeature(shapefile_with_nans):1
  title (String) = NaLocation
  x (Real) = (null)
  y (Real) = (null)
  POINT (nan nan)
```

**Comment by agiudiceandrea** [comment] 2021-02-22 22:43
QGIS 3.4.5 (OSGeo4W, GEOS 3.7.0, GDAL/OGR 2.4.0) doesn't crash adding the provided shapefile layer.

**Comment by jgrocha** [comment] 2021-03-05 21:29
Confirmed on current master.

`ogr` reads the file, as QGIS.

The crash is rendering related, not on the data itself. I've created a hidden group and added the shapefile to it. The shape is properly read and the attribute table is fine QGIS crashes when trying to render it.

![shape with nulls](https://user-images.githubusercontent.com/163681/110175471-b744cc00-7df9-11eb-96d2-d3777e868452.png)

**Comment by jratike80** [comment] 2021-03-07 21:19
For information, ArcGIS Pro opens the shapefile without warnings. Running Validate geometries reports a few warnings, though:

```
 WARNING 000442: null geometry at 1 in shapefile_with_nans
 WARNING 000442: bad dataset extent at -1 in shapefile_with_nans
 WARNING 000442: could not find spatial index at -1 in shapefile_with_nans
```

When I saved the data into a new shapefile the NULL geometry was converted into this

```
OGRFeature(esri_out):1
  title (String) = NaLocation
  x (Real) = 0.000000000000000
  y (Real) = 0.000000000000000
  POINT (-1.79769313486232E+308 -1.79769313486232E+308)
```

Check geometries gives only one warning about the shapefile written by ESRI:

` WARNING 000442: null geometry at 1 in esri_out`

That NaNs exist does not seem to be very critical because they do not make any real issue with ESRI products. Data can be opened and converted into new feature classes.

**Comment by nyalldawson** [comment] 2021-03-08 04:47
This crash is definitely coming from GDAL. You can reproduce it with ogrinfo if you pass a "-spat 7 46 8 47" filter.

Closing as an upstream bug.

**Closed by nyalldawson** 2021-03-08 04:47 UTC
Labels: Bug, Crash/Data Corruption, PyQGIS, Regression

**Comment by jratike80** [comment] 2021-03-08 07:00
Works for me on Windows with GDAL 3.1.4 and 3.3.0dev.

```
ogrinfo esri_out.shp -al -spat 7 46 8 47
INFO: Open of `esri_out.shp'
      using driver `ESRI Shapefile' successful.

Layer name: esri_out
Metadata:
  DBF_DATE_LAST_UPDATE=2021-03-07
Geometry: Point
Feature Count: 2
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
title: String (80.0)
x: Real (19.15)
y: Real (19.15)
OGRFeature(esri_out):0
  title (String) = Bern, Switzerland
  x (Real) = 7.447819000000000
  y (Real) = 46.947820000000000
  POINT (7.447819 46.94782)
```

**Comment by jgrocha** [comment] 2021-03-08 08:44
Hi @jratike80 

My `ogrinfo` crashes with `-spat 7 46 8 47`. I suspect that GDAL is able to read the file, but it is not able to apply filters. That's why QGIS also fails to render it.

```bash
$ ogrinfo shapefile_with_nans.shp -al -spat 7 46 8 47
INFO: Open of `shapefile_with_nans.shp'
      using driver `ESRI Shapefile' successful.

Layer name: shapefile_with_nans
Metadata:
  DBF_DATE_LAST_UPDATE=2021-02-22
Geometry: Point
Feature Count: 2
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
title: String (80.0)
x: Real (24.15)
y: Real (24.15)
OGRFeature(shapefile_with_nans):0
  title (String) = Bern, Switzerland
  x (Real) = 7.447819000000000
  y (Real) = 46.947820000000000
  POINT (7.447819 46.94782)

Segmentation fault (core dumped)
```
Ubuntu, GDAL 3.3.0dev-f6689b6533-dirty,

**Comment by jratike80** [comment] 2021-03-08 08:51
Interesting. There is definitely no crash on Windows and another data window finds correctly no features.
```
ogrinfo esri_out.shp -al -spat 6 46 7 47 --debug on
Feature Count: 
...
title: String (80.0)
x: Real (19.15)
y: Real (19.15)
SHAPE: Clear panSpatialFIDs
GDAL: GDALClose(esri_out.shp, this=00000271A1D468D0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```
