### ISSUE TITLE
It crashes every time i closse the program

### ISSUE THREAD

**Issue by viniciuspg** [qgis/QGIS#30660] opened 2019-07-10 16:31 UTC
**Describe the bug**
<It crashes every time I close the aplication. I know, there are lots of the same topic, but It's my first time here and it is not clear how to fix this.>

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

<h2. User Feedback

It Crashes every time i close the aplication.

h2. Report Details

*Crash ID*: 41bd556bfb4cb3857ad8b303df49560eb10217ac

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.5-Madeira
QGIS code revision: commit:89ee6f6e23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763
>

**Comment by gioman** [comment] 2019-07-10 16:43
@viniciuspg duplicate of several other identical reports.

**Closed by gioman** 2019-07-10 16:43 UTC
Labels: Bug
