### ISSUE TITLE
extend/trim crash

### ISSUE THREAD

**Issue by Andrea-Zep** [qgis/QGIS#31864] opened 2019-09-18 07:41 UTC
**Describe the bug**

**How to Reproduce**
file attached
[extend-trim.zip](https://github.com/qgis/QGIS/files/3625043/extend-trim.zip)

## User Feedback

i created two line vectors, then i esed the tool extend trim

## Report Details

*Crash ID*: bb19b0c6e91b041c46ef852eaf2f70ec5e0b1658

*Stack Trace*
<pre>
QgsVectorLayer::beginEditCommand :
QgsMapToolTrimExtendFeature::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Additional context**

**Comment by elpaso** [comment] 2019-09-18 08:23
Hi, I've tested this on latest 3.8 on both windows and Linux and I cannot reproduce it.
Can you test latest master (nightly build for windows from OSGEO4W) ?

**Comment by lbartoletti** [comment] 2019-09-18 09:23
@Andrea-Zep Please test with latest version of QGIS 3.8 we have maybe already fixed it in https://github.com/qgis/QGIS/pull/31020/commits/6bc37103ac42af7151263390dd871d6e14d42b94

**Comment by Andrea-Zep** [comment] 2019-09-18 09:28
> Hi, I've tested this on latest 3.8 on both windows and Linux and I cannot reproduce it.
> Can you test latest master (nightly build for windows from OSGEO4W) ?

I haven't downloaded the 3.8.4 yet, i'll try

**Comment by nirvn** [comment] 2019-09-25 07:34
@Andrea-Zep , can you confirm the crash has been fixed on 3.8.4?

**Comment by Andrea-Zep** [comment] 2019-09-25 09:31
> @Andrea-Zep , can you confirm the crash has been fixed on 3.8.4?

Confirm

**Comment by nirvn** [comment] 2019-09-25 09:31
Thanks, enjoy your QGIS :smile:

**Closed by nirvn** 2019-09-25 09:31 UTC
Labels: Bug, Feedback

**Comment by Andrea-Zep** [comment] 2019-09-25 09:33
> Thanks, enjoy your QGIS 😄

thank a lot for the support

**Comment by GSavelev-VSEGEI** [comment] 2020-02-13 23:06
Same bug on 3.10.2 with the following stack trace:

```
Crash ID: ID not generated due to missing information.

Your version of QGIS install might not have debug information included or we couldn't get crash information.


Stack Trace
Stack trace could not be generated.


QGIS Info


System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

```
tried to repeat the action with new profile - same problem

**Comment by gioman** [comment] 2020-02-14 09:48
> tried to repeat the action with new profile - same problem

@GSavelev-VSEGEI if the problem persist in recent versions please open a new ticket and attach/link the necessary sample data to replicate with also the detailed steps that lead to the crash.
