### ISSUE TITLE
[DB-Manager] primary key of postgresql table not recognized on the Info tab

### ISSUE THREAD

**Issue by SamyFR** [qgis/QGIS#34885] opened 2020-03-05 10:49 UTC
In QGis 3.12, the Info tab returns incorrect information about the primary key of a postgresql table :
[...]
### General info
Relation type: Table
[...]
**_No primary key defined for this table!_**
[...]
### Constraints
| Name         | Type    | Column(s) |
|--------------|---------|-----------|
| my_pkey | **_Unknown_** | id        |

This is not very important because the layer can be correctly added to the canvas.

In QGis 3.10, this information is correct : 
### Constraints
| Name         | Type    | Column(s) |
|--------------|---------|-----------|
| my_pkey | **_Primary key_** | id        |

**Comment by elpaso** [comment] 2020-03-05 12:41
Can you please attach a SQL dump to reproduce the issue?

**Comment by gioman** [comment] 2020-03-05 14:37
@elpaso I confirm the issue, I seen it yesterday and it was on my todo list to report it today.

This is not about a specific table/layer, just import any vector in DB Manager. Regardless of what is chosen about the "primary key" option

![Screenshot_20200305_143318](https://user-images.githubusercontent.com/1951107/75991516-7a947b00-5eee-11ea-977e-58cd31274402.png)

![Screenshot_20200305_143520](https://user-images.githubusercontent.com/1951107/75991559-8bdd8780-5eee-11ea-854d-1ddae248c3ee.png)

The results is always a table that **has** a primary key as expected

![Screenshot_20200305_143619](https://user-images.githubusercontent.com/1951107/75991681-b7f90880-5eee-11ea-90ed-f6abc2859e9d.png)


but that is not recognized anymore by QGIS/DB Manager

![Screenshot_20200305_143336](https://user-images.githubusercontent.com/1951107/75991709-c6472480-5eee-11ea-8ad8-e4b3e43f023d.png)

![Screenshot_20200305_143350](https://user-images.githubusercontent.com/1951107/75991716-ca734200-5eee-11ea-87d1-017e4e3da67a.png)

**Comment by gioman** [comment] 2020-03-05 14:39
On LTR 3.10.3 is OK

![Screenshot_20200305_143932](https://user-images.githubusercontent.com/1951107/75991940-276ef800-5eef-11ea-9411-9c114f14283a.png)

**Comment by elpaso** [comment] 2020-03-05 14:44
I cannot reproduce on master.
Can you attach a SQL dump?

![immagine](https://user-images.githubusercontent.com/142164/75992380-28f0ee00-5ef8-11ea-93b8-0636068334e1.png)

**Comment by gioman** [comment] 2020-03-05 14:47
> I cannot reproduce on master.

@elpaso testing now too.

>  Can you attach a SQL dump?

I will, but there is not much point, it happens with *any*vector imported using DB Manager (at least).

**Comment by elpaso** [comment] 2020-03-05 14:48
ok, so it does not happen with pre-existing table but only with newly created tables after an import from DB manager?

Does it happen if you import the (say) shapefile with drag&drop from the browser?

**Comment by elpaso** [comment] 2020-03-05 14:49
(because the OP didn't mention any import procedure)

**Comment by gioman** [comment] 2020-03-05 14:50
> ok, so it does not happen with pre-existing table but only with newly created tables after an import from DB manager?
> 
> Does it happen if you import the (say) shapefile with drag&drop from the browser?

@elpaso testing both things now.

**Comment by gioman** [comment] 2020-03-05 14:56
> Does it happen if you import the (say) shapefile with drag&drop from the browser?

@elpaso importing by other means than DB Manager is ok, meaning that the PK is correctly seen in DB manager.

**Comment by gioman** [comment] 2020-03-05 14:58
> ok, so it does not happen with pre-existing table but only with newly created tables after an import from DB manager?

@elpaso tables imported or created in the past (with previous QGIS releases) seem ok.

**Comment by elpaso** [comment] 2020-03-05 15:00
Maybe worth trying to compare the imported tables from the two procedures, it would be also useful to check if restarting QGIS after the DB-manager import "fixes" the issue.

**Comment by gioman** [comment] 2020-03-05 15:03
> it would be also useful to check if restarting QGIS after the DB-manager import "fixes" the issue.

@elpaso it does. As it does for this https://github.com/qgis/QGIS/issues/34862

**Comment by SamyFR** [comment] 2020-03-05 15:03
> ok, so it does not happen with pre-existing table but only with newly created tables after an import from DB manager?

No, my table is not newly created.

> Can` you please attach a SQL dump to reproduce the issue?

https://framabin.org/p/?92be4c92b69cf460#Px1pM/9P0nZXIqgB7E8gNo0vrBhcALKNZdA5IMkKir4=
I can't attach any sql or txt file in GitHub...

**Comment by gioman** [comment] 2020-03-05 15:04
>  I can't attach any sql or txt file in GitHub...

@SamyFR 
you can attach ZIPs.

**Comment by SamyFR** [comment] 2020-03-05 15:09
>  you can attach ZIPs.

Sorry, I can't with sql, txt, or zip file of only few Ko. Message is "Something went really wrong, and we can't process that file. Try again"

**Comment by elpaso** [comment] 2020-03-05 15:11
@SamyFR thanks, but

ERRORE:  il tipo "pelotes.precisions_localisations2" non esiste
RIGA 22:     precision_lieu pelotes.precisions_localisations2

**Comment by SamyFR** [comment] 2020-03-05 15:16
Arf, sorry, you can replace this user-defined TYPE with TEXT

**Comment by elpaso** [comment] 2020-03-05 15:24
I commented out the triggers and all looks good to me on master:

![immagine](https://user-images.githubusercontent.com/142164/75996121-b125c200-5efd-11ea-8915-7e0d9b53ca46.png)

**Comment by gioman** [comment] 2020-03-05 15:26
> I commented out the triggers and all looks good to me on master:

@elpaso testing on master ASAP

**Comment by gioman** [comment] 2020-03-05 16:56
> I commented out the triggers and all looks good to me on master:

@elpaso I have not tested @SamyFR because I don't think is necessary, meaning that this problem shows with any imported layer with DB Manager.

I have tested on master, and when clicking on that tables ("info" tab) I'm greeted with

```
TypeError: must be real number, not list 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_manager.py", line 100, in itemChanged
    self.refreshTabs()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_manager.py", line 143, in refreshTabs
    self.info.showInfo(item)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\info_viewer.py", line 74, in showInfo
    self._showTableInfo(item)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\info_viewer.py", line 133, in _showTableInfo
    html += table.info().toHtml()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\info_model.py", line 361, in toHtml
    ret = self.getTableInfo()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\postgis\info_model.py", line 231, in getTableInfo
    ret = TableInfo.getTableInfo(self)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\info_model.py", line 303, in getTableInfo
    spatial_info = self.spatialInfo()
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\postgis\info_model.py", line 250, in spatialInfo
    return VectorTableInfo.spatialInfo(self)
  File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\info_model.py", line 400, in spatialInfo
    estimated_extent_str = '%.5f, %.5f - %.5f, %.5f' % self.table.estimatedExtent
TypeError: must be real number, not list
```

that was reported already on another ticket.

**Comment by gioman** [comment] 2020-03-05 17:07
> Maybe worth trying to compare the imported tables from the two procedures

@elpaso attached, 1 with DBM the other with Processing.

**Comment by gioman** [comment] 2020-03-05 17:10
@elpaso this fix https://github.com/qgis/QGIS/issues/34862#issuecomment-595297514 fixed also the issue in this ticket.

**Comment by gioman** [comment] 2020-03-06 10:04
@elpaso this should also be fixed by your PR https://github.com/qgis/QGIS/pull/34890 closing?

**Closed** 2020-08-04 22:05 UTC
Labels: Bug, DB Manager, Regression
