### ISSUE TITLE
GeoPDF: Some layer names come across wrong

### ISSUE THREAD

**Issue by davidlgalt** [qgis/QGIS#36619] opened 2020-05-21 10:25 UTC
Some layers have the prefix "map: " added to them in the finished PDF.

**Comment by rouault** [comment] 2020-05-25 19:52
Please provide a way to reproduce: project + procedure followed

**Comment by nyalldawson** [comment] 2020-05-25 20:17
All good - this one is on the qgis side. I'm on it.

**Comment by nyalldawson** [comment] 2020-05-28 01:19
Duplicate of #33306

**Closed by nyalldawson** 2020-05-28 01:19 UTC
Labels: Bug, Feedback, Print Layouts
