### ISSUE TITLE
QGIS crashed while creating a layout from a template in Layout Manager

### ISSUE THREAD

**Issue by AvilinTsimafei** [qgis/QGIS#31300] opened 2019-08-19 16:03 UTC
## User Feedback

1. Installed two versions of QGIS - 2.18 Las Palmas and 3.8.2 Zanzibar. 
2. On both versions Easy Custom Labeling and Memory Layer Saver plugins were installed. 
3. Then in one day the labels just disappeared for some unknown reason.
4. Tried to open the project with labels in both QGIS versions, but there were no them;
5. Uninstalled these two versions and installed QGIS 3.4.1.
6. Opened this new installed version, added above mentioned plugins and try to make labels visible;
7. Copied .qpt template from my custom folder, but it was not added for some reason;
8. The path to .qtp was displayed and while creating it the QGIS was crashed.
QGIS was a little bit slowly during a work, may be, because of browser was consuming to much memory.
Operation sys: Win 10, x64;

## Report Details

*Crash ID*: 41bd556bfb4cb3857ad8b303df49560eb10217ac

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment] 2019-08-19 16:06
Is not clear to me how we could replicate this, any chance you can attach a sample project (with data)?

**Comment by AvilinTsimafei** [comment] 2019-08-20 10:09
Hi Giovanni!
I guess it might happen because of this broken label added with "Easy Custom Labeling". This is label's attribute table
<img width="658" alt="Capture" src="https://user-images.githubusercontent.com/29484378/63338225-b301ac80-c342-11e9-8c79-9f778dfb627a.PNG">

when a new label is added, then some coordinates and simple information is displayed: 
<img width="522" alt="Capture" src="https://user-images.githubusercontent.com/29484378/63338347-e5aba500-c342-11e9-86e9-8cf98517107a.PNG">

the main issue seems to be a missing label related data.
Can I somehow send you this broken added label? But it stored with Memory Layer Saver.

I've got today the same exception: 
Crash ID: ba57c275ca02c4382c6bad72ed8a9ae520f48257


Stack Trace


proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

The steps were just to play with this label and close the QGIS.

**Comment by roya0045** [comment] 2019-08-20 12:38
Isn't this issue more about the plugins than QGIS itself?

**Comment by gioman** [comment] 2019-08-20 15:05
> Stack Trace
> 
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist :

this part of the stack trace is the same as of many other tickets. Anyway, you should check if the crash is caused by the 3rd party plugin "easy custom labelling" or if it happens regardless if you don't have it installed at all.

**Comment by roya0045** [comment] 2019-08-20 15:16
But if the plugin changes the project file and then qgis doesn't know how to handle the project without the plugin. Or if the Template file contains element that depend on the plugin, this would explain the crash.

**Comment by gioman** [comment] 2019-08-20 15:17
> But if the plugin changes the project file and then qgis doesn't know how to handle the project without the plugin. Or if the Template file contains element that depend on the plugin, this would explain the crash.

yes, but QGIS should handle such cases more gracefully and not crash. A test project would really help here.

**Comment by AvilinTsimafei** [comment] 2019-08-22 06:46
whould it be enough to provide just a .qgs file and some related .shp files?

**Comment by gioman** [comment] 2019-08-22 08:07
> whould it be enough to provide just a .qgs file and some related .shp files?

yes, if does help replicate the issue.

**Comment by jef-n** [comment] 2019-08-27 12:13
Duplicate of #28104

**Closed** 2019-08-27 14:36 UTC
Labels: Bug, Feedback, Print Layouts
