### ISSUE TITLE
Add "zoom last" and "zoom next" buttons to layout navigation toolbar

### ISSUE THREAD

**Issue by EricUniqueUsername** [qgis/QGIS#58413] opened 2024-08-16 14:09 UTC
### Feature description

I am new to QGIS, having recently made the break from Arc.
When working in the layout window, I was hoping to find a button or keystroke combo to go backward or forward in zoom choices. I would expect this to be a basic option to be found in the layout navigation toolbar, analogous to what one finds in the layout toolbar of ArcMap, or to hitting `Alt + →` or `Alt + ←` on the keyboard to zoom a page in a pdf reader.  
What I'm looking for would be the equivalent of the `zoom last` and `zoom next` buttons currently found in the map navigation toolbar of the main map window, but for the layout, not the map extent.  
Thanks for considering this request.  
Eric
 
Making this request at the suggestion of a user in this Stack Exchange thread:  
https://gis.stackexchange.com/q/484885/52318

**Comment by YoannQDQ** [comment] 2024-09-29 15:17
Duplicate of #22077

**Closed** 2024-10-22 19:06 UTC
Labels: Feature Request, Print Layouts
