### ISSUE TITLE
TilesXYZ ignores selected layer CRS

### ISSUE THREAD

**Issue by frafra** [qgis/QGIS#43904] opened 2021-06-24 10:54 UTC
I have two layers: a vector layer (EPSG:25833) and a OpenStreetMap silly map raster tile (EPSG:3857). QGIS project CRS is set to match the raster tile (EPSG:3857).

When I run "Generate XYZ tiles (MBTiles)" from the graphical user interface, I can select the map canvas extent to generate the tiles, which works as expected, or the vector tile, which produces tiles in the wrong position.

I see the extent as `xmin,xmax,ymin,ymax [EPSG:3857]` if I use the map canvas extent, while I see  the extent as `xmin,xmax,ymin,ymax [EPSG:3857]` if I select the vector layer. CRSs are then correctly specified, but TilesXYZ does not convert the coordinates into the project coordinates, producing incorrect results sometimes.

Setting the project CRS to match the vector layer CRS works.

**Comment by gioman** [comment] 2021-06-24 10:57
> a vector layer (EPSG:25833)

@frafra can you attach it?

**Comment by frafra** [comment] 2021-06-24 11:13
@gioman I am sorry, it contains sensible information I cannot share. It contains some areas near Oslo, Norway, but when I generate the tiles it produces images located in northern France.

I have the same problem when I use Python and I use a simple `layer.extent()` as extent instead of `QgsReferencedRectangle(layer.extent(), layer.crs())`.

**Comment by gioman** [comment] 2021-06-24 11:15
>  I am sorry, it contains sensible information I cannot share.

@frafra it is just needed a rectangle with the bbox of your layer.

**Comment by frafra** [comment] 2021-06-24 11:18
> @frafra it is just needed a rectangle with the bbox of your layer.

Sure, that should work as well :)

`195250.0000,292500.0000,6550500.0000,6654750.0000 [EPSG:25833]`

**Comment by gioman** [comment] 2021-06-24 11:25
@frafra what QGIS version are you using? and on what operating system?

**Comment by frafra** [comment] 2021-06-24 11:34
@gioman 3.16.4-Hannover, revision 654e76b3cb, Windows 10.

**Comment by gioman** [comment] 2021-06-24 11:39
I think the problem is that mbtiles are (by design) always generated in 3857, and the tool do not reprojects the chosen extent if this is not in 3857 and the project is (because if the project and extent are both the same and not in 3857 it seems to work ok).

**Comment by alexbruy** [comment] 2023-10-05 13:36
I'd say this is a won't fix, as MBTiles is always in EPSG:3857.

**Closed by alexbruy** 2023-10-05 13:36 UTC
Labels: Processing, Bug
