### ISSUE TITLE
layer of processing result is placed on top of the layer stack

### ISSUE THREAD

**Issue by peter-morcinek** [qgis/QGIS#56863] opened 2024-03-15 06:52 UTC
### What is the bug or the crash?

The result of any processing tool is placed on top of the layers stack view. Expected behaviour would place it next to the active layer in the layer stack view. So it did in former versions.

### Steps to reproduce the issue

set any layer active, choose a vector processing tool, the output maybe set to 'temporary layer' or 'save as file', then the output layer is added to the top of layer stack view

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.34.4-Prizren | QGIS-Codeversion | decd43dc
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.18
GDAL-Version | 3.8.4
PROJ-Version | 9.3.1
EPSG-Registraturdatenbankversion | v10.098 (2023-11-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.41.1
PDAL-Version | 2.6.0
PostgreSQL-Client-Version | 16.1
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
AnotherDXF2Shape | 1.3.1
BulkVectorExport | 1.1
coveragebuilder | version 0.5.0
DeltaCoordHSB VS-Code | 1.0
joinmultiplelines | Version 0.4.1
KpOhm_VS-Code | 0.5
latlontools | 3.6.19
loadthemall | 3.4
MastErdHSB VS-Code | 1.0
MinDistHSB VS-Code | 1.0
PolygonsParallelToLine | 1.0
polystrip | 3.0.1
ProjectPackager | 0.7.2
reconstruct_line | 0.7
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS-Version
3.34.4-Prizren
QGIS-Codeversion
[decd43dc](https://github.com/qgis/QGIS/commit/decd43dc)
Qt-Version
5.15.3
Python-Version
3.9.18
GDAL-Version
3.8.4
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
16.1
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
AnotherDXF2Shape
1.3.1
BulkVectorExport
1.1
coveragebuilder
version 0.5.0
DeltaCoordHSB VS-Code
1.0
joinmultiplelines
Version 0.4.1
KpOhm_VS-Code
0.5
latlontools
3.6.19
loadthemall
3.4
MastErdHSB VS-Code
1.0
MinDistHSB VS-Code
1.0
PolygonsParallelToLine
1.0
polystrip
3.0.1
ProjectPackager
0.7.2
reconstruct_line
0.7
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment] 2024-03-19 17:55
Duplicate of #56129

**Closed by DelazJ** 2024-03-19 17:55 UTC
Labels: Bug
