### ISSUE TITLE
Qgis crashes when I close the program

### ISSUE THREAD

**Issue by pedr0H** [qgis/QGIS#30753] opened 2019-07-16 20:44 UTC
Crash ID: 5ad41d6be94809f981e2ec9b06a0e20f1d0b0a87

Stack Trace

proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char * __ptr64 * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.9-Madeira
QGIS code revision: 54585165bb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by gioman** [comment] 2019-07-17 08:39
Duplicate of several other tickets, i.e. https://github.com/qgis/QGIS/issues/30494

**Closed by gioman** 2019-07-17 08:39 UTC
Labels: Bug
