### ISSUE TITLE
QGIS Browser: Add option in contextmenu to delete connections

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39771] opened 2020-11-03 05:47 UTC
**Feature description**

QGIS Browser: Add option in contextmenu to delete connections:

<img src="https://user-images.githubusercontent.com/20856381/97952122-9cefd880-1d9c-11eb-9bb5-d9b1ae8616f0.png" width="300">

After click on _Delete Connections..._ the same `Manage Connections` UI as used for _Load Connections..._ could be used with a _Delete_ instead of an _Import_ button: 

<img src="https://user-images.githubusercontent.com/20856381/97953240-3076d880-1da0-11eb-9c90-7b45d1128812.png" width="300">

**Additional context**

Currently it's not possible to delete e.g. multiple `WMS` / `WFS` / `XYZ Tiles` connections at once.

This is also not possible by using multiselect for multiple connections, related issue: https://github.com/qgis/QGIS/issues/26276

So if there are many connections, it's cumbersome to delete all connections which currently has to be done by deleting one by one.

The suggested implementation allows to delete all or multiple connections easily.

**Comment by amano-takahisa** [comment] 2021-11-04 16:13
Until QGIS supports this feature, the following script may be useful.
```python
import re

pattern = 'qgis/connections-xyz/[0-9]+'  # <- modify this.
repattern = re.compile(pattern)
qs = QSettings()

for k in qs.allKeys():
    m = re.match(repattern, k)
    if m is not None:
        print(k)
        qs.remove(k)
        
iface.reloadConnections()

```

**Comment by nyalldawson** [comment] 2024-06-18 00:19
Duplicate of #57788 26276

**Closed by nyalldawson** 2024-06-18 00:19 UTC
Labels: Feature Request, QGIS Browser
