### ISSUE TITLE
Export layer with Boolean field results in Integer field

### ISSUE THREAD

**Issue by meyerlor** [qgis/QGIS#57359] opened 2024-05-07 10:51 UTC
### What is the bug or the crash?

I refactored a layer, the resulting layer has a field of the type "boolean" - when i export this layer as .shp or MapInfo .tab the boolean field shows up as a Integer field.

Refactored memory layer:
![grafik](https://github.com/qgis/QGIS/assets/15894401/9ad0bc44-9f74-479b-9cc2-8588659620c0)

Export options:
![grafik](https://github.com/qgis/QGIS/assets/15894401/a225d57f-a543-43fe-82c3-bbd2e6326700)

Resulting layer:
![grafik](https://github.com/qgis/QGIS/assets/15894401/78ca9287-19dd-493a-b491-f6c52d2493d7)

### Steps to reproduce the issue

1.Have a layer with boolean field
2. Export layer
3. Open layer -> boolean field is Integer or String

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.5
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.9
lizmap | 4.3.11
PluginLoadTimes | 4.0.2
processing_saga_nextgen | 1.0.0
qfieldsync | v4.9.1
simplesvg | 3.0.3
slyr | 7.3.0
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.36.1-Maidenhead
QGIS code revision
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.9
lizmap
4.3.11
PluginLoadTimes
4.0.2
processing_saga_nextgen
1.0.0
qfieldsync
v4.9.1
simplesvg
3.0.3
slyr
7.3.0
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment] 2024-05-07 12:21
This is not a bug. ESRI Shapefile does not support boolean field type (boolean are converted to integer by QGIS on save).
Switch to Geopackage if you want boolean field.

**Comment by meyerlor** [comment] 2024-05-07 13:33
MapInfo supports boolean though, and the same happens when exporting to MapInfo

**Comment by rouault** [comment] 2024-05-07 23:30
> ESRI Shapefile does not support boolean field type

actually they do (at least DBF supports it. Support for it in ESRI software itself is half convincing). Support added for that in the ESRI Shapefile driver of GDAL 3.9

> MapInfo supports boolean though, and the same happens when exporting to MapInfo

@meyerlor Could you attacha MapInfo dataset with a boolean field? Ideally both a .mid/.mif and a .tab/.dat/.map

**Comment by meyerlor** [comment] 2024-05-08 05:38
@rouault sure thing:
[MapInfo_Trees_Logical.zip](https://github.com/qgis/QGIS/files/15244264/MapInfo_Trees_Logical.zip)
The field "Kronensicherung" is a field of type "logical"

**Comment by nyalldawson** [comment] 2024-05-08 21:11
Closing as an upstream (gdal) issue

**Closed by nyalldawson** 2024-05-08 21:11 UTC
Labels: Data Provider, Bug
