### ISSUE TITLE
Model is not working correctly if opened with QGIS browser on Windows

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#39749] opened 2020-11-02 11:13 UTC
**Describe the bug**

QGIS model is not working correctly if opened with QGIS browser on Windows, i.e. available fields in vector field input are not updated accordingly if selected layer for vector layer input is changed by the user.

**How to Reproduce**

1. Download and extract [model_and_sample_data.zip](https://github.com/qgis/QGIS/files/5474419/model_and_sample_data.zip).
2. Add both layers of the GPKG to a QGIS project and have a look at the field names.
3. Open the model included in the zip file with QGIS browser.
4. Switch the layers for the vector layer inputs in the model UI and have a look at the fields shown in the vector field inputs. 
5. See error: The vector fields in the vector field inputs are not all the time matching the fields of a selected layer.

![model_not_working_correctly](https://user-images.githubusercontent.com/20856381/97860402-5b125400-1d02-11eb-8c19-f2ee671bf3c1.gif)

**QGIS and OS versions**

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
QuickOSM; 
db_manager; 
MetaSearch; 
processing

**Additional context**

- If the model is opened and run from the proccesing toolbox panel (_Open Existing Model..._) it is working as expected on Windows.

- On Linux it is working as expected also if opened with QGIS browser.

**Comment by gioman** [comment] 2020-11-03 14:22
@pathmapper works fine on 3.16.0 on Ubuntu 20.04

**Comment by gioman** [comment] 2020-11-03 14:22
>     * On Linux it is working as expected also if opened with QGIS browser.

I overlooked this, sorry.

**Comment by gioman** [comment] 2020-11-03 14:27
> See error: The vector fields in the vector field inputs are not all the time matching the fields of a selected layer.

@pathmapper confirmed on windows 10 and QGIS 3.16

**Comment by nyalldawson** [comment] 2021-06-14 03:39
Duplicate of #42181

**Closed by nyalldawson** 2021-06-14 03:39 UTC
Labels: Bug, Modeller, Processing, Windows
