### ISSUE TITLE
QGIS 3.6 crashes Opening 3D Views with WMTS and WCS Layer in TOC 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29194] opened 2019-02-25 14:18 UTC
Author Name: **Flo Ju** (Flo Ju)
Original Redmine Issue: [21377](https://issues.qgis.org/issues/21377)
Affected QGIS version: 3.6.0
Redmine category:3d

---

## User Feedback

Opening 3D Views with WMTS and WCS Layer in TOC 

## Report Details

*Crash ID*: 05ce4fcfbe6a9c5216be39579ce6404490379032

*Stack Trace*
```
QMetaObject::cast :
QgsMapRendererJob::prepareLabelCache :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererSequentialJob::start :
QgsTerrainGenerator::typeToString :
QgsTerrainGenerator::typeToString :
QgsFlatTerrainGenerator::createChunkLoader :
QgsCameraController::camera :
QgsCameraController::camera :
Qgs3DMapScene::onFrameTriggered :
QMetaObject::activate :
Qt3DLogic::QFrameAction::triggered :
Qt3DLogic::QFrameAction::onTriggered :
Qt3DLogic::QFrameAction::onTriggered :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
sourceSelectProviders :
sourceSelectProviders :
sourceSelectProviders :
QgsRasterPipe::QgsRasterPipe :
QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererSequentialJob::start :
QgsTerrainGenerator::typeToString :
QgsTerrainGenerator::typeToString :
QgsFlatTerrainGenerator::createChunkLoader :
QgsCameraController::camera :
QgsCameraController::camera :
QMetaObject::activate :
QMetaObject::activate :
Qgs3DAlgorithms::qt_metacast :
QgsTerrainGenerator::typeToString :
QMetaObject::activate :
QMetaObject::activate :
QMetaObject::activate :
QFutureWatcherBase::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.6.0-Noosa
QGIS code revision: 58734527ab
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.0
Running against GDAL: 2.4.0

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by wonder-sk** [comment] 2019-05-27 11:52
Duplicate of #26706

**Closed by wonder-sk** 2019-05-27 11:52 UTC
Labels: 3D, Bug, Crash/Data Corruption, High Priority
