### ISSUE TITLE
No transform available between EPSG:21781 and EPSG:2056

### ISSUE THREAD

**Issue by romainbh** [qgis/QGIS#32919] opened 2019-11-18 07:18 UTC
**Describe the bug**
QGIS shows an error message "No transform available between EPSG:21781 and EPSG:2056" when your project is in EPSG:2056 or 21781 and your layer in EPSG:21781 or 2056 (not the same EPSG in the project/the layer).
This occurs only with the latest update made by OSGeo4W (made on 2019.11.18).
Tested with a blank user profile and a new installation of QGIS.
[Here is a GPKG with two layers, one per EPSG](https://github.com/qgis/QGIS/files/3857224/test_epsg.zip)

![image](https://user-images.githubusercontent.com/18001925/69031307-118a0580-09da-11ea-8c50-05e92e9a161b.png)

When you try to download "proj-datumgrid-europe-latest.zip" and install CHENyx06a.gsb, an other error message says that QGIS can't access to the proj folder in the default profile folder.

**How to Reproduce**

1. Create a blank project and set the EPSG in 2056 or 21781
2. Add a layer that is in EPSG:21781 or 2056 (not the same as the project)
3. See the error message

**QGIS and OS versions**

Version de QGIS
3.10.0-A Coruña
Révision du code
6ffa89eb3e
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.2
Utilisé avec GDAL/OGR
3.0.2
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.2.1
Fonctionne avec PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 10 (10.0)
Extensions Python actives
changeDataSource; 
DataPlotly; 
disconnected-islands; 
geomapfish_locator; 
geometry_paster; 
GroupStats; 
LAStools; 
MemoryLayerSaver; 
mmqgis; 
networks; 
NNJoin; 
pdaltools; 
plugin_reloader; 
pointsamplingtool; 
profiletool; 
qchainage; 
qgis_resource_sharing; 
quick_map_services; 
refFunctions; 
searchlayers; 
SelvansGeo; 
splitmultipart; 
SpreadsheetLayers; 
db_manager; 
MetaSearch; 
processing; 
qgis2web

**Comment by gioman** [comment] 2019-11-18 09:49
@romainbh duplicate of https://github.com/qgis/QGIS/issues/32795 ?

**Comment by romainbh** [comment] 2019-11-18 10:08
> @romainbh duplicate of #32795 ?

It seems to be a duplicate, sorry I didn't find the other post.

**Closed** 2019-11-18 10:09 UTC
Labels: Bug, Feedback
