### ISSUE TITLE
Composition controlled by Atlas, it is not possible to include dynamically raster images.

### ISSUE THREAD

**Issue by respeso** [qgis/QGIS#49252] opened 2022-07-06 11:46 UTC
### What is the bug or the crash?

Inclue a raster image is not possible  in a composition controlled by Atlas, because when the image path is defined (dynamically), interface automatically changes and forces you to declare a SVG.

### Steps to reproduce the issue

1.- Go to Project-> Composition
2.- Add image
3.- Select Image Raster and define file path by 'Expresion String Constructor'
4.- When click Ok and return to previous window the 'Image Raster' radio button change to 'SVG image'

### Versions

3.26.0-Buenos Aires

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2022-07-06 11:51
Duplicate of https://github.com/qgis/QGIS/issues/47981, https://github.com/qgis/QGIS/issues/38031, https://github.com/qgis/QGIS/issues/37804 and #49165

**Comment by news24lor** [comment] 2022-08-06 10:58
I confirm the Bug that has been present for many versions, maybe 1 year.
I have two large projects, one created over 1 year ago and a new one very similar. In the one from 1 year ago I had 34 png raster images that were loaded as screenshots from an ATLAS (T01.png, T02.png, etc.) and the variable entered ("concat(@project_folder, ....) worked and still works fine the old Layout in the latest version of QGIS.
I have a new very similar project with as many as 64 raster images that I need to load into an ATLAS, one after the other as screenshots, and with the same Layout, the same variable, all the same but incredibly in the picture area the selector changes to SVG removing the Raster file and so no images are loaded.
So the bug is something that conflicts within the new Layout in the last year versions.
This bug makes a very useful automatism inside QGIS unusable.

**Comment by nicogodet** [comment] 2022-08-08 06:40
@news24lor You NEED to enable the atlas preview to render your images.
![image](https://user-images.githubusercontent.com/39594821/183354632-af1e58dd-6eef-4690-9a11-3ebda1d2acc3.png)

Otherwise, the expression can not be evaluated and is considered as invalid (and switch to SVG).
The SVG switch is not an easy fix (see https://github.com/qgis/QGIS/pull/49615).
Can you close this ticket as it duplicates the ones mentioned by @roya0045 ?

**Comment by news24lor** [comment] 2022-08-08 11:51
Yes, the Atlas is enabled. The ATLAS in the main map works.
The problem is only in the picture (png) loaded as geographic position of the atlas, a screenshot with expression. One year ago another ATLAS worked very well with external picture loaded with expression.

**Comment by nicogodet** [comment] 2022-08-08 11:54
@news24lor Can you past your expression and previsualisation of the evaluated expression (display below white box in expression builder) ?
And a screenshot of your issue ?

**Comment by news24lor** [comment] 2022-08-08 21:24
The ATLAS is enabled.

The expression is the same.
`concat(@project_folder, '/logo/basetable/',"tables", '.png')`
The path is "/myhd/works/projectpi/is1/logo/basetable/T01.png", "/myhd/works/projectpi/is1/logo/basetable/T02.png", ...

In the old layout works.
In Picture properties the button "Raster image" is always selected.




The same expression in the new layout with ATLAS enabled
`concat(@project_folder, '/logo/basetable/',"tables", '.png')`
The path is "/myhd/works/projectpi/is2/logo/basetable/T01.png", "/myhd/works/projectpi/is2/logo/basetable/T02.png", ...

In Picture properties the button "Raster image" switch to "SVG image" immediately after the Expression is entered and the "Raster image" button is no longer selectable

**Comment by nicogodet** [comment] 2022-08-09 07:07
This is what I do:
![export14](https://user-images.githubusercontent.com/39594821/183585945-5f62df19-b311-44e1-914d-b44e2566a66b.gif)

The same exact steps does not work for you ?

**Comment by news24lor** [comment] 2022-08-10 11:36
No when I select Atlas the button does not return to Raster image but it remains to SVG.
In the old layout worked.

**Comment by gioman** [comment] 2022-08-10 11:58
> In the old layout worked.

@news24lor do you mean an older QGIS release? like 3.22?

**Comment by nicogodet** [comment] 2022-08-10 12:07
@news24lor in that case, could you share a project with sample data to reproduce the issue ?

**Comment by news24lor** [comment] 2022-08-10 17:51
It worked in an old version but I don't remember the exact version (more than one year ago). I'll do one thing. I disable all plug-in and I install a clean version of 3.26 and I create a new simple ATLAS and I try to load external pictures with the same expression. I will try and report back.

**Comment by news24lor** [comment] 2022-09-01 18:04
I tried with QGIS 3.26.2 in macOS and Windows. It is the same bug. If I enter an expression to load multiple raster files, the Picture object changes to SVG files and pressing the ATLAS button to see the various maps the rasters disappear. No files are loaded.

![layouyt_atlas_bug_load_calculated_rasterfile](https://user-images.githubusercontent.com/33484600/187981690-d7d66837-62cd-431a-b77e-463421d8782c.gif)

**Comment by news24lor** [comment] 2022-09-17 09:35
I have now solved it. I had reinstalled Qgis from scratch and the problem is solved

**Closed** 2022-09-17 09:50 UTC
Labels: Feedback, Raster, Bug, Print Layouts
