### ISSUE TITLE
QGIS crashes after choosing "New shapefile layer"-->Filename

### ISSUE THREAD

**Issue by JulianAnton** [qgis/QGIS#32233] opened 2019-10-13 13:26 UTC
Hi all,

i just installed QGIS Desktop 3.4.12 ltr via the OSGeo4W-Installer after deleting all other QGIS-stuff on my PC from past versions.
After opening QGIS and choosing "New Shapefile Layer" i click the "..."-button for filename. This opens the explorer to "Save as …". An then always QGIS crashes with the following Report:

_**rash Report Details**

Crash ID: 5488363ea6517dc4eb88c311509b7da21181c4fa

Stack Trace

RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1962
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1962
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1962
ICoCreateInstanceEx objact.cxx:2029
CComActivator::DoCreateInstance immact.hxx:385
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
SHELL32_GetIconOverlayManager :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763_

I deinstalled an reinstalled QGIS but the error still occurs. It's no longer possible for me to use QGIS.
Can somebody help me?
Thank you and have a good sunday!

Julian

**Comment by roya0045** [comment] 2019-10-13 14:43
related to #30667, can you try  with a clean profile and no plugins activated?

Otherwise you could test the standalone installer.

**Comment by nyalldawson** [comment] 2019-10-13 19:43
This is a local issue, caused by other software installed on the machine which has registered a buggy icon handler. It's not qgis issue or something which can be fixed in qgis.

**Closed by nyalldawson** 2019-10-13 19:43 UTC
Labels: Bug, Feedback
