### ISSUE TITLE
Max/Min Band Rendering decimal point issue

### ISSUE THREAD

**Issue by GustyLa** [qgis/QGIS#34426] opened 2020-02-12 10:10 UTC
**Describe the bug**
If deleting the raster rendering Max/Min value entirely, it is no longer possible to enter a point as a decimal separator. It is possible to enter a comma, but that is not a valid separator and 

**How to Reproduce**
1. Go to 'Layer properties'
2. Click on 'Band Rendering'
3. Click on 'Min' or 'Max'
4. Delete value entirely
5. Enter decimal number

**QGIS and OS versions**

QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | crayfish; d3datavis; dataexplorer; Multi_Ring_Buffer; profiletool; rivergis; SelectWithin; timemanager; ViewshedAnalysis; db_manager; MetaSearch; processing

**Comment by gioman** [comment] 2020-02-12 10:19
@GustyLa duplicate of https://github.com/qgis/QGIS/issues/33859 ?

**Comment by GustyLa** [comment] 2020-02-12 10:56
Exactly the same. Found a workaround by setting the User Interface Translation to American English, and the Locale to English UnitedStates (en_US).

**Closed** 2020-02-12 12:13 UTC
Labels: Bug, Feedback
