### ISSUE TITLE
Crash when saving Qgis-project on geopackage

### ISSUE THREAD

**Issue by dariaqu** [qgis/QGIS#31689] opened 2019-09-11 10:53 UTC
## User Feedback

the crash happens when i save a qgis project on geopackage

## Report Details

*Crash ID*: 4457b00eb6f619d2f3169d3365f1e5934a2ed4c5

*Stack Trace*
<pre>
QString::multiArg :
QString::arg :
isProvider :
QgsProject::write :
CPLStringList::operator[] :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by elpaso** [comment] 2019-09-11 11:24
Duplicate of #31310

**Closed by elpaso** 2019-09-11 11:24 UTC
