### ISSUE TITLE
Tile layer misalignement

### ISSUE THREAD

**Issue by cbertelli** [qgis/QGIS#46917] opened 2022-01-20 15:46 UTC
### What is the bug or the crash?

Tile layers are misaligned in the new version.
The misalignement es even stronger with high resolution tiles.
It didn't happen on previous versionas.

### Steps to reproduce the issue

Open an XYZ layer in the browser pan (or add a new layer with the proper URI and tile size)
add it to the project
zoom on it and it does not work properly, even zooming shows a strange behaviour.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.22.3-Białowieża | Revisione codice QGIS | 1628765ec7
-- | -- | -- | --
Versione Qt | 5.15.2
Versione Python | 3.9.5
Versione GDAL/OGR | 3.3.2
Versione PROJ | 8.1.1
Versione database del Registro EPSG | v10.028 (2021-07-07)
Versione GEOS | 3.9.1-CAPI-1.14.2
Versione SQLite | 3.35.2
Versione PDAL | 2.3.0
Versione client PostgreSQL | 12.3
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.6
Versione QScintilla2 | 2.11.5
Versione SO | macOS Mojave (10.14)
  |   |   |  
Plugins Python attivi
OnlineRoutingMapper | 0.9
QuickOSM | 2.0.0
pg_raster_import | 1.0.10
geo_sim_processing | 1.2.0
changeDataSource | 3.1
quick_map_services | 0.19.27
GeoCoding | 2.18
qgis2web | 3.16.0
web2qgis | 0.2.0
latlontools | 3.6.1
gpapext | 0.1
Generalizer3 | 1.0
geocode_sqlite | 0.6
LayerBoard | 1.0.1
qgis-maptiler-plugin | 2.0.0
openlayers_plugin | 2.0.0
raster_tracer | 0.3.2
StreetView | 3.2
NeatMap | 1.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

--

**Comment by gioman** [comment] 2022-01-20 16:42
Can you provide a screenshot and a URL? Maybe is related to https://github.com/qgis/QGIS/issues/46882 ?

**Comment by elpaso** [comment] 2022-01-20 16:45
I checked and it's caused by https://github.com/qgis/QGIS/pull/46816 reverting that one fixes this issue, OTOH my approach https://github.com/qgis/QGIS/pull/46801 fixes the original issue without introducing this bug.

**Comment by caheri** [comment] 2022-01-20 22:11
Hi good afternoon, I have the same issue with QGIS 3.22.3 in MacOS Monterey, are there some way to get a previous version of QGIS, maybe (3.22.2) for reinstall?

**Comment by pathmapper** [comment] 2022-01-21 03:35
Is this bug specific for MacOS? 

Can't replicate with the standard OSM XYZ connection on Windows 10 and Ubuntu 20.04.

> are there some way to get a previous version of QGIS, maybe (3.22.2) for reinstall?

@caheri -> https://qgis.org/downloads/macos/pr/

**Comment by caheri** [comment] 2022-01-21 03:53
@pathmapper Thanks so much!!

I appreciate it

**Comment by cbertelli** [comment] 2022-01-28 16:03
has the fix suggested by @elpaso resolved the issue? Is a silently amended 3.22.3 version available? Should we wait for 3.22.4? I don't want to stress anyone, just a suggestion is gratefully accepted.

**Comment by gioman** [comment] 2022-01-28 16:07
@cbertelli the patch that has introduced this bug has not (I think( been reverted see https://github.com/qgis/QGIS/issues/46917#issuecomment-1017702695

**Comment by garvamel** [comment] 2022-02-20 19:29
My reproduction of the issue. Specs are: QGIS 3.22.3, MacOS Monterrey (same issue with Catalina, though). Tile layer loaded with QuickMapServices Plugin.

https://user-images.githubusercontent.com/17742377/154860520-04b0ca17-1f29-4f40-b176-5a88c9ed3b95.mov

**Comment by gioman** [comment] 2022-02-21 07:57
Isn't this the same as https://github.com/qgis/QGIS/issues/46882 ?

**Comment by cbertelli** [comment] 2022-02-22 17:41
Yes, it is, I think.
Will it be fixed with 3.22.4 or should we expect it for 3.24?

**Comment by gioman** [comment] 2022-02-22 17:43
> Will it be fixed with 3.22.4 or should we expect it for 3.24?

it is fixed in 3.24 but I don't know of it has been backported.

**Closed by gioman** 2022-02-22 17:43 UTC
Labels: Map and Legend, Regression, Bug

**Comment by cbertelli** [comment] 2022-02-22 17:51
Thank you.

**Comment by garvamel** [comment] 2022-03-04 13:47
Thanks everyone. It works properly on 3.22.4

**Comment by cbertelli** [comment] 2022-03-04 13:50
Yes, thank you very much.
