### ISSUE TITLE
Algorithm "Difference" failing to execute properly

### ISSUE THREAD

**Issue by CG-Purdue** [qgis/QGIS#49291] opened 2022-07-08 18:27 UTC
### What is the bug or the crash?

The algorithm "Difference", used to extract features from an input layer that fall outside of features in the overlay layer has not been working properly since at least v3.16.4 of QGIS. I've attached a representative log from QGIS v3.26.0 of a failed attempt at extracting features of a point layer that fall outside of a polygon layer. 
   * macOS Big Sur v11.6.7
   * Macbook Pro 16" 2019
![Difference Failure v3 26 0](https://user-images.githubusercontent.com/108951737/178047876-4c336e97-c8d1-4996-8458-0710ed30fd83.png)

### Steps to reproduce the issue

1. Vector... Geoprocessing Tools... Difference
2. Choose point vector input layer (EPSG:26916]
3. Choose polygon vector overlay layer (EPSG:26916]
4. Click "run"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 11.6
  |   |   |  
Active Python plugins
Multi_Ring_Buffer | 1.1
mmqgis | 2020.1.16
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 11.6

Active Python plugins
Multi_Ring_Buffer
1.1
mmqgis
2020.1.16
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The problem appeared in all versions subsequent to v3.10.6.

**Comment by roya0045** [comment] 2022-07-08 19:51
This might be mac specific, on windows GEOS is at 3.10.3-CAPI-1.16.1.

Does it happen with specific data only or any data that you tried to use?

**Comment by agiudiceandrea** [comment] 2022-07-09 10:47
@roya0045 the issue does occur on Windows with OSGeo4W QGIS 3.22.8 and 3.26.0  with GEOS 3.10.3. To reproduce the issue, just use a polygon layer with 1 polygon and a point layer with 1 point placed inside the polygon, then use the Difference alg with the point layer as Input layer and the polygon layer as the Overlay layer.

It seems to me the issue is due to an underlying QgsGeos class issue already reported at https://github.com/qgis/QGIS/pull/35776#issuecomment-616808246 for QGIS 3.13.0-Master and GEOS 3.8.1.
Such issue was fixed in QGIS 3.14.0 (GEOS 3.8.1) with https://github.com/qgis/QGIS/pull/35882 by @nyalldawson and the fix worked until QGIS 3.16.3 (GEOS 3.8.1).
The issue occurred again starting from QGIS 3.16.4 (GEOS 3.8.1) and for all subsequent QGIS/GEOS versions.

**Comment by CG-Purdue** [comment] 2022-07-09 12:06
> @roya0045 the issue does occur on Windows with OSGeo4W QGIS 3.22.8 and 3.26.0 with GEOS 3.10.3. To reproduce the issue, just use a polygon layer with 1 polygon and a point layer with 1 point placed inside the polygon, then use the Difference alg with the point layer as Input layer and the polygon layer as the Overlay layer.
> 
> It seems to me the issue is due to an underlying QgsGeos class issue already reported at [#35776 (comment)](https://github.com/qgis/QGIS/pull/35776#issuecomment-616808246) for QGIS 3.13.0-Master and GEOS 3.8.1. Such issue was fixed in QGIS 3.14.0 (GEOS 3.8.1) with #35882 by @nyalldawson and the fix worked until QGIS 3.16.3 (GEOS 3.8.1). The issue occurred again starting from QGIS 3.16.4 (GEOS 3.8.1) and for all subsequent QGIS/GEOS versions.
> 
> I suppose the underlying QgsGeos issue was inadvertently reintroduced with #41422 by @nirvn.

Thank you @agiudiceandrea for your insight on the occurrence of the problem.

I am just a simple QGIS user, not a developer. 

I use this algorithm alot for "cleaning" point data sets generated by grain yield monitors (e.g., corn or soybean fields) by creating "buffer" polygons and using the Difference algorithm to remove data points from fixed distances at either end of a field of harvested grain to eliminate the "ramp up" and "ramp down" nature of the physics of grain flow data in a combine harvester that occurs at the beginning and end of harvest passes in a field. With the newer releases of QGIS, I am forced to remove the data by "brute force" selection and removal of the data. That significantly slows my work flow. 

**What is the procedure within the QGIS developers' community for escalating this, apparently, known issue with the Difference algorithm in multiple versions of QGIS in order to fix the problem?**

**Comment by agiudiceandrea** [comment] 2022-07-09 12:15
@CG-Purdue I will try to submit a patch to fix the issue. In the mean time,
I think you can achieve the same results in the mean time at least in two ways:
- using the "Clip" algorithm with the original point layer and the original polygon layer and then use the Difference algorithm with the clipped point layer (the output of the Clip algorithm) and the original point layer
- using the "Extract by location" algorithm and selecting the "disjoint" geometric predicate

**Comment by agiudiceandrea** [comment] 2022-07-09 15:56
Other reports on Difference alg issue with points layer:
- https://gis.stackexchange.com/questions/359232/using-qgis-difference-with-point-and-polygon
- https://gis.stackexchange.com/questions/263664/points-and-polygons-difference-issue-qgis
- https://gis.stackexchange.com/questions/411433/qgis-3-18-difference-doesnt-work-with-points-as-the-input-layer

**Comment by CG-Purdue** [comment] 2022-07-09 18:20
Thank you, @agiudiceandrea .

How will users know if a patch becomes available?

**Closed** 2022-07-12 01:42 UTC
Labels: Processing, Bug

**Comment by agiudiceandrea** [comment] 2022-07-12 05:43
@CG-Purdue, the fix will be in the upcoming QGIS 3.26.1 version and in the QGIS LTR 3.22.10 version.
