### ISSUE TITLE
Spyware detection by QGIS

### ISSUE THREAD

**Issue by KacanuHa** [qgis/QGIS#36540] opened 2020-05-19 06:52 UTC
Hello QGIS Team,
we faced a sudden detection of spyware by QGIS, due to its nature I would like to provide you more information by an e-mail and not make it public.
Is it possible to do it?
Thanks

**Comment by elpaso** [comment] 2020-05-19 07:01
We do have a security@qgis.org private address but the chances that it is just a false positive are high. Have you already seen this message? https://github.com/qgis/QGIS-Website/issues/758#issuecomment-630520562

**Comment by jef-n** [comment] 2020-05-19 07:11
@KacanuHa related to #36401 or #32247 ?

**Comment by KacanuHa** [comment] 2020-05-19 07:19
ah, sorry. Someone already made it public. Here is some additional information:
TrendMicro Support:
"While this tool helps with administrative tasks,  attackers could also potentially use this tool to perform system profiling and other malicious purposes.".
VirusTotal:
Detected by THOR APT Scanner
Matched Rule: CN_Hacktools_tools_CMDget
Ruleset: Hacktools

I have this issue with version 2.18, 3.4 and 3.10 
but when it is already reported then it is ok. Hope that there will be workaround instead of adding an exclusions.
Thanks

**Comment by jef-n** [comment] 2020-05-19 07:23
Duplicate of #36401

**Closed** 2020-05-19 07:22 UTC
