### ISSUE TITLE
Issue with NSIS on Windows 

### ISSUE THREAD

**Issue by Jabern** [qgis/QGIS#39626] opened 2020-10-26 17:03 UTC
Hello , so i'm trying to pack my QGIS build , so everything went fine the build is a success and everything running fine , coming to the packing step i followed the one mentioned in the documentation , so i run the creatensis perl script but the makensis fail everytime in windows `URL:http://download.osgeo.org/osgeo4w/x86_64/setup.ini [226029/226029] -> "setup.ini" [1]
Command line defined: "INNER=1"
Command line defined: "UNINSTALLERDEST=C:\\OSGeo4W64\\QGIS\\ms-windows"
Command line defined: "INSTALLER_NAME=makeuinst.exe"
Command line defined: "INSTALLER_NAME=QGIS-OSGeo4W-3.15.0-1-Setup-x86_64.exe"
running makensis failed [makensis -DINSTALLER_NAME='QGIS-OSGeo4W-3.15.0-1-Setup-x86_64.exe'  -V0 -DVERSION_NAME='Master' -DVERSION_NUMBER='3.15.0' -DBINARY_REVISION=1 -DVERSION_INT='3150001' -DQGIS_BASE='QGIS 3.15' -DDISPLAYED_NAME="QGIS 3.15.0 'Master'" -DPACKAGE_FOLDER=osgeo4w/unpacked-x86_64 -DLICENSE_FILE='osgeo4w/unpacked-x86_64/apps/qgis/doc/LICENSE' -DARCH='x86_64' QGIS-Installer.nsi] at creatensis.pl line 528.` ( while in my linux VM everything is fine ) so i tried to catch if something went wrong in the perl script 
`$cmd = "makensis -DINSTALLER_NAME='$installerbase.exe' $args";
eval {
    system $cmd;
    1;
} or do {
    my $e = $@;
    print("Something went wrong while executing the cmd : $e\n");
}; 

if ($?)
{
	print ("Something is wrong with nsis exit code : $?\n");
	die "running makensis failed [$cmd]";
} `

so i don't know if it's an issue from my side or the nsis script is not made for windows, thank you for reading :)

**Comment by gioman** [comment] 2020-10-26 17:04
> so i don't know if it's an issue from my side or the nsis script is not made for windows, thank you for reading :) 

@Jabern you should ask in the developers mailing list.

**Comment by Jabern** [comment] 2020-10-27 11:09
> > so i don't know if it's an issue from my side or the nsis script is not made for windows, thank you for reading :)
> 
> @Jabern you should ask in the developers mailing list.

Where ? and thank you for the fast reply :D

**Comment by gioman** [comment] 2020-10-27 11:12
@Jabern https://qgis.org/en/site/getinvolved/mailinglists.html

**Comment by roya0045** [comment] 2020-10-27 21:06
I think this can be closed as its not a bug with qgis but rather about NSIS usability (I gave up trying to use that a long time ago).

**Closed** 2020-12-19 18:18 UTC
Labels: Bug, Feedback
