### ISSUE TITLE
bugs (?) in QTableview

### ISSUE THREAD

**Issue by fedpav** [qgis/QGIS#32132] opened 2019-10-06 10:25 UTC
QGIS 3.6 and 3.8 crash when I execute the code below (in the init function of dialog script).  
The object QTableView in the dialog ui is filled only if currentLayer is "Rete", a vector layer of 7702 features; in this case I see the dialog ui, but when I scroll the list QGIS crashes. If current layer is another one (i.e. "ambiti", a vector layer of 3 features) QGIS crashes while the script is executing. I don't know how to do or if it's a bug of methods called.

        cb = self.mMapLayerComboBox.currentLayer()
        cache = QgsVectorLayerCache(cb, cb.featureCount())
        modello = QgsAttributeTableModel(cache)
        modello.loadLayer()
        self.tableView.setModel(modello)

**Comment by nyalldawson** [comment] 2019-10-06 10:27
It's likely caused by "cache" going out of scope and being deleted early. Try making "cache" and "modello" class members to avoid this.

**Comment by fedpav** [comment] 2019-10-06 10:56
Thanks. Finally it works

**Closed** 2019-10-06 11:14 UTC
Labels: Bug, Feedback
