### ISSUE TITLE
Crash when opening the scale combobox in the status bar

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#52896] opened 2023-04-26 08:07 UTC
### What is the bug or the crash?

```
Python Stack Trace

Windows fatal exception: access violation

 

Current thread 0x00004e54 (most recent call first):

 



Stack Trace


QString::toInt :
QgsScaleComboBox::showPopup :
QComboBox::showPopup :
QComboBox::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
```

### Steps to reproduce the issue

User clicked the combobox. Possibly typed some non-numeric content before (deducing this from the crash report)

### Versions

3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment] 2023-04-26 08:12
@m-kuhn this looks like a duplicate of a number of issues and it should have been fixed already, have you checked master?

**Comment by nicogodet** [comment] 2023-04-26 08:28
Should be fixed by https://github.com/qgis/QGIS/pull/52511

**Closed** 2023-04-26 08:32 UTC
Labels: Bug
