### ISSUE TITLE
[Forms] Layer fields are not available when putting an expression for default values

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#32888] opened 2019-11-15 12:54 UTC
**Describe the bug**

**How to Reproduce**

Any vector Layer
Any field in form
Default value
Use expression
Layer fields are not available

![image](https://user-images.githubusercontent.com/8614223/68944852-33ec0b00-07af-11ea-8d78-2a5ff3f88d4f.png)

When for constraint :

![image](https://user-images.githubusercontent.com/8614223/68944888-4cf4bc00-07af-11ea-90e8-2ed5c8ae7401.png)

**QGIS and OS versions**

Tested on QGIS 3.4.13, 3.10.0 

Win 7-10 x64 

**Additional context**

**Comment by roya0045** [comment] 2019-11-15 15:26
I think this was mostly to prevent people from simply using the field itself. This is probably not a bug but to prevent a bug. Though I agree that this seems like an inconvenience.

**Comment by gioman** [comment] 2019-11-15 15:33
> This is probably not a bug

I also think is by design.

**Comment by nyalldawson** [comment] 2019-11-18 03:43
Duplicate of #30034

**Closed by nyalldawson** 2019-11-18 03:43 UTC
Labels: Bug, Feedback

**Comment by ponceta** [comment] 2019-11-19 09:00
The group is **fields and values.**

Fields are NULL, it is non-sense to add them, I agree.

But for values it would be nice to have the selected attribute relationnal values.
