### ISSUE TITLE
QGIS 3.x.x: freezes and crashes

### ISSUE THREAD

**Issue by Axel57000** [qgis/QGIS#35109] opened 2020-03-16 11:15 UTC
Hello, everybody!

It's been more than 2 weeks now since I've been unable to use QGIS on my computer.
Due to a version change, QGIS is now just crashing on my computer. As soon as I launch it, I can manipulate the software for a few seconds until it crashes, and it's starting to get annoying, especially since I absolutely need this software for my professional projects ...

I've already tried to upgrade to an earlier version (LTR and not LTR), updated my graphic card drivers, performed a disk cleanup and defragmentation and freed up space on my hard drive but nothing helped. I also tried to start QGIS with a blank profile and no extensions, but it doesn't change anything.
When I launch QGIS, I see that the hard disk usage goes to 100%. So I used DISM to repair the system files but nothing changes, QGIS still crashes...

On the internet, several people have already been confronted with my problem, but the problem seems to be solved by a simple reinstallation of a previous version. What I already tried but always the same problem. I rather have the impression that it comes from my hardware but I would like to know if other people have already been or not in my case.

Here's my configuration:
Windows 10 x64
Intel Core i7-4720HQ @2.60GHz
8 gb ram
Nvidia Geforce GTX960M 2gb

Thank you in advance for your answers!

Here is my crash report:

```
Crash ID: ID not generated due to missing information.

Your version of QGIS install might not have debug information included or we couldn't get crash information.


Stack Trace
Stack trace could not be generated.


QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363
```

**Comment by roya0045** [comment] 2020-03-16 11:40
Do you have custom scripts enabled or any other customized code such as custom processing algorythm?

**Comment by Axel57000** [comment] 2020-03-16 11:42
> 
> 
> Do you have custom scripts enabled or any other customized code such as custom processing algorythm?

Thanks for your answer.
No I don't have any of that, I was only using a few plugins, which I disabled, but the crashes still persist.
I also have ArcGIS on my computer and it's working properly, so I can't understand why QGIS doesn't work.

**Comment by roya0045** [comment] 2020-03-16 11:48
Try to reinstall without leftover from previous version, you could also try nightly builds.

**Comment by m-kuhn** [comment] 2020-03-16 12:00
> Due to a version change, QGIS is now just crashing on my computer.

..

> I've already tried to upgrade to an earlier version (LTR and not LTR)

Can you confirm, you have upgraded QGIS (from which version to which version exactly?) and now you downgraded again to the old version which used to work but now the same version crashes?

**Comment by Axel57000** [comment] 2020-03-16 12:04
> 
> 
> > Due to a version change, QGIS is now just crashing on my computer.
> 
> ..
> 
> > I've already tried to upgrade to an earlier version (LTR and not LTR)
> 
> Can you confirm, you have upgraded QGIS (from which version to which version exactly?) and now you downgraded again to the old version which used to work but now the same version crashes?

Initially, I had version 3.8.3 Zanzibar. I later installed version 3.12 and when I saw the crashes I reinstalled version 3.8.3 except that it bugs now too.

**Comment by m-kuhn** [comment] 2020-03-16 12:06
Thanks. Sounds like something on your system has changed meanwhile (hard to say what).

Can you use the osgeo4w installer, install a `-dev` version and a `-pdb` package which is available for the same version? That should give better information on the crash cause.

**Comment by Axel57000** [comment] 2020-03-16 12:22
> 
> 
> Thanks. Sounds like something on your system has changed meanwhile (hard to say what).
> 
> Can you use the osgeo4w installer, install a `-dev` version and a `-pdb` package which is available for the same version? That should give better information on the crash cause.

Thanks for your answer.
How do I do that? I have never used the osgeo installer to install QGIS.

**Comment by m-kuhn** [comment] 2020-03-16 12:26
Just found this howto on google: https://www.giscourse.com/install-qgis-through-osgeo4w/

**Comment by Axel57000** [comment] 2020-03-16 12:33
> 
> 
> Just found this howto on google: https://www.giscourse.com/install-qgis-through-osgeo4w/

Thanks, I will try this and do a feedback after.

**Comment by Axel57000** [comment] 2020-03-16 13:17
I noticed something. QGIS seems to crash when I open a project that I saved with an older version. Could this explain the crashes? Here I have opened a blank project and I don't have any crashes yet.

**Comment by m-kuhn** [comment] 2020-03-16 13:20
Thanks!
Any chance you can attach the project with data here?

**Comment by Axel57000** [comment] 2020-03-16 13:23
No, I'm sorry. I'm making a map as part of an academic publication and it's not finalized. But can projects saved with an old version and opened with another one explain the crash?  I had saved my project under QGIS 3.8 to open it on QGIS 3.12.

**Comment by m-kuhn** [comment] 2020-03-16 13:25
QGIS 3.8 generally open very well with QGIS 3.12
This seems to be a very specific configuration option in your project and possibly in its data. Can you send it to me by mail (matthias (at) opengis.ch)?

**Comment by gioman** [comment] 2020-03-17 14:27
>  I was only using a few plugins, which I disabled

@Axel57000 there are 3rd party plugins that are bad for QGIS even if disabled. The best things to do is to try with a NEW QGIS profile and do not install any 3rd party plugin. I found also that in more complicated cases a complete wipeout of the QGIS folder inside the Windows user profile had helped, and in even more rare cases also a wipeout of anything QGIS/OSGeo related in Windows registry also helped.

**Comment by m-kuhn** [comment] 2020-03-17 14:31
Update:

- I have received a test project and data (thanks @Axel57000)
- I could not reproduce any issue on a local compiled master
- Based on https://github.com/qgis/QGIS/issues/35109#issuecomment-599511244 I have modified the project and removed any paint effects (since they seem to have been causing the crash) and sent the modified project back but have not yet received a reply if the modified project still crashes or not.

**Comment by nyalldawson** [comment] 2020-03-17 16:48
The crash report indicates the crash is due to a qt issue, which was already fixed upstream

**Comment by Axel57000** [comment] 2020-03-17 20:11
> 
> 
> > I was only using a few plugins, which I disabled
> 
> @Axel57000 there are 3rd party plugins that are bad for QGIS even if disabled. The best things to do is to try with a NEW QGIS profile and do not install any 3rd party plugin. I found also that in more complicated cases a complete wipeout of the QGIS folder inside the Windows user profile had helped, and in even more rare cases also a wipeout of anything QGIS/OSGeo related in Windows registry also helped.

I had already tried to reinstall QGIS 3.12. by having emptied all QGIS related folders on my hard drive, but nothing has changed, it still bugs.



> The crash report indicates the crash is due to a qt issue, which was already fixed upstream

What should I do then?

**Comment by gioman** [comment] 2020-03-17 20:14
> > 
> 
> I had already tried to reinstall QGIS 3.12. by having emptied all QGIS related folders on my hard drive, but nothing has changed, it still bugs.

@Axel57000 per https://github.com/qgis/QGIS/issues/35109#issuecomment-600178996 you must wait for new build that will included a patched QT release.

**Comment by gioman** [comment] 2020-03-17 20:15
Closing as upstream issue.

**Comment by m-kuhn** [comment] 2020-03-17 20:15
Quote from private email communication:

> On 3/17/20 5:14 PM, Axel Schwoerer wrote:
> > Hello.
> >
> > It works untin that I activate glow effects...
> >
> > Thanks in advance.
> > Axel 

> 
> Hi.
> 
> Thanks for the feedback. Can you confirm this on the issue itself, it's important for the resolution of the problem!
> 
> There is nothing I can quickly do for that, I am sorry.
> 
> There are three things you can do:
> 
>  - Not use glow effects
> 
>  - Wait for Qt to be upgraded on Windows (not sure how long that takes, to be verified on the issue discussion, there is no ETA yet)
> 
>  - Use a Linux instead of Windows. On Linux there are newer Qt versions. You can use a virtual machine for that.
> 
> Best regards
> 
> Matthias
>

**Closed** 2020-03-17 20:15 UTC
Labels: Bug
