### ISSUE TITLE
Saving CSV edits fails on Windows

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#35144] opened 2020-03-17 17:45 UTC
**Describe the bug**

When you have a CSV layer in the project, the edit mode is possible, so you can modify the values of the objects of the CSV layer, but when you try to save the layer (to save the modification), an error message appears (OGR Error) .

**How to Reproduce**

1) Add a CSV file to the QGIS project (by drag and drop from the Windows Explorer)
2) Edit the layer
3) Modify some values
4) Save the layer
5) The OGR Error appears

**QGIS and OS versions**

Windows 10 - 64 bits

Version de QGIS 3.10.3-A Coruña
Révision du code 0e1f846438
Compilé avec Qt 5.11.2
Utilisant Qt 5.11.2
Compilé avec GDAL/OGR 3.0.4
Utilisé avec GDAL/OGR 3.0.4
Compilé avec GEOS 3.8.0-CAPI-1.13.1
Utilisé avec GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
Version du client PostgreSQL 11.5
Version de SpatiaLite 4.3.0
Version de QWT 6.1.3
Version de QScintilla2 2.10.8
Compilé avec PROJ 6.3.1
Fonctionne avec PROJ Rel. 6.3.1, February 10th, 2020
OS Version  Windows 10 (10.0)
Extensions Python actives cadastre; ClipMultipleLayers;  gban; GeofoncierEditeurRFU;  gml_application_schema_toolbox; loadthemall; localiserparcelle; mmqgis; OSMDownloader; qgis2web; 
QgisLayerBoardPlugin-master; qProf; quick_map_services; refFunctions; SgmCdmTransfo; SgmComparePmAvvApv; SgmDxfImportPro; SgmExpressFunctions; SgmLinesToPoints; SgmVertex2NodeByAtt; StreetView; db_manager; MetaSearch; processing

**Additional context**
Using a python program (little extension), it's totally possible to modify a CSV layer.

**Comment by gioman** [comment] 2020-03-17 18:23
Confirmed on Windows.
Works on 3.12 on Linux with old dependencies (GDAL 2.4).

**Comment by jgrocha** [comment] 2020-03-17 22:03
@sigmoe Which error message? Just "OGR Error"?

Works on 3.13.0-Master, with GDAL 3.1.0dev (on Linux)

**Comment by sigmoe** [comment] 2020-03-18 07:44
@jgrocha The Error message: 
CRITICAL    Couche t_baie : Erreur OGR lors la synchronisation vers le disque : Cannot rename files

**Comment by gioman** [comment] 2020-03-18 13:07
@sigmoe did it worked ok on 3.4?

**Comment by sigmoe** [comment] 2020-03-18 15:05
@gioman same problem with QGIS 3.4

**Comment by gioman** [comment] 2020-03-18 19:37
As also on 2.18 so it seems this is long standing issue.

**Comment by roya0045** [comment] 2020-03-19 23:19
see #28703

**Comment by gioman** [comment] 2020-03-20 17:10
> see #28703

this ticket is not completely accurate. You can edit CSVs on Linux (I can't test macOS now), but not on Windows. So the functionality is there.

**Comment by stev-0** [comment] 2020-03-26 12:02
This is a duplicate of #25421 - can we close that older one?

**Comment by samillar94** [comment] 2020-11-02 16:12
This issue is still here on QGIS 3.16.0. Why is it not a higher priority? To quote Gio from the old forum, "To add insult to injury if the table covers the message bar the user don't see the error and when toggling editing the unsaved values are sticking in the table giving the sensation that edits went well".

**Comment by bjornharrtell** [comment] 2020-11-10 20:26
As far as I've been able to verify fix done in https://github.com/qgis/QGIS/pull/39919 is effective.

**Comment by gioman** [comment] 2020-11-11 10:56
> As far as I've been able to verify fix done in #39919 is effective.

@bjornharrtell so I guess we can close this?

**Comment by samillar94** [comment] 2020-11-11 11:02
Thanks all for your hard work, much appreciated

**Comment by bjornharrtell** [comment] 2020-11-11 13:32
@gioman as far as I'm concerned yes, but as disclaimer I will say that I have not been able to reproduce this issue even before the fix.

**Comment by roya0045** [comment] 2020-11-11 13:39
Just let someone test the MXE to see if it truly solves the issue in this case.

**Comment by stev-0** [comment] 2020-11-11 14:02
I did experience the problem and it seems to be fixed by this issue. However this is only when loading via drag and drop.

When using the Delimited Text widget, I no longer seem to be able to load CSVs at all. Not sure if this is related to this or something else. Can anyone else confirm?

Message is `Layer is not valid : The layer file:///C:/Users/Stephen.Knox/Documents/test.csv?type=csv&maxFields=10000&detectTypes=yes&xyDms=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason: `

**Comment by stev-0** [comment] 2020-11-11 14:10
Actually, it isn't present in 3.16, so it could be this that the PR to fix this issue has introduced the problem as the PR I linked above is pre-3.16

**Comment by gioman** [comment] 2020-11-11 14:12
> When using the Delimited Text widget, I no longer seem to be able to load CSVs at all. Not sure if this is related to this or something else. Can anyone else confirm?
> 
> Message is `Layer is not valid : The layer file:///C:/Users/Stephen.Knox/Documents/test.csv?type=csv&maxFields=10000&detectTypes=yes&xyDms=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason:`

@stev-0 qgis version? sample data?

**Comment by bjornharrtell** [comment] 2020-11-11 14:18
@stev-0 I also noticed the problem you describe on *some* CSV content however AFAIK completely unrelated to *this* issue.

**Comment by stev-0** [comment] 2020-11-11 14:21
@gioman I am using the master (fe05aad7e1) osgeo4w build which has the bugfix for this issue in.

To be more precise, with the attached file, it loads fine in both master and 3.16

However, when loading via Add Layer -> Delimited Text, with the defaults it loads correctly in 3.16 but not in master 
[test.txt](https://github.com/qgis/QGIS/files/5524518/test.txt)

@bjornharrtell - guess I should open another ticket.

**Comment by bjornharrtell** [comment] 2020-11-11 16:12
@stev-0 please do, and please be more careful when wording the description - I can't make sense where it works and fails for you with what you write above ("loads correctly in 3.16 but not in master" vs "loads fine in both master and 3.16").

**Comment by stev-0** [comment] 2020-11-11 16:54
> @stev-0 please do, and please be more careful when wording the description - I can't make sense where it works and fails for you with what you write above ("loads correctly in 3.16 but not in master" vs "loads fine in both master and 3.16").

whoops - yes added that in to the reply

**Comment by gioman** [comment] 2020-11-11 17:24
> However, when loading via Add Layer -> Delimited Text, with the defaults it loads correctly in 3.16 but not in master

@stev-0 confirmed, please file a new ticket.

**Comment by gioman** [comment] 2020-11-11 17:39
> Just let someone test the MXE to see if it truly solves the issue in this case.

@roya0045 I tested https://github.com/qgis/QGIS/suites/1486274517/artifacts/25792318 and works ok while on master/ccdff23dbe is not, but the latter probably does not have the fix. Closing?

**Comment by gioman** [comment] 2020-11-11 17:41
> @stev-0 confirmed, please file a new ticket.

@stev-0 I did it https://github.com/qgis/QGIS/issues/39968

**Comment by roya0045** [comment] 2020-11-11 19:13
@gioman Since the commits reference this issue it should close when merged.

**Comment by stev-0** [comment] 2020-11-12 14:13
@roya0045 it should have closed but hasn't so I think someone needs to close it manually. It's fixed from my point of view.

**Closed** 2020-11-12 14:14 UTC
Labels: Bug, Windows

**Comment by roya0045** [comment] 2020-11-12 14:42
@stev-0 you're right, when I gave a quick look I saw that the backport was not merged and though it was still pending...

**Comment by djagar** [comment] 2022-03-11 18:44
The error is still present in the actual LTR version 3.22, exactly as described in the first post:
QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e9
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
Active Python plugins
nominatim | 1.4.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99
