### ISSUE TITLE
UI: message log incorrectly scrolled past messages

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#31837] opened 2019-09-17 10:28 UTC
In #31799 I have not noticed the log messages, because the view is scrolled to show only the last one, and empty space below it suggests there is nothing above. Last line should be coinciding the lowest boundary instead.

current:
![image](https://user-images.githubusercontent.com/810638/65034072-fb66b700-d94e-11e9-9cb0-e3d55148bd0a.png)

expected:
![image](https://user-images.githubusercontent.com/810638/65034118-0de0f080-d94f-11e9-9cc0-e40c943d62a1.png)

```
QGIS version
3.8.2-Zanzibar
QGIS code revision
4470baa1a3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
10.8
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)
```

**Comment by alexbruy** [comment] 2020-04-21 11:44
Seems fixed in master.

**Comment by nyalldawson** [comment] 2020-05-26 00:49
I can't reproduce either

**Closed by nyalldawson** 2020-05-26 00:49 UTC
Labels: Bug, Feedback
