### ISSUE TITLE
QGIS finds topology errors, official checker doesn't

### ISSUE THREAD

**Issue by decheu** [qgis/QGIS#47911] opened 2022-03-22 14:18 UTC
### What is the bug or the crash?

Vector > Topology Checker and Vector > Geometry Tools > Check Validity... give out 4 errors when checking the communities of the canton of Zurich (ZH) for the rule 'must not have invalid geometries' (in Topology Checker). Tested directly on the WFS. According to the data owner (canton of Zurich) their own check service (MOCheckZH) doesn't show any errors.
As a result, I couldn't use the Split Features tool of the Advanced Digitizing Toolbar.
Workaround: Processing Toolbox: Fix geometries

Data Source: pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:2056' typename='ms:gemeinden_f' url='http://maps.zh.ch/wfs/AVZHWFS' version='auto'

Question: **Are** the QGIS checkers (**Topology Checker & Check Validity...**) or the data, meaning also MOCheckZH, **erronous?**

### Steps to reproduce the issue

1. Load the wfs (see Data Source above) as a layer
2. Click on Vector > Topology Checker
3. Click the configure button and add the following rule:
![image](https://user-images.githubusercontent.com/97091934/159499937-1fdd20c3-ac87-4875-a6f9-234d776588c0.png)
4. Click the Verify All button. I get the following output:
![image](https://user-images.githubusercontent.com/97091934/159500622-dc031979-a00e-4664-94cb-892a77332ca1.png)

For Check Validity...
2. Click on Vector > Geometry Tools > Check Validity...
3. Choosing the added 'Gemeinden' layer and using the standard settings without generating any new layers
![image](https://user-images.githubusercontent.com/97091934/159501741-1dcaa801-8e5f-49bd-a29c-2ba068bef490.png)
4. After clicking the run button, I get the following output:
```
QGIS version: 3.22.4-Białowieża
QGIS code revision: ce8e65e9
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-03-22T15:14:17
Algorithm 'Check validity' starting…
Input parameters:
{ 'ERROR_OUTPUT' : 'TEMPORARY_OUTPUT', 'IGNORE_RING_SELF_INTERSECTION' : False, 'INPUT_LAYER' : "WFS:// pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:2056' typename='ms:gemeinden_f' url='http://maps.zh.ch/wfs/AVZHWFS' version='auto'", 'INVALID_OUTPUT' : 'TEMPORARY_OUTPUT', 'METHOD' : 2, 'VALID_OUTPUT' : 'TEMPORARY_OUTPUT' }

Execution completed in 0.25 seconds
Results:
{'ERROR_COUNT': 4,
'ERROR_OUTPUT': 'Error_output_1ccdfcb7_1a5c_4738_bfcb_2f3dbb9e11b0',
'INVALID_COUNT': 4,
'INVALID_OUTPUT': 'Invalid_output_45233895_8c30_4a7d_9e56_bb3102eaa86c',
'VALID_COUNT': 161,
'VALID_OUTPUT': 'Valid_output_14bcdddc_39b1_49dc_853d_dbba03fc781f'}

Loading resulting layers
Algorithm 'Check validity' finished
```

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
clipper
1.2
DigitizingTools
1.5.1
interlis
0.14.8
qconsolidate3
0.2.0
QgisModelBaker
v7.0.3
rivergis
3.0
SwapVectorDirection
0.9
swiss_locator
1.4.8
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lbartoletti** [comment] 2022-05-18 08:47
Yes, it's a duplicate of #17923

**Closed by lbartoletti** 2022-05-18 08:47 UTC
Labels: Bug, Vectors, Topology checker, Geometry checker
