### ISSUE TITLE
Drawing circle yields a diamond when digitizing small feature in a project with a geographic CRS

### ISSUE THREAD

**Issue by Llaves** [qgis/QGIS#38212] opened 2020-08-09 16:50 UTC
When drawing very small circle features (~0.1M diameter) qgis creates a diamond, not a circle. Above some critical cutoff, around .25M, the shape becomes a circle. 

To reproduce:
Open a new map. Set CRS to EPSG:4326 if that's not your default. (Problem persists for EPSG:26713 - UTM13, NAD23)
Layer->Create New. I used shapefile but geopackage seems to display the same issue.
Set map scale to 1:10
Select new layer
Toggle editing on
Edit->Add Circle->Add circle by Center and another point
Now draw a very small circle - around .1M

![diamonds](https://user-images.githubusercontent.com/6778818/89737399-e5ae2480-da2d-11ea-8f4a-d4f3e4d7b099.png)

Feature rubber bands as a circle, but when you right-click the second point, it changes to a diamond.
Shape remains diamond if you remove the layer and add it back to the map. (I suppose it would be more surprising if they showed up as circles again.) 

Problem seems to occur _only_ if newly created layer is in 4326. Does not occur if the created layer is in 26713

**Comment by gioman** [comment] 2020-08-10 14:52
@Llaves it may be a bug, but also it may be just an effect when you are digitizing in a project that has a CRS in degrees (what you describe does not happen if your project has a projected CRS).

**Comment by Llaves** [comment] 2020-08-10 15:17
@gioman  Just to be precise, the issue is not that the _project_ has a CRS in degrees vs projected, it's that the new layer has a CRS in degrees vs. projected. The fact that is appears as a circle above about .25M suggests it's not an inherent property of non-projected CRS. The shift from diamond to circle without appearing as an octogon at intermediate sizes suggests it's not an artifact of some minimum edge length in the circle approximation.

**Comment by gioman** [comment] 2020-08-10 15:19
> d, it's that the new layer has a CRS in degrees vs. projected

@Llaves that is not my observation: i get the same problem even on a layer with a projected CRS in a project with a geographic CRS.

**Comment by Llaves** [comment] 2020-08-10 15:43
@gioman - this may be more dependent on the CRS than simple tests reveal. 

In my tests in Qgis  3.10.5 on Windows:
Project CRS 4326, layer CRS 26713 - Small circles appear as circles
Project CRS 26713, layer CRS 4326 - Small circles appear as diamonds
Project CRS 26173, layer CRS 26713 - small circles appear as circles

I get strange behavior with project = 4326, layer = 26713. The rubberband action is a circle. Right click and it converts to a diamond. Then click OK on attributes and it's a circle again.

**Comment by lbartoletti** [comment] 2020-09-23 04:45
It's a duplicate of #25167

**Closed** 2020-09-23 09:50 UTC
Labels: Bug, Digitizing
