### ISSUE TITLE
Attribute Table - Move Selection Top does not work each time

### ISSUE THREAD

**Issue by EmreHepgunes** [qgis/QGIS#31658] opened 2019-09-10 07:48 UTC
Attribute Table - Move Selection Top does not work each time when pressed the button. Sometimes it works and sometimes it is not. It was working properly in version 2 but in version 3 still the same problem occurs in every new update i have tried.

**Comment by Gustry** [comment] 2019-09-10 09:16
Duplicate of https://github.com/qgis/QGIS/issues/28914 ?

**Comment by alexbruy** [comment] 2020-04-19 13:46
Should be fixed in master. Please reopen if necessary.

**Closed by alexbruy** 2020-04-19 13:46 UTC
Labels: Bug, Feedback
