### ISSUE TITLE
Error in Customizing Projection

### ISSUE THREAD

**Issue by aflaurio** [qgis/QGIS#33309] opened 2019-12-10 01:08 UTC
In QGIS A Coruña 3.10, customizing projection does not accept the parameters +towgs84.
It will delete that portion. The result of the test portion is either "inf" or "error"
This QGIS function works from the old version up to 3.4
Please see attached file
<img width="642" alt="cust_proj" src="https://user-images.githubusercontent.com/7996232/70486322-5a8e2f00-1b2c-11ea-98c0-daf60aa4fe81.png">
<img width="642" alt="cust_proj2" src="https://user-images.githubusercontent.com/7996232/70486405-a7720580-1b2c-11ea-835f-09b64c8d33d2.png">

**Comment by gioman** [comment] 2019-12-10 10:10
I believe is a duplicate of several other reports made lately, @aflaurio do you mind checking?

**Comment by aflaurio** [comment] 2019-12-10 10:24
Thank you. I will check for same issue in 3.10.

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 10, 2019 at 6:10 PM, Giovanni Manghi<notifications@github.com> wrote:   
I believe is a duplicate of several other reports made lately, @aflaurio do you mind checking?

**Closed** 2020-06-12 16:37 UTC
Labels: Bug, Feedback
