### ISSUE TITLE
Shortcut "Save as..." is double assigned

### ISSUE THREAD

**Issue by JHM-BGR** [qgis/QGIS#55328] opened 2023-11-20 08:28 UTC
### What is the bug or the crash?

The shortcut for "Save as..." in the "Project" menu and the one in the "Layer" menu are linked to each other. If a shortcut is defined for "Save as..." from the "Layer" menu, this is assigned to both "Save as..." shortcuts after a restart of QGIS and will no longer work.

![grafik](https://github.com/qgis/QGIS/assets/151500437/86bc62b6-0fbd-423b-8a6b-638a357d1eb1)

If you then set the "Save as..." shortcut from the "Project" menu to empty, the shortcut works as wanted. However, if you restart QGIS, there is no shortcut for the "Save as..." from the "Layer" menu again.

### Steps to reproduce the issue

1. open Settings -> Keyboard Shortcuts...
2. set a filter "save" to become an overview
3. set a shortcut for "Save as..." (the one without an icon)
4. restart QGIS
5. open the Keyboard Shortcuts again and set the filter
6. now the shortcut is assigned to both "Save as..."

### Versions

As I remember all versions since 3.2 up to the version I'm currently using

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.28.11-Firenze | QGIS-Codeversion | b02458a196
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.7.2
PROJ-Version | 9.3.0
EPSG-Registraturdatenbankversion | v10.094 (2023-08-08)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
coordinate_capture | 0.2
latlontools | 3.6.16
OSMDownloader | 1.0.3
qgis2web | 3.16.0
Style-Loader_41 | 0.1
StyleLoadSave | 1.0
VectorBender | 0.2.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
CustomToolBar | 1.1

</body></html>QGIS-Version
3.28.11-Firenze
QGIS-Codeversion
[b02458a196](https://github.com/qgis/QGIS/commit/b02458a196)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.7.2
PROJ-Version
9.3.0
EPSG-Registraturdatenbankversion
v10.094 (2023-08-08)
GEOS-Version
3.12.0-CAPI-1.18.0
SQLite-Version
3.41.1
PDAL-Version
2.5.5
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
coordinate_capture
0.2
latlontools
3.6.16
OSMDownloader
1.0.3
qgis2web
3.16.0
Style-Loader_41
0.1
StyleLoadSave
1.0
VectorBender
0.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
CustomToolBar
1.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by YoannQDQ** [comment] 2023-11-21 10:29
Duplicate of #39903, fixed in 3.32

**Closed** 2023-11-21 10:29 UTC
Labels: Bug
