### ISSUE TITLE
[Postgis] Feature Attributes editor corrupts data in table with multiple columns of geometry type.

### ISSUE THREAD

**Issue by MorriganR** [qgis/QGIS#49380] opened 2022-07-16 17:45 UTC
### What is the bug or the crash?

Feature Attributes editor corrupts data in PostgreSQL table with multiple columns of geometry type.

### Steps to reproduce the issue

Create a postgresql table with multiple columns of geometry type.
```
DROP TABLE IF EXISTS public.test_geom;
CREATE TABLE IF NOT EXISTS public.test_geom (
  pk integer NOT NULL,
  test_int integer DEFAULT 0,
  geom geometry(Point,4326),
  geom_srid geometry(Point,4326),
  geom_no_srid geometry(Point),
  CONSTRAINT test_geom_pkey PRIMARY KEY (pk)
) TABLESPACE pg_default;
```

Add test data & check the result
```
DELETE FROM public.test_geom;
INSERT INTO public.test_geom (pk, test_int, geom, geom_srid, geom_no_srid)
  VALUES (1, 0, ST_GeomFromEWKT('SRID=4326;POINT(1 1)'), ST_GeomFromEWKT('SRID=4326;POINT(1 1)'), ST_GeomFromEWKT('POINT(1 1)'));

SELECT pk, test_int, st_asewkt(geom) as geom, st_asewkt(geom_srid) as geom_srid, st_asewkt(geom_no_srid) as geom_no_srid FROM public.test_geom;

 pk | test_int |         geom         |      geom_srid       | geom_no_srid
----+----------+----------------------+----------------------+--------------
  1 |        0 | SRID=4326;POINT(1 1) | SRID=4326;POINT(1 1) | POINT(1 1)
(1 row)
```

Open table `public.test_geom` in QGIS.
Start edit layer & open "Feature Attributes"
![0007](https://user-images.githubusercontent.com/31573086/179365884-69057fc6-3f9d-4c89-8404-03383ebd3a25.PNG)

Change `test_int` from 0 to 42 & save data to DB.
![0008](https://user-images.githubusercontent.com/31573086/179365928-d466dc3a-3267-4691-bb3b-c3a4d2d1c068.PNG)

Check the result in PostgreSQL DB & QGIS
```
SELECT pk, test_int, st_asewkt(geom) as geom, st_asewkt(geom_srid) as geom_srid, st_asewkt(geom_no_srid) as geom_no_srid FROM public.test_geom;
 pk | test_int |         geom         | geom_srid | geom_no_srid
----+----------+----------------------+-----------+--------------
  1 |       42 | SRID=4326;POINT(1 1) |           |
(1 row)
```
![0009](https://user-images.githubusercontent.com/31573086/179366011-ddf0b45e-90be-4e71-b32c-5cc74e3b16cd.PNG)

### Versions

```
QGIS version
3.27.0-Master
QGIS code branch
master
Qt version
5.15.4
Python version
3.10.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.36.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.0
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
```

PostgreSQL:
```
select version();
PostgreSQL 10.21 (Ubuntu 10.21-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

select PostGIS_Full_Version();
 POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.6.2-CAPI-1.10.2 4d2925d6" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by MorriganR** [comment] 2022-08-08 07:30
It is very likely that these are the consequences of this PR #45127
Unfortunately, I don't have the resources to test this hypothesis right now, @m-kuhn, what do you think?

**Comment by strk** [comment] 2022-10-17 22:13
I can confirm the issue with current master branch ( 645bc943197493feb40cb80cf3836e7d8bf28fe6 )
I guess editing of geometry-typed geometries should be completely disabled ?

**Comment by strk** [comment] 2022-10-17 22:48
I just tried with QGIS-3.22 and there you can edit attributes of type Geometry just fine (although they are edited in WKT format so every edit is subject to change the coordinates due to rounding). So this is a regression from 3.22.

**Comment by strk** [comment] 2022-10-18 08:21
The code responsible for creating the display string is in QgsField::displayString in src/core/qgsfield.cpp

One thing I notice is that the WKT of the geometry is truncated if it is bigger than 1050 characters. This means editing a table with big geometries as attributes is likely to corrupt the tables anyway, unless the "display string" is different from what is actually used in the UPDATE statement later. @m-kuhn ?

**Comment by strk** [comment] 2022-10-18 08:52
This may also be related:
>   src/gui/qgsfieldvalidator.cpp:164 : (validate) [0ms] unsupported type 1024 for validation

**Comment by strk** [comment] 2022-10-18 10:24
More detail: type 1024 is a `qrange`, so I'm not sure the warning is related

**Comment by MorriganR** [comment] 2022-10-18 10:46
> I can confirm the issue with current master branch ( [645bc94](https://github.com/qgis/QGIS/commit/645bc943197493feb40cb80cf3836e7d8bf28fe6) ) I guess editing of geometry-typed geometries should be completely disabled ?

Yes, in my opinion, at the initial stage it is worth blocking the possibility of editing the columns of secondary geometries in the Attribute Editor. This will protect user data from corruption if a 3.22 or older project is opened in the latest version of QGIS.

Of course, this can be done by the user himself by marking the columns with secondary geometries "read-only" if he guesses that otherwise some data will be lost.

**Comment by strk** [comment] 2022-10-18 12:49
The warning was actually related, as in my test the "geom2" field is seen by postgresql provider as being of type "qrange" instead of "geometry". Not being able to edit those fields would still be a regression though

**Comment by strk** [comment] 2022-10-18 12:50
Note: "qrange" comes out of `QMetaType::typeName( fld.type() )` which is not necessarely the way to do things

**Comment by strk** [comment] 2022-10-18 12:54
Sorry, `fld.typeName()` is the right way to print that type, and it is "geometry" so I'm on the right track now

**Comment by strk** [comment] 2022-10-18 12:57
Ok here's what happens, in `QgsPostgresProvider::changeAttributeValues`  (`src/providers/postgres/qgspostgresprovider.cpp`)

```
          QString defVal = defaultValueClause( siter.key() );
          if ( qgsVariantEqual( *siter, defVal ) )
```

The qgsVariantEqual function returns true for the default value and the actual value, which I've yet to further debug

**Comment by strk** [comment] 2022-10-18 14:49
another possibly interesting debug line spotted:
```
src/gui/qgsattributeform.cpp:443 : (saveEdits) [6771ms] Updating field 2
src/gui/qgsattributeform.cpp:444 : (saveEdits) [0ms] dst:'' (type:qrange, isNull:1, isValid:1)
src/gui/qgsattributeform.cpp:446 : (saveEdits) [0ms] src:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
```

Again `qrange` is seen (maybe by mistake)

**Comment by strk** [comment] 2022-10-18 15:02
Added more debugging lines and saw type of the secondary geometry field change from QgsReferencedGeometry to qrange:

```
src/gui/qgsattributeform.cpp:354 : (saveEdits) [11611ms] XXX0 dst:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:354 : (saveEdits) [0ms] XXX0 dst:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:354 : (saveEdits) [0ms] XXX0 dst:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:404 : (saveEdits) [0ms] XXX1 dst:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:406 : (saveEdits) [0ms] XXX1 src:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:404 : (saveEdits) [0ms] XXX1 dst:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:406 : (saveEdits) [0ms] XXX1 src:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:404 : (saveEdits) [0ms] XXX1 dst:'' (type:qrange, isNull:1, isValid:1)
src/gui/qgsattributeform.cpp:406 : (saveEdits) [0ms] XXX1 src:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
```

**Comment by strk** [comment] 2022-10-18 15:46
I'm guessing a QgsRangeWidgetWrapper is being used for QgsReferencedGeometry attribute, for some reason.
Ref: https://api.qgis.org/api/classQgsEditorWidgetWrapper.html

**Comment by strk** [comment] 2022-10-18 15:55
Things feel mixed here:
```
src/gui/qgsattributeform.cpp:354 : (saveEdits) [4575ms] XXX0 dst:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:354 : (saveEdits) [0ms] XXX0 dst:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:354 : (saveEdits) [0ms] XXX0 dst:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:356 : (saveEdits) [0ms] XXX0 src:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:366 : (saveEdits) [0ms] XXX editor widget for field 0 wrapper is 21QgsRangeWidgetWrapper
src/gui/qgsattributeform.cpp:366 : (saveEdits) [0ms] XXX editor widget for field 1 wrapper is 18QgsTextEditWrapper
src/gui/qgsattributeform.cpp:366 : (saveEdits) [0ms] XXX editor widget for field 2 wrapper is 18QgsTextEditWrapper
src/gui/qgsattributeform.cpp:414 : (saveEdits) [0ms] XXX1 dst:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:416 : (saveEdits) [0ms] XXX1 src:'1' (type:qlonglong, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:414 : (saveEdits) [0ms] XXX1 dst:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:416 : (saveEdits) [0ms] XXX1 src:'5' (type:int, isNull:0, isValid:1)
src/gui/qgsattributeform.cpp:414 : (saveEdits) [0ms] XXX1 dst:'' (type:qrange, isNull:1, isValid:1)
src/gui/qgsattributeform.cpp:416 : (saveEdits) [0ms] XXX1 src:'' (type:QgsReferencedGeometry, isNull:0, isValid:1)
```

Should the range widget be for the primary key instead of for the other fields ??

**Comment by strk** [comment] 2022-10-18 16:15
Interesting debugging shows that a QgsTextEditWrapper can return value() of different types, and for the QgsReferencedGeometry ends up returning a qrange:
```
src/gui/qgsattributeform.cpp:366 : (saveEdits) [0ms] XXX editor widget for field 1 wrapper is 18QgsTextEditWrapper
src/gui/qgsattributeform.cpp:399 : (saveEdits) [0ms] XXX editor widget for field 1 returned 1 values
src/gui/qgsattributeform.cpp:407 : (saveEdits) [0ms] XXX editor widget for field 1 returned value 0 is 5 of type int (to replace 5 of type int)
src/gui/qgsattributeform.cpp:366 : (saveEdits) [0ms] XXX editor widget for field 2 wrapper is 18QgsTextEditWrapper
src/gui/qgsattributeform.cpp:399 : (saveEdits) [0ms] XXX editor widget for field 2 returned 1 values
src/gui/qgsattributeform.cpp:407 : (saveEdits) [0ms] XXX editor widget for field 2 returned value 0 is  of type qrange (to replace  of type QgsReferencedGeometry)
```

**Comment by strk** [comment] 2022-10-18 16:36
the problem may be in `QgsField::convertCompatible` which fail for our `geometry` typed value. The documentation for that method is not very clear, it says "convert to a compatible format", but what does that mean ? Compatible with what ?

**Comment by strk** [comment] 2022-10-18 16:37
convertCompatible failed with message: Could not convert value "Point (10 1) [EPSG:4326 - WGS 84]" to target type

**Comment by strk** [comment] 2022-10-18 18:24
@MorriganR a temptative fix is in https://github.com/qgis/QGIS/pull/50592 -- do you want to give it a try ?

**Comment by MorriganR** [comment] 2022-10-18 19:40
Yes! this is the exact place and code, cool

![0010](https://user-images.githubusercontent.com/31573086/196527548-112e8bbb-f1ce-40f1-b1b3-6541ff36e5a9.PNG)

**Comment by strk** [comment] 2022-10-18 20:49
There seem to be additional bug with some code which is triggered by any keystroke inside the text edit widget

**Comment by strk** [comment] 2022-10-18 20:58
Got it: the additional problem is that you cannot edit the field "incrementally" because as soon as you have an invalid geometry representation the whole field turns into a NULL (and this is always the case when the ellipsis is used)

**Comment by strk** [comment] 2022-10-19 09:30
@MorriganR can you try now ? You won't be able to edit geometries with no SRID unless you specify a CRS yourself in the text field

**Comment by strk** [comment] 2023-02-07 15:21
I confirm this bug is still present as of current master branch, aka 00da22feca83470670576074f596c28f112d9855 (Before-merge-new_vector_api-63452-g00da22feca8)

**Comment by strk** [comment] 2023-02-15 17:32
Bug is still present as of commit 955c9017bb0d830011460d4a78c64245c1b67fe1

**Comment by strk** [comment] 2023-02-23 16:14
@nyalldawson I've tried with current master branch and I confirm the data corruption is fixed.

BUT, when editing geometries, only the Geometry part is really saved back, while the CRS is only shown in the Attribute form but not saved back to the database. It might still be seen as a "data corruption" as we see a CRS but then it's lost ? Or should we file a separate ticket ?

**Comment by strk** [comment] 2023-02-23 16:19
See how QGIS shows wrong information to user in this screenshot.

![geometry_widget_not_saving_crs](https://user-images.githubusercontent.com/289678/220966558-1bde47e5-2b4e-4e56-9b9b-44722b33f875.png)

**Comment by strk** [comment] 2023-05-29 15:49
After trying the procedure in the original submission once again with QGIS 3.31.0-Master as of 5d6c016eb07 and not seeing a problem I'm closing this as completed.

@MorriganR feel free to file a new ticket shall anything else come out, thanks!

**Closed by strk** 2023-05-29 15:49 UTC
Labels: Regression, Bug, Crash/Data Corruption, PostGIS data provider
