### ISSUE TITLE
Can't modify KML entities

### ISSUE THREAD

**Issue by Ashzero0** [qgis/QGIS#59008] opened 2024-10-08 14:02 UTC
### What is the bug or the crash?

Edition mode does not work for kml files.
If you want to edit entities in the attribute table, you can't. You can't select the cell, even if you're in edit mode. 
If the format is shp or geojson it works. 

### Steps to reproduce the issue

1. Import a kml files and go to attribute table
2. Select editing mode
3. Try to edit an entity 
4. You can't select the cell

### Versions

QGIS Version : 3.38.3 Grenoble 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Ipickedausername** [comment] 2024-10-10 04:45
Hi, 

I'm not sure QGIS can edit .kml files. 
As you said it works with shp files. So the best way to avoid this issue is to export it as .shp ; do the modifications and export it back as Keyhole Markup Language (KML).

**Comment by rouault** [comment] 2024-10-10 22:01
duplicate of https://github.com/qgis/QGIS/issues/58780. Will be solved by a QGIS build running against future GDAL 3.10

**Closed by rouault** 2024-10-10 22:01 UTC
Labels: Bug
