### ISSUE TITLE
attribute table row sorting doesn't work

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#57338] opened 2024-05-03 18:23 UTC
### What is the bug or the crash?

The sorting of the rows of the attribute table does not work if we use a geometric function as an expression (for example like $area)

### Steps to reproduce the issue

1. I load the Reg01012024_g_WGS84 layer in QGIS;
2. I open the attributes table;
3. I position the mouse on the COD_REG attribute header;
4. right-click and select 'sort';
5. in the window that opens, I activate it and type $area;
6. I click OK
7. nothing happens (even if you activate ascending sort in the window)

https://github.com/qgis/QGIS/assets/7631137/0f33bf65-427a-49f7-9483-96e98fbe435e

## OSGeo4W QGIS 3.34.6-Prizren

Versione di QGIS 3.34.6-Prizren
Revisione codice QGIS
623828f5
Versione Qt 5.15.13
Versione Python 3.12.3
Versione GDAL/OGR 3.8.5
Versione PROJ 9.4.0
Versione database del Registro EPSG v11.004 (2024-02-24)
Versione GEOS 3.12.1-CAPI-1.18.1
Versione SQLite 3.45.1
Versione PDAL 2.6.3
Versione client PostgreSQL 16.2
Versione SpatiaLite 5.1.0
Versione QWT 6.2.0
Versione QScintilla2 2.14.1
Versione SO Windows 11 Version 2009

Plugins Python attivi
DataPlotly 4.1.0
eurostat_downloader 0.2.1
felt 2.0.1
kmltools 3.1.33
mapswipetool_plugin 1.2
nominatim_locator_filter 0.3.2
quick_map_services 0.19.34
valuetool 3.0.19
db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.6
processing 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

data for testing:

[Reg01012023_g.zip](https://github.com/qgis/QGIS/files/15203663/Reg01012023_g.zip)

**Comment by agiudiceandrea** [comment] 2024-05-03 22:02
I can confirm that the issue occurs on Windows using QGIS 3.34.6 and QGIS 3.36.2 and also using previous versions like QGIS 3.28 or QGIS 3.22.
The issue doesn't occur using a memory layer.

**Comment by ludovico85** [comment] 2024-05-04 14:27
Same for me. Tested on Windows 11 and QGIS 3.34.6. I would like to add that if sorting the rows occurs on a table just opened using the $area function, nothing happens. However, if you try to sort the table after having sorted it using a field, the $area function works.

https://github.com/qgis/QGIS/assets/24815399/74e7cad7-06d6-4cd7-b345-a334b1824c75

**Comment by elpaso** [comment] 2024-05-23 10:43
I cannot reproduce on Linux master.

**Comment by pigreco** [comment] 2024-05-28 13:13
> I cannot reproduce on Linux master.

Can I be helpful in some way?

**Comment by elpaso** [comment] 2024-05-28 13:19
> > I cannot reproduce on Linux master.
> 
> Can I be helpful in some way?

If you can test on Linux it would be useful to determine if this is an issue that only affects the windows operating system.

I watched your video and tried to reproduce the issue on Linux/master and I failed.

**Comment by pigreco** [comment] 2024-05-28 16:39
@elpaso 
> If you can test on Linux it would be useful to determine if this is an issue that only affects the windows operating system.

I don't have a Linux machine to test on, I asked a friend, he doesn't order well either.
If you watch the video, you first find Piemonte and then Valle d'Aosta and then Lombardia.

https://github.com/qgis/QGIS/assets/7631137/f37d130e-7d90-47ce-9fb7-791f3ba57982

**Comment by elpaso** [comment] 2024-05-29 09:29
I tested with 3.36 and I noticed that there is something wierd in the area calculation:

```python
Out[5]: [5, 19, 'Sicilia', 1337059.54488, 25823747101.9, -25710002545.38736]

In [6]: sicilia = layer.getFeature(18)

In [7]: sicilia.geometry()
Out[7]: <QgsGeometry: MultiPolygon (((800959.90629999991506338 3939248.08000000007450581, 800968.66559999994933605 3939326.28639999963343143, 800975.60219999961555004 3939364.54490000009536743, 800994.41519999969750643 3939446.37199999950826168, 801017.31570000015199184 3939477.58720000088214874, 801152.76109999977052212 3939405.41809999942779541, 801207.20260000042617321 3939350.85979999974370003, 801210.41380000021308661 3939327.00290000066161156, 801179.2556999996304512 3939283.25799999944865704, 801115.25189999956637621 3939202.93410000018775463, 801097.79920000024139881 3939185.08190000057220459, 801068.88370000012218952 3939170.28949999995529652, 801039.29030000045895576 3939170.73790000006556511, 801006.49189999978989363 3939186.77769999951124191, 800976.51150000002235174 3939210.00589999929070473, 800959.90629999991506338 3939248.08000000007450581),(767921.07919999957084656 4079202.97499999962747097, 767914.47429999988526106 4079184.52449999935925007, 767908.36330000031739473 4079178.128799999132752...>

In [8]: sicilia.geometry().area()
Out[8]: -25823646416.06542
```

So, the sorting is actually working as expected, it is the area calculation which is wrong.

```python
In [11]: for f in layer.getFeatures():
    ...:     print(f.id(), f['DEN_REG'], '\t', f.geometry().area() )
    ...:     
0 Piemonte 	 25393881930.289486
1 Valle d'Aosta 	 3258837560.7730026
2 Lombardia 	 -23862884335.37197
3 Trentino-Alto Adige 	 13607548166.78475
4 Veneto 	 18343552567.801147
5 Friuli Venezia Giulia 	 -7934088572.041777
6 Liguria 	 -5414352990.638311
7 Emilia-Romagna 	 -22529657706.320057
8 Toscana 	 -22961496921.925686
9 Umbria 	 8459510252.238089
10 Marche 	 9343412244.844238
11 Lazio 	 -17228723623.873173
12 Abruzzo 	 10829031555.9828
13 Molise 	 4461183416.968442
14 Campania 	 -13663229485.754004
15 Puglia 	 -19536279509.59188
16 Basilicata 	 -10072710736.895847
17 Calabria 	 15215124598.480162
18 Sicilia 	 -25823646416.06542
19 Sardegna 	 -24093749596.157593
```

**Comment by elpaso** [comment] 2024-05-29 09:31
... and here is the geometry validation result:

![immagine](https://github.com/qgis/QGIS/assets/142164/10423916-2516-4435-b3ff-7c0005b77920)

**Comment by elpaso** [comment] 2024-05-29 09:32
I guess we should close this ticket.

**Comment by pigreco** [comment] 2024-05-29 10:29
@elpaso 
I tested with other files, for me the problem persists.
Should I share another dataset as soon as I can, or should we close this ticket and open another?

**Comment by pigreco** [comment] 2024-05-29 10:39
@elpaso 
Thanks for your time Alessandro.
I close ticket

As you have clearly pointed out, it seems like a data-related problem.

**Comment by aborruso** [comment] 2024-05-29 12:30
@elpaso in the @pigreco sample video he has that the interface has values, and that sorting is not done on those values.
There are definitely topological errors, but the interface does not sort with respect to values that have been computed.

Also in your calculation I see negative area values, probably due to topological errors. Negative values that @pigreco does not have, and which are not returned by GDAL.
In duckdb (then in gdal) if I run

```
duckdb -c "select COD_REG,DEN_REG,FLOOR(ST_Area(GEOM)) AS AREA from st_read('Reg01012023_g_WGS84.shp') order by AREA desc"
```

I have

| COD_REG |        DEN_REG        |     area      |
|--------:|-----------------------|--------------:|
| 19      | Sicilia               | 25823747101.0 |
| 1       | Piemonte              | 25393881930.0 |
| 20      | Sardegna              | 24094030578.0 |
| 3       | Lombardia             | 23862315752.0 |
| 9       | Toscana               | 22984035404.0 |
| 8       | Emilia-Romagna        | 22499871143.0 |
| 16      | Puglia                | 19535673191.0 |
| 5       | Veneto                | 18343552567.0 |
| 12      | Lazio                 | 17226818021.0 |
| 18      | Calabria              | 15216065606.0 |
| 15      | Campania              | 13663252600.0 |
| 4       | Trentino-Alto Adige   | 13607548166.0 |
| 13      | Abruzzo               | 10829032566.0 |
| 17      | Basilicata            | 10072742785.0 |
| 11      | Marche                | 9343412244.0  |
| 10      | Umbria                | 8464379534.0  |
| 6       | Friuli Venezia Giulia | 7934115959.0  |
| 7       | Liguria               | 5414542477.0  |
| 14      | Molise                | 4461183416.0  |
| 2       | Valle d'Aosta         | 3258837560.0  |

**Comment by pigreco** [comment] 2024-05-29 18:20
@elpaso 
I have to reopen the ticket.
I changed the dataset (which I attach) but the problems remain:
1. does not sort using geometric functions like $area;
2. does not report any problems, see video.

https://github.com/qgis/QGIS/assets/7631137/302c9368-39a2-4938-8c16-3de942e3cbd3


[polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip)

**Comment by elpaso** [comment] 2024-05-31 06:51
@aborruso @pigreco you were right: there was a bug. Thank you for the test data.

**Comment by pigreco** [comment] 2024-05-31 07:03
@elpaso 
I have to be honest, the credit goes to Andrea, otherwise I would have left the issue closed.

**Comment by aborruso** [comment] 2024-05-31 07:07
Thank you @elpaso 

However, I have a curiosity: how come you had area negative values in the output?

Do your code and `$area` have a different engine? I ask because, beyond the corrupted geometry, the areas calculated by @pigreco are not negative.

**Comment by pigreco** [comment] 2024-05-31 07:10
@elpaso 

I also ask, with which processing algorithm did you calculate this table and in particular the highlighted column?
![image](https://github.com/qgis/QGIS/assets/7631137/3a6f90bc-cad8-4a07-a017-238b0ed6c5a9)

**Comment by elpaso** [comment] 2024-05-31 07:21
> Thank you @elpaso
> 
> However, I have a curiosity: how come you had area negative values in the output?
> 
> Do your code and `$area` have a different engine? I ask because, beyond the corrupted geometry, the areas calculated by @pigreco are not negative.

I just added a calculated field with `$area` expression. 

If I am not wrong the area is calculated using GEOS library, I might have different version here. 

You can try the python code from the console to check what `feature.geometry().area()` returns.

@pigreco I think I used 

![immagine](https://github.com/qgis/QGIS/assets/142164/b03d1eba-7e74-497a-98d8-9599081c4d16)

**Comment by pigreco** [comment] 2024-05-31 10:04
@elpaso 
i used this build (https://github.com/qgis/QGIS/pull/57624#issuecomment-2141368117), it still doesn’t work

https://github.com/qgis/QGIS/assets/7631137/058d56ed-2c07-41ce-976b-f5fb1e0c6055

**Comment by elpaso** [comment] 2024-05-31 10:30
> @elpaso i used this build ([#57624 (comment)](https://github.com/qgis/QGIS/pull/57624#issuecomment-2141368117)), it still doesn’t work
> 2024-05-31_11h56_29.mp4

What dataset are you using now for testing?

**Comment by pigreco** [comment] 2024-05-31 10:43
> What dataset are you using now for testing?

I used both datasets shared in this issue, I attach the last one used

[polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip)

https://github.com/qgis/QGIS/assets/7631137/4e5e6fec-0773-4a41-8501-8d0afced36dd

**Comment by pigreco** [comment] 2024-05-31 16:44
> Can you test the last commit when the build is ready?

unfortunately it still doesn't work :-(

https://github.com/qgis/QGIS/assets/7631137/3cdda1a2-8492-4058-a297-20d92a392e67

[polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip)

**Comment by pigreco** [comment] 2024-05-31 18:34
@elpaso 
> @pigreco works for me:

I have win 11 and it doesn't work

**Comment by agiudiceandrea** [comment] 2024-05-31 22:22
The fix doesn't work also for me on Windows 10 using the MinGW64 build available at https://github.com/qgis/QGIS/actions/runs/9318038831 (PR #57624 - b561aca27f962bfb7567a4e53efb1fa293082b66) and the [polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip) layer.

**Comment by elpaso** [comment] 2024-06-01 05:41
@agiudiceandrea I tested the build on windows and I can confirm it doesn't work while it works on Linux. 

I'm not sure if I can fix it on windows: this is going to be tricky (and slow).

**Comment by agiudiceandrea** [comment] 2024-06-01 06:41
Thanks @elpaso. While I don't see a reason for which your fix doesn't work on Windows (and I cannot test on Linux) maybe the following evidences can help you:
- the issue doesn't occur with a memory layer (i.e. select all the feature in the original layer, copy the feature, past the features as Temporary Scratch Layer)
- the issue doesn't occur if a virtual field with an expression involving the features geometry is added to the layer using the field calculator.

Anyway, it seems to me your fix may have introduced a new issue, at least on Windows: adding any custom sort order expression, such sort order expression is lost when the attribute table is closed:

https://github.com/qgis/QGIS/assets/16253859/d4feed60-292c-4745-ba69-617cb7a1c566

Such issue doesn't occur using QGIS 3.36.3 or QGIS 3.34.7:

https://github.com/qgis/QGIS/assets/16253859/6b1e155e-7bdb-47ae-ac6b-71f2a23fbb23

**Comment by agiudiceandrea** [comment] 2024-06-01 06:54
Thanks @elpaso. While I don't see a reason for which your fix doesn't work on Windows (and I cannot test on Linux) maybe the following evidences can help you:
- the issue doesn't occur with a memory layer (i.e. select all the feature in the original layer, copy the feature, past the features as Temporary Scratch Layer)
- the issue doesn't occur if a virtual field with an expression involving the features geometry is added to the layer using the field calculator.

Anyway, it seems to me your fix may have introduced a new issue, at least on Windows: adding any custom sort order expression, such sort order expression is lost when the attribute table is closed and subsequently reopened:

https://github.com/qgis/QGIS/assets/16253859/355ea63d-5456-420b-b1ea-c09618750cda


Such issue doesn't occur using QGIS 3.36.3 or QGIS 3.34.7:

https://github.com/qgis/QGIS/assets/16253859/c0477401-5c40-4d24-9890-1e8601e40160

**Comment by elpaso** [comment] 2024-06-01 07:18
@agiudiceandrea I am waiting for https://github.com/qgis/QGIS/pull/57630 to be merged, with that API in place I can simplify the code and see if that fixes the issue without side effects.

**Comment by elpaso** [comment] 2024-06-02 14:23
@agiudiceandrea @pigreco I tested the latest changes in PR https://github.com/qgis/QGIS/pull/57624 and it seems to be working as expected also on Windows.

**Comment by agiudiceandrea** [comment] 2024-06-02 18:01
Unfortunately, it seems to me the fix doesn't work on my Windows 10 system using the MinGW64 build available at https://github.com/qgis/QGIS/actions/runs/9338972878 (PR #57624 - a1fce5638e5913f05ce26900d9b300cde88e37bb) and the [polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip) layer.

**Comment by pigreco** [comment] 2024-06-02 19:15
> using the MinGW64 build available at https://github.com/qgis/QGIS/actions/runs/9338972878 (PR #57624 - [a1fce56](https://github.com/qgis/QGIS/commit/a1fce5638e5913f05ce26900d9b300cde88e37bb)) and the [polygon_test.zip](https://github.com/qgis/QGIS/files/15489159/polygon_test.zip) layer.

Unfortunately I have to confirm that it doesn't work on Win 11 either.

https://github.com/qgis/QGIS/assets/7631137/8a989679-f722-45c9-9e29-c7b4c9a5930e

**Comment by elpaso** [comment] 2024-06-03 07:16
@pigreco @agiudiceandrea I think I've finally found the reason why I couldn't reproduce: try setting the default table mode to 

![immagine](https://github.com/qgis/QGIS/assets/142164/29815178-736e-4813-a940-caacb05e4c10)

does it make any difference?

**Comment by agiudiceandrea** [comment] 2024-06-03 07:28
@elpaso, yes, settings such non default mode, the issue doesn't occur even using QGIS 3.36.3 or QGIS 3.34.7.

**Comment by pigreco** [comment] 2024-06-03 07:38
@elpaso 
I confirm what was said by @agiudiceandrea

**Comment by elpaso** [comment] 2024-06-03 07:48
This should do it for "Show all features":  https://github.com/qgis/QGIS/pull/57624/commits/e115e6df08b81aa323da00430152aea931cf2388

**Comment by agiudiceandrea** [comment] 2024-06-03 11:11
@elpaso, not completely fixed... The order is again incorrect after clicking on the "Reload the table" button.

https://github.com/qgis/QGIS/assets/16253859/6e37bdad-b9f9-4a05-97f9-a0416370b169

Anyway, does the fix actually needs to rely on the newly added compare methods to QgsFeatureRequest? If yes, then it cannot be backported to 3.34.

**Comment by elpaso** [comment] 2024-06-03 14:51
@agiudiceandrea ready for another test? https://github.com/qgis/QGIS/pull/57624

About the `compare()`, that is not strictly necessary but because now every call to `QgsAttributeTableModel::setRequest()` calls `prefetchSortData` (which can be costly) and because `setRequest()` is called a lot of times (I tried to optimize it too), I don't want this patch to make the overall loading time of the attribute table slower than it already is.

That said, I don't see why we shouldn't backport `compare()` it is a new API with absolutely no impact on any other part of the code.

Anyway, fixing this in master would be already a good achievement in itself.

**Comment by agiudiceandrea** [comment] 2024-06-03 19:20
> I don't see why we shouldn't backport `compare()`

Good to know!

I've tested the latest build and it seems to me the reported issue is completely fixed!

During the tests I've seen a glitch in the attribute table sorting functionality which is already present in current releases: changing the sorting expression the ascending/descending arrows are not removed if the sorting expression is not a simple field or is a geometry expression or is not related to any field. I'll open a new issue report.

**Comment by agiudiceandrea** [comment] 2024-06-04 07:01
> During the tests I've seen a glitch in the attribute table sorting functionality which is already present in current releases: changing the sorting expression the ascending/descending arrows are not removed if the sorting expression is not a simple field or is a geometry expression or is not related to any field. I'll open a new issue report.

See: https://github.com/qgis/QGIS/pull/57650.

**Closed** 2024-06-04 08:02 UTC
Labels: Attribute Table, Bug
