### ISSUE TITLE
Subscript and Superscript Single Labels expression bug

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29499] opened 2019-03-27 15:17 UTC
Author Name: **Uros Djuric** (Uros Djuric)
Original Redmine Issue: [21683](https://issues.qgis.org/issues/21683)
Affected QGIS version: 3.6.0
Redmine category:labelling

---
Hello,

I am trying to label my polygons using Single Label option.

I have set labeling to be in relation to the string from Attribute table column called _"Simboli"_
That column contains a set of different labels that were written using HTML sub and sup codes (e.g. _"K<sub>2</sub><sup>2,3</sup>"_). *(see Fig. number 1)*
After that, If I choose Expression dialogue, under the _"Output preview"_ I can see regular formatted Label, as I wanted it to be. *(see Fig. number 2)*
But, when I save everything, close all windows and come back to the map, again I can see only codes on my map *(see Fig. number 3)*, instead properly sub and sup formatted numbers (or letters etc.)

I suppose that this the bug, since within the "Output" preview everything is fine, but not on map canvas. 
Or maybe I didn't set something properly? I need this kind of labels in map canvas, not on print composer for which I know that support HTML rendering.

![sub_sup_label_BUG.png](https://issues.qgis.org/attachments/download/14676/sub_sup_label_BUG.png)

---

- [sub_sup_label_BUG.png](https://issues.qgis.org/attachments/download/14676/sub_sup_label_BUG.png) (Uros Djuric)

**Comment by nyalldawson** [comment] 2019-05-29 05:09
Duplicate of #14063

**Closed by nyalldawson** 2019-05-29 05:09 UTC
Labels: Bug, Labeling
