### ISSUE TITLE
DXF Export does not work properly since version 3.8

### ISSUE THREAD

**Issue by zabi-gis** [qgis/QGIS#37202] opened 2020-06-14 15:28 UTC
Exporting dxf files does not work properly since version 3.8
 -Coordinate system transformation
 -Polyline  and Symbol not optimal

**Comment by baswein** [comment] 2020-06-15 00:01
I also recently discovered that the DXF CRS was not transforming correctly. 
If I make a square feature in a shapefile in CRS 30245 and export it with the dxf export as 30245 and then re-import it it works fine. But if I try to translate the CRS during the process it doesn't work.
![image](https://user-images.githubusercontent.com/15817745/84607162-bd64d800-ae79-11ea-9b30-16908abcd8f3.png)

**Comment by nyalldawson** [comment] 2020-06-15 02:51
Please provide more details (including a sample project) in order to reproduce this bug

**Comment by baswein** [comment] 2020-06-15 03:20
@nyalldawson @zabi-gis - Here is my sample project. I realize that I am butting into this issue and this may or may not be related to @zabi-gis issues. If you want me to start another thread  I am happy to. 
My issues started when I had a property line that kept coming into CAD at a weird size. Eventually I created this squares test. I know that it is probably complicated by the fact that I am going from feet to meters. Also I did not try this on a clean profile so it could be getting messed up there. QGIS 3.12.3 
[Vermont_dxf_CRS_issues.zip](https://github.com/qgis/QGIS/files/4777860/Vermont_dxf_CRS_issues.zip)
In my file naming L=Layer D=DXF M=Map.
Thanks!

**Comment by baswein** [comment] 2020-08-18 18:12
DXF export is now creating invalid files if unit conversion occurs. QGIS 3.14.1
![image](https://user-images.githubusercontent.com/15817745/90548006-535afe80-e15a-11ea-9b5e-1a625fb60c6f.png)
AutoCAD says the errors start on line 710 where numbers have been replaced with inf.0.
![image](https://user-images.githubusercontent.com/15817745/90548802-818d0e00-e15b-11ea-83dd-57096fea787a.png)
Here are some test files.
[DXF_TEST.zip](https://github.com/qgis/QGIS/files/5092067/DXF_TEST.zip)
In my file naming L=Layer D=DXF M=Map.

**Comment by os-ai** [comment] 2021-03-12 06:23
In **version 3.18** - Export Project to DXF crashes (unable to load the selection window)

In **version 3.16** - Export Project to DXF  - Symbols do not appear identical. Unable to export multiple vectors that have different CRS's (eg. mix of WGS, pesudo-mercator and UTM), only the vectors with the same CRS as the output DXF CRS selected will appear. i.e. reprojecting error. This is reproducible. 

In **version 3.10.14** - Export Project to DXF works fine - reprojecting multiple CRS's works fine. Symbols in both QGIS and DXF appear the same.

**Comment by antoniolocandro** [comment] 2021-05-27 21:24
I had problems exporting lines in UTM and the data got rotated, polygon worked as expected

**Comment by AlisterH** [comment] 2021-06-03 02:55
I suggest closing this ticket.  The current issues are covered by #41858 (crash in 3.18) and #43449 (reprojection failing in 3.16).

**Comment by nyalldawson** [comment] 2021-06-03 04:58
Duplicate of https://github.com/qgis/QGIS/issues/43449

**Closed by nyalldawson** 2021-06-03 04:58 UTC
Labels: Bug, DXF/DWG, Regression
