### ISSUE TITLE
Adding a layout report page number

### ISSUE THREAD

**Issue by nicolasmcfadden** [qgis/QGIS#37060] opened 2020-06-09 08:54 UTC
**Feature description.**

QGIS would rock even more if it were possible to have layout page numbers! I have tried a few times with @layout_page but the number remains 1. Maybe I'm missing something...

**Additional context**

I found this page that mentions the same problem:
https://gis.stackexchange.com/questions/325909/adding-page-number-in-qgis-report

Otherwise, keep up the awesome work!

**Comment by gioman** [comment] 2020-06-09 09:47
@nicolasmcfadden "@layout_page" works as expected here, you may want to detail more about your case where it does not work.

**Comment by nicolasmcfadden** [comment] 2020-06-10 03:46
My case is the most basic one : a report with a Field Group Section as you can see in the screenshot. On every page i have an "Add Label" box in which I have [%'Page ' ||   @layout_page %]. When I choose to print the report to pdf, I get "Page 1" printed on all pages.
This isn't a unique problem as shown in the unresolved stackexchange ticket.

**Comment by nyalldawson** [comment] 2020-09-15 22:45
Duplicate of #33636

**Closed by nyalldawson** 2020-09-15 22:45 UTC
Labels: Feature Request, Print Layouts, Reports
