### ISSUE TITLE
Raster Legend not sorting correct when edited due to decimal separation

### ISSUE THREAD

**Issue by jkr-wrk** [qgis/QGIS#39757] opened 2020-11-02 15:01 UTC
Version QGis 3.16.0

bug not in QGIS 3.14.15

Language settings: Dutch
Country settings: Dutch

I have a style saved in QGis 3.14.15. When using this style in QGis 3.16 it works good.
But changing the value with a decimal precision the legend items moves to the bottem.

Closing and opening the legend settings, shows the correct order again.

See attachments for explanation.
Step 1
![Knipsel 1](https://user-images.githubusercontent.com/73838413/97882909-78581a00-1d24-11eb-8473-ed4b99880c4c.PNG)
Step 2
![Knipsel2](https://user-images.githubusercontent.com/73838413/97882951-85750900-1d24-11eb-8c12-93a8141d2a24.PNG)
Step 3
![Knipsel3](https://user-images.githubusercontent.com/73838413/97882983-91f96180-1d24-11eb-96cb-b9ea77e0b10b.PNG)

**Comment by roya0045** [comment] 2020-11-02 15:04
related or duplicate of #39685

**Comment by PedroVenancio** [comment] 2020-11-02 15:42
I've reported https://github.com/qgis/QGIS/issues/39685 and I can also confirm this one, that should be related. 

But the problem is not only in sorting, because the definition of the class breaks becomes a mess, as it does not recognize the point as the decimal separator (like on previous versions).

@elpaso do you think this can be a side efect of https://github.com/qgis/QGIS/pull/39088 ?

**Comment by elpaso** [comment] 2020-11-02 15:54
@PedroVenancio it might be related, let me have a look to both issue.

**Comment by elpaso** [comment] 2020-11-02 18:46
Looks like it is not directly related (all that shader code is of course somewhat related) but the bug has probably been there for a while (far before my latest changes). 

There appear to be multiple issues here, in particular, when using "Discrete" interpolation min value gets recalculated totally wrong (after you edit some values), this messes all up (sorting etc.).

Other issues are related to the precision used: all shader code assumes `double` but if your raster is `float` wierd thing happens (because of the well known different internal representation of numbers between float and double).

I'll try to fix the issues that I can see, but I'll ask your help @PedroVenancio and @jkr-wrk to test the patches.

**Comment by PedroVenancio** [comment] 2020-11-02 23:01
> I'll try to fix the issues that I can see, but I'll ask your help @PedroVenancio and @jkr-wrk to test the patches.

Of course @elpaso I will test the patches. Just point me to the windows binaries.

**Closed** 2020-11-13 09:38 UTC
Labels: Bug, Raster, Symbology
