### ISSUE TITLE
Grid Values to Points: could not initialize data objects

### ISSUE THREAD

**Issue by danielpaz88** [qgis/QGIS#34464] opened 2020-02-13 20:48 UTC
When I try to use the tool, I get this error "Grid Values to Points: could not initialize data objects".  I have the version 3.4.13 Madeira.

Procesando algoritmo...
Algoritmo 'Raster values to points' comenzando…
Parámetros de entrada:
{ 'GRIDS' : ['B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/ndvilote.tif'], 'NODATA' : True, 'POLYGONS' : None, 'SHAPES' : 'B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/grilla.shp', 'TYPE' : 0 }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/5df798c011354a0da6f68f3b70a1cf70/ndvilote.sgrd" -FILES "B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/ndvilote.tif"
shapes_grid "Grid Values to Points" -GRIDS "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/5df798c011354a0da6f68f3b70a1cf70/ndvilote.sgrd" -NODATA true -TYPE 0 -SHAPES "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/a4d3ffc73ed74f96b03a4340d7b4fd38/SHAPES.shp"

C:\Users\daniel\Documents>set SAGA=C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr

C:\Users\daniel\Documents>set SAGA_MLB=C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr\modules

C:\Users\daniel\Documents>PATH=C:\PROGRA~1\QGIS3~1.4\apps\qgis-ltr\bin;C:\PROGRA~1\QGIS3~1.4\apps\grass\grass78\lib;C:\PROGRA~1\QGIS3~1.4\apps\grass\grass78\bin;C:\PROGRA~1\QGIS3~1.4\apps\Python37;C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.4\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.4\apps\Python37;C:\PROGRA~1\QGIS3~1.4\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.4\apps\Python27\Scripts;C:\PROGRA~1\QGIS3~1.4\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\WBem;C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\pywin32_system32;C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\numpy\.libs;C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\scipy\extra-dll;;C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr;C:/PROGRA~1/QGIS3~1.4/apps\saga-ltr\modules

C:\Users\daniel\Documents>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/5df798c011354a0da6f68f3b70a1cf70/ndvilote.sgrd" -FILES "B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/ndvilote.tif"
Error: select a library
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

67 loaded tool libraries (607 tools):
- climate_tools
- contrib_perego
- db_odbc
- db_pgsql
- docs_html
- garden_3d_viewer
- garden_fractals
- garden_games
- garden_learn_to_program
- garden_webservices
- grid_analysis
- grid_calculus
- grid_calculus_bsl
- grid_filter
- grid_gridding
- grid_spline
- grid_tools
- grid_visualisation
- imagery_classification
- imagery_isocluster
- imagery_maxent
- imagery_photogrammetry
- imagery_segmentation
- imagery_svm
- imagery_tools
- io_esri_e00
- io_gps
- io_grid
- io_grid_image
- io_shapes
- io_shapes_dxf
- io_table
- io_virtual
- pj_georeference
- pj_geotrans
- pointcloud_tools
- pointcloud_viewer
- shapes_grid
- shapes_lines
- shapes_points
- shapes_polygons
- shapes_tools
- shapes_transect
- sim_cellular_automata
- sim_ecosystems_hugget
- sim_erosion
- sim_fire_spreading
- sim_hydrology
- sim_ihacres
- sim_qm_of_esp
- sim_rivflow
- statistics_grid
- statistics_kriging
- statistics_points
- statistics_regression
- ta_channels
- ta_compound
- ta_hydrology
- ta_lighting
- ta_morphometry
- ta_preprocessor
- ta_profiles
- ta_slope_stability
- table_calculus
- table_tools
- tin_tools
- tin_viewer

type -h or --help for further information

C:\Users\daniel\Documents>call saga_cmd shapes_grid "Grid Values to Points" -GRIDS "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/5df798c011354a0da6f68f3b70a1cf70/ndvilote.sgrd" -NODATA true -TYPE 0 -SHAPES "C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/a4d3ffc73ed74f96b03a4340d7b4fd38/SHAPES.shp"
Error: executing tool [Grid Values to Points]
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 2.3.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS3~1.4\apps\saga-ltr\modules\
library name: shapes_grid
library : Grid Tools
tool : Grid Values to Points
author : O.Conrad (c) 2001
processors : 4 [4]
____________________________

Load grid: C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/5df798c011354a0da6f68f3b70a1cf70/ndvilote.sgrd...
failed
Grid Values to Points: could not initialize data objects

C:\Users\daniel\Documents>exit
Ejecución completada en 35.09 segundos
Resultados:
{'SHAPES': 'C:/Users/daniel/AppData/Local/Temp/processing_0b72e46ba3514d71a5c7360cdb65ba82/a4d3ffc73ed74f96b03a4340d7b4fd38/SHAPES.shp'}

Cargando las capas resultantes
Las siguientes capas no se generaron correctamente.<ul><li>B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/grilla.shp</li></ul>Puede comprobar el «Panel de mensajes del registro» en la ventana principal de QGIS para encontrar más información sobre la ejecución del algoritmo.

**Comment by gioman** [comment] 2020-02-14 10:03
@danielpaz88 just tried on QGIS 3.10.2 on Windows with some data from the QGIS sample data set, it works.

Please try using input that are stored in patch *without* spaces and special characters. Yours seems to be "B:/geomatica/inta/Archivos para práctico Análisis de Ensayo Mediante NDVI y Mapa de Rendimiento con Q-GIS/Imagenes/" which has both.

**Comment by danielpaz88** [comment] 2020-02-18 01:32
Thanks. The error persists. Now I changed the path but the output is the following one:

**Comment by danielpaz88** [comment] 2020-02-18 01:42
I also get this error: (python error)

2020-02-17T22:37:29     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\gui\BatchAlgorithmDialog.py", line 182, in runAlgorithm
              handleAlgorithmResults(self.algorithm(), context, multi_feedback, False)
              File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins\processing\gui\Postprocessing.py", line 124, in handleAlgorithmResults
              feedback.reportError(msg)
             TypeError: reportError(self, error: str, fatalError: bool): not enough arguments

**Comment by gioman** [comment] 2020-02-18 09:18
> C:\Users\daniel\Documents>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/daniel/AppData/Local/Temp/processing_f6a80025895349febf461a8c1b999d49/e1ca6199ca0f4c23bc9379406804a371/ndvilote.sgrd" -FILES "B:\geomatica\inta\Imagenes\ndvilote.tif"
> Error: select a library

@danielpaz88 I believe is the same as https://github.com/qgis/QGIS/issues/32953#issuecomment-555649562 

please check. Thanks!

**Comment by gioman** [comment] 2020-03-02 16:31
Closing as duplicate.

**Closed by gioman** 2020-03-02 16:31 UTC
Labels: Bug, Feedback, Processing

**Comment by ignaciobfp** [comment] 2022-05-03 11:48
Hello,

Having same problem here on fresh installation. I installed QGIS using Osgeo4W installer, I marked latest stable versions and libs for SAGA.

I think that all the functions that involve I/O with shapefiles are not working. I can use, for example, saga:multilevelbspline, but I cannot use saga:addrastervaluestopoints (even on temp layers).

Since I could not find specifi packages for gdal2 in the setup utility (even marking "Prev" option) I have tried to install gdal204.dll dependency manually to no avail (downloaded from gisinternals.com windows binaries), in both %windir%/system32 and the bin folders from QGIS and GRASS.

Log with error follows:

`Versión de QGIS: 3.24.2-Tisler
Revisión del código de QGIS: 13c1a028
Versión de Qt: 5.15.2
Python version: 3.9.5
Versión de GDAL: 3.4.2
Versión de GEOS: 3.10.2-CAPI-1.16.0
Versión de PROJ: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 1c17a7)
SAGA version 7.8.2 is not officially supported - algorithms may encounter issues
El algoritmo comenzó en: 2022-05-03T13:48:47
Algoritmo 'Add Raster Values to Points' comenzando…
Parámetros de entrada:
{ 'GRIDS' : ['IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&service=WMS&version=1.3.0&styles=&format=image/png&transparent=true&layers=B05&crs=EPSG:32630&url=https%3A%2F%2Fservices.sentinel-hub.com%2Fogc%2Fwms%2Fe83e35c5-44c8-4beb-8298-e18e724dcfda%3FshowLogo%3Dfalse%26time%3D2022-03-01%252F2022-03-31%252FP1D%26priority%3DleastCC%26maxcc%3D100%26preview%3D1'], 'RESAMPLING' : 3, 'RESULT' : 'TEMPORARY_OUTPUT', 'SHAPES' : 'D:/Escritorio 2019/Pep/0.QGis/Satelites/Pruebas/Gracianoshp_sentinel.shp' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/af8b5f40ea8f4739a6621f5345ca0715/Sentinel2L1CB05WMS2022030120220331100leastCCEPSG_32630.sgrd" -FILES "IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&service=WMS&version=1.3.0&styles=&format=image/png&transparent=true&layers=B05&crs=EPSG:32630&url=https%3A%2F%2Fservices.sentinel-hub.com%2Fogc%2Fwms%2Fe83e35c5-44c8-4beb-8298-e18e724dcfda%3FshowLogo%3Dfalse%26time%3D2022-03-01%252F2022-03-31%252FP1D%26priority%3DleastCC%26maxcc%3D100%26preview%3D1"
shapes_grid "Add Grid Values to Points" -SHAPES "D:/Escritorio 2019/Pep/0.QGis/Satelites/Pruebas/Gracianoshp_sentinel.shp" -GRIDS "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/af8b5f40ea8f4739a6621f5345ca0715/Sentinel2L1CB05WMS2022030120220331100leastCCEPSG_32630.sgrd" -RESAMPLING 3 -RESULT "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/e79e2b9c23df48f89b2ef16ef2ea11a1/RESULT.shp"

C:\WINDOWS\system32>set SAGA=C:/OSGeo4W/apps\saga

C:\WINDOWS\system32>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

C:\WINDOWS\system32>PATH=C:\OSGeo4W\apps\qgis\bin;C:\OSGeo4W\apps\grass\grass78\lib;C:\OSGeo4W\apps\grass\grass78\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

C:\WINDOWS\system32>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/af8b5f40ea8f4739a6621f5345ca0715/Sentinel2L1CB05WMS2022030120220331100leastCCEPSG_32630.sgrd" -FILES "IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&service=WMS&version=1.3.0&styles=&format=image/png&transparent=true&layers=B05&crs=EPSG:32630&url=httpsAFFservices.sentinel-hub.comFogcFwmsFe83e35c5-44c8-4beb-8298-e18e724dcfdaFshowLogoDfalse6timeD2022-03-0152F2022-03-3152FP1D6priorityDleastCC6maxccD1006previewD1"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)


87 loaded tool libraries (754 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *


*) tool chain libraries

Error: select a library
type -h or --help for further information


C:\WINDOWS\system32>call saga_cmd shapes_grid "Add Grid Values to Points" -SHAPES "D:/Escritorio 2019/Pep/0.QGis/Satelites/Pruebas/Gracianoshp_sentinel.shp" -GRIDS "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/af8b5f40ea8f4739a6621f5345ca0715/Sentinel2L1CB05WMS2022030120220331100leastCCEPSG_32630.sgrd" -RESAMPLING 3 -RESULT "C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/e79e2b9c23df48f89b2ef16ef2ea11a1/RESULT.shp"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

____________________________
library path: C:\OSGeo4W\apps\saga\tools\
library name: shapes_grid
library : shapes_grid
tool : Add Grid Values to Points
identifier : 0
author : O.Conrad (c) 2003
processors : 8 [8]
____________________________

Load shapes: D:/Escritorio 2019/Pep/0.QGis/Satelites/Pruebas/Gracianoshp_sentinel.shp...


Loading grid: C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/af8b5f40ea8f4739a6621f5345ca0715/Sentinel2L1CB05WMS2022030120220331100leastCCEPSG_32630.sgrd...
failed
Add Grid Values to Points: could not initialize data objects
Error: executing tool [Add Grid Values to Points]

C:\WINDOWS\system32>exit
Execution completed in 4.47 segundos
Resultados:
{'RESULT': 'C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/e79e2b9c23df48f89b2ef16ef2ea11a1/RESULT.shp'}

Cargando las capas resultantes
Las siguientes capas no se generaron correctamente.
• C:/Users/Juan/AppData/Local/Temp/processing_JGgECS/e79e2b9c23df48f89b2ef16ef2ea11a1/RESULT.shp
Puede comprobar el «Panel de mensajes del registro» en la ventana principal de QGIS para encontrar más información sobre la ejecución del algoritmo.`
