### ISSUE TITLE
Model fails to raise the correct error when attribute selector matches no field

### ISSUE THREAD

**Issue by why-not-try-calmer** [qgis/QGIS#54988] opened 2023-10-19 12:17 UTC
### What is the bug or the crash?

It is a bug. Consider the screenshot below:
![image](https://github.com/qgis/QGIS/assets/19554213/9f37725b-c17a-48d4-ad0c-3bb78a2b4f9e)

`Selection attribute` = `name` is such that it tries to select the field `name` in the attributes table of the layer features. Problem: when there is no match, instead of raising something like

> Error, no feature with name: 'non referring name'

it just continues, and will (probably) throw on the next step in the model algorithm. So at the end of the day the exception that the user receives is not the exception representative of the underlying issue.

### Steps to reproduce the issue

1. Create a layer and add features with an attribute/field `A`.
2. Create a model using the `Extract by attribute` step.
3. Apply the model to the layer, where `A` is the attribute used by `Extract by attribute` and where the attribute value does not exist.

### Versions

3.32.3, commit a2eff0461663c60d5689408a17a064ebe82e4c533bba67d38788011864a01b93

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment] 2023-10-23 01:25
I can't reproduce:

![image](https://github.com/qgis/QGIS/assets/1829991/3ad40e87-64e8-47dc-8654-61da65a622c1)

Am i misinterpreting the report?

**Comment by why-not-try-calmer** [comment] 2023-10-23 05:55
Let's consider an attribute table with a single feature and a single attribute, _name_. Let "a" be the value of _name_ for the feature. The bug seems to be that selecting that feature by _name_ using a value different from "a" will not raise the expected exception, at least not if selecting that feature is not the last step in the model's algorithm.

**Comment by nyalldawson** [comment] 2023-10-23 06:57
That's intentional, and necessary for many models. There's an explicit "raise exception" algorithm you can use if for your use case you want to guarantee that some features match the filter.

Closing as "wontfix"

**Closed by nyalldawson** 2023-10-23 06:57 UTC
Labels: Feedback, Bug, Modeller

**Comment by why-not-try-calmer** [comment] 2023-10-23 08:06
I don't think it's reasonable to close as "Won't fix". Perhaps there's a misunderstanding. The bug is __not__ that `Extract by attribute` should raise when the attribute value matches no feature. The bug is that the step that immediately depends on `Extract by attribute` will raise for a reason that is completely rubbed under the carpet.

In other words, when the input of a step is not defined, report the not-definedness to the user, especially when the not-definedness is the consequence of `Extract by attribute` matching no feature.

**Comment by nyalldawson** [comment] 2023-10-23 08:59
> In other words, when the input of a step is not defined,

It will be defined though -- the input will be an empty layer with the same structure as the layer would have if it did have features

**Comment by why-not-try-calmer** [comment] 2023-10-23 09:47
I see, I though that steps wore their requirements on their sleeves, so that it would be feasible, for any step that require features from its inputs, to throw something along the lines of `Sorry, I need features to work on, but the input I was provided with (output of step XYZ) provided none. That would require a complete revamp of the processing module?
