### ISSUE TITLE
Crash when using "Identify Features" in Ubuntu?

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29923] opened 2019-05-21 05:26 UTC
Author Name: **Mark Topinka** (Mark Topinka)
Original Redmine Issue: [22110](https://issues.qgis.org/issues/22110)
Affected QGIS version: 3.6.3
Redmine category:map_tools

---
Hi - I am having problems with the Identify Feature function - when I load something (either a ESRI shapefile or a raster both lead to this problem), click Identify Features, and then mouse over the main area of QGIS showing the raster or shape, QGIS immediately crashes.  I've tried enabling log file, but nothing is written to it during the crash.  This only happens in Ubuntu, I haven't been able to reproduce it with the same version (nominally) of QGIS running on Windows.  I'm using QGIS 3.6.3, and Ubuntu 18.04.2 LTS.

---

- [example.tif](https://issues.qgis.org/attachments/download/14964/example.tif) (Mark Topinka)

**Comment by elpaso** [comment] 2019-05-28 10:11
I'm afraid this is probably a local issue, I personally build and use different versions of QGIS daily on 18.04 and I've never seen that issue.

**Comment by jgrocha** [comment] 2019-05-28 17:54
- Unable to reproduce, using QGIS 3.6.3-Noosa, on Ubuntu 18-04.
- Unable to see the attachment.
- There is no useful information how to reproduce the bug and about the specific environment (how QGIS was installed, packages versions, QT versions, etc).

I suggest to close this issue. It can be reopened if the author is able to show how to reproduce it.

At least, I suggest to drop labels High Priority, Crash/Data Corruption right now.

**Comment by svikas** [comment] 2019-07-31 17:20
To potentially help others with the warnings above

`Warning: QXcbConnection: Failed to initialize XRandr
Warning: Qt: XKEYBOARD extension not present on the X server.`
`Warning: qt_xcb_createCursorXRender: query_pict_formats failed
Warning: The X11 connection broke (error 2). Did the X11 server die?`

This issue appears to be independent of QGIS. I've seen this issue occur based on the VNC client and desktop being used (if it's being used in to access a remote Ubuntu instance). 

While there may be better ways to set this up, to check if it is indeed the issue I'd recommend setting up tigervnc with the xorg-extension and use Gnome 3 desktop. That has worked for me in the past.

**Comment by gioman** [comment] 2019-08-25 08:52
> I suggest to close this issue. It can be reopened if the author is able to show how to reproduce it.

done.

**Closed by gioman** 2019-08-25 08:52 UTC
Labels: Bug, Crash/Data Corruption, Feedback, High Priority, Map Tools
