### ISSUE TITLE
Layout composer wrong legend when using the size assistant

### ISSUE THREAD

**Issue by AndreasEm** [qgis/QGIS#32710] opened 2019-11-07 09:47 UTC
When setting the size of points acording to a datset (sieze>Assistant), the plot works fine in the map view but no symbols appear in the leged

![image](https://user-images.githubusercontent.com/57481520/68378140-e4249880-014b-11ea-852c-3ba97608f2ed.png)

![image](https://user-images.githubusercontent.com/57481520/68378198-facaef80-014b-11ea-9060-7870f2527d12.png)

**Comment by nyalldawson** [comment] 2020-11-12 01:17
Duplicate of https://github.com/qgis/QGIS/issues/19761

**Closed by nyalldawson** 2020-11-12 01:17 UTC
Labels: Bug, Print Layouts
