### ISSUE TITLE
CSV import not working

### ISSUE THREAD

**Issue by mattbeets** [qgis/QGIS#41924] opened 2021-02-28 17:52 UTC
I just updated to QGIS 3.18 and tried to add a Delimited Text Layer with the same csv file I had just succesfully added before updating QGIS. 
But in QGIS 3.18, I got the error "layer is not valid". I tried different settings and tweaks but nothing worked. Not even after exporting a working shapefile to CSV and using that for import. I normally do this all the time with no problems. Finally, I gave up and reverted to QGIS 3.16, tried to add any csv file, including the one that did not work in 3.18, and with the same settings as initially, and it worked with no problems at all. 
So the only explanation I can arrive at is that the "Add Delimited Text Layer" function in QGIS 3.18 is not working properly for some reason.

**Comment by gioman** [comment] 2021-02-28 18:45
@mattbeets please attach your CSV file.

**Comment by mattbeets** [comment] 2021-02-28 19:20
The original file was 300,000 rows so I tried also with this small snippet of the same. Same problem.
I also tried both decimal separator settings in the import. None of them worked.
[anlaeg_all_4326_snippet.zip](https://github.com/qgis/QGIS/files/6057768/anlaeg_all_4326_snippet.zip)

**Comment by gioman** [comment] 2021-02-28 20:00
@mattbeets no issues whatsoever on Linux and Windows. Please try with a new QGIS profile.

**Comment by agiudiceandrea** [comment] 2021-02-28 20:38
No issue importing the provided csv file on Windows 7 with QGIS 3.19.0-Master code revision d6a706a8

**Comment by mattbeets** [comment] 2021-02-28 21:02
@gioman Ok that's strange. What do you mean "try with a new QGIS profile"? Do you mean reinstall? (I am on Windows 10, by the way so I guess it should work).

**Comment by agiudiceandrea** [comment] 2021-02-28 21:07
@mattbeets see https://docs.qgis.org/3.16/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by pjshelton** [comment] 2021-03-01 00:04
No issue on that snippet here either.  Windows 10 and a fresh install of 3.18.0

**Comment by wmeinolf** [comment] 2021-03-01 16:13
Same issue here. I can't import CSV under QGIS 3.18 on Windows 10 any more. Import worked w/o any problem on 3.16.3 running on UBUNTU VM. Data are in a plain txt file containing German Umlaute, special Characters äöüß and is UTF-8 coded. Earlier today I could import a Excel exported CSV without issues.

Sample Data:
[2020-03-17-adressen-th-mitKopf - Kopie.txt](https://github.com/qgis/QGIS/files/6062904/2020-03-17-adressen-th-mitKopf.-.Kopie.txt)

**Comment by gioman** [comment] 2021-03-01 16:28
> Same issue here.

@wmeinolf your data works fine here.

![Screenshot_20210301_162732](https://user-images.githubusercontent.com/1951107/109526990-17aad500-7aab-11eb-8082-d075b12eee8a.png)

Please try with a new QGIS profile.

**Comment by wmeinolf** [comment] 2021-03-01 16:55
Ok, here what I found: (1) Created new profile: Same issue. Then i recalled, that I sometimes had issues with german special characters in path name. So (2) I moved the text file from C:\Users\WMeinolf\Geodaten 2017\Thüringen\Hauskoordinaten Thüringen Stand 2018-03-15 to C:\Users\WMeinolf\OneDrive - BBV Deutschland GmbH, which has no ü in path name.

Import works perfect with old and new profile. Created (3) new subfolder named "Töst" and moved txt in new folder. No import possible. Renamed (4) folder to "Test", import possible. (5) Deleted layer imported and renamed Directory to "Tüst", again, no import possible.

I suspect, it's related to special characters in path name.  Here some characters to pick: ä ö ü ß

Thanks for your support!

**Comment by gioman** [comment] 2021-03-01 17:13
> I suspect, it's related to special characters in path name. Here some characters to pick: ä ö ü ß

@wmeinolf you should file a separate ticket called "cannot import CSV with delimited text tool of path contains special chars".

**Comment by gioman** [comment] 2021-03-01 17:13
> @wmeinolf you should file a separate ticket called "cannot import CSV with delimited text tool of path contains special chars".

@mattbeets it is also your issue?

**Comment by wmeinolf** [comment] 2021-03-01 17:25
@gioman : New Case is #41948

**Comment by mattbeets** [comment] 2021-03-01 17:53
@gioman I haven't had time to test it in 3.18, but looking at my filepath: it contains the Danish word "Øvelser", so that could probably explain the issue. Thank you for clearing that up, @wmeinolf :) I don't know if something like spaces or capital letters would also give problems? (unfortunately don't have time to reinstall 3.18 right now to test it myself).

**Comment by gioman** [comment] 2021-03-02 10:55
Duplicate of https://github.com/qgis/QGIS/issues/41948

**Closed by gioman** 2021-03-02 10:55 UTC
Labels: Bug, Delimited text data provider, Feedback
