### ISSUE TITLE
Feature edits dont save - temp layer 

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29838] opened 2019-05-08 16:54 UTC
Author Name: **Rob Erogaster** (Rob Erogaster)
Original Redmine Issue: [22024](https://issues.qgis.org/issues/22024)
Affected QGIS version: 3.6.2
Redmine category:editing

---
I added a geojson polygon layer.  Then I toggled editing, select a feature, and deleted it.  It disappears as expected.  Next, I toggle editing, click yes when prompted to save edits.  Then the deleted polygon re-appears.  In the source folder, I see a temp file with the saved edits (i.e. some_file..geojson.tmp).  If I remove the layers and re-add the geojson I meant to edit, it appears without the saved edits.

**Comment by rouault** [comment] 2019-07-12 11:22
yep duplicate of #28580. closing

**Closed by rouault** 2019-07-12 11:22 UTC
Labels: Bug, Editing, Feedback
