### ISSUE TITLE
Removing ArcGIS Rest Server connections

### ISSUE THREAD

**Issue by ColinMazengarb** [qgis/QGIS#54811] opened 2023-10-03 04:34 UTC
### What is the bug or the crash?

In QGIS 3.32.3, I have created some REST connections. However, despite following the simple menu for removing connections, this does not occur. 3.28 does not have this problem.

### Steps to reproduce the issue

1. Right click on connected service to bring up menu
2. Select 'Remove connections'
Result: connection persists! 

![Screenshot 2023-10-03 153042](https://github.com/qgis/QGIS/assets/126990750/0f875083-2053-402f-bee1-4b1fd3e75c89)

### Versions

QGIS version
3.32.3-Lima
QGIS code revision
67d46100b5
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
kart
1.0.12
koordinates
2.0.0
QuickWKT
3.1
soar
1.0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment] 2023-10-04 03:30
@ColinMazengarb duplicate of #54718 fixed in #54725. Will be available in 3.34

**Closed by DelazJ** 2023-10-04 03:30 UTC
Labels: Bug

**Comment by pathmapper** [comment] 2023-11-19 06:28
There are still issues with master (461a3158d01).

-> details in https://github.com/qgis/QGIS/issues/53321#issuecomment-1817761926
