### ISSUE TITLE
When I add additional vector layers QGIS freezes on me

### ISSUE THREAD

**Issue by matosang** [qgis/QGIS#39045] opened 2020-09-26 03:04 UTC
I've been working on a project for a quite a while, I've loaded many vector layers, including several hundred short line segments that are kmz files, as well as topo lines, lake and glacier polygons, rivers, roads, vegetation, hillshade, etc. I've also created about 50 Map themes and map layouts that use these layers in many different configurations. Everything is quite intricate and has taken a ton of time to set up. Unfortunately I've run into a problem where I can't load additional vector layers in. When I try to add a layer, the layer will appear in the layer panel, but the program will then freeze with a spinning wheel. Generally if I click a few more times QGIS will alert me that the program isn't responding, and I restart. Once or twice I left it for a long time, maybe 30 minutes, and it seemed to resolve and was usable again, but then froze up in the same manner shortly after.

I've tried trouble shooting and found that if I remove about 80 percent of the kmz files the project seems to function normally and I can add new layers, however this won't allow me to finish my project. Also, I was able to continue to add new kmz files fairly recently so I don't' understand why I'd need to remove so many files for it to work normally. I've tried to determine if there's a corrupted vector layer by removing the layers in different combinations but it doesn't seem like there's one file causing the issue.

The other possible problem I've tried to look at is whether the map themes could be causing an issue, perhaps if they link to a layer that I accidently deleted, but this doesn't seem to be the case. 

Is this a bug in QGIS?

When the issues occurs my hardware usage is: 20% cpu, 40 % memory, 1% disk. 
I'm on Windows 10 home, QGIS 3.10.4. I'm not sure how to count the number of layers but I'd assume there are around 350 kmz files (each quite simple, small lines representing hiking routes) plus about 20 layers that represent other map features: topo lines, lake and glacier polygons, rivers, roads, vegetation, hillshade, etc. A couple of those are large, such as the topo lines.

I used QConsolidate to package the project files and laylayers, which were mostly kmz, were reduced as gpkg files. The crashing issue still exist using this these files. Therefore I don't think it's the kmz format.

**Comment by matosang** [comment] 2020-09-26 03:37
One thing I just noticed while using the plugin Layer Board. When I use it to look at the layers, it identifies over 1200 layers. As part of my workflow I've been editing my vector layers in Google Earth and saving them as kmz for import as vector layers into QGIS. Later I often tweak the layers in Google earth and overwrite the kmz using the same name. those files edited vecor files show up in QGIS in their updated configuration without having to add them again. However, looking at Layer Board it looks like all of the previous kmz's that were overwritten are being considered as vector layers in the project. Most vector layers show up several times in the Layer Board list - The layer names are the same, but the IDs are not the same.- the number/letter code added to the name for the IDs are different. Instaead of tracking about 350 kmz, it's tracking over 1200, more than half of which were overwritten by a file with the same name. see the inlcuded screes shot to clarify. could this be causing my issues?

![image](https://user-images.githubusercontent.com/71899961/94329326-ec0d4700-ff6e-11ea-82c5-a0cb1e4c3e1a.png)

**Comment by elpaso** [comment] 2020-09-26 06:33
Have you tried with a clean user profile?

**Comment by gioman** [comment] 2020-09-27 08:00
@matosang this seems duplicate of https://github.com/qgis/QGIS/issues/38978

**Comment by Gustry** [comment] 2020-09-28 09:22
> Instaead of tracking about 350 kmz, it's tracking over 1200, more than half of which were overwritten by a file with the same name. see the inlcuded screes shot to clarify. could this be causing my issues?

In the LayerBoard plugin can you check the ghost column?

And indeed, try with a new QGIS user profile

**Comment by gioman** [comment] 2020-11-11 18:44
Closing for lack of further feedback and as likely duplicate.

**Closed by gioman** 2020-11-11 18:44 UTC
Labels: Bug, Feedback
