### ISSUE TITLE
FSC Tom-Bio plug in - Temporary OSGR Grid Squares layer - can't make permanent?

### ISSUE THREAD

**Issue by gideonsway** [qgis/QGIS#44075] opened 2021-07-07 10:16 UTC
I am using 3.20.0-Odense version. I can't believe this is new but nor can I find via Google/Git Hub
 etc answer. I am a novice so please be patient. I have greated Grid Layer using Tom-Bio on UK Nat Grid. But when I go to try to save by Make pernamanent or save as work I get  Save Error. I wonder if it is something to do with Export to vector file failed. _**Error: Feature write errors:Error converting value (Quadrant (5 km square)) for attribute field GridType: String of length 22 exceeds maximum field length (20_)**  Thanks for any help.
![Screen Shot 2021-07-05 at 17 00 36](https://user-images.githubusercontent.com/63467753/124741915-1c2d4180-df14-11eb-806e-e62f0f9b4831.png)

**Comment by jef-n** [comment] 2021-07-07 10:20
Duplicate of https://github.com/FieldStudiesCouncil/QGIS-Biological-Recording-Tools/issues/56 :)

**Closed** 2021-07-07 10:20 UTC

**Comment by gideonsway** [comment] 2021-07-07 10:30
Sorry Jürgen but I had put it on FSC bug report as you have said
(duplicate), but no one had responded after 2 days so i thought I must have
put it in wrong place, hence why I tried again. Martyn

On 7 July 2021 at 11:21:08, Jürgen Fischer ***@***.***) wrote:

Duplicate of FieldStudiesCouncil/QGIS-Biological-Recording-Tools#56
<https://github.com/FieldStudiesCouncil/QGIS-Biological-Recording-Tools/issues/56>
:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qgis/QGIS/issues/44075#issuecomment-875483788>, or
unsubscribe

**Comment by gideonsway** [comment] 2021-07-07 10:30
Sorry Jürgen but I had put it on FSC bug report as you have said (duplicate), but no one had responded after 2 days so i thought I must have put it in wrong place, hence why I tried again. Martyn
