### ISSUE TITLE
Scale bar size is not saved properly in print composition

### ISSUE THREAD

**Issue by miron-t** [qgis/QGIS#32379] opened 2019-10-24 09:23 UTC
When a scale bar is added to a print composition and the size of the scale bat is changed, for example the height, after reopening the composition, the scalebar height is back to a default value or something.

**Comment by gioman** [comment] 2019-10-24 17:50
@miron-t duplicate of https://github.com/qgis/QGIS/issues/26931 ?

**Comment by HaVRane** [comment] 2020-02-04 12:07
Still a bug in 3.10.1

**Comment by ekauq** [comment] 2020-04-15 16:16
Still in 3.12.1

**Closed** 2020-05-05 05:14 UTC
Labels: Bug, Feedback

**Comment by HaVRane** [comment] 2020-05-05 08:28
Thanks, nyalldawson! Looking forward to next release!

**Comment by fiddlersfan** [comment] 2020-12-04 15:19
Unfortunately still available in version 3.10.12 LTR. Its possible to push this in the LTR branch?
