### ISSUE TITLE
QGIS 3.20.1 fails to start

### ISSUE THREAD

**Issue by ulmi** [qgis/QGIS#44293] opened 2021-07-21 09:37 UTC
**Describe the bug and How to reproduce**

Today after updating to QGIS 3.20.1
`qgis:
  Installed: 1:3.20.1+32focal
  Candidate: 1:3.20.1+32focal
  Version table:
 *** 1:3.20.1+32focal 500
        500 https://qgis.org/ubuntu focal/main amd64 Packages`

I'm unable to start QGIS. When running from the terminal  it shows
`Gtk-Message: 10:21:38.287: Failed to load module "appmenu-gtk-module"`

after installing the missing module

it the shows

`Gtk-Message: 10:20:54.299: Failed to load module "unity-gtk-module"
Gtk-Message: 10:20:54.301: Failed to load module "unity-gtk-module"`

and it seems when installing one the other module is remove

**QGIS and OS versions**

On a linux mint manchine with cinnamon DE
`System:    Kernel: 5.8.0-63-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.0.5 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal `

QGIS 3.20.1

**Comment by ulmi** [comment] 2021-07-21 09:57
strangely QGIS 3.16, gives the same error, but starts 

`Gtk-Message: 10:50:29.839: Failed to load module "appmenu-gtk-module"
no layer`

QGIS version | 3.16.8-Hannover | QGIS code revision | 8c50902ea4
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Linux Mint 20.2

**Comment by dgva** [comment] 2021-07-21 10:44
Also can't run in Kubuntu 20.04. In a laptop, the splashscreen does not show, and the fans ramp up to the max speed.

**Comment by ondrolexa** [comment] 2021-07-21 11:00
Same on Ubuntu 20.04.2 LTS. Process using 100% CPU, no splash screen....

**Comment by ulmi** [comment] 2021-07-21 13:10
> Same on Ubuntu 20.04.2 LTS. Process using 100% CPU, no splash screen...
> 
> **EDIT**
> Once the existing local profile from ~/.local/share/QGIS is removed, QGIS starts and works...

Yep...it works, thanks for pointing in the right direction.

I managed to get it to work, just by removing the _**symbology-style.db**_ on the profile folder.

**Comment by hamiltoncj** [comment] 2021-07-21 13:46
When installed with OSGeo4W installer it also does not run on Windows 10. There is no splashscreen but the process can be seen in the TaskManager.

**Comment by Houska1** [comment] 2021-07-21 13:58
> When installed with OSGeo4W installer it also does not run on Windows 10. There is no splashscreen but the process can be seen in the TaskManager.

No problems here (OSGeo4W v2, installed 3.20.1-1 as update to 3.20.0-5) so whatever the unfortunate problem is, it's not universal.

**Comment by fgianoli** [comment] 2021-07-21 14:31
> When installed with OSGeo4W installer it also does not run on Windows 10. There is no splashscreen but the process can be seen in the TaskManager.

I have the same issue in Windows10. I tried to reinstall the previous version but the issue is not solved.

**Comment by ulmi** [comment] 2021-07-21 14:44
The same issue happens in Windows 10, and it seems it only occurs when the default profile has custom saved symbology. 

Versão do QGIS | 3.20.1-Odense | Revisão do código do QGIS | 1c3c5cd6
-- | -- | -- | --
Qt version | 5.15.2
Versão do Python | 3.9.5
GDAL/OGR version | 3.3.1
PROJ version | 8.1.0
EPSG Registry database version | v10.027 (2021-06-17)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
Versão PDAL | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
Versão QScintilla2 | 2.11.5
OS version | Windows 10 Version 1607

**Comment by hamiltoncj** [comment] 2021-07-21 15:06
> The same issue happens in Windows 10, and it seems it only occurs when the default profile has custom saved symbology.
> 

That seems to be the problem on Windows 10. When I removed symbology-style.db like the Linux folks have done, it solved the problem. 

I should mention that the QGIS 3.16.9 update that was done at the same time does not have this problem.

**Comment by samuelVJrobinson** [comment] 2021-07-21 22:28
> > Same on Ubuntu 20.04.2 LTS. Process using 100% CPU, no splash screen...
> > **EDIT**
> > Once the existing local profile from ~/.local/share/QGIS is removed, QGIS starts and works...
> 
> Yep...it works, thanks for pointing in the right direction.
> 
> I managed to get it to work, just by removing the _**symbology-style.db**_ on the profile folder.

Same problem: I had to remove all *.db files, but then it worked as usual.

**Comment by benhur07b** [comment] 2021-07-22 02:09
> > Same on Ubuntu 20.04.2 LTS. Process using 100% CPU, no splash screen...
> > **EDIT**
> > Once the existing local profile from ~/.local/share/QGIS is removed, QGIS starts and works...
> 
> Yep...it works, thanks for pointing in the right direction.
> 
> I managed to get it to work, just by removing the _**symbology-style.db**_ on the profile folder.

Same issue occurs in Pop! OS 21.04 after updating to QGIS 3.20.1. Resolved by deleting **symbology-style.db** in the profile folder of the current default profile (thank you @ondrolexa). Might be an issue with custom symbologies as @ulmi mentioned.

**Comment by klakar** [comment] 2021-07-22 07:21
You don't need to remove the old symbology-styel.db file...

The only structural difference between the old and "new" symbology-style.db is the lack of a "stylemetadata" table in the "new" database.

If you delete this table from the old database, QGIS 3.20.1 will start and use all the current styles in the database.

I did this using DBeaver (you need to kill any running QGIS processes to unlock the database first).

**Comment by ReghardNell** [comment] 2021-07-22 21:36
@klakar 

Thanks this resolved the issue for me on Windows 10
:)

**Comment by patrickharvey333** [comment] 2021-07-23 05:51
Windows 10 and having the same no start issue. I also can no longer install an older version to run either.

**Comment by patrickharvey333** [comment] 2021-07-23 06:42
completely shutting down seems to have fixed my issue.

**Comment by klakar** [comment] 2021-07-23 07:44
This issue should now be resolved by #44343 and included in the next 3.20.2 release.
If you want to _workaround_ the issue without using a database manager you can use the terminal/command line:

1. Open terminal in the default profile folder
2. Open the database:
`sqlite3 symbology-style.db`
3. Drop the metadata table:
`drop TABLE stylemetadata;`
4. Exit the database:
`.exit`

**Note**! This is not a FIX, it's a workaround. The bug in the code is still there and you probably should be careful with what you do here. At least take a backup of the _symbology-style.db_ file.

**Comment by hamiltoncj** [comment] 2021-07-23 13:31
I think it is a big mistake not to immediately release the fix to this as 3.20.1-2. Don't wait for 3.20.2.

**Comment by vlulla** [comment] 2021-07-23 16:24
It is surprising to me that a mere one row database can stop the whole application! I find it even more surprising that customized styles causes this issue. While I do not remember when I created custom styles, it is quite baffling that this issue will affect users who are knowledgeable enough to create customized styles! Do not regular users of QGIS create customized styles for their own uses?

**Comment by rduivenvoorde** [comment] 2021-07-24 05:00
>     1. Open terminal in the default profile folder

Just a short note: you actually have a symbology-style.db in every profile folder, so I think you have to 'fix' the db in the profile folder(s) you actually use(d) last time you shutdown QGIS.
Also, if you can start QGIS from the command line, you can use `qgis --profile foo` to let QGIS create a fresh profile with a pristine symbology-style.db  and start QGIS in foo profile.

**Comment by nicogodet** [comment] 2021-07-24 05:58
3.20.1-2 is available on osgeo4w and msi.
Jef was building for Ubuntu and debian few hours ago so it should be available now (or very soon)

**Comment by ulmi** [comment] 2021-07-25 10:33
Just upgraded from 3.20 → 3.20.1-2 and everything worked as expected, however i haven't tested from 3.20.1 → 3.20.1-2 with the workaround @klakar mention!

Should the issue be closed since it has been fixed #44343 and the new packages addressing it have been release?

**Comment by klakar** [comment] 2021-07-25 20:20
+1 for closing this issue.
I did upgrade from 3.20.1-1 and the original issue is resolve.
Any remaining issues should probably be treated as a new issue.

**Closed** 2021-07-25 21:29 UTC
Labels: Bug, Build/Install, Regression
