### ISSUE TITLE
Problem during raster to vector conversion

### ISSUE THREAD

**Issue by frchalaoux** [qgis/QGIS#41441] opened 2021-02-09 08:38 UTC
**Describe the bug**

I would like to transform a raster image to an vector image but it seems there is an import problem with _gdal:
ModuleNotFoundError: No module named '_gdal'

**How to Reproduce**

1. Go to Raster/Conversion/Polygoniser
2. Enter asked values.
4. See error -->

Version de QGIS : 3.16.3-Hannover
Révision du code : 3a90ea3afd
Version de Qt : 5.14.2
Version de GDAL : 3.1.2
Version de GEOS : 3.8.1-CAPI-1.13.3
Version de Proj : Rel. 6.3.2, May 1st, 2020
Traitement de l'algorithme…
Démarrage de l'algorithme 'Polygoniser (raster vers vecteur)'…
Input parameters:
{ 'BAND' : 1, 'EIGHT_CONNECTEDNESS' : False, 'EXTRA' : '', 'FIELD' : 'DN', 'INPUT' : '/Users/frchalaoux/Documents/Drone/Production/Clients/Sarda/Vigne basse/17122020/Litchi/Images/Vol2/ortho_NRGDI_10.tif', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdal_polygonize.py "/Users/frchalaoux/Documents/Drone/Production/Clients/Sarda/Vigne basse/17122020/Litchi/Images/Vol2/ortho_NRGDI_10.tif" /private/var/folders/m_/d9wmm9hn7lgg28j_wyx_0c5w0000gn/T/processing_rriPPi/46c6ac6b7fcb4251bd2e8c54b53af3d4/OUTPUT.gpkg -b 1 -f "GPKG" OUTPUT DN
GDAL command output:
Traceback (most recent call last):

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 18, in swig_import_helper

return importlib.import_module(mname)

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

File "<frozen importlib._bootstrap>", line 983, in _find_and_load

File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 670, in _load_unlocked

File "<frozen importlib._bootstrap>", line 583, in module_from_spec

File "<frozen importlib._bootstrap_external>", line 1043, in create_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: dlopen(/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/_gdal.cpython-37m-darwin.so, 2): Symbol not found: _curl_mime_addpart

Referenced from: /Applications/QGIS.app/Contents/MacOS/bin/../lib/libgdal.27.dylib

Expected in: /usr/lib/libcurl.4.dylib

in /Applications/QGIS.app/Contents/MacOS/bin/../lib/libgdal.27.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/Applications/QGIS.app/Contents/MacOS/bin/gdal_polygonize.py", line 4, in <module>

__import__('pkg_resources').run_script('GDAL==3.1.2', 'gdal_polygonize.py')

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script

self.require(requires)[0].run_script(script_name, ns)

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script

exec(code, namespace, namespace)

File "/Applications/QGIS.app/Contents/Resources/python/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/EGG-INFO/scripts/gdal_polygonize.py", line 36, in <module>

from osgeo import gdal

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 32, in <module>

_gdal = swig_import_helper()

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg/osgeo/__init__.py", line 31, in swig_import_helper

return importlib.import_module('_gdal')

File "/Applications/QGIS.app/Contents/MacOS/lib/python3.7/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_gdal'

Execution completed in 0.45 seconds
Results:
{'OUTPUT': '/private/var/folders/m_/d9wmm9hn7lgg28j_wyx_0c5w0000gn/T/processing_rriPPi/46c6ac6b7fcb4251bd2e8c54b53af3d4/OUTPUT.gpkg'}

Chargement des couches de résultat
Les couches suivantes n'ont pas été générées correctement.
• /private/var/folders/m_/d9wmm9hn7lgg28j_wyx_0c5w0000gn/T/processing_rriPPi/46c6ac6b7fcb4251bd2e8c54b53af3d4/OUTPUT.gpkg
Vous pouvez vérifier le Panel de messages du journal dans la fenêtre principale de QGIS pour trouver plus d'informations à propos de l'exécution de l'algorithme.

**QGIS and OS versions**

Version de QGIS | 3.16.3-Hannover | Révision du code | 3a90ea3afd
-- | -- | -- | --
Compilé avec Qt | 5.14.2 | Utilisant Qt | 5.14.2
Compilé avec GDAL/OGR | 3.1.2 | Utilisé avec GDAL/OGR | 3.1.2
Compilé avec GEOS | 3.8.1-CAPI-1.13.3 | Utilisé avec GEOS | 3.8.1-CAPI-1.13.3
Compilé avec SQLite | 3.31.1 | Fonctionne avec SQLite | 3.31.1
Version du client PostgreSQL | 12.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.4
Compilé avec PROJ | 6.3.2 | Fonctionne avec PROJ | Rel. 6.3.2, May 1st, 2020
Version de l'OS | macOS Mojave (10.14)
Extensions Python actives | quick_map_services; processing; db_manager; MetaSearch

**Additional context**

This version is a full version of QGIS with Python and all the plugins inside

**Comment by PeterPetrik** [comment] 2021-02-09 09:06
Hi, this is duplicate of https://github.com/qgis/QGIS-Mac-Packager/issues/111

**Closed by PeterPetrik** 2021-02-09 09:06 UTC
Labels: Bug

**Comment by frchalaoux** [comment] 2021-02-09 09:39
> Hi, this is duplicate of [qgis/QGIS-Mac-Packager#111](https://github.com/qgis/QGIS-Mac-Packager/issues/111) . Thanks for reporting

Don't understand. Is the problem suppressed in the nighty version ?

**Comment by PeterPetrik** [comment] 2021-02-09 09:43
No, the problem is that the system library /usr/lib/libcurl is missing on your computer. It looks like on some macOS versions/settings it is not present. I need to fix the installer to package it. Lets continue the discussion on qgis/QGIS-Mac-Packager#111

**Comment by frchalaoux** [comment] 2021-02-09 09:54
libcurl.4.dylib is not missing in /usr/lib of my macos. Should I try to install a new version of libcurl with homebrew or other in an other PATH ?
