### ISSUE TITLE
[browser] Right-click options do nothing for OWS - browser

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31925] opened 2019-09-21 15:02 UTC
3.4.12
In the browser, if you right click on any layer under "OWS" you see two options: "Delete" and "edit". Neither button does anything

**Comment by gioman** [comment] 2019-09-21 20:31
duplicate of https://github.com/qgis/QGIS/issues/26150

**Closed by gioman** 2019-09-21 20:31 UTC
Labels: Bug
