### ISSUE TITLE
“QGIS3.14” can’t be opened because Apple cannot check it for malicious software."  This software needs to be updated. Contact the developer for more information.

### ISSUE THREAD

**Issue by Shakshak-Bitong** [qgis/QGIS#37943] opened 2020-07-23 10:12 UTC
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by Gustry** [comment] 2020-07-23 10:17
Duplicate of many ticket https://github.com/qgis/QGIS/issues/34018
Solution is included there

**Closed by Gustry** 2020-07-23 10:17 UTC
Labels: Bug
