### ISSUE TITLE
Wrong reprojection shift using Proj >= 5.2.0

### ISSUE THREAD

**Issue by rmarzocchi84** [qgis/QGIS#34424] opened 2020-02-12 09:49 UTC
Problem on 
- QGIS 3.4.15 
- Windows 10
- Proj 5.2.0 

Fail reprojection of XYZ using the EPSG 3857 or of a WMS using the EPSG 25832
 

While using
- QGIS 3.4.15 
- Ubuntu 18.04
- Proj 4.9.3
the same layers (XYZ  using the EPSG 3857 and  WMS using the EPSG 25832) are correctly reprojected

attached the QGIS projects saved on two different O.S.

[qgis_projects.zip](https://github.com/qgis/QGIS/files/4191098/qgis_projects.zip)

**Comment by gioman** [comment] 2020-02-12 09:59
>     * QGIS 3.4.15
> 
>     * Windows 10
> 
>     * Proj 5.2.0
> 
> 
> Fail reprojection of XYZ using the EPSG 3857 or of a WMS using the EPSG 25832

seems to work, here. Anyway is much slower (to show the layers) than on Ubuntu 18 and Proj 493.

![Screenshot_20200212_095812](https://user-images.githubusercontent.com/1951107/74324066-5d044380-4d7e-11ea-83af-f5b2b3dde58f.png)

**Comment by pigreco** [comment] 2020-02-12 10:10
the attached project shows the shift also on QGIS 3.10.2-2 with proj 6.3 and in the master with proj 7.0

![image](https://user-images.githubusercontent.com/7631137/74324991-2c290c00-4d88-11ea-88c6-598a007ba56e.png)

## OSGeo4W64

**Comment by gioman** [comment] 2020-02-12 10:12
@rmarzocchi84 oh sorry, you mean there is a *shift*... I thought it was about reprojection failing completely. Then yes, there is a shift.

**Comment by rmarzocchi84** [comment] 2020-02-12 10:16
WINDOWS
![reproj_win](https://user-images.githubusercontent.com/4061154/74325431-de60d380-4d88-11ea-91fd-8ea797bd3377.png)

LINUX:
![reproj_linux](https://user-images.githubusercontent.com/4061154/74325451-e91b6880-4d88-11ea-8eb0-a9339a909fff.png)


I think the problem is on the .qgs file because we encountered the shift or not also opening the saved project on windows or on linux

**Comment by rmarzocchi84** [comment] 2020-02-12 14:03
On QGIS 3.10 it seems OK (no shift):
- Windows 10
- QGIS 3.10.1
- Proj 6.2.1

![reproj_win_3_10](https://user-images.githubusercontent.com/4061154/74341780-9782d600-4da8-11ea-80b2-ce4d89226cd9.png)

**Comment by RobiFag** [comment] 2020-02-12 15:03
> On QGIS 3.10 it seems OK (no shift):
> 
> * Windows 10
> * QGIS 3.10.1
> * Proj 6.2.1

I have just tested and I get the shift:

- Windows 10
- QGIS 3.10.2
- Proj 6.3

**Comment by gioman** [comment] 2020-02-12 15:04
>  EPSG 25832

@rmarzocchi84 this happens only for this specific CRS? and what about other sources with the same CRS?

**Comment by rmarzocchi84** [comment] 2020-02-12 15:12
It seems to work with WMS using EPSG 4326 or EPSG 3857 not with other datums / projections. perhaps a problem with `+towgs84` parameters?

**Comment by gioman** [comment] 2020-02-12 15:16
@rmarzocchi84 do you see the shift when adding layers in EPSG 25832 from other sources (other WMS/WFS services, or file bases datasources)?

**Comment by rmarzocchi84** [comment] 2020-02-12 15:37
we have tested other WMS of the same source (Liguria Region) and the shift is confirmed while using WMS from a different source (Veneto Region) we do not have the shift

**Comment by gioman** [comment] 2020-02-12 15:39
> different source (Veneto Region)

url?

**Comment by rmarzocchi84** [comment] 2020-02-12 15:50
url Liguria Region: http://geoservizi.regione.liguria.it/geoserver/M1407/wms?version=1.3.0&request=getcapabilities (single layer)

url Veneto Region: https://idt2-geoserver.regione.veneto.it/geoserver/ows (workspace, more layers)

**Comment by gioman** [comment] 2020-02-12 16:17
> url Veneto Region: https://idt2-geoserver.regione.veneto.it/geoserver/ows (workspace, more layers)

I don't see 25832 among the list of CRSs...
https://idt2-geoserver.regione.veneto.it/geoserver/ows?service=wms&version=1.3.0&request=getcapabilities

...

<CRS>EPSG:3003</CRS>
<CRS>EPSG:3004</CRS>
<CRS>EPSG:32632</CRS>
<CRS>EPSG:32633</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:4857</CRS>
<CRS>EPSG:6876</CRS>
<CRS>EPSG:900913</CRS>
<CRS>CRS:84</CRS>
...

**Comment by RobiFag** [comment] 2020-02-12 17:22
Maybe it is a limited list of CRSs..

```
<!-- Limited list of EPSG projections: -->
<CRS>EPSG:3003</CRS>
<CRS>EPSG:3004</CRS>
<CRS>EPSG:32632</CRS>
<CRS>EPSG:32633</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:4857</CRS>
<CRS>EPSG:6876</CRS>
<CRS>EPSG:900913</CRS>
<CRS>CRS:84</CRS>
```
Anyway, I have just tested (QGIS 3.4.14 - PROJ 5.2 ) using epsg:3003 for instance and the WMS overlaps perfectly, no shift.

**Comment by gioman** [comment] 2020-02-12 18:18
@rmarzocchi84 FYI, I downloaded some data from here 

http://geoportale.regione.emilia-romagna.it/it/download/dati-e-prodotti-cartografici-preconfezionati/database-topografico/gestione-viabilita-e-indirizzi/dati-preconfezionati-dbtr-civico-ncv_gpt 

which comes in EPSG 25832 and on 3.10.2 on Windows it is placed exactly where is expected.

**Comment by nyalldawson** [comment] 2020-02-13 02:28
If this is only reproducible on builds based on proj < 6 it should be closed, with the solution being using the newer proj version.

Projection handling on anything pre proj 6.3 is playing with fire...

**Comment by rmarzocchi84** [comment] 2020-02-13 07:48
The problem seems to be related to a specific WMS and to proj 5 because it works correctly with proj version 4 an 6. It is not nice that happens with the actual LTR

**Comment by gioman** [comment] 2020-02-13 08:41
> If this is only reproducible on builds based on proj < 6 it should be closed, with the solution being using the newer proj version.
> 
> Projection handling on anything pre proj 6.3 is playing with fire...

in this specific case it happens also with master/proj7. So I'm not sure if it a QGIS fault after all, also I'm unsure if the problem is the remote service or newer versions of proj.

**Comment by gioman** [comment] 2020-08-01 21:42
On the new LTR, 3.10 (as on 3.14 and master), there is no shift, so I'm closing this.

**Closed by gioman** 2020-08-01 21:42 UTC
Labels: Bug, Feedback, Projections/Transformations
