### ISSUE TITLE
[OAPIF] using snapping with OAPIF layers offering next pages freeze QGIS

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#56554] opened 2024-02-27 11:06 UTC
### What is the bug or the crash?

If OAPIF provider offers next page links like so in items url: 

```json
"links": [

    {
      "href": "https://someurl/items?next=MDoxMjQyNTU4Mg%3D%3D&limit=5",
      "rel": "next",
      "type": "application/geo+json",
      "title": "Next page"
    }
  ],
```
QGIS tries to load every feature when indexing the layer if snapping is enabled regardless of pagings used This might freeze QGIS for hours.

![snapping_oapif](https://github.com/qgis/QGIS/assets/33314057/6844a239-d60a-4d7c-8f00-343a56a526a5)

### Steps to reproduce the issue

1. Register here https://omatili.maanmittauslaitos.fi/user/new/avoimet-rajapintapalvelut?lang=en to get the API key. After registering log in (use email as username) and get the API key.
2. Set map extent to fitting `iface.mapCanvas().setExtent(QgsRectangle(28.0502, 64.6811, 28.0504, 64.6814))`
3. Create draft memory polygon layer and draw some shape there (to prevent map from  zooming to OAPIF layer extent added later)
4. Add following Oapif server connection: "https://avoin-paikkatieto.maanmittauslaitos.fi/maastotiedot/features/v1/". Use created API-key in step 1 as username, leave password empty. 
5. Add layer "kivi" to project
6. Enable snapping via Snapping Toolbar. Make sure it will snap to all layers
7. Start editing for draft memory layer and try to create new feature
8. As soon as the cursor moves over map canvas, QGIS freezes (for hours if not killing the process)

### Versions

The bug occurs with main branch (commit da9afac631f) as well as with 3.34.3
<details>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.37.0-Master | QGIS code revision | da9afac631f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.37.0-Master
QGIS code revision
[da9afac631f](https://github.com/qgis/QGIS/commit/da9afac631f)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

By limiting the max. number of features in provider options, the bug can be evaded but this might be undesired.

**Comment by rouault** [comment] 2024-02-28 21:40
This is a duplicate of https://github.com/qgis/QGIS/issues/51179. Closing as such

**Closed by rouault** 2024-02-28 21:40 UTC
Labels: Bug
