### ISSUE TITLE
DB Manager slow with remote PostGIS / Python error in DB Manager

### ISSUE THREAD

**Issue by beedawg1985** [qgis/QGIS#34963] opened 2020-03-10 10:40 UTC
**Describe the bug**
1) DB Manager v. slow to connect to remote PostGIS DB, and to list schemas and tables, and to add layers to the project
2) DB Manager throws Python error when retrieving layer information. From python error log:
```
2020-03-10T10:27:23     WARNING    Traceback (most recent call last):
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_manager.py", line 100, in itemChanged
              self.refreshTabs()
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_manager.py", line 143, in refreshTabs
              self.info.showInfo(item)
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/info_viewer.py", line 74, in showInfo
              self._showTableInfo(item)
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/info_viewer.py", line 133, in _showTableInfo
              html += table.info().toHtml()
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/info_model.py", line 361, in toHtml
              ret = self.getTableInfo()
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 231, in getTableInfo
              ret = TableInfo.getTableInfo(self)
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/info_model.py", line 303, in getTableInfo
              spatial_info = self.spatialInfo()
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 250, in spatialInfo
              return VectorTableInfo.spatialInfo(self)
              File "/Applications/QGIS3.12.app/Contents/MacOS/../Resources/python/plugins/db_manager/db_plugins/info_model.py", line 400, in spatialInfo
              estimated_extent_str = '%.5f, %.5f - %.5f, %.5f' % self.table.estimatedExtent
             TypeError: must be real number, not list
```
From the PG logfile:
```
2020-03-10 10:27:22.192 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.192 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.192 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.192 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.192 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.192 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.192 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.192 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.643 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.643 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.644 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.644 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.644 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.644 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
2020-03-10 10:27:22.644 UTC [60098] WARNING:  ST_Estimated_Extent signature was$
2020-03-10 10:27:22.644 UTC [60098] CONTEXT:  PL/pgSQL function _postgis_deprec$
        SQL function "st_estimated_extent" during startup
```

**How to Reproduce**
1) Establish remote DB instance
2) Tunnel remote DB port to localhost, as described in[ this post](https://tripgis.wordpress.com/2015/02/19/creating-a-remote-postgis-backend-to-use-with-qgis/)
3) Load DB Manager and connect to DB

**QGIS and OS versions**
QGIS 3.12.0
Client: Mac OSX Catalina 10.15.3
Server: Microsoft Azure VM, running postgres (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

**Comment by Gustry** [comment] 2020-03-10 10:47
Duplicate of https://github.com/qgis/QGIS/issues/34467 and fix https://github.com/qgis/QGIS/pull/34795

**Comment by beedawg1985** [comment] 2020-03-10 11:31
Is the slow running of DB Manager / PostGIS layer rendering also related?

**Comment by gioman** [comment] 2020-03-10 22:02
> Is the slow running of DB Manager / PostGIS layer rendering also related?

@beedawg1985 please file a separate ticket, but please be specific about this issue because at a first try I cannot replicate (tested a remote server with hundreds of tables and views).

**Closed** 2020-03-10 22:01 UTC
Labels: Bug
