### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by tophatjuggler** [qgis/QGIS#34880] opened 2020-03-04 22:43 UTC
## User Feedback

trying to load vector file from data source manager screen. program quits shortly after selecting souce file browse button.

## Report Details

**Crash ID**: [5116e676c2c945e349bdd11b64ef682d506dda0a]('https://github.com/qgis/QGIS/search?q=5116e676c2c945e349bdd11b64ef682d506dda0a&type=Issues')

**Stack Trace**
<pre>
RtlFreeHeap :
HeapFree :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:1000
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CApartmentActivator::CreateInstance actvator.cxx:2251
CProcessActivator::CCICallback actvator.cxx:1716
CProcessActivator::AttemptActivation actvator.cxx:1630
CProcessActivator::ActivateByContext actvator.cxx:1488
CProcessActivator::CreateInstance actvator.cxx:1389
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
CClientContextActivator::CreateInstance actvator.cxx:685
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1918
ICoCreateInstanceEx objact.cxx:1397
CComActivator::DoCreateInstance immact.hxx:343
CoCreateInstanceEx actapi.cxx:175
CoCreateInstance actapi.cxx:120
_SHCoCreateInstance :
SHExtCoCreateInstance :
DCA_SHExtCoCreateInstance :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::CreateInstance :
IconOverlayManagerInit :
GetIconOverlayManager :
FileIconInit :
SHGetImageList :
CBreadcrumbBar::InitBreadcrumbBar :
CAddressBand::_EnsureBreadcrumbBar :
CAddressBand::_CreateAddressBand :
CAddressBand::SetSite :
IUnknown_SetSite :
CBandSite::_AddBandByID :
CBandSite::AddBand :
CNavBar::_CreateBands :
CNavBar::_CreateBar :
CNavBar::ShowDW :
CFileOpenSave::_CreateNavigationBar :
CFileOpenSave::_InitOpenSaveDialog :
CFileOpenSave::s_OpenSaveDlgProc :
UserCallDlgProcCheckWow :
DefDlgProcWorker :
DefDlgProcW :
UserCallWinProcCheckWow :
InternalCreateDialog :
InternalDialogBox :
DialogBoxIndirectParamAorW :
DialogBoxIndirectParamW :
CFileOpenSave::Show :
QDialog::exec :
QFileDialog::getOpenFileUrls :
QFileDialog::getOpenFileNames :
QgsFileWidget::openFileDialog qgsfilewidget.cpp:267
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1609
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by gioman** [comment] 2020-03-05 16:22
@tophatjuggler please try with a clean QGIS profile, no 3rd party plugins installed.

**Comment by DeerCreekFan** [comment] 2020-04-01 17:30
@gioman , could you inform me on how to see if a plugin is QGIS or not? I am new to it, thought I installed the basic program, but am getting a very similar issue. Does the Stack Trace indicate what plugin is causing the problem? Any direction would be accepted gratefully.

Thanks for your time 

Crash ID: e6a35940e0c612a00f44523d6a4d395ae7d77c4a


Stack Trace


RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2211
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :




QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment] 2020-04-01 17:31
> could you inform me on how to see if a plugin is QGIS or not?

@DeerCreekFan simple: within QGIS create a new profile and use it without installing any 3rd party plugin. See if it still crashes.

**Comment by roya0045** [comment] 2020-04-01 19:15
To be clear: Settings->User Profiles -> New Profile

**Comment by DeerCreekFan** [comment] 2020-04-01 20:21
@gioman , Thanks for the suggestion. I made a new profile, checked what pluggins are installed (DB Manager, MetaSearch Catalog Client, and Processing all of which indicate they are a core plugin). I had the same thing happen. I hope that is what you suggested I do.

Steps to cause crash:
opened Data Source Manager,
Selected Add Vector file symbol
Left source type as File, Encoding as Auto 
Tried to browse for file, but the program either freezes or crashes. 


 The new Stack Trace is pasted below.

Cheers!

Crash ID: 5f5a9b1aceb4039bbc1963630fe1b6aad76f6ad8


Stack Trace


RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2211
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CKnownFoldersFolder::_GetOverlayIndex :
CRegFolder::GetOverlayIndex :
CIconOverlayTask::DispatchTasks :
CIconOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.12.0-Bucure?ti
QGIS code revision: cd141490ec
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment] 2020-04-01 20:50
duplicate of #34891 #34880 and #32239 , similar to https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/explorerexe-keeps-crashing-on-a-windows-server/08bec9c0-4eb9-4b9b-a376-f20a758acd54

**Comment by markdx** [comment] 2020-04-12 05:28
QGIS (and the Linux OS (Fedora31)) crash hard every time no matter what type of file (vector, raster, etc.) I try to add through the Data Source Manager browse button. The workaround that I found is to add layers through left pane browser. But does anyone have any ideas why this is happening and any thoughts on how to fix it?

**Comment by roya0045** [comment] 2020-04-26 22:06
@markdx can you test the build proposed here https://github.com/qgis/QGIS/issues/34891#issuecomment-607863934
@gioman would you be so kind as to close these duplicates and let 34891 open to validate if the proposed fix solves this issue? Thanks

**Comment by gioman** [comment] 2020-04-27 10:00
Closing as duplicate of https://github.com/qgis/QGIS/issues/34891

**Closed by gioman** 2020-04-27 10:00 UTC
Labels: Bug, Feedback

**Comment by MLACORTT** [comment] 2021-06-09 15:00
I hate this fucking program, my bofera cant support them and his is so wrong my man, Qgis if your progams wiil read this my honestly fuck you!!!!
