### ISSUE TITLE
QGIS crashes when using 3D view for point cloud data

### ISSUE THREAD

**Issue by ntw-au** [qgis/QGIS#54415] opened 2023-08-30 05:05 UTC
### What is the bug or the crash?

QGIS crashes frequently but intermittently when using the 3D viewer for point cloud data. Input point clouds are in LAS 1.4 format 6 of a range of sizes, from very small to 40MB+.

The crash often happens the first time a point cloud is loaded into QGIS, straight after COPC conversion.

**Python Stack Trace Example 1**
```
Windows fatal exception: access violation

Thread 0x00008014 (most recent call first):
<no Python frame>
```

**Stack Trace Example 1**

```

Qt3DCore::QChangeArbiter::sceneChangeEvent :
Qt3DRender::Render::Geometry::notifyExtentChanged :
Qt3DRender::Render::CalculateBoundingVolumeJob::run :
Qt3DCore::QThreadPooler::waitForAllJobs :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**Python Stack Trace Example 2**
```
Windows fatal exception: access violation

Current thread 0x00009d7c (most recent call first):
```

**Stack Trace Example 2**

```

Qt3DCore::QChangeArbiter::distributeQueueChanges :
Qt3DCore::QChangeArbiter::syncChanges :
Qt3DCore::QAspectManager::processFrame :
Qt3DCore::QAspectManager::exitSimulationLoop :
QObject::qt_static_metacall :
QUnifiedTimer::setSlowdownFactor :
QAbstractAnimation::setCurrentTime :
QUnifiedTimer::updateAnimationTimers :
QUnifiedTimer::updateAnimationTimers :
QAnimationDriver::advance :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

I have also captured a stack trace like Example 2, but with an additional `Qt3DCore::QSystemInformationService::tr :` at the top of the stack.

### Steps to reproduce the issue

* Start QGIS
* Drag a previously unviewed LAZ point cloud into project and wait for COPC conversion
* View > new 3D map view (opens 3D Map 1 in child window)
* Resize 3D window so it's larger
* Zoom Full
* Zoom, rotate, pan around 3D scene using the mouse

The length of steps may vary; sometimes the crash happens straight after opening the 3D map view.

### Versions

**QGIS Info**
QGIS Version: 3.32.2-Lima
QGIS code revision: c0b8833964
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

Installed via OSGeo4W.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ntw-au** [comment] 2023-08-30 05:55
This is likely to be the same underlying issue as #54331

**Comment by wonder-sk** [comment] 2023-10-15 20:56
Duplicate of #53941

**Closed by wonder-sk** 2023-10-15 20:56 UTC
Labels: 3D, Bug, Crash/Data Corruption, Point Clouds
