### ISSUE TITLE
Rule Based Geometry Generator: Layer pallet in map view and Legend in Print Layout incorrect

### ISSUE THREAD

**Issue by sco0012** [qgis/QGIS#30762] opened 2019-07-17 07:39 UTC
When using displaying Items generated using the geometry generator in rule based symbology, The items take up a very large area within the layer pallet, making it very difficult to see (see attached screen clip). Additionally the items do not display correctly in the print layout legend either (See attached screen clip - TPZ and Encroachment should be represented by Burgundy and Green rectangles the same size as Building
![Screen Shot 2019-07-17 at 5 33 26 pm](https://user-images.githubusercontent.com/52994394/61356336-73662180-a8b9-11e9-9c91-540086d61876.png)
![Screen Shot 2019-07-17 at 5 34 13 pm](https://user-images.githubusercontent.com/52994394/61356338-752fe500-a8b9-11e9-8d98-7d5e2c61962c.png)

)

Previously described for QGIS 2.18 here https://issues.qgis.org/issues/15860.

I am using QGIS 3.8 MacOS Mojave

**Comment by roya0045** [comment] 2021-04-08 21:55
What is the symbology? Curious to know if this is solved my the new feature to limite the size of features.

**Comment by gioman** [comment] 2021-06-14 21:27
Duplicate of https://github.com/qgis/QGIS/issues/33755

**Closed by gioman** 2021-06-14 21:27 UTC
Labels: Bug, Feedback, Map and Legend
