### ISSUE TITLE
can't commit changes to geopackage after merging rectangles

### ISSUE THREAD

**Issue by huber-j** [qgis/QGIS#36242] opened 2020-05-06 16:22 UTC
Setting: MultiPolygon Geopackage Layer, no z- or m-values, projected coordinate system (EPSG:31468)
1. Add at least two rectangles using one of the two "add rectangle by 3 points" tools in the "shape digitizing" toolbar.
2. Combine the two rectangles using the "merge selected features" tool.
3. Click on "Save Layer Edits" to commit changes
-> Error "Could not commit changes to layer testdb"
"Errors: ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer"

It works when
- A shapefile is edited instead of a geopackage
- Two Polygons are drawn with another tool an then merged and saved to a geopackage layer
- Polygons are created with the "by 3 points" tools but not merged

So the problem seems to occur only when merging polygons created with the "by 3 points" tools and the layer is a geopackage layer (not tested with spatialite ot postgis).

QGIS Version: 3.12.2-București on Windows 10 Prof. x64 (OSGeo4W)

**Comment by huber-j** [comment] 2020-05-07 06:29
When comparing the WKT geometries, the only difference I found was that using the "by 3 points" tools, a polygon with z values (MultiPolygonZ) is created even though the geopackage layer is only 2D (see issue #35671). Seemingly this does not cause problems with geopackage when saving a single part polygon (as it does with PostGIS, #35671) but only when a multipart MultiPolygonZ is saved to a 2D layer. So fixing issue #35671 should fix this issue as well.

**Comment by gioman** [comment] 2020-05-07 08:21
@huber-j duplicate of https://github.com/qgis/QGIS/issues/35671

**Closed by gioman** 2020-05-07 08:21 UTC
Labels: Bug
