### ISSUE TITLE
Copy/Paste Column Mapping Dialog

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33696] opened 2020-01-09 20:26 UTC
**Feature description.**
I would love to see an optional ManifoldGIS-esque column mapping for Copy/Paste of data to QGIS.

In Manifold, like QGIS, attributes from columns with names in common with columns in the target dataset will be pasted automatically, Unlike in QGIS, in Manifold, when there are non-intrinsic columns with attributes that are not common across datasets, a dialog will pop up asking you to manually map columns from left to right.

This may seem clunky at first, but it can be incredibly helpful and can save one from multiple Refactor Fields operations, especially when the goal is just to migrate data from one dataset to another.

**Additional context**
http://www.manifold.net/doc/mfd9/copy_and_paste_between_drawings.htm

Example image showing Manifold column map dialog:  
![image](https://user-images.githubusercontent.com/19295950/72102145-48064180-32f4-11ea-830c-f219bcd1f5c8.png)

**Comment by saberraz** [comment] 2020-01-09 20:36
Duplicate of https://github.com/qgis/QGIS/issues/24538?

**Comment by Saijin-Naib** [comment] 2020-01-09 20:41
Yep! I searched before I opened this ticket, but apparently missed yours.

**Closed** 2020-01-09 20:46 UTC
Labels: Feature Request
