### ISSUE TITLE
Add query reconnect to DBManager 

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#31994] opened 2019-09-25 04:02 UTC
**Feature description.**
At the moment if a query tab window is open and the connection to a PG database is dropped and you try to execute a query you get the following error: `connection already closed` The workaround at the moment is you need to close the query window and open a new one and restore the SQL text. It would be better to reconnect the database connection with the query tab window, much like you can do with the database node browser. 

**Additional context**
See the current error. 
<img width="418" alt="Screen Shot 2019-09-25 at 2 01 24 PM" src="https://user-images.githubusercontent.com/580022/65568417-04820480-df9d-11e9-8bfe-822d16d0d672.png">

**Comment by strk** [comment] 2019-11-27 10:23
Interesting enough, a "reconnect" menu item exists if you right-click on the database name, but that connection seems to be different from the one used in the SQL window

**Comment by strk** [comment] 2019-11-27 13:02
@elpaso I'm not sure if this is related to recent changes in the connection API but when you reconnect from the DBManager right-click menu, you end up with the DlgSqlWindow window pointing to a deleted object:

> wrapped C/C++ object of type PGDatabase has been deleted

**Comment by elpaso** [comment] 2019-11-27 15:38
@strk I don't think it's related. 
The old API seems to be used for that kind of connection. You can quickly try with 3.4 if it has the same behavior.

**Comment by strk** [comment] 2019-11-28 07:52
Does indeed happen with 3.4 as well:
> RuntimeError: wrapped C/C++ object of type QAction has been deleted

Way to reproduce:

   1. Open an Sql Query Window from DBManager (F2)
   2. Restart PostgreSQL
   3. Execute a query (twice?)

**Comment by strk** [comment] 2020-03-10 15:42
With #33225 merged we can close this.

**Closed by strk** 2020-03-10 15:42 UTC
Labels: Feature Request
