### ISSUE TITLE
Precise digitization with Measurement tool.

### ISSUE THREAD

**Issue by Catalin75** [qgis/QGIS#53233] opened 2023-05-25 16:28 UTC
### Feature description

Good afternoon ! I think it would be of great help, in order to perform precise digitising, to be added in the window of Measurement Tool a button named "Copy as vector". What I wish QGIS to do is, after finalising a measurement, to allow me to copy the line or the convex poligon created with the Measurement tool and to paste them in a vector layer (line layer/polygon layer).

Following the same idea, the solution to my suggestion would be to be added in the status bar of QGIS, a coordinate like window for area, when digitising/editing convex polygon happens,  (similar to what QFIELD measurement tool does), and a button for length, in the same conditions. 
Please excuse my english.
Best regards,
Catalin

**Comment by Catalin75** [comment] 2023-10-25 16:45
It is great that, with the Lima version, it is possible to copy the coordinates of a line created with the Measurement Tool. It would be really useful that the same option will be, in future versions, available for area (polygons). I wish you all the best.

**Comment by YoannQDQ** [comment] 2024-12-18 08:46
Duplicate of #53329

**Closed** 2024-12-18 08:52 UTC
Labels: Map Tools, Feature Request, Digitizing
