### ISSUE TITLE
Cannot edit PostGIS views anymore

### ISSUE THREAD

**Issue by sylviaobk** [qgis/QGIS#30388] opened 2019-06-25 12:23 UTC
mp4 file: [preparation.zip](https://github.com/qgis/QGIS/files/3325090/preparation.zip)
mp4 file: [show_bug.zip](https://github.com/qgis/QGIS/files/3325091/show_bug.zip)
SQL file: [save_from_view_sql.txt](https://github.com/qgis/QGIS/files/3325171/save_from_view_sql.txt)

PostGIS 2.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Postgres PostgreSQL 9.5.4, compiled by Visual C++ build 1800, 64-bit
QGIS 3.4.9 Madeira

On PostGIS database I created two tables and a view, functions and rules.

I can insert, update and delete this view with SQL. (preparation.zip)
I can insert, update and delete this view with QGIS 2.8.2 Wien. (show_bug.zip)
**I can not insert, update and delete this view with QGIS 3.4.9 Madeira. (show_bug.zip) This is the bug.**

Here are the SQL commands for the tables and the view:
```sql
CREATE TABLE myschema.mytable_geometry
(
  gid serial NOT NULL,
  object integer,
  the_geom geometry(Point,25832),
  CONSTRAINT mytable_geometry_pkey PRIMARY KEY (gid)
)
WITH (
  OIDS=TRUE
);

CREATE TABLE myschema.mytable_attributes
(
  id serial NOT NULL,
  object integer,
  color character varying(50),
  CONSTRAINT mytable_attributes_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=TRUE
);

CREATE OR REPLACE VIEW myschema.qry_mytable AS 
	SELECT mytable_geometry.gid,
			mytable_attributes.id,
			mytable_geometry.object,
			mytable_attributes.color,
			mytable_geometry.the_geom
	FROM myschema.mytable_geometry,
			myschema.mytable_attributes
	WHERE mytable_geometry.object = mytable_attributes.object
	ORDER BY  mytable_geometry.gid;
```

Here are the SQL commands for the functions:

```sql
CREATE OR REPLACE FUNCTION myschema.func_del_mytable(
    integer,
    integer)
  RETURNS void AS
$BODY$

	DELETE FROM myschema.mytable_geometry
	WHERE gid = $1;
	
	DELETE FROM myschema.mytable_attributes
	WHERE id = $2;
	
$BODY$
  LANGUAGE sql VOLATILE
  COST 100;

CREATE OR REPLACE FUNCTION myschema.func_ins_mytable(
    integer,
    character varying,
    geometry)
  RETURNS void AS
$BODY$
	INSERT INTO myschema.mytable_geometry 
	(object,
	the_geom
	)
	VALUES($1,
	$3
	);

	INSERT INTO myschema.mytable_attributes
	(object, color)
	VALUES($1,$2);

$BODY$
  LANGUAGE sql VOLATILE
  COST 100;

CREATE OR REPLACE FUNCTION myschema.func_upd_mytable(
    integer,
    integer,
    integer,
    character varying,
    geometry)
  RETURNS void AS
$BODY$

	UPDATE myschema.mytable_geometry 
	SET	object	 	= $3,
		the_geom		= $5
	WHERE gid = $1;

	UPDATE myschema.mytable_attributes
	SET	object 		= $3,
		color			= $4
	WHERE id = $2;

$BODY$
  LANGUAGE sql VOLATILE
  COST 100;
```

Here are the SQL commands for the rules:

```sql
CREATE OR REPLACE RULE ondelete_qry_mytable AS
    ON DELETE TO myschema.qry_mytable DO INSTEAD  SELECT myschema.func_del_mytable(old.gid, old.id) AS func_del_mytable;


CREATE OR REPLACE RULE oninsert_qry_mytable AS
    ON INSERT TO myschema.qry_mytable DO INSTEAD 
    (INSERT INTO myschema.mytable_geometry (object, the_geom)
     VALUES (new.object, new.the_geom);
  
     INSERT INTO myschema.mytable_attributes (object, color)
     VALUES (new.object, new.color);
     );

CREATE OR REPLACE RULE onupdate_qry_mytable AS
    ON UPDATE TO myschema.qry_mytable DO INSTEAD  SELECT myschema.func_upd_mytable(old.gid, old.id, new.object, new.color, new.the_geom) AS func_upd_mytable;
```

Here are the SQL commands to edit the view directly on PostGIS database:

```sql
INSERT INTO myschema.qry_mytable (object, color, the_geom)
VALUES (9, 'grey', ST_GeometryFromText('POINT(389000 5641000)', 25832));

UPDATE myschema.qry_mytable
SET object = 10,
	color = 'red',
	the_geom = ST_GeometryFromText('POINT(389001 5641001)', 25832)
WHERE gid = 1;

DELETE FROM myschema.qry_mytable
WHERE gid = 1;
```

**The functionality of editing a view in QGIS is lost.
The QGIS form qry_mytable is without active "OK" button. This is the bug.**

On show_bug.mp4 video you can see this functionality is working using QGIS 2.8 Wien.

**Comment by jef-n** [comment] 2019-06-30 21:53
Duplicate of #23997

The INSERT rule is missing a RETURNING clause like

```sql
CREATE OR REPLACE RULE oninsert_qry_mytable AS
    ON INSERT TO qry_mytable DO INSTEAD (
        INSERT INTO mytable_attributes(object, color) VALUES (NEW.object, NEW.color);
        INSERT INTO mytable_geometry(object, the_geom) VALUES (NEW.object, NEW.the_geom)
        RETURNING
                gid,
                lastval()::integer,
                object,
                NULL::varchar(50),
                the_geom;
    );
```

**Closed by jef-n** 2019-06-30 21:53 UTC
Labels: Bug, Regression
