### ISSUE TITLE
No “QGIS Desktop X.X.X with GRASS X.X.X” when installing QGIS with the OSGeo4W Installer on a Windows 10 machine

### ISSUE THREAD

**Issue by miron-t** [qgis/QGIS#33350] opened 2019-12-12 09:40 UTC
When I try installing QGIS version 3.10.14 or 3.4.14 on a Windows 10 machine with the OSGeo4W Installer, there is no qgis-grass7.bat or qgis-ltr-bin-g7.exe. Hence, I cannot use GRASS processes in QGIS.
I tried everything, clean Install and all. Any Ideas or suggestions? Can someone reproduce? I started a similar bug report here #32930

![grafik](https://user-images.githubusercontent.com/38276891/70700584-47fe2c00-1ccb-11ea-98cc-fffb19f742f9.png)

**Comment by alexbruy** [comment] 2019-12-12 09:54
Please don't create duplicate tickets, better to add new information to the old one.
Looks like duplicate of #32930.

**Closed by alexbruy** 2019-12-12 09:54 UTC
Labels: Bug

**Comment by miron-t** [comment] 2019-12-12 10:28
Well, I found out that this error also occurs when I try to install any single version of QGIS using the OSGeo4W Installer. That is why I open a new bug report, cause the error is not limited to the installation of parallel versions.

**Comment by miron-t** [comment] 2019-12-12 10:38
I will edit the oroginal report...
