### ISSUE TITLE
I have the same issue than #28788, but dependencies are installed

### ISSUE THREAD

**Issue by Soufleuse** [qgis/QGIS#54191] opened 2023-08-11 13:42 UTC
### What is the bug or the crash?

Hi,

I try to compile QGIS on Ubuntu 22.04. When I use make command, the file QtXml/QtXmlmod.sip is not found, but I have pyqt5-dev and pyqt5.qsci-dev installed. Also, the file is present at /usr/lib/python3/dist-packages/PyQt5/bindings/QtXml/QtXmlmod.sip on my drive; is there something I've missed?

Steve "Soufleuse" Lemieux

### Steps to reproduce the issue

Do a cmake and make on QGIS.

### Versions

On the source of QGIS 3.32.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment] 2023-08-11 14:56
Looks like a duplicate of https://github.com/qgis/QGIS/issues/54184 ?

**Comment by Soufleuse** [comment] 2023-08-12 22:37
> Looks like a duplicate of #54184 ?

With what I saw from the issue you mentionned, I would say yes. Should I close my issue or wait the other issue to be closed?

**Comment by nicogodet** [comment] 2023-08-14 07:35
We can close this one and you can add a comment on the other one if you want.

**Closed by nicogodet** 2023-08-14 07:35 UTC
Labels: Feedback, Bug
