### ISSUE TITLE
Can't see postgis tables when switching between postgis rw and read-only auth conf.

### ISSUE THREAD

**Issue by jamierob** [qgis/QGIS#32843] opened 2019-11-14 00:03 UTC
**Bug Description**
Wnen swapping between read/write and readonly postgis authentication configurations, the readonly user cannot see the tables in the dialogue in order to add them to the map. 

**How to Reproduce**

1. create a qgis auth conf with the postgis user (full access)
2. connect to a database > see all of the tables > add a table to the map
3. create a qgis auth conf with the readonly postgis user with access to same database
4. connect to same database>connection is valid>can't see tables in the db manager
5. Open up qgis 2.x > create readonly user auth conf > connect to same database> see tables that were not visible in qgis 3.10 db manager.

qgis 3.10 auth config read/write:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/775783/68814661-9cfc4300-0636-11ea-9c4d-3c341d54b677.png">

can see tables:
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/775783/68814688-a9809b80-0636-11ea-8fa1-2e9dd631077f.png">

qgis 3.10 auth config read-only
<img width="466" alt="image" src="https://user-images.githubusercontent.com/775783/68814719-c4531000-0636-11ea-9e44-f2ad53e8ee2d.png">

CAN'T see tables:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/775783/68814736-d16fff00-0636-11ea-839b-6e2b3b3de8a0.png">

qgis 2.18 auth config read-only:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/775783/68814546-5ad30180-0636-11ea-8944-0703cc83b889.png">

can see tables:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/775783/68814601-7b9b5700-0636-11ea-9cd1-dc81b8c9aa0e.png">

**QGIS and OS versions**
QGIS 3.10.0-A / MacOS Mojave

**Comment by gioman** [comment] 2019-11-14 09:08
@jamierob duplicate of https://github.com/qgis/QGIS/issues/32726 ? Can you test on QGIS LTR (3.4)?

**Comment by strk** [comment] 2019-11-14 13:36
@jamierob also can you test #32822 ?

**Comment by strk** [comment] 2019-11-14 14:14
I suspect this problem has to do with named connections NOT storing auth info in the cache key \cc @elpaso  @jef-n

**Comment by jamierob** [comment] 2019-11-14 16:23
@gioman , I think you are right. I'm not getting this behavior on 3.4 LTS. Possibly a simpler way to observe this behavior is not by switching between RW and RO auth configs, but simply changing the database in the connection itself while leaving the RO auth config the same. 

on 3.10:

1. create a RO user with access to two databases on the postgis server
2. create a qgis auth conf with the RO user
3. create a new db connection to one of the databases>connect>see tables
4. Leave everything in the connection the same, but change the database
5. Connection is valid>can't see tables

on 3.4 LTS:
1-4: same
5. connection is valid>CAN see tables

**Comment by jamierob** [comment] 2019-11-14 16:39
@strk , I'm not sure how to test [#32822 ](https://github.com/qgis/QGIS/pull/32822). But I don't think this table display issue is related to access to the topology.topology table since the creds work ok on 2.18 and 3.4? I would be happy to test it with some guidance, however.

**Comment by strk** [comment] 2019-11-14 18:42
@jamierob does removing topology support fix your issue ?

**Comment by gioman** [comment] 2019-11-15 09:06
> . But I don't think this table display issue is related to access to the topology.topology table

@jamierob oddly enough it is.

**Comment by jamierob** [comment] 2019-11-15 15:19
@strk , I'm unsure how to run that unit test, but when I revoke access to the topology schema for the readonly role, I am still seeing the 'blank' table display for the readonly user on 3.10.

`REVOKE ALL PRIVILEGES ON SCHEMA topology FROM acreadonly;`

**Comment by strk** [comment] 2019-11-18 09:04
@jamierob yes that's the symptom of the bug fixed by https://github.com/qgis/QGIS/pull/32822 so next nightly build from 3.10 branch should fix that (NOTE that privileges are only checked at connection time)

**Comment by gioman** [comment] 2020-01-08 17:36
Assuming this is fixed. Please reopen if necessary.

**Closed by gioman** 2020-01-08 17:36 UTC
Labels: Bug, Feedback
