### ISSUE TITLE
Actions on layers with Action Scopes Feature and Field add widgets incorrectly

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#57398] opened 2024-05-11 19:11 UTC
### What is the bug or the crash?

I created an action on a layer and selected Action Scopes: Feature and Field; when I open the attribute table and activate Action Widget with the Organize Columns icon and sort the first attribute by clicking on the header, the widget appears in the attribute cells.

https://github.com/qgis/QGIS/assets/7631137/0a795577-4632-4c04-85f1-8ef029456a9c

### Steps to reproduce the issue

1. start QGIS;
2. load any layer;
3. create an action (for example search for a name via Google);
4. open the attributes table and activate the actions widget;
5. sort the first column by clicking on the header;
6. The action widgets will also appear in the first column.

## OSGeo4W win 11 pro

QGIS version3.34.6-Prizren
QGIS code revision 623828f5
Qt version 5.15.13
Python version 3.12.3
GDAL/OGR version 3.8.5
PROJ version 9.4.0
EPSG Registry database version v11.004 (2024-02-24)
GEOS version 3.12.1-CAPI-1.18.1
SQLite version 3.45.1
PDAL version 2.6.3
PostgreSQL client version 16.2
SpatiaLite version 5.1.0
QWT version 6.2.0
QScintilla2 version 2.14.1
OS version Windows 11 Version 2009

Active Python plugins
hsa 0.1
db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.6
processing 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## data for testing

[Reg01012024_g.zip](https://github.com/qgis/QGIS/files/15284066/Reg01012024_g.zip)

**Comment by DelazJ** [comment] 2024-05-15 04:25
Duplicate of https://github.com/qgis/QGIS/issues/33464?

**Closed** 2024-05-22 03:41 UTC
Labels: Feedback, Attribute Table, Bug, Widgets
