### ISSUE TITLE
temporal controller @map_start_time minus a time value from field returns strange result

### ISSUE THREAD

**Issue by rkalasek** [qgis/QGIS#39393] opened 2020-10-15 13:09 UTC
based on nyall dawson's video about time handling and map animation i've done some experiments - concerning this presumed bug things  get interesting at min 47 of the video [https://www.youtube.com/watch?v=vgDg5cRwPRw&feature=youtu.be&t=2820]() where the following expression is used to modify the size of points: `hour(@map_start_time - time)`
where time is a field-value of "Date & Time" type.

my testing starts at that point of the video (find my testdata at the end of this report with labeled points)

image_01 (below) shows the temporal controller settings and the resulting map output:
- my data: a GPS track from a yacht race in the Adriatics. the interval of the data acquisition is +- 5 min
- point symbols (yellow) in the foreground are controlled by QGIS' temporal controller, and "scaled" by the expression  `hour(@map_start_time - "time_s_osec")`
- points (grey): in the background are non-temporal and displayed just for giving an overview 
- temporal controller settings are:
step width: 15min (= 0,25 hours)
the displayed interval starts at `2018-10-15 15:45:00`
and ends at `2018-10-15 16:00:00` (see the values next to the "Frame:" entry of the GUI)

point size is depending on a temporal expression: `hour(@map_start_time - time_s_oesec")` (see the expression in image_02/below) where
- `@map_start_time` is the QGIS-internal variable - which should be equal to the Frame start value, i.e. `'2018-10-15 15:45:00'` in my example
- `time_s_oesec` is a reference to the "Date & Time" field in my data 
i.e. the location of the gps-tracking timestamp data

image_01 shows my test-labels
in my example i will refer to the point with timestamp "`time_s_osec:        15.10.18 16:00:00`" / lower right point of the screenshot image_01

- 1st line:  time stamp of each point  -> lable:  "`time_s_osec:        15.10.18 16:00:00`"
- 2nd line:   value of the variable @map_start_time -> lable:  "`@map_start_time:   15.10.18 15:45:00`"
- 3rd line:  result of the expression "`@map_start_time - time_s_osec`" -> lable: "`@map_start_t* - time_s*:    1,75`"
- 4th line is my check-value: this value is the output from: `hour(to_datetime('2018-10-15T15:00:00') - "time_s_osec" )` where `'2018-10-15T15:45:00'` is a string-value which is transformed to hours via `hour(to_datetime())` and thus should exactly be equal to the value of the variable `@map_start_time`        -->    lable: `'2018-10-15T15:45:00' - time_s_oesec:      -0.25`

summary:
- the resulting value in line 3 of the lables for the expression  "`@map_start_time - time_s_osec`" is 1,75 
- **according to line 4 it should be  -0,25** 
- the dimension of the value 1.75 might be related to bugreport #38647 
- the fact, that the value should be negative (since any timestamp within the interval [@map_start_time, @map_end_time] is greater or equal @map_start_time **is topic of my bug report**

**image_01**
![Bildschirmfoto 2020-10-15 um 14 25 43](https://user-images.githubusercontent.com/37180158/96128336-7fde8d00-0ef5-11eb-8355-229039ff49b4.png)

**image_02**
![Bildschirmfoto 2020-10-15 um 14 26 46](https://user-images.githubusercontent.com/37180158/96123380-05ad0900-0ef3-11eb-8bea-e8207a424fbd.png)

**demo_data**
[gps_track_demo.zip](https://github.com/qgis/QGIS/files/5384868/gps_track_demo.zip)

**QGIS and OS versions**
win: 3.14.16
mac: 3.14.16

**Comment by rduivenvoorde** [comment] 2020-10-15 15:32
@rkalasek I have been playing with this also, and indeed my conclusion was that this indeed has to do with the TimeZone-NON-awareness of DateTimes in QGIS. See  the mail thread mentioned in the issue above too: https://lists.osgeo.org/pipermail/qgis-developer/2020-September/062175.html
QGIS itself is not TimeZone aware.

As in the issue I got stuff working to 'cast' everything to Zulu-time/UTC, for example in one of my datasets I use:

```
coalesce(scale_exp(second(@map_start_time - to_datetime(to_string("timestamp")+'Z') ), 0, 10, 1, 8, 0.57), 0)
```
Note that in the thread above @nyalldawson is telling that making QGIS TimeZone aware is not trivial (he is guessing at least 5 days of work). I'm happy to sponsor at least one day of it, if others chime in....

**Comment by rkalasek** [comment] 2020-10-16 06:48
@rduivenvoorde - well i am far away from being inside of that kind of developer-topics. but there is still an open question to me: if i do take a time stamp like the one you have mentioned "2020-07-25 20:21:38 UTC" and use it in QGIS-expressions  why does qgis "know" how to interpret the data being UTC-time if QIGS is non-timezone aware at all. and if it is not, why does it "know" that your time has to be changed somehow - where does the information about CET come from. 

the thing is - my time stamps do not provide any information about timezones. so it should be straight forward to just calculate the difference between @map_start_time and a timestamp-value as long none of both time-values are "timezone-sensitive". 

to_datetime(to_string("timestamp")+'Z'): works fine for scaling (thx !). i can imagine that fixing that issue is not trivial (time-zones, standard time vs daylight saving time, ...) but i am sorry, since i am a university member i can provide ressources for testing but unfortunately not for sponsoring.

**Comment by kannes** [comment] 2021-03-19 11:06
I just ran into this evil bug as well. Timezones, darn timezones!

Unfortunately the timestamps in [my data](https://github.com/anitagraser/movingpandas/blob/master/tutorials/data/demodata_ais.gpkg) are in the form of '`MM/dd/yyyy HH:mm:ss`' so I have to specify that format in `to_datetime` and cannot simply append a "Z" (QTime has no concept of timezones: https://doc.qt.io/qt-5/qtime.html#fromString-1).

For me the workaround is a nasty 'parse with custom format, convert to string, add "Z", parse again with magic' sequence:


	to_datetime(
		to_string(
			to_datetime("Timestamp", 'MM/dd/yyyy HH:mm:ss')
		) || 'Z'
	),

Thoughts and prayers to the developer who will end up tackling this, stay strong :D

I guess https://doc.qt.io/qt-5/qdatetime.html will be involved.

**Comment by joeberkovitz** [comment] 2021-04-02 11:53
I have been working on a plugin project which requires the display of local times at tide observation stations around the world. To get this going in concert with the temporal controller I have had to drive all the tidal predictions to UTC, plus create a few custom expression functions that determine time zones from coordinates (using a hidden vector layer loaded from a PD timezone data set), adjust UTC dates for QTimeZones based on IANA ids or UTC offsets, and get the display names of QTimeZones for formatting purposes.

If it helps, I'm happy to contribute this code towards the timezone effort. I don't really have enough to make it into a dedicated time plugin at this point and there's little point in that if it's going to go into QGIS soon enough, but I think something like the expression functions will probably be needed.

**Comment by nyalldawson** [comment] 2021-06-10 00:33
Duplicate of https://github.com/qgis/QGIS/issues/38647

**Closed by nyalldawson** 2021-06-10 00:33 UTC
Labels: Bug, Temporal
