### ISSUE TITLE
crssync.exe - System Error

### ISSUE THREAD

**Issue by NykoTera** [qgis/QGIS#42178] opened 2021-03-10 10:14 UTC
**Describe the bug**

Usin OSGeo4W to install a nightly version of QGIS 3.19, as proposed in #42034 but got a dll issue :
![image](https://user-images.githubusercontent.com/44168242/110612737-c4aedd00-8190-11eb-8d7d-a29225ccca3e.png)

Seems like installation is not complete and got an error loading QGIS error :
![image](https://user-images.githubusercontent.com/44168242/110612912-f031c780-8190-11eb-82f2-58982116a289.png)
I tried [this](https://gis.stackexchange.com/questions/240159/qgis-2-18-the-program-cant-start-because-qgis-app-dll-is-missing-from-your-com) (using qgis-dev.bat instead of exe), but still have this error message

**How to Reproduce**

Use OSGeo4W and try to install qgis-dev build.
Note that I never installed any QGIS version (niglty or released) using OSGeo4W before on this computer.

**QGIS and OS versions**

Trying to install QGIS 3.19 nightly version
Windows 10 (10.0)

**Additional context**

After a simple search I found [this chinese post](https://blog.csdn.net/nmj2008/article/details/109555061) that locate the normal proj_8_0.dll. Look what I see in this location :
![image](https://user-images.githubusercontent.com/44168242/110613337-72ba8700-8191-11eb-8efb-b534428467d3.png)
It seems I've got a newer proj library than expected by installer.
I didn't found how to install an older dev library. I just can install prov v5, proj v6 and proj v8.1 using OSGeo4W.

**Comment by agiudiceandrea** [comment] 2021-03-10 18:58
It seems the issue is already reported on the OSGeo4W issue tracker: https://trac.osgeo.org/osgeo4w/ticket/667

If I understand correctly, currently qgis-dev doesn't work if installed with the usual OSGeo4W installer and from the usual repository. It only works if installed with the new testing OSGeo4W installer and from the new testing repository.
See https://lists.osgeo.org/pipermail/qgis-user/2021-February/048137.html and https://www.lutraconsulting.co.uk/blog/2021/02/15/qgis-point-cloud-windows/

**Comment by NykoTera** [comment] 2021-03-11 08:04
Oh yes, it works well with this installer. Thank you !

So the OSGeo4W dowload link on QGIS website seems to be obsolete ?

**Comment by gioman** [comment] 2021-03-11 08:06
Closing?

**Closed** 2021-03-11 08:10 UTC
Labels: Bug, Build/Install, Feedback

**Comment by agiudiceandrea** [comment] 2021-03-11 08:46
@NykoTera it only works for the LTR version QGIS 3.16.4. I proposed to remove also the installation instructions about the QGIS latest release via the OSGeo4W network installer from the website without success https://github.com/qgis/QGIS-Website/commit/72e5e881f9a0079d97e52f9247115c7d77b69a76#commitcomment-47686807
