### ISSUE TITLE
Metadata "save as default" for layers in geopackages with multiple layers applies to all layers

### ISSUE THREAD

**Issue by mikedufty** [qgis/QGIS#31161] opened 2019-08-08 08:22 UTC
**Describe the bug**

While metadata can be saved individually for all layers in a geopackage within a qgis project, if the save as default menu item is used to save the metadata with the geopackage file, it creates a qmd file with the current layer's data only.
Any layers imported from the geopackage will come in with the data for that layer that was saved.
Saving as default from a different layer in the geopackage will overwrite what was written previously with the data from that layer.
The metadata dialogue is not set up to allow for metadata from multiple layers to be included.

**How to Reproduce**
Import 2 layers from a single geopackage.  
Enter different metadata for each layer, save with metadata-save as default.
Open a new project and import the geopackage layers.
All layers will have the metadata last saved.

**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**

Not sure if this should be a feature request.
I'd expected metadata to be able to be saved within the geopackage like styles.
Failing that something like what is done for the identifier, being used to save separate qmd files for each layer e.g.   
MyGeopackage.gpkg|layername=My Layer

As it is, it makes using multiple layers in a single geopackage difficult.

**Comment by Gustry** [comment] 2019-08-08 10:48
Duplicate of https://github.com/qgis/QGIS/issues/25119

**Comment by mikedufty** [comment] 2019-08-11 13:27
It's not a duplicate, #25119 is about the metadata not saving in the geopackage, this is about it not handling multiple layers.  Quite possibly the same fix will work for both though.

**Comment by cesarkero** [comment] 2019-10-15 13:31
I'm just facing the same issue right now. I though that gpkg could be unbeatable but, because of this, gdp are still better. Having several sidecar files with the gpkg is not useful neither is "clean". I think it could be greate to have those metadata within the geopackage or, at least, one unique .qmd with the metadata of all the layers.

**Comment by gioman** [comment] 2020-08-01 08:39
Still valid on the latest master.

**Closed** 2021-05-04 02:18 UTC
Labels: Bug, Metadata
