### ISSUE TITLE
Crashing after loading atlas based Print Layout

### ISSUE THREAD

**Issue by rokitsciencepublic** [qgis/QGIS#33588] opened 2020-01-02 23:34 UTC
## User Feedback

Loading an atlas based layout- this is happening consistently, even after recreating the layout

## Report Details

**Crash ID**: [878842a2b15ac6bbb3476743e02ae773ae50d110]('https://github.com/qgis/QGIS/search?q=878842a2b15ac6bbb3476743e02ae773ae50d110&type=Issues')

**Stack Trace**
<pre>
QRasterPaintEngine::transformChanged :
QPainter::translate :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw qgslayouteffect.cpp:33
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent qgslayoutview.cpp:1147
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserDispatchMessage :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.1-A Coru�a
QGIS code revision: ef24c526da
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2020-01-03 09:09
@rokitsciencepublic can you attach a sample project+data? have you tried with a new QGIS profile?

**Comment by rouault** [comment] 2020-01-23 19:19
Assuming this was due to a WFS layer, and thus closing as a duplicate of #32913

**Closed by rouault** 2020-01-23 19:19 UTC
Labels: Bug, Crash/Data Corruption, Feedback, Print Layouts
