### ISSUE TITLE
Unable to use aggregate fucntions in Field Calculator under Graphical Modeller

### ISSUE THREAD

**Issue by toasthall** [qgis/QGIS#33311] opened 2019-12-10 03:59 UTC
When using aggregates in the field calculator within the graphical modeller I get the following message:

![Field Calc](https://user-images.githubusercontent.com/5704624/70493626-d9e12a00-1b4f-11ea-84b7-6a19a487661b.PNG)

**Comment by toasthall** [comment] 2019-12-10 04:01
QGIS version | 3.10.0-A CoruÃ±a | QGIS code revision | 6c816b4204
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0)
Active python plugins | AttributeAssignment; autoSaver; CalcArea; CalculateGeometry; DigitizingTools; FreehandRasterGeoreferencer; latlontools; qgis2web; quick_map_services; scriptrunner3; SemiAutomaticClassificationPlugin; SpreadsheetLayers; track_profile_2_web; db_manager; MetaSearch; processing

**Comment by gioman** [comment] 2019-12-10 10:07
Maybe is by design, not 100% sure at the moment.

**Comment by nyalldawson** [comment] 2020-06-25 21:23
Duplicate of #30397

**Closed by nyalldawson** 2020-06-25 21:23 UTC
Labels: Bug
