### ISSUE TITLE
Raster Layer Symbology crashing

### ISSUE THREAD

**Issue by DrewFrance** [qgis/QGIS#39805] opened 2020-11-04 14:23 UTC
## User Feedback

When I go to symbology in raster files lately, this crash tends to happen 50% of the time, any raster layer.

## Report Details

**Crash ID**: [6bd3f50df79a73d6a64ae737cb5de1c114f91817](https://github.com/qgis/QGIS/search?q=6bd3f50df79a73d6a64ae737cb5de1c114f91817&type=Issues)

**Stack Trace**
<pre>
QObject::isWidgetType :
QMainWindow::trUtf8 :
QHeaderView::logicalIndexAt :
QWidget::setStyleSheet :
QgsCollapsibleGroupBoxBasic::updateStyle qgscollapsiblegroupbox.cpp:386
QgsCollapsibleGroupBoxBasic::showEvent qgscollapsiblegroupbox.cpp:115
QWidget::event :
QGroupBox::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QWidgetPrivate::showChildren :
QWidgetPrivate::show_helper :
QWidget::setVisible :
QStackedLayout::setCurrentIndex :
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment] 2020-11-04 14:31
duplicate of https://github.com/qgis/QGIS/issues/39693

**Closed by gioman** 2020-11-04 14:31 UTC
