### ISSUE TITLE
Fix Geometries - Structure stops because of wrong 

### ISSUE THREAD

**Issue by justinjngan** [qgis/QGIS#53954] opened 2023-07-26 11:37 UTC
### What is the bug or the crash?

The structured method to make geometries valid requires a QGIS build based on GEOS 3.10 or later
Execution failed after 0.01 seconds

### Steps to reproduce the issue

Run Fix Geometries
Choose Structure for Repair method

### Versions

Mac does not have the About option under Help

The current released version of QGIS is 3.32.1. 
We are working on 3.33-Master. It will go into feature freeze on 2023-09-15 12:00:00 UTC and be released as 3.34 on 2023-10-27 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Fulll error

QGIS version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec112
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2023-07-26T07:37:20
Algorithm 'Fix geometries' starting…
Input parameters:
{ 'INPUT' : '/Users/justinngan/Downloads/Roads_2021.gpkg|layername=Roads', 'METHOD' : 1, 'OUTPUT' : 'TEMPORARY_OUTPUT' }

The structured method to make geometries valid requires a QGIS build based on GEOS 3.10 or later
Execution failed after 0.01 seconds

Loading resulting layers
Algorithm 'Fix geometries' finished

**Comment by lbartoletti** [comment] 2023-07-26 12:02
Please can you share your data to test?

**Comment by nicogodet** [comment] 2023-07-26 12:19
MacOS build is based on an old version of GEOS (3.9.5). This is a known issue for a will.
more info here : https://github.com/qgis/QGIS-Mac-Packager/issues/160

**Comment by justinbb** [comment] 2023-08-08 07:57
This is a duplicate of #52360. The immediate problem was fixed in a point release of 3.30. The underlying problem is as mentioned above by @nicogodet.

**Comment by agiudiceandrea** [comment] 2023-08-08 15:37
@justinbb, it seems to me this issue report is not a duplicate of https://github.com/qgis/QGIS/pull/52360 (actually, not a duplicate of https://github.com/qgis/QGIS/pull/52360). This issue report is not about a crash.
The same issue was reported at https://github.com/qgis/QGIS-Mac-Packager/issues/160 as already stated in a previous comment.
Please see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/270 on how QGIS.ORG will address this and other macOS issues.
I think we can close this issue report since it is not related to QGIS itself.

**Closed by agiudiceandrea** 2023-08-08 15:37 UTC
Labels: Bug, macOS, Downstream

**Comment by justinbb** [comment] 2023-08-08 19:07
@agiudiceandrea Right, sorry. This would be the non-crash resulting from the fix :-)
