### ISSUE TITLE
current theme variable

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#56886] opened 2024-03-17 17:22 UTC
### Feature description

It would be useful to have the `@current_theme` variable among the variables present in the expression engine, this would allow us to understand which theme is currently active.

Layer Panel:
![image](https://github.com/qgis/QGIS/assets/7631137/d31a12b8-c90d-4c24-8a92-230c667bbdde)

field calc:

![image](https://github.com/qgis/QGIS/assets/7631137/7a5dc873-13ad-4c96-8f7f-095d4c891ad8)

**Comment by nyalldawson** [comment] 2024-03-17 22:59
Duplicate of https://github.com/qgis/QGIS/issues/29581

**Closed by nyalldawson** 2024-03-17 22:59 UTC
Labels: Expressions, Feature Request, Field Calculator
