### ISSUE TITLE
DB Manager: geometry column is a no show in virtual layers

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#46025] opened 2021-11-14 10:21 UTC
### What is the bug or the crash?

QGIS 3.22.0 and 3.16.13 OSgeo4W v2, Windows 10
Geometry column is a no show when querying a project layer in DB Manager within "Virtual Layers":

![image](https://user-images.githubusercontent.com/1951107/141676795-ef0d2517-5675-4eeb-9225-b8c0ac768305.png)

On earlier QGIS versions:

![image](https://user-images.githubusercontent.com/1951107/141676865-5a5fec31-aee7-49f0-8324-818e52ae0a2d.png)

On QGIS 3.16.6 (based on OSGeo4W v1/old dependencies) is also OK.

### Steps to reproduce the issue

See above.

### Versions

See above.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2021-11-14 11:34
Can you try on master ?
Few fixes recently but I don't know if they affect this

**Comment by gioman** [comment] 2021-11-14 12:58
> Can you try on master ?
> Few fixes recently but I don't know if they affect this

@nicogodet no changes on the latest master available on osgeo4w v2.

**Comment by nicogodet** [comment] 2021-11-14 15:08
https://github.com/qgis/QGIS/blob/637e5ca748dbd68eb9ce5c3aa7370916274865e4/python/plugins/db_manager/db_plugins/vlayers/connector.py#L59

Returns `False` when, I believed, it should not.

```python
>>> d = QgsVirtualLayerDefinition.fromUrl(QUrl("file:///C:/Users/Nicolas Godet/AppData/Local/Temp/QGIS3.aHnRWI?layer_ref=Pistes_Ibardin_6bac0d29_baae_4574_9a20_aab9403d3745:Pistes_Ibardin&geometry=geometry:5:2154&field=id:int&field=Nom:text&field=Difficulte:text&field=Dénivelé:real&field=Longueur:int&lazy"))
>>> d.hasDefinedGeometry()
False
```

**Comment by nicogodet** [comment] 2021-11-14 15:48
Something seems to fail during `fromUrl()` method.

```python
>>> d = QgsVirtualLayerDefinition.fromUrl(QUrl("file:///C:/Users/Nicolas Godet/AppData/Local/Temp/QGIS3.aHnRWI?layer_ref=Pistes_Ibardin_6bac0d29_baae_4574_9a20_aab9403d3745:Pistes_Ibardin&geometry=geometry:5:2154&field=id:int&field=Nom:text&field=Difficulte:text&field=Dénivelé:real&field=Longueur:int&lazy"))
>>> d.toUrl()
PyQt5.QtCore.QUrl('file:///C:/Users/Nicolas Godet/AppData/Local/Temp/QGIS3.aHnRWI?layer_ref=Pistes_Ibardin_6bac0d29_baae_4574_9a20_aab9403d3745:Pistes_Ibardin&lazy')
```

**Comment by albertograva** [comment] 2021-11-30 13:08
I don't know if related to this issue...
but if I try to create a new virtual layer it turns me an error message like: "impossible to opne virtual layer selection panel"

thx

qgis 3.22.1-Białowieża on ubuntu 0.20.04.1

**Comment by pigreco** [comment] 2021-11-30 14:54
By clicking on New Virtual Layer the message appears:

![image](https://user-images.githubusercontent.com/7631137/144069984-efce33ef-e3bc-4956-8370-086f9319617e.png)

## OSGeo4W v2 QGIS 3.22.1

**Comment by m4x300** [comment] 2021-12-06 23:45
[Can totally confirm] missing geometry column in DB manager as well as the error message when trying to edit already existing virtual layers in a project when using **any Qgis version depending on OSGeo4W v2**
(https://gis.stackexchange.com/questions/413600/qgis-db-manager-virtual-layers-geometry-column-not-showing)

**Comment by Bernd-Vogelgesang** [comment] 2021-12-09 12:29
Confirmed for Linux Mint and 3.22 with editing a new virtual layer.
As I had to move a project to another disk, the Virtual layer does not find the source, I can't edit it  or recreate it-> Data loss!

**Comment by nyalldawson** [comment] 2021-12-13 22:37
This is fixed now, isn't it? I can't reproduce anymore

**Comment by pigreco** [comment] 2021-12-14 07:08
> This is fixed now, isn't it? I can't reproduce anymore

![image](https://user-images.githubusercontent.com/7631137/145949686-45df435f-1b60-4413-9d3c-6ce9cfc9942a.png)
it works for me

**Comment by m4x300** [comment] 2021-12-14 12:34
@gioman Does DB Manager in version 3.22.1 on Windows return a geometry column? If not please undo the closing!

**Comment by gioman** [comment] 2021-12-14 12:36
> @gioman Does DB Manager in version 3.22.1 on Windows return a geometry column? If not please undo the closing!

@m4x300 there is another ticket about this.

**Comment by gioman** [comment] 2021-12-14 12:40
> @m4x300 there is another ticket about this.

@m4x300 no sorry, the ticket I was thinking about is this one.

**Comment by m4x300** [comment] 2021-12-14 13:55
@gioman Thanks.  Since this is a rather pressing issue - Is there a way to push this?

**Comment by gioman** [comment] 2021-12-14 13:56
> Is there a way to push this?

@m4x300 sure, you can contact one of the many companies (listed on the site) that offer commercial support.

**Comment by nyalldawson** [comment] 2021-12-15 01:40
Why was this re-opened? It was fixed and the fix was backported to 3.22

**Comment by gioman** [comment] 2021-12-15 08:22
> Why was this re-opened? It was fixed and the fix was backported to 3.22

@nyalldawson on [618d575704 ](https://github.com/qgis/QGIS/commit/618d575704073727def70cb671a6cad28b1dfeda)(osgeo4w) the geometry column is still a no show in virtual layers, as described https://github.com/qgis/QGIS/issues/46025#issue-1052901839

**Comment by nyalldawson** [comment] 2021-12-15 08:25
@gioman that's not a nightly version though, and the fixes haven't hit a release yet...

**Comment by gioman** [comment] 2021-12-15 08:27
> that's not a nightly version though

@nyalldawson is master/osgeo4w, with commits from up 22 hours ago, isn't that right?

**Comment by agiudiceandrea** [comment] 2021-12-15 08:27
> @gioman that's not a nightly version though, and the fixes haven't hit a release yet...

@nyalldawson the version referred by @gioman at commit 618d575704 is a qgis-dev nightly build.

**Comment by m4x300** [comment] 2022-01-14 19:25
version 3.22.2 still not happening.

**Comment by gioman** [comment] 2022-01-14 19:28
> version 3.22.2 still not happening.

@m4x300 sure, this is still open so it means that there is no fix yet.

**Comment by gioman** [comment] 2022-03-12 17:11
Still valid on 3.24.0

**Comment by lbartoletti** [comment] 2022-03-23 08:51
It's ok for me on 3.24.0 :

![image](https://user-images.githubusercontent.com/7521540/159659295-779a17b0-1270-49c7-9c6e-10ca6d2f907e.png)

![image](https://user-images.githubusercontent.com/7521540/159659575-7448e2b8-1a6c-4df0-a138-67474bb7bd5b.png)

@gioman it's weird. Maybe is there a particular step to reproduce?

My steps: I have created a new projet, add a layer and run the query on the virtual layer in DB Manager

I'm missing something?

**Comment by pigreco** [comment] 2022-03-23 09:00
@lbartoletti 

I confirm that the geometry is not visible
![2022-03-23_09h58_13](https://user-images.githubusercontent.com/7631137/159661697-03a24c8f-81b9-4943-bf87-4dbc38b853b6.gif)


## OSGeo4w64 Win 10 Pro 64 bit

**Comment by m4x300** [comment] 2022-03-23 13:54
@lbartoletti judging from the looks of your ui you're on macos and apparently the issue is OSGeo4W v2 related. that's probably what you're missing out on.

**Comment by lbartoletti** [comment] 2022-03-23 14:12
@m4x300 I'm not on macOs (FreeBSD for me). But yes, it's a Windows only bug.

**Comment by lbartoletti** [comment] 2022-03-23 14:13
I can reproduce it on QGIS 3.25 on windows

**Comment by agiudiceandrea** [comment] 2022-03-23 14:14
@lbartoletti I can confirm the issue about the missing geometry column does only occur with QGIS 3.16.16, 3.20.x, 3.22.x and 3.24.x installed using the OSGeo4W Network Installers v2 or the .msi OSGeo4W Standalone Installers.
The issue does not occur with QGIS 3.16.16 installed using the OSGeo4W Network Installers v1 or the .exe OSGeo4W Standalone Installers.

So I think the issue is due to some underlying issue in the different dependencies or some other issue in the packaging of OSGeo4W v2 repository.

QGIS 3.16.16 (OSGeo4W v1) works:
QGIS version
3.16.16-Hannover
QGIS code revision
f5778a89df
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing


QGIS 3.16.16 (OSGeo4W v2) doesn't work:
QGIS version
3.16.16-Hannover
QGIS code revision
f5778a89
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.1
Running against GDAL/OGR
3.4.1
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.37.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.1
Running against PROJ
Rel. 8.2.1, January 1st, 2022
OS Version
Windows 10 Version 1903
Active python plugins
db_manager; 
MetaSearch; 
processing

**Comment by lbartoletti** [comment] 2022-03-23 14:16
> So I think the issue is due to some underlying issue in the different dependencies or some other issue in the packaging of OSGeo4W v2 repository.

I agree with you, I was trying to find the differences between the packages... 

Maybe @jef-n has an idea?

**Closed** 2023-03-18 21:48 UTC
Labels: Regression, DB Manager, Bug, Windows
