### ISSUE TITLE
QGIS 3.10.2 crashes when committing changes to a layer after editing geometry in python console

### ISSUE THREAD

**Issue by scottshambaugh** [qgis/QGIS#34044] opened 2020-01-27 05:34 UTC
**Describe the bug**
When I attempt to modify my layer's geometry using the Python Console, QGIS crashes when I call the commitChanges() method.

Using a fresh installation of QGIS 3.10.2 on Windows 10. I believe I ran into this issue on previous versions as well. 

**How to Reproduce**

The following code snippet (doesn't do anything useful, I tried to edit down to the bare essentials) triggers the crash with the attached project & shapefile: [crash_test_files.zip](https://github.com/qgis/QGIS/files/4115676/crash_test_files.zip)

```
from qgis.core import *
import qgis.utils
layer = QgsProject.instance().mapLayersByName("crash_test")[0]
layer.startEditing()

for f in layer.getFeatures():
    g = f.geometry()
    mls = g.get()    # multilinestring
    layer.changeGeometry(f.id(), QgsGeometry(mls))

layer.commitChanges()
```

**Stack Trace**

> QgsGeometry::asWkb qgsgeometry.cpp:2369
> QgsOgrProvider::changeGeometryValues qgsogrprovider.cpp:2357
> QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:378
> QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3102
> meth_QgsVectorLayer_commitChanges sip_corepart1.cpp:319829
> PyMethodDef_RawFastCallKeywords :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyEval_EvalCodeWithName :
> PyImport_Import :
> PyImport_Import :
> PyMethodDef_RawFastCallKeywords :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyEval_EvalCodeWithName :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyEval_EvalCodeWithName :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyFunction_FastCallDict :
> PyMethodDef_RawFastCallDict :
> PyObject_Call :
> PyInit_sip :
> PyInit_Qsci :
> QWidget::event :
> QFrame::event :
> QAbstractScrollArea::event :
> PyInit_Qsci :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QSizePolicy::QSizePolicy :
> QSizePolicy::QSizePolicy :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QGuiApplicationPrivate::processKeyEvent :
> QWindowSystemInterface::sendWindowSystemEvents :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main main.cpp:1598
> BaseThreadInitThunk :
> RtlUserThreadStart :

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**

[crash_test_files.zip](https://github.com/qgis/QGIS/files/4115676/crash_test_files.zip)

**Comment by elpaso** [comment] 2020-01-27 08:25
The problem is:
```
layer.changeGeometry(f.id(), QgsGeometry(mls))
```

QgsGeometry gets garbage-collected. Store it in a python variable.

**Comment by gioman** [comment] 2020-01-27 11:26
Closing?

**Comment by scottshambaugh** [comment] 2020-01-27 14:49
The crash still occurs if I do that:
```
from qgis.core import *
layer = QgsProject.instance().mapLayersByName("crash_test")[0]
layer.startEditing()

for f in layer.getFeatures():
    g = f.geometry()
    mls = g.get()    # multilinestring
    g2 = QgsGeometry(mls)
    layer.changeGeometry(f.id(), g2)

layer.commitChanges()
```

**Comment by elpaso** [comment] 2020-01-27 16:51
This works for me:

```
# store geoms so that they don't get garbage collected
geoms = []

for f in layer.getFeatures():
    g = f.geometry()
    geoms.append(g)
    mls = g.get()    # multilinestring
    g2 = QgsGeometry(mls)
    fid = f.id()
    layer.changeGeometry(fid, g2)
```

or just don't use `get()` (that if I'm not wrong returns a raw pointer to the geometry without incrementing the reference counter).

```
for f in layer.getFeatures():
    g = f.geometry()
    mls = g  # makes a copy
    g2 = QgsGeometry(mls)  # makes another copy
    fid = f.id()
    layer.changeGeometry(fid, g2)
```

**Closed by elpaso** 2020-01-27 16:51 UTC
Labels: Bug

**Comment by scottshambaugh** [comment] 2020-01-28 02:00
Thank you! Your snippets work for me.
