### ISSUE TITLE
Can't set min/max values to decimal in raster symbology with QGis Linux versions

### ISSUE THREAD

**Issue by benjaminh** [qgis/QGIS#33859] opened 2020-01-16 17:22 UTC
When setting the properties of a raster layer, I encounter an issue related to Min/Max values form fields (with Singleband pseudo color render type) : default precalculated value can be decimal, but I can't manually set the value to decimal.

Strange thing is : form field accepts dot symbol `.` if such symbol is already present, but the key doesn't work if the default value is an integer. I also cannot copy/paste a value in those fields.

In my case, as a matter of example, default max value is `30.8921` and default min value is `-100`. If I suppress only decimal values in the max value field, I can achieve to set to `0.5`, but I clean the field, I am not able to add a dot. In the min value field, I cannot add a dot at all.

This issue occurred on QGis 3.4 LTS, 3.8, 3.10 with Ubuntu 18.04, Debian 10 and MacOS 10 Catalina. Doesn't occur on Windows versions (tested only on QGis 3.4 with Windows 10).

How to reproduce :
- Add raster layer in QGis (3.4 for example) under Ubuntu 18.04 (didn't test with other versions)
- Select the layer and open the Properties window
- In symbology, choose `Singleband pseudocolor` for `Render type`
- Try to set default Min value to `-0.5` and Max value to `0.5`

Please tell me if you need additional infos, this bug looks quite surprising in my opinion (or is it ?).

**Comment by elpaso** [comment] 2020-01-16 18:23
What are your language and locale settings in QGIS -> Options -> General ?

**Comment by gioman** [comment] 2020-01-16 18:37
> What are your language and locale settings in QGIS -> Options -> General ?

@elpaso it also happens on QGIS in English on a operating system in English. In my case is Ubuntu 18.04 and QGIS 3.10.1. I can't recall such limitation in the past, so it is likely to be a regression (not 100% sure).

**Comment by gioman** [comment] 2020-01-16 20:36
And confirm that also on Windows (all in English) does not seems to be an issue.

**Comment by benjaminh** [comment] 2020-01-17 08:42
> What are your language and locale settings in QGIS -> Options -> General ?

I use French and fr_FR, but also tried to change to American English and en_US

**Comment by elpaso** [comment] 2020-01-21 17:59
I cannot reproduce with current master.

**Comment by elpaso** [comment] 2020-01-22 09:56
@benjaminh can you share a test project that shows the issue?

**Comment by gioman** [comment] 2020-01-22 12:11
> @benjaminh can you share a test project that shows the issue?

@elpaso here it goes

[sample.zip](https://github.com/qgis/QGIS/files/4097131/sample.zip)

Also see this: in the cast is not possible to appreciate the fact that trying to use the "." as separator does not work. But you can see that you can use the "," but that causes the min/max values to automatically revert both to 0

![Peek 2020-01-22 12-09](https://user-images.githubusercontent.com/1951107/72893191-5ef35d80-3d10-11ea-8ccf-ee74468cc1ad.gif)

**Comment by benjaminh** [comment] 2020-01-22 12:15
> > @benjaminh can you share a test project that shows the issue?
> 
> @elpaso here it goes
> 
> [sample.zip](https://github.com/qgis/QGIS/files/4097131/sample.zip)
> 
> Also see this: in the cast is not possible to appreciate the fact that trying to use the "." as separator does not work. But you can see that you can use the "," but that causes the min/max values to automatically revert both to 0
> 
> ![Peek 2020-01-22 12-09](https://user-images.githubusercontent.com/1951107/72893191-5ef35d80-3d10-11ea-8ccf-ee74468cc1ad.gif)

Exactly what I also get, thank you for providing a data sample !

**Comment by elpaso** [comment] 2020-01-22 13:43
@gioman thanks for sharing, unfortunately I still cannot reproduce, I tried with and without locale overrides and with different locales.

I must say that locales are not even taken into consideration in that particular widget so it shouldn't really matter.

The only difference I can think of is that I'm building with a different (and far newer) QT version: 5.13.2.

**Comment by benjaminh** [comment] 2020-01-22 13:56
> @gioman thanks for sharing, unfortunately I still cannot reproduce, I tried with and without locale overrides and with different locales.
> 
> I must say that locales are not even taken into consideration in that particular widget so it shouldn't really matter.
> 
> The only difference I can think of is that I'm building with a different (and far newer) QT version: 5.13.2.

I don't know if that helps, but I'm not building my QGis version from sources. I installed the LTS version from the official ppa (according to QGis doc) : `https://qgis.org/ubuntu-ltr bionic main`.

**Comment by gioman** [comment] 2020-01-22 14:54
> The only difference I can think of is that I'm building with a different (and far newer) QT version: 5.13.2.

@elpaso yeah... Windows uses 5.11.something and works as expected... closing?

**Comment by elpaso** [comment] 2020-01-22 15:28
@gioman I'd say yes, but I'm not 100% sure QT is to blame. 

I cannot test QT 5.9.5 here, sorry, the oldest I have is 5.11.0 but a full rebuild will waste me ~30 minutes.

**Comment by GustyLa** [comment] 2020-02-12 10:57
Had exactly the same issue using Norwegian as the Locale. Found a workaround by setting the User Interface Translation to American English, and the Locale to English UnitedStates (en_US).

**Comment by elpaso** [comment] 2020-02-12 11:08
Can anyone check a master MXE windows build? https://github.com/qgis/QGIS/actions?query=workflow%3A%22Windows+cross+build+with+MXE%22
It uses QT 5.13, so that we can rule that out.

**Comment by gioman** [comment] 2020-02-12 12:45
> Can anyone check a master MXE windows build? https://github.com/qgis/QGIS/actions?query=workflow%3A%22Windows+cross+build+with+MXE%22
> It uses QT 5.13, so that we can rule that out.

@elpaso It seems to be ok, meaning that decimal values can be entered using the dot as delimiter and after applying/closing/reopening the properties dialog that values stick as expected.

Small issue:
On the other hand a user can still try use the comma as separator, but QGIS will reset the values to 0.

**Comment by SebastienPeillet** [comment] 2020-06-09 14:30
> I must say that locales are not even taken into consideration in that particular widget so it shouldn't really matter.

Actually it is because we apply QDoubleValidator on the lineEdit widgets (see [QValidator doc](https://doc.qt.io/qt-5/qvalidator.html#locale) ) : 

`The locale is by default initialized to the same as QLocale().`

So the lineEdit expects a QString that looks like a double/float with the local configuration, and then we convert these QString to double/float without taking account of the local... that's explain why these values are reset

**Comment by agiudiceandrea** [comment] 2020-06-09 16:00
Hi @SebastienPeillet, it seems there are some widget that use QDoubleValidator() and toDouble() instead of QLocale().toDouble()
qgssinglebandpseudocolorrendererwidget.cpp
qgssinglebandgrayrendererwidget.cpp
qgsmultibandcolorrendererwidget.cpp
qgsextentwidget.cpp
...

**Comment by SebastienPeillet** [comment] 2020-06-09 16:08
@agiudiceandrea Indeed :+1:  I began to fix it [here](https://github.com/SebastienPeillet/QGIS/commit/6e6663417e80344fa2957384bed1579e1dde230e), but it's not easy to catch them all :)

**Comment by elpaso** [comment] 2020-06-09 16:19
@SebastienPeillet I'm pretty sure we have dealt with double validation and locales before but unfortunately I can't remember in which part of the code. I remember writing code that accepts locale's decimal separator and fall back to (`.`) on failure.

**Comment by agiudiceandrea** [comment] 2020-06-09 16:50
@elpaso https://github.com/qgis/QGIS/commit/d9afb899a0311f4867e0ec5a2cd1265a910a516d

**Comment by SebastienPeillet** [comment] 2020-06-09 17:14
@elpaso Thank you, I guess you are talking about [qgsfieldvalidator.cpp#L59](https://github.com/qgis/QGIS/blob/master/src/gui/qgsfieldvalidator.cpp#L59) and [convertCompatible function in qgsfield.cpp](https://github.com/qgis/QGIS/blob/master/src/core/qgsfield.cpp#L339) ? I wasn't aware of this, so I didn't think about searching

Edit : @agiudiceandrea :+1:  

An opinion on what is the best between QLocale( QLocale::English) or QLocale( QLocale::C ) ? Nevermind ?

**Comment by elpaso** [comment] 2020-06-09 17:26
@agiudiceandrea @SebastienPeillet yes, maybe a good idea to add a generic static function to some utils class, put it under test and use it everywhere?

Side note to self: the QGIS API has grown sooo big that reinventing the wheel is a serious threat.
 
I would use QLocale::C, as far as LC_NUMERIC is concerned they are equivalent.

**Closed** 2020-07-14 13:45 UTC
Labels: Bug, Raster
