### ISSUE TITLE
Inaccurate Layer Projection Over Basemap on OSX 12.0.1

### ISSUE THREAD

**Issue by jlaw45** [qgis/QGIS#47213] opened 2022-02-06 05:24 UTC
### What is the bug or the crash?

Using OpenStreetMap as a base map, rasters & shapefiles do not project currently. CSRs are the same. Generally, the rasters and shapefiles end up northwest of their intended location. But as you zoom and navigate around the map the rasters and shapefiles also move, instead of staying stationary. 

### Steps to reproduce the issue

1. Load OpenStreetMap
2. Drag in shapefile or raster
3. Notice it does not project to the proper location
4. Use hand tool to move around or zoom out
5. Notice the shapefile or raster does not stay at it's original displayed location, nor the intended location

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.0
  |   |   |  
Active Python plugins
quick_map_services | 0.19.28
SRTM-Downloader | 3.1.15
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[1628765ec7](https://github.com/qgis/QGIS/commit/1628765ec7)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
12.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.0

Active Python plugins
quick_map_services
0.19.28
SRTM-Downloader
3.1.15
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment] 2022-02-06 11:00
> Active Python plugins
> quick_map_services
> 0.19.28
> SRTM-Downloader
> 3.1.15

@jlaw45 this means you haven't tried on a new QGIS profile, please do. If the problem persist please attach a small sample project+data.

**Comment by gioman** [comment] 2022-02-06 11:00
@jlaw45 also, M1 or Intel?

**Comment by gioman** [comment] 2022-02-06 13:09
@jlaw45 can't replicate on macOS 12.1 on M1 (mac mini 2020) BUT the same issue has been reported to me privately from another user, and also was not able to replicate. 

![IMG_20220206_130833_743.jpg](https://user-images.githubusercontent.com/1951107/152682392-72a75d26-4edd-42e3-a6e7-ee815f0304ff.jpg)

**Comment by jlaw45** [comment] 2022-02-06 14:51
@gioman Intel.

Maybe updating my system will solve the issue.

I'll try with a new profile. For what it's worth, I'm a brand new user as of yesterday, so my profile is new. But your comment tells me it has to do with the accumulation of third party plugins, not the newness of a profile?

**Comment by agiudiceandrea** [comment] 2022-02-06 17:40
> it has to do with the accumulation of third party plugins, not the newness of a profile?

@jlaw45, if the profile were really new (i.e. created just before the test), it would not contain any third party plugin.

**Comment by kobrienGIS** [comment] 2022-02-06 23:00
Very new user here, but I have been having this same issue on MacOS Monterey 12.2 (Intel) as of a couple days ago. Like OP said, it persists with basemaps and rasters. I have uninstalled and reinstalled the newest version of QGIS and that didn't help. I am also reproducing this with the sample data from https://qgis.org/downloads/data/ by simply adding any basemap (OpenStreetMap) and I used the Alaska shapefile.

**Comment by gioman** [comment] 2022-02-07 13:06
Just tested again on both 3.22.2 and .3 on macOS Catalina (Intel) and Monterey (M1), no issues whatsoever.

If there is an issue then there is something else at play.

**Comment by jlaw45** [comment] 2022-02-08 02:01
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.0
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.3-Białowieża
QGIS code revision
[1628765ec7](https://github.com/qgis/QGIS/commit/1628765ec7)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
12.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.0




Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5


On a new profile I pulled a base map from the Overpass API link on OSM's website. Then dragged in the same shapefiles in from before and everything projected perfectly.

Then I downloaded QuickMapServices plugin and the OSM Standard map I loaded from there would not project correctly and seems to be the culprit of the drift.

Any suggestions for a good basemap plugin or online source?

**Comment by gioman** [comment] 2022-02-08 12:13
> Then I downloaded QuickMapServices plugin and the OSM Standard map I loaded from there would not project correctly and seems to be the culprit of the drift.

@jlaw45 just tested it on a M1 and Intel mac Mini, on 3.22.3 and can't confirm.

**Comment by Lugal-PCZ** [comment] 2022-02-08 15:13
I'm having the same problem on an M1 MacBook Air with Mac OS 12.2. It was working fine with 3.22.2, but started with 3.22.3. I will try reverting to see if the issue is resolved.

**Comment by Lugal-PCZ** [comment] 2022-02-08 16:19
Oddly enough, the problem seems to be resolved. I think that the culprit was QuickMapServices. I updated all my plugins, and then when I re-launched QGIS everything worked properly again.

**Comment by gioman** [comment] 2022-02-08 16:20
Anyone else here experiencing this issue is using a not up to date version of the QuickMapServices plugin?

**Comment by Lugal-PCZ** [comment] 2022-02-08 20:31
Rats! The problem came back. I didn't make any changes, just closed and re-opened the same project that I was using before.

**Comment by Lugal-PCZ** [comment] 2022-02-09 00:31
I'm not sure how to make a self-contained sample project, so here's a Geopackage file with one layer, a 50x50m grid overlaying the archaeological site of Lagash. It's supposed to plot directly on top of the site that's visible in Google Earth Satellite or Bing Satellite imagery retrieved with QMS, but doesn't anymore. Now, when you zoom or pan, the points move relative to the site in the satellite imagery.
[Lagash.gpkg.zip](https://github.com/qgis/QGIS/files/8028437/Lagash.gpkg.zip)

**Comment by Lugal-PCZ** [comment] 2022-02-09 04:15
Update: I downloaded the LTS, and it displayed properly with the same project file. Then I deleted all my QGIS preferences and profile, and the problem resurfaced when I opened the same project file, unmodified, with 3.22.3. I have no idea why it doesn't fail 100% of the time, but now it fails almost always w/ the latest QGIS version.

**Comment by nyalldawson** [comment] 2022-02-09 04:18
Isn't this a duplicate of https://github.com/qgis/QGIS/issues/46882? (fixed for 3.22.4)

**Comment by Lugal-PCZ** [comment] 2022-02-09 04:31
Yes, Retina Display seems to be the issue. The problem rears its head on my laptop, but not on an external monitor connected to that same laptop. When I drag the QGIS window between the laptop’s screen and the external monitor shows the display goes from working (external monitor) to problematic (laptop screen).

**Comment by jlaw45** [comment] 2022-02-09 17:15
Can confirm, my iMac's Retina display has the issue but my external monitor projects OSM and the other layers accurately.

**Comment by gioman** [comment] 2022-02-10 19:55
> Isn't this a duplicate of #46882? (fixed for 3.22.4)

Closing as duplicate/fixed.

**Closed by gioman** 2022-02-10 19:55 UTC
Labels: Feedback, Bug

**Comment by lambichr** [comment] 2022-06-23 09:17
This is still a problem. I am experiencing this on several Macs... Rasters and Shapefiles are located in the wrong location, even though they have the same CRS and on-the-fly projection is enabled.
