### ISSUE TITLE
Geometry generator is not rendered if feature's geometry does not intersect with canvas extent

### ISSUE THREAD

**Issue by 3nids** [qgis/QGIS#40377] opened 2020-12-01 09:15 UTC
When using a geometry generator in symbogy, the symbol is only rendered if the feature's geometry intersects with the current map canvas extent.

While this is totally understandable in terms of performance optimization, there are cases where this is a limitation.

I would propose to add an option in the geometry generator dialog to by-pass the check and force to compute the geometry to check if the symbol has to be rendered or not.

**Comment by nyalldawson** [comment] 2020-12-01 09:17
I think theres already a ticket for this, but I'd suggest having an option to extend the map bounds "render features within .... Map units". That's quite straightforward to implement, there's already API for a renderer to extend the request bounds

**Comment by 3nids** [comment] 2020-12-01 09:22
I don't think this is sufficient. 
I was thinking of the case where you have null geometries.

**Comment by gioman** [comment] 2020-12-01 09:34
@3nids duplicate of https://github.com/qgis/QGIS/issues/38579 ?

**Closed** 2020-12-01 10:04 UTC
Labels: Bug
