### ISSUE TITLE
Chinese character layer name cannot be displayed normally in Geospatial PDF

### ISSUE THREAD

**Issue by antzzp** [qgis/QGIS#38201] opened 2020-08-08 09:43 UTC
I have threee spatial layers(two layers' names are English,one is Chinese) in qgis. I exported the layout in Geospatial PDF,it generated the GeoPDF file  succesfully.When I open the PDF file with Adobe Reader or other application,the features of three layers' are fine,but in the layer panel,my Chinese character layers' name cannot be displayed normally ,the Chinese character is garbled.
My OS is windows 7 and qgis version is 3.14.1-PI.
Zheng Zhipeng,Qgis uesr from China.
![image](https://user-images.githubusercontent.com/33449027/89707139-1e062200-d99e-11ea-959b-168ddf67c75c.png)
![image](https://user-images.githubusercontent.com/33449027/89707140-23fc0300-d99e-11ea-82c9-436adb9e20fa.png)
![image](https://user-images.githubusercontent.com/33449027/89707141-28282080-d99e-11ea-98e7-52e786a9d956.png)

**Comment by FelisPimeja** [comment] 2020-09-25 08:03
Confirm same problem with other non latin characters in layer name. In example below I've tried Cyrillic, Deutch and Simplified chinese for layer names, 

![qgis geopdf bug](https://user-images.githubusercontent.com/874261/94211919-68eee100-fedb-11ea-9b79-e7a30d38e331.gif)

**Comment by agiudiceandrea** [comment] 2020-11-21 09:11
Hi @FelisPimeja @antzzp, could you please check if the issue is fixed for you with the latest QGIS 3.16.1 (in will be available today or in the next few days)?

**Comment by antzzp** [comment] 2020-11-24 01:00
Simplified Chinese works well both in layer name and attributes in QGIS 3.16.1.
Thanks for the efforts!
![图片](https://user-images.githubusercontent.com/33449027/100032652-740ab280-2e33-11eb-9ae9-030c81f9e0fd.png)
![图片](https://user-images.githubusercontent.com/33449027/100032661-7836d000-2e33-11eb-915e-d3ce5747760f.png)

**Comment by gioman** [comment] 2020-11-24 11:58
Not sure why the merge of the PR did not auto closed this.

**Closed by gioman** 2020-11-24 11:58 UTC
Labels: Bug, Feedback, Print Layouts
