### ISSUE TITLE
loading of QGIS project is very slow, when containing multiple Layouts

### ISSUE THREAD

**Issue by fischerteamplan** [qgis/QGIS#51438] opened 2023-01-11 22:18 UTC
### What is the bug or the crash?

QGIS Project loads very slowly, when starting a project containing 23 Layouts. Is it possible to force QGIS not loading the Layouts while open the project?

### Steps to reproduce the issue

I have a project, which laods very slowly when I open the project.
The loading bar gets actually very quickly to 100%, but then remains loading (somehow freezes).
I tried deleting all the 23 Layouts of the project. The project loaded quickly to 100% without hanging/freezing. So I assume, the loading of the Layouts takes a long time. 

### Versions

QGIS 3.22.10 and QGIS 3.22.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2023-01-12 00:56
Duplicate of #51233

**Closed** 2023-01-12 06:19 UTC
Labels: Bug
