### ISSUE TITLE
QGIS hangs on graduated symbols with fixed interval classification

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#50932] opened 2022-11-18 08:08 UTC
### What is the bug or the crash?

While using the fixed interval classification (graduated legend, new since 3.26) QGIS hangs.

### Steps to reproduce the issue

can be reproduced using natural earth dataset ne_50m_admin_0_countries (attached) and the attribute gdp_md_est
1 load layer
2 layer styling->graduated
3 select column gdp_md_est
4 select mode: fixed interval
![2022-11-18 09_05_46-_Untitled Project — QGIS  English  (Keine Rückmeldung)](https://user-images.githubusercontent.com/46351209/202652423-a3c77de4-0be8-40c0-a3b5-f0d4d980a28a.png)

[ne_50m_admin_0_countries.zip](https://github.com/qgis/QGIS/files/10039315/ne_50m_admin_0_countries.zip)

### Versions

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
ee_plugin | 0.0.5
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f](https://github.com/qgis/QGIS/commit/ed3ad0430f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2022-11-18 13:03
Duplicate of #49333

**Closed by uclaros** 2022-11-18 13:03 UTC
Labels: Bug
