### ISSUE TITLE
libqgis_customwidgets causes SIGSEGV in QT Designer

### ISSUE THREAD

**Issue by DavidPavlicek** [qgis/QGIS#33202] opened 2019-12-03 09:58 UTC
Recently I updated my development virtual machine (VirtualBox) from Debian 9 to Debian 10. Except for a few minor bumps along the road, everything went smooth. But when I try to run QT Designer I got this message in terminal (in Czech environment):

    Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
    Neoprávněný přístup do paměti (SIGSEGV)

and this in syslog:

    kernel: [403847.205496] designer[7998]: segfault at 8 ip 00007f9977eef510 sp 00007fff537da728 error 4 in libQt5Core.so.5.11.3[7f9977cdd000+2a4000]
    kernel: [403847.205502] Code: e9 8b 2e e0 ff e9 d4 2e e0 ff 48 8b 4f 08 83 e6 01 01 f6 0f b6 51 20 89 d0 83 e2 fd d0

QT tools came from the system repository as a dependency for the qgis package (from qgis repository). After a bit of fiddling around, I found that when I remove libqgis_* files from plugins folder inside the designer installation folder then the error disappears.  

There is more info about the system

 - Virtualization: oracle (VBox 6.0.14 r133895 (Qt5.6.2))
 - Operating System: Debian GNU/Linux 10 (buster)
 - Kernel: Linux 4.19.0-6-amd64
 - Architecture: x86-64
 - QT Designer 5.11.3
 - QGIS 3.10.0-A Coruña
 - QGIS code rev. 6c816b4204

**Comment by gioman** [comment] 2019-12-03 10:22
Duplicate of https://github.com/qgis/QGIS/issues/32860 ?

**Comment by DavidPavlicek** [comment] 2019-12-03 10:28
Yes, it is the same issue...

**Closed** 2019-12-03 10:29 UTC
Labels: Bug, Feedback
