### ISSUE TITLE
Rubberband not working correctly with "Shapes" digtizing in rotated map window 

### ISSUE THREAD

**Issue by bvthomsen** [qgis/QGIS#33287] opened 2019-12-08 21:57 UTC
If you try to digitize a polygon (and other types of objects) using the "Shapes" ditizing tool in a **rotated** map-window the rubberband shows strange geometries. The ordinary digtizing tool works as expected.

Affected version (at least) QGIS v. 3.10 64 bit on windows 8.1

**Comment by gioman** [comment] 2019-12-08 22:03
> using the "Shapes" ditizing tool

@bvthomsen 
is that a 3rd party plugin?

**Comment by bvthomsen** [comment] 2019-12-08 22:21
Not AFAIK. I'm referring to the digitizing tools in a toolbar called "Shape Digitizing toolbar". 

I don't have any plugins installed that contains these functions, so it must be core functionality or a system plugin

**Comment by bvthomsen** [comment] 2019-12-09 09:36
Further examination reveals that the resulting object seem to be geometrically correct even if the rubberbard is screwed up during the digitizing.

**Comment by lbartoletti** [comment] 2020-02-03 08:59
Duplicate of https://github.com/qgis/QGIS/issues/25095
Still present in master

**Closed by lbartoletti** 2020-02-03 08:59 UTC
Labels: Bug, Digitizing
