### ISSUE TITLE
Project is saved without projection even though the default projection is in use.

### ISSUE THREAD

**Issue by blackpeanut19** [qgis/QGIS#33420] opened 2019-12-16 09:17 UTC
**Describe the bug**

When saving a new project without changing it's CRS projection and reopening it, the projection in use is lost.

**How to Reproduce**
![Peek 2019-12-16 09-20_test](https://user-images.githubusercontent.com/15546414/70892553-b273dc80-1fe9-11ea-93c1-e872cb463859.gif)

**QGIS and OS versions**
Ubuntu 16.04
QGIS version | 3.4.14-Madeira | QGIS code revision | QGIS code revision
-- | -- | -- | --
Compiled against Qt | 5.5.1 | Running against Qt | 5.5.1
Compiled against GDAL/OGR | 2.2.2 | Running against GDAL/OGR | 2.2.2
Compiled against GEOS | 3.5.1-CAPI-1.9.1 | Running against GEOS | 3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version | 9.5.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.2 | QScintilla2 Version | 2.9.1
PROJ.4 Version | 492
Active python plugins | MetaSearch; processing; db_manager

**Additional context**
When saving a project, for it to load the CRS projection correctly, it must have the xml entry "ProjectionsEnabled" set to 1. This line is prepared correctly to be written in the current 3.11.0 build, more exactly in the [671st line of qgsproject.cpp](https://qgis.org/api/qgsproject_8cpp_source.html#l00671). But when creating a new project, the QgsProject::clear method is called, which erases all keys set in the line [725](https://qgis.org/api/qgsproject_8cpp_source.html#l00725) of the same file. This key is not written again and the resulting project file once saved will have mentions to it's current crs projection, but not having the "ProjectionsEnabled" key will make the project to not load it's CRS.

Possible one liner fix:
Add the following line in qgsproject.cpp line 776, under the lines that "[reset some default project properties](https://qgis.org/api/qgsproject_8cpp_source.html#l00771)":

`writeEntry( QStringLiteral( "SpatialRefSys" ), QStringLiteral( "/ProjectionsEnabled" ), crs.isValid() ? 1 : 0 );`

**Comment by mstuyts** [comment] 2020-01-31 12:51
I have a similar problem in QGIS 3.10.2 (d4cd3cde5a) on Windows (OSGeo4W). 

Here is a project file that contains the problem:
[testcrs.zip](https://github.com/qgis/QGIS/files/4139236/testcrs.zip)

---
How to reproduce:
- Set the default CRS in QGIS to EPSG:31370
- Create a new project file (this gets the CRS from the default settings, so it's EPSG:31370)
- Add a layer (in my test I added a WMS layer with EPSG:31370 as layer CRS
- Save the project file
- Close QGIS
- Open QGIS
- Open the saved project file
- QGIS asks to select a transformation for the WMS layer between EPSG:31370 and EPSG:4326
- After selecting a transformation, the QGIS project has no longer a projection.

If I do the same without closing and reopening QGIS, the projects CRS is set just fine.

---

In QGIS 3.4.15 (e83d02e274) and QGIS 3.11.0-Master (ee323eb5c1) on Windows (OSGeo4W) the problem doesn't occur for me.

**Comment by roya0045** [comment] 2020-01-31 12:54
The first thing would be to update and see if the problem still occurs. Since @mstuyts said that it did not occur in the latest LTR for him the bug might be fixed already.

**Comment by Pedro-Murteira** [comment] 2022-01-21 17:44
@blackpeanut19 Hello, I can no longer replicate this issue using QGIS 3.22.3, tested on both macOS and Windows 10. Is this still a problem with you?

**Comment by blackpeanut19** [comment] 2022-01-22 08:09
I’m sorry, I no longer work in the project, I can not test this issue.

On 21 Jan 2022, at 18:44, pmurteira ***@***.***> wrote:

﻿

@blackpeanut19<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fblackpeanut19&data=04%7C01%7C%7C76998e0e151747ad94dd08d9dd05aa37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783838680095603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sjq8WpaWFZMKKPZYRgiKiRbg581RR3n2%2FZn2cV1KiwE%3D&reserved=0> Hello, I can no longer replicate this issue using QGIS 3.22.3, tested on both macOS and Windows 10. Is this still a problem with you?

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqgis%2FQGIS%2Fissues%2F33420%23issuecomment-1018726930&data=04%7C01%7C%7C76998e0e151747ad94dd08d9dd05aa37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783838680095603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sI0ESG63q43wYGvsSiKw2pZoqybakf%2Foce6AlSyW3vw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADWTQLXH2PVHN2C56OHDT6TUXGLPRANCNFSM4J3GXUTA&data=04%7C01%7C%7C76998e0e151747ad94dd08d9dd05aa37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783838680095603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wUvjG2Xv9OYXE7tfmvEGsDdcLK5oLoBFwpjzWe9m%2FU8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C76998e0e151747ad94dd08d9dd05aa37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783838680095603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pw44mFTqQ4Oa3pLz3vX%2FKZPMF0x3gLdDpJP9q6RJEcY%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C76998e0e151747ad94dd08d9dd05aa37%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637783838680095603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4xj9b3icYdWn2RJmAFtYeQmV71Q7hfnsJ8nEno6PMRQ%3D&reserved=0>.

**Closed** 2022-01-22 08:27 UTC
Labels: Feedback, Bug
