### ISSUE TITLE
[QGIS] [QGIS-LTR] [macOS] Pyrcc5, syntax error in component code

### ISSUE THREAD

**Issue by palikao** [qgis/QGIS#54199] opened 2023-08-12 07:19 UTC
### What is the bug or the crash?

In QGIS and QGIS-LTR for macOS, since very long time, the component pyrcc5, which is located in QGIS.app>Contents>MacOS>bin or QGIS-LTR.app>Contents>MacOS>bin, has a syntax error in its code.

The problem occurs when QGIS tries to use it, for example when the plugin "plugin-builder" recall it to compile the plugin package. I tested it mainly in this occasion.. But I'm not alone! It's a long time issue!

PyQt are ok.

Workaround: edit pyrcc5 file with TextEdit.app replacing '`dirname $0`/python3.9' with `dirname $0`/python3.9 (removing quotes)

### Steps to reproduce the issue

1. install plugin "plugin-builder"
2. activate it and open it
3. try to compile masks to create a new plugin
4. in the final step, when finishing, the procedure that recalls pyrcc5 fails because of pyrcc5
5. or..
6. simply launch pyrcc5 in Terminal.app

### Versions

All actual versions of QGIS and QGIS-LTR, all previous QGIS and QGIS-LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Also plugin-builder.py, on macOS, has a small syntax bug in its code (but it's only related), and this is the solution:

At lines 474-475-476
cmd = ['/Applications/QGIS.app/Contents/MacOS/bin/pyrcc5', '-o',
                   os.path.join(self.plugin_path, 'resources.py'),
                   os.path.join(self.plugin_path, 'resources.qrc')]

Where QGIS.app can be changed into QGIS-LTR.app

**Comment by agiudiceandrea** [comment] 2023-08-12 10:27
Hi @palikao, thanks for reporting and for sharing your workarounds. Since it seems to me the pyrcc5 issue is a packaging issue of the official QGIS installer for macOS, I think it should be better to report it to https://github.com/qgis/QGIS-Mac-Packager if not already reported. Moreover, the plugin-builder issue should be addressed in the plugin code, so I suggest you to report it to the plugin code reporistory https://github.com/g-sherman/Qgis-Plugin-Builder.

**Comment by palikao** [comment] 2023-08-12 11:32
Ok! I will do those too!
Hope it helps!

**Comment by agiudiceandrea** [comment] 2023-08-12 13:12
Closing, since the issue is not in the QGIS codebase.

**Closed by agiudiceandrea** 2023-08-12 13:12 UTC
Labels: Feedback, Bug, macOS
