### ISSUE TITLE
QGIS Crash when loading a datasource 

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#52343] opened 2023-03-22 10:45 UTC
### What is the bug or the crash?

QGIS Crash with no error message :

![Crash_on_loading_datasource](https://user-images.githubusercontent.com/8614223/226879328-5f5d9714-3464-4c07-88e2-496d041a5149.gif)

I can't reproduce it on a new profile but it happens on newer versions of QGIS (3.28, 3.30, nightly)

Happens only on a blank project.

How can I investigate further?

### Steps to reproduce the issue

1. Launch QGIS
2. Select New project
3. Add Datasource (WMS, Postgres, ...)

### Versions

Version de QGIS
3.28.4-Firenze
Révision du code
fd0fb72ab3
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
changeDataSource
3.1
document_management_system
0.3.2
DPFE
1.3.7
EasyImport
3.4.0
geomapfish_locator
1.3.3
LandSurveyCodesImport
v0.3.0
linking_relation_editor
v1.1.4
nominatim_locator_filter
0.2.4
openlayers_plugin
2.0.0
ordered_relation_editor
0.2.7
ORStools
1.5.2
pg_history_viewer
2.2
PluginLoadTimes
3.0.1
plugin_reloader
0.9.3
qfieldsync
v4.4.8
qgepplugin
1.6.0-rc.4
QgisModelBaker
v6.4.0
trackable_project_files
v1.2.2
wincan2qgep
1.1.0
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2023-03-22 12:50
As you can't reproduce it with a new profile, it's not related to QGIS.
You can try on faulty profile to deactivate all plugins and see if it stills happens.
If you have your profile for a long time, I suggest to start fresh and configure it again

**Comment by elpaso** [comment] 2023-03-27 09:40
> It seems to be a common excuse to blame plugins for bugs. 

It is not an excuse, it's just that we need to know if the problem is in QGIS core or in  a plugin.

> But why are plugins allowed to make such problems?

Because of the nature of the Python bindings, see this old but still valid article for some insight: http://enki-editor.org/2014/08/23/Pyqt_mem_mgmt.html

**Comment by alexbruy** [comment] 2023-11-03 15:15
Closing as issue does not happen with clean profile.

**Closed by alexbruy** 2023-11-03 15:15 UTC
Labels: Bug
