### ISSUE TITLE
Laggy, jumpy behavior when zooming with trackpad on MacBook

### ISSUE THREAD

**Issue by telnet23** [qgis/QGIS#50942] opened 2022-11-19 22:28 UTC
### What is the bug or the crash?

In QGIS 3.16, zooming with the trackpad is smooth. In QGIS 3.22 and QGIS 3.28, zooming with the trackpad is laggy and jumpy. Same issue has been reported by multiple users in https://github.com/qgis/QGIS/issues/49319, but that issue was closed automatically due to inactivity. 

### Steps to reproduce the issue

Zoom with the trackpad on a MacBook.

### Versions

QGIS 3.22 and QGIS 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Same issue has also been reported by multiple users on [Reddit](https://www.reddit.com/r/QGIS/comments/slkmyb/zooming_issues_inaccurate_projections_in_osx_v322/).

**Comment by jef-n** [comment] 2022-11-20 00:00
duplicate of # 49319

**Closed by jef-n** 2022-11-20 00:00 UTC
Labels: Bug
