### ISSUE TITLE
Can't add custom projection in QGIS 3.10 

### ISSUE THREAD

**Issue by thangqd** [qgis/QGIS#33182] opened 2019-12-02 03:05 UTC
Can't add custom projection in QGIS 3.10 . The OK Button does not work!
![custom](https://user-images.githubusercontent.com/1776420/69927642-42def700-14eb-11ea-896f-292cf25c2067.PNG)

**Comment by gioman** [comment] 2019-12-02 08:48
duplicate of https://github.com/qgis/QGIS/issues/33038

**Closed by gioman** 2019-12-02 08:48 UTC
