### ISSUE TITLE
Sentinel 1 data set not working properly

### ISSUE THREAD

**Issue by aludzuweit** [qgis/QGIS#52694] opened 2023-04-14 12:54 UTC
### What is the bug or the crash?

I am trying to work with a crop data set from Zenodo based on Sentinel-1, Sentinel-2 and Landsat 8 data. Here is the link: https://zenodo.org/record/5153047?token=eyJhbGciOiJIUzUxMiIsImV4cCI6MTY4MTUxMzE5OSwiaWF0IjoxNjc4ODg5OTIxfQ.eyJkYXRhIjp7InJlY2lkIjo1MTUzMDQ3fSwiaWQiOjMwOTc1LCJybmQiOiIwMzE4YTg1MCJ9.xwKDUFCc9zqtQGKJqLmcPexQVfq50BiCYik4DTlnEuSvX8LfNZZUsAk3x5Vchjqem3UYxbF5kZTIyKhbopnHUw#.ZDaBqILP1kY
The data set loads slowly. I was able to convert from tif to vector (polygonize) file but when trying to use the dissolve function to aggregate the crop classes, the operation never completed.
If helpful, I can post the Zenodo tif file and the modified shapefile.
Thanks for your attention.
Regards
Anja
aludzuweit@yahoo.de

### Steps to reproduce the issue

Used the following QGIS functions on the data set:
Polygonize
Dissolve

### Versions

Tried to run the file with 2.89 Firenze and V. 3.30.1 Hertogenbusch and ran into the same issue both times.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Nothing else to add here.

**Comment by agiudiceandrea** [comment] 2023-04-15 15:16
@aludzuweit, if I understood correctly, the issue is not about the "Sentinel 1 data set not working properly", but about the Dissolve processing algorithm that "never completed".
Could you please provide the input vector layer you used with the Dissolve processing algorithm and all the parameter used?

**Comment by aludzuweit** [comment] 2023-04-15 19:26
What is the best way to share the files? Here I can only download 25MB zip files but my zip files are 124.5, 589.2 and 92.7MB.

**Comment by aludzuweit** [comment] 2023-04-17 13:50
Hi Andrea how can I share the data? I could share via OneDrive to your Email address. Thanks for letting me know. Anja

**Comment by agiudiceandrea** [comment] 2023-04-17 14:07
@aludzuweit, please provide a public link (using a file share service) to download the whole or a subset of the input vector layer you used with the Dissolve processing algorithm. If the data is not shareable to the public, then you need to wait for a developer that explicitly ask you to share the data privately with him.

In the mean time, you can try to use the "Fix geometry" algorithm in order to fix any error possibly present in the input layer and then use the fixed layer as input of the Dissolve algorithm.

**Comment by aludzuweit** [comment] 2023-04-18 08:17
@agiudiceandrea thank you for your recommendation to retry using the "Fix geometry" algorithm in QGIS. Unfortunately, this has not worked, the dissolve algorithm never completed (ran overnight for > 12 hours). 

Here is the link to the data sets: 

1. Zenodo_Crop_Tif - original raster data set
2. CropData_Rrepoj33N_Vector - polygonized data set and clipped to study area
3. Zenodo_Crop_Dissolve - attempt to dissolve to 9 crop classes but failed

https://we.tl/t-wphWVPXBiU

**Comment by agiudiceandrea** [comment] 2023-04-18 14:07
Your CropData_Rrepoj33N_Vector is a huge 2 GB GeoPackage with more than 4 millions polygons. It could be challenging to dissolve it as a file based layer in a reasonable amount of time. Maybe it would be better using a PostgreSQL/PostGIS server.
Anyway, maybe it would be better also to first reclassify the raster, polygonize the reclassified raster and then eventually just collect the geometries by the reclassified attribute value, instead of polygonize the raster, reclassify the polygonixed vector layer and then dissolve the geometries.

**Comment by aludzuweit** [comment] 2023-04-18 16:17
@agiudiceandrea thank you very much for your recommendation. 
I tried reclassifying the raster using the "Reclassify by table" function under raster analysis in the processing toolbox. However, this has not worked. Here is the table logic I am trying to assign - do you have a recommendation on how I can do this? Apologies for these basic questions:

LU Class | Crop | Associated codes | Gardner Taxonomy
-- | -- | -- | --
1 | Cereal | 31, 32, 33, 34, 41, 42, 43 | Cereal
2 | Rape | 50 | Oilseed rape
3 | Legume | 60, 130, 140, 181, 182 | Broad/field beans, vegetables, peas
4 | Sunflower | 70 |  
5 | Sugar beet | 80 | Sugar beet
6 | Maize | 91, 92 | Maize
7 | Potatoes | 100 | Potatoes
8 | Orchard | 110, 120, 150, 160 | Orchard, Strawberry in poly, Strawberry in open, berries
9 | Other | 555, 999 | NA

**Comment by agiudiceandrea** [comment] 2023-04-19 06:03
I would use the GDAL Raster caclulator with a formula like: `1*(isin(A,[31, 32, 33, 34, 41, 42, 43])) + 2*(A == 50)+ 3*(isin(A,[60, 130, 140, 181, 182])) + 4*(A == 70) + 5*(A == 80) + 6*(isin(A,[91, 92])) + 7*(A == 100) + 8*(isin(A,[110, 120, 150, 160])) + 9*(isin(A,[555, 999]))`. Please use a forum like gis.stackexchange.com or the qgis-user mailing list https://lists.osgeo.org/pipermail/qgis-user/ to post questions.

**Comment by aludzuweit** [comment] 2023-04-20 08:40
Thank you for your help, @agiudiceandrea !

**Comment by alexbruy** [comment] 2023-06-05 12:29
Closing, as tools work correctly it is more related to data.

**Closed by alexbruy** 2023-06-05 12:29 UTC
Labels: Processing, Bug
