### ISSUE TITLE
Georeferencer Freezes QGIS 3.18.0

### ISSUE THREAD

**Issue by tcwyse** [qgis/QGIS#41954] opened 2021-03-01 20:01 UTC
Running 64 bit version of QGIS 3.18.0 on a Windows 10 PC.  The program freezes up after entering GCP points and starting the georeferencing.  It creates a file that I can load after force quitting and restarting QGIS.  The raster is georeferenced, but it's all black.  Georeferencing works fine in 3.16.3.

**Comment by agiudiceandrea** [comment] 2021-03-01 20:46
It seems a duplicate of #41770.

**Closed** 2021-03-02 11:11 UTC
