### ISSUE TITLE
Selection features tools not working on rules based styled layers

### ISSUE THREAD

**Issue by d-lombardi-a** [qgis/QGIS#43273] opened 2021-05-18 10:50 UTC
**Describe the bug**
The following tools aren't working on rules based styled layers:

- ![image](https://user-images.githubusercontent.com/53909185/118635472-eac9ac80-b7d3-11eb-8c28-ae9fcca11099.png)Select Features by area or single click
- ![image](https://user-images.githubusercontent.com/53909185/118635544-01700380-b7d4-11eb-8af8-d6f8ad9b49b5.png)Select Features by Polygon
- ![image](https://user-images.githubusercontent.com/53909185/118635628-1351a680-b7d4-11eb-9fc8-fc4b26d3277b.png)Select Features by Freehand
- ![image](https://user-images.githubusercontent.com/53909185/118635648-1c427800-b7d4-11eb-8c56-7980ca96a181.png) Select Features by Radius

**How to Reproduce**

1. Open a new/existing project
2. Add a layer
3. Define some sort of rule based layer style
4. Trying to select features using one of the above mentioned selection tools fails: no features are being selected.

**QGIS and OS versions**

Versione di QGIS
3.16.5-Hannover
Revisione codice QGIS
58ba7c1ed6
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.1.4
Esecuzione con GDAL/OGR
3.1.4
Compilato con GEOS
3.8.1-CAPI-1.13.3
Esecuzione con GEOS
3.8.1-CAPI-1.13.3
Compilato su SQLite
3.29.0
In esecuzione su SQLite
3.29.0
Versione client PostgreSQL
11.5
Versione SpatiaLite
4.3.0
Versione QWT
6.1.3
Versione QScintilla2
2.10.8
Compilato con PROJ
6.3.2
Esecuzione con PROJ
Rel. 6.3.2, May 1st, 2020
Versione SO
Windows 10 (10.0)
Attiva python plugin
imposta_gruppo_comuni; 
powerpan; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
send2google_earth; 
db_manager; 
processing

**Additional context**
Find attached a .zip file containing sample.gpkg (project (embedded in the gpkg) and data to reproduce the bug). 
[sample.zip](https://github.com/qgis/QGIS/files/6500675/sample.zip)

**Comment by gioman** [comment] 2021-05-18 10:57
@d-lombardi-a Duplicate of https://github.com/qgis/QGIS/issues/42066 ?

**Comment by d-lombardi-a** [comment] 2021-05-18 11:01
> @d-lombardi-a Duplicate of #42066 ?

Yes, it is. Should I close this?

**Comment by gioman** [comment] 2021-05-18 11:07
> Yes, it is. Should I close this?

@d-lombardi-a yes thanks.

**Closed** 2021-05-18 11:08 UTC
Labels: Bug, Feedback, Map Tools
