### ISSUE TITLE
When using atlas and a data override symbol style with the assistant, symbol does not display in the legend unless the coalesce function is removed

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27708] opened 2018-09-18 16:10 UTC
Author Name: **cris c** (cris c)
Original Redmine Issue: [19884](https://issues.qgis.org/issues/19884)
Affected QGIS version: 3.4.1
Redmine category:map_composer/printing

---
I have a project with a soil analysis layer whose dots are colored and size variable depending on the concentration of the element. 
I have set up an atlas based on a table that loops through all the layers (elements). 
The legend for the currently selected atlas item displays correctly if I manually change each symbol size. It does not display a dot at all if the assistant is used to set the data driven override for symbol sizes. It will show the dots, albeit without a change in size, if I change the function from:
coalesce(scale_exp("ChosenElement", 0, 75, 1.5, 3, 0.5), 0)
to 
scale_exp("ChosenElement", 0, 75, 1.5, 3, 0.5)

---

- [assistant set sizes.PNG](https://issues.qgis.org/attachments/download/13312/assistant%20set%20sizes.PNG) (cris c)
- [manually set sizes.PNG](https://issues.qgis.org/attachments/download/13317/manually%20set%20sizes.PNG) (cris c)
- [data set sizes no coalesce.PNG](https://issues.qgis.org/attachments/download/13318/data%20set%20sizes%20no%20coalesce.PNG) (cris c)

**Comment by nyalldawson** [comment] 2019-09-26 05:38
Duplicate of #19761 -- same underlying issue

**Closed by nyalldawson** 2019-09-26 05:38 UTC
Labels: Bug, Print Layouts
