### ISSUE TITLE
Qgis 3.4 crash when closing

### ISSUE THREAD

**Issue by Charlybreizh** [qgis/QGIS#32079] opened 2019-10-01 12:23 UTC
## User Feedback

Qgis crashe quand je ferme le logiciel.
Le problème est moins présent dans Qgis 3.4.12 que dans Qgis 3.4.11 mais continue.
Il semble que le problème arrive le plus souvent quand le composeur de carte est ouvert.
Aucune autre version de Qgis n'est installée sur le PC.

## Report Details

*Crash ID*: b4417c17e4e0afd551fca11b93f09b0325592b2f

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransformPrivate::freeProj qgscoordinatetransform_p.cpp:340
QgsCoordinateTransformPrivate::~QgsCoordinateTransformPrivate qgscoordinatetransform_p.cpp:91
QHashNode<QPair<QString,QString>,QgsCoordinateTransform>::~QHashNode<QPair<QString,QString>,QgsCoordinateTransform> :
QHashData::free_helper :
QHash<QPair<QString,QString>,QgsCoordinateTransform>::clear qhash.h:591
QgsCoordinateTransform::invalidateCache qgscoordinatetransform.cpp:831
QgsApplication::exitQgis qgsapplication.cpp:1211
QgisApp::~QgisApp qgisapp.cpp:1600
QgisApp::`vector deleting destructor' :
main main.cpp:1543
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Gustry** [comment] 2019-10-01 12:27
It's a duplicate of 3 tickets: https://github.com/qgis/QGIS/search?q=b4417c17e4e0afd551fca11b93f09b0325592b2f&type=Issues which are all closed. Wait for the next release.

**Closed** 2019-10-01 12:28 UTC

**Comment by Charlybreizh** [comment] 2019-10-01 12:37
Thanks.
