### ISSUE TITLE
XYZ tiles do not render with QGIS 3.10.2 running on Windows.

### ISSUE THREAD

**Issue by brian-fisher** [qgis/QGIS#34237] opened 2020-02-03 21:31 UTC
**Describe the bug**
QGIS fails to render xyz tiles when running on Windows.  

No errors are shown, but imagery is not displayed.  Projects saved under previous versions do not display imagery from xyz tiles when opened under 3.10 but do display when opened under previous version 3.8.3.  

Open question on GIS stack exchange https://gis.stackexchange.com/questions/349237/problem-with-xyz-tiles-not-rendering-in-qgis-3-10?noredirect=1#comment571848_349237

Image of project created in 3.10.2 with xyz layers added but not rendered on top.  Below is same project opened with 3.8.3.  
![xyz test](https://user-images.githubusercontent.com/36671451/73692300-ec2ba000-4688-11ea-87eb-99a68380ec07.png)

**How to Reproduce**

Project file:
[XYZ_test.zip](https://github.com/qgis/QGIS/files/4150318/XYZ_test.zip)
This works fine and renders in 3.8.3, but no imagery is rendered in 3.10.2.

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 8.1 (6.3)
Active python plugins
batch_gps_importer; 
clipper; 
dataexplorer; 
DataPlotly; 
DigitizingTools; 
GroupStats; 
ImportPhotos; 
joinmultiplelines; 
LocatePoints; 
mmqgis; 
pointsamplingtool; 
profiletool; 
qchainage; 
qgis2web; 
qgsAzimuth; 
quick_map_services; 
rivergis; 
splitmultipart; 
SplitPolygonShowingAreas; 
db_manager; 
MetaSearch; 
processing

**Additional context**

**Comment by gioman** [comment] 2020-02-03 21:34
> Image of project created in 3.10.2 with xyz layers added but not rendered on top. Below is same project opened with 3.8.3.

@brian-fisher what is your project CRS?

**Comment by brian-fisher** [comment] 2020-02-03 21:43
Project CRS is EPSG 2285 (Washington State Plane North in US Feet NAD 83).

I tried changing layer CRS, to no effect, but based on your question I 
tried changing project CRS.  The xyz tiles render when project CRS set 
to EPSG:4326 (WGS84)  or EPSG 6339 (UTM Zone 10N).

**Comment by gioman** [comment] 2020-02-03 21:45
> Project CRS is EPSG 2285 (Washington State Plane North in US Feet NAD 83).

@brian-fisher when reprojecting did you choose to use a transformation based on a NTv2 grid?

**Comment by brian-fisher** [comment] 2020-02-03 21:49
@gioman I did not get any options that asked about transformations.  
Setting project CRS to EPSG:4326 under Project Properties > CRS > select new projection the box under Datum Transformations is blank.

Trying out several options, they render with EPSG: 6597 (NAD 83(2011)/Washington North)

**Comment by gioman** [comment] 2020-02-03 22:02
>  Setting project CRS to EPSG:4326 under Project Properties > CRS > select new projection the box under Datum Transformations is blank.

@brian-fisher you said before that it was 2285. When switching to 2285 from 3857 a transformation dialog indeed shows, but without option to choose one based on a ntv2 grid:

![Screenshot_20200203_215349](https://user-images.githubusercontent.com/1951107/73694795-bca08600-46d0-11ea-8c0f-59fc47781f47.png)

Anyway it seems that those transformations work only if zooming where expected (i.e. Washington state) and not elsewhere.

**Comment by brian-fisher** [comment] 2020-02-03 22:08
@gioman That dialog does not come up for me, perhaps I set a default at some point in the past?  
I've tried several different CRS and found that the layers render fine with some and not others.  EPSG: 6597 is a viable solution for me.

**Comment by gioman** [comment] 2020-02-03 22:10
> That dialog does not come up for me, perhaps I set a default at some point in the past?

@brian-fisher try with a new QGIS profile.

**Comment by brian-fisher** [comment] 2020-02-03 22:20
@gioman With a new QGIS profile, I opened a new project, added OpenStreetMap, then changed to EPSG:2285.  I get three options for transformations.  None of them indicate they are based on a ntv2 grid.  
The options I see are all Inverse of Popular Visualization Pseudo-Mercator + Inverse of NAD83 to WGS84 {here I have options of 41, 1 or 20} + SPCS83 Washington North zone (US Survey Feet)
I would generally select the first one (41) because the accuracy is listed as 1m, and the area of use is Washington as opposed to Idaho and Montana. 
 
![image](https://user-images.githubusercontent.com/36671451/73696074-49771f80-4690-11ea-9a6b-69aba7f35c43.png)

**Comment by gioman** [comment] 2020-02-03 22:33
@brian-fisher I was trying to see if this was the same as https://github.com/qgis/QGIS/issues/34183 but apparently is a slightly different case.

**Comment by brian-fisher** [comment] 2020-02-04 02:06
@gioman It seems like it is probably related, but the behavior described is somewhat different - I cannot get the tiles to render at any scale when the project CRS is set to the ones that don't work, while in the the issue mentioned, there were geographic areas where the tiles rendered.

**Comment by nyalldawson** [comment] 2020-02-04 02:09
Duplicate of #33929 -- the selected coordinate operation does use a limited area grid "WO". If you select the second coordinate operation then things work as expected

**Closed by nyalldawson** 2020-02-04 02:09 UTC
Labels: Bug, Projections/Transformations
