### ISSUE TITLE
3.10.x fails to build with sip4 4.19.23 (sip: core/conversions.sip:1440: %MappedType template for this type has already been defined)

### ISSUE THREAD

**Issue by sebastic** [qgis/QGIS#37098] opened 2020-06-10 11:52 UTC
The Debian package build fails due to the recent update of sip4 to 4.19.23+dfsg-1:
```
[3799/4686  81%]cd /<<PKGBUILDDIR>>/debian/build/python && /usr/bin/cmake -E echo && /usr/bin/cmake -E touch /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart0.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart1.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart2.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart3.cpp && /usr/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -n sip -t WS_X11 -t Qt_5_12_4 -g -o -a /<<PKGBUILDDIR>>/debian/build/python/qgis.server.api -n sip -y /<<PKGBUILDDIR>>/debian/build/output/python/qgis/_server.pyi -j 4 -c /<<PKGBUILDDIR>>/debian/build/python/server -I /<<PKGBUILDDIR>>/debian/build/python/server -I /usr/share/sip/PyQt5 -I /<<PKGBUILDDIR>>/python /<<PKGBUILDDIR>>/debian/build/python/server/server.sip
FAILED: python/server/sip_serverpart0.cpp python/server/sip_serverpart1.cpp python/server/sip_serverpart2.cpp python/server/sip_serverpart3.cpp 
cd /<<PKGBUILDDIR>>/debian/build/python && /usr/bin/cmake -E echo && /usr/bin/cmake -E touch /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart0.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart1.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart2.cpp /<<PKGBUILDDIR>>/debian/build/python/server/sip_serverpart3.cpp && /usr/bin/sip -w -e -x TESTS -x ANDROID -x ARM -x MOBILITY_LOCATION -n sip -t WS_X11 -t Qt_5_12_4 -g -o -a /<<PKGBUILDDIR>>/debian/build/python/qgis.server.api -n sip -y /<<PKGBUILDDIR>>/debian/build/output/python/qgis/_server.pyi -j 4 -c /<<PKGBUILDDIR>>/debian/build/python/server -I /<<PKGBUILDDIR>>/debian/build/python/server -I /usr/share/sip/PyQt5 -I /<<PKGBUILDDIR>>/python /<<PKGBUILDDIR>>/debian/build/python/server/server.sip

sip: core/conversions.sip:1440: %MappedType template for this type has already been defined
```

**Comment by jef-n** [comment] 2020-06-11 08:08
The mapping for ``QVector<_TYPE_ *>`` conflicting with our custom mapping was introduced in PyQt5-5.15.0.   But once that's fixed and actual sip issue pops up:
```
/home/fischer/src/qgis/debian/build/python/server/sip_serverpart3.cpp: In function ‘void assign_QgsRequestHandler(void*, Py_ssize_t, void*)’:
/home/fischer/src/qgis/debian/build/python/server/sip_serverpart3.cpp:1121:115: error: use of deleted function ‘QgsRequestHandler& QgsRequestHandler::operator=(const QgsRequestHandler&)’
 1121 |     reinterpret_cast< ::QgsRequestHandler *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QgsRequestHandler *>(sipSrc);
      |                                                                                                                   ^
In file included from /home/fischer/src/qgis/debian/build/python/server/auto_generated/qgsrequesthandler.sip:22:
../../python/../src/server/qgsrequesthandler.h:38:21: note: ‘QgsRequestHandler& QgsRequestHandler::operator=(const QgsRequestHandler&)’ is implicitly deleted because the default definition would be ill-formed:
   38 | class SERVER_EXPORT QgsRequestHandler
      |                     ^~~~~~~~~~~~~~~~~
../../python/../src/server/qgsrequesthandler.h:38:21: error: non-static reference member ‘QgsServerRequest& QgsRequestHandler::mRequest’, can’t use default assignment operator
../../python/../src/server/qgsrequesthandler.h:38:21: error: non-static reference member ‘QgsServerResponse& QgsRequestHandler::mResponse’, can’t use default assignment operator
```

plus other classes with deleted assignment operators.    Which might be related to a recent sip change:

```
2020-06-04  Phil Thompson  <phil@riverbankcomputing.com>

       * sipgen/gencode.c:
       Check there is a public copy ctor when we can't using an assigment
       operator as a workaround.
       [19026da2a827] <4.19-maint>
```

**Comment by pblottiere** [comment] 2020-06-11 10:39
These issues have already been raised [here](https://github.com/qgis/QGIS/issues/37072).

> plus other classes with deleted assignment operators. Which might be related to a recent sip change:

I proposed a PR to fix these issues (still one thing to tweak though): https://github.com/qgis/QGIS/pull/37116

**Comment by pblottiere** [comment] 2020-06-11 10:42
This ticket is a duplicate so I think we should close it. Do you agree @jef-n?

**Closed** 2020-06-11 12:45 UTC
Labels: Bug, Build/Install

**Comment by jef-n** [comment] 2020-06-12 17:56
Duplicate of #37072
