### ISSUE TITLE
Polyline crash 

### ISSUE THREAD

**Issue by lola25847** [qgis/QGIS#53521] opened 2023-06-20 09:18 UTC
### What is the bug or the crash?

Qgis crash when utilise polyline in new creation page 
## User Feedback

the bug come with polyline 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000006dc (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

create new page 
create polyline 
change color 

## User Feedback

the bug come with polyline 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000006dc (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2023-06-20 17:13
@lola25847, thanks for reporting. Could you please provide a sample layer and exact steps in order to replicate the issue?

**Comment by lola25847** [comment] 2023-06-22 08:37
https://we.tl/t-zXrPtD7PJr 
1- new layout
2- add map 
3 - add label 
4 - add arrow 
5 - change arrow color 
6 - widen arrow line 
7 - do not mark any end of arrow 
8 - export in pdf format 
9 - on the same layout delete arrow 
10 - recreate arrow 
the crash occurs  now

**Comment by nyalldawson** [comment] 2023-10-03 03:26
@lola25847 the project download has expired -- can you attach to this ticket as a zip instead?

**Comment by nyalldawson** [comment] 2023-10-04 04:27
Duplicate of https://github.com/qgis/QGIS/issues/52079

**Closed by nyalldawson** 2023-10-04 04:27 UTC
Labels: Feedback, Bug, Crash/Data Corruption, Print Layouts
