### ISSUE TITLE
QGIS Crashed when defining GRASS location

### ISSUE THREAD

**Issue by cfontm** [qgis/QGIS#31440] opened 2019-08-27 07:21 UTC
This crash happens every time I try to set a GRASS new directory. 
I use QGIS 3.4 but it also happens with 3.8.

The error windows states:

Crash ID: d76ef2dff745d2aba152da6d1350374fbeb23cff

Stack Trace

RtlRaiseStatus :
longjmp :
longjmp :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.4.7-Madeira
QGIS code revision: 5c56989325
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by Gustry** [comment] 2019-08-27 07:29
Duplicate of https://github.com/qgis/QGIS/issues/30317 ?

**Comment by nirvn** [comment] 2019-08-27 07:31
@Gustry , very likely, and the prospect of fixing this abandoned provider is very, very low I'm afraid.

@cfontm , creating/managing GRASS projects through QGIS is not recommended; if you need access to GRASS algorithms, go through processing.

**Comment by gioman** [comment] 2019-08-27 08:18
> and the prospect of fixing this abandoned provider is very, very low I'm afraid.

It does not happen on Linux, so hopefully is not the provider that is completely broken and maybe it "just" a Windows compiling/packing issue.

**Closed by gioman** 2019-08-27 08:18 UTC
Labels: Bug
