### ISSUE TITLE
Saving project in QGIS LTR changes fonts in print layout legend

### ISSUE THREAD

**Issue by myxBeni** [qgis/QGIS#53127] opened 2023-05-16 13:58 UTC
### What is the bug or the crash?

Saving a QGIS project with QGIS LTR (3.28) changes the fonts in the print layout.

### Steps to reproduce the issue

1. create a project with QGIS (3.30)
2. create a print layout from a template
3. save
4. open the project with QGIS LTR (3.28)
5. Do something (here, adding a layer)
6. save
7. Open the project with QGIS (3.30)
8. Open the previously created template
9. Observe the differences in the legend in terms of fonts

![image](https://github.com/qgis/QGIS/assets/109787519/be89166b-3c84-4c09-86e9-fe8fce248125)

![image](https://github.com/qgis/QGIS/assets/109787519/9ebb9544-b49a-46d2-93b5-054c56874da0)

### Versions

QGIS-Version | 3.30.2-'s-Hertogenbosch | QGIS-Codeversion | 0992b53397
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.2
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.11.5
BS-Version | macOS 12.6
  |   |   |  
Aktive Python-Erweiterungen
SpreadsheetLayers | 2.1.0
profiletool | 4.2.6
cartolinegen | 3.2.2
AnotherDXF2Shape | 1.2.7
SentinelHub | 2.0.0
rastertimeseriesmanager | 1.8
poiexport | 3.0.4
qgis2web | 3.16.0
qfieldsync | v4.4.9
geosys-plugin | 1.3.0
slyr | 6.3.1
TerrainShading | 0.9.3
Generalizer3 | 1.0
qlyrx | 0.3.3
VoGisProfilTool | 3.0.2
inundation_calculator | 0.1
qtiles | 1.7.2
concavehull | 2.0
timemanager | 3.6
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS-Version
3.30.2-'s-Hertogenbosch
QGIS-Codeversion
[0992b53397](https://github.com/qgis/QGIS/commit/0992b53397)
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.3.2
PROJ-Version
8.1.1
EPSG-Registraturdatenbankversion
v10.028 (2021-07-07)
GEOS-Version
3.9.1-CAPI-1.14.2
SQLite-Version
3.35.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.11.5
BS-Version
macOS 12.6

Aktive Python-Erweiterungen
SpreadsheetLayers
2.1.0
profiletool
4.2.6
cartolinegen
3.2.2
AnotherDXF2Shape
1.2.7
SentinelHub
2.0.0
rastertimeseriesmanager
1.8
poiexport
3.0.4
qgis2web
3.16.0
qfieldsync
v4.4.9
geosys-plugin
1.3.0
slyr
6.3.1
TerrainShading
0.9.3
Generalizer3
1.0
qlyrx
0.3.3
VoGisProfilTool
3.0.2
inundation_calculator
0.1
qtiles
1.7.2
concavehull
2.0
timemanager
3.6
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2023-05-17 06:48
It's not new that there is compatibility issues from a newer version to an older.
This PR https://github.com/qgis/QGIS/pull/50959 changes behavior of legend texts.

This is a won't fix to me...

**Comment by myxBeni** [comment] 2023-05-17 07:14
Many Thanks! As a context: 
In a productive environment, It would be great to be able to run everything from the latest to the latest LTR version. So if saving a project with the most recent LTR-Version doesn't change the fonts in a layout, that wasn't even touched.

**Comment by nicogodet** [comment] 2023-05-17 08:26
In production environnement, you should stick with one version only.
Maintain compatibility between latest and LTR is too much work. It is always possible to read an old project in a newer version but the opposite is not true and an intended behavior.
See https://github.com/qgis/QGIS/issues/52252#issuecomment-1471807668

**Closed by nicogodet** 2023-05-17 08:26 UTC
Labels: Bug
