### ISSUE TITLE
QGIs mis-labelling CRS authority

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#30099] opened 2019-06-05 15:18 UTC
**Describe the bug**

ESRI (and possibly other) CRS's are being incorrectly labelled as EPSG CRSs - whereas they are correctly labelled upstream in proj. 

This was a QGIS issue, bounced to Proj and now back with QGIS now we can see what's going on: https://github.com/OSGeo/PROJ/issues/1503#issuecomment-499090015

**QGIS and OS versions**

QGIS version | 3.4.6-Madeira | QGIS code branch | Release 3.4
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.0 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 9.6.10 | SpatiaLite Version | 4.4.0-RC1
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by nyalldawson** [comment] 2019-06-05 20:26
This is a "wontfix" in my opinion, unless it's reproducible under 3.8 and proj 6.1.

**Comment by nyalldawson** [comment] 2019-06-05 20:27
Just to further explain: the cause of this is deeply rooted in qgis outdated srs db, and I cannot see anyway to safely alter it without extreme risk to the ltr release.

**Comment by nyalldawson** [comment] 2019-06-11 02:20
Marking this as a wont-fix. Please reopen if still reproducible under the Proj 6.1 based builds.

**Closed by nyalldawson** 2019-06-11 02:20 UTC
Labels: Bug, Projections/Transformations, Won't fix
