### ISSUE TITLE
Problems adding Vector Shape from MYSQL

### ISSUE THREAD

**Issue by javiermateos** [qgis/QGIS#33274] opened 2019-12-06 17:52 UTC
Im currently using QGIS Desktop 3.4.13 and I’m trying to add a vector layer connected with MySQL to my Project. After setting all paramters of database and connecting succesfully, I tried to add some points within the vector layer. When I save changes in the layer I get this  message:

Could not apply changes to MySQL layer: qgis, host = LocalHost, port = 3306 authcfg = 'w6u75gp' points

Errors: ERROR: 1 spatial object has not been added.
Supplier errors:
OGR error when creating object -4: MySQL error message: SRID value is out of range in 'st_geomfromtext' Description: INSERT INTO `points` (` pointscol`, `idpoints`) VALUES (ST_GeomFromText ('POINT (-5.15748180042588 41.4380033714209 ) ', - 2), 5)

I tried to add this SQL sentence into my database through MySQL workbench and it worked after change -2 value to 4326, which is the correct src for my project.  I don’t know why Im getting that value if I properly set my project SRC and vector layer SRC.

Windows Version: Windows 10 Pro
MySQL version: 8.0.18 Community Edition

**Comment by gioman** [comment] 2019-12-06 22:57
duplicate of https://github.com/qgis/QGIS/issues/32275

**Closed by gioman** 2019-12-06 22:57 UTC
