### ISSUE TITLE
[browser] Selecting multiple connections and pressing "delete" only deletes one

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#31926] opened 2019-09-21 15:03 UTC
3.4.12
If you select multiple connections (i.e. several SQLite connections, or several WMS connections), it will only delete one of them.

**Comment by nyalldawson** [comment] 2019-09-21 20:56
Duplicate of #26276

**Closed by nyalldawson** 2019-09-21 20:56 UTC
Labels: Bug, GUI/UX, QGIS Browser
