### ISSUE TITLE
3.18.1-1 MSI installer and start menu shortcuts

### ISSUE THREAD

**Issue by pnrthomp** [qgis/QGIS#42574] opened 2021-03-30 13:18 UTC
Hello,

When I performed a silent installation with the .MSI file, the installer had left out the start menu icons for a few executables, but had added Grass GIS 7.8.5 and OsGEo4W Shell.

Any assistance is appreciated.

Thanks,

Paul T.

**Comment by jef-n** [comment] 2021-06-23 16:10
Duplicate of #43850

**Closed by jef-n** 2021-06-23 16:10 UTC
