### ISSUE TITLE
after merging selected features, which appears successful; edits will not save/commit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29635] opened 2019-04-10 08:45 UTC
Author Name: **Leanne Farrell** (Leanne Farrell)
Original Redmine Issue: [21820](https://issues.qgis.org/issues/21820)
Affected QGIS version: 3.4.6
Redmine category:digitising

---
after digitising new polygons into an existing dataset i want to merge two to make a multipart polygon. This appears successful until I try to commit the changes and get the error 

_Could not commit changes to layer XXX

Errors: ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer._

I have used an alternative GIS to merge and commit this fine and have previously used these tools fine. I updated my QGIS version last week to QGIS version 3.4.6-Madeira

---

- [TEST_TAB.zip](https://issues.qgis.org/attachments/download/14781/TEST_TAB.zip) (Leanne Farrell)

**Comment by SrNetoChan** [comment] 2019-07-11 13:44
I can confirm this behavior. If the user as a single part only layer, that is, not a MULTI layer, the merge tool will allow the user to merge two non-adjacent geometries, but later will fail when the user tries to save it.

Although this may not be considered a bug, it's quite bad in terms of usability and confuses the user, which probably may not remember that the layer is not multi, or does not realize that the geometries are not adjacent. In case of single part layers editing, would be nice if the merge could skip any non-adjacent geometries (or all geometries), and warn the user that not all features were merged because that would generate multi-part features in a single part layer.

**Comment by gioman** [comment] 2021-01-31 16:01
Still true on the latest master.

**Closed** 2022-01-10 06:28 UTC
Labels: Bug, Digitizing
