### ISSUE TITLE
Mesh calculator: flo2D extension is not used to filter folders

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#45257] opened 2021-09-26 22:57 UTC
### What is the bug or the crash?

In the mesh calculator, if you want to select an output file, the flo2D extension is not available for filtering files in the dialog that opens. Selecting another "output format", you get it in the file extension dropdown of the "save as..." dialog.

### Steps to reproduce the issue

Open the mesh calculator dialog
Switch the output format to flo2D and click to select an "output file". Files in the new dialog are not filtered by the flo2D extension. Either you get all the files, either the applied filter is the previously selected output format (you get this if you switched among the output format combobox items)

### Versions

3.21 on windows 10 and ubuntu 20.04 but probably affects earlier releases

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by PeterPetrik** [comment] 2021-09-29 14:34
duplicate of #41943

**Closed by PeterPetrik** 2021-09-29 14:34 UTC
Labels: GUI/UX, Bug, Mesh

**Comment by DelazJ** [comment] 2021-09-29 16:24
@PeterPetrik I'm not sure they are duplicate. The issue here is when you open the file selection dialog (you hit the ... button):
- if a format other than flo2d was selected in output format, it is shown in the extension dropdown of the dialog
- if flo2d was selected, then you get "all files" or the previously used format.
