### ISSUE TITLE
WFS-T post request in QGIS desktop always uses WFS version 1.0.0 (even if I choose a newer version)

### ISSUE THREAD

**Issue by kostergeert** [qgis/QGIS#34608] opened 2020-02-22 15:06 UTC
**Bug Description**
On a WFS-T layer in QGIS, for post requests (if features are inserted/deleted/modified) QGIS uses WFS version 1.0.0, even if we choose a newer WFS version when loading the layer or when it is set to 'maxium'.

This is problematic because I want to make use of certain features that only WFS 1.1.0 or WFS 2.0.0 supports, this is not possible

**How to Reproduce**
Dowload Fiddler in order to see requests generated by QGIS.

In QGIS Settings > Options > Network , setup a HttpProxy with host: 127.0.0.1 and port: 8888

Load in a freely accesible WFS-T (e.g. http://giswebservices.massgis.state.ma.us/geoserver/wfs?)

Try adding/modifying a feature in this WFS-T and check the request generated by QGIS in fiddler.
Getfeature requests use the maximim WFS version available (2.0.0) but post requests use WFS version 1.0.0

**QGIS and OS versions**
QGS version: 3.10.2-A Coruña
OS: Windows 10

**Comment by rouault** [comment] 2020-02-22 18:39
This is expected. WFS-T in QGIS is only implemented for 1.0.0

**Comment by rouault** [comment] 2020-02-22 18:40
Duplicate of https://github.com/qgis/QGIS/issues/24002

**Closed by rouault** 2020-02-22 18:40 UTC
Labels: Feature Request
