### ISSUE TITLE
Crash when using advanced digitizing tools 

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [qgis/QGIS#34037] opened 2020-01-26 13:02 UTC
## User Feedback

exploring advanced digitizing tools to split a layer.

## Report Details

**Crash ID**: [03364e9e53adf4eabab9cb4afbfb527b314295a3]('https://github.com/qgis/QGIS/search?q=03364e9e53adf4eabab9cb4afbfb527b314295a3&type=Issues')

**Stack Trace**
<pre>
QgsLocatorResultsView::selectNextResult :
QgsLocatorWidget::eventFilter :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.0-A Coruña
QGIS code revision: 6c816b4204
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment] 2020-01-26 13:04
>  QGIS Version: 3.10.0-A Coruña

@PauloEduardoCardoso please update to 3.10.2

if the problem persist try with a new QGIS profile, no 3rd party plugins installed.

**Comment by lbartoletti** [comment] 2020-02-10 09:42
Duplicate of https://github.com/qgis/QGIS/issues/33408 ?

**Comment by gioman** [comment] 2020-02-10 09:57
> Duplicate of #33408 ?

seems so, also closing because no feedback was given.

**Closed by gioman** 2020-02-10 09:57 UTC
Labels: Bug, Feedback
