### ISSUE TITLE
Crash - using shape digitizing tools on a raster layer

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#33583] opened 2020-01-02 14:26 UTC
**Describe the bug**

If you use the shape digitizing toolbar (not the plugin) on a raster layer, QGIS crashes.

**How to Reproduce**

1. Load into a new project
   1. a raster layer
   1. a polygon vector layer
1. Select the vector and switch to edit mode
1. Enable the shape digitizing toolbar
1. Select the raster layer
1. Draw a shape with the previously mentionned toolbar
   1. finish your shape with a right click

```
Crash ID: 419df0013f72d85e8071f5ab69345c4623f0fd4c
Stack Trace

QgsPointPatternFillSymbolLayer::hasDataDefinedProperties :
QgsLabelEngineConfigDialog::trUtf8 :
QgsLabelEngineConfigDialog::trUtf8 :
QgsLongLongValidator::QgsLongLongValidator :
QgsLongLongValidator::QgsLongLongValidator :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsPointPatternFillSymbolLayer::hasDataDefinedProperties :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsPointPatternFillSymbolLayer::hasDataDefinedProperties :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsLabelEngineConfigDialog::trUtf8 :
BaseThreadInitThunk :
RtlUserThreadStart :
```

```
QGIS Info
QGIS Version: 3.11.0-Master
QGIS code revision: 0d84e35839
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev
```

```
System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393
```

**Comment by gioman** [comment] 2020-01-02 16:15
Seen also on 3.10.1

**Comment by obrix** [comment] 2020-01-16 11:30
Hi,
I cannot reproduce this bug on 3.11 master. Here is a webm of what I'm doing : [repro_33583](https://s1.webmshare.com/rVyPJ.webm)

![version](https://user-images.githubusercontent.com/19537259/72521524-e138d900-385b-11ea-814b-3e9984471b73.png)

Am I doing something wrong ?

**Comment by gioman** [comment] 2020-01-16 12:43
> Am I doing something wrong ?

not really, but with the specific editing tool you used does also does not crashes on 3.10.1 while if you use the "add rectangle" one it crashes.

**Comment by obrix** [comment] 2020-01-16 12:49
> not really, but with the specific editing tool you used does also does not crashes on 3.10.1 while if you use` the "add rectangle" one it crashes.

Okay that's it indeed, the circle does not crash but the rectangle does I can confirm.

**Comment by elpaso** [comment] 2020-01-23 13:09
@obrix please assign to yourself the bugs you're working on, this will spare some time to other developers.

**Comment by obrix** [comment] 2020-01-23 13:42
I am not able to assign the bugs to myself right now, I'll see if someone can assign them to me.

**Closed** 2020-02-20 09:42 UTC
Labels: Bug, Crash/Data Corruption, Digitizing
