### ISSUE TITLE
loading of a large a geojson datasources is very slow

### ISSUE THREAD

**Issue by Rigonz** [qgis/QGIS#35524] opened 2020-04-02 17:12 UTC
## User Feedback

Crashed while uploading a geojson file (approx 2000 points as features).

## Report Details

**Crash ID**: [bc6171c4b75132534ec4e8ca1e91ecf1c4dfc0ae]('https://github.com/qgis/QGIS/search?q=bc6171c4b75132534ec4e8ca1e91ecf1c4dfc0ae&type=Issues')

**Stack Trace**
<pre>
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
OGRToOGCGeomType :
OGRLayer::FilterGeometry :
sqlite3_extension_init :
QgsSqlExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerLabelProvider::stopRender :
QgsVectorLayerLabelProvider::stopRender :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2020-04-02 22:08
> uploading

@Rigonz uploading where? do you mean _loading_ in QGIS? If yes please attach the dataset here.

**Comment by Rigonz** [comment] 2020-04-03 09:45
@gioman , yes, sorry: I meant loading into QGIS.
The dataset is deleted, I was making tests using the same filenames several times.
Later I noticed that the dataset was corrupted (it was a geojson with which I was playing), but still I think QGIS should had warned (as it normally does) rather than crashing.

**Comment by gioman** [comment] 2020-04-03 10:47
@Rigonz reopen if you can provide a dataset we can use to replicate this issue.

**Comment by tye-shutty** [comment] 2021-07-18 12:42
QGIS crashes when creating and loading a large geojson file.

version: QGIS 3.16.3-Hannover 'Hannover' (94ac9f21b8)
system: Ubuntu 18.04.5

I downloaded statscan's 2016 DA shapefile (56589 features) from [here](https://www12.statcan.gc.ca/census-recensement/alternative_alternatif.cfm?l=eng&dispext=zip&teng=lda_000b16a_e.zip&k=%20%20%20%2090414&loc=http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/2016/lda_000b16a_e.zip). Then I loaded it into QGIS using default settings, exported as geojson using default settings. The file was created but the computer became unresponsive and QGIS crashed after about 2 minutes. The file appears to be error free, as geojson-to-sqlite was able to convert it. Then when loading the geojson file in QGIS, QGIS again crashes.

**Comment by gioman** [comment] 2021-10-12 09:45
> Was it solved somehow? I've got the same issue now (running Hannover LTR as well)
> [0180C3520_Buildings.geojson.zip](https://github.com/qgis/QGIS/files/7327950/0180C3520_Buildings.geojson.zip)

@pasichnyi no crash here loading the datasource you link. Anyway it won't show in QGIS as it is a "Geometry: 3D Geometry Collection".

**Comment by pasichnyi** [comment] 2021-10-13 08:21
OK, sorry, now I got where the confusion came from - for each file with buildings, I have a file with a surrounding environment - e.g. [0180C3520_Walls.geojson.zip](https://github.com/qgis/QGIS/files/7336272/0180C3520_Walls.geojson.zip) in this case. So when I was importing those in bulk, it was actually showing me the wall objects, not buildings.

> it does not support geometry collections
Now I found a [feature request for GeometryCollection](https://github.com/qgis/QGIS/issues/32747), so probably that is the answer. I imported 2D buildings without any issues before, but I've checked those files and realised those were only FeatureCollections. So, naturally it breaks done when facing GeometryCollection.

Excuse for messing things up, and thank you for the help!

**Comment by rouault** [comment] 2022-05-18 21:59
Working interactively with large geojson datasources will always be very slow. There's nothing we can do about that. You have to convert such files to something else (shapefiles, geopackage, etc) before.
Regarding GeometryCollection, this is a duplicate of #32747
so closing

**Closed by rouault** 2022-05-18 21:59 UTC
Labels: Bug, Vectors
