### ISSUE TITLE
Unable to import layers from DWG/DXF

### ISSUE THREAD

**Issue by moadAlami** [qgis/QGIS#55336] opened 2023-11-20 15:00 UTC
### What is the bug or the crash?

In the dialogue menu for importing DWG/DXF packages, the source drawing prompts for gpkg instead of DWG/DWF. It seems that the restrictions for the source drawing and the target package has been flipped, because the target package now requires GPKG.

### Steps to reproduce the issue

1. Go to Project
2. Import/Export
3. Import layers from dwg/dxf..
4. Try to import a dwg or dxf layer.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.5
GDAL/OGR version | 3.7.3
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.44.0
PDAL version | 2.6.0
PostgreSQL client version | 16.0
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
kmltools | 3.1.31
quick_map_services | 0.19.33
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.11
Python version
3.11.5
GDAL/OGR version
3.7.3
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.44.0
PDAL version
2.6.0
PostgreSQL client version
16.0
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Arch Linux

Active Python plugins
kmltools
3.1.31
quick_map_services
0.19.33
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment] 2023-11-20 15:35
@moadAlami 
Duplicate of #55096 fixed in #55153 and the fix will land in QGIS 3.34.1 (https://github.com/qgis/QGIS/pull/55199)

**Closed by DelazJ** 2023-11-20 15:35 UTC
Labels: Bug
