### ISSUE TITLE
I'd like to see units next to band values in the "Identify Results" panel

### ISSUE THREAD

**Issue by MattF-NSIDC** [qgis/QGIS#38159] opened 2020-08-05 16:23 UTC
**Feature description.**
I would like to be able to see the units for each pixel in my raster data when I use the identify tool. In the below example, Vegetation Biomass is a GeoTIFF. The units of each pixel are `kg/m2`. Is there any way we can cause current versions of QGIS to display this unit next to the value in the Identify Results panel, either by changing the GeoTIFF's metadata or by changing a setting in the project file? We think this isn't currently supported right now, but it's not clear if we're just missing something. 

**Additional context**
Here's what we see now, but we would like to see `0.12765 kg/m2` instead.

![image](https://user-images.githubusercontent.com/18539827/89437389-be411a00-d704-11ea-8a23-bf7d2ca53027.png)

**Comment by baswein** [comment] 2020-08-05 17:24
Iam not an athority on this matter but I don't think QGIS knows anything about rasters other than the value and the pixel size and horizontal units. One way this could be achieved is using an raster attribute table functionality that is not currently available. https://github.com/qgis/QGIS/issues/22427#issue-448421618

**Comment by roya0045** [comment] 2020-08-05 18:29
Pixel have arbitrary values, without units. This doesn't make sense.

**Comment by uclaros** [comment] 2020-08-05 21:42
It makes sense  in the way #37805 proposes

**Comment by roya0045** [comment] 2020-08-05 22:18
@uclaros yeah with a user defined suffix yes, though I don't see the use as you can set that in the raster's name, but that's just me. But having qgis know magically what pixel value represents doesn't make sense.

**Comment by alexbruy** [comment] 2020-08-06 11:39
@roya0045 actually it makes sense. GDAL supports setting unit type metadata for raster bands, see #24140. #37805 is a different thing.

**Comment by roya0045** [comment] 2020-08-06 11:59
@alexbruy I didn't know this was possible with GDAL, but this value must be set somewhere. I feel like most users will obtain a raster where this value is not set or gets removed (clipping, raster operation, etc) and then bugs are filled because the value isn't there anymore or doesn't make sense after some processing. Though if its doable for a few cases totally I'm fine with it.

 But we don't want to have users feel like its magic and will always show the proper units.

**Comment by uclaros** [comment] 2020-08-06 12:08
> #37805 is a different thing.

I wonder what @gioman 's use case is other than to display units.

**Comment by gioman** [comment] 2020-08-06 15:05
> I wonder what @gioman 's use case is other than to display units.

@uclaros mine is not other than to display units, but it is a pretty compelling one :)

closing as duplicate of https://github.com/qgis/QGIS/issues/37805


Side note: there is also a clear necessity to have the core identify tool to allow round raster float values (you can have that using the "value tool" plugin, which really should be a core tool).

**Closed by gioman** 2020-08-06 15:05 UTC
Labels: Feature Request
