### ISSUE TITLE
Add option to zoom to extent of saved bookmark in Map composer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29894] opened 2019-05-15 08:20 UTC
Author Name: **Admire Nyakudya** (@NyakudyaA)
Original Redmine Issue: [22081](https://issues.qgis.org/issues/22081)

Redmine category:map_canvas

---
I am using map themes and saving the extent of each map theme as a bookmark. However, when I go to the map
composer I will still need to change the scale to align to the bookmark extent. This is cumbersome when I add multiple maps on the same page
corresponding to a theme. If there was an option to change the extent of a map to align to a bookmark it would make it easier.

---

- [Screenshot 2019-05-15 at 10.13.16.png](https://issues.qgis.org/attachments/download/14946/Screenshot%202019-05-15%20at%2010.13.16.png) (Admire Nyakudya)

**Comment by nyalldawson** [comment] 2019-09-03 19:35
Duplicate of #20279

**Closed by nyalldawson** 2019-09-03 19:35 UTC
Labels: Feature Request, Map and Legend
