### ISSUE TITLE
Basemaps not displaying in projected CRS

### ISSUE THREAD

**Issue by Robinlovelace** [qgis/QGIS#33916] opened 2020-01-20 11:10 UTC
To reproduce, change the CRS of your project to 27700 and open a wms tile service.

In the latest LTR (certainly in 3.2.1 that I just tested it on) you see the tiles:

![image](https://user-images.githubusercontent.com/1825120/72721695-94fbda80-3b74-11ea-851d-991ebbd39545.png)

In the nightly build and, according to @david-laverty in version 3.12.2, the tiles do not dispaly on our machines, as illustrated below.

![image](https://user-images.githubusercontent.com/1825120/72722029-48fd6580-3b75-11ea-85b9-63f95b97d449.png)

A work-around I found is to use a web mercator CRS such as [900913](https://en.wikipedia.org/wiki/Web_Mercator_projection#EPSG:900913).

Can anyone else reproduce this issue?

A handful of people have reported it in https://github.com/qgis/QGIS/issues/30643

**Comment by SteveLowman** [comment] 2020-01-20 12:10
Is this a duplicate of #33154 ?

**Comment by Robinlovelace** [comment] 2020-01-20 12:15
I think so. It's also a duplicate of #30643.

**Comment by Robinlovelace** [comment] 2020-01-20 12:17
@SteveLowman can you reproduce the behaviour?

**Comment by SteveLowman** [comment] 2020-01-20 12:26
In #33154, @david-laverty 10 days ago reproduced the problem in 3.10.1 with proj 7.0.0 and GDAL 3.1.0. I think we need to try again with 3.10.2 and the latest dev versions of proj and gdal libraries. I will try this when I get time.

**Comment by Robinlovelace** [comment] 2020-01-20 12:28
Many thanks. Apologies for duplicating an issue. Did so because it didn't seem anyone was going to re-open the previous issues despite evidence of the bug in recent QGIS issues.

**Comment by david-laverty** [comment] 2020-01-20 12:30
I have tested this with 3.10.2 (OSGeo4W download) this morning and still having the issue with the thin strip of western Scotland only being displayed. I added the images of what I did to https://github.com/qgis/QGIS/issues/33154

**Comment by gioman** [comment] 2020-01-20 13:17
> I think so. It's also a duplicate of #30643.

@Robinlovelace so let's close this one. I understand that https://github.com/qgis/QGIS/issues/33154 is closed, but is not ignored. Let's try to figure what is going on and continue comment there.

**Closed by gioman** 2020-01-20 13:17 UTC
Labels: Bug

**Comment by Robinlovelace** [comment] 2020-01-20 13:21
> Let's try to figure what is going on and continue comment there.

Sounds like a constructive approach, but if other people can reproduce the issue should it not be re-opened? Happy to provide further input/tests to help figure it out, let me know if I can be of further help it at least flagging work-arounds, if not debugging, this issue.
