### ISSUE TITLE
GeoPackage merge with field maps not working

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#55016] opened 2023-10-22 18:36 UTC
### What is the bug or the crash?

I have two `gpkg` with `maps` attribute, launch the `Merge vector layers` and get this error:

```
QGIS version: 3.28.11-Firenze
QGIS code revision: b02458a196
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
Algorithm started at: 2023-10-22T20:23:25
Algorithm 'Merge vector layers' starting…
Input parameters:
{ 'CRS' : QgsCoordinateReferenceSystem('EPSG:3035'), 'LAYERS' : ['D:/GitHub/pop_istat_griglia_chilometrica/output/19.gpkg|layername=grigliapop2021_ita_datiprov','D:/GitHub/pop_istat_griglia_chilometrica/output/20.gpkg|layername=grigliapop2021_ita_datiprov'], 'OUTPUT' : 'ogr:dbname=\'D:/GitHub/pop_istat_griglia_chilometrica/dati/GrigliaPop2021_ITA_DatiProv/BUTTA.gpkg\' table="output" (geom)' }

Using specified destination CRS EPSG:3035
Setting output type to MultiPolygon
Could not create layer ogr:dbname='D:/GitHub/pop_istat_griglia_chilometrica/dati/GrigliaPop2021_ITA_DatiProv/BUTTA.gpkg' table="output" (geom): Unsupported type for field maps
Execution failed after 0.03 seconds

Loading resulting layers
Algorithm 'Merge vector layers' finished
```

### Steps to reproduce the issue

1. Load in QGIS 3.28 two gpkg attached;
2. run Merge vector layers algorithm
3. I get error.

[output.zip](https://github.com/qgis/QGIS/files/13064193/output.zip)

## OSGeo4W 64b WIN 10 PRO
```
Versione di QGIS
3.28.11-Firenze
Revisione codice QGIS
b02458a196
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009




Plugins Python attivi
AcATaMa
23.4
DataPlotly
4.0.3
felt
1.1.0
kmltools
3.1.31
Label On Off
0.1
latlontools
3.6.15
layer2kmz
1.5.3
nominatim_locator_filter
0.2.4
OpenAndFilterAttributeTable
0.1
osminfo
0.7.1
processing_r
3.1.1
profiletool
4.2.6
qconsolidate
1.1.0
qgis-raster-attribute-table-plugin-bugfix-gh16
1.0
Qgis2threejs
2.7.1
qmapshaper
0.8.2
QuickOSM
2.2.3
quick_map_services
0.19.33
redLayer
2.2
SelectionFilter
1.0
soar
1.0.2
StyleLoadSave
1.0
valuetool
3.0.17
wbt_for_qgis
1.0.9
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The same gpkg are seamlessly merged into the current master

**Comment by nyalldawson** [comment] 2023-10-23 01:21
I can't reproduce on master -- can you confirm that this is fixed?

**Comment by agiudiceandrea** [comment] 2023-10-23 06:11
@pigreco, it seems the issue has been fixed by @elpaso with PR https://github.com/qgis/QGIS/pull/52774 since QGIS 3.32.0 but the fix was not backported to the release-3_28 branch.

**Comment by pigreco** [comment] 2023-10-23 06:23
> I can't reproduce on master -- can you confirm that this is fixed?

I wrote in the additional contest that the problem doesn't exist in the master, but in the current LTR it doesn't work.

**Comment by pigreco** [comment] 2023-10-23 06:24
I confirm that it works in 3.32!

**Comment by agiudiceandrea** [comment] 2023-10-23 22:43
Fixed by https://github.com/qgis/QGIS/pull/55023.

**Closed by agiudiceandrea** 2023-10-23 22:43 UTC
Labels: Feedback, Data Provider, Bug
