### ISSUE TITLE
Data source manager's inner window shrinks when opening it for a second time

### ISSUE THREAD

**Issue by IngaSchl** [qgis/QGIS#33318] opened 2019-12-10 14:56 UTC
When opening the data source manager for a second time (after closing it once), the inner window of the input screen shrinks relative to the data source manager's outer window.
Only when adjusting the size of the outer window, the inner one adapts and shows its full extent.

![qgis](https://user-images.githubusercontent.com/18262383/70540521-b5904800-1b65-11ea-9c67-326478d45d53.PNG)

**Comment by elpaso** [comment] 2019-12-10 15:09
This is a duplicate, which QGIS version is affected?

**Comment by IngaSchl** [comment] 2019-12-10 15:50
sorry for replicating... affected is version 3.10

**Comment by elpaso** [comment] 2019-12-10 16:04
would you please check this version and see if that works? https://github.com/qgis/QGIS/suites/350685733/artifacts/629024 (just unzip it in a temp folder and run QGIS.exe)

**Comment by elpaso** [comment] 2019-12-10 16:05
... it's a zip inside a zip, so unzip it twice :)

**Comment by IngaSchl** [comment] 2019-12-11 06:47
works perfectly!

**Comment by elpaso** [comment] 2019-12-11 06:54
Ok, thanks for checking, next diagnostic step would be to test an official nightly build from master branch.

**Comment by elpaso** [comment] 2019-12-11 10:24
Duplicate of #32615 btw

**Comment by alexbruy** [comment] 2020-04-19 14:08
Works fine in master

**Closed by alexbruy** 2020-04-19 14:08 UTC
Labels: Bug, GUI/UX
