### ISSUE TITLE
GPS Information - BUG

### ISSUE THREAD

**Issue by umayakuy** [qgis/QGIS#48483] opened 2022-05-07 02:45 UTC
### What is the bug or the crash?

In QGIS 3.24.2 the utility GPS Information doesn't work, always in RED.
RECENTER does't work correctly, moves other place of GPS data.

In old QGIS 3.21.1 works fine all.

### Steps to reproduce the issue

Enable GPS Information Panel
Press CONNECT
Press RECENTER

### Versions

3.24.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment] 2022-06-03 06:18
More information is required here, as that functionality is working in other setups.

**Comment by mhnplm** [comment] 2022-07-20 14:27
Quick status indicator shows RED
but position is correct, see picture
[GPS-issue-48483.txt](https://github.com/qgis/QGIS/files/9150723/GPS-issue-48483.txt)
![GPS-issue-48483](https://user-images.githubusercontent.com/14727804/180007166-3e1a296d-0903-4b09-810e-a8a2430ab01d.png)
e

**Comment by umayakuy** [comment] 2022-07-20 21:39
Yes values of position are right, but if you click on *RECENTER *doesn't
work, in the map goes to 0,0 coordinate
In older versions of QGIS, worked fine the indicator is GREEN and map goes
to the right position, that's the BUG, that even in the last version 3.26.1
have the same error.
RECENTER doesn't work for map use in my location, The strange thing is
that the value of *Altitude* i have: *nan m * (i think the bug start's
there).

**Comment by mhnplm** [comment] 2022-07-21 07:34
Then we have the same problem. I'm running on a Ubuntu laptop, could that be a problem, it has not been before?

**Comment by umayakuy** [comment] 2022-07-21 17:57
I have tested in Ubuntu 20.04 LTS, 22.04 LTS. Windows 10, 11 the bug is in
all systems. In older versions RECENTER worked fine, it was a great, useful
tool. I reported this bug in the new versions, but I think nobody is
interested or uses this tool now.

**Comment by mhnplm** [comment] 2022-08-25 13:11
Has it something to do with the information in the field Signal quality, which shows [ unknown -1 ] ?

**Comment by nyalldawson** [comment] 2022-08-28 03:31
Should be fixed by https://github.com/qgis/QGIS/pull/49911

**Comment by DanaisM** [comment] 2022-09-16 08:41
I have the same bug. In Bialowieza version the light is red and cursor failure when recenter. In Buenos Aires version even if the light is green the cursor failure when recenter ! the cursor drops to thousands of km !
This is a bug certainly very annoying for the users.

**Comment by nicogodet** [comment] 2022-09-16 08:43
Which point release ?
3.22.11 and 3.26.3 ?

**Comment by DanaisM** [comment] 2022-09-16 08:48
yes i have tried both

**Comment by nicogodet** [comment] 2022-09-16 12:32
I tried 3.22.9 and I reproduce the issue but it is fixed in 3.22.11

**Comment by mhnplm** [comment] 2022-09-16 13:10
I can confirm, it works for me  on 3.22.11 (Ubuntu) and 3.26.3 (Windows)

Well done, developers!

Den fre 16 sep. 2022 kl 14:32 skrev Nicolas Godet ***@***.***

**Comment by DanaisM** [comment] 2022-09-16 13:46
I use a Galaxy Book 12 pro with windows 10 and 3.22.11 export me in gulf of Guinea when I make a "recenter" from France....I think it's not exactly the good issue.

**Comment by nicogodet** [comment] 2022-09-16 13:51
@DanaisM In info panel, displayed coordinates are ok ? And recenter goes to 0;0 in lat/long coordinates ?

I had this issue in 3.22.9 but fixed in 3.22.11

**Comment by umayakuy** [comment] 2022-09-16 14:28
I can confirm too, it works fine in 3.26.3
Thanks for the atention mhnplm, and good work for the developers!!

Greetings from El Alto, Bolivia (South America)

**Comment by DanaisM** [comment] 2022-09-16 16:14
> @DanaisM In info panel, displayed coordinates are ok ? And recenter goes to 0;0 in lat/long coordinates ?
> 
> I had this issue in 3.22.9 but fixed in 3.22.11

In info panel even when light green, coordinates are not displayed. After recenter none also. There is no satellites bars, But i have satellites connection, for example when i use geoportail my location is good.

**Comment by nicogodet** [comment] 2022-09-16 16:51
If no coordinates are displayed, it seems normal that recenter fails...
It seems you have another issue.

Closing this as completed.

**Closed by nicogodet** 2022-09-16 16:51 UTC
Labels: Feedback, Bug, GPS
