### ISSUE TITLE
Unicode is not rendered properly when placement mode is changed to "Curved"

### ISSUE THREAD

**Issue by nbaghm** [qgis/QGIS#40044] opened 2020-11-14 05:41 UTC
when I want to display labels and set placement method to **Parallel**, the text is rendered without any issues,
![image](https://user-images.githubusercontent.com/4522358/99140624-6fd0df00-2654-11eb-87d2-686639a25faf.png)
 the text is rendered correctly:
![image](https://user-images.githubusercontent.com/4522358/99140635-8840f980-2654-11eb-9553-118af2cebb36.png)
 However, when I change the placement method to **Curved**, the letters are parted, which they supposed to be merged as displayed in the above image;
![image](https://user-images.githubusercontent.com/4522358/99140664-c6d6b400-2654-11eb-83d6-38d3006d2fab.png)

the text is rendered incorrectly:
![image](https://user-images.githubusercontent.com/4522358/99140674-da821a80-2654-11eb-85fc-ec1a2a677ac8.png)

**Comment by nbaghm** [comment] 2020-12-24 18:44
Still this issue exist in the new updated version.

**Comment by nyalldawson** [comment] 2021-05-21 03:13
Duplicate of #21940

**Closed by nyalldawson** 2021-05-21 03:13 UTC
Labels: Bug, Labeling
