### ISSUE TITLE
QGIS consistently crashes while doing simple raster calculation

### ISSUE THREAD

**Issue by mudomau** [qgis/QGIS#32858] opened 2019-11-14 10:42 UTC
Im trying to extract some raster data using the Raster calculator. 

The formula is: (Raster>=10)*Raster, but even just "(Raster>=10)" crashes it.

It worked a couple of times, but since then every time I try to it just closes QGIS suddenly. It doesnt even show the usual "QGIS closed unexpectedly" window.

Working in Windows 10 with QGIS 3.10. The raster is a 1mx1m DEM.

**Comment by gioman** [comment] 2019-11-14 10:45
@mudomau duplicate of https://github.com/qgis/QGIS/issues/32855 ?

**Comment by mudomau** [comment] 2019-11-14 22:06
Possible. I thought it could be an issue with my raster, but as per https://github.com/qgis/QGIS/issues/32855#issuecomment-553909877 and https://github.com/qgis/QGIS/issues/32855#issuecomment-553960140 I uninstalled OSGeo4W, reinstalled 3.10 and 3.8 and tried again - 3.10 failed with the same issue, but 3.8 managed with no problem.

**Comment by gioman** [comment] 2019-11-15 08:38
@mudomau see https://github.com/qgis/QGIS/issues/32855#issuecomment-554263187

**Comment by nyalldawson** [comment] 2019-11-26 01:26
Closing as duplicate of  #32855

**Closed by nyalldawson** 2019-11-26 01:26 UTC
Labels: Bug, Crash/Data Corruption, Feedback
