### ISSUE TITLE
python exception on startup after update from QGIS 3.14.15-4 to 3.14.15-5/6 

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#38483] opened 2020-08-28 10:28 UTC
After update from QGIS 3.14.15-4 (1ce3875163) to QGIS 3.14.15-5 (175d1d2f3a) / QGIS 3.14.15-6 (4e804a0ae3) with OSGeo4W 64bits, I can't start QGIS with some plugins installed, like **First Aid** plugin from @wonder-sk 

Simply, if I run qgis-rel-dev in OSGeo4W shell, the splash screen shows up untill "Restoring loaded plugins" and it crashes without any message.

Removing First Aid, if I have **Crayfish** plugin installed, I get

```
An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded 
Traceback (most recent call last):
  File "C:/Users/PedroVenancio/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 38, in 
    import pyqtgraph
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 794, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
RecursionError: maximum recursion depth exceeded

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.15-Pi Pi, 4e804a0ae3 
```

In this case, QGIS starts.

Without First Aid or Crayfish, QGIS starts, but with this message in a window or in the status bar:

```
An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 738, in check_str
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.14.15-Pi Pi, 4e804a0ae3 
```

This seems something recent, as it does not happened with QGIS 3.14.15-4.

**Comment by gioman** [comment] 2020-08-29 18:08
I see the message
```

RecursionError: maximum recursion depth exceeded 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
RecursionError: maximum recursion depth exceeded
```

while starting QGIS master (osgeo4w) on Windows, but not 3.14 or 3.10, on clean Windows 10 machine.

**Comment by gioman** [comment] 2020-08-29 18:08
Possibly this should be filed in the osgeo4w tracker (too)?

**Comment by PedroVenancio** [comment] 2020-08-31 21:58
@jef-n QGIS 3.14.15-4 was fine here, this issue started only with QGIS 3.14.15-5, and affects QGIS 3.14.15-6 and QGIS 3.14.15-7.

So, it seems that should be something related to one of these commits:

- Fix range of date time values for animation export dialog - https://github.com/qgis/QGIS/commit/1ce3875163c58d9fa5a98652636a66d28b37e5cc 

- windows: map python PATH changes to Add/RemoveDllDirectory https://github.com/qgis/QGIS/commit/84dd67580789c53708f49448a6f54c870c0381a7 

- Make relation reference in filter work again https://github.com/qgis/QGIS/commit/175d1d2f3a85137ab72a7aafdcd3f04d3181b449

**Comment by skampus** [comment] 2020-09-04 07:33
Hi this error is also in QGIS dev.

An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 738, in check_str
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.15.0-Master Master, f5ce5773e1 

Python Path:
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGEO4~1\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by skampus** [comment] 2020-09-04 07:34
ciao, this error is present also in my QGIS dev, just installed, via OSGeo4W

An error has occurred while executing Python code: 

RecursionError: maximum recursion depth exceeded while calling a Python object 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 777, in _import
    new_path = os.environ['PATH']
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 744, in encodekey
    return encode(key).upper()
  File "C:\OSGEO4~1\apps\Python37\lib\os.py", line 738, in check_str
    if not isinstance(value, str):
RecursionError: maximum recursion depth exceeded while calling a Python object


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.15.0-Master Master, f5ce5773e1 

Python Path:
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGEO4~1\apps\gdal-dev\pymod3\lib\site-packages
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGEO4~1\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGEO4~1\bin
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by pigreco** [comment] 2020-09-04 19:33
> ciao, this error is present also in my QGIS dev, just installed, via OSGeo4W

 I confirm!!!

**Comment by nicogodet** [comment] 2020-09-13 07:26
I got this error when installing 3.14.16 (it was OK on 3.14.15).
I had to create a new profile to be able to start Qgis otherwise on default profile with a bunch of plugin, it didn't even start at all.

**Comment by amr66** [comment] 2020-09-14 12:50
Same here, 3.10.10 can't start processing plugin, started qgis-ltr with a clean profile

**Comment by jef-n** [comment] 2020-09-15 09:50
Duplicate of #38720

**Closed by jef-n** 2020-09-15 09:50 UTC
Labels: Bug, Build/Install, Feedback
