### ISSUE TITLE
Label masking and composer export bug

### ISSUE THREAD

**Issue by eprouteau** [qgis/QGIS#50543] opened 2022-10-13 16:17 UTC
### What is the bug or the crash?

Context : Hiking map with a lot of labels (lakes, peak, saddle, places, ...) and OSM road network.

labels have an active mask property on the road network.

When the Label masking property is activate on road network, an export with composer taker very long time or crash. When the property is disable no problem.

A try on qgis 2.22.4 and there is no problems

### Steps to reproduce the issue

Label masking property enable on all label layer and active on road network. Composer export bug

### Versions

2.26.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment] 2022-10-14 07:23
Could you share a project with sample data?

**Comment by C4pT4in0bvi0u5** [comment] 2022-10-31 23:17
Yes, tried with v3.28, and it will now export (to PNG, PDF, and printer) after disabling the text mask on the Sections layer. The project file is posted above, so feel free to experiment on your own with it.

**Comment by C4pT4in0bvi0u5** [comment] 2022-11-02 17:26
@troopa81 My project file is posted over on issue #50734 and produces the same symptoms.

**Comment by agiudiceandrea** [comment] 2022-11-02 18:55
On Windows 10, the issue doesn't occur using QGIS 3.22.12, while it does using QGIS 3.28.0 and the latest QGIS 3.29.0-Master (2a3cdfd4c5).

**Comment by C4pT4in0bvi0u5** [comment] 2022-11-02 22:50
Issue also occurs with QGIS 3.26.

**Comment by troopa81** [comment] 2022-11-03 18:10
> On Windows 10, the issue doesn't occur using QGIS 3.22.12, while it does using QGIS 3.28.0 and the latest QGIS 3.29.0-Master (https://github.com/qgis/QGIS/commit/2a3cdfd4c52e312967b23d48219be7852fb485ce).

I imagine it's related to #47459 which appears on 3.26. In 3.22, the result must be fully rasterized even if you select the option full vector when exporting. 

@C4pT4in0bvi0u5 You can disable the full vector export options, it would certainly work and you'll have your masks, but the result will be fully rasterized. 

Thanks for the project sample and data, I'll try to take a look at it when I get the time (not quite soon I'm afraid).

**Comment by C4pT4in0bvi0u5** [comment] 2022-11-04 22:22
@troopa81 I don't see any "rasterize" or "vector" options when printing from layout or exporting to PNG. So not sure what exactly you're talking about. I seem to remember a "vector" setting for PDF somewhere, but this is not a problem that is limited to PDF.

Doesn't matter anyway, because there is clearly a problem in 3.26 and up. Just use 3.22.12 if you want something that works. Trying to find workarounds seems pointless to me.

**Comment by troopa81** [comment] 2022-11-07 08:08
> Doesn't matter anyway, because there is clearly a problem with printing/exporting in 3.26 and up. Just use 3.22.12 if you want something that works. Trying to find workarounds seems pointless to me.

There is clearly an issue, but I would like to be sure it's only related to export with full vector option (see this [comment](https://github.com/qgis/QGIS/issues/50785#issuecomment-1302517105)) and it's the same issue than #50785

Are you sure that you have the issue when you export in PNG ? If yes, could you please share the stacktrace when it crashes!

**Comment by agiudiceandrea** [comment] 2022-11-07 14:33
> Are you sure that you have the issue when you export in PNG

Yes, the issue occurs exporting in PNG.

**Comment by C4pT4in0bvi0u5** [comment] 2022-11-08 06:50
@troopa81 I'm sure.

> Are you sure?

**Comment by MarcelFernandesCGEO** [comment] 2022-11-24 11:34
Hi!
Any news on this issue?
I have the same problem. Just disable the option to mask the labels so that the export in any format works again.
QGIS 3.24.3 works fine, but 3.26.x and 3.28.x fail.
The maps I export have many layers and generate large files, so it's difficult to get the error log (stracktrace) when QGIS crashes.

**Comment by troopa81** [comment] 2022-11-28 16:04
> Any news on this issue?

Yes, like I said in this [comment](https://github.com/qgis/QGIS/pull/49302#issuecomment-1329345869), and contrary to what I thought, there is no way to have a full raster-only rendering, and the vector way of rendering selective masking is very slow. 

I try to find a solution to this.

**Comment by syntax42** [comment] 2022-12-03 11:58
I too seem to have run into this problem. When using label masking and exporting as raster file, i sometimes get the crash (without any error popping up). It seems to be an intermittent issue, so maybe related to memory handling? If needed i can help test any bug fix or provide more details on the problem.

**Comment by CharlesGag** [comment] 2022-12-15 13:38
I have the same issue, map size goes from 3MB to 98.6MB. If I mask additional layers with my unique mask, it crashes while exporting.

**Comment by tdeboss** [comment] 2023-04-10 17:16
Are there any news on this very annoying bug, that practically renders inusable a great deal of Qgis?

**Comment by jsehner** [comment] 2023-04-10 18:22
Same for us, a big cartographic agency in Germany: selective masking is a great feature of QGIS, but we have to stay at version 3.22 to export the maps in a raster format. In future hopefully also in vector format. Would be great to see progress with this bug.

**Comment by troopa81** [comment] 2023-04-25 07:49
Hi @tdeboss  and @jsehner I'm well aware about this issue and I don't fortget it. However, I fail to find time to improve things here. 

If you're interested in funding you can contact me here : julien dot cabieces at oslandia dot com

Otherwise, I'll try to fix it in the next QGIS bugfix round

**Comment by agiudiceandrea** [comment] 2024-01-17 18:18
See also: https://github.com/qgis/QGIS/issues/55874.

**Comment by oskarlin** [comment] 2024-02-29 09:53
How's it going with this? This problem is still very annoying since I still have to use 3.24.3 in order to export images from QGIS. It's been over two years now.

**Comment by troopa81** [comment] 2024-02-29 14:19
I failed to find the time to work on this in the previous bug fix round.

**Comment by oskarlin** [comment] 2024-03-07 13:10
> I failed to find the time to work on this in the previous bug fix round.

I emailed you the other day to see if you could get an estimate on fixing this. Did you get it?

**Comment by zoran-cuckovic** [comment] 2024-05-13 09:21
Hello, 
Same problem here, with 3.34 version. When label masking is turned on both map composer exports and screenshot exports hang for 10 minutes or so. The output is broken, transparency seems to be reverted to 0%, in spite of layer symbology settings.  
It took me quite a while to discover the cause of the problem - this issue is probably affecting a large number of users who may be unaware of the cause.

**Comment by FeroS66** [comment] 2024-05-14 10:33
Long time problem(s). Several time closed "because no activity in thread".
I have to use QGIS 3.22 for output.

**Comment by oskarlin** [comment] 2024-05-14 10:50
Maybe we could go together and finance this? @troopa81 is interested to help out.

**Comment by agiudiceandrea** [comment] 2024-05-14 11:09
> Several time closed "because no activity in thread"

This issue repor was never been closed.

**Comment by C4pT4in0bvi0u5** [comment] 2024-05-17 08:14
> > Several time closed "because no activity in thread"
> 
> This issue repor was never been closed.

So although zero meaningful progress has been made on this MAJOR bug in the past 19+ months, we can still find time to argue about irrelevant details. Brilliant.

As this render issue leaves the entire QGIS program pretty much unusable...perhaps if the great minds of science can't fix the problem, maybe there could be a code regression introduced in order to bring back export functionality?

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-23 05:53
QGIS v3.38.0 is confirmed working. Thank you for fixing this huge bug!

**Comment by nyalldawson** [comment] 2024-06-23 22:43
@C4pT4in0bvi0u5 

You should try switching to the new geometry based backend, which will give much better results on QGIS 3.38+ (and MUCH better results on 3.38.1, when that's released.)

From the Python console enter:

    QgsSettings().setValue('map/mask-backend', 'geometry')

**Comment by troopa81** [comment] 2024-06-24 07:15
> QGIS v3.38.0 is confirmed working. Thank you for fixing this huge bug!

All modifications brought recently by @nyalldawson are non default, so I'm wondering how it could actually work.

I'm hesitating at closing this, because I think the issue still exists. @nyalldawson What do you think?

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-24 07:32
Took a bloody long time, but it completed the render, gave me a usable file, and didn't crash.

To be fair, as there has been basically no activity on this bug for the last 2 years, I had no reason to check every QGIS version that came out. I've been using the known-working 3.22.12 version. So perhaps the crashing issue was fixed before now?

**Comment by nyalldawson** [comment] 2024-06-24 10:26
@C4pT4in0bvi0u5 can you confirm you tried with the qsettings switch to the new backend?

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-25 00:12
Trying v3.38.0RC again today, and it's back to it's old tricks. Crashes after 2 minutes.

- Tried the Python switch mentioned above, still crashes.
- Uninstalled, reinstalled, tried again without the switch. Still crashes.
- Tried a lower (96 dpi) resolution render, still crashes.

When it worked yesterday, the progress bar on the bottom of the QGIS window showed grey (0% complete) throughout the operation. Today when it doesn't work, the progress bar is blue (100% complete) throughout the operation. Not sure if this means anything, but it's just something I noticed.

The big mystery is: why did it work yesterday?

Here's the project I used (slightly more refined version of the last one I posted):  [temp QGIS project 2.zip](https://github.com/user-attachments/files/15962599/temp.QGIS.project.2.zip)

**Comment by nyalldawson** [comment] 2024-06-25 00:21
@C4pT4in0bvi0u5 did you see my question?

**Comment by nyalldawson** [comment] 2024-06-25 00:27
@C4pT4in0bvi0u5 can you try with the build from  https://github.com/qgis/QGIS/pull/57839#issuecomment-2185334188 ?

Here's a (realtime!) screen recording of exporting the layouts from your sample project using that build:

file:///home/nyall/Videos/Peek%202024-06-25%2010-25.mp4

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-25 00:36
> @C4pT4in0bvi0u5 did you see my question?


> * Tried the Python switch mentioned above, still crashes.
> * Uninstalled, reinstalled, tried again without the switch. Still crashes.

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-25 05:35
- Launched "backport" QGIS version from [https://github.com/qgis/QGIS/pull/57839#issuecomment-2185334188)]
- QGIS promptly crashed.
- Launch attempted again. QGIS loads successfully. Information message that "Plugin MetaSearch" has been disabled because it previously crashed QGIS.
- Loaded the project posted above (temp QGIS project 2).
- Attempted rendering to PNG image, 600 dpi. Render successful, usable file produced.
- Opened Python console (Plugins menu -> Python console), entered the command "QgsSettings().setValue('map/mask-backend', 'geometry')".
- Attempted rendering to PNG image, 600 dpi. Render successful, usable file produced.

**Comment by C4pT4in0bvi0u5** [comment] 2024-06-26 00:48
Tried with a different map project today, and both rendering methods function properly (new/old backends).

Render times between the 2 methods are very similar to each other, new geometry method maybe 3-5% faster.

The important thing is that everything seems to work. That's a win, IMHO.

**Comment by est987** [comment] 2024-07-24 07:16
I have been having this issue for a while, and managed to isolate it to issues with the mask feature.
When labels with mask intersect small number of features only transparency fails. Rendering time becomes extremely slow and eventually crashes when label masks intersect with many features. 

Most simple scenario:

New project using QGIS LTR 3.34.8:
Created a simple polygon with transparency set to 50%, with label on edge.
With  mask enabled on label:
![Layout 1](https://github.com/user-attachments/assets/a3842ad1-a6a0-4257-b481-4931a56731a1)
With mask disabled on label:
![Layout 2](https://github.com/user-attachments/assets/c1c3f0c2-6b95-472b-92e9-5849efc1506d)
Transperency set at 50% for both examples.

**Comment by nyalldawson** [comment] 2024-07-24 07:25
@est987 please test with 3.38.1 -- these issues should be resolved. Please open a new issue if you can still reproduce on 3.38.1

**Closed by nyalldawson** 2024-07-24 07:25 UTC
Labels: Labeling, Regression, Bug, Crash/Data Corruption, Print Layouts

**Comment by est987** [comment] 2024-07-24 08:13
Reproduced issue also in 3.38.1:
https://github.com/qgis/QGIS/issues/58230
