### ISSUE TITLE
Zonal statistics no longer offers option to alter zone layer (supposedly fixed with request #29504)

### ISSUE THREAD

**Issue by NickLanzer** [qgis/QGIS#45208] opened 2021-09-22 16:17 UTC
### Feature description

In versions 3.14 and earlier, Zonal Statistics wrote statistics to file/layer chosen in "Vector layer containing zones". This was "fixed" in version 3.16 so that a new layer is created every time Zonal Statistics is run. Some uses of Zonal Statistics rely on the iterative additions of ZS to the same input layer, which is no longer possible (or easily achieved). Please give the OPTION to either A) alter the input zone layer or B) create a new layer. Removing option A entirely with the "FIX" renders Zonal Statistics nearly useless for some applications.

**Comment by gioman** [comment] 2021-09-22 16:20
@NickLanzer duplicate of https://github.com/qgis/QGIS/issues/40400 ?

**Comment by NickLanzer** [comment] 2021-09-22 16:25
You're right, it is a duplicate, though I'm not sure I understand the
resolutions discussed in thread #40400.

**Closed** 2021-09-22 16:26 UTC
Labels: Feedback, Feature Request
