### ISSUE TITLE
Unable to start freshly installed QGIS

### ISSUE THREAD

**Issue by NulAsh** [qgis/QGIS#32674] opened 2019-11-06 01:24 UTC
## User Feedback

Installed and started QGIS. It was immediately unexpectedly ended

## Report Details

**Crash ID**: [042c02325df936f12805a24a81439429ada8f46a]('https://github.com/qgis/QGIS/search?q=042c02325df936f12805a24a81439429ada8f46a&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
QgsTask::~QgsTask qgstaskmanager.cpp:45
QgsNetworkContentFetcherTask::~QgsNetworkContentFetcherTask qgsnetworkcontentfetchertask.cpp:38
QgsNetworkContentFetcherTask::`vector deleting destructor' :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QCoreApplication::processEvents :
QgisApp::QgisApp qgisapp.cpp:1202
main main.cpp:1344
WinMain mainwin.cpp:170
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: c86ed789bf
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by roya0045** [comment] 2019-11-06 18:42
duplicate of #32662

**Closed** 2019-11-07 17:34 UTC
Labels: Bug
