### ISSUE TITLE
QGIS 3.8.1 - Crashes when opening a file

### ISSUE THREAD

**Issue by Claudia500** [qgis/QGIS#31216] opened 2019-08-12 20:11 UTC
Hi,

I am having problems with QGIS 3.8.1. Installation was ok but it crashes when I try to open a file.

Any suggestion?

Here goes the message:

Crash ID: 3e69c3831f81060df4dfecd083df63ac8ed58120

Stack Trace

RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CoGetTreatAsClass :
CoRevokeInitializeSpy :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoGetTreatAsClass :
CoRevokeInitializeSpy :
CoRevokeInitializeSpy :
CoRevokeInitializeSpy :
IIDFromString :
IIDFromString :
SHBindToParent :
Ordinal866 :
AssocCreateForClasses :
Ordinal791 :
Ordinal791 :
Ordinal791 :
Ordinal791 :
Ordinal791 :
Ordinal893 :
StgMakeUniqueName :
Ordinal791 :
Ordinal904 :
DuplicateIcon :
DuplicateIcon :
SHFree :
DllCanUnloadNow :
RtlGetNtProductType :
RtlFreeUnicodeString :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by gioman** [comment] 2019-08-12 20:43
Try with a new/clean QGIS profile.

**Comment by nyalldawson** [comment] 2019-08-12 21:02
Past similar reports have been caused by other installed software (not QGIS). It's unfortunately a local issue which can't be fixed by the QGIS project.

**Closed** 2019-12-21 09:42 UTC
Labels: Bug, Feedback
