### ISSUE TITLE
Automatic classification of singleband pseudocolor uses wrong class breaks/range

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#43346] opened 2021-05-22 12:03 UTC
**Describe the bug**
The automatic classification of a singleband pseudocolor style gives different results depending on which band was styled beforehand. It seems like the class breaks are kept from the previous band or something.

**How to Reproduce**

1. Load the grib file from https://www.dwd.de/DE/leistungen/gribdaten/grib_beispiel_01.zip?__blob=publicationFile&v=2 (I noticed the bug before on a multiband TIFF, it is probably format agnostic)
2. Switch to a singleband pseudocolor style
3. Iterate through the bands using the dropdown going band 1 -> 2
4. Band 2 will be displayed with a range of about -3 to 16
5. Iterate through the bands using the dropdown going band 3 -> 2
6. Band 2 will be displayed with a range of about -99800 to 123000

It does not matter if the min/max value settings are set to "estimate" or "actual".

I made a video where I scrolled the mousewheel on the dropdown. You can see the resulting class breaks and visualisation depends on from which directing I select band 2.

https://user-images.githubusercontent.com/7661092/119225749-08fe1800-bb06-11eb-978a-36217d567d35.mp4

**QGIS and OS versions**

QGIS version | 3.19.0-Master | QGIS code revision | 9da78ed2e4a
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0dev-9f57a8d3c5-dirty
PROJ version | 8.0.1
EPSG Registry database version | v10.018 (2021-04-02)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.5
PostgreSQL client version | 13.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.12.1
OS version | Arch Linux

**Comment by gioman** [comment] 2021-05-23 08:40
> * Iterate through the bands using the dropdown going band 1 -> 2
> 
> * Band 2 will be displayed with a range of about -3 to 16
> 
> * Iterate through the bands using the dropdown going band 3 -> 2
> 
> * Band 2 will be displayed with a range of about -99800 to 123000

@kannes can't confirm the described behavior here (QGIS master on Ubuntu 20.04). The range for band 2 is the same regardless of going from 1 to 2 or 3 to 2.

**Comment by kannes** [comment] 2021-05-25 13:52
The displayed min max values right below the band dropdown or also the bands used in the color classification? I can reproduce it in 1d17bf5bd3 on Ubuntu as well as on my other systems.

**Comment by gioman** [comment] 2021-05-25 13:53
> The displayed min max values right below the band dropdown or also the bands used in the color classification?

@kannes both

**Comment by vcloarec** [comment] 2021-05-30 00:52
I reproduce the same behavior as @kannes  with master and  kubuntu 20.04

**Comment by agiudiceandrea** [comment] 2021-05-30 15:43
I can confirm the reported behaviour with QGIS 3.19.0-Master 89484a3f on Windows (MingW64 Windows 64bit Build) and with QGIS >= 3.14 (OSGeo4W installers).

QGIS 3.10.14 and 3.12.3 don't show the reported behaviour.

This is a screen cast of the behaviour with QGIS <= 3.12.3:

https://user-images.githubusercontent.com/16253859/120110608-7517f600-c16e-11eb-8c89-5cc1157a5b3f.mp4

**Comment by vcloarec** [comment] 2021-05-30 19:26
This issue seems to be here from a long time ago... 
Seems to come from : https://github.com/qgis/QGIS/pull/36376

**Comment by vcloarec** [comment] 2021-05-31 02:09
could be fixed by https://github.com/qgis/QGIS/pull/43455

by the way, I found the rendering of this file nicer as mesh layer :smile:

![grib](https://user-images.githubusercontent.com/7416892/120130083-5415cc00-c193-11eb-8ff0-26bd234b89fe.gif)

**Comment by agiudiceandrea** [comment] 2021-05-31 10:10
@vcloarec the issue is fixed when using the docked Layer Styling panel with the "live update" option checked.

Anyway I see a different behaviour using the docked panel with the "live update" option not checked or using the Symbology panel in the Layer Properties window: the Min / Max values don't change when the band is changed so the classification doesn't change unless you click on the Apply button.
Is this an expected behaviour? It seem a bit strange to me...

https://user-images.githubusercontent.com/16253859/120177543-d7bdd000-c208-11eb-9560-215ef63a8f0c.mp4

**Comment by vcloarec** [comment] 2021-05-31 13:44
@agiudiceandrea , I think it is not a bug but a feature :) .
Indeed, while the button apply is not clicked, the band change is not applied an derived changes are not here until application of this change. But maybe I am wrong here of how the good behavior has to be...
In any case, the behavior is the same as before the regression, so I want to say it is another subject.

**Closed** 2021-05-31 21:06 UTC
Labels: Bug, Raster, Regression, Symbology

**Comment by kannes** [comment] 2021-06-01 17:49
Thanks everyone!
