### ISSUE TITLE
Processing/GRASS is broken in QGIS 3.10 LTR on Windows standalone installer

### ISSUE THREAD

**Issue by PCdurham** [qgis/QGIS#34721] opened 2020-02-27 08:38 UTC
**Describe the bug**

GRASS processing tools seem to be incorrectly installed in 3.10 LTR.  None work. The GUI appears and the user can set parameters, but processing aborts.  The error message is not informative.

Same issues were not present in 3.4 LTR

**How to Reproduce**
Open RGB image; Extract a band; try any tool.  For example, i.segment or r.texture.  Process runs through the motions, but no results.  Similarly, create a vector and try v.to.rast.  Again no result.

 the process runs blank.
 
**QGIS and OS versions**
3.10 LTR and Win 10 OS

**Additional context**

Worked fine in 3.4 LTR.  There are older posts about similar bugs.  But I was hoping 3.10 LTR would have these sorted.

**Comment by gioman** [comment] 2020-02-27 09:38
@PCdurham is working here without issues using the osgeo4w installer. Are you using the standalone one?

**Comment by PCdurham** [comment] 2020-02-27 09:48
Yes I was.  Will try OSGEO4W installer today.
Thanks

**Comment by gioman** [comment] 2020-02-27 10:30
I confirm that GRASS/Processing is broken in the standalone installer of 3.10.3, works on osgeo4w.

No issues on 3.4.15 so regression.

**Comment by PCdurham** [comment] 2020-02-27 10:54
Sorry if I'm not familiar with development protocol, but what are the next steps and recommendations?  Will a new 3.10 LTR be released or will this bug only be fixed when 3.16 becomes LTR on 2020-10-23?  Should users needing GRASS processing regress to 3.4.15 until then?  I ask because I'm about to get my University to do a campus wide update of QGIS.  I was going to ask for 3.10 LTR, but perhaps best use 3.4.15 for the next 12/18 months?
thanks

**Comment by gioman** [comment] 2020-02-27 11:03
@PCdurham there will be plenty of 3.10 point releases in the upcoming weeks/months (3.10.4,5,6,...) where this can be solved.

**Comment by jef-n** [comment] 2020-02-27 11:35
grass still depends on proj_6_2.dll.  Should also affect the standalones of 3.12.   Dependency added in OSGeo4W - new standalones upcoming.

**Comment by gioman** [comment] 2020-02-27 13:00
>  Dependency added in OSGeo4W - new standalones upcoming.

@jef-n thanks! closing?

**Comment by murr2** [comment] 2020-02-27 13:38
Hello. I'm new to reporting bugs re QGIS, so please forgive me if I'm doing it wrong - thanks.

The problem I'm finding is that GRASS7 isn't performing processes on DEM files.  The modules activate and run but fail to do anything.

I've seen it described on web (and here) and it seems this isn't a new problem but there are conflicting messages.

I've installed QGIS ltr, QGIS 3.10 and now 3.12.0 via OSGeo4W - this last one also as standalone. All behave in exactly the same way:  a log error tells me the 3 grass dlls  (which are in the correct folder) failed to load because they can't be found.  All of the various grass dlls are in the correct and same folders as they were in an older standalone installation of 2.8 (which worked well).
What I did notice when I moved the 3 dlls - grassplugin7.dll, grassprovider7.dll and grassrasterprovider7.dll to C:\OSGeo4W\bin - the log error message disappeared but this didn't fix GRASS7.
I wiped everything clean and installed again so many times it's made me dizzy!  I've deleted the Windows appdata roaming profiles and I've completely removed qgis 2.18 and gone through the windows registry.

Observation: in the menu "Plugins" - 'managed and installed' only "processing" is shown (in old qgis it showed grass - and in old qgis it showed up on a drop down menu and - it had a toolbar).
In qgis 3.12.0 under the drop down of "Help" - "Plugins" is listed with a small black arrow - clicking this does nothing.

Sorry to have written a short essay! - but as I've spent days on trying to fix it thought it might be helpful.  By the way QGIS is a great program have used it for LiDAR and minor things (for archaeology) for several years.  Am trying to learn more about the processing side.

**Comment by gioman** [comment] 2020-02-27 13:43
> The problem I'm finding is that GRASS7 isn't performing processes on DEM files. The modules activate and run but fail to do anything.

@murr2 are you speaking about the QGIS-GRASS plugin or the GRASS tools from the QGIS Processing toolbox?

If you are using the first I strongly suggest you to start using GRASS from the Processing toolbox, the QGIS-GRASS plugin hasn't seen much attention lately and is possible/likely that something is not working. On the other hand the same GRASS tools are working OK in the Processing toolbox and you don't have the hassle to need to take care of GRASS locations/mapsets.

**Comment by murr2** [comment] 2020-02-27 15:20
Hi gioman - thank you for your quick response. My problem is with the **Processing toolbox** in qgis - r.basin r.watershed - those modules.  SAGA works fine.
I've not come across the QGIS-GRASS plugin - the only other GRASS I know about is the command prompt one - and I've not tried any processing with it - just started it up (OK) and exited - that one has the location/mapset hassle - which I did use in qgis with grass in 2.18.

**Comment by gioman** [comment] 2020-02-27 15:22
> Hi gioman - thank you for your quick response. My problem is with the **Processing toolbox** in qgis - r.basin r.watershed

@murr2 attach the data you want to process and the parameters you use.

**Comment by murr2** [comment] 2020-02-27 15:50
Hi Gioman,  Thank you.  Am a bit busy at present so will send the file etc. later on tonight.
And I'll re-do and check the file etc. because it's one I used earlier.  There is a projection issue when I load it (am not too good on that).  More later - thanks for your time...

**Comment by edurojasr** [comment] 2020-02-27 17:47
hello everyone

Just I encountered this problem, yesterday install 3 times QGIS 3.10.3 and 3.12, via OSGeo4W GRASS in Processing Toolbox works, however, the plugin is not, here the error message: 

WARNING Failed to load C:/OSGeo4W64/qgis/apps/qgis/plugins/grassplugin7.dll (Reason: Cannot load library C:-OSGeo4W64-qgis-apps-qgis-plugins-grassplugin7.dll: Cannot-find the specified module.)

WARNING Failed to load C:/OSGeo4W64/qgis/apps/qgis/plugins/grassprovider7.dll (Reason: Cannot load library C:-OSGeo4W64-qgis-apps-qgis-plugins-grassprovider7.dll: Cannot-find the specified module.)

WARNING Failed to load C:/OSGeo4W64/qgis/apps/qgis/plugins/grassrasterprovider7.dll (Reason: Cannot load library C:-OSGeo4W64-qgis-apps-qgis-plugins-grassrasterprovider7.dll: Cannot-find-specified module.)

If i check the folders, I can see the .dll files are there so...
I suppose it should be related, according to the recommendation @gioman it is better to start using GRASS from Processing?

**Comment by gioman** [comment] 2020-02-27 17:49
> according to the recommendation @gioman it is better to start using GRASS from Processing?

yes. The GRASS plugin is abandoned.

**Comment by edurojasr** [comment] 2020-02-27 21:41
Thanks @gioman I understand

**Comment by gioman** [comment] 2020-02-28 11:21
> new standalones upcoming.

@jef-n where the new standalone installers already uploaded and available in the download page? Thanks.

**Comment by jef-n** [comment] 2020-02-28 11:35
> @jef-n where the new standalone installers already uploaded and available in the download page? Thanks.

no

**Comment by degreiff** [comment] 2020-04-22 14:48
Hello, this is my first post here, it will be a little long,
I am a teacher, BASIC to intermediate GIS, the students are in their houses do to quarentine, each one instaled QGIS 3.10 in its own computer.
I creater a module to work hydrology tools Using GRASS in the Process Tool Box, and half of the students report issues running the r.wateshed module whit the next warning (shortened), "... does not contain a  valid set of GRASS 7 modules ..."
Some of the syudents hace reintaled QGis but get the same result.
Shollud they change to an older verson.

Thank you

**Comment by PCdurham** [comment] 2020-04-22 15:50
I would say yes. I have had no issues with version 3.4.15. Grass and Saga
work and I've been able to install the Orfeo toolbox without issue as well.

Good luck

**Comment by gioman** [comment] 2020-04-22 16:16
> I creater a module to work hydrology tools Using GRASS in the Process Tool Box, and half of the students report issues running the r.wateshed module whit the next warning (shortened), "... does not contain a valid set of GRASS 7 modules ..."

@degreiff 

did they run QGIS using the shortcut that says "With GRASS"?

**Comment by edurojasr** [comment] 2020-04-22 16:23
One thing that can help and that certainly helped me solve my problems with QGIS installations is to install it through the OSGeo4W Network Installer (advance) in this way I was able to solve my problems with GRASS and QGIS and as @gioman say using "QGIS with GRASS"

**Comment by degreiff** [comment] 2020-04-22 16:28
Thanks @PCdurham , @gioman , @edurojasr .
I will check all your usefull sugestions with the students.

**Comment by gioman** [comment] 2020-04-22 16:30
> I am a teacher, BASIC to intermediate GIS, the students are in their houses do to quarentine, each one instaled QGIS 3.10 in its own computer.

@degreiff just tested the latest 3.10 standalone installer on a clean Win 10 machine, GRASS/Processing is ok.

**Closed** 2020-07-31 19:36 UTC
Labels: Bug, Feedback, High Priority, Regression
