### ISSUE TITLE
gdal polygonize fails with "No module named '_gdal'. message

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#40801] opened 2020-12-30 16:33 UTC
**Describe the bug**

Running Raster -> Conversion -> Polygonize fails.  The log contains the exception  ModuleNotFoundError with message "No module named 'osgeo._gdal'"
Handling this exception produces another with message "No module named '_gdal'.

**How to Reproduce**

Load a raster.
Use menu Raster -> Conversion -> Polygonize
Choose raster as input layer and click Run

**QGIS and OS versions**

The error appears in 3.10.13.  It is not in 3.10.8.

QGIS version | 3.10.13-A Coruña | QGIS code revision | 311f3bbade
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | plugin_reloader; QSWAT3; QSWAT3_64; QSWATPlus3_64; remotedebug; db_manager; MetaSearch; processing

**Additional context**

**Comment by roya0045** [comment] 2020-12-30 16:45
duplicate of #40764 ?

**Comment by ChrisWGeorge** [comment] 2020-12-30 17:02
#40764 is a different OS as well as a different version of QGIS.  It reports a message that is only a secondary consequence of my first message.  So it may be related, but I don't know.

**Comment by roya0045** [comment] 2020-12-30 17:04
Root cause may still be the same regardless of platform and version. If it's a dependency issue it's the same thing.

**Comment by gioman** [comment] 2020-12-30 17:33
>  Handling this exception produces another with message "No module named '_gdal'.

@ChrisWGeorge I cannot replicate on my testing machines (clean Windows 10 machines), both with the osgeo4w installers or the standalone ones. The OS in in English, with the latest 3.10 and 3.16.

Can you test on a different machine?

**Comment by roya0045** [comment] 2020-12-30 17:44
I don't think the c++ port was in 3.10, from the sound of it its the python version and its simply a dependency conflict with your other python environments. @gioman you won't be able to replicate it as its a local issue.

**Comment by gioman** [comment] 2020-12-30 17:47
If is a local issue we will close this @ChrisWGeorge for this is necessary to test on a different machine.

**Comment by ChrisWGeorge** [comment] 2020-12-30 17:48
Tried on another machine and the error disappeared.  Please close it and accept my apologies.

**Comment by gioman** [comment] 2020-12-30 17:50
> my apologies.

@ChrisWGeorge 
none needed. There are many factors in play... sometimes is QGIS fault, other is not.

**Closed** 2020-12-30 17:50 UTC
Labels: Bug, Feedback, Processing
