### ISSUE TITLE
Split feature doesn't trigger default widget expression

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS#30164] opened 2019-06-11 02:05 UTC
**requires more testing to confirm**

It seems if you have a default field expression set as "Apply default value on update" it only applies to the new side of the split feature.

![image](https://user-images.githubusercontent.com/381660/59238338-12f01e80-8c41-11e9-8066-5767cdd213d2.png)

An example was splitting a property should update the area field for both (Yes could use virtual fields for that but seems update default on update should trigger here?)

**Comment by gioman** [comment] 2019-06-11 08:54
@NathanW2 duplicate of https://github.com/qgis/QGIS/issues/29683 ?

**Comment by m-kuhn** [comment] 2019-06-12 10:57
> It seems if you have a default field expression set as "Apply default value on update" it only applies to the new side of the split feature.

Apparently it's the other way round: it only applies to the old side of the split feature and the new side keeps the old value.

**Closed** 2019-06-13 05:01 UTC
Labels: Bug
