### ISSUE TITLE
Feature request: Make a new layer filter based on expressions

### ISSUE THREAD

**Issue by TNogatz** [qgis/QGIS#56957] opened 2024-03-25 00:22 UTC
### Feature description

It would be great if it would be possible to filter layers based on expressions. So it would be possible to create filters based on variables, for instance filter a layer by user name to show only the areas of interest to the user - especially in QField projects for teams. 
See also https://gis.stackexchange.com/a/212605 and https://github.com/qgis/QGIS/issues/56927

**Comment by nyalldawson** [comment] 2024-03-25 00:33
Duplicate of https://github.com/qgis/QGIS/issues/24662

**Closed by nyalldawson** 2024-03-25 00:33 UTC
Labels: Feature Request
