### ISSUE TITLE
Cannot see Model Output in batch process configuration of Model 

### ISSUE THREAD

**Issue by neonntt** [qgis/QGIS#37978] opened 2020-07-27 06:57 UTC
**Describe the bug**
Graphical Modeler. If there is only one output of the entire Model, it does not show in the ‘Run as batch Process’ settings configuration page, thereby unable to select its output file name and location. If there are multiple outputs, one of them does not get displayed in the ‘Run as batch Process’. 

**How to Reproduce**

1. Create a Graphical Model which gives a Model output
2. Run the Model
3. Select the Run as batch Process
4. In the settings page of Run as batch Process, the Model Output is not available as a column to select and feedin its settings.

**QGIS and OS versions**

QGIS version
3.14.0-Pi
QGIS code revision
9f7028fd23
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing
[GM - Copy.pdf](https://github.com/qgis/QGIS/files/4980432/GM.-.Copy.pdf)

**Additional context**

**Comment by gioman** [comment] 2020-07-27 09:30
Confirmed on master too.

**Comment by nyalldawson** [comment] 2020-07-30 22:29
Duplicate of https://github.com/qgis/QGIS/issues/38054

**Closed by nyalldawson** 2020-07-30 22:29 UTC
Labels: Bug, Modeller, Processing, Regression
