### ISSUE TITLE
No Print dialog or Page Setup dialog in macOS

### ISSUE THREAD

**Issue by sl8tech** [qgis/QGIS#30791] opened 2019-07-18 12:48 UTC
**Describe the bug**

No Print dialog appears. No Page Setup dialog appears.

**How to Reproduce**

1. New Print Layout
2. Click Print
3. Brief flash of a progress bar in the Status bar then nothing
4. Similarly no Page Layout dialog, except there is no progress bar.

**QGIS and OS versions**

macOS 10.11.6 El Capitan  QGIS 3.4.9 and 3.8.0
**Additional context**

No meaningful log messages
Export to PDF works fine.

**Comment by nyalldawson** [comment] 2019-07-18 20:13
Which macos builds/installer are you using?

**Comment by sl8tech** [comment] 2019-07-19 07:57
Hi,

Thanks for responding. The installer is the one downloaded from https://qgis.org/downloads/macOS/

macOS 10.11.6

For 3.4:

QGIS version
3.4.9-Madeira
QGIS code branch
Release 3.4 <https://github.com/qgis/QGIS/tree/release-3_4>
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.1-CAPI-1.11.0
Running against GEOS
3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version
9.6.10
SpatiaLite Version
4.4.0-RC1
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
520
Running against PROJ
5.2.0


For 3.8:

QGIS version
3.8.0-Zanzibar
QGIS code branch
Release 3.8 <https://github.com/qgis/QGIS/tree/release-3_8>
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.1-CAPI-1.11.0
Running against GEOS
3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version
9.6.10
SpatiaLite Version
4.4.0-RC1
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
OS X El Capitan (10.11)



Hope this helps.

Chris

**Comment by nyalldawson** [comment] 2019-07-19 08:01
Please try the alternative builds from https://qgis.org/downloads/macos/

**Comment by sl8tech** [comment] 2019-07-19 10:48
This isn’t going well!

Another machine running macOS Sierra and 3.8.0 shows exactly the same behaviour.

I’ve tried:
qgis_ltr_final-3_4_7_20190424_062817
and 
qgis_ltr_final-3_4_8_20190528_075201

Neither of these will even start up, console message is:

19/07/2019 11:35:38.910 com.apple.xpc.launchd[1]: (org.qgis.qgis34.409312[3744]) Service exited with abnormal code: 1

Any further suggestions?

Chris

**Comment by saberraz** [comment] 2019-07-19 11:33
I think, you have better luck upgrading to the latest version of macOS (Mojave) or at least High Siera.

**Comment by alexbruy** [comment] 2020-05-01 13:03
Probably the same as #26423.

**Comment by gioman** [comment] 2020-07-06 15:30
> I think, you have better luck upgrading to the latest version of macOS (Mojave) or at least High Siera.

@saberraz this is still valid using macOS Catalina and QGIS 3.14.0

**Comment by PeterPetrik** [comment] 2020-09-17 13:56
unable to reproduce with nightly2 https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200917_044804.dmg

all works as expected. 

![Screenshot 2020-09-17 at 15 55 39](https://user-images.githubusercontent.com/804608/93480906-4454a100-f8fe-11ea-80e6-193927cacc0b.png)

**Comment by PeterPetrik** [comment] 2020-09-17 13:57
@sl8tech  can you retest please with https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200917_044804.dmg

**Comment by gioman** [comment] 2020-12-21 16:06
Closing for lack of further feedback.

**Closed by gioman** 2020-12-21 16:06 UTC
Labels: Bug, Feedback, MacOS, Print Layouts

**Comment by inega** [comment] 2021-09-09 13:05
Currently having a similar issue using QGIS 3.18.3-Zurich on a Centos8 Linux distribution. The Layout properties window does not appear at all. The Page setup does show up, but I can't change the page size/properties and I get this warning on the terminal:

Warning: QPageSetupDialog: Cannot be used on non-native printers
