### ISSUE TITLE
QGIS crashes on Save As

### ISSUE THREAD

**Issue by Griffonaus** [qgis/QGIS#32239] opened 2019-10-14 06:39 UTC
Trying to save the project using Save As. System freezes immediately. This also happens with release 3.8.

## User Feedback

Trying to save the project using Save As. System freezes immediately. This also happens with release 3.8.

## Report Details

*Crash ID*: 2b5b8847e4fda81698b56c97b7805166938c74fd

*Stack Trace*
<pre>
RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2039
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.12-Madeira
QGIS code revision: 625767347a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-10-14 09:44
@Griffonaus Please try with a new/clean QGIS profile, and  no 3rd party plugins installed.

**Comment by Griffonaus** [comment] 2019-10-14 09:49
Hi Giovanni. I have tried clean installs of both 3.4 ltr and 3.8. I have removed all qgis references in User accounts. I have cleared the registry. I have rebooted between uninstall and installs. I have tried to install on other drives as well.Sent on the go with Vodafone
-------- Original message --------From: Giovanni Manghi <notifications@github.com> Date: 14/10/19  20:14  (GMT+09:30) To: qgis/QGIS <QGIS@noreply.github.com> Cc: Griffonaus <griffonaus@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [qgis/QGIS] QGIS crashes on Save As (#32239) @Griffonaus Please try with a new/clean QGIS profile, and  no 3rd party plugins installed.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/qgis/QGIS/issues/32239?email_source=notifications\u0026email_token=AHAVHKRSRDM6KQTKJCZEFETQOQ5P3A5CNFSM4JALE6BKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBD6ESY#issuecomment-541581899",
"url": "https://github.com/qgis/QGIS/issues/32239?email_source=notifications\u0026email_token=AHAVHKRSRDM6KQTKJCZEFETQOQ5P3A5CNFSM4JALE6BKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBD6ESY#issuecomment-541581899",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gioman** [comment] 2019-10-14 09:52
> I have removed all qgis references in User accounts

sure? what folders have you removed?
To be sure just use the QGIS "new profile" functionality, and try again.

**Comment by DelazJ** [comment] 2019-10-14 10:24
>To be sure just use the QGIS "new profile" functionality, and try again.

https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by Griffonaus** [comment] 2019-10-14 10:44
Same issue. Qgis-ltr-bin.exe has stopped working.

**Comment by nirvn** [comment] 2019-10-14 10:48
This is an OS-level issue, not a bug in QGIS' code itself. That said, there's a plan being formulated to work around this OS-level crasher, it'll hopefully be in by QGIS 3.10.1 (in a little over a month).

**Comment by Griffonaus** [comment] 2019-10-14 10:51
Cool thanks. It is a little strange. It had ben working fine previously. I just upgraded from previous version.


Sent from an archaeological site somewhere

**Comment by nirvn** [comment] 2019-10-14 10:52
@Griffonaus , can you think of any other programs you'd have installed alongside upgrading QGIS?

**Comment by Griffonaus** [comment] 2019-10-14 10:57
I haven’t installed any other software recently. Certainly everything is working fine for those applications. The only thing would have been Win 10 updates in the last two months, and possibly anti-virus update.

Sent from an archaeological site somewhere

**Comment by gioman** [comment] 2020-04-27 10:01
Closing as duplicate of https://github.com/qgis/QGIS/issues/34891

**Closed by gioman** 2020-04-27 10:01 UTC
Labels: Bug, Feedback
