### ISSUE TITLE
The "Split Features" tool does not maintain the M values of each point in the new geometries

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27065] opened 2018-06-21 17:44 UTC
Author Name: **Jorge Almaraz** (Jorge Almaraz)
Original Redmine Issue: [19237](https://issues.qgis.org/issues/19237)
Affected QGIS version: 3.0.3
Redmine category:editing

---
When split  a PolylineZM with de "Split features" tool the resultans polylines lossing the  M values

**Comment by Pedro-Murteira** [comment] 2021-11-30 12:43
Can still reproduce this on QGIS 3.16.14 and 3.22.1.

**Comment by gioman** [comment] 2022-01-25 19:59
Closing as duplicate of https://github.com/qgis/QGIS/issues/40796

**Closed** 2022-01-25 19:59 UTC
Labels: Bug, Digitizing
