### ISSUE TITLE
Filtering and selecting features using forms - Flash Feature and Zoom to Features do not work

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#36903] opened 2020-06-02 11:52 UTC
What are the two buttons `Flash Features` and` Zoom to Features` in this module for?

In win 10 **OSGeo4W** and in **QGIS 3.10**, **3.12** and **MASTER** they don't work !!!

![image](https://user-images.githubusercontent.com/7631137/83516771-f72bfb00-a4d7-11ea-8c50-0d0d23b7c9c9.png)

## QGIS Documentation
https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/attribute_table.html#filtering-and-selecting-features-using-forms

**Comment by gioman** [comment] 2020-06-02 12:51
@pigreco duplicate of https://github.com/qgis/QGIS/issues/34506

**Closed by gioman** 2020-06-02 12:51 UTC
Labels: Bug
