### ISSUE TITLE
LIBJPEG MEM ALLOC Issue

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#34558] opened 2020-02-19 19:38 UTC
**Describe the bug**
A set of JPEGs which have been losslessly compressed using mozjpeg and others are not easily loadable in QGIS (3.4.15-1 LTS, 3.10.2-2, Nightly) and ArcGIS Pro, though numerous other programs can open and display them just fine, many of which are pictured below. Notable programs not pictured: Pix4D Mapper, OpenDroneMap.

**How to Reproduce**
Test using the included JPEG below.

QGIS will not draw the image.

**QGIS and OS versions**

**Additional context**

QGIS version | 3.10.2-A Coruña | QGIS code revision | d4cd3cfe5a
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.3 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.0 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; contour; MemoryLayerSaver; openlayers_plugin; ORStools; PeliasGeocoding; PluginLoadTimes; realcentroid; SpreadsheetLayers; zoom_level; db_manager; MetaSearch; processing

Rendering Log Message:  
```
2020-02-19T14:30:19     WARNING    GOPR0125_3857ab71_beea_4d4c_8087_8e4b7cc01af9 :: C:/Users/username/Desktop/CVI/GOPR0125.JPG, band 3: IReadBlock failed at X offset 0, Y offset 0: Reading this image would require libjpeg to allocate at least 108000000 bytes. This is disabled since above the 104857600 threshold. You may override this restriction by defining the GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC environment variable, or recompile GDAL by defining the GDAL_LIBJPEG_LARGEST_MEM_ALLOC macro to a value greater than 104857600
2020-02-19T14:30:19     WARNING    GOPR0125_3857ab71_beea_4d4c_8087_8e4b7cc01af9 :: C:/Users/username/Desktop/CVI/GOPR0125.JPG, band 2: IReadBlock failed at X offset 0, Y offset 0: Reading this image would require libjpeg to allocate at least 108000000 bytes. This is disabled since above the 104857600 threshold. You may override this restriction by defining the GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC environment variable, or recompile GDAL by defining the GDAL_LIBJPEG_LARGEST_MEM_ALLOC macro to a value greater than 104857600
2020-02-19T14:30:19     WARNING    GOPR0125_3857ab71_beea_4d4c_8087_8e4b7cc01af9 :: C:/Users/username/Desktop/CVI/GOPR0125.JPG, band 1: IReadBlock failed at X offset 0, Y offset 0: Reading this image would require libjpeg to allocate at least 108000000 bytes. This is disabled since above the 104857600 threshold. You may override this restriction by defining the GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC environment variable, or recompile GDAL by defining the GDAL_LIBJPEG_LARGEST_MEM_ALLOC macro to a value greater than 104857600
```
Sample Image:  
![GOPR0125](https://user-images.githubusercontent.com/19295950/74870725-31f29480-5328-11ea-9fdd-fb43fb1066e9.JPG)
[GOPR0125.zip](https://github.com/qgis/QGIS/files/4227011/GOPR0125.zip)

ArcGIS Desktop:  
![arcgis_desktop](https://user-images.githubusercontent.com/19295950/74868872-f3a7a600-5324-11ea-9d2f-fa555223538b.png)

ArcGIS Pro:  
![arcgis_pro](https://user-images.githubusercontent.com/19295950/74868886-f904f080-5324-11ea-909f-87b16d2b1569.png)

GIMP:  
![gimp](https://user-images.githubusercontent.com/19295950/74868914-01f5c200-5325-11ea-9fdb-bcb205ae13ce.png)

MS Paint:  
![mspaint](https://user-images.githubusercontent.com/19295950/74868919-05894900-5325-11ea-9019-78354f20905f.png)

Paint.NET:  
![paintnet](https://user-images.githubusercontent.com/19295950/74868928-09b56680-5325-11ea-9091-e6fc4dd70da1.png)

QGIS 3.10.2-2:  
![qgis_31022](https://user-images.githubusercontent.com/19295950/74868939-0f12b100-5325-11ea-880a-1de088ab8599.png)

Windows Photos:  
![windows_photos](https://user-images.githubusercontent.com/19295950/74868950-133ece80-5325-11ea-94d6-c604e69963cf.png)

**Comment by gioman** [comment] 2020-02-19 20:10
@Saijin-Naib it opens fine on Linux, and by the log messages I would say that this is a problem in how GDAL is compiled/packages for Windows:

![Screenshot_20200219_201005](https://user-images.githubusercontent.com/1951107/74871713-d63e0080-5353-11ea-8e6a-3ebc07a8b906.png)

**Comment by Saijin-Naib** [comment] 2020-02-19 20:19
> @Saijin-Naib it opens fine on Linux, and by the log messages I would say that this is a problem in how GDAL is compiled/packages for Windows:

Still a bug, no?

Who controls the GDAL/libjpeg compilation behavior, and why is it different under Linux?

**Comment by gioman** [comment] 2020-02-19 20:20
> Still a bug, no?

if that is the cause, then it should be reported in the osgeo4w tracker. But this must be confirmed by a dev, mine is a guess.

**Comment by Saijin-Naib** [comment] 2020-02-19 20:36
> Still a bug, no?
> 
> if that is the cause, then it should be reported in the osgeo4w tracker. But this must be confirmed by a dev, mine is a guess.

![image](https://user-images.githubusercontent.com/19295950/74873601-82202580-532d-11ea-9f0e-fcee6174bdaf.png)
Fair point. Setting the environment variable to true does allow QGIS to render the JPEG. I'm not noticing any negative effects at current, though I'm not entirely sure how I would test for them.

**Comment by nyalldawson** [comment] 2020-02-19 20:37
Duplicate of https://github.com/OSGeo/gdal/issues/1545

**Closed by nyalldawson** 2020-02-19 20:37 UTC
Labels: Bug, Feedback
