### ISSUE TITLE
Bug in @Symbol_label using with aggregate function

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#58315] opened 2024-08-05 13:49 UTC
### What is the bug or the crash?

When using @symbol_layer within an Aggregate function, there is no filtering on the symbol in question.

Layer with 4 categories
![Knipsel1](https://github.com/user-attachments/assets/6c4d5dd2-2f08-4ed8-acb8-e8622a28c91d)

Atlas layout legenda
![Knipsel2](https://github.com/user-attachments/assets/fca3b0cd-507b-4f23-a34e-4545baa90203)

Expresion on legenda item
![Knipsel3](https://github.com/user-attachments/assets/4f3b8e33-49bc-46cc-bab6-b5f31bd9820f)

### Steps to reproduce the issue

Load a layer and simulate in categories.
Create an atlas map and use the layer in the legend.
Enter the expression on the existing layer.
I also use the LTR version (latest), it still works after the update.

### Versions

QGIS-versie
3.38.1-Grenoble
QGIS code revisie
3d4177af
Qt versie
5.15.13
Python versie
3.12.4
GDAL/OGR versie
3.9.1
PROJ versie
9.4.0
EPSG-register databaseversie
v11.004 (2024-02-24)
GEOS versie
3.12.2-CAPI-1.18.2
SQLite versie
3.45.1
PDAL versie
2.6.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.1.0
QWT versie
6.2.0
QScintilla2 versie
2.14.1
OS versie
Windows 11 Version 2009

Actieve Python plug-ins
processing
2.12.99
bfvw_tools
1.3
changeDataSource
3.1
export_to_sql_server
0.4
lizmap
4.3.20
pdokservicesplugin
5.1.1
qconsolidate3
0.2.0
SelectWithin
0.4
qgis2web
3.22.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

After the latest update my expression no longer works as before. Only the name and number of the first symbol are calculated and displayed for all subsequent symbols.

**Comment by roya0045** [comment] 2024-08-05 13:55
Duplicate of https://github.com/qgis/QGIS/issues/58221

**Comment by NvBgm** [comment] 2024-08-17 11:35
Also afther update QGis to 3.38.2-2 stil the same problem.

**Closed** 2024-10-14 10:57 UTC
Labels: Bug
