### ISSUE TITLE
vectors not exporting

### ISSUE THREAD

**Issue by instudios76** [qgis/QGIS#32299] opened 2019-10-17 15:27 UTC
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

I have the latest QGIS 3.8.3 Zanzabar and I'm attempting to export a map as either an .svg and/or .pdf file so that I may further work with it in Adobe Illustrator.   My problem is no matter what I do QGIS still exports my map as a raster image.  I've watched every single online video I can find with regards to this specific task but I'm still unable to get a map in vector format.  At this point I'm convinced it's a bug within the software.  

Additionally, when I try and open my exported .svg file in illustrator I get error message stating that This SVG is Invalid.  Validate it before opening".  So what I end up doing is opening the .svg file in Inkscape and then re-saving.  Illustrator is then able to open the saved .svg file (from Inkscape)  with no problem.  

![Illustrator_p2Hjhi1vrL](https://user-images.githubusercontent.com/56689806/67023582-b4b1db80-f10b-11e9-936a-ce96cb43fc14.png)
![Illustrator_DaFhYm36M9](https://user-images.githubusercontent.com/56689806/67023609-bd0a1680-f10b-11e9-84e9-07a193465560.png)

**Comment by kannes** [comment] 2019-10-17 17:54
Do you have actual vector data loaded? The screenshots look like you have pre-rendered OpenStreetMap tiles. Those are raster data with no editing possibilities.

**Comment by instudios76** [comment] 2019-10-18 04:26
Thanks for the prompt response Kannes.  Apparently, I only have OpenStreetMap tiles loaded.  In the past I've downloaded vector data from the OpenStreetMap website in .svg format (see below image) and I assumed exporting OSM vector data from QGIS would be a similar process.  

![chrome_IODKFCBTT8](https://user-images.githubusercontent.com/56689806/67065587-8a960300-f177-11e9-9e14-91120c3f795b.png)

I have background in desktop publishing and  I'd like to be able to tweak my QGIS maps within Illustrator/Photoshop whenever possible.  Within QGIS, is the vector data input by the user or is it downloaded/imported through one of the many plugins.  Please advise.

Your time and assistance is greatly appreciated.

**Comment by haubourg** [comment] 2019-10-18 06:44
@instudios76 OK, I think you probably miss some informations about how work web services. 
You added OSM raster tiles (images then) to QGIS from OSM servers. 
QGIS is just requesting images to a web server and have no access to the OSM vectors this ways. 
If you really want vector layers, you need to download locally OSM vector data, and style them. You can use QuickOSM plugin for this. 

When you use the web interface of OSM, they have the data on their side and are able to convert it to SVG. 

I'm closing the issue, it is not a bug. If you need more assistance, please use qgis-user mailing list. Cheers

**Closed by haubourg** 2019-10-18 06:44 UTC
Labels: Bug
