### ISSUE TITLE
QGIS-OSGeo4W-3.10.3-1-Setup-x86_64.exe is missing exiv2.dll

### ISSUE THREAD

**Issue by limpus2** [qgis/QGIS#34626] opened 2020-02-24 13:18 UTC
Steps to reproduce:
- run installation mentioned in title
- start menu item "QGIS Desktop 3.10.3"
- see message box attached complaining about missing "exiv2.dll"
![QGIS-3 10 3-error](https://user-images.githubusercontent.com/61417523/75155415-4b248800-5710-11ea-996d-5b7f07b0fb8d.png)

PS: I solved this problem for me by copying that DLL from "QGIS-OSGeo4W-3.10.2-2-Setup-x86_64.exe".

**Comment by gioman** [comment] 2020-02-24 13:19
@limpus2 duplicate of https://github.com/qgis/QGIS/issues/34623

**Closed by gioman** 2020-02-24 13:19 UTC
Labels: Bug
