### ISSUE TITLE
Strange behavior with decimals in postgresql tables

### ISSUE THREAD

**Issue by pierloca** [qgis/QGIS#39588] opened 2020-10-24 15:53 UTC
hi, i just install new version, i have a table with some data from temperature and rain sensors, with 1 or 2 decimals, when i load the table, the system add digits to arrive at 9 (11.4 became 11.3999992 but on the table the data is 11.4) and in this way are displayed as label, a little workaround i used is to force to show only 1 or 2 decimal when i format the label, but it's useful only for single data, if i want to concatenate data from multiple columns it doesn't go.
till version 3.14 everything was ok.
i add two screenshot from pgadmin and from qgis of same table, to have a look, check column  "termo".
![Schermata del 2020-10-24 17-51-54](https://user-images.githubusercontent.com/37863952/97086092-a3a28100-1621-11eb-906b-77b88036673c.png)
![Schermata del 2020-10-24 17-50-57](https://user-images.githubusercontent.com/37863952/97086093-a4d3ae00-1621-11eb-972b-4561266d1830.png)

**Comment by gioman** [comment] 2020-10-24 16:35
>  till version 3.14 everything was ok.

@pierloca can you please attach a small sample of your data (as you are working with PostgreSQL a dump made with pg_dump would be ideal)? Thanks.

**Comment by gioman** [comment] 2020-10-24 16:37
> till version 3.14 everything was ok.

@pierloca this means that you observe this only on QGIS master?

**Comment by pierloca** [comment] 2020-10-24 16:40
yes only on master, downgraded to 3.14 and everything returned ok, it's a
3.16 only problem.

Il giorno sab 24 ott 2020 alle ore 18:37 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-10-24 16:49
> yes only on master, downgraded to 3.14 and everything return ok, it's a 3.16 only problem.

@pierloca same question:

can you please attach a small sample of your data (as you are working with PostgreSQL a dump made with pg_dump would be ideal)? Thanks.

**Comment by pierloca** [comment] 2020-10-24 17:17
yes, sure here is my dump (i had to rename it as txt, sql is not allowed), I was checking on it, because with pgadmin, i read 2 decimals,  but checking into dump file it seems that data have 9 digits, more and more strange...so what fail, all the older versions, or the new one? :-)
at least, sensors data, that i download to fill the table, have max 2 decimal, so I can't figure why dump has 9 digits.
[sensori.txt](https://github.com/qgis/QGIS/files/5433345/sensori.txt)

**Comment by gioman** [comment] 2020-10-25 15:29
@pierloca I tried on the latest 3.10 on Linux and on master (now 3.17) on Windows and on the latest pgadmin4 available on Ubuntu 20.04 and in three cases I see the data with just 1 decimal.

**Comment by pierloca** [comment] 2020-10-25 16:14
@gioman thanks, but as i show with the two screenshot above, it's a stange situation, i had 3.16 in two different computer and the result was the same, the second screenshot is made on the computer i downgraded from 3.16 to 3.14, but with 3.16 the result was like the first screenshot, i don't know what is happend. maybe with 3.17 it not happens, i'll try with.

**Comment by gioman** [comment] 2020-10-25 16:29
@pierloca same thing on 3.16.

Please try with a new QGIS profile.

**Comment by pierloca** [comment] 2020-10-26 09:03
Ciao Giovanni, thanks for your hints, I tried with a new profile, but nothing changes, I keep seeing 9 digits. Some more information: I used the Mint updater when prompted, it move the version from one to the other, so after update, usually, nothing changes, this time yes, I could try to compile source file from github, but, i have no time now.
I can't be more useful, for now I use 3.14 and it's ok.

lastly, we focused on the digits problem, and it's ok, but my feedback is also on the workaround I tried to use in my first post, forcing the label to have only a few decimals, for single column,  works, but if I concatenate more than one column it doesn't work and shows 9 digits again, maybe this is a general problem.

**Comment by gioman** [comment] 2020-10-26 12:24
@pierloca what is your postgresql version? can you test on a desktop system with a en_en locale?

**Comment by pierloca** [comment] 2020-10-26 15:30
I have postgres 11, i can change the language, but it's a behavior that
happens only if I use qgis 3.16 (and 3.17, i just build a fresh
installation from github...same as 3.16), no other releases are affected
from this, from 2.14 to 3.14 it goes ok, i can even change everything of my
system, but could be a problem if i have to change my desktop or database
settings to be able to see my data with only 1 decimal! I remain with 3.14
and amen....
Do not misunderstand, i'm really glad for your efforts and i thank you a
lot for the time you are giving me, but i think that something inside the
program is changed, i don't know what, i'm not a programmer so I can't
help, but if every other release is ok, something goes wrong, or better
goes different, with the latest, maybe it's an error of my database that
other releases are able to correct and this not, I don't know, but seems
that i'm the only to have this strange behavior, I don't know even if it's
a good idea to have a deeper investigation.
thanks again!





Il giorno lun 26 ott 2020 alle ore 13:24 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-10-26 15:34
> Do not misunderstand, i'm really glad for your efforts and i thank you a lot for the time you are giving me, but i think that something inside the program is changed, i don't know what, i'm not a programmer so I can't help, but if every other release is ok, something goes wrong, or better goes different, with the latest, maybe it's an error of my database that other releases are able to correct and this not, I don't know, but seems that i'm the only to have this strange behavior, I don't know even if it's a good idea to have a deeper investigation. thanks again!

@pierloca as per https://github.com/qgis/QGIS/issues/39588#issuecomment-716174470 it seems something related to your system. It can also be a bug, but it needs more efforts on your side as it is not replicable here. So if you are available to go to the bottom of this problem would e great, if you are not we will probably close this ticket.

**Comment by pierloca** [comment] 2020-10-26 16:28
yes, I agree to close it until someone else do not has my same problem. i
trust in you when you say that it's a problem of my system, but on two
different computers? and in each one 3.14 works and 3.16 don't, there is
something different in  the new release  about how it deal with the
postgresql database, no other explication. i'll try later with one other
lubuntu distribution, or i could install a virtual machine with english
language as you ask, but i have some doubt about it could work, anyway,
i'll try and i'll send you news if there will be.

thanks

Il giorno lun 26 ott 2020 alle ore 16:34 Giovanni Manghi <
notifications@github.com> ha scritto:

**Comment by gioman** [comment] 2020-10-26 16:32
> virtual machine with english language as you ask, but i have some doubt about it could work

@pierloca unless you have better ideas, I don't see any other difference (I can of course be missing something obvious).

**Comment by pierloca** [comment] 2020-10-27 21:03
nothing to do, i install a virtual machine en_US, i install first a 2.18 version and the numbers were correct, than i upgrade to 3.16 and again i got that crazy numbers, at this point it's not possible at all that it is a problem of my system, someone, i don't know how, changes something inside qgis, Giovanni, I don't know if you have developed that part of code or you know who did, i can only say what i notice inside layer properties in field format, the precision field in 3.16 is set to 0, before was set to -1, i don't know if that is the set that show me so many decimals, and either I don't know if it's possible to change. last question, when you loaded my dump in your database and loaded in your qgis, the label of points with the value "termo" (but it's the same with vento), are all with one decimal?

**Comment by gioman** [comment] 2020-10-27 21:14
> when you loaded my dump in your database and loaded in your qgis, the label of points with the value "termo" (but it's the same with vento), are all with one decimal?

@pierloca 

![Screenshot_20201027_211318](https://user-images.githubusercontent.com/1951107/97362713-54ff1c00-1899-11eb-8f81-70ca3c070dc4.png)

![Screenshot_20201027_211409](https://user-images.githubusercontent.com/1951107/97362746-60524780-1899-11eb-8123-a9d2981d91c0.png)

**Comment by pierloca** [comment] 2020-10-27 21:22
![Schermata del 2020-10-27 22-16-33](https://user-images.githubusercontent.com/37863952/97362975-2174bf80-18a2-11eb-94f1-9a5c18fb8685.png)
![Schermata del 2020-10-27 22-17-43](https://user-images.githubusercontent.com/37863952/97363355-bf688a00-18a2-11eb-9115-e85f8029dc65.png)
![Schermata del 2020-10-27 22-20-40](https://user-images.githubusercontent.com/37863952/97363364-c1324d80-18a2-11eb-88a0-c8a53853bfdd.png)


no, basta io non ce la faccio piu'....the precision of the field in the layer properties is 0 in yours?
I give up...after this

**Comment by gioman** [comment] 2020-10-28 10:38
> the precision of the field in the layer properties is 0 in yours?

@pierloca is it as yours, anyway it does not means much other than the field is a double precision datatype, so it has a fixed number of decimals.

Have you tested this on a Ubuntu 20.04 based system (yours is based on 18.04) or Windows (this is to exclude a problem related to the older dependencies used on 18.04)?

**Comment by pierloca** [comment] 2020-10-28 13:17
ok, got the problem, and it's not good, i uninstall postgresql 11 and update to 12, and the strange behavior disappear, but that's not acceptable, there's someone still using 9.4.
I solved my problem, but not everyone is able to uninstall databases, update and reinstall it, qgis have to work with every version of the database, till 3.14 it happend, from 3.16 no more.
thank you for your help!
now it's possible to close the issue, but it's necessary that one developer have a look about it.

**Comment by gioman** [comment] 2020-10-28 13:19
>  now it's possible to close the issue, but it's necessary that one developer have a look about it.

@pierloca it does not work like that. If you really want to help this project grow, once found the source of the issue you should at least edit/change the title and description to better reflect your latest findings.

**Comment by gioman** [comment] 2020-10-28 13:27
@pierloca I tested also on 9.6 and I can see what you describe. The SQL file has indeed that values with several decimal places, but once imported in the DB (I used psql) they don't have anymore many decimals. So the maybe the problem is the way the data is imported, not QGIS.

**Comment by pierloca** [comment] 2020-10-28 13:47
i really don't know, I have a bash script that download values and update the table with psql too, maybe it's how psql update the table, but the deep question is, why with postgresql 11 and the same table, in qgis 3.14  i can see 1 decimal and with 3.16 not, if it was the same for all version, it could be a bash script problem, but it's running from 1 year now and had no troubles till now. , then upgrade to pg12 everything returns right, with every distribution, the 18.04 and the 20.10. I don't know how to change the title of this issue could be valid "Compatibility between qgis 3.16 and postgres lower than 12" ?

**Comment by gioman** [comment] 2020-10-28 14:40
@pierloca did you use the same psql version to import data in the different (version) databases?

What does it happens if you import the data on pg11 and then update it to 12?

**Comment by pierloca** [comment] 2020-10-28 16:53
@gioman this is incredible, now I set up 4 release of pg 10 11 12 and 13, here is the results ;-)) 
same bash script that download the sensors and update the 4 tables and are update every 15 minutes, so they change continuosly, the layout on pictures has the version of pg in the name (qgis version 3.16), of course with 3.14 all 4 layers show number correctly.
more than this i can't be clear.


![Schermata del 2020-10-28 17-23-40](https://user-images.githubusercontent.com/37863952/97467985-11fa8280-1945-11eb-8b5e-6daeb0f6e202.png)
![Schermata del 2020-10-28 17-23-26](https://user-images.githubusercontent.com/37863952/97467667-b8925380-1944-11eb-8db9-610eb07f8983.png)
![Schermata del 2020-10-28 17-38-54](https://user-images.githubusercontent.com/37863952/97467583-a44e5680-1944-11eb-9802-7ff9732ce172.png)
![Schermata del 2020-10-28 17-23-56](https://user-images.githubusercontent.com/37863952/97467756-ce077d80-1944-11eb-9413-82f401a4f378.png)

**Comment by gioman** [comment] 2020-10-28 17:32
> @gioman this is incredible,

@pierloca I'm not sure why you are surprised.

Anyway this is what I'm seeing.

Your dump has columns with data with several decimal places.

I have a pg12 machine, I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are truncated to 1 decimal place.

I have also pg9.6 machine,  I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are nor truncated.

So... what I see in QGIS is compatible with the above, in other words there is no QGIS issue here. The problem seems to lie in how psql imports data in pg releases 12 or above.

**Comment by gioman** [comment] 2020-10-28 17:34
> I have a pg12 machine, I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are truncated to 1 decimal place.
> 
> I have also pg9.6 machine, I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are nor truncated.

ps: this was checked by inspecting the data directly in the DB, no QGIS involved here.

**Comment by pierloca** [comment] 2020-10-29 13:44
@gioman you are right, I checked in all four dumps and 10 and 11 give 9 digits instead 12 and 13 only the correct value.
even if with pgadmin i read the numbers of sensors as expected for every database version, and it is again strange, why pgadmin correct, as gqis 3.14, the long digits number as i expect they would be.
But i continue to say: you (the community of developers) have a version, that willing or not, auto correct wrongly data formatted by database, why remove this behaviour, it's not comprehensible, I speak as end user, and seems that I resolve my problem, everything developers will do, is not important for me, but if a program can run whatever is the input, it's better, not? 
last favor, I don't know how to close this post, you suggest to change title, i don't know what to write, can you help me.
thank you again, without your advise, never I would have thought it was a database problem.

**Comment by gioman** [comment] 2020-10-30 14:26
> I have a pg12 machine, I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are truncated to 1 decimal place.
> 
> I have also pg9.6 machine, I imported your dump with PSQL (\i \tmp\sensori.sql) installed on the same machine, and the values in that columns are nor truncated.

@pierloca I must correct my statemente. In both cases psql imports the data with only 1 decimal place, this can be seen by quering your table directly with the PSQL command line, so not QGIS or PgAdmin involved:


pg9.6:

```
SELECT termo FROM sensori WHERE termo IS NOT NULL;
 termo 
-------
   8.7
  11.6
  10.3
    13
  13.9
   2.7
     8
   8.1
   8.3
    12
  12.8
  10.5
  11.9
   7.7
  10.6
  11.6
  11.6
  12.1
  12.3
  12.5
  14.5
   8.9
  10.4
  12.7
  12.7
  13.5
  15.5
    12
  12.7
  14.4
(30 rows)
```

pg12:
```

SELECT termo FROM sensori WHERE termo IS NOT NULL;
 termo 
-------
   8.7
  11.6
  10.3
    13
  13.9
   2.7
     8
   8.1
   8.3
    12
  12.8
  10.5
  11.9
   7.7
  10.6
  11.6
  11.6
  12.1
  12.3
  12.5
  14.5
   8.9
  10.4
  12.7
  12.7
  13.5
  15.5
    12
  12.7
  14.4
(30 rows)
```


and of course QGIS (any version) shows the labels/data with only 1 decimal.

You must check (better done with psql cli) if your data was imported with 1 decimal or not.

**Comment by gioman** [comment] 2020-11-11 18:50
Closing for lack of further feedback.

**Closed by gioman** 2020-11-11 18:50 UTC
Labels: Bug, Feedback
