### ISSUE TITLE
DB Manager fails to display Postgresql table details: TypeError: must be real number, not list

### ISSUE THREAD

**Issue by jgrocha** [qgis/QGIS#34467] opened 2020-02-13 23:48 UTC
**Describe the bug**

DB Manager is reporting a python error when it needs to display Postgresql table's summary. 

The core functionality is not affected. I can everything else.

![db manager error display pg table info](https://user-images.githubusercontent.com/163681/74488608-a8bc0780-4eba-11ea-947e-292f1cbcb44d.png)

The error is:
```
TypeError: must be real number, not list 
Traceback (most recent call last):
  File "/usr/local/share/qgis/python/plugins/db_manager/db_manager.py", line 100, in itemChanged
    self.refreshTabs()
  File "/usr/local/share/qgis/python/plugins/db_manager/db_manager.py", line 143, in refreshTabs
    self.info.showInfo(item)
  File "/usr/local/share/qgis/python/plugins/db_manager/info_viewer.py", line 74, in showInfo
    self._showTableInfo(item)
  File "/usr/local/share/qgis/python/plugins/db_manager/info_viewer.py", line 133, in _showTableInfo
    html += table.info().toHtml()
  File "/usr/local/share/qgis/python/plugins/db_manager/db_plugins/info_model.py", line 361, in toHtml
    ret = self.getTableInfo()
  File "/usr/local/share/qgis/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 231, in getTableInfo
    ret = TableInfo.getTableInfo(self)
  File "/usr/local/share/qgis/python/plugins/db_manager/db_plugins/info_model.py", line 303, in getTableInfo
    spatial_info = self.spatialInfo()
  File "/usr/local/share/qgis/python/plugins/db_manager/db_plugins/postgis/info_model.py", line 250, in spatialInfo
    return VectorTableInfo.spatialInfo(self)
  File "/usr/local/share/qgis/python/plugins/db_manager/db_plugins/info_model.py", line 400, in spatialInfo
    estimated_extent_str = '%.5f, %.5f - %.5f, %.5f' % self.table.estimatedExtent
TypeError: must be real number, not list
```

**How to Reproduce**

Open DB Manager

Select one Postgresql table

The error is shown when trying to dsplay table information.

**QGIS and OS versions**

Python version: 3.6.8 (default, Apr  9 2019, 04:59:38) [GCC 8.3.0] 
QGIS version: 3.11.0-Master Master, 5ae9807303

**Comment by jgrocha** [comment] 2020-02-13 23:57
The query sent to Postgresql is working and returning the proper values.

```sql
SELECT st_xmin(extent), st_ymin(extent), st_xmax(extent), st_ymax(extent) FROM (SELECT st_estimated_extent('caminha','lugar','geom') AS extent) as subquery
```
```text
st_xmin       |st_ymin      |st_xmax        |st_ymax   |
--------------|-------------|---------------|----------|
-61791.2890625|234832.921875|-44596.99609375|249969.625|
```

**Comment by gioman** [comment] 2020-02-14 09:58
Jeez... it keeps breaking on and on...

**Comment by elpaso** [comment] 2020-02-14 10:03
@gioman that's why we are desperately fighting for moving it to C++, but sometimes I feel like we are doing one step forward and two steps backward.

**Comment by elpaso** [comment] 2020-02-14 10:06
I can't reproduce btw.

**Comment by gioman** [comment] 2020-02-14 10:08
> reproduce

I can replicate with master from osgeo4w.

**Comment by gioman** [comment] 2020-02-14 10:12
> @gioman that's why we are desperately fighting for moving it to C++, but sometimes I feel like we are doing one step forward and two steps backward.

@elpaso I think that idea is to move everything to the data source manager, correct? I think we should make a list of the functionalities that DB  Manager has that are not available in the data source manager and put to vote what is necessary to keep and what not.

**Comment by elpaso** [comment] 2020-02-14 10:23
The first and most important goal is to have a C++ core API to manage DBs in a unified way, I've started that API one year ago with the grant proposal about connections management.

That API can be the foundation upon which we  build the new DB manager, it is already used in both DB manager and the browser but it needs to be extended to all supported DBs because it's now only available for postgres and GPKG.

I think that we need to define a minimum set of features we need to implement in the browser in order to drop DB manager from core and let it continue it's life as an independent plugin for those who need extra features. 

Also, the new browser and the new API are available for other parts of the application and for plugins, this means that the future DB manager will definitely benefit from that.

**Comment by PedroVenancio** [comment] 2020-02-28 10:06
I can also confirm this issue in QGIS 3.12.

It only happens in tables that have "Estimated extent" displayed in Info tab. 

And the error only show up in Info tab. No problem with Table and Preview tabs.

**Comment by jonnyforestGIS** [comment] 2020-02-28 10:24
Same in where. As Pedro said:

> Tt only happens in tables that have "Estimated extent" displayed in Info tab.

> And the error only show up in Info tab. No problem with Table and Preview tabs.

Using the First Aid Plugin this is the result:

![Capture](https://user-images.githubusercontent.com/4480601/75540608-41529b80-5a14-11ea-8e19-696c6d3a8887.PNG)

**Closed** 2020-03-11 18:45 UTC
Labels: Bug, DB Manager, Regression
