### ISSUE TITLE
Labels disappear even if "Allow truncted labels" option is enabled

### ISSUE THREAD

**Issue by Xeenych** [qgis/QGIS#32856] opened 2019-11-14 09:04 UTC
Something is broken in QGIS 3.10 labelling.
Labels disappear if they don't fit into canvas. Even if "Allow truncated labels" option is enabled.
In QGIS 3.4 everything is ok.

This could be somehow related to #32825

QGIS 3.10
Win7 x64

**Comment by nyalldawson** [comment] 2019-11-14 19:13
Can't reproduce -- can you share a project demonstrating this?

**Comment by Xeenych** [comment] 2019-11-15 05:21
Project
[test.zip](https://github.com/qgis/QGIS/files/3849902/test.zip)
Video
https://yadi.sk/d/uDHYJnIObfYjYg

**Comment by andreasneumann** [comment] 2019-11-15 07:46
It is also broken on my QGIS on Linux with this test project. Labels disappear if  I pan the map that only parts of the label would be in the canvas.

Here are my versions:


QGIS version | 3.11.0-Master | QGIS code revision | b38e191010
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.3 LTS | This copy of QGIS writes debugging output.
Active python plugins | trackable_project_files; QgisModelBaker; DataPlotly; processing; db_manager; MetaSearch

**Comment by nyalldawson** [comment] 2019-11-18 04:19
Ok - I've done some debugging, and the issue isn't with the "allow truncated labels" setting. Rather, it relates to the change (feature!) added in 3.10 which allows users to manually specify a maximum overrun distance which labels can run past the ends of linear features. In 3.10 this new setting defaults to 0, whereas in some circumstances in <3.10 linear labels would allow overrun of varying distances. If you go into your layer's placement tab and increase the "overrun feature" distance you'll be able to see these labels again.

**Comment by nyalldawson** [comment] 2019-11-18 04:19
(In other words, this is a change in behavior, but not a bug)

**Comment by andreasneumann** [comment] 2019-11-18 08:15
Thanks for the clarification, Nyall! There are a lot of different settings in labeling that interact somehow.

**Comment by gioman** [comment] 2019-11-18 08:18
closing?

**Comment by Xeenych** [comment] 2019-11-18 08:34
No, don't close it.

So. If I want to be able to see truncated labels, I have to increase overrun distance? But then my labels will shift along the line, which will make a mess on my map.

Whether overrun is set to some value or is 0, I expect "show truncated labels" to work, and I don't want labels to overrun.

**Comment by gioman** [comment] 2020-06-12 15:54
> No, don't close it.
> 
> So. If I want to be able to see truncated labels, I have to increase overrun distance? But then my labels will shift along the line past its end, which will make a mess on my map.
> 
> Whether overrun is set to some value or is 0, I expect "show truncated labels" to work, and I don't want labels to overrun.
> 
> Overrun and showing truncated labels are completely different bahaviours, they should not be mixed.

@Xeenych I would say that as this point and given the explanation of a developer this is better suited for a question on the developers mailing list. If it turns out that there is really a bug then please reopen this ticket.

**Closed by gioman** 2020-06-12 15:54 UTC
Labels: Bug, Feedback, Labeling, Regression
