### ISSUE TITLE
Clicking "Test Connection" on a new MSSQL connection displays error "Driver not loaded Driver not loaded"

### ISSUE THREAD

**Issue by bbct** [qgis/QGIS#37177] opened 2020-06-12 18:26 UTC
**Describe the bug**
Using "Test connection" on a new MSSQL connection results in an error "Driver not loaded driver not loaded" leading the user to believe it is not working.  However if the user just clicks "List databases" the list is populated correctly, so the connection actually works just fine.

Please either remove the "Test Connection" button on this dialog box, and let the user "test" the connection by trying to list the databases, or repair the code so the Test Connection does not fail when the connection data is entered correctly.

**How to Reproduce**
Right click on MSSQL in the browser and click New Connection...
fill in the Connection Name, Host, and proper credentials.  (be sure the Host and credentials are valid) 
Click the "Test Connection" button
You will see the error displayed.
Click List Databases, and you will see the list of databases on that server, proving the connection works just fine.

**QGIS and OS versions**
Windows 10
QGIS 3.12.3-București

**Additional context**

**Comment by MarvinMep** [comment] 2020-10-22 19:52
On Debian Linux 10 (buster), QGIS 3.14 the same error ("Driver not loaded Driver not loaded") shows up when clicking "test connection", but when clicking "list databases" QGIS freezes entirely (needing to kill the process).

Same on Debian Testing (bullseye), QGIS from unstable repositories (3.14.16)

**Comment by bbct** [comment] 2020-11-24 18:31
MarvinMep: I'm not positive, but clicking the "test connection" first may put it in a bad state.  If I recall correctly, if you avoid pressing that button at all, then, if all your info is entered correct, when you click List Databases, the database list populated.

**Comment by MarvinMep** [comment] 2021-07-19 17:38
> MarvinMep: I'm not positive, but clicking the "test connection" first may put it in a bad state. If I recall correctly, if you avoid pressing that button at all, then, if all your info is entered correct, when you click List Databases, the database list populated.

No, even if I only click "List Databases" (without clicking "test connection" first), I get the error "Error opening connection: Driver not loaded Driver not loaded". It doesn't freeze, but I still can't connect.
Now Debian Bullseye, QGIS 3.20.0-Odense

**Comment by MarvinMep** [comment] 2021-07-19 17:52
Sorry, looks like my issue is more like #33392.
But I could confirm this issue: when I click "test connection" the error "Driver not loaded Driver not loaded" shows up, but when I click "List databases" the error is much more descriptive, in my case, "[unixODBC][Driver Manager]Can't open lib 'FreeTDS' : file not found QODBC3: Unable to connect".

**Comment by jmkerloch** [comment] 2022-03-09 14:16
I managed to remove this error message by following this gist https://gist.github.com/genio/7c7fc52fcb8be5d486aa#file-01_setup_ubuntu-md

But now I have a new error : 
`[FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist`

But this time it seems to be related to my FreeTDS configuration, not QGIS.

**Comment by gioman** [comment] 2022-03-09 14:58
Closing as duplicate of https://github.com/qgis/QGIS/issues/33392

**Closed by gioman** 2022-03-09 14:58 UTC
Labels: Bug, MS SQL data provider

**Comment by bbct** [comment] 2022-03-09 16:20
@gioman I believe you have closed this in error.  The other case #33392 which you claim this is a duplicate of is for folks who really are having a problem communicating with their SQL Server with the drivers they believe should be working fine. That case assumes the error is correct, that there is indeed a problem communicating with the SQL Server.  

This case is nothing like that at all.  This case only applies to folks who have absolutely no issue communicating with their SQL Server. If you never click the "Test Connection" button, all works great. The problem reported here is ONLY with the button labeled "Test Connection", which ALWAYS returns an error, falsely implying that there is a problem with the SQL Server access. The button ALWAYS fails to test a SQL Server connection, whether it is configured properly or not. The error you see when you press this button is completely misleading. 

@MarvinMep even says in a comment above that his issue is more like case #33392, and NOT this case.  @jmkerloch added a comment, but his comment also belongs on case #33392, it has nothing at all to do with this case.  

You have closed this case in error, please undo your action.  I don't want to have to open a new identical one. Thanks.

**Comment by bbct** [comment] 2022-03-09 16:26
> Sorry, looks like my issue is more like #33392. But I could confirm this issue: when I click "test connection" the error "Driver not loaded Driver not loaded" shows up, but when I click "List databases" the error is much more descriptive, in my case, "[unixODBC][Driver Manager]Can't open lib 'FreeTDS' : file not found QODBC3: Unable to connect".

Yes, exactly.  Clicking the Test Connection button for a SQL Server configuration simply ALWAYS says "Driver not loaded Driver not loaded".  It very well could be an accurate description of a problem with the Test Connection logic.  But it has nothing at all to do with whether you've configured your SQL Server connection properly or not. As you say, if you want to test the connection and get a meaningful error if there is a problem, try the "List Databases" button. That will indeed test your database connection, and return a meaningful error if there is an issue.

**Comment by jmkerloch** [comment] 2022-03-09 17:36
@bbct I posted the comment just for user who gets the message "Driver not loaded Driver not loaded" so they can configure FreeTDS driver for use in QGIS.

I managed to fix my issue 

> [FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist

I was using a docker image for mssql server but I didn't use the correct port forwarding 🤦‍♂️ 

But I just tested the Test connection button on QGIS 3.22 and it didn't show any error.

@bbct  Didn't mean to ask for issue closing but just sharing my experience with mssql use on Ubuntu.

**Comment by bbct** [comment] 2022-03-09 18:16
> But I just tested the Test connection button on QGIS 3.22 and it didn't show any error.

That is interesting to hear.  I use QGIS on Windows, I've not tried with Docker or Linux. When I upgrade QGIS to the latest version I'll try it again.  It is possible this is a Windows only issue, or perhaps it's been fixed by this case was not tagged, I don't know. I'm using 3.14.1, as I've not upgraded in quite a while. And it was mentioned above on Debian 3.14.x.  Thanks.

**Comment by gioman** [comment] 2022-03-09 19:59
> I'm using 3.14.1, as I've not upgraded in quite a while. And it was mentioned above on Debian 3.14.x. Thanks.

@bbct this is too old. Try on 3.22.4 or 3.24.0 and if necessary I can reopen this.
