### ISSUE TITLE
Attribute table does not take into account the temporal controller range

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#40768] opened 2020-12-27 19:15 UTC
**Describe the bug**

When opening the attribute table on a layer that is used the new temporal controller, it shows all objects from the layer regard less of temporal data, instead of just what the temporal controller is letting show on the canvas.

**How to Reproduce**

1. Create a layer with features with temporal values
2. The the temporal controller on for that later with start and end dates
3. In the temporal controller panel, select a step size and move the range slider thumb to a date
4. in Settings→Data Sources, for "Attribute table behavior" choose "Show All Features"
5. Click on the button to open the attribute table

Here is what the attribute table, with all features regardless of temporal values, looks like.
![image](https://user-images.githubusercontent.com/8172909/103177741-0cd58900-484b-11eb-963b-a1f80762c5be.png)
See how the selected line doesn;t turn an object yellow as expected, because it is not getting drawn to the canvas because of the temporal controller.
![image](https://user-images.githubusercontent.com/8172909/103178066-b4ec5180-484d-11eb-8cac-aac231340baf.png)

**QGIS and OS versions**

QGIS version | 3.17.0-Master | QGIS code revision | 5deda1f456
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.0.1 | Running against PDAL | 2.0.1 (git-version: Release)
PostgreSQL Client Version | 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | ImageServerConnector; db-style-manager; AzimuthDistanceCalculator; cartography_tools; quick_map_services; qgis-maptiler-plugin; QuickOSM; bettereditor; BackupLayer; OSMDownloader; deactivate_active_labels; Discovery; processing; db_manager; MetaSearch

**Comment by gioman** [comment] 2020-12-27 19:42
@CoryAlbrecht same as https://github.com/qgis/QGIS/issues/39076 ?

**Comment by CoryAlbrecht** [comment] 2020-12-27 21:48
When set to "Show Features Visible on Map", some times it isn't even correct as to what gets listed in the attribute table. A syou can see, there is no "New Spain" feature showing, and "Quebec" i snot listed in the table.

![image](https://user-images.githubusercontent.com/8172909/103180337-e3c0f280-4862-11eb-8b60-fd1eb6077b5c.png)

**Comment by CoryAlbrecht** [comment] 2020-12-27 21:59
> @CoryAlbrecht same as #39076 ?

@gioman 
I would guess so, assuming that this other error I found doesn't change that.

**Comment by gioman** [comment] 2020-12-28 08:12
>  I would guess so, assuming that this other error I found doesn't change that.

@CoryAlbrecht I would say that the description of this ticket is duplicate of https://github.com/qgis/QGIS/issues/39076 and that



> When set to "Show Features Visible on Map", some times it isn't even correct as to what gets listed in the attribute table. A syou can see, there is no "New Spain" feature showing, and "Quebec" i snot listed in the table.

is a different issue you must file in a separate ticket. Closing?

**Closed** 2020-12-29 21:56 UTC
Labels: Bug, Feedback, Temporal
