### ISSUE TITLE
Raster layer symbology exposed/hidden after batch import or moving into group (Layers Panel)

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#44663] opened 2021-08-12 01:47 UTC
### What is the bug or the crash?

When loading a group of rasters layer at the same time, their symbology is alternatively exposed/hidden instead of being all exposed. It happens if loading is done with a drag and drop from the system file explorer, from the Browser Panel or from the Data Source Manager.
![image](https://user-images.githubusercontent.com/32580398/129095269-c9c80716-d730-4fa7-8533-c46ad7a62bda.png)

### Steps to reproduce the issue

**Test one**
1. Open new empty project
2. Select a group of 5 rasters from the Browser Panel and drag them all at the same time to the canvas.
3. _Observe alternating exposed/hidden symbology (note: in my case layer 1-3-5 are exposed and layer 2-4 are hidden)_
4. Manually hide all symbologies
5. Select all raster layers and add to new group
6. _Observe that some layers have their symbology exposed (note: that sometime it was one, sometime two, not always the same order, it may depends on which layer is selected first or last)_
7. Hide all symbologies
8. Select all raster layers inside the group and add to new group
9. _Observe that all symbologies stay hidden_

**Test two**
1. Open new empty project
2. Add one layer laying around
3. Select a group of 5 rasters from the Browser Panel and drag them all at the same time to the canvas.
4. _Observe reversed alternating exposed/hidden symbology (note: in my case layer 2-4 are exposed and layer 1-3-5 are hidden)_

### Versions

QGIS version 3.20.0-Odense
QGIS code revision decaadb
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.0
GEOS version 3.9.1-CAPI-1.14.2
Windows 10 Version 1809

### Additional context

The issue was not present in 3.14.1. Testing with a brand new profile didn't help.

**Comment by nicogodet** [comment] 2021-08-12 05:03
I can confirm this.

**Comment by roya0045** [comment] 2021-08-12 13:15
Duplicate of #42596

**Closed** 2021-08-12 14:07 UTC
Labels: Map and Legend, Bug
