### ISSUE TITLE
Print Composer crashing 

### ISSUE THREAD

**Issue by DrewFrance** [qgis/QGIS#42777] opened 2021-04-12 18:47 UTC
## User Feedback

Just trying to resize a map in the Composer.

## Report Details

**Crash ID**: [afa0a1d4359eff83cc60efa7a0f084ed10976b34](https://github.com/qgis/QGIS/search?q=afa0a1d4359eff83cc60efa7a0f084ed10976b34&type=Issues)

**Stack Trace**
<pre>
GEOSEquals_r :
GEOSEquals_r :
QgsGeos::shortestLine qgsgeos.cpp:2274
QgsGeometry::shortestLine qgsgeometry.cpp:636
<lambda_098e6f315b0c35646bc666a71ce10ce8>::operator() qgscallout.cpp:473
QgsSimpleLineCallout::draw qgscallout.cpp:539
QgsCallout::render qgscallout.cpp:143
QgsVectorLayerLabelProvider::drawCallout qgsvectorlayerlabelprovider.cpp:333
QgsVectorLayerLabelProvider::drawLabelBackground qgsvectorlayerlabelprovider.cpp:311
QgsLabelingEngine::drawLabels qgslabelingengine.cpp:427
QgsDefaultLabelingEngine::run qgslabelingengine.cpp:561
QgsMapRendererJob::drawLabeling qgsmaprendererjob.cpp:1002
QgsMapRendererCustomPainterJob::doRender qgsmaprenderercustompainterjob.cpp:355
QgsMapRendererCustomPainterJob::staticRender qgsmaprenderercustompainterjob.cpp:267
QtConcurrent::RunFunctionTask<void>::run qtconcurrentrunbase.h:136
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.4-Hannover
QGIS code revision: 654e76b3cb
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

**Comment by gioman** [comment] 2021-04-12 18:50
@DrewFrance please try with a new QGIS profile. Also update to 3.16.5, if the problem persist please attach/link the project (with the composer and the necessary data).

**Comment by roya0045** [comment] 2021-04-13 16:42
@gioman I'd suggest closing this, duplicate of #41968 and fixed already.

**Closed** 2021-04-13 17:38 UTC
Labels: Feedback, Print Layouts
