### ISSUE TITLE
Dissolve tool incorrectly fills holes

### ISSUE THREAD

**Issue by dalyk85** [qgis/QGIS#31041] opened 2019-08-01 16:06 UTC
I am coming across the problem where when I dissolve a polygon to a temporary file within the workspace it appears fine and contains several holes, which matches the input single part polygon. 

When I ' export>>save features as', some of the holes become infilled and yet retain a border. This means areas are shown as flooded which should not be as the polygons represent flood outlines. 

Has anybody come across this issue before? Any help appreciated. The issue occurs for me in QGIS v2.18 and v3.6. 

Thanks

The attachments highlight the before saving and after saving issue where the hole becomes infilled for no apparent reason. 

![Temporary dissolve file_correct](https://user-images.githubusercontent.com/53575300/62309054-95959d00-b47e-11e9-8094-d1257954022e.png)

![Saved dissolve file_incorrect with hole infilled](https://user-images.githubusercontent.com/53575300/62309052-94fd0680-b47e-11e9-958f-c1fe87e7ea62.png)

**Comment by gioman** [comment] 2019-08-01 16:21
Please attach sample data and the exact sequence of steps you follow.

**Comment by dalyk85** [comment] 2019-08-01 16:33
[flood_extent_singlepart.zip](https://github.com/qgis/QGIS/files/3457721/flood_extent_singlepart.zip)

flood_extent_singlepart.shp is the input file which I dissolve via: 

Vector>>Geoprocessing tools>>Dissolve

![dissolve tool window](https://user-images.githubusercontent.com/53575300/62310828-481b2f00-b482-11e9-8a98-3c38336e8d02.png)

Initially I dissolve to a temporary layer and results match the input layer in terms of holes in the polygon. However when I export>>save feature as the output file (test_dissolve_multipart.shp) infills some of the holes which baffles me.

I have validated the geometry and no issues show up. I also tested the dissolve in ArcMap and the output doesn't contain any infilled holes so very confused as to what's causing this in QGIS, especially given the temporary output layer looks fine. 

Thanks

**Comment by dalyk85** [comment] 2019-08-01 17:16
The issue appears to be a display issue, as when displaying the output files in ArcMap they display with the holes intact, but when the same polygon shp is uploaded to QGIS the holes appear infilled. 

Clueless as to how I get QGIS to render the polygon without infilling the holes

**Comment by gioman** [comment] 2019-08-01 21:32
> The issue appears to be a display issue

no it is not. Your input has geometry errors, if you fix them with the "fix geometries" tool, then the QGIS dissolve tool return the result you expect. Curiosly enough both GDAL and SAGA dissolve tools still will fill some of the holes, while GRASS dissolve do not miss a beat (because of course is heavy artillery) also using your original unfixed input.

**Comment by dalyk85** [comment] 2019-08-01 22:04
Thanks...but none of the three methods I try following I "fix geometries" give the desired result of a fully dissolved multipart polygon. While both GDAL and SAGA fill some holes, the GRASS function whilst it does retain the holes, leaves sections of the polygon undissolved like so

![Dissolve_GRASS](https://user-images.githubusercontent.com/53575300/62330353-5aac5d00-b4b0-11e9-9951-17e6944c0b75.png)

I wonder is there any tool combination that give the required result. If it isn't a display issue, why do the temporary dissolve layers for the GDAL operation appear 100% correct, and it is only when you export and save the file that the holes infill. Also the saved dissolved shp displays fine in ArcMap without any holes infilled - so the same file displays differently across both platforms...odd.

**Comment by gioman** [comment] 2019-08-01 22:06
I changed the title because the problem is in the dissolve tools for this particular input, not the export operation.

**Comment by gioman** [comment] 2019-08-01 22:07
> why do the temporary dissolve layers for the GDAL operation appear 100% correct,

not here.

**Comment by dalyk85** [comment] 2019-08-01 22:16
OK re the name change. Ah so for you the temporary dissolved layer also has holes infilled? For me the temporary layer appears ok:

![Dissolve_GDAL_temporary layer](https://user-images.githubusercontent.com/53575300/62330983-541ee500-b4b2-11e9-9dbc-1f356fd0d160.png)

**Comment by gioman** [comment] 2019-08-01 22:21
> Ah so for you the temporary dissolved layer also has holes infilled?

no, for me on Linux 3.4: QGIS, GDAL and SAGA tools all fill some holes if first I don't fix the input. After fixing the input on QGIS tools returns the expected result. GRASS dissolve always return the expected result (just add a field in your input filled with the same values for all features, then dissolve by this field).

**Comment by dalyk85** [comment] 2019-08-01 22:35
Ah ok. I'm using windows 10. When I fix the input geometry and then dissolve, the output polygon still has some holes infilled like so...



![Dissolve_GDAL_saved layer](https://user-images.githubusercontent.com/53575300/62331805-fd66da80-b4b4-11e9-8abe-4e527361a4ac.png)

**Comment by gioman** [comment] 2019-08-01 22:37
> the output polygon still has some holes infilled like so

with what tool? we have 4 :)

**Comment by dalyk85** [comment] 2019-08-01 22:50
For dissolve QGIS, GDAL, SAGA and GRASS. I can't get any of the four to produce an output matching the single part input layer in terms of holes as well as dissolving the internal boundary polylines. This is after I have fixed the input geometry layer

**Comment by strk** [comment] 2020-02-26 09:45
This bug has been reported by @MDavidson17 to happen also when dissolving outside of QGIS (using ST_Union) - I guess the title of this issue can be changed again. It's really about rendering a shapefile rather than products of a tool.

**Comment by strk** [comment] 2020-02-26 09:46
@dalyk85 if you can still reproduce, can you do so with a single shapefile, with no dissolving tools involved in the excercise ? If so, can you reduce the shapefile as much as possible while still reproducing the problem ? Can you then attach that shapefile and report the version of OGR you're using ?

**Comment by gioman** [comment] 2020-02-26 18:27
@strk 

> @dalyk85 if you can still reproduce, can you do so with a single shapefile, 

the sample data was provided here https://github.com/qgis/QGIS/issues/31041#issuecomment-517363669

>with no dissolving tools involved in the excercise ?

what do you mean? wrong output out of a dissolving operation is the whole point of this ticket.


>Can you then attach that shapefile and report the version of OGR you're using ?


I made new tests on QGIS 3.10.3 and the results are better than the last time I checked.

SAGA and OGR return the correct results even if not fixing the input geometries.

QGIS dissolve (by design) does not run if there are invalid geoms, after fixing them the result in the expected one.


QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Windows 7 SP 1 (6.1)

**Comment by dwsilk** [comment] 2020-02-26 23:38
I think, as @dalyk85 had suspected, that this was a rendering issue and not a problem with any of the QGIS dissolve tools.

I get it on QGIS 3.4.15 / GDAL 2.2.3 - but given that QGIS 3.10.3 became the LTR ~1 week ago, I guess the solution will now be to upgrade. :smile:

**Comment by gioman** [comment] 2020-02-27 09:17
closing?

**Comment by strk** [comment] 2020-02-27 09:22
Let's wait for a confirmation. @dwsilk can you update and verify ?

**Comment by dwsilk** [comment] 2020-02-27 09:50
Yep, it appears to be fixed in QGIS 3.10.3 / GDAL 3.0.4

**Comment by strk** [comment] 2020-02-27 09:57
Great, thanks for testing !

**Closed by strk** 2020-02-27 09:57 UTC
Labels: Bug, Feedback
