### ISSUE TITLE
QGIS works incorectly with SRS 5513

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28935] opened 2019-01-29 09:16 UTC
Author Name: **Vladimír Hans** (Vladimír Hans)
Original Redmine Issue: [21117](https://issues.qgis.org/issues/21117)
Affected QGIS version: 3.4.4
Redmine category:projection_support

---
I created point layer with srs 5513 in GeoPackage. Enter new point by plugin "Lat Lon Tools" with coordinates of trigonometric point. This point saved correctly in positive valus of coordinates, but QGIS didn't show. If I exported points to SRS 5513 (layer localities), they were saved with negative values of coordinates. This points are in Czech Republic and coordinates in SRS 5513 could bee in positive values.

---

- [pokus.gpkg](https://issues.qgis.org/attachments/download/14189/pokus.gpkg) (Vladimír Hans)

**Comment by nyalldawson** [comment] 2019-06-11 02:22
Please reopen if still reproducible under 3.8 and proj 6.1 -- all transformation handling is now done using Proj's CRS database, which has fixed many issues like this.

Issues like this won't be addressed in the LTR release, due to the complexity of CRS handling in that release and the risk of breaking other components of QGIS.

**Closed by nyalldawson** 2019-06-11 02:22 UTC
Labels: Bug, Projections/Transformations, Won't fix
