### ISSUE TITLE
Ability to have continuous raster legend in legend tree

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29051] opened 2019-02-11 16:36 UTC
Author Name: **Saber Razmjooei** (@saberraz)
Original Redmine Issue: [21233](https://issues.qgis.org/issues/21233)

Redmine category:map_legend

---
It would be great to have an option (or even switch to) continuous raster colour instead of blocks:

---

- [legend.png](https://issues.qgis.org/attachments/download/14278/legend.png) (Saber Razmjooei)
- [continuous.png](https://issues.qgis.org/attachments/download/14280/continuous.png) (Saber Razmjooei)

**Comment by nyalldawson** [comment] 2020-05-02 22:58
Duplicate of #17844

**Closed by nyalldawson** 2020-05-02 22:58 UTC
Labels: Feature Request, Map and Legend
