### ISSUE TITLE
QGIS crashes: save project as geopackage

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#31310] opened 2019-08-20 09:11 UTC
## User Feedback

saving project to geopackage

## Report Details

*Crash ID*: d8b7a54a86f76032fae98484940c9b4c326da7f4

*Stack Trace*
<pre>
QString::multiArg :
QString::arg :
wildcards :
QgsProject::write :
CPLStringList::operator[] :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-08-20 13:30
Can't confirm on 3.8.1 on Linux. Would you mind checking on a new/clean QGIS profile, thanks.

**Comment by eurojam** [comment] 2019-08-20 15:28
just tested it with a new profile, but same result. also with 3.9

**Comment by gioman** [comment] 2019-08-20 15:29
> just tested it with a new profile, but same result. also with 3.9

what your project contain?

**Comment by eurojam** [comment] 2019-08-20 15:37
one vectorlayer with lines (shapefile). also tried to first import the lines into a gpk and then save the project with that vectorlayer into the same gpk.

**Comment by gioman** [comment] 2019-08-20 15:43
> one vectorlayer with lines (shapefile)

can you post it?

**Comment by eurojam** [comment] 2019-08-20 15:48
https://files.wheregroup.com/index.php/s/ZabeYQ59G2H7igb

**Comment by gioman** [comment] 2019-08-20 15:55
> https://files.wheregroup.com/index.php/s/ZabeYQ59G2H7igb

no problems here on Linux and QGIS 3.8.2.

**Comment by eurojam** [comment] 2019-08-20 16:00
so you load the layer and then save the project into the same gpk?

**Comment by gioman** [comment] 2019-08-20 16:00
> so you load the layer and then save the project into the same gpk?

yes

**Comment by eurojam** [comment] 2019-08-20 16:00
will try it when I will back in office on an other computer (also windows)

**Comment by elpaso** [comment] 2019-08-20 16:02
works fine here on Linux/master

**Comment by eurojam** [comment] 2019-08-20 16:11
it's just a video how it happens on my computer: https://files.wheregroup.com/index.php/s/TetErXTsG9eigc5

**Comment by yopyop25** [comment] 2019-08-29 10:18
hello, I have the same problem in win10
Version de QGIS
3.8.2-Zanzibar

**Comment by tecbabel** [comment] 2019-09-08 11:20
Same problem for me, QGIS 3.8.2, Win 10. Could it be that there is a problem if the gpkg is not on the same drive as the QGIS installation-drive? As long as I have the Geopackage on C-drive, it works - but not on my D-drive (where I store my data).

Everything work perfect as long as I save it to my Desktop (C-drive/installation-drive where QGIS is installed): create new project, add a few layers, safe all the layers to the same gpkg-file and than safe the project to the same gpkg. Works perfect on C:/

When I try exactly the same on my D-drive (data-drive), then the crash happens. If I restart QGIS and try to inspect the saved gpkg from QGIS Browser Window, the file created before on C-drive shows me all the layers AND the saved project. I can re-open the safed project and everything is perfect. I can rename or move the gpkg to any other folder on C and re-open the project (just have to change the path for the layers).

When I copy the gpkg file to D-drive, in the QGIS browser-window I only see the layers, but NOT the project. It's the same file that works on C:/ - even after rename or moving to an other folder.

**Comment by elpaso** [comment] 2019-09-10 10:42
I'm testing on windows10 right now, I can save the GPKG project into C:/ and E:/ (another partition on the same drive) without issues.

I'm also testing on a network drive (a samba share), address of the file is `//192.168.99.45/VBoxShared/shared.gpkg` and this does not allow to save the project, it silently fails but there is no crash.

I think that this issue is related to network drives only, because it works just fine if the path is on a partition of a local drive.

Can you confirm my findings so far?

Is your failing drive a network drive using the SMB protocol?

**Comment by eurojam** [comment] 2019-09-10 12:19
Yes partially I can confirm your findings: I can reproduce it on a different machine (windows7) like this:
- Geopackage on Drive C - where QGIS is installed: worked
- Geopackage on Drive D local disk: crashed
- Geopackage on a network drive (SMB): crashed

**Comment by tecbabel** [comment] 2019-09-10 12:27
My posting was based on my windows-machine at home, now I'm at the office, working with 
another windows-machine, where I can reproduce the crash: Create new layer, safe it to a 
new gpkg on local drive D, try to safe the project to the same gpkg - QGIS crashes. 

D:/ here on this machine is primary partition, a local drive (standard data-drive, NTFS) - see 
attached screeshot from the disk management. 

What I do in detail to reproduce the error:

1.) Start QGIS 3.8.2. Zanzibar (Standalone-Installer, NOT OSGeo4W) on Win 10 Enterprise, 
x64
2.) Menu Project - new (unsaved)
3.) Menu Layer - create new layer - geopackage layer
4.) in dialog-window: Database: navigate to drive D:/ (local!) , add a name (here: test.gpkg) 
select geometry-type: points, close with OK
5.) new layer: toggle edit mode, add a few points, toggle edit mode
6.) menu project - safe as - GeoPackage - 
7.) in dialog-window: connection: navigate to and select D:/(....)/test.gpkg; project:add a 
name as project-title (here: project1)

see screenshot attached for this step

As soon as I hit OK, the crash produces, see report below

Crash ID: e7011e5af9861f5af44505412c289594af0a914a


Stack Trace


QString::multiArg :
QString::arg :
wildcards :
QgsProject::write :
CPLStringList::operator[] :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763




Am 10 Sep 2019 um 3:43 hat Alessandro Pasotti geschrieben:

I'm testing on windows10 right now, I can save the GPKG project into C:/ and E:/ (another 
partition on the same drive) without issues.
I'm also testing on a network drive (a samba share), address of the file is 
//192.168.99.45/VBoxShared/shared.gpkg and this does not allow to save the project, it 
silently fails but there is no crash.
I think that this issue is related to network drives only, because it works just fine if the path is 
on a partition of a local drive.
Can you confirm my findings so far?
Is your failing drive a network drive using the SMB protocol?
-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

Der folgende Teil dieser Nachricht enthält einen Anhang im
sogenannten Internet MIME Nachrichtenformat.
Wenn Sie Pegasus Mail oder ein beliebiges anderes MIME-kompatibles
Email-System verwenden, sollten Sie den Anhang mit Ihrem Email-System
speichern oder anzeigen können. Gegebenenfalls fragen Sie Ihren Administrator.

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any another MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- Datei Information/File information -----------
     Datei/File:  DEFAULT.BMP
     Datum/Date:  21 Sep 2001, 14:59
     Größe/Size:  358 bytes.
     Typ/Type:    Unbekannt

Der folgende Teil dieser Nachricht enthält einen Anhang im
sogenannten Internet MIME Nachrichtenformat.
Wenn Sie Pegasus Mail oder ein beliebiges anderes MIME-kompatibles
Email-System verwenden, sollten Sie den Anhang mit Ihrem Email-System
speichern oder anzeigen können. Gegebenenfalls fragen Sie Ihren Administrator.

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any another MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- Datei Information/File information -----------
     Datei/File:  qgis_crash.jpg
     Datum/Date:  10 Sep 2019, 14:10
     Größe/Size:  194694 bytes.
     Typ/Type:    JPEG-image

Der folgende Teil dieser Nachricht enthält einen Anhang im
sogenannten Internet MIME Nachrichtenformat.
Wenn Sie Pegasus Mail oder ein beliebiges anderes MIME-kompatibles
Email-System verwenden, sollten Sie den Anhang mit Ihrem Email-System
speichern oder anzeigen können. Gegebenenfalls fragen Sie Ihren Administrator.

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format.
If you are using Pegasus Mail, or any another MIME-compliant system,
you should be able to save it or view it from within your mailer.
If you cannot, please ask your system administrator for assistance.

   ---- Datei Information/File information -----------
     Datei/File:  disk_management.jpg
     Datum/Date:  10 Sep 2019, 14:24
     Größe/Size:  229289 bytes.
     Typ/Type:    JPEG-image

**Comment by elpaso** [comment] 2019-09-10 12:40
Thanks for checking, I think we have two related issues here:

1. cannot load or save projects from/to a GPKG stored on a network drive (such as `\\192.168.99.1\MyShare\db.gpkg`), I've been able to reproduce this issue and I have made a patch, I will make a PR very soon
2. crash when storing a project into a geopackage loaded from a local drive different than `C:`, the destination gpkg was selected by opening the file browser dialog and not from a stored GPKG connection (worths checking if this case works).

I've not been able to reproduce case 2 on win10, indeed I've always done all my tests on drive `D:` instead of `C:` and I've never had any issue, I've also tried to select the destination file by browsing the file system instead of using a stored connection.

In any event, there is a tiny chance that my patch will also fix this issue.

I've never seen a crash anyway, the worst case was a silent failure in saving the project (which is also fixed by my patch).

**Comment by elpaso** [comment] 2019-09-10 12:41
just to be clear: I'm not saying that this is not an issue, just that **I** cannot reproduce it on my machines and if I cannot reproduce it I cannot fix it.

**Comment by tecbabel** [comment] 2019-09-10 13:01
@ elpaso:
What do you mean by not using the file browser dialog, but selection from a stored GPKG connection? If I just select the GPKG from the pop-up-list as in the screenshot? Same result: QGIS crashes. Or how to select GPKG?
(https://user-images.githubusercontent.com/55049648/64615930-c650e680-d3db-11e9-8d9c-c47fce44cf27.jpg)

**Comment by elpaso** [comment] 2019-09-10 13:06
Yes, that was what I meant, because I didn't originally test the file browser, btw now I checked both cases and they don't make any difference (they both work).

**Closed** 2019-09-11 05:37 UTC
Labels: Bug, Feedback, Windows

**Comment by tecbabel** [comment] 2019-09-20 08:19
Tested with QGIS 3.8.3.  - problem solved: I can save a qgis-project to a pre-existing gpkg - no crash. Thanks
