### ISSUE TITLE
qgis flatpak - can't find SIP module

### ISSUE THREAD

**Issue by dragonfly-lover** [qgis/QGIS#39643] opened 2020-10-27 09:53 UTC
**Describe the bug**

installing latest qgis 3.14 flatpak i get this error message:
impossible to load SIP module 
![image](https://user-images.githubusercontent.com/36678626/97284014-d1194580-1840-11eb-9a59-e058eb67a5b6.png)
So qgis functions are limited and many layers can't be visualized.

**How to Reproduce**

flatpak install org.qgis.qgis

**QGIS and OS versions**

Versione di QGIS | 3.14.16-Pi | Revisione codice QGIS | a235a149
-- | -- | -- | --
Compilato con Qt | 5.15.1 | Esecuzione con Qt | 5.15.1
Compilato con GDAL/OGR | 3.0.4 | Esecuzione con GDAL/OGR | 3.0.4
Compilato con GEOS | 3.8.1-CAPI-1.13.3 | Esecuzione con GEOS | 3.8.1-CAPI-1.13.3
Compilato su SQLite | 3.32.1 | In esecuzione su SQLite | 3.32.1
Versione client PostgreSQL | 12.2 | Versione SpatiaLite | 4.3.0a
Versione QWT | 6.1.5 | Versione QScintilla2 | 2.11.5
Compilato con PROJ | 6.3.1 | Esecuzione con PROJ | Rel. 6.3.1, February 10th, 2020
Versione SO | KDE Flatpak runtime

**Additional context**

OS is Ubuntu 18.04 + kde Neon.

I don't exactly know what a flatpak does, but i think qt 5.15 should be statically linked inside the flatpak. if not, my system has qt 5.14. can it help?

**Comment by Gustry** [comment] 2020-10-27 09:58
Duplicate of https://github.com/qgis/QGIS/issues/39603

**Closed by Gustry** 2020-10-27 09:58 UTC
Labels: Bug
