### ISSUE TITLE
QGIS crashed

### ISSUE THREAD

**Issue by vminano** [qgis/QGIS#31099] opened 2019-08-05 19:07 UTC
Crash ID: f3b94088ad28fd40600a5d0e06b9c43ac6243e50

Stack Trace

RtlRaiseStatus :
memset :
setjmpex :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by vminano** [comment] 2019-08-05 19:09
QGIS CHASED WHEN i TRY TO SET NEW LOCALIZATION EN NUEVO DIRECTORIO DE MAPAS

**Comment by roya0045** [comment] 2019-08-05 20:56
Could you provide steps, I'm not sure what you were trying to do.

**Comment by vminano** [comment] 2019-08-05 21:35
yes

I am try install or load grass gis

thanks a lot

**Comment by vminano** [comment] 2019-08-05 22:40
[cid:122ee1df-99db-4b25-9514-a4293c2fa786]

________________________________
De: Alex <notifications@github.com>
Enviado: lunes, 5 de agosto de 2019 08:56 p. m.
Para: qgis/QGIS <QGIS@noreply.github.com>
CC: vminano <vladiuni@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [qgis/QGIS] QGIS CRASED (#31099)


Could you provide steps, I'm not sure what you were trying to do.

**Comment by gioman** [comment] 2019-08-06 12:07
> I am try install or load grass gis

@vminano do you mean that *within QGIS* you are trying to create a new GRASS location/mapset with the QGIS/GRASS plugin?

**Comment by vminano** [comment] 2019-08-06 14:10
yes ist correct, how I can solve that please.

thanks.

Vladimir minano

________________________________
De: Giovanni Manghi <notifications@github.com>
Enviado: martes, 6 de agosto de 2019 12:07 p. m.
Para: qgis/QGIS <QGIS@noreply.github.com>
CC: vminano <vladiuni@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [qgis/QGIS] QGIS CRASED (#31099)


I am try install or load grass gis

@vminano<https://github.com/vminano> do you mean that within QGIS you are trying to create a new GRASS location/mapset with the QGIS/GRASS plugin?

**Comment by gioman** [comment] 2019-08-06 14:46
Duplicate of https://github.com/qgis/QGIS/issues/30317

**Closed by gioman** 2019-08-06 14:46 UTC
Labels: Bug, Feedback
