### ISSUE TITLE
The temporary point in the `georeferencer` window moves when you change the extent (pan, zoom in/out)

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#50864] opened 2022-11-11 07:27 UTC
### What is the bug or the crash?

Unexpected behavior:
The temporary point in the `georeferencer` window moves when you change the extent (pan, zoom in/out).

Expected behavior:
The temporary point must remain where you put it.

### Steps to reproduce the issue

1. Open Georeferencer.
2. Add any point.
3. Change extent (zoom in/out or pan).

![qgis-bin_Ra412KpqGI](https://user-images.githubusercontent.com/20655102/201288241-c2dd663b-0978-4857-b3cd-84ef375a4e04.gif)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.5.2 | Running against GDAL/OGR | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
Compiled against SQLite | 3.39.4 | Running against SQLite | 3.38.1
Compiled against PDAL | 2.4.3 | Running against PDAL | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
ContrastHomogenizer | 3.2
fast_field_filler | 1.0
FreehandRasterGeoreferencer | 0.8.3
Go2NextFeature3 | 2.1
latlontools | 3.6.6
loadthemall | 3.3.0
MapsPrinter | 0.9
pluginbuilder3 | 3.2.1
PluginLoadTimes | 3.0.1
plugin_reloader | 0.9.2
profiletool | 4.2.2
qgsAzimuth | 0.9.15
quick_map_services | 0.19.32
rasterstats | 0.4.3
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f3](https://github.com/qgis/QGIS/commit/ed3ad0430f3)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.2
Running against GDAL/OGR
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
Compiled against SQLite
3.39.4
Running against SQLite
3.38.1
Compiled against PDAL
2.4.3
Running against PDAL
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
ContrastHomogenizer
3.2
fast_field_filler
1.0
FreehandRasterGeoreferencer
0.8.3
Go2NextFeature3
2.1
latlontools
3.6.6
loadthemall
3.3.0
MapsPrinter
0.9
pluginbuilder3
3.2.1
PluginLoadTimes
3.0.1
plugin_reloader
0.9.2
profiletool
4.2.2
qgsAzimuth
0.9.15
quick_map_services
0.19.32
rasterstats
0.4.3
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2022-11-11 09:40
Duplicate of #44986

**Closed by uclaros** 2022-11-11 09:40 UTC
Labels: Bug, Georeferencer
