### ISSUE TITLE
GSB File missing on macOS

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#31453] opened 2019-08-27 18:20 UTC
Adding a layer downloaded from 

https://dados.gov.pt/en/datasets/freguesias-de-portugal/

(first layer listed there), I get prompted to manage the transformation:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/178003/63797085-fbefcd00-c90f-11e9-87e5-6177fc92c29b.png">

However the needed gsb file is not there:

```
File 'ptLX_e89.gsb' not found in directory '/Applications/QGIS3.9.app/Contents/Resources/proj/proj'
```

Mac package downloaded from QGIS nightly builds.

QGIS version | 3.9.0-Master | QGIS code revision | 6af029d52e
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |  

QGIS version | 3.9.0-Master | QGIS code revision | 6af029d52e
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |

**Comment by timlinux** [comment] 2019-08-27 18:20
cc @PeterPetrik

**Comment by gioman** [comment] 2019-08-27 19:28
> However the needed gsb file is not there:

@timlinux Hi Tim, this is not a QGIS issue, we must submit the gsb grids for Portugal upstream to Proj. Recently we got the green light to do that by the entity (DGT) that creates them. Shortly after I committed to submit them to Proj, but then I had some issues and forgot to do that. I'm still committed to do this pr against proj, in the meantime you can grab the gsb files here: https://github.com/NaturalGIS/naturalgis_ntv2_transformations_grids_and_sample_data/tree/master/pt

**Comment by nyalldawson** [comment] 2019-08-27 19:50
I think Tim's issue is that it's being presented as a valid choice, yet shouldn't be (since the grid is missing).

Anyway - this is already fixed in Proj 6 builds.

**Comment by timlinux** [comment] 2019-08-27 21:01
Thanks -@gioman - I tested with the file you provided and it fixes the issue it seems:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/178003/63807614-c2768c00-c926-11e9-96fb-09d489fd0bd9.png">


@nyalldawson there is another minor issue in that the dialog is not resizable so the full message in the dialog is not readable.

@

**Comment by nyalldawson** [comment] 2019-08-27 21:29
@timlinux are you sure it fixed the issue? Your dialog is now showing a different pair of CRS. Anyway, this is all total poop on proj < 6. The sooner we can make proj 6 a hard dependency of QGIS the better the world will be.

>  there is another minor issue in that the dialog is not resizable so the full message in the dialog is not readable.

Sounds like a MacOS specific issue - I can't reproduce.

**Comment by timlinux** [comment] 2019-08-28 05:06
> Your dialog is now showing a different pair of CRS

Hooo you are right I missed that

Ok I will hold on for PROJ6

**Comment by gioman** [comment] 2019-08-30 08:24
See https://github.com/OSGeo/proj-datumgrid/pull/54

I think this can be closed.

**Comment by PedroVenancio** [comment] 2019-09-02 14:50
Hi @nyalldawson 

The PR to proj datum grids with portuguese grids needed by @timlinux was merged yesterday 
https://github.com/OSGeo/proj-datumgrid/commit/46e538feb7ce906e6cf1deb4efbd96443d72d287

So, they will be available soon.

However, OSGeo4W is using old versions of proj datum grids, missing the most recent ones:

![proj-datumgrid_version](https://user-images.githubusercontent.com/1331581/64121896-fd017e00-cd97-11e9-87cf-b1610d60fd20.jpg)

On another side, OSGeo4W is putting these grids on ..\OSGeo4W64\share\proj folder, which I believe will be the final location when the PROJ>=6 will be fully supported by QGIS (and other software). However, at this moment, QGIS dev is expecting these grids in ..\OSGeo4W64\apps\proj-dev\share\proj folder, and the interface does not show the location where the grids should be placed:

![Datum_Transformation_QGIS_dev](https://user-images.githubusercontent.com/1331581/64122151-b3656300-cd98-11e9-990c-f707e4250815.jpg)

Just says that they are not available in the system.

Can this be polished in some way?

**Comment by nyalldawson** [comment] 2019-12-13 05:58
Should all be fixed in recent versions

**Closed by nyalldawson** 2019-12-13 05:58 UTC
Labels: Bug, MacOS
