### ISSUE TITLE
printing layout doesn't consider layer blending mode

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#54143] opened 2023-08-08 16:33 UTC
### What is the bug or the crash?

When you apply a blending mode to a layer, "multiplay" for istance, the output image doesn't consider it and it depict as a solid color.
I tried all .PNG, .SVG and .PDF

### Steps to reproduce the issue

1. make a project
2. make a layer 
3. style it and apply a blending mode to all the layer (the option bottom to the left in the window GUI
4. export the image

### Versions

Versione di QGIS
3.28.8-Firenze
Revisione codice QGIS
5ac45272b58
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.0
Versione PROJ
9.2.1
Versione database del Registro EPSG
v10.088 (2023-05-13)
Versione GEOS
3.11.2-CAPI-1.17.2
Versione SQLite
3.41.1
Versione PDAL
2.5.3
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
azimuth_distance_measurement
0.4
latlontools
3.6.13
qgis_points2one
0.3.1
rvt-qgis
0.9.6
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2023-08-11 17:03
@Forna73, thanks for reporting. I cannot replicate the issue using the very QGIS version, as you can see in the following screencast:

https://github.com/qgis/QGIS/assets/16253859/1e71545d-c734-429e-b0be-ffed32e823cf

Could you please try if the issue does occur also using a new QGIS user profile? If yes, please specify with more details the steps needed to replicate the issue and or provide a sample project and layers.

**Comment by Forna73** [comment] 2023-08-11 22:41
Hi!
I'm trying with a new profile, and it happens randomly... this is strange...
When I'll get much more time I'll go deeper trying several options.
Now I have 2 projects exactly the same and one has the problem and the other not?!?!?
Is there any option in the map windows relative to rendering in the layout composer? I can't find any...

**Comment by nyalldawson** [comment] 2023-08-11 22:42
Do you have label masks enabled in your project?

**Comment by Forna73** [comment] 2023-08-11 22:44
OMG... I need to search deeper... maybe some where....

**Comment by nyalldawson** [comment] 2023-08-11 22:47
If so, it's a duplicate of https://github.com/qgis/QGIS/issues/50526

**Comment by Forna73** [comment] 2023-08-11 22:49
But they are not rasters... in my case are line set with a width in "map unit" that are in "multiply" blending mode....

**Comment by Forna73** [comment] 2023-08-11 22:51
I can't understand why in a project they blend in the correct way in the other they are solid coloured....

**Comment by Forna73** [comment] 2023-08-11 22:55
I can't understand.... the mask could be in any layer?

**Comment by Forna73** [comment] 2023-08-11 23:03
YES!... I've found and old layer where the mask option was active.... Now it works well..... thanks a lot!
This MASK option seems to be a real problem, cause I read  often about strange behaviours when enabled.
I'm also trying to avoid this features cause it often causes crash... above all when there are a lot of labels in a little space.

**Comment by nyalldawson** [comment] 2023-08-11 23:14
Duplicate of https://github.com/qgis/QGIS/issues/50526

**Closed by nyalldawson** 2023-08-11 23:14 UTC
Labels: Feedback, Bug
