### ISSUE TITLE
ESRI .vtpk can not be rendered in QGIS Desktop when zooming in to higher scales

### ISSUE THREAD

**Issue by GallPeters** [qgis/QGIS#52872] opened 2023-04-24 06:37 UTC
### What is the bug or the crash?

Hi, 
I created .vtpk from sample .shp using ArcGIS Pro 2.9.1 using ArcGIS Pro 'Create Vector Tiles Package' GP tool.
The .vtpk was flat (not indexed) and was based on ESRI WGS84_Geographic_Coordinate_System_V2.xml tiling scheme
(.vtpk, .shp and .xml attached). Then I dragged and dropped .vtpk into QGS Desktop 3.28.1. When I zoomed in into higher scale then 1:2910 the .vtpk vanished from the screen.

I tried to change some components in the process inclulding:
- Upgrade ArcGIS Pro version (3.0.2) and QGIS Desktop version (3.30.1)
- Change .vtpk tiling scheme xml in ArcGIS GP tool parameters in order to change .vtpk coordinate system (used EPSG: 4326, 3395, 3857).
- Modify the minimum and maximum cached scales in ArcGIS GP tool parameters.
- Modify the maximum and minimum zoom in QGIS Desktop symbology pane.
- Change QGIS project coordinate system (used EPSG: 4326, 3395, 3857).
Despite of all my attempts QGIS Desktop refuse to render the .vtpk in higher scales.

Thanks in advance,
Jossef

[attachments.zip](https://github.com/qgis/QGIS/files/11307250/attachments.zip)
[test_qgs_proj.zip](https://github.com/qgis/QGIS/files/11307306/test_qgs_proj.zip)

 

### Steps to reproduce the issue

Above

### Versions

Above

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment] 2023-05-02 05:37
@GallPeters 

I've had a look, and this is an indexed VTPK, which is currently NOT supported by QGIS.

You can tell by extracting the .vtpk archive, and looking at the "root.json" file. It contains: `"type": "indexedVector"`.

Closing as duplicate of https://github.com/qgis/QGIS/issues/52874

**Comment by nyalldawson** [comment] 2023-05-10 02:37
Actually this is NOT a indexed vtpk, and this IS a valid bug report.

Looking further into this I suspect that ESRI software will detect a zero size tile and automatically fallback to lower zoom level tiles transparently. I.e. they treat EVERY vtpk a bit like an indexed VTPK, but without the up-front tilemap information. We could do the same.

**Closed** 2023-05-22 02:50 UTC
Labels: Bug, ArcGIS vector tile data provider
