### ISSUE TITLE
QGIS Browser is missing icon for Vector Tile Layers

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#53094] opened 2023-05-13 10:08 UTC
### What is the bug or the crash?

The browser panel is missing the [icon](https://github.com/qgis/QGIS/blob/master/images/themes/default/mIconVectorTileLayer.svg) for Vector Tiles Layers when viewing the contents of a QGIS Project. 

### Steps to reproduce the issue

1. Save a QGIS Project that contains a vector tiles layer
2. In the Browser Panel navigate to the folder location of the saved project
3. Open the dropdown to show contents of the project file

<img width="481" alt="missing_vectortiles_icon" src="https://github.com/qgis/QGIS/assets/78353871/56a8f4c1-687b-4e73-bacf-2bef03951eed">

### Versions

QGIS 3.30.2 s'Hertogenbosch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment] 2023-05-15 03:42
I can't reproduce this on current master -- can you test please?

**Comment by mblesius** [comment] 2023-05-15 08:21
Just tested with QGIS-Version 3.31.0-Master QGIS-Codeversion 7b284fee19

Can't reproduce, seems to be fixed 👍

**Comment by nyalldawson** [comment] 2023-05-29 05:29
Fixed in 3.32

**Closed by nyalldawson** 2023-05-29 05:29 UTC
Labels: Feedback, GUI/UX, Bug, QGIS Browser, Vector tiles
