### ISSUE TITLE
python error- standard deviational ellipse

### ISSUE THREAD

**Issue by alanamckeon** [qgis/QGIS#58764] opened 2024-09-16 15:16 UTC
### What is the bug or the crash?

python error- an error has occurred while executing python code 
Type error: setValue(self, value: int) argument 1 has unexpected type 'float' 

### Steps to reproduce the issue

go to plugin 
install plugins
type standard deviational ellipse
install plugin 
exit window 
hover over vector to display menu 
click standard deviational ellipse
error pops up 

### Versions

Version 3.34.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2024-09-16 16:50
@alanamckeon, thanks for reporting. "The issue is related to an external third-party plugin. If the issue concerns a third party plugin (downloaded with the plugin manager) then it can't be fixed by the QGIS core team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description)."
You could fix the issue applying the changes to the plugin code in your QGIS user profile folder as described at https://github.com/havatv/qgisstandarddeviationalellipseplugin/pull/13/files.

**Closed by agiudiceandrea** 2024-09-16 16:50 UTC
Labels: Bug
