### ISSUE TITLE
Crash on startup dev vesrion 3.11.0-6

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#32632] opened 2019-11-04 22:54 UTC
## User Feedback

Crash on startup of version 3.11.0-6

## Report Details

**Crash ID**: [e2b6bd2e605690d5963e3c2ddd9c77f2254309de]('https://github.com/qgis/QGIS/search?q=e2b6bd2e605690d5963e3c2ddd9c77f2254309de&type=Issues')

**Stack Trace**
<pre>
QBasicMutex::unlockInternal :
</pre>

**QGIS Info**
QGIS Version: 3.11.0-Master
QGIS code revision: c86ed789bf
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.0dev
Running against GDAL: 3.1.0dev

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by grantboxer** [comment] 2019-11-04 22:55
Hangs on start-up with "initialise File Filters"

**Comment by gioman** [comment] 2019-11-04 23:14
duplicate of #32592 ? @grantboxer

**Comment by grantboxer** [comment] 2019-11-04 23:28
I updated via the network installer this morning but I get the same problem

 

Cheers Grant

**Comment by nyalldawson** [comment] 2019-11-05 00:02
Yes, this is a duplicate of the other ticket (already fixed). The osgeo4w builds are probably too young to have the fix yet

**Closed by nyalldawson** 2019-11-05 00:02 UTC
Labels: Bug, Feedback

**Comment by grantboxer** [comment] 2019-11-05 00:09
Still having the problem this morning, after a new download. Do I need to wait a little longer or do I have to blitz the entire OSGeo4W64 folder?

 

Also the link to download the Standalone installer for 3.10 from the QGIS download page is still broken this morning.

 

Cheers Grant
