### ISSUE TITLE
Error: Raster Map not found

### ISSUE THREAD

**Issue by frede791** [qgis/QGIS#55133] opened 2023-11-02 15:56 UTC
### What is the bug or the crash?

When trying to run a .las file in QGIS version 3.22.4 I get an error saying:
```
ERROR: Raster map <outpute6921994bebc4aaa9a52ef7fdec3084f> not found
ERROR: Raster map or group <outpute6921994bebc4aaa9a52ef7fdec3084f> not found
```

Here is my configuration
```
g.proj -c wkt="/tmp/processing_GnumIZ/333089713bb84461807ada8d4eececc9/crs.prj"
g.region n=3339350.0 s=3338250.0 e=3338250.0 w=324865.0 res=100.0
r.in.lidar input="/home/fremarkus/Downloads/points.las" method="n" type="CELL" zrange=-10000.0,10000.0 zscale=1 intensity_range=-10000.0,10000.0 intensity_scale=1 percent=100 pth=1 resolution=1 class_filter="2" -e -n output=outpute6921994bebc4aaa9a52ef7fdec3084f --overwrite
g.region raster=outpute6921994bebc4aaa9a52ef7fdec3084f
r.out.gdal -t -m input="outpute6921994bebc4aaa9a52ef7fdec3084f" output="/home/fremarkus/Downloads/output.tiff" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
```
Please advise on what to do here. 

### Steps to reproduce the issue

See above

### Versions

QGIS version: 3.22.4-Białowieża
Qt version: 5.15.3
Python version: 3.10.3
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment] 2023-11-03 09:01
@frede791, thanks for reporting. QGIS 3.22 is no longer supported. Please try if the issue does occur also using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new QGIS user profile as requested in the issue report form.
If the issue does occur also using a currently supported QGIS version, please provide:
- a sample layer
- exact steps to replicate the issue
- the missing info requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."

**Comment by frede791** [comment] 2023-11-03 10:44
@agiudiceandrea 
Thank you for the response I have updated my QGIS version and tried again to no avail. 
I am folllowing this guide with the layer provided in the tutorial and all other steps replicated as shown there
https://www.pointsnorthgis.ca/blog/blog/dem-from-lidar-using-open-source-software-tutorial/


My system is:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS




Active Python plugins
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
db_manager
0.1.20

**Comment by agiudiceandrea** [comment] 2023-11-03 11:35
@frede791, please consider that usually a developer have limited time to debug an issue for free. So, please provide the minimum steps (e.g. pointing out which part of the tutorial exactly leads to the issue) and layer to replicate the issue in order to have more chances that the issue will be fixed.

**Comment by frede791** [comment] 2023-11-03 14:51
Of course. Here are the steps:
1. Download the Dataset for Trinity River from this dataset catalog: https://portal.opentopography.org/dataCatalog
2. Open QGIS and in a new project, under Project->Properties->CRS find and apply the NAD83 / UTM zone 15N (Authority ID: EPSG: 26915) Coordinate Reference System. 
3. Click the cog called Toolbox in the top row (or open with ctrl + alt + t) and search for the r.in.lidar setting.
4. In this setting adjust the following parameters:
    -> LAS input file to downloaded file
    -> Statistic to use for raster values: n
    -> Storage type for resultant raster maps: CELL
    -> Filter range for z data: min: -10000, max: 10000
    -> Scale to apply to z data: 1
    -> Filter range of intensity values: min: -10000, max: 10000
    -> Scale to apply to intensity values: 1
    -> Only import points of selected classes: 2
5. In the advanced parameters tick the first three boxes 
    -> Use the extent of the input for the raster extent
    -> Set computation region to match the new raster map
    -> Override projection check
6. Set the GRASS GIS 7 region extent to: 325932.190921, 324865.23594, 3339345.806159, 3338251.653494

After this click `Run` at the bottom right and you should be able to get the error I got.

**Comment by agiudiceandrea** [comment] 2023-11-05 10:28
@frede791, I cannot replicate the reported issue on my Windows 10 system using QGIS 3.34.0 with GRASS 8.3.1.

What is the GRASS-GIS version used by QGIS in your Ubuntu system? Could you please provide the full execution processing log? Have you tried if the issue does occur also directly using GRASS-GIS available in your system?
Note: the tutorial at https://www.pointsnorthgis.ca/blog/blog/dem-from-lidar-using-open-source-software-tutorial/ mentions to set `Output raster resolution=1` and doesn't mention to set a GRASS GIS 7 region extent.

**Comment by frede791** [comment] 2023-11-06 08:10
My Ubuntu system is using GRASS-GIS 7.8.7. I am not quite sure what you mean by "using GRASS-GIS directly"? I forgot to mention the `Output raster resolution` parameter, but I did set it to 1. 

Here is the full log output:
```
QGIS version: 3.34.0-Prizren
QGIS code revision: ffbdd678812
Qt version: 5.15.3
Python version: 3.10.12
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2023-11-06T09:01:52
Algorithm 'r.in.lidar' starting…
Input parameters:
{ '-d' : False, '-e' : True, '-i' : False, '-j' : False, '-n' : True, '-o' : True, '-v' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : '324865.235940000,325932.190921000,3338251.653494000,3339345.806159000', 'base_raster' : None, 'class_filter' : '2', 'input' : '/home/fremarkus/Downloads/points.las', 'intensity_range' : [-10000,10000], 'intensity_scale' : 1, 'method' : 0, 'output' : '/home/fremarkus/Downloads/test.tiff', 'percent' : 100, 'pth' : None, 'resolution' : 1, 'return_filter' : '', 'trim' : None, 'type' : 0, 'zrange' : [-10000,10000], 'zscale' : 1 }

g.proj -c wkt="/tmp/processing_GaJEaS/d27a1dbc5e4e4a76a25e01c872941ffb/crs.prj"
g.region n=3339345.806159 s=3338251.653494 e=325932.190921 w=324865.23594 res=100.0
r.in.lidar input="/home/fremarkus/Downloads/points.las" method="n" type="CELL" zrange=-10000.0,10000.0 zscale=1 intensity_range=-10000.0,10000.0 intensity_scale=1 percent=100 resolution=1 class_filter="2" -e -n -o output=output9e652ac6d2294eb0b0cf66056e43ecf4 --overwrite
g.region raster=output9e652ac6d2294eb0b0cf66056e43ecf4
r.out.gdal -t -m input="output9e652ac6d2294eb0b0cf66056e43ecf4" output="/home/fremarkus/Downloads/test.tiff" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
Starting GRASS GIS...
Cleaning up temporary files...
Executing </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> ...
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
/tmp/processing_GaJEaS/grassdata/grass_batch_job.sh: 4: r.in.lidar: not found
ERROR: Raster map <output9e652ac6d2294eb0b0cf66056e43ecf4> not found
ERROR: Raster map or group <output9e652ac6d2294eb0b0cf66056e43ecf4> not found
Execution of </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Starting GRASS GIS...
Cleaning up temporary files...
Executing </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> ...
ERROR: Raster map <output9e652ac6d2294eb0b0cf66056e43ecf4> not found
ERROR: Raster map or group <output9e652ac6d2294eb0b0cf66056e43ecf4> not found
Execution of </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Execution completed in 0.37 seconds
Results:
{'output': '/home/fremarkus/Downloads/test.tiff'}

Loading resulting layers
The following layers were not correctly generated.
• /home/fremarkus/Downloads/test.tiff
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
QGIS version: 3.34.0-Prizren
QGIS code revision: ffbdd678812
Qt version: 5.15.3
Python version: 3.10.12
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2023-11-06T09:05:46
Algorithm 'r.in.lidar' starting…
Input parameters:
{ '-d' : False, '-e' : True, '-i' : False, '-j' : False, '-n' : True, '-o' : True, '-v' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : '324865.235940000,325932.190921000,3338251.653494000,3339345.806159000', 'base_raster' : None, 'class_filter' : '2', 'input' : '/home/fremarkus/Downloads/points.las', 'intensity_range' : [-10000,10000], 'intensity_scale' : 1, 'method' : 0, 'output' : '/home/fremarkus/Downloads/test.tiff', 'percent' : 100, 'pth' : None, 'resolution' : 1, 'return_filter' : '', 'trim' : None, 'type' : 0, 'zrange' : [-10000,10000], 'zscale' : 1 }

g.proj -c wkt="/tmp/processing_GaJEaS/eaa9d94fd6944c59bf3aefabb8ef126b/crs.prj"
g.region n=3339345.806159 s=3338251.653494 e=325932.190921 w=324865.23594 res=100.0
r.in.lidar input="/home/fremarkus/Downloads/points.las" method="n" type="CELL" zrange=-10000.0,10000.0 zscale=1 intensity_range=-10000.0,10000.0 intensity_scale=1 percent=100 resolution=1 class_filter="2" -e -n -o output=output79a6e18301804242b49c83300be18f23 --overwrite
g.region raster=output79a6e18301804242b49c83300be18f23
r.out.gdal -t -m input="output79a6e18301804242b49c83300be18f23" output="/home/fremarkus/Downloads/test.tiff" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
Starting GRASS GIS...
Cleaning up temporary files...
Executing </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> ...
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
/tmp/processing_GaJEaS/grassdata/grass_batch_job.sh: 4: r.in.lidar: not found
ERROR: Raster map <output79a6e18301804242b49c83300be18f23> not found
ERROR: Raster map or group <output79a6e18301804242b49c83300be18f23> not found
Execution of </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Starting GRASS GIS...
Cleaning up temporary files...
Executing </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> ...
ERROR: Raster map <output79a6e18301804242b49c83300be18f23> not found
ERROR: Raster map or group <output79a6e18301804242b49c83300be18f23> not found
Execution of </tmp/processing_GaJEaS/grassdata/grass_batch_job.sh> finished.
Cleaning up temporary files...
Execution completed in 0.33 seconds
Results:
{'output': '/home/fremarkus/Downloads/test.tiff'}

Loading resulting layers
The following layers were not correctly generated.
• /home/fremarkus/Downloads/test.tiff
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

**Comment by agiudiceandrea** [comment] 2023-11-06 09:21
@frede791 it looks like the issue is due to the fact that the r.in.lidar tool is missing in GRASS-GIS in your system (see in the log: "r.in.lidar: not found").
The r.in.lidar peocessing algorithm in QGIS cannot succeeds if the r.in.lidar GRASS-GIS tool is missing.
You need to report such issue to the GRASS-GIS maintainers for Ubuntu systems.

**Comment by alexbruy** [comment] 2023-11-12 10:55
Not a QGIS issue, I successfully can perform all steps on Ubuntu with GRASS 8.3.1 from the "ubuntugis-unstable" repository. Probably GRASS in standard repository is not built with PDAL support.

**Closed** 2023-11-12 12:11 UTC
Labels: Feedback, GRASS, Processing, Bug
