### ISSUE TITLE
QGIS crashes when saving a manually-changed vertex coordinate in the vertex editor table

### ISSUE THREAD

**Issue by afrigeri** [qgis/QGIS#32003] opened 2019-09-25 13:11 UTC
**bug description**

When saving a vector layer after manually editing the vertex coordiates with the vertex tool of a point, QGIS crashes (QGIS died on signal 11[New LWP 8475])

**How to Reproduce**

1. Open a new session
2. Create a new point(s) vector layer (any format - scratch layer included)
3. Add two point features
4. Click on Vertex tool icon
5. Right click on a vertex and change manually the coordinates (at bottom left in the gui)
6. Click on the pencil / save the layer -> Crash

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.4 (Ubuntu 11.4-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 |   |  

**Additional context**

**Comment by nirvn** [comment] 2019-09-25 13:15
Very likely fixed in 3.8.4, can you try with the latest release and confirm crash is gone?

**Comment by afrigeri** [comment] 2019-09-27 09:32
Did not get a way to have the 3.8.4 from an ubuntu repo.  I've tried with the 3.8.3 (available from ubuntu-nightly-release) but the same issue is there.  

Installed the 3.9 (ubuntu-nightly ) and now the Vertex editor does not show the table view with right-click on the point.

QGIS version | 3.9.0-Master | QGIS code revision | a26834076f
-- | -- | -- | --
Compiled against Qt | 5.12.2 | Running against Qt | 5.12.2
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu 19.04 | This copy of QGIS writes debugging output.
Active python plugins | timemanager; qgis2web; SVG2ColoR; GeoWrap; profiletool; temporalprofiletool; DataPlotly; gimpselectionfeature_plugin; openlayers_plugin; beePen; MapsPrinter; mmqgis; qconsolidate3; FreehandRasterGeoreferencer; DigitizingTools; VectorBender; db_manager; processing

**Comment by nirvn** [comment] 2019-09-27 09:38
@afrigeri , hey, you're the first person who has pasted the version content of the About window into an open issue, congrats! :tada: 

Joking apart, you have quite a few non-default python plugins that could be the cause of your crasher. Try with a clean profile, or with all plugins disabled, to see if the crash still happens.

**Comment by gioman** [comment] 2019-09-27 09:46
> Try with a clean profile

a new/clean profile is preferred to disabling plugins, we had cases in the past that a bad, disabled plugin was causing issues anyway.

**Comment by afrigeri** [comment] 2019-09-27 19:50
Thanks, guys.  Here on the laptop OsX QGIS 3.8.3 the vertices coordinate editor works flawlessly as well as the saving process after the edit.  On Monday I'll be back to the Ubuntu workstation and try with the clean profile/plugins disabled.  I'll report in here.

**Comment by afrigeri** [comment] 2019-10-01 14:40
I confirm that with a clean profile (settings->new profile) the coordinates Vertex editor works flawlessly both on QGIS  3.8.3-Zanzibar (code revision  0b21735e28) and QGIS-dev on the Ubuntu machine.  Thanks for the suggestion.

**Closed** 2019-10-01 14:40 UTC
Labels: Bug, Feedback

**Comment by nirvn** [comment] 2019-10-01 14:53
@afrigeri , if you want to go the extra mile, you can try to reactivate your plugins one by one until you find the culprit. I'm sure the plugin author would be happy to know about this.
