### ISSUE TITLE
Blurry layouts in v3.32.2, not after v3.28.2

### ISSUE THREAD

**Issue by luanero** [qgis/QGIS#54579] opened 2023-09-14 02:30 UTC
### What is the bug or the crash?

The layout in V3.32.2 appears blurry, but the same layout in V3.28.2 does not.  I've attached the screenshots from same monitor to illustrate the issue.
<img width="1920" alt="v3 32 2_blurry" src="https://github.com/qgis/QGIS/assets/80796685/70452e60-7719-43d1-930a-9c70c874ecc7">
<img width="1920" alt="v3 28 2_notblurry" src="https://github.com/qgis/QGIS/assets/80796685/e51b5917-e1b3-4fbb-9380-63bb359eda54">

### Steps to reproduce the issue

open equivalent workspaces in 3.28 and 3.31 and compare layouts, I'm viewing mine at 155% magnification. 

### Versions

v3.28.2 and v3.32.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by mblesius** [comment] 2023-09-14 20:03
This is likely a duplicate of the issue #54205 I reported. I closed mine as your screenshots are better in showing that it affects the whole layout.

**Closed** 2024-01-31 07:40 UTC
Labels: Regression, Bug, Print Layouts
