### ISSUE TITLE
qgis

### ISSUE THREAD

**Issue by thanawit30** [qgis/QGIS#32221] opened 2019-10-12 03:06 UTC
QList::size :
QAbstractTableModel::index :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by DelazJ** [comment] 2019-10-12 06:07
@thanawit30 developers can't do anything with your current report other than guessing you got a crash. As indicated in the crash report and the issue report template, please tell more about the context:
- what you were doing when it happens
- can you reproduce it
- your OS and version of QGIS

Thanks.

**Comment by roya0045** [comment] 2019-10-12 11:28
possible duplicate of #32224 ?

**Comment by gioman** [comment] 2019-10-12 11:52
@thanawit30 also please use meaningful subject/titles.

**Comment by m-kuhn** [comment] 2019-10-29 11:19
> possible duplicate of #32224 ?

Close as duplicate

**Closed by m-kuhn** 2019-10-29 11:19 UTC
Labels: Bug, Feedback
