### ISSUE TITLE
missing expression is_layer_visible()

### ISSUE THREAD

**Issue by eurojam** [qgis/QGIS#51135] opened 2022-12-07 05:45 UTC
### What is the bug or the crash?

the documented (https://docs.qgis.org/3.28/en/docs/user_manual/expressions/functions_list.html?highlight=is_layer_visible#is-layer-visible) expression function `is_layer_visible()` is missing

### Steps to reproduce the issue

- open select by expression
- goto "general" 

### Versions

3.22, 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2022-12-07 12:46
The function is not available in all context. For expressions in the layout, it is present.

**Comment by nyalldawson** [comment] 2022-12-08 01:46
To further explain: it's only available in contexts where the expression is directly associated with a particular map (or map canvas). So it's available in layout maps, and in symbology, but not in tools which aren't associated with any individual map like the "select by expression" tool. The issue is that if the user has multiple maps open then "is_layer_visible" no longer has any clear meaning.

**Comment by nyalldawson** [comment] 2022-12-08 01:47
Closing as wont-fix.

**Closed by nyalldawson** 2022-12-08 01:47 UTC
Labels: Expressions, Bug
