### ISSUE TITLE
Icons are messed up in dropdown lists (MacOS)

### ISSUE THREAD

**Issue by jaakla** [qgis/QGIS#35683] opened 2020-04-09 08:53 UTC
**Describe the bug**
Dropdown lists with text+icon the icon is messed up to wrong location - see attached images

**How to Reproduce**
Seems to happen in all text+label lists, e.g. renderer selection, label type selection, in both dialogs and toolbar. Very few selections, e.g. snapping layer selection does not have the problem, but next to it snap type selection has.

**QGIS and OS versions**

macOS 10.15.4
Issue started sometimes before QGIS 3.10 and after 3.4. 
Happens in QGIS versions 3.10 LTS, 3.12, 3.13 (nightly - about attached)
Does NOT happen in QGIS 3.4 LTS (and olders)

![Screen Shot 2020-04-09 at 11 49 20](https://user-images.githubusercontent.com/5609650/78876992-da83c180-7a58-11ea-9bf3-8beeafa6af62.png)
![Screen Shot 2020-04-09 at 11 46 35](https://user-images.githubusercontent.com/5609650/78877000-dc4d8500-7a58-11ea-8343-36c7b75c15e3.png)
![Screen Shot 2020-04-09 at 11 08 16](https://user-images.githubusercontent.com/5609650/78877005-dce61b80-7a58-11ea-9c95-61fe7b3ec80d.png)
![Screen Shot 2020-04-09 at 11 06 44](https://user-images.githubusercontent.com/5609650/78877008-dd7eb200-7a58-11ea-8974-a43d9d050e6d.png)
![Screen Shot 2020-04-09 at 11 03 47](https://user-images.githubusercontent.com/5609650/78877012-de174880-7a58-11ea-8150-de83e705749a.png)

Older version 3.4 LTS:

![Screen Shot 2020-04-09 at 11 05 17](https://user-images.githubusercontent.com/5609650/78877009-de174880-7a58-11ea-91ab-d1ee29aad30a.png)

Last confirmed with:
![Screen Shot 2020-04-09 at 11 56 47](https://user-images.githubusercontent.com/5609650/78877258-3d755880-7a59-11ea-930e-0da0be409529.png)

**Comment by gioman** [comment] 2020-04-10 10:14
@jaakla does it happens with the default QGIS theme?

**Comment by Gustry** [comment] 2020-04-10 12:19
Duplicate of https://github.com/qgis/QGIS/issues/34032 and mainly https://github.com/qgis/QGIS/issues/32248 

Wait for Qt 5.12.5

**Closed** 2020-04-10 12:19 UTC
Labels: Bug, Feedback, GUI/UX, MacOS

**Comment by jaakla** [comment] 2020-04-10 17:58
@gioman **no**, it does not happen with default, great hint! So changing theme from "night mapping" to "default" fixed it! It looks quite the same in my dark OS theme, so I'm not sure what the other (broken) theme is even supposed to do.

@Gustry note that it does not depend on Qt version, in both my broken 3.4 and latest dev had same Qt 5.12.3 versions. But as given above, it does not depend even on QGIS version either, it now seems to be really a broken theme.
