### ISSUE TITLE
Aggregate function bug on macOS version

### ISSUE THREAD

**Issue by giovanniborga** [qgis/QGIS#32932] opened 2019-11-18 15:17 UTC
**Bug description:**
**Note that it occurs ONLY WITH MACOS VERSION of QGIS.**
For numeric fields, setting "first_value" on aggregate function inside AGGREGATE process dialogue doesn't take effect. Processing tool returns always SUM of numeric values.

**How to Reproduce:**
1) Open a new project on a QGIS MACOS System
2) Add a vector layer
3) Choose Vector Geometry -> Aggregate from Geoprocessing Tools panel
4) Set input layer and a **numeric field as aggregate field**
5) Set some aggregate functions for existing fields
6) Set "first_value" for the field used in step 4 to get references for results dataset rows
7) execute
8) check result: values in filed used in step 4 **are summed instead of first_values**

**QGIS and OS versions:**
All 3.x versions (until 3.10) for MAC OS.

**Comment by gioman** [comment] 2019-11-18 15:18
it works as expected on other platforms?

**Comment by giovanniborga** [comment] 2019-11-18 15:20
Yes. On Windows it works perfectly!

**Comment by gioman** [comment] 2019-11-18 15:22
> Yes. On Windows it works perfectly!

is data dependent?

**Comment by giovanniborga** [comment] 2019-11-18 15:24
do you mean "data-type" dependant?

**Comment by gioman** [comment] 2019-11-18 15:24
> do you mean "data-type" dependant?

also, but also if it happens with specific datasets rather than any dataset.

**Comment by giovanniborga** [comment] 2019-11-18 15:32
I teach GIS from several years ... having students with both Windows and MAC OSes. I think I saw this bug about almost 3 years ago and it has never been solved (I suppose few persons encountered it).
I used different datasets and everytime I encountered the bug so, yes, I think it happens with any dataset... I don't know if the bug occurs on string fields; I remember only that numeric fields were always summed instead of selected the first value … (I cannot reproduce the bug now because I'm a MS user)

**Comment by gioman** [comment] 2019-11-18 15:38
> so, yes, I think it happens with any dataset.

just to be sure an you attach a dataset where you observe this? thanks.

**Comment by giovanniborga** [comment] 2019-11-18 15:49
[buildings.zip](https://github.com/qgis/QGIS/files/3859419/buildings.zip)
Today we worked with this tiny layer.
Just aggregate by "zones_id", compute count of "NUMERO", sum of "volume" and first of "zones_id".
MAC users just had zones_ids summed instead of first_selected.

**Comment by gioman** [comment] 2019-11-18 15:59
@giovanniborga for what is worth, I get expected results on Linux/QGIS 3.4. I can't test on macOS.

**Comment by DelazJ** [comment] 2019-11-19 11:50
I'm afraid the issue is worse. Here's the settings in the aggregates dialog, using Mojave
![image](https://user-images.githubusercontent.com/7983394/69144106-d5829d80-0aca-11ea-8a45-9c85b324229d.png)
Here's the call when it's executed
![image](https://user-images.githubusercontent.com/7983394/69144193-0793ff80-0acb-11ea-83ca-8adfe80858cc.png)

Everything is about SUM though I asked none

**Comment by giovanniborga** [comment] 2019-11-19 12:36
I supposed it was so ...

**Comment by gioman** [comment] 2020-01-08 17:08
I also see this now that I can test on macOS...

**Comment by gioman** [comment] 2020-01-08 17:09
For a quick check compare to results given by the "group stats" plugin.

**Comment by PeterPetrik** [comment] 2020-10-06 12:41
Cannot replicate with the latest master anymore https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20201005_122844.dmg

![Screenshot 2020-10-06 at 14 39 44](https://user-images.githubusercontent.com/804608/95202626-dce58f00-07e1-11eb-956d-e96b6faf6064.png)

![Screenshot 2020-10-06 at 14 40 12](https://user-images.githubusercontent.com/804608/95202642-e1aa4300-07e1-11eb-984e-b1f746219b14.png)

**Comment by gioman** [comment] 2020-12-21 18:37
Closing for lack of further feedback.

**Closed by gioman** 2020-12-21 18:37 UTC
Labels: Bug, Feedback, MacOS
