### ISSUE TITLE
3D without elevation layer renders badly

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28511] opened 2018-12-01 13:27 UTC
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [20691](https://issues.qgis.org/issues/20691)
Affected QGIS version: 3.4.2
Redmine category:3d

---
If I don't have an elevation layer to generate the terrain QGIS should apply a flat terrain model so I can render 3D objects from vector layers.
It does render, but pan, zoom and orbit is "jumpy" and unpredictable. Even the simplest models renders poorly (attached file).

As soon as a terrain layer is applied as elevation source, all issues are resolved.

---

- [Skärmbild från 2018-12-01 14-24-41.png](https://issues.qgis.org/attachments/download/13889/Sk%C3%A4rmbild%20fr%C3%A5n%202018-12-01%2014-24-41.png) (Klas Karlsson)

**Comment by wonder-sk** [comment] 2019-05-27 11:39
When you used flat terrain model, how big was the area that was displayed in the 3D view? A whole country? the whole world? 

Currently QGIS 3D has issues when working with an area that is too large. The fact that you applied a terrain model just made the scene much smaller, avoiding those issues (related to numerical stability)

**Comment by klakar** [comment] 2019-05-29 13:14
I don't remember the exact conditions and have moved on to 3.6 since then, and when I test quickly right now it seems to work predictable in 3.6.3.
The example above, as I remember it, was using large datasets, and tile services as basemaps, but the view window only covered a few blocks of a city.

**Comment by Pedro-Murteira** [comment] 2022-03-17 16:18
@klakar Hello, I'm not being able to reproduce this issue. Did you come across this issue on more recent versions?

**Comment by klakar** [comment] 2022-03-17 16:29
Close it!

**Closed** 2022-03-17 16:30 UTC
Labels: 3D, Bug
