### ISSUE TITLE
QGIS crashes when "open directory" is selected from the recent projects contextual menu

### ISSUE THREAD

**Issue by bellanz80** [qgis/QGIS#40665] opened 2020-12-18 19:41 UTC
Hi.
I open QGIS: no project, no layer loaded
I right-clicked on a recent project and chose to open its directory -->> crash

**Windows 10 64 bit**
**QGIS 3.16.1 StandAlone** 
**Clean Profile**

**It is the same problem as a previous issue, already closed
https://github.com/qgis/QGIS/issues/31630**

![image](https://user-images.githubusercontent.com/38449926/102654160-b4f59e80-4135-11eb-8d0c-db014bfd4b9f.png)

![image](https://user-images.githubusercontent.com/38449926/102654166-b921bc00-4135-11eb-8ca3-70c8884f259e.png)

Crash ID: 5b7d7853716001199e29628e91df8bb8e06ddcdd

Stack Trace

QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:458
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1637
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.1-Hannover
QGIS code revision: b381a90dca
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by pigreco** [comment] 2020-12-18 19:43
I confirm and add that it also happens in the master

Crash ID: 6b5c5effa82d74926e7821c9530e43b45763a9a1


Stack Trace


QtSharedPointer::ExternalRefCountData::getAndRef :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:462
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :




QGIS Info
## QGIS Version: 3.17.0-Master
## QGIS code revision: e488a57afc
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.3.0dev
Running against GDAL: 3.3.0dev



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment] 2020-12-18 20:02
Also 3.10.12 on windows, but Linux (3.12 and 3.16) is ok.

**Comment by gioman** [comment] 2020-12-18 20:04
Regression,  as per https://github.com/qgis/QGIS/issues/31630

**Comment by agiudiceandrea** [comment] 2020-12-21 09:06
On windows, the issue doesn't occur with QGIS 3.4.15.
It seems to occur from version 3.6.0 onward and also with QGIS 3.14.0, which contain the patch provided by https://github.com/qgis/QGIS/pull/36738 to solve https://github.com/qgis/QGIS/issues/31630.
So probably https://github.com/qgis/QGIS/issues/31630 didn't fix the issue.

**Comment by PeterPetrik** [comment] 2021-02-16 13:35
i can replicate on MacOS with these steps
- open QGIS: no project, no layer loaded
- right-clicked on a recent project and chose to open its directory 
- file dialog opens, click on "X" to close it -->> crash

**Comment by agiudiceandrea** [comment] 2021-02-16 13:47
I can also confirm on Windows with QGIS 3.16.3.

**Comment by roya0045** [comment] 2021-02-16 14:52
@PeterPetrik I had a quick look at it previously and the only difference between this crashing version and other implementation was the initiation of the QAction. Maybe making it static instead of lambda would solve this somehow.

**Comment by PeterPetrik** [comment] 2021-02-16 14:57
this https://github.com/qgis/QGIS/pull/41591/commits/2bd5218fe01406529a1c22d4a7d49441a0dd3560 looks like solves crash on MacOS, but I assume the original issue is still there

**Closed** 2021-02-17 20:28 UTC
Labels: Bug, Crash/Data Corruption, Regression, Windows

**Comment by dlejay** [comment] 2023-05-03 09:47
I am getting this issue with macOS 13.3.1 (a)
and:
Homebrew QGIS 3.30.2 or .dmg QGIS LTR 3.28.6

but not with MacPorts QGIS 3.28.6
