### ISSUE TITLE
Ctrl+click does not close new polygons on vector file MacOS (multiple versions) Q3.10 & 3.14

### ISSUE THREAD

**Issue by juancobravo** [qgis/QGIS#38846] opened 2020-09-17 18:44 UTC
Neither do Option+click, Shift+click or Command+Click. Two fingers on track pad (+click) work but instructions in documentation don't mention it and may not be available in older macs or when operating a mouse.

**Comment by uclaros** [comment] 2020-09-17 19:49
The shortcut you are looking for is "right-click"

**Comment by juancobravo** [comment] 2020-09-17 20:01
I guess it is but on most apps ctrl+click serves as right click, from when Apple mice had only one button. Not sure what they look now as I use only trackpad and stylus

**Comment by DelazJ** [comment] 2020-09-17 21:17
> Two fingers on track pad (+click) work but instructions in documentation don't mention it and may not be available in older macs or when operating a mouse.

Docs contributors are not necessarily using macOS. Would be nice if mac users could help [improve the docs](https://github.com/qgis/QGIS-Documentation) with their specific instructions.
Duplicate of #31279 (seems there's a workaround on trackpad)

**Closed by DelazJ** 2020-09-17 21:17 UTC
Labels: Bug

**Comment by juancobravo** [comment] 2020-09-17 22:49
Thank you . This all helps me understand the QGIS project better.
