### ISSUE TITLE
ProductCode or ProductVersion missing in the .MSI file for Microsoft Intune

### ISSUE THREAD

**Issue by macnotiz** [qgis/QGIS#51729] opened 2023-02-04 21:58 UTC
### What is the bug or the crash?

When I try to upload the QGIS-OSGeo4W-3.28.3-1.msi or QGIS-OSGeo4W-3.22.15-1.msi file in M365 Endpoint manager for deployment / distribution via intune, I receive the following error:

The selected app package does not appear to have either a ProductCode or ProductVersion.

I checked with Orca and it seems that the infos are set. Any ideas?

### Steps to reproduce the issue

Endpointmanager > Apps > Windows > Add > 

### Versions

3.28.3-1 and 3.22.15-1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment] 2023-02-04 22:47
Duplicate of #45333

**Closed by jef-n** 2023-02-04 22:47 UTC
Labels: Bug
