### ISSUE TITLE
Measuring an angle causes a crash to desktop

### ISSUE THREAD

**Issue by tonywob** [qgis/QGIS#52361] opened 2023-03-23 20:12 UTC
### What is the bug or the crash?

Using the measure tool for angles, once the angle has been measured and the result shown, clicking the close button will cause qgis to crash and close to desktop without an error. This bug has existed for a while and is still not fixed in version 3.30

### Steps to reproduce the issue

Open up any layer using any projection, e.g. Use an OSM tile layer
Select the edge of a building, and using the angle measure tool, measure the angle, it will report a correct result
Click the close button on the popup... boom.. crash to desktep

### Versions

All versions up to 3.30 that I've used. Always been an issue, but not reported until now

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Not tested this in Windows.

I'm using Mac OS 13.2.1 on an M2 Macbook Pro (ARM chip). I don't recall it being a problem on the Intel macs, but I don't believe it was since I used qgis extensively then as well.

**Comment by agiudiceandrea** [comment] 2023-03-27 19:09
It seems to me the issue doesn't occur using QGIS 3.30 on Windows. Have you actually tried using a new QGIS user profile? Could you provide the full info requested in the issue report form (in particular Help->About info)?

**Comment by uclaros** [comment] 2024-07-04 20:54
Duplicate of #46151
Fixed in #56202

**Closed by uclaros** 2024-07-04 20:54 UTC
Labels: Map Tools, Bug, Crash/Data Corruption, macOS
