### ISSUE TITLE
QGIS fails to apply style file to rasters

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29427] opened 2019-03-18 15:55 UTC
Author Name: **Luís de Sousa** (Luís de Sousa)
Original Redmine Issue: [21611](https://issues.qgis.org/issues/21611)
Affected QGIS version: 3.6.1
Redmine category:symbology

---
I need have a number of .qml style files that I need to apply on raster maps. These .qml files were created with QGis itself, here is an example:
https://files.isric.org/soilgrids/legends/ORCDRC.qml

In QGis 3.4 I apply this style by accessing the layer context menu, then following _Properties_ -> _Symbology_ -> _Style_ and selecting the correct .qml file. While the _Properties_ menu is still on the map canvas shows the style correctly applied (Figure 1). But when I click OK and the _Properties_ dialogue closes the layer disappears (F1gure 2). If I open the _Properties_ dialogue again no style is displayed. 

Any cartograms (layouts) created with this layer are also affected.

---

- [QGis_Styles02.png](https://issues.qgis.org/attachments/download/14619/QGis_Styles02.png) (Luís de Sousa)
- [QGis_Styles01.png](https://issues.qgis.org/attachments/download/14620/QGis_Styles01.png) (Luís de Sousa)

---

Related issue(s): #29695 (duplicates)
Redmine related issue(s): [21880](https://issues.qgis.org/issues/21880)

---

**Comment by iona5** [comment] 2019-09-15 12:17
can confirm this is still happening for me on QGIS 3.8

Easy way to reproduce is to use the ESA CCI Land cover data and .qml file from http://maps.elie.ucl.ac.be/CCI/viewer/download.php (screenshots in bug #29695)

Steps:
- Load the raster layer/geoTIFF ESACCI-LC-L4-LCCS-Map-300m-P1Y-2015-v2.0.7
- right click layer properties -> go to Symbology (Symbology is "singleband grey")
- Style -> load Style... -> load "ESACCI-LCMapsColorLegend.qml"
- Observe that layer symbology changes with correct class labels and colors. canvas in the main window gets correctly updated as well. Note: legend in layer-view is NOT updated
- click "Apply"

Expected: Symbology stays correct and is also applied to legend in mainWindow
Actual: Symbology resets to "Blues" colorramp


QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 10.8 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by Spartacus1** [comment] 2019-10-22 21:24
I'm using 3.8.3 and this bug is still there. Very annoying bug.

**Comment by dbaston** [comment] 2019-11-07 19:41
Seeing this in 3.10.0 using official Docker image.

**Comment by Spartacus1** [comment] 2019-11-07 19:49
I'll try. If it works it would be awesome. Thank you dbaston.

**Comment by neteler** [comment] 2020-01-22 16:57
The bug is still present in 3.10.1

**Comment by elpaso** [comment] 2020-01-22 17:39
I can reproduce: it's seriously broken!

**Comment by gioman** [comment] 2020-01-22 17:41
> I can reproduce: it's seriously broken!

tagged as regression since March 2019 :(

**Comment by Spartacus1** [comment] 2020-01-23 00:08
We still can use it perfectly by replacing the QGIS libiconv.2.dylib extension by the system's one, as suggested by Peter. However it's an undesirable "bricolage".

**Comment by elpaso** [comment] 2020-01-23 09:43
I've investigated the issue with the ESACCI-LCMapsColorLegend.qml style and the problem is in the style file itself: it was created with QGIS 2.10 and the `classificationMinMaxOrigin="CumulativeCutFullExtentEstimated"` value is wrong.

The following style was created with QGIS 3 and it works perfectly:

[ESACCI-LCMapsColorLegend_3.x.zip](https://github.com/qgis/QGIS/files/4102247/ESACCI-LCMapsColorLegend_3.x.zip)

I'll check the other samples now.

**Comment by elpaso** [comment] 2020-01-23 10:15
The other sample https://files.isric.org/soilgrids/legends/ORCDRC.qml is missing a lot of information and I've no data to test it with.

I'm inclined to close this issue unless there are other test cases with QML actually exported by (a supported version of) QGIS.

**Comment by iona5** [comment] 2020-01-23 10:30
i agree with removing high priority if this is related to the qml file created by older versions which are unsupported.

the current behavior however is rather odd - seemingly applying the correct style and then reverting it back without any information. imo at least there should be a warning clearly stating an unsupported or broken file - bonus points for stating that it comes from an unsupported QGIS version.

also i would imagine this behavior does point to another underlying issue with the way symbologies are applied, but i couldn't figure that out from my limited debugging experience with qt/c++ and you have clearly a better picture of this.

**Comment by elpaso** [comment] 2020-01-23 10:45
@iona5 I cannot say I have a clear picture, the code is 12 years old and pretty complicated, but I've spent a few hours now trying to understand what's going on, by importing old/incomplete QMLs (like the test cases here) the style is first applied to the layer, then the layer properties widget is updated **from** the layer's renderer instance.

The fact is that in both sample cases, the ramp information is missing, so there is no ramp information and the default color ramp is loaded.

What happens next is different in the two cases: in ORCDRC there is no information about min/max at all and in that case it gets loaded from the raster actual values and the Min/Max value setting is set to  "Min/Max", in the other case there is no ramp but there is information about min/max, which is set to CumulativeCutFullExtentEstimated.

Both are wrong: the correct value should be "User defined", if you manually set it everything works as expected.

About reporting a warning there is no easy way to do it but I'll have a look, the only thing it comes to my mind is to check the condition where a source color ramp is missing and warn the user to check min/max settings.

**Comment by iona5** [comment] 2020-01-24 09:40
@elpaso yeah, i understand and thanks for the explanations. tried to have a brief look at the situation and honestly gave up a few hours in.

i really would love to find a nice solution here myself, but the code path is so convoluted and my skills are clearly lacking.

i do not insist on dragging this issue along, which is probably a very edge-y case (and a workaround exists). (i might work on this anyway someday ;) )

**Comment by elpaso** [comment] 2020-01-24 10:00
@iona5 a hand here would be very welcome. Closing for now.

**Closed by elpaso** 2020-01-24 10:00 UTC
Labels: Bug, Feedback, Symbology
