### ISSUE TITLE
More intuitive way to turn on/off several symbol layers

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#44677] opened 2021-08-12 18:18 UTC
### Feature description

It would be nice if instead of having the checkbox down  a small eye on/off symbol would be beside the symbol layer. This is useful when you have several layers and want to check how one looks by hiding the others. 

### Additional context

![image](https://user-images.githubusercontent.com/4627073/129248245-cf472751-a487-4a19-aa2a-6e9c38aa11ee.png)

**Comment by DelazJ** [comment] 2021-08-13 14:49
Duplicate of #33861?

**Comment by antoniolocandro** [comment] 2021-08-13 17:56
Yes, can you please merge

**Closed** 2021-08-13 18:58 UTC
Labels: Feedback, GUI/UX, Feature Request
