### ISSUE TITLE
Refresh fieldlist after adding new field

### ISSUE THREAD

**Issue by FlyingEagle** [qgis/QGIS#30560] opened 2019-07-05 07:35 UTC
When adding a new field to attribute table with right click on layer -> properties dialog -> sourcefields and then switching to tab attribute form to arrange the fields in the internal ui designer then the new fields is not there.
you have to close the dialog and reopen it, then it is there.

**Comment by DelazJ** [comment] 2019-07-05 08:03
Duplicate of #26350?

**Closed** 2019-07-05 09:05 UTC
Labels: Feature Request
