### ISSUE TITLE
'Add circle from two points' doesn't produce a true circle

### ISSUE THREAD

**Issue by gubuntu** [qgis/QGIS#38493] opened 2020-08-30 13:10 UTC
**Describe the bug**
this is the shape I get - note the dimples at top and bottom
<img width="678" alt="Screenshot 2020-08-30 at 15 06 54" src="https://user-images.githubusercontent.com/496911/91659862-c194af00-ead2-11ea-9ff5-c34a60605970.png">

**How to Reproduce**

Digitise a circle with the 'add circle from two points' tool

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | ORStools; SpreadsheetLayers; lrs; DataPlotly; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; qgis_resource_sharing; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; geocatbridge; timemanager; processing; db_manager; MetaSearch

**Comment by gioman** [comment] 2020-08-30 18:05
cannot replicate on Linux and Windows, need to check it on macOS.

**Comment by roya0045** [comment] 2020-08-31 11:40
I can get this when I try to modify the geometry as the two anchors don't move.

**Comment by gioman** [comment] 2020-08-31 12:00
> I can get this when I try to modify the geometry as the two anchors don't move.

but that is expected, I think.

**Comment by roya0045** [comment] 2020-08-31 14:18
Well personally if I want to expand a circle I would like for it to remain a circle and not become two conjoined blobs. But maybe that's just me.

**Comment by gioman** [comment] 2020-08-31 14:23
> Well personally if I want to expand a circle I would like for it to remain a circle and not become two conjoined blobs. But maybe that's just me.

after you finished draw it I think that QGIS doesn't know anymore that it is a circle, it is just a polygon/curve, I guess.

**Comment by roya0045** [comment] 2020-08-31 14:30
Yes that's the case, same with rectangles and other typical drawn forms, its just more apparent with circles, especially if you try to make an ellipse with it, it just make two spheres,

**Comment by agiudiceandrea** [comment] 2020-08-31 17:38
Maybe the [Shape Tools plugin](https://plugins.qgis.org/plugins/shapetools/) could be the right tool for this task.

**Comment by nyalldawson** [comment] 2020-08-31 19:46
I think there's an existing report about this -- it's only seen when the project is set to a geographic crs

**Comment by gioman** [comment] 2020-08-31 19:48
> I think there's an existing report about this -- it's only seen when the project is set to a geographic crs

@nyalldawson this one? https://github.com/qgis/QGIS/issues/38212

**Comment by nyalldawson** [comment] 2020-08-31 19:50
That sounds similar. I vaguely recall that there was one I filed/commented on too

**Comment by baswein** [comment] 2020-08-31 19:50
Is it possible that your project CRS and your digitizing layer CRS are different? 
Experimenting I found that if my project CRS is set to 3857 and my digitizing layer is 4326 I get the dimpled circle: 
![image](https://user-images.githubusercontent.com/15817745/91759721-1fdb9380-eba0-11ea-9c3a-2a2ffcd59559.png)
If my project is set to 4326 and my digitizing layer is set to 3857 I get an vertical eye shape:  
![image](https://user-images.githubusercontent.com/15817745/91760122-caec4d00-eba0-11ea-92ed-892f7613853e.png)
It seems like the bounding points a being created based on the project CRS but the arcs are being calculated based on the layer CRS.

**Comment by roya0045** [comment] 2020-08-31 20:08
@baswein if you change project afterward, to they change shape?

**Comment by baswein** [comment] 2020-08-31 20:15
They become either squatter or more stretched out depending on the original CRS but maintain their dimpled and eye shapes.

**Comment by gubuntu** [comment] 2020-09-01 07:29
My data source CRS was 4326 and digitising (project) CRS was TM. I think that's a common scenario and would expect the generated geometry to start off as a true circle in the project CRS.

**Comment by baswein** [comment] 2020-09-01 16:45
@gubuntu Totally agree that it should give you a circle in the project CRS hopefully someone can fix it soon. It seems that adding a circular string has the same issue. I was thinking that a clunky work around may be to create temporary scratch layer that is the same CRS as your project create the circles you want and then copy and paste them to your layer with the desired CRS but that produces the same issue.

**Comment by baswein** [comment] 2020-09-01 17:22
Also exporting a temporary scratch layer or geopackage from 3857 to 4326 had the same effect. The only way I figured out how to get a 3857 circle to export without becoming dimpled was to export it as a shapefile with the same CRS (I think as a shapefile it is no longer a circular string and instead becomes faceted) and then export it to 4326. Is it possible that this is a problem that effects the conversion of any layer with circular strings?

**Comment by rduivenvoorde** [comment] 2020-09-17 10:46
See https://github.com/qgis/QGIS/issues/38830 (closed) to easily reproduce. It is the switch between geo and non geo crs.

I also opt there to not give the ability to create circles and such in geo crs layers IF the project crs is non-geo crs...

I thought a workaround was to create the circles in a project AND layer in the 4326/geo crs and then copy them as a temporary scratch layer into a non geo crs project. That looks fine, but if you then copy them to your non geo crs layer they are warped again.

Note als that 'circles' in geo crs's like EPSG 4326 do not stay circles if you move them from the equator to the poles, UNLESS maybe if you define them as arc's?

**Comment by baswein** [comment] 2020-09-17 12:06
@rduivenvoorde I think it is more that just when you are digitizing and the CRS's are geo and non geo. Even if you digitize the geometry in the same CRS and they are true circles if you then re-project keeping the curve type geometry you will end up with the same issue. **I think this is will occur anytime you have curve geometry and are going from a geo to non geo crs and it is only obvious with circles.**
To try this create a geopackage with curvepoly type geometry in CRS 3857 and then add a circle or any geometry with curves.  
Do a Save features as and see that it is now bunned up. This happens with the geometry set to either the default (automatic) and polygon both keep it as curvepoly. I assume there is a way to convert it to non curve geometry in custom options. 
If however you start with a geopackage with the geometry type set to Polygon there is no bunning of course you loose the benefit of the curves.

When creating a temporary scratch layer there is no option to choose a non curve geometry. 
![image](https://user-images.githubusercontent.com/15817745/93468030-5dd4f900-f8bc-11ea-9427-2ac8e6e7376b.png)

**Comment by lbartoletti** [comment] 2020-09-23 04:45
> I think there's an existing report about this -- it's only seen when the project is set to a geographic crs

Yes, It's a duplicate of #25167

**Closed** 2020-09-23 09:51 UTC
Labels: Bug, Digitizing, Feedback

**Comment by BlytheDuckett1** [comment] 2022-05-09 15:30
OK, so you have to switch CRS to EPSG:3857. problem fixed
