### ISSUE TITLE
Qgis do not open..

### ISSUE THREAD

**Issue by wildlife23** [qgis/QGIS#41993] opened 2021-03-03 02:26 UTC
Hi

I am a person studying GIS through Qgis in Korea.
To upgrade qgis 3.16, I deleted the existing version and installed qgis3.16.
With the problem of "Could not load qgis_app.dll"
A message appears asking you to check the environment path of "qgis-ltr-bin.env"
It cannot be executed.
If any of you have experienced or solved this problem,
Any solution would be greatly appreciated.

If you look at the file of "qgis-ltr-bin.env", it is as follows.

PATH=C:\PROGRA~1\QGIS3~1.16\apps\qgis-ltr\bin;C:\PROGRA~1\QGIS3~1.16\apps\Python37;C:\PROGRA~1\QGIS3~1.16\apps\Python37 \Scripts;C:\PROGRA~1\QGIS3~1.16\apps\qt5\bin;C:\PROGRA~1\QGIS3~1.16\bin;C:\Windows\system32;C:\Windows;C:\Windows\ system32\WBem
GDAL_DATA=C:\PROGRA~1\QGIS3~1.16\share\gdal
GDAL_DRIVER_PATH=C:\PROGRA~1\QGIS3~1.16\bin\gdalplugins
GDAL_FILENAME_IS_UTF8=YES
GEOTIFF_CSV=C:\PROGRA~1\QGIS3~1.16\share\epsg_csv
JPEGMEM=1000000
OSGEO4W_ROOT=C:\PROGRA~1\QGIS3~1.16
PROJ_LIB=C:\PROGRA~1\QGIS3~1.16\share\proj
PYTHONHOME=C:\PROGRA~1\QGIS3~1.16\apps\Python37
PYTHONPATH=C:\PROGRA~1\QGIS3~1.16\apps\Python37;C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
QGIS_PREFIX_PATH=C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr
QT_PLUGIN_PATH=C:\PROGRA~1\QGIS3~1.16\apps\qgis-ltr\qtplugins;C:\PROGRA~1\QGIS3~1.16\apps\qt5\plugins
VSI_CACHE=TRUE
VSI_CACHE_SIZE=1000000
O4W_QT_PREFIX=C:/PROGRA~1/QGIS3~1.16/apps/Qt5
O4W_QT_BINARIES=C:/PROGRA~1/QGIS3~1.16/apps/Qt5/bin
O4W_QT_PLUGINS=C:/PROGRA~1/QGIS3~1.16/apps/Qt5/plugins
O4W_QT_LIBRARIES=C:/PROGRA~1/QGIS3~1.16/apps/Qt5/lib
O4W_QT_TRANSLATIONS=C:/PROGRA~1/QGIS3~1.16/apps/Qt5/translations
O4W_QT_HEADERS=C:/PROGRA~1/QGIS3~1.16/apps/Qt5/include
![qgis error](https://user-images.githubusercontent.com/79952598/109742860-22807980-7c13-11eb-8aae-0c1a0ef00224.PNG)

**Comment by gioman** [comment] 2021-03-03 12:02
Duplicate of https://github.com/qgis/QGIS/issues/41740

**Closed by gioman** 2021-03-03 12:02 UTC
Labels: Won't fix
