### ISSUE TITLE
Map rendering different from legend rendering using symbology-override

### ISSUE THREAD

**Issue by sylviaobk** [qgis/QGIS#55038] opened 2023-10-24 14:54 UTC
### What is the bug or the crash?

Hello, 
the legend in the layertree does not show the colours in the mapcanvas.
![image](https://github.com/qgis/QGIS/assets/20552367/0f455643-6883-47d5-b487-c70873a6776e)

### Steps to reproduce the issue

1. Add vectorlayer exampledata.gpkg
![image](https://github.com/qgis/QGIS/assets/20552367/1e3414cf-e723-4bd9-b108-7c37462512b5)

2. Layerproperties Symbology Categorized
Value field „legend_text“
![image](https://github.com/qgis/QGIS/assets/20552367/fa7d1321-d3e5-4347-a768-0a26f22848d7)

![image](https://github.com/qgis/QGIS/assets/20552367/0f43b2d4-7e87-40c1-ad5f-1075e08ce0f8)

Symbolsettings Fill Colour „Override“ button
![image](https://github.com/qgis/QGIS/assets/20552367/0dc1ce63-77dd-49e8-973d-cf02eb07dd41)

in expression editor choose field „rgba“
![image](https://github.com/qgis/QGIS/assets/20552367/0fcc3e7a-8af2-4192-a87c-703af14e7765)
3. Classify
![image](https://github.com/qgis/QGIS/assets/20552367/47f666b0-93e0-48f6-b85f-9c3df448249a)

![image](https://github.com/qgis/QGIS/assets/20552367/dde0a4ea-7277-4a6c-9073-4dc25ecfc634)

4. See error / Now here is the bug:
The legend is different to the map. In the map are correct colours from field „rgba“
![image](https://github.com/qgis/QGIS/assets/20552367/59cc86fd-9202-44ed-8dc9-c9709c414e30)

### Versions

QGIS-Version
3.28.4-Firenze
QGIS-Codeversion
fd0fb72ab3
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.2
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
attributeBasedClustering
2.2.1
bkggeocoder
1.3.3
drucker
3.1.0
geometry_paster
0.2
OSMDownloader
1.0.3
pluginbuilder3
3.2.1
postgis_geoprocessing
0.9
punkte_setzen
1.0
qdraw
3.0.2
spatial_filter
1.5
spw2_print_straßenverzeichnis
0.9.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by sylviaobk** [comment] 2023-10-24 14:58
[exampledata.zip](https://github.com/qgis/QGIS/files/13118422/exampledata.zip)

**Comment by roya0045** [comment] 2023-10-30 11:51
Not a bug, you chose to override the symbology to something feature based instead of the symbol provided by the renderer. This has been raised and closed previously. If you want it to match, use the renderer and set the color for each category instead of overriding it.

**Comment by roya0045** [comment] 2023-11-02 15:31
The proper solution would be to create a symbology file and use the color attribute of your feature to define the symbol color.  Would be doable with a custom processing tool.

**Comment by roya0045** [comment] 2024-09-27 13:16
Duplicate of #55038 , I added a processing alg in the original issue ticket, this should help.

**Comment by roya0045** [comment] 2024-09-29 13:27
My mistake with the ID, duplicate of #53065

**Comment by roya0045** [comment] 2024-09-29 13:31
@agiudiceandrea could you close this issue? I'm not sure 53065 should remain open either but as there are two solutions to correct the symbology, I'm not sure if the ticket should remain open.

**Closed** 2024-09-29 13:38 UTC
Labels: Map and Legend, Symbology, Bug
