### ISSUE TITLE
Crash QGis

### ISSUE THREAD

**Issue by ecallejasbriones** [qgis/QGIS#37865] opened 2020-07-17 21:54 UTC
i cant open anything archive, 

Crash ID: 2b5b8847e4fda81698b56c97b7805166938c74fd

Stack Trace

RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2211
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.14.0-Pi
QGIS code revision: 9f7028fd23
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by gioman** [comment] 2020-07-17 22:00
@ecallejasbriones please try with a new QGIS profile, no 3rd party plugins installed.

**Comment by ecallejasbriones** [comment] 2020-07-17 23:54
I installed 3.14 and now I installed 3.10 and they do not work opening a file, the program freezes and throws the following error:

Crash ID: 2b5b8847e4fda81698b56c97b7805166938c74fd


Stack Trace


RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:877
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CApartmentActivator::CreateInstance actvator.cxx:2185
CProcessActivator::CCICallback actvator.cxx:1636
CProcessActivator::AttemptActivation actvator.cxx:1523
CProcessActivator::ActivateByContext actvator.cxx:1367
CProcessActivator::CreateInstance actvator.cxx:1267
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
CClientContextActivator::CreateInstance actvator.cxx:566
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1970
ICoCreateInstanceEx objact.cxx:2211
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
DCA_SHExtCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.7-A Coru�a
QGIS code revision: 7b4ca4c8d0
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by agiudiceandrea** [comment] 2020-07-18 06:58
@ecallejasbriones you need to try to use a new user profile https://docs.qgis.org/3.10/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by roya0045** [comment] 2020-07-18 11:02
Duplicate of #34891

**Closed** 2020-07-18 11:39 UTC
Labels: Bug, Feedback

**Comment by ecallejasbriones** [comment] 2020-07-19 01:04
Thanks, I installed QGis 2.10 and it works fine for me!
