### ISSUE TITLE
Can't open r.drain

### ISSUE THREAD

**Issue by gambinhas** [qgis/QGIS#32686] opened 2019-11-06 12:35 UTC
I'm trying to use r.drain to calculate an optimal route, but it wont open. I'm using QGIS 3.4.13 with GRASS 7.6.1. While using the plugin, I can open all tools (r.cross, r.walk, etc) but r.drain.
I get the following message: 

![image](https://user-images.githubusercontent.com/57443545/68298602-b24efb80-0091-11ea-851d-a683b393ea36.png)

I've tried also with 3.10 and on different computers with the same result.
Can you please check if this is a bug?

Thanks in advance.

**Comment by roya0045** [comment] 2019-11-06 13:07
Do you mean the GRASS plugin or the processing toolbox?

**Comment by gambinhas** [comment] 2019-11-06 13:30
The plugin

**Comment by gioman** [comment] 2019-11-06 13:32
The plugin is broken (on Windows) and abandoned, use Processing instead.

This is also duplicate of another report.

**Comment by roya0045** [comment] 2019-11-06 18:40
@gambinhas if it works properly from the processing toolbox please close this issue.

**Closed** 2019-11-06 18:54 UTC
Labels: Bug, Feedback
