### ISSUE TITLE
mapCanvas().scene().items() causes crash in Qgis 3.10

### ISSUE THREAD

**Issue by dgreenewalt** [qgis/QGIS#32894] opened 2019-11-15 19:21 UTC
the line:
`gList = self.iface.mapCanvas().scene().items()`
Causes Qgis 3.10 to freeze and crash.  This line of code is fine in version 3.8

Adding VertexMarkers is still working properly, but it is no longer possible to generate a list of graphics on the scene using the above line.  From the list I want to delete certain graphics (vertex markers or rubber bands).

**Comment by nyalldawson** [comment] 2019-11-15 19:45
This is already fixed in master and for 3.10.1

**Closed by nyalldawson** 2019-11-15 19:45 UTC
Labels: Bug

**Comment by Gustry** [comment] 2019-11-15 19:47
Duplicate of https://github.com/qgis/QGIS/issues/32700

**Comment by dgreenewalt** [comment] 2019-11-15 21:15
Thank you!  I can wait for 3.10.1    : )
