### ISSUE TITLE
copy / paste feature does not work correctly for MultilinestringZ

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#33977] opened 2020-01-22 10:45 UTC
QGIS 3.10.1
See attachments.
copy 'la Sarthe' from 'cours_eau_base' layer.
paste to 'cours_eau_ajout'

the copy creates 321 features
(one for each part of the multiline entity)
[test.zip](https://github.com/qgis/QGIS/files/4096656/test.zip)

**Comment by gioman** [comment] 2020-01-22 11:33
Also on 3.10.2

**Comment by gioman** [comment] 2020-01-22 11:36
@FERRATON this seems limited to the case where the involved vectors have the "Z". Just tested with copies without Z and it works as expected.

**Comment by FERRATON** [comment] 2020-01-22 12:51
I confirm.

**Comment by elpaso** [comment] 2020-01-23 12:54
@FERRATON I cannot reproduce on current master/linux, can you try latest master?

**Comment by FERRATON** [comment] 2020-01-23 13:18
it's strange

I've just tried with QGIS 3.11.0-master révision 4a7ea580e9  ( windows 10)
and I'm reproducing the issue.

**Comment by gioman** [comment] 2020-01-23 13:21
me too on Linux (from the repo for Ubuntu, so with slightly old dependencies).

**Comment by elpaso** [comment] 2020-01-23 14:02
maybe a different way to copy-paste? Can you attach a short video?

**Comment by elpaso** [comment] 2020-01-23 14:04
@gioman I don't think dependencies matter in this case, it should all be QGIS core code.

**Comment by FERRATON** [comment] 2020-01-23 14:48
see attachment
![copy_paste_issue](https://user-images.githubusercontent.com/2129643/72994664-d05a0b80-3df7-11ea-8c41-84b87a54b83a.gif)

**Comment by elpaso** [comment] 2020-01-23 16:09
@FERRATON thank you, it's the same I was doing, I'll give it another try.

**Comment by roya0045** [comment] 2020-01-23 16:13
@elpaso are you using master with the attribute table fix? Since it might be related to the attribute table, could this explain why?

**Comment by elpaso** [comment] 2020-01-23 16:38
@roya0045 it's not related: I also tried with selecting on canvas.

**Comment by gioman** [comment] 2020-01-23 18:42
> @FERRATON thank you, it's the same I was doing, I'll give it another try.

@elpaso I'm copy/pasting from the map canvas and the result is the same.

**Comment by elpaso** [comment] 2020-01-24 12:32
Tested again with latest master: cannot reproduce.

**Comment by gioman** [comment] 2020-01-24 12:38
weird, for me is replicable in a consistent way.

**Comment by roya0045** [comment] 2020-01-24 12:41
@gioman with the latest master or slightly outdated master?

**Comment by gioman** [comment] 2020-01-24 17:36
> @gioman with the latest master or slightly outdated master?

@elpaso @roya0045 I have tested now master on Windows (in opposition to my previous tests on Linux) and it works as expected.

**Comment by roya0045** [comment] 2020-01-24 17:43
@FERRATON please test with the latest master to confirm it is fixed.

**Comment by gacarrillor** [comment] 2020-01-26 15:38
Tested with master (revision f82932e39a, build today) on a Linux machine. 
I confirm this issue was fixed.

**Comment by FERRATON** [comment] 2020-01-27 07:42
I confirm that the working is correct in the last QGIS master.
is it possible to port the patch to QGIS 3.10 LTR ?

**Comment by elpaso** [comment] 2020-01-27 08:28
Which patch exactly?

**Comment by FERRATON** [comment] 2020-01-27 08:48
Sorry, I don't know exactly !
Isn't it possible to identify the modification that allowed the problem to disappear in the QGIS master ?

**Comment by roya0045** [comment] 2020-01-27 12:59
@elpaso I know that my fix was not backported and it affects the copy paste function and other things related to the attribute table. I am guessing that if someone builds master right before it was merged we could see if this is the root cause and backport it at the same time.

**Comment by elpaso** [comment] 2020-01-27 13:08
@roya0045 I think you should backport that PR in any case.

**Comment by roya0045** [comment] 2020-01-27 13:11
@elpaso agreed, I'm just not too sure how to backport properly without breaking things, I'll give it a try when I have some time today. Should I backport for both 3.10 and 3.4 or only one?

**Comment by roya0045** [comment] 2020-01-27 15:25
Could someone test #34057 and see if that fixes this?

**Comment by Gustry** [comment] 2020-01-27 15:35
> Should I backport for both 3.10 and 3.4 or only one?

3.4 is EOL and these last few weeks only crash/data corruption were backported to 3.4 anyway.

**Closed** 2020-01-27 17:08 UTC
Labels: Bug, Digitizing, Feedback
