### ISSUE TITLE
Raster Calculator Crashes

### ISSUE THREAD

**Issue by j66FME** [qgis/QGIS#32954] opened 2019-11-19 16:00 UTC
Hello,

I am currently using the QGIS 3.4 training module (chapter 8: Rasters). I recently downloaded 3.10 so I can stay updated with the new features. Recently, I've been trying to use the raster calculator that can calculate the aspect layer I created from srtm_41_19.tiff (8.3.5 raster calculator section). This data is from the QGIS-Training-Data-2.0 folder. The formula is:
 "aspect@1" >= 90 OR "aspect@1" <= 270

I utilized the raster calculator in 4 different ways:
1. Raster -> Raster Calculator: Causes the program to crash without any error message. the file is created but when I try to view it, it says it damaged, too big, corrupted, etc. the tiff size is 1KB
2. Processing -> Raster Analysis -> Raster calculator: same as above.
3.Processing -> GDAL -> Raster miscellaneous -> Raster calculator: QGIS doesn't crash but it is giving me invalid syntax from the log menu:
             
2019-11-19T10:48:27     INFO    gdal_calc --calc "aspect@1 >= 90 OR aspect@1 
2019-11-19T10:48:28     INFO    GDAL execution console output
             0 .. evaluation of calculation aspect@1 >= 90 OR aspect@1              
             Traceback (most recent call last):
             
              File "C:\PROGRA~1\QGIS3~1.10\bin\gdal_calc.py", line 483, in 
             
              main()
             
              File "C:\PROGRA~1\QGIS3~1.10\bin\gdal_calc.py", line 476, in main
             
              doit(opts, args)
             
              File "C:\PROGRA~1\QGIS3~1.10\bin\gdal_calc.py", line 344, in doit
             
              myResult = eval(opts.calc, global_namespace, local_namespace)
             
              File "", line 1
             
              aspect@1 >= 90 OR aspect@1              
              ^
             
             SyntaxError: invalid syntax

It should be noted that the file is no longer 1 KB but 2,165 KB.
             
4. SAGA -> Raster calculus -> Raster calculator: It also doesn't crashes but the log message is this: 

             C:\WINDOWS\system32>call saga_cmd grid_calculus "Grid Calculator" -GRIDS "C:/Users/JS0981/AppData/Local/Temp/processing_30877ba17e49499a9eb6b33c183ab485/9d12a9bc39fa46eabe770db702dca5ae/aspect.sgrd" -XGRIDS "C:/Users/JS0981/AppData/Local/Temp/processing_30877ba17e49499a9eb6b33c183ab485/d59b9f68c91a4ed1a14cf3e2bda36072/aspect.sgrd" -FORMULA ""aspect@1" = 270" -RESAMPLING 0 -USE_NODATA false -TYPE 7 -RESULT "Y:/Utils/_PVC_IT/_FME_TRAINING/QGIS_Training/QGIS-Training-Data-2.0/exercise_data/raster/SRTM/y.sdat"
             Error: executing tool [Grid Calculator]
             ____________________________
             
             ##### ## ##### ##
             ### ### ## ###
             ### # ## ## #### # ##
             ### ##### ## # #####
             ##### # ## ##### # ##
             ____________________________
             
             SAGA Version: 2.3.2 (64 bit)
             
             ____________________________
             library path: C:\PROGRA~1\QGIS3~1.10\apps\saga-ltr\modules\
             library name: grid_calculus
             library : Calculus
             tool : Grid Calculator
             author : A.Ringeler (c) 2003
             processors : 8 [8]
             ____________________________
             
             Load grid: C:/Users/JS0981/AppData/Local/Temp/processing_30877ba17e49499a9eb6b33c183ab485/9d12a9bc39fa46eabe770db702dca5ae/aspect.sgrd...
             failed
             Load grid: C:/Users/JS0981/AppData/Local/Temp/processing_30877ba17e49499a9eb6b33c183ab485/d59b9f68c91a4ed1a14cf3e2bda36072/aspect.sgrd...
             failed
             Grid Calculator: could not initialize data objects
             
             C:\WINDOWS\system32>exit

At this point, the only one that has some what success is the GDAL choice. But it won't display on the canvas. The layer is present in the layers box with values and the file is bigger than 1KB (2,165 KB). Should I uninstall QGIS 3.10 and go back to 3.8? What would be the best solution? 

Thanks

**Comment by roya0045** [comment] 2019-11-19 16:04
related to #32855

**Comment by elpaso** [comment] 2019-11-19 16:05
I think it's in part a duplicate of #32477

**Comment by j66FME** [comment] 2019-11-19 16:22
Got it to work. It wa unchecked  OpenCl box gave me some trouble.


 Thank you very much

**Closed** 2019-11-19 16:26 UTC
