### ISSUE TITLE
.qgz saving as temporary file

### ISSUE THREAD

**Issue by dcwestph** [qgis/QGIS#33671] opened 2020-01-08 19:19 UTC
Is there a way we could remove the temporary tag ('AT' in below screenshot) from .qgz files when saving them?  Or is there a reason they are saved as such?  Reason I ask is that we sync files back and forth between a local server and a cloud server, but the sync ignores temporary files such as these.

![image](https://user-images.githubusercontent.com/22817947/72008318-297f4800-3219-11ea-9fab-9b8717c27474.png)

**Comment by nyalldawson** [comment] 2020-01-08 23:06
Duplicate of #32118 - already fixed

**Closed by nyalldawson** 2020-01-08 23:06 UTC
