### ISSUE TITLE
FTBFS: fatal error: ui_qgswmssourceselectbase.h: No such file or  directory

### ISSUE THREAD

**Issue by thiagomacieira** [qgis/QGIS#32882] opened 2019-11-15 07:26 UTC
**Describe the bug**
When compiling QGIS from source with a high -j number, the build fails with:
```
In file included from /builddir/build/BUILD/QGIS-final-3_10_0/src/providers/wms/qgswmsdataitems.cpp:26:
/builddir/build/BUILD/QGIS-final-3_10_0/src/providers/wms/qgswmssourceselect.h:20:10: fatal error: ui_qgswmssourceselectbase.h: No such file or 
directory
   20 | #include "ui_qgswmssourceselectbase.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Note that later we see:
```
[  5%] Generating ui_qgswmssourceselectbase.h
cd /builddir/build/BUILD/QGIS-final-3_10_0/clr-build/src/ui && /usr/bin/uic -o /builddir/build/BUILD/QGIS-final-3_10_0/clr-build/src/ui/ui_qgswmssourceselectbase.h /builddir/build/BUILD/QGIS-final-3_10_0/src/ui/qgswmssourceselectbase.ui
```

**How to Reproduce**
Run:  make -j172`

**QGIS and OS versions**
QGIS-3.10.0, Qt 5.13.2, GCC 9.2.1, Clear Linux

**Additional context**
The problem is that there is no dependency requirement between the .ui files, the ui_*.h headers produced from them by uic and the .cpp files that require them. Please add the necessary CMake rules to instruct the dependency to exist.

**Comment by lbartoletti** [comment] 2019-11-15 07:38
Already fixed in #32824 
Duplicate of https://github.com/qgis/QGIS/issues/32764

**Closed by lbartoletti** 2019-11-15 07:38 UTC
Labels: Bug
