### ISSUE TITLE
CTRL-click no longer works to finish digitizing a polygon

### ISSUE THREAD

**Issue by wylie2121** [qgis/QGIS#31279] opened 2019-08-16 22:04 UTC
I recently upgraded to QGIS 3.4.10. 

Ctrl-click (the MAC equivalent to right-click) no longer works as a way to end digitizing a polygon.

Ctrl-click works in other applications I use; it also works to bring up drop-down menus in QGIS when I click on one of the panels.

Is this a bug that needs fixing in the MAC version of QGIS?

**Comment by gioman** [comment] 2019-08-17 09:45
> I recently upgraded to QGIS 3.4.10.

from?

**Comment by wylie2121** [comment] 2019-08-18 16:51
From QGIS 2.18

**Comment by gioman** [comment] 2019-08-18 17:11
> From QGIS 2.18

digitizing has changed quite a lot since 2.18, are you sure are you taking it into account?

**Comment by wylie2121** [comment] 2019-08-18 18:07
I've read the most recent QGIS manual and the way to tell QGIS you have finished digitizing a polygon is by hitting the right-click button, which is what it has always been (no change between versions). On MACs this is ctrl-click. ctrl-click works as it is supposed in other areas of QGIS but no longer when drawing a polygon.

**Comment by DelazJ** [comment] 2019-08-19 09:36
> On MACs this is ctrl-click. ctrl-click works as it is supposed in other areas of QGIS but no longer when drawing a polygon.

I did not know about the ctrl-click tip but on a macos sierra, using both ctrl-click and the usual right-click on the mouse terminate the feature's creation on 3.6

**Comment by MikkoVihtakari** [comment] 2019-10-12 18:15
Also configuring "Secondary click" in Trackpad System Preferences to "Click in bottom right/left corner" [seems to work](https://gis.stackexchange.com/questions/337648/how-to-draw-a-polygon-in-qgis-3-8-on-mac/338387#338387).

**Comment by thayeray** [comment] 2020-02-13 22:16
Control click works in 3.8.0 but not in any of the 3.10.0 .1 or .2. "Secondary click" using the trackpad does work in 3.10.2.

**Comment by gioman** [comment] 2020-02-15 17:48
> Control click works in 3.8.0 but not in any of the 3.10.0 .1 or .2. "Secondary click" using the trackpad does work in 3.10.2.

@thayeray 
I tested on 3.4.15 on macOS Catalina and ctrl-click does not work to end editing a geometry. is weird to have ever worked on 3.8.

**Comment by thayeray** [comment] 2020-02-15 22:04
Could the bug be something that was back-ported to 3.4? The roadmap says 3.4.15 is January of this year, but 3.8.0 was June of 2019. I checked again, the version in which control click works for finishing polygons is the first Zanzibar (3.8.0).My OS version is High Sierra.

    On Saturday, February 15, 2020, 12:48:51 PM EST, Giovanni Manghi <notifications@github.com> wrote:  
 
 

Control click works in 3.8.0 but not in any of the 3.10.0 .1 or .2. "Secondary click" using the trackpad does work in 3.10.2.


@thayeray
I tested on 3.4.15 on macOS Catalina and ctrl-click does not work to end editing a geometry. is weird to have ever worked on 3.8.

**Comment by gioman** [comment] 2020-02-15 22:46
> Could the bug be something that was back-ported to 3.4? The roadmap says 3.4.15 is January of this year, but 3.8.0 was June of 2019. I checked again, the version in which control click works for finishing polygons is the first Zanzibar (3.8.0).My OS version is High Sierra.

@thayeray you should ask in the developers mailing list too, I'm not sure if this is a bug or something that changed in purpose.

**Comment by ghobona** [comment] 2020-04-11 09:29
QGIS 3.10.1-A Coruña, on a macOS Catalina, also does not allow finishing of polygons by Ctrl + Click on a trackpad.

**Comment by gioman** [comment] 2020-04-11 14:25
> QGIS 3.10.1-A Coruña, on a macOS Catalina, also does not allow finishing of polygons by Ctrl + Click on a trackpad.

 @ghobona see https://github.com/qgis/QGIS/issues/31279#issuecomment-586624638

it is somewhere documented that ctrl + click should work (on macOS)?

**Comment by ghobona** [comment] 2020-04-11 14:48
Please see the documentation [here](https://support.apple.com/en-gb/HT207700).

Note that polygons can be finished by **tapping with two fingers** on a trackpad on QGIS 3.10.1-A Coruña in a macOS Catalina environment.

**Comment by gioman** [comment] 2020-04-11 14:51
> @gioman Please see the documentation [here](https://support.apple.com/en-gb/HT207700).

@ghobona QGIS docs, not Apple's...

**Comment by ghobona** [comment] 2020-04-11 14:58
This [page](https://docs.qgis.org/3.10/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#adding-features) mentions "right-click".

The page is correct but could benefit from a note that, on some platforms, users have to tap a trackpad with two fingers to perform a right-click.

**Comment by gioman** [comment] 2020-04-11 15:00
> The page is correct but could benefit from a note that, on some platforms, users have to tap a trackpad with two fingers to perform a right-click.

@ghobona feel free to add that to the QGIS docs. In the meantime the expected way to finish edits IS right click, so this should be closed.

**Comment by ghobona** [comment] 2020-04-11 15:07
Agreed, the issue can be closed.

**Comment by johannessen** [comment] 2020-04-11 15:14
Uh, no. I shouldn't need to buy a two-button mouse just in order to use QGIS.

**Comment by gioman** [comment] 2020-04-11 15:16
> Uh, no. I shouldn't need to buy a two-button mouse just in order to use QGIS.

@johannessen why you need that for a right click? I have a mac and don't need a two button mouse to use QGIS.

**Comment by johannessen** [comment] 2020-04-11 15:23
A “right click” (mouse click with secondary functionality) on Mac is done by holding down the CTRL key while clicking the single (or left) mouse button.

Depending on the input devices you have available, other methods may be supported as well. But the ctrl-click is the primary method on macOS. It’s been that since before OS X was introduced.

It follows that software supporting macOS should also support ctrl-click for the secondary click functionality.

**Comment by gioman** [comment] 2020-04-11 15:28
> It follows that software supporting macOS should also support ctrl-click for the secondary click functionality.

if this is the case then this should be a feature request (given that the "workaround" it is just use a "normal" mouse).

**Comment by johannessen** [comment] 2020-04-11 15:34
A “normal” Mac mouse only has a single button. [Apple’s docs](https://support.apple.com/en-gb/HT207700) clearly state:

> On Mac computers, right click is known as secondary click or Control click.

Since QGIS now purports to officially support macOS, this issue IMHO clearly is a bug, not a feature request. (But of course, do feel free to change the issue label if it helps resolving this.)

**Comment by gioman** [comment] 2020-04-11 15:42
> A “normal” Mac mouse

sorry, to me a "normal" mouse is not Apple's one. Maybe I should have called it "common". Regardless I still think that this is not a bug but a feature request, but I don't really care about macOS (other than testing) so I'll leave to others decide.

**Comment by thayeray** [comment] 2020-04-11 15:57
With respect to right click in MacOS, this is not a problem limited to trackpads on laptops. Some Apple Mouse models only have one button, and that performs a left-click. So someone using such a mouse in QGIS on a computer without a trackpad would be limited to control click for completing a polygon. There is usually an alternative way to do most of the things that right click performs in QGIS, for example by navigating through left clickable menus. For completing a polygon the only way is to right click. It is inconsistent that control clicking should work throughout the rest of QGIS as a right click but not for polygon completion.
I believe that this inconsistency is indeed a bug and this issue should not be closed. My experience with using the trackpad methods is that they are less dependable than control click. I never had a problem with precision when making polygons back when control click was still working in QGIS. I have no problem in the ID Editor for Open Street Map, and frequently digitize nice polygons using my track pad and control click. It is unfortunate that exactly when I need precision in QGIS it is not available for finishing a polygon.
Thank you for considering my input on this issue.
-Thayer Young

    On Saturday, April 11, 2020, 10:51:17 AM EDT, Giovanni Manghi <notifications@github.com> wrote:  
 
 



@gioman Please see the documentation here.


@ghobona QGIS docs, not Apple's...

**Comment by thayeray** [comment] 2020-04-11 19:41
Control click is supported throughout QGIS3 as right click except in editing. It was supported at least as recently as in QGIS 2.14 for completing polygons and lines, but now it is not. So yes it is a bug. It does not make sense that it would be a feature request because it was dropped from the software probably as an oversight when editing was redesigned.
-Thayer



    On Saturday, April 11, 2020, 11:42:19 AM EDT, Giovanni Manghi <notifications@github.com> wrote:  
 
 



A “normal” Mac mouse


sorry, to me a "normal" mouse is not Apple's one. Maybe I should have called it "common". Regardless I still think that this is not a bug but a feature request, but I don't really care about macOS (other than testing) so I'll leave to others decide.

**Comment by gioman** [comment] 2020-04-14 08:48
>  It was supported at least as recently as in QGIS 2.14 for completing polygons and lines, but now it is not.

so it is confirmed that is a bug and is a regression, thanks for checking.

**Comment by fgfletcher** [comment] 2020-05-18 14:42
Control-click was supported for completing lines and polygons in 3.8.3 and before.
Control-click is still supported throughout QGIS, except for the above limited case.
Control-click has been the standard and recognized equivalent of "right-click" for decades.
The "standard mouse" in the Mac world has been the single button mouse for the 30+ years I have been using Macs (and developing software for them).  Yes, there are more elaborate mice from Apple and others, but not all users have them.  Recent laptops make other provisions for "right-click", but not all do.
Since this partial regression (from 3.8) causes problems it should be considered a "bug" rather than just a "feature request".

**Comment by 12rambau** [comment] 2020-07-20 13:55
any news since may ?

**Comment by ghobona** [comment] 2020-07-20 20:28
The solution to this issue is "users have to tap a trackpad with two fingers to perform a right-click". See the Comment https://github.com/qgis/QGIS/issues/31279#issuecomment-612440027.

This issue can be closed.

**Comment by fgfletcher** [comment] 2020-07-20 20:38
Not all Mac systems have a trackpad.
The Mac standard is control-click for right-click. 
QGIS in earlier releases did support control-click, and current version still supports it for other functions.
This problem is a regression and thus is a bug which could easily be fixed.
Refusing to fix it is a doctrinaire approach by non-Mac users and is inappropriate.
This issue should not be closed.

**Comment by wylie2121** [comment] 2020-07-20 23:55
I agree. It hasn’t been fixed. Has it been fixed on later releases? If not, it should be fixed going forward.

**Comment by gioman** [comment] 2020-07-21 09:34
> Not all Mac systems have a trackpad.

correct



> This problem is a regression

And has been tagged as a regression



>  Refusing to fix it is a doctrinaire approach by non-Mac users and is inappropriate.

no one is refusing to fix it, it that was the case this would have been closed.



>  This issue should not be closed.

it is open



> and thus is a bug which could easily be fixed.

may be is easy, maybe not, but in general there is no guarantee that a bug will be fixed sooner than later. QGIS development (and bug fixing) is "user driven", it means that are us, the user, that dictate the pace of development/bug fixing. If a bug is really bad and undermines a basic functionality this is usually fixed by the project quickly. But many other bugs are annoying for a smaller subset of the users (like this one apparently) and in this cases it is the us, the users, can step in: propose a patch, hire a developer, do a crowdfunding, etc.

**Comment by batchku** [comment] 2020-08-27 21:06
I'm using QGIS 3.14.15 with MacOS 10.15.5

None of the above solutions are working for me and so I'm not able to close polygons.
I have tried:
- using a USB mouse and right clicking
- using 2-finger secondary click (configured in trackpad preferences)
- using control-click


How are other mac users managing to create a polygon?

**Comment by gioman** [comment] 2020-08-29 16:01
> using a USB mouse and right clicking

this works fine here on a mac Mini.

**Comment by thayeray** [comment] 2020-09-03 19:37
But what proportion of Mac users have/use a USB mouse? This is a reversion that does not comply with Mac standard. 
    On Saturday, August 29, 2020, 12:01:49 PM EDT, Giovanni Manghi <notifications@github.com> wrote:  
 
 



using a USB mouse and right clicking


this works fine here on a mac Mini.

**Comment by thayeray** [comment] 2020-09-03 19:44
I am assuming you are using a trackpad. There is an option on newer systems to control click by clicking the right side of the trackpad. 
    On Thursday, August 27, 2020, 05:06:48 PM EDT, batchku <notifications@github.com> wrote:  
 
 


I'm using QGIS 3.14.15 with MacOS 10.15.5

None of the above solutions are working for me and so I'm not able to close polygons.
I have tried:
   
   - using a USB mouse and right clicking
   - using 2-finger secondary click (configured in trackpad preferences)
   - using control-click

How are other mac users managing to create a polygon?

**Comment by wylie2121** [comment] 2020-09-03 20:31
Question: is this fixed in later versions of QGIS (the version we are talking about here is: 3.4.10-Madeira)? 

Applications should meet the user’s needs, not the other way around.

**Comment by gioman** [comment] 2020-09-03 20:37
> Applications should meet the user’s needs, not the other way around.

@wylie2121 QGIS development (and bug fixing) is user driven. If you (macOS users) really want a macOS version bug fixed you should start thinking about doing something, like supporting the work to fix it, or sending over a patch if you are able to.

**Comment by pvgenuchten** [comment] 2020-09-11 13:24
i have the same problem using trackpad, but using right-click on a 3-button windows mouse worked for me

**Comment by 3nids** [comment] 2021-01-25 13:18
I fail a bit to see how it was different on QGIS 2.14 as the code looks really the same:
2.14: https://github.com/qgis/QGIS/blob/release-2_14/src/app/qgsmaptooladdfeature.cpp#L195-L212
3.16 https://github.com/qgis/QGIS/blob/release-3_16/src/gui/qgsmaptooldigitizefeature.cpp#L246-L263

**Comment by thayeray** [comment] 2021-01-25 14:08
Maybe Qt has changed?
-T

    On Monday, January 25, 2021, 08:19:08 AM EST, Denis Rouzaud <notifications@github.com> wrote:  
 
 


I fail a bit to see how it was different on QGIS 2.14 as the code looks really the same:
2.14: https://github.com/qgis/QGIS/blob/release-2_14/src/app/qgsmaptooladdfeature.cpp#L195-L212
3.16 https://github.com/qgis/QGIS/blob/release-3_16/src/gui/qgsmaptooldigitizefeature.cpp#L246-L263

**Comment by fgfletcher** [comment] 2021-01-25 15:50
I suspect the problem lies in "Qt::RightButton " which appears to
report a "right click".

Previously that accepted a Control-click (i.e., holding down the Control
key while clicking a single button mouse) as the equivalent of a
Right-click on a two button mouse.

I suspect that it no longer does so...

Cordially,
-- 
Garth Fletcher

**Comment by johannessen** [comment] 2021-01-25 16:03
As we discussed, ctrl-click is standard for “right click” on Mac, so it would indeed be best for Qt to handle this automatically. The [Qt for macOS](https://doc.qt.io/qt-5/macos-issues.html#right-mouse-clicks) docs suggest this only happens for `QContextMenuEvent`, which kinda makes sense I suppose?

But I’ve just tried this in both QGIS 3.8.3 (older kyngchaos.com build) and QGIS 3.16.3 (latest qgis.org build). QGIS 3.8 doesn’t have this issue (that’s not news). But now I also can’t reproduce it in the official QGIS 3.16!

Could anyone verify this, please?

**Comment by fgfletcher** [comment] 2021-01-25 16:18
Mac OS X 10.13.6, QGIS 3.16.3
Control-click now WORKS as equivalent of right-click in closing
polygons.  Also works for other right-click functions such as
selecting layer options, etc.

Many many thanks to whoever fixed this Mac-specific irritating problem!

Cordially,
-- 
Garth Fletcher

**Closed** 2021-01-25 16:19 UTC
Labels: Bug, Digitizing, MacOS, Regression

**Comment by thayeray** [comment] 2021-01-25 18:24
Thanks are probably due to @PeterPetrik, who is doing the recompile for MacOS.
-Thayer

    On Monday, January 25, 2021, 11:18:23 AM EST, fgfletcher <notifications@github.com> wrote:  
 
 

Mac OS X 10.13.6, QGIS 3.16.3
Control-click now WORKS as equivalent of right-click in closing
polygons. Also works for other right-click functions such as
selecting layer options, etc.

Many many thanks to whoever fixed this Mac-specific irritating problem!

Cordially,
-- 
Garth Fletcher

**Comment by PeterPetrik** [comment] 2021-02-02 07:49
believe me, I did nothing...

**Comment by thayeray** [comment] 2021-02-04 22:00
You did nothing besides packaging with the newer Qt, which had the bug fixed in its code. So you inadvertently solved a problem that was not in the QGIS code.

**Comment by jknockaert** [comment] 2021-02-09 13:03
Any chance this fix (i.e. packaging the newer Qt) will be ported back to QGIS 3.10 LTS?

**Comment by PeterPetrik** [comment] 2021-02-09 13:54
Hi @jknockaert, it is technically very difficult and not possible to include in the official QGIS plan due to the EOL of QGIS 3.10 LTS. You may try to use alternative QGIS installation methods (conda, Kingchairos packages, etc) to see if there is any that is without this problem

**Comment by DelazJ** [comment] 2021-02-09 16:37
Or upgrade to 3.16 that is labeled LTR at the end of the month...

**Comment by spara** [comment] 2021-11-19 00:16
This is still broken on QGIS-LTR and 3.22 on macOS 11.6.
