### ISSUE TITLE
gdal:proximity doesn't output raster file in output location in PyQGIS standalone application

### ISSUE THREAD

**Issue by seanaxn1135** [qgis/QGIS#36344] opened 2020-05-11 09:53 UTC
**Describe the bug**
gdal:proximity does not save output file in output directory

**How to Reproduce**

Example code using python 3.7:

 ```
   def publicgreen_qgis(self):

        params = {'INPUT':'test/file/rasterized.tif','BAND':1,
        'VALUES':'','UNITS':0,'MAX_DISTANCE':0,'REPLACE':0,
        'NODATA':0,'OPTIONS':'','EXTRA':'','DATA_TYPE':5,'OUTPUT':"test/file/proximity.tif"}

        res2 = processing.run("gdal:proximity", params)
```

UPDATED EDIT:
Added more information
```
import sys
# Import only what you're going to use
from qgis.core import QgsApplication, QgsRasterLayer

# You can add this path to your system's environment so you don't have to type it here
sys.path.append('C:/OSGeo4W64/apps/qgis/python/plugins')
import processing

# This is a 'fake' iface since we are not using a interface here
class DummyIface(object):

    def __init__(self):
        self.destCrs = None


# Pass QgsApplication to an object and you can use it just like a QApplication
app = QgsApplication([], True)
app.initQgis()
print("QGIS successfully Initialised")

# I took the freedom to change the way you used processing here, just to be sure it will work
processing.classFactory(DummyIface())

res = processing.run("gdal:rasterize", {
    'INPUT': 'C:\\Users\\seteg\\Desktop\\LVI System\\Vector Files\\National Park SG\\National Park SG.shp',
    'FIELD': '1', 'BURN': 1, 'UNITS': 1, 'WIDTH': 10, 'HEIGHT': 10,
    'EXTENT': '2667.53800002985,56396.4399999964,15748.72099999,50256.3342999838 [EPSG:3414]', 'NODATA': 0,
    'OPTIONS': '', 'DATA_TYPE': 5, 'INIT': None, 'INVERT': False, 'EXTRA': '', 'OUTPUT': 'C:/Users/seteg/Desktop/rasterize.tif'})

processing.run("gdal:proximity",
               {'INPUT': res['OUTPUT'], 'BAND': 1, 'VALUES': '', 'UNITS': 0, 'MAX_DISTANCE': 0, 'REPLACE': 0,
                'NODATA': 0, 'OPTIONS': '', 'EXTRA': '', 'DATA_TYPE': 5,
                'OUTPUT': 'C:/Users/seteg/Desktop/proximity.tif'})

app.exit()
```
code structure taken from: https://gis.stackexchange.com/questions/231702/using-pyqgis-in-standalone-scripts-without-crashing

Code runs without errors but does not produce the output file in the directory.

**QGIS and OS versions**

QGIS version
3.12.2-București
QGIS code revision
8a1fb33634
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

**Additional context**
Other GDAL functions such as rasterize and slope works

Have tried using the processing toolbox to run the process and it works as intended.

Input parameters above were copied from Processing > History from QGIS Desktop and worked as intended in QGIS Desktop.

EDIT:
More additional information:
-Additional code can be found above
-I'm using PyQt5 for GUI if that matters, the process should run after a button is pressed. (the button works for other processes)
-IDE used is Pycharm community edition 2018.3.5
-Have uploaded vector files I was working with
[National Park SG.zip](https://github.com/qgis/QGIS/files/4679340/National.Park.SG.zip)

**Comment by alexbruy** [comment] 2020-05-25 07:35
Looks like there is a path issue. Your output path is relative not absolute.

**Comment by seanaxn1135** [comment] 2020-05-25 08:32
> Looks like there is a path issue. Your output path is relative not absolute.

I've tried it with an absolute path, does not work as well.

**Comment by alexbruy** [comment] 2020-05-25 09:20
I can not reproduce using provided infomation.

**Comment by seanaxn1135** [comment] 2020-05-25 14:18
> I can not reproduce using provided information.

Could you get an output on a rasterised layer using gdal:rasterize?

**Comment by alexbruy** [comment] 2020-05-25 14:24
For me it works just fine with any laer I have tried.

**Comment by seanaxn1135** [comment] 2020-05-26 00:51
> For me it works just fine with any laer I have tried.

I have uploaded the vector files I was using and have edited some extra information.

**Comment by alexbruy** [comment] 2020-05-26 12:11
Unfortunately your code is not very useful for testing as it is incomplete and can't be used "as is". After modifying it (setting path to files, moving code out of function etc) I still can not reproduce issue even with attached data.

Tested by running Processing algorithms one by one, by creating model, by executing standalone script.

**Comment by gioman** [comment] 2020-05-26 12:59
I'm inclined to close this ticket, as one of the core developers is struggling to replicate the issue.

**Comment by seanaxn1135** [comment] 2020-05-26 15:48
> Unfortunately your code is not very useful for testing as it is incomplete and can't be used "as is". After modifying it (setting path to files, moving code out of function etc) I still can not reproduce issue even with attached data.
> 
> Tested by running Processing algorithms one by one, by creating model, by executing standalone script.

'''
import sys
# Import only what you're going to use
from qgis.core import QgsApplication, QgsRasterLayer

# You can add this path to your system's environment so you don't have to type it here
sys.path.append('C:/OSGeo4W64/apps/qgis/python/plugins')
import processing

# This is a 'fake' iface since we are not using a interface here
class DummyIface(object):

    def __init__(self):
        self.destCrs = None


# Pass QgsApplication to an object and you can use it just like a QApplication
app = QgsApplication([], True)
app.initQgis()
print("QGIS successfully Initialised")

# I took the freedom to change the way you used processing here, just to be sure it will work
processing.classFactory(DummyIface())

res = processing.run("gdal:rasterize", {
    'INPUT': 'C:\\Users\\seteg\\Desktop\\LVI System\\Vector Files\\National Park SG\\National Park SG.shp',
    'FIELD': '1', 'BURN': 1, 'UNITS': 1, 'WIDTH': 10, 'HEIGHT': 10,
    'EXTENT': '2667.53800002985,56396.4399999964,15748.72099999,50256.3342999838 [EPSG:3414]', 'NODATA': 0,
    'OPTIONS': '', 'DATA_TYPE': 5, 'INIT': None, 'INVERT': False, 'EXTRA': '', 'OUTPUT': 'C:/Users/seteg/Desktop/rasterize.tif'})

processing.run("gdal:proximity",
               {'INPUT': res['OUTPUT'], 'BAND': 1, 'VALUES': '', 'UNITS': 0, 'MAX_DISTANCE': 0, 'REPLACE': 0,
                'NODATA': 0, 'OPTIONS': '', 'EXTRA': '', 'DATA_TYPE': 5,
                'OUTPUT': 'C:/Users/seteg/Desktop/proximity.tif'})

app.exit()
'''
I ran this in my IDE and the rasterize layer would show up but proximity layer wouldn't

**Comment by seanaxn1135** [comment] 2020-05-26 15:51
> Unfortunately your code is not very useful for testing as it is incomplete and can't be used "as is". After modifying it (setting path to files, moving code out of function etc) I still can not reproduce issue even with attached data.
> 
> Tested by running Processing algorithms one by one, by creating model, by executing standalone script.

`import sys
# Import only what you're going to use
from qgis.core import QgsApplication, QgsRasterLayer

# You can add this path to your system's environment so you don't have to type it here
sys.path.append('C:/OSGeo4W64/apps/qgis/python/plugins')
import processing

# This is a 'fake' iface since we are not using a interface here
class DummyIface(object):

    def __init__(self):
        self.destCrs = None


# Pass QgsApplication to an object and you can use it just like a QApplication
app = QgsApplication([], True)
app.initQgis()
print("QGIS successfully Initialised")

# I took the freedom to change the way you used processing here, just to be sure it will work
processing.classFactory(DummyIface())

res = processing.run("gdal:rasterize", {
    'INPUT': 'C:\\Users\\seteg\\Desktop\\LVI System\\Vector Files\\National Park SG\\National Park SG.shp',
    'FIELD': '1', 'BURN': 1, 'UNITS': 1, 'WIDTH': 10, 'HEIGHT': 10,
    'EXTENT': '2667.53800002985,56396.4399999964,15748.72099999,50256.3342999838 [EPSG:3414]', 'NODATA': 0,
    'OPTIONS': '', 'DATA_TYPE': 5, 'INIT': None, 'INVERT': False, 'EXTRA': '', 'OUTPUT': 'C:/Users/seteg/Desktop/rasterize.tif'})

processing.run("gdal:proximity",
               {'INPUT': res['OUTPUT'], 'BAND': 1, 'VALUES': '', 'UNITS': 0, 'MAX_DISTANCE': 0, 'REPLACE': 0,
                'NODATA': 0, 'OPTIONS': '', 'EXTRA': '', 'DATA_TYPE': 5,
                'OUTPUT': 'C:/Users/seteg/Desktop/proximity.tif'})

app.exit()`

I've tried running this in my IDE and the rasterize layer would show up in the desktop but proximity wouldn't.

Sorry for the vague code above, I hope this code could be used "as if" with some minor changes to the file path.

I will close this ticket if the problem still cannot be replicated.

**Comment by seanaxn1135** [comment] 2020-05-26 15:56
> Unfortunately your code is not very useful for testing as it is incomplete and can't be used "as is". After modifying it (setting path to files, moving code out of function etc) I still can not reproduce issue even with attached data.
> 
> Tested by running Processing algorithms one by one, by creating model, by executing standalone script.

Hi, sorry for the vague code. I've updated it and hopefully, it can be used "as if" with some minor changes to input and output parameters.

The problem persists where rasterized would create an output on my desktop but proximity wouldn't.

Hopefully, the issue is replicable, I'll close the ticket if the issue is not.

**Comment by alexbruy** [comment] 2020-05-26 16:32
Still can not reproduce. Here is output from my test on Windows using standalone script (stripped unrelated information). Both outputs: from rasterize and proximity tools are there.
```
[434ms] 2020-05-26T16:28:43 Processing[0] gdal_rasterize -l "National Park SG" -a 1 -tr 10.0 10.0 -a_nodata 0.0 -te 2667.53800002985 15748.72099999 56396.4399999964 50256.3342999838 -ot Float32 -of GTiff "C:/data/National Park SG.shp" C:/data/rasterize.tif
[13ms] 2020-05-26T16:28:43 Processing[0] GDAL command:
[4ms] 2020-05-26T16:28:43 Processing[0] gdal_rasterize -l "National Park SG" -a 1 -tr 10.0 10.0 -a_nodata 0.0 -te 2667.53800002985 15748.72099999 56396.4399999964 50256.3342999838 -ot Float32 -of GTiff "C:/data/National Park SG.shp" C:/data/rasterize.tif
[13ms] 2020-05-26T16:28:43 Processing[0] GDAL command output:
[354ms] 2020-05-26T16:28:44 Processing[0] 0...10...20...30...40...50...60...70...80...90...100 - done.

[19ms] 2020-05-26T16:28:44 Processing[0] GDAL execution console output
0...10...20...30...40...50...60...70...80...90...100 - done.

[12ms] 2020-05-26T16:28:44 Processing[0] Results: {'OUTPUT': 'C:/data/rasterize.tif'}
{'OUTPUT': 'C:/data/rasterize.tif'}
[69ms] 2020-05-26T16:28:44 Processing[0] python3 -m gdal_proximity -srcband 1 -distunits GEO -nodata 0.0 -ot Float32 -of GTiff C:/data/rasterize.tif C:/data/proximity.tif
[9ms] 2020-05-26T16:28:44 Processing[0] GDAL command:
[4ms] 2020-05-26T16:28:44 Processing[0] python3 -m gdal_proximity -srcband 1 -distunits GEO -nodata 0.0 -ot Float32 -of GTiff C:/data/rasterize.tif C:/data/proximity.tif
[9ms] 2020-05-26T16:28:44 Processing[0] GDAL command output:
[2002ms] 2020-05-26T16:28:46 Processing[0] 0...10...20...30...40...50...60...70...80...90...100 - done.

[34ms] 2020-05-26T16:28:46 Processing[0] GDAL execution console output
0...10...20...30...40...50...60...70...80...90...100 - done.

[15ms] 2020-05-26T16:28:46 Processing[0] Results: {'OUTPUT': 'C:/data/proximity.tif'}```

**Comment by seanaxn1135** [comment] 2020-05-26 16:36
> Still can not reproduce. Here is output from my test on Windows using standalone script (stripped unrelated information). Both outputs: from rasterize and proximity tools are there.
> 
> ```
> [434ms] 2020-05-26T16:28:43 Processing[0] gdal_rasterize -l "National Park SG" -a 1 -tr 10.0 10.0 -a_nodata 0.0 -te 2667.53800002985 15748.72099999 56396.4399999964 50256.3342999838 -ot Float32 -of GTiff "C:/data/National Park SG.shp" C:/data/rasterize.tif
> [13ms] 2020-05-26T16:28:43 Processing[0] GDAL command:
> [4ms] 2020-05-26T16:28:43 Processing[0] gdal_rasterize -l "National Park SG" -a 1 -tr 10.0 10.0 -a_nodata 0.0 -te 2667.53800002985 15748.72099999 56396.4399999964 50256.3342999838 -ot Float32 -of GTiff "C:/data/National Park SG.shp" C:/data/rasterize.tif
> [13ms] 2020-05-26T16:28:43 Processing[0] GDAL command output:
> [354ms] 2020-05-26T16:28:44 Processing[0] 0...10...20...30...40...50...60...70...80...90...100 - done.
> 
> [19ms] 2020-05-26T16:28:44 Processing[0] GDAL execution console output
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> 
> [12ms] 2020-05-26T16:28:44 Processing[0] Results: {'OUTPUT': 'C:/data/rasterize.tif'}
> {'OUTPUT': 'C:/data/rasterize.tif'}
> [69ms] 2020-05-26T16:28:44 Processing[0] python3 -m gdal_proximity -srcband 1 -distunits GEO -nodata 0.0 -ot Float32 -of GTiff C:/data/rasterize.tif C:/data/proximity.tif
> [9ms] 2020-05-26T16:28:44 Processing[0] GDAL command:
> [4ms] 2020-05-26T16:28:44 Processing[0] python3 -m gdal_proximity -srcband 1 -distunits GEO -nodata 0.0 -ot Float32 -of GTiff C:/data/rasterize.tif C:/data/proximity.tif
> [9ms] 2020-05-26T16:28:44 Processing[0] GDAL command output:
> [2002ms] 2020-05-26T16:28:46 Processing[0] 0...10...20...30...40...50...60...70...80...90...100 - done.
> 
> [34ms] 2020-05-26T16:28:46 Processing[0] GDAL execution console output
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> 
> [15ms] 2020-05-26T16:28:46 Processing[0] Results: {'OUTPUT': 'C:/data/proximity.tif'}```
> ```

May i know how u got above information? I'll check mine.

**Comment by alexbruy** [comment] 2020-05-26 17:11
> May i know how u got above information?

It is printed to stdout when running script from OSGeo4W shell. Your IDE also should be able to catch it and show somewhere.

> Does the proximity tif file appear in your directory?

Yes, see my previous comment.
>> Both outputs: from rasterize and proximity tools are there.

**Comment by seanaxn1135** [comment] 2020-05-26 17:18
I recorded a gif to showcase what I'm seeing.
![2020-05-27_1-16-55](https://user-images.githubusercontent.com/37982680/82930405-e8b18100-9fb7-11ea-8188-9d83f220c4c1.gif)

**Comment by alexbruy** [comment] 2020-05-26 17:25
Text is not readable, but seems there is an error in the log printed in red. Have you tried to read it and fix?

**Comment by seanaxn1135** [comment] 2020-05-26 17:26
> Text is not readable, but seems there is an error in the log printed in red. Have you tried to read it and fix?

it is a deprecation warning

C:\OSGEO4~1\apps\qgis\python\qgis\utils.py:744: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  mod = _builtin_import(name, globals, locals, fromlist, level)

**Comment by alexbruy** [comment] 2020-08-03 12:32
Not reproducible.

**Closed by alexbruy** 2020-08-03 12:32 UTC
Labels: Bug, Feedback, Processing
