### ISSUE TITLE
No transform is available after Update to QGIS 3.10.0-3 and GRASS 7.8.1-1

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#32795] opened 2019-11-11 18:24 UTC
After Update to 3.10.0-3 and Grass Gis 7.8.1-1 I get the following message, when opening an existing project with multiple layers of different CRS:
No transform is available between EPSG:3044 [ETRS89 / UTM zone 32N (N-E)] and EPSG:3857 [WGS 84 / Pseudo-Mercator].
proj_create_operations: At least one of the operation lacks a source and/or target CRS.
Before the Update it worked perfectly. To ensure a clean system I uninstalled qgis via OSGeo4W setup, deleted OSGeo4W64 Path to get rid of old profiles, downloaded fresh installer and installed via Quickinstall.

This is under Windows 10, latest Updates installed.

**Comment by roya0045** [comment] 2019-11-11 18:44
what proj version are you using?

**Comment by wmeinolf** [comment] 2019-11-11 19:04
I'm not sure, If I understand correctly. I open a QGZ project file. Do the following QGIS "About" infos help?

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | AnotherDXF2Shape; batchvectorlayersaver; ClusterPoints; joinmultiplelines; mmqgis; ORStools; Qgis2threejs; qgis2web; QuickOSM; quick_map_services; db_manager; MetaSearch; processing

**Comment by roya0045** [comment] 2019-11-11 19:31
Ok you have proj 6.

**Comment by nCVJTK** [comment] 2019-11-13 13:46
I have very similar if not the same issue related to projections/transformations so I will just post my comments here without opening new bug report. 

My system info:

![system](https://user-images.githubusercontent.com/57320462/68765595-7087fd00-061d-11ea-864c-f4e29a1d1848.png)

The problem I encountered is related to layer reprojecting , in my case from EPSG:3908 to EPSG:3907. Both CRSs are deprecated in newer versions of EPSG database (there are now refreshed definitions of both CRSs as EPSG:8678 and EPSG:8677) but that is irrelevant for the problem because I have recreated the issue in my environment even with new definitions:

![proj_problem](https://user-images.githubusercontent.com/57320462/68766537-56e7b500-061f-11ea-956b-c95300fd1b38.png)


![proj_problem2](https://user-images.githubusercontent.com/57320462/68766546-59e2a580-061f-11ea-8d49-1c4fe5443818.png)

I have also encountered the warning message that there are no transformation parameters between the same CRS. I am aware of the fact the latest QGIS version has been compiled against GDAL 3.0.2 and PROJ 6 (new  API and other improvements) but some warning messages do not make sense:

- there should be no warning message about transformation parameters if one tries to reproject layers from projected CRS A to projected CRS B if both CRSs share the same geodetic datum and ellipsoid definition (in my example those are EPSG:3908 -->EPSG:3907) becasue in theory it is not transformation but rather a conversion from projection A to projection B

- there should be no warning message about transformation parameters if one defines projected CRS A as the CRS of the entire QGIS session and forces the very same definition as layer CRS on loaded layer

The issue does not manifest itself just as warning transformation messages but the reprojection also fails resulting in invalid layer. None of these issues have been encountered in previous QGIS builds compiled against GDAL 2.4 and PROJ 5.

**Comment by cybernar** [comment] 2019-11-13 15:17
I have the same problem. I have just updated QGIS to 3.10.0-3, with GDAL 3.0.2 and PROJ 6.2.1.

The error happens in a existing project set with "World-Gall Peters" CRS (ESRI:54016) - this CRS is based on WGS84 datum. This project contains a layer with "ETRS89 LAEA" (EPSG:3035) CRS. 

I have found something interesting to reproduce the bug:
- when I open an existing QGIS 3.8 project, transformation from EPSG:3035 to ESRI:54016 (or to EPSG:4326) is not available.
- but when I create a new QGIS project, add my EPSG:3035 layer, and then set the project to "World-Gall Peters" CRS, a choice for transformation is available from ETRS89 to WGS84 datum.

Moreover, with this version of GDAL and PROJ, cs2cs is able to convert a shapefile from EPSG:3035 to ESRI:54016. I don't think the problem is from PROJ.

![transform_bug](https://user-images.githubusercontent.com/5719742/68776750-e5b0fd80-0630-11ea-80fb-64e89c039920.PNG)
![transform_ok](https://user-images.githubusercontent.com/5719742/68776789-f2355600-0630-11ea-8ca7-e5b62fc06e31.PNG)

**Comment by Houska1** [comment] 2019-11-18 18:03
Ditto (same upgrade, same issue) for EPSG:26918 to EPSG:2951. I have also opened a separate bug report (#32936 ) for minor problems in doing a manual workaround by choosing an available datum transformation and/or installing a .gsb grid file.

**Comment by bellanz80** [comment] 2019-11-21 15:44
I confirm problem in QGIS 3.10 + PROJ 6.2.1
In my case, the transformation error is to go from EPSG: 6372, to EPSG: UTM 32615 or EPSG: 4326

Video attachment

In QGIS 3.10 + PROJ 5 no problem.
https://drive.google.com/open?id=1Uu0GQMphI2JM9jIDOStB_9mOxtQOYnII

**Comment by torecki** [comment] 2019-11-21 17:16
I confirm the issue in QGIS 3.10 Kompiliert mit PROJ | 6.2.1
and QGIS 3.11.
I get the warning:
> CRITICAL    Keine Transformation zwischen EPSG:3044 und EPSG:3045 verfügbar
> 2019-11-21T09:16:33     CRITICAL    Keine Transformation zwischen EPSG:3044 und +proj=longlat +a=6378137 +rf=298.25722210100002 +no_defs verfügbar
> 2019-11-21T09:20:44     CRITICAL    Keine Transformation zwischen EPSG:3044 und EPSG:25833 verfügbar
> 2019-11-21T10:19:59     CRITICAL    Keine Transformation zwischen EPSG:3044 und EPSG:25833 verfügbar

**Comment by nyalldawson** [comment] 2019-11-25 06:56
Duplicate of #30569

**Closed by nyalldawson** 2019-11-25 06:56 UTC
Labels: Bug, Projections/Transformations
