### ISSUE TITLE
db manager SQL console became very slow

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#40643] opened 2020-12-17 12:31 UTC
Hi all,

See also #40642 
This is the second bug / issue I found. I don't know if or how they are related, but both show up from qgis 3.12.0 onwards and do not show in 3.10.12 and earlier. I have tested this in Qgis 3.4.15, 3.10.4, 3.10.12, 3.12.0, 3.14.16 and 3.16.1

In DB Manager query result are significantly slower, on all tables tested.
Consider the following:
A table with 380 rows with geom (multi-polygon) and a few more fields.
The query Select * From table takes about .4 seconds in DB Manager from 3.12.0 and upwards. In 3.10.12 and earlier, it takes about .004 seconds.
The same query on another table with a little over 108000 rows (multilinestring) takes about 14 seconds from 3.12.0 onwards and about 2.5 seconds for 3.10.12 and earlier.

I am using qgis 64bit, on winodws10 64 bit. The OS, database and qgis are on the same SSD. System is a i5 6th gen with 8 GB memory.

This bug has been reproduced by @raymondnijssen with his own datasets, so I think it can be reproduced easily.

**Comment by gioman** [comment] 2020-12-17 12:34
@Jeroen-GroeneBij @raymondnijssen see https://lists.osgeo.org/pipermail/qgis-developer/2020-July/061797.html (which did not get a lot of traction).

**Comment by gioman** [comment] 2020-12-17 12:35
@Jeroen-GroeneBij probably duplicate of https://github.com/qgis/QGIS/issues/38256

**Comment by Jeroen-GroeneBij** [comment] 2020-12-17 13:17
Indeed it seems like a duplicate, sory I missed that one.

**Closed** 2020-12-17 13:43 UTC
Labels: Bug, DB Manager, Feedback, Regression
