### ISSUE TITLE
Failed to open /usr/share/qgis/resources/data/world_map.gpkg

### ISSUE THREAD

**Issue by pirx3** [qgis/QGIS#35383] opened 2020-03-26 15:46 UTC
**Describe the bug**
Installed QGIS 3.12 on Fedora 31 from:
https://copr.fedorainfracloud.org/coprs/dani/qgis/
When starting QIS as local user - receiving the msg: 
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Keine Berechtigung.
In the layer panel it is not possible to change the order of the layers. 
When running QGIS as root there is no warning message and no issue with the layers.  -->

**How to Reproduce**

![grafik](https://user-images.githubusercontent.com/25775964/77667034-00ea2d00-6f82-11ea-8751-dc42975f0320.png)
In the layer panel, it is not possible to change the order of the layers by drag & drop. 
This will only work when running QGIS as super user (sudo qgis). 

When running QGIS as normal user, following warnings are shown:

![grafik](https://user-images.githubusercontent.com/25775964/77667298-49a1e600-6f82-11ea-9fe4-ffe99df595cb.png)
keine Berechtigung == No permission
**QGIS and OS versions**

QGIS version | 3.12.0-București | QGIS code branch | Release QGIS code branch.3
-- | -- | -- | --
Compiled against Qt | 5.13.2 | Running against Qt | 5.13.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.6 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 31 (Thirty One)
Active python plugins | processing; MetaSearch; db_manager

**Additional context**

Linux Kernel: SMP Mon Oct 21 19:18:58 UTC 2019

**Comment by Gustry** [comment] 2020-03-26 15:48
Can you please fill up the required information in the ticket?
What did you try to do?

**Comment by Susticle** [comment] 2020-04-21 16:33
I notice same error message.

**Describe the bug**
When I double click "OpenStreetMap" in Browser->XYZ Tiles, the following message appears twice in the console:

> Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Keine Berechtigung.

**QGIS and OS versions**
QGIS-Version | 3.12.0-București | QGIS-Codezweig | Release QGIS-Codezweig.3
-- | -- | -- | --
Kompiliert gegen Qt | 5.14.1 | Laufendes Qt | 5.14.2
Kompiliert mit GDAL/OGR | 3.0.4 | Läuft mit GDAL/OGR | 3.0.4
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.31.1 | Läuft mit SQLite | 3.31.1
PostgreSQL-Client-Version | 12.2 | SpatiaLite-Version | 4.3.0a
QWT-Version | 6.1.4 | QScintilla2-Version | 2.11.4
Kompiliert mit PROJ | 6.3.1 | Läuft mit PROJ | Rel. 6.3.1, February 10th, 2020
BS-Version | Arch Linux
Aktive Python-Erweiterungen | GpxSegmentImporter; processing; MetaSearch; db_manager

**Additional context**
Linux version 5.6.4-arch1-1 (linux@archlinux) (gcc version 9.3.0 (Arch Linux 9.3.0-1)) #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000

**Comment by fnx2k** [comment] 2020-09-06 21:03
I confirm this issue for at least a few recent version of QGIS
Presentely testing with qgis 3.10.8-A Coruña on LinuxMint (variant of Ubuntu 18.04)

If you list the data requested:
     ls -la  /usr/share/qgis/resources/data/
    ... 
    -rw-r--r-- 1 root root    25158 févr. 21  2020 world_map_generalize.model3
    -rw-r--r-- 1 root root 12689408 juil. 20 17:47 world_map.gpkg

It shows that these data are present on the disk but with  read/show only for root user.

Maybe packaging script should be modified.

**Comment by landryb** [comment] 2020-10-09 14:28
duplicate of #25876 which is older - probably affects all unix distributions, seeing it on OpenBSD too.

**Comment by Denis4l** [comment] 2020-11-06 09:59
Same problem on fedora 32 execpt that QGIs 3.12 starts normally until I zoom, unzoom or change anything in the map window. Then QGIS freeze, and the map window with a grey screen that's it.

Launching QGIS from a terminal, I get :
`Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: S’ha denegat el permís.
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: S’ha denegat el permís.
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 360, resource id: 36277004, major code: 40 (TranslateCoords), minor code: 0`
I also have a : WARNING    Codec not found. Falling back to system locale no idea if it have something to do with the problem...

**Comment by landryb** [comment] 2021-01-18 13:49
dunno if its linked to a gdal update, but the issue is even more verbose those days with qgis 3.16:
```
Warning 4: Failed to open /usr/local/share/qgis/resources/data/world_map.gpkg: Permission denied.
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_countries_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_countries_geom_update3" AFTER UPDATE ON "countries" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_countries_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_countries_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_countries_geom_update3" already exists
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_states_provinces_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_states_provinces_geom_update3" AFTER UPDATE ON "states_provinces" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_states_provinces_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_states_provinces_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_states_provinces_geom_update3" already exists
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_disputed_borders_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_disputed_borders_geom_update3" AFTER UPDATE ON "disputed_borders" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_disputed_borders_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_disputed_borders_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_disputed_borders_geom_update3" already exists
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_countries_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_countries_geom_update3" AFTER UPDATE ON "countries" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_countries_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_countries_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_countries_geom_update3" already exists
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_states_provinces_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_states_provinces_geom_update3" AFTER UPDATE ON "states_provinces" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_states_provinces_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_states_provinces_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_states_provinces_geom_update3" already exists
ERROR 1: sqlite3_exec(DROP TRIGGER rtree_disputed_borders_geom_update3) failed: attempt to write a readonly database
ERROR 1: sqlite3_exec(CREATE TRIGGER "rtree_disputed_borders_geom_update3" AFTER UPDATE ON "disputed_borders" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_disputed_borders_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_disputed_borders_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END) failed: trigger "rtree_disputed_borders_geom_update3" already exists

```

**Comment by jkugler** [comment] 2021-05-13 18:42
Just hit this on Ubuntu 20.04 (focal) with qgis version 3.18.2+32focal.
```
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
```
File:
```
[jkugler:~] $ ls -la /usr/share/qgis/resources/data/world_map.gpkg
-rw-r--r-- 1 root root 12804096 Apr 14 21:06 /usr/share/qgis/resources/data/world_map.gpkg
```
It is world readable. I assume QGIS is trying to open it in read/write mode, thus the error?

**Comment by jef-n** [comment] 2021-05-13 19:04
Quoting myself from #25876: This is harmless - OGR tries to open r/w and falls back to r/o after that. But this is just for the map display in the CRS selection dialog.

**Comment by mirandadam** [comment] 2021-11-10 14:17
Hi, I know this is an old issue, but I am still seeing this on QGIS release candidate version 3.22.0-Białowieża, QGIS code revision d9022691f1 freshly installed from "https://qgis.org/debian focal". @jef-n is correct in that qgis eventually recovers from the error, but in my machine it takes a good 40 seconds or more for qgis to unfreeze.
By the way, the error message when invoking qgis from the console and clicking in CRS selection dialog is:

```
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
```

**Comment by jef-n** [comment] 2021-11-10 14:45
the "recovery" doesn't take any significant amount of time - if qgis starts slowly on you machine it's most likely something else.

**Closed** 2022-09-11 23:17 UTC
Labels: Build/Install, Bug
