### ISSUE TITLE
QGIS crashing when opening a display layout

### ISSUE THREAD

**Issue by ZMcCarrey** [qgis/QGIS#32254] opened 2019-10-15 09:28 UTC
I think it is because the legend is displaying every layer rather than filtering to the display (which should be the default)

Crash ID: 806f91e2b884e40cab710dd75a0e7a39112e3f22

Stack Trace

QRasterPaintEngine::transformChanged :
QPainter::translate :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
CallWindowProcW :
DispatchMessageW :
IsWindowVisible :
KiUserCallbackDispatcher :
NtUserDispatchMessage :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by gioman** [comment] 2019-10-15 10:06
@ZMcCarrey please try with a new/clean QGIS profile.

**Comment by rouault** [comment] 2020-01-23 19:19
Assuming this was due to a WFS layer, and thus closing as a duplicate of #32913

**Closed by rouault** 2020-01-23 19:19 UTC
Labels: Bug, Feedback
