### ISSUE TITLE
QGIS 3.8 3d render crashing issue

### ISSUE THREAD

**Issue by MatanGolan** [qgis/QGIS#30482] opened 2019-06-30 21:34 UTC
Crash ID: f7290ce4a60391f5f0f439e0a8ec965ceaf13f1e
QGIS 3.8 3d render crashing issue. 
All vectors layers set with spatial index. 

Stack Trace

Qt3DCore::QNode::setEnabled :
QgsWindow3DEngine::trUtf8 :
Qgs3DMapScene::onFrameTriggered :
QMetaObject::activate :
Qt3DLogic::QFrameAction::triggered :
Qt3DLogic::QFrameAction::onTriggered :
Qt3DLogic::QFrameAction::onTriggered :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by wonder-sk** [comment] 2019-07-01 11:47
Hi @MatanGolan is this a duplicate of #30195 that you have raised few weeks ago? It would be good to add more details to the original ticket: 1. what do yo do to get the crash? 2. can you repeatedly get the crash or it happens only sometimes? 3. can you provide the data you used?

**Comment by gioman** [comment] 2019-08-25 09:17
Closing for lack of feedback, please reopen if necessary.

**Closed by gioman** 2019-08-25 09:17 UTC
Labels: Bug, Feedback
