### ISSUE TITLE
Topology Checker crashes

### ISSUE THREAD

**Issue by L-P-beginner** [qgis/QGIS#57627] opened 2024-05-31 09:04 UTC
### What is the bug or the crash?

Using Topology Checker Panel - Must Not have gaps (only) - Validate extent
in a Geopackage layer. It has happened more than once.

(It had run without any issue on a small area, 50 ha, next with 26000 ha, and then in another area of 26000 crashes)

### Steps to reproduce the issue

Topology Checker Panel 
Must Not have gaps (only)
zoom to a small area
Validate extent  -> ok
zoom to a bigger area (more hectares)
Validate extent  -> ok
zoom to a different area aprox same hectares
Validate extent  -> crashes

### Versions

3.34.4-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pathmapper** [comment] 2024-06-04 11:59
Crash reproduced with 3.36.3 on Windows, confirmed this happes with lots of features:

Test data: https://share.krzn.de/exs/action/kreis-viersen/0SZp6Xcq/test.gpkg

```
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00002e00 (most recent call first):
  


Stack Trace


QVariant::QVariant :
version :
QAbstractProxyModel::headerData :
QSortFilterProxyModel::headerData :
QHeaderView::paintSection :
QHeaderView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QProgressDialog::setValue :
QObject::qt_static_metacall :
version :
version :
version :
version :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.36.3-Maidenhead
QGIS code revision: 2df96554
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
```

**Comment by pathmapper** [comment] 2024-06-06 19:18
The first run of a QGIS session is fine -> the issue is fixed by https://github.com/qgis/QGIS/pull/57695

**Comment by troopa81** [comment] 2024-06-11 06:21
@pathmapper Thans for testing, it's indeed the same issue

**Closed by troopa81** 2024-06-11 06:21 UTC
Labels: Bug
