### ISSUE TITLE
QGIS crashed after adding new field with old field name

### ISSUE THREAD

**Issue by gis123456** [qgis/QGIS#32350] opened 2019-10-23 02:48 UTC
h2. User Feedback
h2. Report Details

*Crash ID*: 2e3bc8b4b3e4cb07dc2a89b62cec8cfd37e5942b

*Stack Trace*
<pre>
QgsField::type :
QgsFields::iconForField :
QgsSourceFieldsProperties::setRow :
QgsSourceFieldsProperties::attributeAdded :
QMetaObject::activate :
QgsVectorLayer::attributeAdded :
QMetaObject::activate :
QgsVectorLayerEditBuffer::attributeAdded :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsSourceFieldsProperties::addAttribute :
QgsSourceFieldsProperties::addAttributeClicked :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::qt_static_metacall :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystem

**Describe the bug**

**How to Reproduce**

<!-- Steps, sample datasets and qgis project file to reproduce the behavior. Screencasts or screenshots welcome

1. Go to layer properties
2. Click on Toggle Editing Mode
3. Change field name (was gid - changed to gid1)
4. add new field "gid"
5. Crash 

repeated 2x

Events :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.2.3-Bonn
QGIS code revision: commit:9b176802e5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by nirvn** [comment] 2019-10-23 02:53
@gis123456 , you'll have to provide steps to reproduce this crash alongside the stack trace for devs to look into this.

**Comment by gis123456** [comment] 2019-10-23 02:55
Apologies I thought I had but I must have pasted over it.

1. Open layer properties
2. Click on Source Fields
3. Toggle edit mode 
4. Edit field name (gid to gid1)
5. add new field (potentially before selecting 'apply changes'?)
6. put in field name as gid
7. click apply
8. Crash

repeated 2x

**Comment by nirvn** [comment] 2019-10-23 02:57
@gis123456 , what is the dataset type ( i.e. geopackage, shapefile, etc. ) you are seeing this crash occur with? Can you provide a sample dataset?

**Comment by gis123456** [comment] 2019-10-23 03:01
Apologies - first time bug poster!
shapefile
attached. 
managed to add the field in the format I wanted (was trying to get gid as a different field type to test something)
[receptor_int_bfsubsetv2_sp.zip](https://github.com/qgis/QGIS/files/3759869/receptor_int_bfsubsetv2_sp.zip)

**Comment by nirvn** [comment] 2019-10-23 03:04
@gis123456 , I'm unable to replicate the crasher here. It could be caused by plugins you have installed. You should try to disable all plugins and see if the crash still occurs.

**Comment by gioman** [comment] 2019-10-23 08:19
> repeated 2x

@gis123456 please try with  a new QGIS profile and no 3rd party plugins.

**Comment by gioman** [comment] 2019-12-21 10:05
Probably duplicate of https://github.com/qgis/QGIS/issues/33488

**Comment by gioman** [comment] 2020-03-02 16:09
Closing as duplicate.

**Closed by gioman** 2020-03-02 16:09 UTC
Labels: Bug, Feedback
