### ISSUE TITLE
Mixed Geometry WFS Support

### ISSUE THREAD

**Issue by vovchykbratyk** [qgis/QGIS#49367] opened 2022-07-14 17:10 UTC
### Feature description

I'd like to request support for mixed geometry WFS connections (points, lines and polygons from a single endpoint).  This implementation should take full advantage of QgsAuthManager including username/pass, but also user soft certs (e.g., PKCS12/PKI) for authenticating to the endpoint.  At least 1.0.0 and 1.1.0 required; 2.0 "nice to have" but not necessary.

**Comment by vovchykbratyk** [comment] 2022-07-14 19:33
Yes, I have tried the approach of executing a call, and then dragging the response (as a file) onto QGIS and that works fine at splitting out the geometric types.  However this is kind of "high friction" for users.  Ideally a mixed geometry WFS would be automatically split into proper layers.  But this could also be very computationally/network expensive to do on the fly (e.g., splitting into 3 separate calls limited to point/linestring/polygon).  I hope QGIS can solve this one, because no other GIS has.  I am also a professional ArcGIS user and WFS is even messier there.  Thanks for the tip!

**Comment by rouault** [comment] 2022-09-17 15:57
closing as duplicate of #49328

**Closed by rouault** 2022-09-17 15:57 UTC
Labels: Feature Request
