### ISSUE TITLE
QGIS crash/freeze on Windows 10 

### ISSUE THREAD

**Issue by wmeinolf** [qgis/QGIS#32925] opened 2019-11-18 10:50 UTC
I use QGIS 3.x  since quite a while and observe frequent freezes and crashes. Often random crashes, while qgis was just running witt open project in background. I use Dell Inspiron Laptop with full HD Display plus DELL External UHD Monitor connected via USB-C and 4k Display resolution. I also changed Resolutions on dditional Monitor to FHD only, which had no impact on the crash/Freeze frequency. Recently I discovered, that during travel with Laptop only, QGIS is extremely stable. Therefore I assume, that there may be an issue with 2 Monitor Configurations.

I use windows 10 with all latest updates installed, also latest Dell drivers. I am temporarily downgraded to QGIS 3.8 as 3.10 had an issue wit coordinate reference system conversion but the crash frequency under 3.10.0-2 was similar.

Here the current Crash info:

```
Crash ID: f4475de87e6a815390b3363a83d3fb7ae10fc9c9


Stack Trace


proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :


QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763
```

Let me know, if further Infos are required.

**Comment by gioman** [comment] 2019-11-18 11:09
> Stack Trace
> 
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist

this should have been already solved.

**Comment by gioman** [comment] 2019-11-18 11:09
> Therefore I assume, that there may be an issue with 2 Monitor Configurations.

so if you don't use the dual screen configuration is much more stable?

**Comment by wmeinolf** [comment] 2019-11-18 11:40
I just unplugged my external Monitor to test. It is more stable but still hangs. In this state the winsors task monitir marks the Task as inactive. I opened a large project, zoomed with the mouse a couple of times in and out. This typically leads to a freeze in dual monitor config, when I close QGIS and select discard changes. With single monitor it took a couple of opens and closes, but then ist also crashed with the following:
Crash ID: 62f1fcd2045780cb9f127836e6b579b8665f3e63


Stack Trace


proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.8.3-Zanzibar
QGIS code revision: 685d8b15d2
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

Also, if I operate slowly (wait, until QGIS CPU use in Taskmonitor is back to 0%,), i observe definitely less crash/freeze.

**Comment by wmeinolf** [comment] 2019-11-18 11:42
I meant windows task monitor in first line

**Comment by NathanW2** [comment] 2019-11-18 11:44
This stack trace already looks like something that should be fixed. Are you
sure you get the same stack trace in 3.10 when it crashes?

**Comment by gioman** [comment] 2019-11-18 11:45
> sure you get the same stack trace in 3.10 when it crashes?

I agree @wmeinolf please update to the latest 3.4 or 3.10

**Comment by wmeinolf** [comment] 2019-11-18 12:07
Ok, I'll upgrade later today and come back. Stay tuned.

**Comment by wmeinolf** [comment] 2019-11-18 14:24
Ok, here we are. I reinstalled 3.10 using the stand alone installer. The already reported issue  #32795 re-appeared. I'm now on:

QGIS-Version | 3.10.0-A Coruña | QGIS-Codeversion | 6ffa89eb3e
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.2.1 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | AnotherDXF2Shape; batchvectorlayersaver; ClusterPoints; disconnected-islands; mmqgis; ORStools; Qgis2threejs; qgis2web; QuickOSM; quick_map_services; db_manager; MetaSearch; processing

Sorry for German UI. Now for both, Laptop Only and dual Monitor config I was unable to reproduce the crash. However in both configurations I had QGIS frozen after some attempts, Windows Task Manager stated QGIS inactive. When I clicked the close window button, the windows popup (Qgis doesn't react) appeares, but no QGIS crash window. So unfortunately I can't provide further infos.
![191118 QGIS screenshot](https://user-images.githubusercontent.com/3882351/69060058-fdb0c480-0a16-11ea-8963-6ec5b8af98d0.jpg)
![191118 QGIS screenshot_still inactive](https://user-images.githubusercontent.com/3882351/69060060-00131e80-0a17-11ea-9194-fa412a83e687.jpg)
![191118 QGIS screenshot_attempt to close](https://user-images.githubusercontent.com/3882351/69060062-01dce200-0a17-11ea-9d55-9e5d37466dfb.jpg)
![191118 QGIS screenshot- laptop only](https://user-images.githubusercontent.com/3882351/69060068-03a6a580-0a17-11ea-885b-6095e2209a37.jpg)

Please advise. Thanks

**Comment by gioman** [comment] 2019-11-18 14:26
> Please advise. Thanks

@wmeinolf please try with a new QGIS profile (no 3rd party plugins installed).

**Comment by wmeinolf** [comment] 2019-11-18 14:37
Ok, I'll try, but my projects depend on some plugin's. That may make it tricky, it's my production environment. However before I do so I just killed another freeze, this time a QGIS Message appeared:
--------------------------------
Crash ID: d468ef1b139000c558c2610e55cf05c5767d4b17


Stack Trace


osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
GMLFeature::SetPropertyDirectly :
IGMLReader::~IGMLReader :
RegisterOGRGML :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :




QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

Let me know, if this is related. Should it be a different issue or should it not hepl, I'll try new profile again and see, if it freezes without plugin's.

I'll wait for you response. Thanks!

**Comment by roya0045** [comment] 2019-11-18 14:56
> ## Ok, I'll try, but my projects depend on some plugin's. That may make it tricky, it's my production environment. However before I do so I just killed another freeze, this time a QGIS Message appeared:
> Crash ID: d468ef1b139000c558c2610e55cf05c5767d4b17
> 
> Stack Trace
> 
> osgeo::proj::datum::Datum::conventionalRS :
> osgeo::proj::datum::Datum::conventionalRS :
> osgeo::proj::datum::Datum::conventionalRS :
> OGRSpatialReference::~OGRSpatialReference :
> OGRSpatialReference::operator= :
> OGRGeomFieldDefn::~OGRGeomFieldDefn :
> OGRFeatureDefn::~OGRFeatureDefn :
> OGRFeatureDefn::~OGRFeatureDefn :
> GMLFeature::SetPropertyDirectly :
> IGMLReader::~IGMLReader :
> RegisterOGRGML :
> QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
> QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
> QMetaObject::activate :
> QTimer::timerEvent :
> QObject::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QEventDispatcherWin32Private::sendTimerEvent :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> 
> QGIS Info
> QGIS Version: 3.10.0-A Coru�a
> QGIS code revision: [6ffa89e](https://github.com/qgis/QGIS/commit/6ffa89eb3e5f5462ea6a88353ece172f0098b2a3)
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 3.0.2
> Running against GDAL: 3.0.2
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.17763
> 
> Let me know, if this is related. Should it be a different issue or should it not hepl, I'll try new profile again and see, if it freezes without plugin's.
> 
> I'll wait for you response. Thanks!

That's just your datum that is incompatible with proj6. You could reproject the layer to a supported datum before opening the project.

**Comment by wmeinolf** [comment] 2019-11-18 15:04
Hm, work with those data since ages. I never had an issue and it's lot's work to reproject all my existing layers. Also I used same files with same datum in the last half hour with unpluged external Monitor. I got the warning, but I had no freeze at all nor any QGIS crash. Would it make sense, to postpone the further investigation to the next point release next week, or will the datum still be unsupported. As I mentioned before, I see this related to the already reported issue #32795 .
I'm afraid, I run out of time with reconfiguring my pc during this week.

**Comment by gioman** [comment] 2019-11-18 15:05
> Hm, work with those data since ages. I never had an issue and it's lot's work to reproject all my existing layers. Also I used same files with same datum in the last half hour with unpluged external Monitor. I got the warning, but I had no freeze at all nor any QGIS crash. Would it make sense, to postpone the further investigation to the next point release next week, or will the datum still be unsupported. As I mentioned before, I see this related to the already reported issue #32795 .
> I'm afraid, I run out of time with reconfiguring my pc during this week.

can you update the subject? it does seems dual screen related.

**Comment by wmeinolf** [comment] 2019-11-18 15:31
Done. I hope I understood you correctly.

**Comment by gioman** [comment] 2019-11-18 15:37
> Done. I hope I understood you correctly.

no, The title still implies that the crash is related to a dual screen/monitor setup. Does not seems the case to me.

**Comment by wmeinolf** [comment] 2019-11-18 16:32
> can you update the subject? it does seems dual screen related.

Ok, is or is not? Your comment stated, it is related. Perhaps a typo. I will change the title but will work tomorrow all day with unplugged second monitor. It's a bit inconveniant for me but we will see, if I will have any freezes/crash at all. Thankfs for your support.

**Comment by wmeinolf** [comment] 2019-11-19 14:34
After spending another day working in various configurations witt Laptop only AND both screns I am completely confused. (1) With clean Profile no crash/freeze at all. (2) With Single Plugin (OSMTools) loaded, QGIS crashed after about 10mins when just put in background while working witt Excel. Deinstalled OSMTools, everything was fine on single or dual Monitor config. Reinstalled QSM Tool, and surprisingly I had no further crash/freeze from late morning until now. I additionaly loaded MMQGIS, opened existing QGZ and left it in background to write this statement. While doing so, Qgis crashed again with this text:
Crash ID: 029bc1a9b819dfb49a1342291172e44f3c1f8e53


Stack Trace


osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
SHPWriteObject :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
SHPWriteObject :
DBFWriteTuple :
OGREditableLayer::Translate :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :

Should this trace be related to the missing CRS translation I suggest to close this issue. I plan to wipe all QGIS versions currently installed, cleaning the registry and install the upcoming point release. Once I get next crash/freeze I will then open a new issue.

Please advise and feel free, to close this issue.

Thanks for your help and best regards.


QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by wmeinolf** [comment] 2019-11-19 15:10
Ok, I again created new profile. Opened existing qgz and put to background by opening Firefox. Crash after less than 5mins in both configs, Laptop only and dual screen. Means, it's indeed not related to dual screen . Report is similar for both configs:
Crash ID: 214a408c61abeb7fb956174cd1ac704781309a67


Stack Trace


osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
osgeo::proj::datum::Datum::conventionalRS :
OGRSpatialReference::~OGRSpatialReference :
OGRSpatialReference::operator= :
OGRGeomFieldDefn::~OGRGeomFieldDefn :
OGRFeatureDefn::~OGRFeatureDefn :
OGRFeatureDefn::~OGRFeatureDefn :
GMLFeature::SetPropertyDirectly :
IGMLReader::~IGMLReader :
RegisterOGRGML :
QgsOgrProviderUtils::GDALCloseWrapper qgsogrprovider.cpp:4129
QgsConnectionPoolGroup::onConnectionExpired qgsconnectionpool.h:227
QMetaObject::activate :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1598
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.0-A Coru�a
QGIS code revision: 6ffa89eb3e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.2
Running against GDAL: 3.0.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by roya0045** [comment] 2019-11-19 15:12
Can you state what plugins, basemaps were present and what was the projection of the project?

**Comment by wmeinolf** [comment] 2019-11-19 15:30
I'm currently on a clean new profile without any plugin. See attached screenshot for layer structure. Laywes OSM Insprctor Adresses, OSM Standard, Google.cn Sattellites and Open Topo Map were added with previous QGIS releases using QuickMapServices  Plugin. all are EPSG 3857. Layers sie01_xxx ate German Digital landscape model and EPSG 3044. Some layers are EPSG 4326 (imported KMZ Files) Other layers are EPSG 25832, as this is the new standard CRS here in Germany. Layers are stored as SHP or GPKG. 

Maybe this is also of help:

QGIS-Version | 3.10.0-A Coruña | QGIS-Codeversion | 6ffa89eb3e
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.0.2 | Läuft mit GDAL/OGR | 3.0.2
Kompiliert mit GEOS | 3.8.0-CAPI-1.13.1 | Läuft mit GEOS | 3.8.0-CAPI-1.13.1
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.2.1 | Läuft mit PROJ | Rel. 6.2.1, November 1st, 2019
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | db_manager; MetaSearch; processing



![191119 QGIS Screen](https://user-images.githubusercontent.com/3882351/69160351-b5aea200-0ae9-11ea-9fdb-2d52f1b8bdcb.jpg)

**Comment by roya0045** [comment] 2019-11-19 15:54
This seems like a basemap and proj6 issue. :/ I'm not too sure if its the plugin that must change its call or something else.

**Comment by nyalldawson** [comment] 2019-11-25 06:58
Caused by upstream GDAL issue - see https://github.com/OSGeo/gdal/commit/ec3b30e0d325189ef0be23be08a20fb0136366a0

**Closed by nyalldawson** 2019-11-25 06:58 UTC
Labels: Bug, Crash/Data Corruption, Feedback, High Priority

**Comment by geoitconsultores** [comment] 2021-08-12 16:02
> I use QGIS 3.x since quite a while and observe frequent freezes and crashes. Often random crashes, while qgis was just running witt open project in background. I use Dell Inspiron Laptop with full HD Display plus DELL External UHD Monitor connected via USB-C and 4k Display resolution. I also changed Resolutions on dditional Monitor to FHD only, which had no impact on the crash/Freeze frequency. Recently I discovered, that during travel with Laptop only, QGIS is extremely stable. Therefore I assume, that there may be an issue with 2 Monitor Configurations.
> 
> I use windows 10 with all latest updates installed, also latest Dell drivers. I am temporarily downgraded to QGIS 3.8 as 3.10 had an issue wit coordinate reference system conversion but the crash frequency under 3.10.0-2 was similar.
> 
> Here the current Crash info:
> 
> ```
> Crash ID: f4475de87e6a815390b3363a83d3fb7ae10fc9c9
> 
> 
> Stack Trace
> 
> 
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist :
> proj_lpz_dist :
> QgsCoordinateTransform::transformPolygon :
> QgsCoordinateTransform::transformPolygon :
> QgsCoordinateTransform::QgsCoordinateTransform :
> QHashData::free_helper :
> QgsCoordinateTransform::addToCache :
> QgsCoordinateTransform::invalidateCache :
> QgsApplication::exitQgis :
> QgisApp::~QgisApp :
> CPLStringList::operator[] :
> main :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> 
> QGIS Info
> QGIS Version: 3.8.3-Zanzibar
> QGIS code revision: 685d8b15d2
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 2.4.1
> Running against GDAL: 2.4.1
> 
> 
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.17763
> ```
> 
> Let me know, if further Infos are required.

Hi, have you try "open as Administrator"?

**Comment by gioman** [comment] 2021-08-12 16:31
> Hi, have you try "open as Administrator"?

@geoitconsultores this issue has been solved since 2019.
