### ISSUE TITLE
Graphical modeller array input not working

### ISSUE THREAD

**Issue by robbieaustrums** [qgis/QGIS#48172] opened 2022-04-11 14:40 UTC
### What is the bug or the crash?

Where a processing tool in the graphical modeller requires a list of inputs, I have in the past used an expression 'array( item1, item2, ...)' as the input. This works fine in QGIS 3.22 LTR, but in 3.24 results in an error:

TypeError: unable to convert a C++ 'QVariantList' instance to a Python object
or
TypeError: unable to convert a C++ 'QVariantMap' instance to a Python object 

I've tested this with 'Merge vector layers' and 'Build virtual raster' processing tools and the same problem occurs.

### Steps to reproduce the issue

1. Create a new graphical model
2.  Add two vector layer inputs called Layer1 and Layer2
3. Add a single algorithm, Merge Vector Layers
4. Set the algorithm input to array( @layer1, @layer2 )
5. Give the algorithm an output name
6. Run the model. Error will occur in the log

![QgisBugReport](https://user-images.githubusercontent.com/65067514/162761495-3b534b24-4cbe-4770-b70e-0fe8d5f48047.PNG)

[BugReport_model3.zip](https://github.com/qgis/QGIS/files/8464922/BugReport_model3.zip)

### Versions

Bug does not affect 3.22 LTR

Bug does affect:

QGIS version
3.24.1-Tisler
QGIS code revision
5709b824
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
HCMGIS
21.8.28
profiletool
4.1.8
QuickOSM
2.0.0-beta3
quick_map_services
0.19.11.1
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-04-11 15:14
Can't reproduce on Master

Related to https://github.com/qgis/QGIS/issues/47955 and fixed by https://github.com/qgis/QGIS/pull/48021 

@robbieaustrums Can you try on Master and 3.24-Nightly to confirm it is fixed ?

**Comment by robbieaustrums** [comment] 2022-04-11 18:15
@nicogodet yes, appears to be fixed in 3.25.0 nightly

**Closed** 2022-04-11 19:05 UTC
Labels: Processing, Bug, Modeller
