### ISSUE TITLE
Scale bar length (decoration): mismatch between stated length and measured length

### ISSUE THREAD

**Issue by dhdeangelis** [qgis/QGIS#41659] opened 2021-02-18 09:19 UTC
I am experiencing an issue with the scale bar (decoration): the stated length of the scale bar (decoration) does not match the measured length.

This happens in several projects, both existing and new. In all tested cases both layer and project CRS are the same and there is no EPSG:3857, 4326 or layers that use mixed CRS. The default unit is meters. Also, the mismatch is far greater than any difference between ellipsoidal and cartesian distances. See example below in UTM44N, but also seen in 18S and 34N.

The issue may probably be related to #40748 (closed). "zooming to previous" helps in case of existing projects.

**How to Reproduce**

1. Open a new project
2. Load a layer
3. Project and layer should ideally be in same coordinate reference system
3. Display a scale bar (decoration)
4. Measure scale bar

![Screenshot_2021-02-18_08-42-46](https://user-images.githubusercontent.com/51515911/108334958-b9d8dc00-71d2-11eb-9a4c-5477bd516899.png)

![Screenshot_2021-02-18_08-48-42](https://user-images.githubusercontent.com/51515911/108334972-bf362680-71d2-11eb-95db-659dcbbdb085.png)

**Comment by agiudiceandrea** [comment] 2021-02-18 09:36
Duplicate of https://github.com/qgis/QGIS/issues/40748 already fixed with https://github.com/qgis/QGIS/pull/41056 and https://github.com/qgis/QGIS/pull/41065. The fix will be available in QGIS 3.16.4.

**Comment by dhdeangelis** [comment] 2021-02-18 09:36
OK. Thanks.

**Closed** 2021-02-18 09:37 UTC
Labels: Bug

**Comment by SimDiet** [comment] 2021-07-01 09:09
I am still experiencing this same issue although using QGIS Desktop 3.16.7.
![Screenshot 2021-07-01 110729](https://user-images.githubusercontent.com/67374272/124098166-982f1180-da5c-11eb-8b86-e8a7a337274d.png)
![Screenshot 2021-07-01 110833](https://user-images.githubusercontent.com/67374272/124098286-b39a1c80-da5c-11eb-8746-0fb968264172.png)

**Comment by agiudiceandrea** [comment] 2021-07-01 09:26
@SimDiet could you share a minimal project in which the incorrect reported behaviour is present?

**Comment by SimDiet** [comment] 2021-07-01 09:42
when I tried to reproduce this behaviour in a new project, I found that it is constricted to a rotated map view like in this project
[issue#41659.zip](https://github.com/qgis/QGIS/files/6747158/issue.41659.zip)

**Comment by agiudiceandrea** [comment] 2021-07-01 10:54
@SimDiet the cause of your issue is different from this issue. So, I think it's better to open a new bug report mentioning that the scale bar decoration is incorrect when the map is rotated. Thanks.
