### ISSUE TITLE
Arcgis REST servers kept duplicating when renamed and impossible to delete

### ISSUE THREAD

**Issue by IspookGt** [qgis/QGIS#54718] opened 2023-09-23 14:27 UTC
### Arcgis REST Server will not go away after deleting it many times

After i made a file for a specific REST server, i wanted to change the name of the file to avoid confusion with my other files. ended up wit a few copies of that file and they are impossible to delete, :(

### Steps to reproduce the issue

1. Open Qgis 3.32.3 Lima
2. Click on Arcgis REST server, add new connection
3. Save the new connection,it should show up at the REST server tab
4. Right Click on said connection, click rename, save
5. There are now probably two files on the tab. one with the old name and one with the new name :)
![Uploading Screenshot (179).png…]()

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
HCMGIS | 23.7.19
ORStools | 1.6.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.3-Lima
QGIS code revision
[67d46100b5](https://github.com/qgis/QGIS/commit/67d46100b5)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
HCMGIS
23.7.19
ORStools
1.6.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

tried right clicking and finding a backdoor to delee the files by code, cant find 'em

**Comment by agiudiceandrea** [comment] 2023-09-24 08:44
Hi @3nids, this seems to me similar to https://github.com/qgis/QGIS/issues/53321. Do you have any clue about what's going wrong with the new settings/configs for connections?

**Comment by 3nids** [comment] 2023-09-25 05:38
> After i made a file for a specific REST server, i wanted to change the name of the file to avoid confusion with my other files. ended up wit a few copies of that file and they are impossible to delete, :(

what do you mean by file? the project file?

> Steps to reproduce the issue

Screenshot hasn't been uploaded.

I cannot reproduce the issue using the add layer dialog.
But there is no "rename button", I have a drop-down selector and I have to click on "edit".

<img width="722" alt="image" src="https://github.com/qgis/QGIS/assets/127259/e4cf034f-2359-4af4-922d-a13d762002e9">

I don't see any Arcgis connections in DB manager, so I'm wondering where you have this experience. Uploading the screenshot would help.

**Comment by pathmapper** [comment] 2023-11-19 06:28
There are still issues with master (461a3158d01).

-> details in https://github.com/qgis/QGIS/issues/53321#issuecomment-1817761926

**Comment by agiudiceandrea** [comment] 2024-12-13 08:00
I guess this should have been fixed by https://github.com/qgis/QGIS/pull/59216.

**Closed by agiudiceandrea** 2024-12-13 08:00 UTC
Labels: Regression, Bug, Configs and Options
