### ISSUE TITLE
In categorized renderer, "Show feature count" returns 0 if category value is "all other values" (null)

### ISSUE THREAD

**Issue by malien24** [qgis/QGIS#30639] opened 2019-07-09 09:50 UTC
**Describe the bug**

In categorized renderer, "Show feature count" returns 0 if category value is "all other values" (null) and other category values count properly.
**How to Reproduce**
1) Make 4 objects with source field "name" and make "name" for first object "a", second "b", therd "c", fours "d" .
2)In symbology chose "Categorized"; column - "name";
   add category: value "a" - "legend" "a",value "b" - legend "b" and without category (in QGIS 3.8 named "all other values") - legend "other"
All 4 objects draw correctly by simbology.
3)chose "Show feature count" and we see all =4, "a"=1, "b"=1, "other"=0 

**QGIS and OS versions**
Windows 8.1 corp x64 and Windows 10 x64, QGIS 3.2, 3.8 and 3.4 long term release

**Additional context**
In QGIS 2.18.20 all work correctly

![bug-qgis 3](https://user-images.githubusercontent.com/48380252/60878556-9acd4680-a248-11e9-8112-7c5e323d54e1.jpg)

**Comment by roya0045** [comment] 2019-07-10 17:07
Same behavior in 3.4.

Is it possibly that is has to do with the symbol_id when having a generic category.

I made a layer with 3 categories and the 2nd one was the 'catch-all'. When checking the count with featureCount, the key '0' and '2' provided the proper count but not the key '1'.

And since the total count is the good one, this means that the counting is done properly. 

It might be an issue with the category symbols.

**Comment by roya0045** [comment] 2019-07-11 14:04
@nyalldawson @wonder-sk  I have looked into this to some extent, and I would like your opinion on my hypothesis, I would like your opinions as you might be more familiar with that part of the code.

If we look at [this part of the code](https://github.com/qgis/QGIS/blob/f3dcd8211ec2fa8e636003ffe9936dae2eb8eb24/src/core/symbology/qgscategorizedsymbolrenderer.cpp#L272), the default value for the main class is used (the empty string).

If the base feature is represented by an empty string as a catch-all during feature count. That means that categories that have an empty string and meant to act as "Else" categories have a name conflict with the feature's and this would prevent proper counting for that case. 

I thought it might also be the render context having an issue with the empty value when the expressionContext is set in the featurecounter but this would act as a catch-all unless skipped, so this is unlikely.

Would that explain things and do we want to prevent such name collisions if this is the cause?

**Comment by roya0045** [comment] 2019-07-18 17:14
@malien24 @gioman The fix is to set the categories and then switch to rule-based. Categories symbols work on a 1 value basis (ie the value of the column must match exactly the one in the value column). This make sens, this also mean that any 'ELSE' case can only be handled by the rule-based approach.

**Comment by malien24** [comment] 2020-03-12 11:49
In QGIS 3.12.0 not working

**Comment by gioman** [comment] 2020-08-05 12:18
Duplicate of https://github.com/qgis/QGIS/issues/27893

**Closed by gioman** 2020-08-05 12:18 UTC
Labels: Bug, Map and Legend, Regression

**Comment by malien24** [comment] 2022-12-07 07:34
Why closed? It still not working in QGIS 3.22

**Comment by malien24** [comment] 2022-12-07 07:46
That bug not duplicate #27893, it another kind of bug bicause in #27893 "**rule based**" renderer and in my ticket bug in **categorized** renderer
