### ISSUE TITLE
non English text is not rendered properly

### ISSUE THREAD

**Issue by nabazgharib** [qgis/QGIS#49517] opened 2022-07-30 14:04 UTC
### What is the bug or the crash?

the text label is not rendered properly when the **placement mode** is changed to Curved.
the correct display of text is:
![image](https://user-images.githubusercontent.com/4522358/181917757-b30ec1b6-c798-4d19-aac2-d184e7053356.png)

however, when the placement mode is changed to Curve, the text is rendered as below:
![image](https://user-images.githubusercontent.com/4522358/181937228-a45ff22c-8c0f-4aac-aef6-0b55fd9933e0.png)

### Steps to reproduce the issue

1. To replaicate the issue exactly, use this text (طريق مطار المثنى)  and added to a field of a datasource with line geometry.
2. label the line, and change the placement to Curve.
3. You can change the modes to see how the text is rendered.

### Versions

QGIS version
3.22.9-Białowieża

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by saberraz** [comment] 2022-07-30 14:18
I'm pretty sure this is duplicate. I opened the same ticket a while back

**Comment by roya0045** [comment] 2022-07-30 14:48
Can't see second image, may be a duplicate of #21940

**Comment by nabazgharib** [comment] 2022-07-30 18:44
@roya0045 ,
I check the issue you mentioned, it is not exactly duplicate. I reuploaded the image you can see the deference.

**Comment by DelazJ** [comment] 2022-07-31 11:26
To me, it is the same. The letters are "individualized" and displayed in the opposite order (https://github.com/qgis/QGIS/issues/21940#issuecomment-495853799). Can you explain what is different here @nabazgharib ? Thanks.

**Comment by nabazgharib** [comment] 2022-08-02 07:41
> To me, it is the same. The letters are "individualized" and displayed in the opposite order ([#21940 (comment)](https://github.com/qgis/QGIS/issues/21940#issuecomment-495853799)). Can you explain what is different here @nabazgharib ? Thanks.

That is correct, the text is not merged and displayed in opposite order.

**Comment by saberraz** [comment] 2022-08-02 08:46
Duplicate of https://github.com/qgis/QGIS/issues/21940

**Closed by saberraz** 2022-08-02 08:46 UTC
Labels: Feedback, Labeling, Bug
