### ISSUE TITLE
Browser Panel: Favorites, the icons for shapefiles are unique and the type of geometry is not distinguished

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#40980] opened 2021-01-13 09:12 UTC
As per object, both for points, lines and polygons the polygon icon is always displayed making it impossible to understand the type of geometry.

![image](https://user-images.githubusercontent.com/7631137/104430869-8a0d3780-5587-11eb-8c04-21d2bd0665f8.png)

## OSGeo4W64 Win10

![image](https://user-images.githubusercontent.com/7631137/104431014-b88b1280-5587-11eb-93ea-f0ad7dab2738.png)

Clean profile!

**Comment by gioman** [comment] 2021-01-13 15:33
Duplicate of https://github.com/qgis/QGIS/issues/17347 (that contains the proper solution).

**Closed by gioman** 2021-01-13 15:33 UTC
Labels: Bug, QGIS Browser

**Comment by pigreco** [comment] 2021-01-13 18:54
![image](https://user-images.githubusercontent.com/7631137/104496376-3592a800-55d9-11eb-8f1c-c9e664790c2e.png)

**Comment by gioman** [comment] 2021-01-14 13:09
@pigreco is the image meant to sent a message? If yes I don't get it.

**Comment by pigreco** [comment] 2021-01-14 13:14
> @pigreco is the image meant to sent a message? If yes I don't get it.

no, just to document how and where to intervene

grazie
