### ISSUE TITLE
No Vector Tile Clipping on SVG Print Layout Export

### ISSUE THREAD

**Issue by frodrigo** [qgis/QGIS#41052] opened 2021-01-17 20:54 UTC
The export of the print layout works fine with PDF, but the same on SVG have trouble on tiles border.

MVT tiles can have a buffer of data outside the visible area. The data and the render have to be clipped on this visible area. It works fine on QGIS map view, print layout view and PDF export.

But on SVG export the clipping is not done, so extra data can be view. But the goal of this extra buffer is to be hidden to avoid styling artifact.

To reproduce. Add a vecto tile map from a "Vecto Tileset", styling is not even required. Make a new layout with this map. Export as PDF and SVG.

PDF:
![imagen](https://user-images.githubusercontent.com/1785486/104855464-385d0800-590d-11eb-9a87-ffd1571f2b47.png)
[5.pdf](https://github.com/qgis/QGIS/files/5826803/5.pdf)

SVG:
![imagen](https://user-images.githubusercontent.com/1785486/104855482-51fe4f80-590d-11eb-8cc3-99b5be3f11b8.png)
[5.svg.zip](https://github.com/qgis/QGIS/files/5826806/5.svg.zip)

Example on real use case, show extra ends of road on buffer tile border because the features are not clipped at the border of the visible tile area.
![imagen](https://user-images.githubusercontent.com/1785486/104855612-0304ea00-590e-11eb-9ad2-79616e990857.png)

Show on last QGIS 3.16.0, Linux.

**Comment by nyalldawson** [comment] 2021-01-17 21:53
Duplicate of https://github.com/qgis/QGIS/issues/10218

**Closed by nyalldawson** 2021-01-17 21:53 UTC
Labels: Bug
