### ISSUE TITLE
Copy/Paste Styles as Keyboard Shortcut no longer works

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29323] opened 2019-03-07 01:04 UTC
Author Name: **Stephen Pang** (@pangcorp)
Original Redmine Issue: [21506](https://issues.qgis.org/issues/21506)
Affected QGIS version: 3.6.0
Redmine category:editing

---
Before 3.6, this feature worked.

**Comment by DelazJ** [comment] 2019-08-09 15:08
@pangcorp Any chance to have more details on what you mean? Or can you check your issue on a more recent release?
On master:
* I've setup shortcuts for both "copy style" and "paste style" actions and they work
* I've used these actions from the layer menu and the layer panel and they work
* I can copy a class from a layer categorized symbology and paste it in the same dialog (this used to fail recently but now fixed)

Are you reporting something else?

**Comment by jgrocha** [comment] 2019-11-25 23:09
Hi,

In my 3.11.0-Master, the problem is: you have to do "copy" twice to get the style in the clipboard.

I've created a shortcut F4 for copy and F8 for paste. To copy and paste a style, I have to hit twice F4 and only then F8.

I didn't dig into this issue, but there is some strange behaviour in **copy and paste** styles. Coping twice works, but it is annoying.

Can someone else confirm this? It can be a local issue.

**Comment by suricactus** [comment] 2020-03-29 07:16
Works fine on 3.12 and current master for me.

**Comment by pangcorp** [comment] 2020-03-29 09:33
It's fine now, just didn't work sometime from 3.6 up to now.

**Closed** 2020-03-29 09:35 UTC
Labels: Bug, Editing, Feedback, High Priority, Regression
