### ISSUE TITLE
3.26 attribute table no longer a seperate window on Windows

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#49863] opened 2022-08-20 12:23 UTC
### What is the bug or the crash?

Using 3.26.2 on a Windows machine attribute tables are no longer a separate window on Windows, but seem to 'stay within the QGIS window/environment'. Minimizing the attribute table makes it go to the lower left corner within the QGIS window and on my 13" screen even blocking the locater/search bar.

![afbeelding](https://user-images.githubusercontent.com/26653761/185745977-e16921a2-be97-4ed6-97c7-e5814b9d74f4.png)

### Steps to reproduce the issue

Open any layer in 3.26.2 on a Windows machine
Open the attribute table, it no longer appears as a separate window on the Windows taskbar.
Minimize the attribute table, it minimizes within QGIS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code revision
[feec3d3b12f](https://github.com/qgis/QGIS/commit/feec3d3b12f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-08-20 12:42
OK in 3.22.10

**Comment by andreasneumann** [comment] 2022-08-20 12:46
Is this "Open attribute table as docked window" setting active?

![image](https://user-images.githubusercontent.com/884476/185746785-504a9477-915a-4ec8-a7e1-e6e07f4a09ca.png)

**Comment by nicogodet** [comment] 2022-08-20 12:49
@andreasneumann No it's not.

**Comment by nicogodet** [comment] 2022-08-20 12:54
This could have been introduced by https://github.com/qgis/QGIS/pull/47922

**Comment by Jeroen-GroeneBij** [comment] 2022-08-21 07:43
That could be it. By the way, that new feature is not mentioned in the changelogs.

In addition to the bug description: once minimized I can not move the minimized table. As such, it keeps blocking the locator bar.

**Comment by nicogodet** [comment] 2022-08-21 08:59
I'm not sure this is a feature 😊 

Ping @nyalldawson

**Comment by agiudiceandrea** [comment] 2022-08-21 09:30
> that new feature is not mentioned in the changelogs

@Jeroen-GroeneBij, it seems to me the feature is in the changelog: see https://www.qgis.org/it/site/forusers/visualchangelog326/index.html#feature-optionally-store-ui-configuration-in-projects

**Comment by roya0045** [comment] 2022-08-24 16:28
Seems to be a duplicate of #49286

**Comment by nicogodet** [comment] 2022-08-25 06:23
@roya0045 Indeed

**Closed by nicogodet** 2022-08-25 06:23 UTC
Labels: GUI/UX, Bug
