### ISSUE TITLE
QGIS crashes when exporting layout as atlas with a geometry generator expression

### ISSUE THREAD

**Issue by Mickeler** [qgis/QGIS#42625] opened 2021-04-02 12:44 UTC
My QGIS version crash when try to create pdf using layout. Is that only memory issue in my PC?

Crash ID: 3c2db2e64ac601962aba9c96a4ad262dc65f110c

Stack Trace

QTextOption::wrapMode :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QPainter::drawTiledPixmap :
QgsFillSymbolLayer::_renderPolygon :
QgsImageFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsGeometryGeneratorSymbolLayer::render :
QgsSymbol::renderUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsLayoutItemMap::drawMap :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLayoutExporter::exportToPdf :
QgsLayoutExporter::exportToPdfs :
QgsMapToolRotateLabel::setRotationPreviewBox :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment] 2021-04-02 12:53
More details needed on the settings used.

**Comment by gioman** [comment] 2021-04-02 15:55
> My QGIS version crash when try to create pdf using layout. Is that only memory issue in my PC?

@Mickeler are you using the "print as raster" option?

**Comment by Mickeler** [comment] 2021-04-02 16:00
I tried also in older version but still crashing

Crash ID: 86668c6e33a44c1fd086449d3a6bfe956d277378


Stack Trace


QTextOption::wrapMode :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QPainter::drawTiledPixmap :
QgsFillSymbolLayer::_renderPolygon :
QgsImageFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsGeometryGeneratorSymbolLayer::render :
QgsSymbol::renderUsingLayer :
QgsFillSymbol::renderPolygon :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerLabelProvider::stopRender :
QgsVectorLayerLabelProvider::stopRender :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsLayoutItemMap::drawMap :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLayoutExporter::exportToPdf :
QgsLayoutExporter::exportToPdfs :
QgisApp::actionAddWcsLayer :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by Mickeler** [comment] 2021-04-02 16:01
> > My QGIS version crash when try to create pdf using layout. Is that only memory issue in my PC?
> 
> @Mickeler are you using the "print as raster" option?

Export as pdf

**Comment by gioman** [comment] 2021-04-02 16:01
> I tried also in older version but still crashing

@Mickeler please attach a project + sample data (and the offending layout).

**Comment by gioman** [comment] 2021-04-02 16:01
> Export as pdf

@Mickeler yes sure, but is the "print as raster" option active?

**Comment by Mickeler** [comment] 2021-04-02 16:03
> > I tried also in older version but still crashing
> 
> @Mickeler please attach a project + sample data (and the offending layout).

Unfortunately too big to attach, vector map which has several map layers. I can export sigle page but using atlas will crash after some pages

**Comment by gioman** [comment] 2021-04-02 16:05
> I can export single page but using atlas will crash after some pages

@Mickeler so it crashes **only** when exporting an atlas? if yes, does it crash always at the same page?

**Comment by Mickeler** [comment] 2021-04-02 16:10
> > I can export single page but using atlas will crash after some pages
> 
> @Mickeler so it crashes **only** when exporting an atlas? if yes, does it crash always at the same page?

I dont know yet is it same page. After crashing need to restart project again...

**Comment by gioman** [comment] 2021-04-02 16:11
> I dont know yet is it same page. After crashing need to restart project again...

@Mickeler so it crashes only when exporting an atlas?

**Comment by gioman** [comment] 2021-04-02 16:14
> Unfortunately too big to attach,

@Mickeler can you create a smaller project where the problem still presents itself?

**Comment by Mickeler** [comment] 2021-04-02 17:19
I suppose crash will occured when using geometry generator. I have nature reserve-areas which border line has created using next formula: difference($geometry, buffer($geometry, -20))

**Comment by gioman** [comment] 2021-04-02 17:24
> I suppose crash will occured when using geometry generator.

@Mickeler so if you remove the geometry generator from the equation, no crash?

**Comment by Mickeler** [comment] 2021-04-02 17:27
> > I suppose crash will occured when using geometry generator.
> 
> @Mickeler so if you remove the geometry generator from the equation, no crash?

yes

![image](https://user-images.githubusercontent.com/56861661/113438755-e39c3a00-93f1-11eb-8cc1-5401e24da3a6.png)

**Comment by Mickeler** [comment] 2021-04-02 17:43
I changed formula using only -1 metre buffer: difference($geometry, buffer($geometry, -1))
Still crashing...

**Comment by gioman** [comment] 2021-04-02 18:00
> I changed formula using only -1 metre buffer: difference($geometry, buffer($geometry, -1))

@Mickeler the size of the buffer probably does not matter, it is the generator that seems to create the issue.

**Comment by nyalldawson** [comment] 2021-04-03 01:59
Duplicate of 41971

**Closed by nyalldawson** 2021-04-03 01:59 UTC
Labels: Bug, Crash/Data Corruption, Print Layouts

**Comment by Mickeler** [comment] 2021-04-08 05:34
I managed to avoid a qgis crash with the following change where I changed the line width from millimeters to map units. Make sense? There is also some examples as attached file
[line_definition.zip](https://github.com/qgis/QGIS/files/6276274/line_definition.zip)
