### ISSUE TITLE
Rotate feature

### ISSUE THREAD

**Issue by hroena** [qgis/QGIS#32834] opened 2019-11-13 15:31 UTC
I am trying to rotate a feature, and QGIS keeps hanging up. This is happening with both lines and polygons. After several minutes, I hit the "X" to close out the window I get the error message "qgis-bin-g7.exe is not responding"
![scrnshot](https://user-images.githubusercontent.com/48995556/68778161-c7330e00-0600-11ea-9913-ee787745deb3.jpg)

I am using QGIS 3.10.0 with GRASS 7.6.1 on a Windows 10 computer.

**Comment by roya0045** [comment] 2019-11-13 16:22
duplicate of #32123

**Closed** 2019-11-13 17:07 UTC
Labels: Bug
