### ISSUE TITLE
 Coordinate error when exporting to kml famat

### ISSUE THREAD

**Issue by eagle-blue** [qgis/QGIS#33141] opened 2019-11-29 01:19 UTC
When converting from shapefile to kml, the exported latitude and longitude coordinates of the kml file are reversed, that is, the longitude becomes latitude, and the latitude becomes longitude.

**Comment by elpaso** [comment] 2019-11-29 08:48
I believe this was fixed in master last week.

**Comment by eagle-blue** [comment] 2019-11-29 09:38
> 我相信上周这个问题已经解决了。

thanks.
but Where should I get the latest installation package?

**Comment by gioman** [comment] 2019-11-29 11:42
Duplicate of https://github.com/qgis/QGIS/issues/33014

**Closed by gioman** 2019-11-29 11:42 UTC
Labels: Bug
