### ISSUE TITLE
Cannot open dxf in AutoCAD when converting shapefile to dxf in QGIS

### ISSUE THREAD

**Issue by thangqd** [qgis/QGIS#34676] opened 2020-02-26 03:17 UTC
Cannot open dxf file in AutoCAD (ver 2019) after save as shapefile to dxf in QGIS (ver 3.xx). However,  open this dxf file in QGIS is OK
![image](https://user-images.githubusercontent.com/1776420/75308340-ca38ce00-5880-11ea-9f03-4c71fd016180.png)

**Comment by lbartoletti** [comment] 2020-02-26 08:04
I confirm too with QGIS 3.10.3 / GDAL 3.0.4 on windows and AutoCAD Map 2020.

I close this ticket since it's a duplicate of #30273 You can follow discussion also on the GDAL ticket OSGeo/gdal#1213

**Closed by lbartoletti** 2020-02-26 08:04 UTC
Labels: Bug

**Comment by gioman** [comment] 2020-02-26 16:38
why this was closed?

**Comment by lbartoletti** [comment] 2020-02-26 16:51
it's a duplicate, and an upstream issue like https://github.com/qgis/QGIS/issues/30273#issuecomment-568174124

**Comment by AlisterH** [comment] 2020-03-29 20:02
Note this is fixed upstream and involved only changes to header.dxf and trailer.dxf
These files can be updated even without a new version of gdal; it would be good to do this in e.g. the Windows package.
