### ISSUE TITLE
copy coordinate copies coordinates in the wrong order

### ISSUE THREAD

**Issue by alansaviolobo** [qgis/QGIS#47441] opened 2022-02-19 07:09 UTC
### What is the bug or the crash?

When you right click to *copy coordinate* in any CRS, the coordinates are mentioned in the reverse order.
In this case instead of listing them as 73.987616,15.414124, they are listed as 15.414124, 73.987616
![copy coordinate](https://user-images.githubusercontent.com/1202289/154790800-c8a154f9-a703-4fb8-adc5-0272a39f6293.png)
.

The result is that if I paste these in say a plugin like Lat Lon Tools to go to the same coordinate, I am directed somewhere else completely different.

### Steps to reproduce the issue

in any project, right click to copy coordinates

### Versions

QGIS version | 3.16.3-Hannover | QGIS code revision | 94ac9f21b8
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.6 LTS
Active python plugins | shapetools; quick_map_services; qfieldsync; searchlayers; latlontools; SuperLabeling; autoSaver; zoomview; FreehandRasterGeoreferencer; processing; MetaSearch; db_manager

</body></html>QGIS version
3.16.3-Hannover
QGIS code revision
[94ac9f21b8](https://github.com/qgis/QGIS/commit/94ac9f21b8)
Compiled against Qt
5.9.5
Running against Qt
5.9.5
Compiled against GDAL/OGR
2.2.3
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.6.2-CAPI-1.10.2
Running against GEOS
3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite
3.22.0
Running against SQLite
3.22.0
PostgreSQL Client Version
10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
SpatiaLite Version
4.3.0a
QWT Version
6.1.3
QScintilla2 Version
2.10.2
PROJ.4 Version
493
OS Version
Ubuntu 18.04.6 LTS
Active python plugins
shapetools; 
quick_map_services; 
qfieldsync; 
searchlayers; 
latlontools; 
SuperLabeling; 
autoSaver; 
zoomview; 
FreehandRasterGeoreferencer; 
processing; 
MetaSearch; 
db_manager

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment] 2022-02-19 21:05
Can't reproduce on master. This might be either CRS dependent, caused by a plugin or already fixed

**Comment by alansaviolobo** [comment] 2022-02-20 03:48
Ill download a fresh copy of qgis and check it out

**Comment by alansaviolobo** [comment] 2022-02-20 06:02
it appears that the latest qgis is not pushed to the bionic repository.

Regards,
Alan Lobo

**Comment by gioman** [comment] 2022-02-20 09:46
> it appears that the latest qgis is not pushed to the bionic repository.

@alansaviolobo 

![image](https://user-images.githubusercontent.com/1951107/154837040-f8cb9c09-b7c7-4643-9c5d-0b076f92f07b.png)

**Comment by alansaviolobo** [comment] 2022-03-07 04:14
it appears that the latest qgis has the same issue. awaiting the screenshots to confirm the same.

**Comment by avinashtavares** [comment] 2022-03-07 10:47
Im using qgis 3.22.3 However, the format is still (long, lat) and not (lat, long)
![image](https://user-images.githubusercontent.com/57594309/157016562-7621ca83-aba3-4acb-aff7-d97ad0ca3193.png)

**Comment by alansaviolobo** [comment] 2022-03-07 11:12
@uclaros can you also please share a screenshot of what you see ?

**Comment by gioman** [comment] 2022-03-07 12:13
> @uclaros can you also please share a screenshot of what you see ?

QGIS shows (in the bottom bar and in right click) lng/lat, and also copies lng/lat, while I think we agree that form most (of software packages, languages, etc,) it should be lat/lng.

**Comment by uclaros** [comment] 2022-03-08 08:28
The coordinates widget below the canvas clearly states *lon, lat* order.
https://github.com/qgis/QGIS/blob/7f9726cafd79519d5e81fcb96eac4a69d069ef5b/src/app/qgsstatusbarcoordinateswidget.cpp#L63
And that's what I'm getting in the widget, in the right click menu and in the actual copied coordinates.
Is this issue about mixing *lon, lat* and *lan, lon* on different places or is it about using *lon, lat* instead of *lat, lon* altogether? The former would be a bug, but the later is a design choice and would have some impact if it was changed.

**Comment by alansaviolobo** [comment] 2022-03-08 09:38
I guess I am referring to the design choice then. 

When I copy the coordinates, I would expect to paste them anywhere else ( either in QGIS itself or in some other app like google maps or google earth ) and the application to zoom to the same point.
Unfortunately, in all three cases, the app zooms to somewhere in the middle of the ocean.
Then I have to manually change the order before passing them on.

> The coordinates widget below the canvas clearly states _lon, lat_ order.
> 
> https://github.com/qgis/QGIS/blob/7f9726cafd79519d5e81fcb96eac4a69d069ef5b/src/app/qgsstatusbarcoordinateswidget.cpp#L63
> 
> 
> And that's what I'm getting in the widget, in the right click menu and in the actual copied coordinates.
> Is this issue about mixing _lon, lat_ and _lan, lon_ on different places or is it about using _lon, lat_ instead of _lat, lon_ altogether? The former would be a bug, but the later is a design choice and would have some impact if it was changed.

**Comment by uclaros** [comment] 2022-03-08 09:46
> When I copy the coordinates, I would expect to paste them anywhere else ( either in QGIS itself or in some other app like google maps or google earth ) and the application to zoom to the same point.
> Unfortunately, in all three cases, the app zooms to somewhere in the middle of the ocean.

This should not be happening within QGIS, as both the coordinates widget and the `goto` locator accept coords in *lon, lat* format. Where are you pasting the coords in QGIS and it does not work as expected?

**Comment by gioman** [comment] 2022-03-08 09:52
> Where are you pasting the coords in QGIS and it does not work as expected?

@uclaros I think that within the realm of QGIS native tools it works ok, It does not with many external ones and plugins, like for example google earth and lat/lon tools plugin (even in its name it suggest that it needs coord in lat/lon) and probably many more.

**Comment by alansaviolobo** [comment] 2022-03-08 09:55
I was using this QGIS plugin call *lat lon tools *and I ran into this issue
there.
But now that you mentioned it, I tried the *go *keywork in the QGIS box and
it seems to work correctely there.


Regards,
Alan Lobo

**Comment by uclaros** [comment] 2022-03-08 09:59
So there's no problem withing QGIS itself I guess.
FYI, you can change the *lon, lat* order in this plugin's settings too!

**Comment by uclaros** [comment] 2022-03-08 12:15
> @uclaros I think that within the realm of QGIS native tools it works ok, It does not with many external ones and plugins, like for example google earth and lat/lon tools plugin (even in its name it suggest that it needs coord in lat/lon) and probably many more.

Sorry @gioman, I completely missed your reply :)
It seems there is already a feature request for customizable *lon, lat* order, #30672

**Comment by gioman** [comment] 2022-03-08 12:16
@uclaros closing this then.

**Closed by gioman** 2022-03-08 12:16 UTC
Labels: Feedback, Map Tools, Bug
