### ISSUE TITLE
QGIS 3.22 is crashing after installation on windows 11

### ISSUE THREAD

**Issue by lqpeter** [qgis/QGIS#49844] opened 2022-08-19 04:40 UTC
### What is the bug or the crash?

Crash ID: [62c06df51ba84c32376002e25009cb4640285a25](https://github.com/qgis/QGIS/search?q=62c06df51ba84c32376002e25009cb4640285a25&type=Issues)

Stack Trace

QNetworkAccessManager::cookieJar :
QgsNetworkAccessManager::setupDefaultProxyAndCache :
QgsNetworkAccessManager::instance :
QgsNetworkContentFetcher::fetchContent :
QgsNetworkContentFetcherTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.10-Bia?owie?a
QGIS code revision: 6a63fd37
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

1. Installation;
2. Start new version
3. Crash is happening with serveral popups with error messages
![afbeelding](https://user-images.githubusercontent.com/30320504/185544054-ce82b044-394d-4757-b50d-898aa0cbdedb.png)

### Versions

QGIS Version: 3.22.10-Bia?owie?a

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nyalldawson** [comment] 2023-10-03 21:43
Duplicate of https://github.com/qgis/QGIS/issues/51581

**Closed by nyalldawson** 2023-10-03 21:43 UTC
Labels: Bug, Crash/Data Corruption, Windows
