### ISSUE TITLE
QGIS reports : Layer creation failed failed to create name.shp: Permission Failed on any file name, possible new feature added '...' menu 11-02-20

### ISSUE THREAD

**Issue by MPN-stack** [qgis/QGIS#34430] opened 2020-02-12 11:18 UTC
**Describe the bug**

**How to Reproduce**
Try to create any new name shape file seems to cause this same error . everything was ok yesterday: Here is the screen shot
![79177c387bfeafa14d7f4f780ebdf7b7](https://user-images.githubusercontent.com/54211372/74330253-90c77500-4d4e-11ea-85d5-c016524a108a.png)

**QGIS and OS versions**

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
aderyn; 
agknow_qgis; 
floodrisk2; 
ImageServerConnector; 
latlontools; 
LecoS; 
qgis_resource_sharing; 
rivergis; 
VectorBender; 
ZoomToPostcode; 
MetaSearch; 
processing

**Additional context**

**Comment by Gustry** [comment] 2020-02-12 11:23
Duplicate of https://github.com/qgis/QGIS/issues/32801

> Use the 3 dots next to it. This field is not a file name input, it's a file path that you must write. Using the 3 dots will highly solve your problem.

You are trying to write to the root of your hard drive, where you don't have write access.

**Comment by MPN-stack** [comment] 2020-02-12 11:33
HI, @Gustry 

I have searched for these files they do not exist on my computer . Placing three dots before made no difference same error persisted when it worked yesterday without three dots. even different file names do give the same error @Gustry do I understand that from today this is now different and different from yesterday I have to place a full path in the shape file name ?

Why has this suddenly changed has the file path changed when it has not been changed?

**Comment by Gustry** [comment] 2020-02-12 11:48
My advice is to **always** use the 3 dots button, never write in this text input.

So could you create your file? Did it work?

**Comment by MPN-stack** [comment] 2020-02-12 11:54
@Gustry Yes created the file with the directory set to documents I note there has been changes in my system preferences even my export filter has been changed to GEOTif when it was a JSON Text export
![37fca894f69c65c5640054116eced4fe](https://user-images.githubusercontent.com/54211372/74332633-65935480-4d53-11ea-88c3-f380823a1175.png)
This export optionGSON Text  has it seemed been removed or renamed. tsk!


Please rename this thread to preferences being changed unknown from yesterday.

**Comment by MPN-stack** [comment] 2020-02-12 11:57
You should note this export option has just returned.
![340f075deec26b13845419a7ef36929d](https://user-images.githubusercontent.com/54211372/74332929-1ac60c80-4d54-11ea-823c-ac730664d1ed.png)

**Comment by gioman** [comment] 2020-02-12 12:27
@MPN-stack so... the original description is about not being able to save a shapefile, while the screenshots posted are not about it. 

In the fist is the dialog to save a raster, where in the "file name" space you have filled just the output name > it won't work, you MUST click the "...", choose a path where you have write permissions and choose a output file name.

In the second is the "save vector" dialog, where all seems ok (given that the path in "file name" is correct and you have write permissions in that location) > did it worked?

**Comment by MPN-stack** [comment] 2020-02-12 18:46
This was added yesterday @gioman  so before this there was no need to with more than 200 features added to QGIS since last year without this button '...'  it used to save directly to Documents . Folder . Now I note some of my shape files are located C:\OSGeo4W64\bin . I am unsure why they are there as they have not been saved their consisting of .shp files .prj files and .aux files part of this data-set. Is it safe to move them and delete them from here **?** As I should not think they should be here**?** The Export routine to be fair to create this JSON (text) export did originally require a directory name with a '...' button. But as of yesterday It seems this was added to shape file creation with no warning. Can you please produce a change log, which i understand is usual practice **?**

Thanks for looking. QGIS is great please use it and support it.

**Comment by gioman** [comment] 2020-02-12 18:59
@MPN-stack let's put it this way: you *must* click on the "..." and select a proper path where to save your vector/raster. In my experience that dialog *does not* remember reliably the last used location/path. I'm not saying it should not, but for that I'm pretty sure there is already a ticket open with a feature request.

**Closed by gioman** 2020-02-12 18:59 UTC
Labels: Bug, Feedback

**Comment by MPN-stack** [comment] 2020-02-12 19:20
I was hoping there would be a preference feature to set a stored path which is usual in apps.  Please answer my questions fully above thank you

**Comment by MPN-stack** [comment] 2020-02-12 19:23
@Gustry @misto @gvellut @jomue @gioman  seems not to have answered my points and just closed the thread is this an attempt to not provide information on your changes to your system ?

**Comment by gioman** [comment] 2020-02-12 19:25
> your changes to your system

There were no changes (in how that dialog works).

**Comment by MPN-stack** [comment] 2020-02-12 19:34
You haven't answered my questions above:
his new feature '...' button on create shape window appeared to be added yesterday @gioman so before this there was no need to with more than 200 features added to QGIS since last year without this button '...' it used to save directly to Documents . Folder . Now I note some of my shape files are located C:\OSGeo4W64\bin . I am unsure why they are there as they have not been saved their consisting of .shp files .prj files and .aux files part of this data-set. Is it safe to move them and delete them from here ? As I should not think they should be here**?** The Export routine to be fair to create this JSON (text) export did originally require a directory name with a '...' button. But as of yesterday It seems this was added to shape file creation with no warning. Can you please produce a change log, which i understand is usual practice ?


**To Simplify fr you**
1)  I note some of my shape files are located C:\OSGeo4W64\bin . I am unsure why they are there as they have not been saved their consisting of .shp files .prj files and .aux files part of this data-set. Is it safe to move them and delete them from here ?  As I should not think they should be here**?**  I need to know if they can be deleted ?
2) The Export routine to be fair to create this JSON (text) export did originally require a directory name with a '...' button. But as of yesterday It seems this was added to shape file creation with no warning. 
3) Can you please produce a change log, which i understand is usual practice ?

Regards
A QGIS USER

**Comment by Gustry** [comment] 2020-02-12 19:41
> This new feature '...'   button on create shape window appeared to be added yesterday

It has been there for years, like QGIS 2.8 **minimum**, look at the screenshot : https://docs.qgis.org/2.8/en/docs/training_manual/vector_analysis/reproject_transform.html#moderate-fa-saving-a-dataset-to-another-crs It was before the `Browse` button in QGIS2.
