### ISSUE TITLE
PostGIS layers with type of GEOMETRY missing in QGIS browser and PostgreSQL Data Source Manager

### ISSUE THREAD

**Issue by palmerj** [qgis/QGIS#32053] opened 2019-09-29 09:23 UTC
- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
PostGIS layers with a type of GEOMETRY, in which the first 100 rows contain null geometries, are not showing in the QGIS browser. This is even when the Use Estimated Metadata option is NOT checked for the connection details.

**How to Reproduce**

1. Create a table in the PostGIS database:

```sql
DROP TABLE IF EXISTS public.foo;

CREATE TABLE public.foo(
   id INTEGER PRIMARY KEY NOT NULL,
   shape GEOMETRY(GEOMETRY, 4326)
);

INSERT INTO public.foo(id, shape)
SELECT g.id, NULL
FROM generate_series(1, 100) AS g (id);

INSERT INTO public.foo(id, shape)
SELECT g.id,'SRID=4326;MULTIPOLYGON(((170 -45, 171 -45,  171 -46, 170 -45 )))'
FROM generate_series(101, 200) AS g (id);

ANALYSE public.foo;
```

2. Establish a new PostGIS connection to the database in the QGIS Browser, by right clicking on the PostGIS node. Do not set any of the checkbox settings

3. Connect to the server, and expand the public schema. The table public.foo does not show.

**QGIS and OS versions**

QGIS version | 3.8.2-Zanzibar | QGIS code revision | 4470baa1a3
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14) |   |  

**Additional context**

I think the issue is because the tables geometry columns without a declared geometry type, always query the first 100 rows of the table to try and determine the geometry type.  See https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresdataitems.cpp#L419. This code should at least respect the Use Estimated Metadata option in the connection info. 

Should probably review this usage as well https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresproviderconnection.cpp#L362

**Comment by palmerj** [comment] 2019-09-29 10:01
Maybe an option if the geometry still can not be resolved after scanning the first 100 rows when using the use estimated metadata option is to show a node browser entry with a ? mark like in the DBmanager. The behaviour from there might need more thought. It's really poor UX to show nothing.

**Comment by jgrocha** [comment] 2019-10-07 23:39
The last option is to provide a dialogue for the user.

@m-kuhn made a very nice PR to create an advanced dialogue to add layers, for generic geometry types. But he just did it for the DB Manager.

@strk Can you take a look at this PR and check if this can be ported to the browser?

**Comment by palmerj** [comment] 2019-10-08 00:59
@jgrocha. sounds great. We should really be trying to fix browser first and then roll that out to other parts of the app.

**Comment by strk** [comment] 2019-10-10 08:44
I would make estimation only take in consideration not-null geometries. This would mean a full scan for tables having ONLY null geometries. How would you feel about such approach ?

**Comment by strk** [comment] 2019-10-10 08:45
Also, would still NOT show tables with all-null geometries I guess

**Comment by strk** [comment] 2019-10-10 10:31
PR #32188 uses the not-null approach.

**Comment by palmerj** [comment] 2019-10-10 12:22
> I would make estimation only take in consideration not-null geometries. This would mean a full scan for tables having ONLY null geometries. How would you feel about such approach ?

I'm ok with this, but after this scan we still can't find a specific type, I think the table should show in the browser with a question mark icon for the user to override and set the type via an advanced dialogue (something like PR #32125).

I also think the browser code should use the Use Estimated Metadata option connection options, rather than alway use `true`.

**Comment by strk** [comment] 2019-10-10 13:32
I agree about honouring the "useEstimatedMetadata" option. Pushed a commit to do that in PR #32053 (maybe it should be in its own PR instead)

**Comment by palmerj** [comment] 2019-10-11 09:58
It's been noted in #32188 that empty tables with a typeless geometry column not showing up in the browser as well

**Comment by strk** [comment] 2019-10-30 09:09
@m-kuhn 's  pull request #32125 was merged, so next step here would be to see how to backport that new feature.

**Comment by strk** [comment] 2020-11-03 12:06
As of current master (47a08a4445b4c46483d03d68e5443081bae5c92a) I cannot reproduce the issue.
Can you, @palmerj ?

**Comment by jgrocha** [comment] 2020-11-03 14:16
Tested here, with current master. The table `foo` is displayed in the browser.

Also works pretty well if other geometry type is used:
```
INSERT INTO public.foo(id, shape)
SELECT g.id, ST_SetSRID(ST_MakePoint(-8, 41),4326)
FROM generate_series(201, 300) AS g (id);
```
![foo](https://user-images.githubusercontent.com/163681/97995839-f547ca00-1dde-11eb-9aeb-764173d5d84a.png)

**Comment by gioman** [comment] 2020-12-21 16:05
Closing for lack of further feedback.

**Closed by gioman** 2020-12-21 16:05 UTC
Labels: Bug, Feedback

**Comment by kannes** [comment] 2023-07-28 13:14
In 3.28 and 3.32 the table created by the code in the first post does NOT show up in the browser for me. Can someone else confirm this?

**Comment by kannes** [comment] 2023-07-28 13:31
Ah, they _do_ show up if the "Don't resolve type of unrestricted columns (GEOMETRY)" option of the connection is _unchecked_ like [@strk also discovered above](https://github.com/qgis/QGIS/issues/32053#issuecomment-540492308).

I have no idea what the intended behaviour should be and if this is how it should work or if it is a bug.
This behaviour has caused confusion with several independent people I have talked too.

As a user I would expect the tables not to be hidden regardless of the "resolve type" option but, if they are special, that QGIS would either present a dialog to choose a geometry type, allow to load them as non-geometry tables or just say "nope, can't load this".

Feature request time or really a bug? :)

PS: When you change this option you seem to have to restart QGIS for the change to be used. Refreshing the browser did not do anything for me.
