### ISSUE TITLE
Protocol Vector data is NOT being requested/refreshed when using "Refresh layer at interval (seconds)"

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#39830] opened 2020-11-06 09:47 UTC
Using "Refresh layer at interval (seconds)" in the layerproperties, does NOT actually retrieve the data. Or at least not for a http service layer.
NOTE: if you use view/refresh F5 the data in a geojson layer IS refreshed..

See also:
https://lists.osgeo.org/pipermail/qgis-developer/2020-April/060938.html
and more recent
https://lists.osgeo.org/pipermail/qgis-user/2020-November/046997.html

I created a geojson service for testing: https://duif.net/geotest/points.geojson it will create ONE random point on the world for every request

This QGIS project contains a world-layer (inbuild) and two layers, both pointing to my test service:
[refreshgeojson.zip](https://github.com/qgis/QGIS/files/5500438/refreshgeojson.zip)

Loading this layer (and hitting F5 to make the layer asynchroon reload the data) would show (something like this):

![Screenshot-20201106104514-912x416](https://user-images.githubusercontent.com/731673/98351580-2ca3ba00-201d-11eb-9615-28fe72701857.png)

In this project the 2 point layers are being refreshed every 3 seconds (and mapcanvas refresh debugging is ON).
As you can see the points do NOT change.
IF you hit F5 they do.

(another observation is that you see that the styles seems to swap between those two layers.... I will create another issue for that #39831)

**Comment by rduivenvoorde** [comment] 2020-11-06 10:06
Important observation:

IF F5 is working, depends on if you opened the geojson url as a File or as a Protocol in the Add Vector dialog. Both work lo load the data but only the 'File'-loaded one actually refreshes the data by going to the web again (I can check in my apache logs).

If you want the little flask python application yourself, let me know.

**Comment by gioman** [comment] 2020-11-06 12:15
There was an identical report on the old tracker that now I can't find on the new one. Just to leave here a note that when this is fixed we must hunt the other report and also close it.

**Comment by Pedro-Murteira** [comment] 2022-01-27 15:00
There is still something going on here. If the option "Refresh layer at interval" is checked, the points only change postition between each other, but if the layers are refreshed with F5, they change positions randomly (I suppose this is the expected behaviour), however, they go right back to changing positions with each other after that. (QGIS 3.22.3)

**Comment by Minkowski2016** [comment] 2022-07-16 17:45
Same problem here but I founded that after adding a 3D Map, the refreshing works. It is not very smooth and the 3D view is always flickering but is better than presing F5 for ever and ever.

**Comment by PedroVenancio** [comment] 2023-07-18 16:10
This is still true in QGIS 3.28.8.

Here is a sample project with: 
[Sample_Refresh_Layer_At_Interval.zip](https://github.com/qgis/QGIS/files/12083358/Sample_Refresh_Layer_At_Interval.zip)

- a WMS layer;
- a WFS layer;
- an ArcGIS REST layer loaded in vector format (f=json);
- an ArcGIS REST layer loaded in raster format (f=image)

All of them have Refresh layer at interval set to 15 seconds:

![imagem](https://github.com/qgis/QGIS/assets/1331581/22a7ee28-085d-496c-82d2-afaa4f40350b)

However, only the raster ones are being effectively refreshed, as you can see in Dev Tools:

![imagem](https://github.com/qgis/QGIS/assets/1331581/b3f0eb5b-ee7e-4e15-85d9-a9c5164bbf52)

**Comment by jonnyforestGIS** [comment] 2023-07-18 23:13
Hi, 
I can confirm this behaviour in QGIS 3.28.8 as well in Windows 10 Pro.

I did a test with the following script using the layers of @PedroVenancio and works:

```python
layer = QgsProject.instance().mapLayersByName('Ocorrencias')[0]
layer.reload()
layer.triggerRepaint()
```

But on the other hand, if I use the checkbox the layer doesn't refresh.

Another test that I did was using the following script but without success:

```python
from qgis.PyQt.QtCore import QSettings
QSettings().setValue("/qgis/map_update_interval", 150)
# For set Refresh layer at interval (seconds) using PyQgis you need:

# Get layer by name
layer = QgsProject.instance().mapLayersByName('pipelines')[0]

# Enabled auto refresh
layer.setAutoRefreshEnabled(True)

# Set seconds (5 seconds)
layer.setAutoRefreshInterval(5000)
```

Source:

[https://gis.stackexchange.com/questions/327132/set-layer-rendering-refresh-layer-at-interval-seconds-using-pyqgis-from-pyth](https://gis.stackexchange.com/questions/327132/set-layer-rendering-refresh-layer-at-interval-seconds-using-pyqgis-from-pyth)

[https://api.qgis.org/api/classQgsMapLayer.html#aa709dde27b7cc2b0c7507bd7b3eecafb](https://api.qgis.org/api/classQgsMapLayer.html#aa709dde27b7cc2b0c7507bd7b3eecafb)

**Comment by PedroVenancio** [comment] 2023-08-11 13:02
@rduivenvoorde Do you still confirm this issue? It seems an important one, since the feature does not work at all for vector data.

**Comment by rduivenvoorde** [comment] 2023-08-16 10:32
Yes, same behaviour: 'refresh' only seems to re-render, not fetching data again  https://github.com/qgis/QGIS/issues/39831 also still valid

**Comment by nyalldawson** [comment] 2023-08-16 19:49
> or it was not intended by this PR?

It wasn't the original use case -- that was for redrawing the layer only, and was designed to be fast so that it would be possible to animate layers. 

We could extend this option with a choice of "redraw"/"refresh", where refresh would do a full refresh and clear local cache etc too

**Closed** 2023-08-29 23:43 UTC
Labels: Data Provider, Bug, Vectors
