### ISSUE TITLE
crash importing .laz files

### ISSUE THREAD

**Issue by twest820** [qgis/QGIS#50387] opened 2022-09-28 15:02 UTC
### What is the bug or the crash?

**Crash ID**: [d8c04cf82e25f1d7af8ffbfc76e2fc8f79b4d752](https://github.com/qgis/QGIS/search?q=d8c04cf82e25f1d7af8ffbfc76e2fc8f79b4d752&type=Issues)

**Stack Trace**
<pre>
QObject::qt_static_metacall :
QgsTask::processSubTasksForCompletion :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

### Steps to reproduce the issue

Drop a small group of 241 .laz tiles in a group (older, lower resolution flight; only 14.5 GB). Also occurs with Layer -> Add Layer -> Add Point Cloud Layer....

Given the limited information available in the stack trace the most effective response might be to expand the information reported.

### Versions

**QGIS Info**
QGIS Version: 3.22.9-Bialowieza
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

It seems likely indexing of points in a particular tile is triggering this crash. However, there's nothing in the crash report indicating which tile and, once QGIS is restarted, point processing doesn't resume on the added tiles. Depending on which tile it is and whether that's one of the tiles I need to process I may eventually have more specifics.

**Comment by uclaros** [comment] 2022-09-29 11:09
It would be really nice if you could pin point and share the offending .laz file by bisecting the dropped files

**Comment by twest820** [comment] 2022-10-14 11:12
Bump to clear the feedback and stale tag so this doesn't autoclose instead of staying open to track improved crash logging to enable QGIS error diagnosis. The tiles inventory fine with LAStools.

**Comment by uclaros** [comment] 2022-10-14 11:44
The feedback tag is still there, as the laz file that causes the crash would be needed for debugging!

After the crash, you can see which files were successfully indexed by the existence of `filename.copc.laz` files or `ept_filename` folders depending on qgis version.

**Comment by twest820** [comment] 2022-10-29 10:39
Bump to clear stale marking. Can someone turn off the bot? It appears it'll take some time for someone familiar with QGIS's error handling systems to get to this since the issue hasn't yet been assigned to anyone.

**Comment by uclaros** [comment] 2022-10-29 19:13
Hey @twest820 , as I mentioned before, this issue gets marked as stale because it has the *awaiting feedback* tag. That's because your feedback is needed in order for someone to replicate the bug, pinpoint what's causing it and come up with a fix.
If you don't want to share the data that's causing the crash it's perfectly understandable. Though the bug report is not of much use if nobody can replicate it, hence the bot will try to close it!

As for error reporting, you don't get to choose what's included in a stack trace. If you want more info reported then you can try using a debug build of qgis which logs its output to stdout.

**Comment by twest820** [comment] 2022-10-30 00:32
Thanks, yes, I understand how the bot works. I have no new feedback since, as previously noted, 1) it's unclear what feedback from me is needed to modify regular QGIS builds to generate actionable crash reports and 2) other tools besides QGIS completed the processing without issue weeks ago. I'd be happy to clear the feedback tag but lack permissions to do so.

While I can help a little bit by spending a few minutes doing what QGIS encourages for error reporting I'm maxed out contributing to multiple other open source projects. Don't have the investigative freeboard to be rewinding projects, installing special builds, digging through logs, trying different input combinations, and all that. Hence some of the apparent value in improving crash reports from regular builds so that they're more readily actionable.

The data's public, though―ftp://lidar.engr.oregonstate.edu/OREGON%20LIDAR%20CONSORTIUM%20PROJECT%20DATA/OLC%20SOUTH%20COAST%202009/POINTS/ (doesn't seem like github markdown can generate ftp urls, so copy/pasting the link may have to do).

**Comment by uclaros** [comment] 2022-10-31 07:18
The feedback needed is *the exact steps to replicate the bug*. We're slowly getting there, but the folder you linked has more than 5000 files weighing more than 300GB. Would any 214 of them do?

**Comment by twest820** [comment] 2022-11-01 03:36
I don't know since, as previously noted, there's no evidence any of the tiles are problematic. I'm also unaware of any evidence which would motivate 214 as a specific choice.

**Comment by twest820** [comment] 2022-11-16 04:21
Routine bump to clear stale tag.

**Comment by uclaros** [comment] 2022-11-16 06:56
@twest820 thanks for reporting this, but the bug is not reproducible with your given instructions. I'm closing this as it was either some local issue or it has already been fixed.

**Closed by uclaros** 2022-11-16 06:56 UTC
Labels: Feedback, Bug, Point Clouds

**Comment by twest820** [comment] 2022-11-16 13:35
If it's been fixed shouldn't a diagnostics improvement PR be attached to this issue?

**Comment by uclaros** [comment] 2022-11-16 13:51
This issue was about a _bug_ causing a _crash_, which can't be replicated so I closed this.
If you have some improvement in mind, feel free to open a _Feature Request_ describing it or a PR implementing it.

**Comment by twest820** [comment] 2022-11-16 14:01
So all 5000 tiles imported without issue for you?

**Comment by uclaros** [comment] 2022-11-16 14:39
I tested with roughly 5% of the files and had no issues. Feel free to test them all using the latest QGIS version if you want though!

**Comment by twest820** [comment] 2022-11-16 16:58
Interesting, thanks! I'll see what happens next time I need to inventory a flight.
