### ISSUE TITLE
[Aggregates] Allow majority and minority statistics on non-numeric fields

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27230] opened 2018-07-12 09:09 UTC
Author Name: **Harrissou Santanna** (@DelazJ)
Original Redmine Issue: [19402](https://issues.qgis.org/issues/19402)

Redmine category:expressions

---
I wonder if it's intentional or if it's a missing feature but currently, there's no way to know the most/less present (aka majority/minority) value in a field if that field is not of numeric type. For example, you may want to know which species is most present in an area but it does not look possible using the majority function if species are not coded as numeric.
This concerns the statistical panel as well as expression functions or aggregate algorithm.

**Comment by PedroVenancio** [comment] 2019-12-09 14:04
This issue is related to https://github.com/qgis/QGIS/issues/27271

I also think that majority/minority aggregators should work with string fields. Tested in QGIS 3.10.1, and majority/minority just work for numeric fields.

**Comment by suricactus** [comment] 2020-03-09 04:59
The problem is with the aggregate expression in general, this is not working:
```
 aggregate( @layer_id , 'majority',  "string_column" )
```
Both on ogr and postgis layers.

**Comment by alexbruy** [comment] 2020-08-12 08:44
Fixed in master.

**Closed by alexbruy** 2020-08-12 08:44 UTC
Labels: Expressions, Feature Request
