### ISSUE TITLE
Unable to load server landingpage

### ISSUE THREAD

**Issue by stev-0** [qgis/QGIS#38308] opened 2020-08-16 01:12 UTC
**Describe the bug**
`[{"code":"Internal server error","description":"The API handler returned an error: [json.exception.type_error.305] cannot use operator[] with a string argument with array"}].`
Something around [this line](https://github.com/qgis/QGIS/blob/master/src/server/services/landingpage/qgslandingpagehandlers.cpp#L72) appears to be causing the problem - the variable `info` appears to be an json array rather than a dictionary so an`id` property cannot be assigned, With the [following line](https://github.com/qgis/QGIS/blob/master/src/server/services/landingpage/qgslandingpagehandlers.cpp#L73) commented out the error message no longer appears and there is a response in `index.json`, but no project summaries load, which I believe is a side effect of the json being incorrect as a result of the issue above.

**How to Reproduce**
Start qgis_mapserver, navigate to localhost:8000 in browser, server successfully reads projects in `QGIS_SERVER_PROJECTS_DIRECTORIES` but does not create landing page

**Environment**
Using QGIS 3.15 master 4e795316cd on Ubuntu 20.04

**Comment by elpaso** [comment] 2020-08-17 06:07
Hi Steve, I cannot reproduce the issue and this code path is under CI Tests so I don't really know how it can happen (because `info` is actually an object not an array). I see two options here:

1. C++ compiler different behavior:  which C++ compiler are you using?
2. the error is not generated on line 73 that you indicated, the `projectsData` function internals is where I place my bet, the source of the error is likely generated in line 72 while executing the `projectsData` function

Anyway, can you please test if the following patch solves your issue?

```diff
diff --git a/src/server/services/landingpage/qgslandingpagehandlers.cpp b/src/server/services/landingpage/qgslandingpagehandlers.cpp
index f39f558520..535fc6f90d 100644
--- a/src/server/services/landingpage/qgslandingpagehandlers.cpp
+++ b/src/server/services/landingpage/qgslandingpagehandlers.cpp
@@ -69,9 +69,7 @@ json QgsLandingPageHandler::projectsData() const
   const auto constProjectKeys { availableProjects.keys() };
   for ( const auto &p : constProjectKeys )
   {
-    auto info { QgsLandingPageUtils::projectInfo( availableProjects[ p ] ) };
-    info[ "id" ] = p.toStdString();
-    j.push_back( info );
+    j.push_back( QgsLandingPageUtils::projectInfo( availableProjects[ p ] ) );
   }
   return j;
 }
diff --git a/src/server/services/landingpage/qgslandingpageutils.cpp b/src/server/services/landingpage/qgslandingpageutils.cpp
index 1ce0d1ea60..773cc8a860 100644
--- a/src/server/services/landingpage/qgslandingpageutils.cpp
+++ b/src/server/services/landingpage/qgslandingpageutils.cpp
@@ -176,8 +176,8 @@ json QgsLandingPageUtils::projectInfo( const QString &projectUri )
     return jLinks;
   };
 
-  json info;
-  info[ "id" ] =  QCryptographicHash::hash( projectUri.toUtf8(), QCryptographicHash::Md5 ).toHex();
+  json info = json::object();
+  info[ "id" ] = QCryptographicHash::hash( projectUri.toUtf8(), QCryptographicHash::Md5 ).toHex();
   QgsProject p;
   if ( p.read( projectUri ) )
   {

It would be useful if you could send me a project that I can use to reproduce the issue.

**Comment by stev-0** [comment] 2020-08-17 10:36
It does help, as the original error goes away (as it did with my earlier experiments).

However, then I get a client-side error `TypeError: Cannot read property 'wmsOutputCrsList' of undefined`.

This seems to be because the index.json projects property is an array of arrays and the project count is reporting 1 when there are actually two projects world.qgs and world3.qgs, which is messing up the lookups in the front end. 

The projects are just from the example tutorials, but I have attached them here in case I modified them somehow, along with the resulting index.json.
[qgsfiles.tar.gz](https://github.com/qgis/QGIS/files/5083655/qgsfiles.tar.gz)

incidentally, output from g++ --version
`g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0`. I'm using the ninja build system as described on the readme.

**Comment by elpaso** [comment] 2020-08-17 10:49
I think the issue is with CGG for some unknown reason. I'll see if I can make a test build with that compiler but it will take a while.

Here are some expected response from the tests:
https://github.com/qgis/QGIS/tree/master/tests/testdata/qgis_server/landingpage

Can you please check if there are structure array/hash differences in what you actually get? In particular, `projects` should be an array of objects, not an array of arrays.

You can also try latest master, I just merged the patch above within another PR: https://github.com/qgis/QGIS/pull/38323

**Comment by elpaso** [comment] 2020-08-17 13:33
@stev-0 I've rebuilt with GCC 7 and downloaded your test projects but I cannot still reproduce the issue...

**Comment by elpaso** [comment] 2020-08-17 14:02
@stev-0 wait: I was finally able to reproduce it with GCC... fix is on the way.

**Comment by elpaso** [comment] 2020-08-17 14:18
... and it was the compiler after all.

**Closed** 2020-08-17 22:27 UTC
Labels: Bug, Feedback
