### ISSUE TITLE
QGIS 3.16.13 does not read .prj file when importing shapefiles

### ISSUE THREAD

**Issue by arojas314** [qgis/QGIS#45973] opened 2021-11-10 00:59 UTC
### What is the bug or the crash?

.prj files not being read by the new qgis 3.16.13 standalone install.

No issues with other versions. After complete uninstall and reinstalling, still getting the same issue.

### Steps to reproduce the issue

Import a shapefile, and there will be no associated CRS. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.13-Hannover | QGIS code revision | a8618a94
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.3 | Running against GDAL/OGR | 3.3.3
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.0 | Running against PROJ | Rel. 8.2.0, November 1st, 2021
OS Version | Windows 10 Version 2009
Active python plugins | db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by coefficient1900** [comment] 2021-11-10 04:24
Seems to be the same as issue #45939 .

**Comment by alexbruy** [comment] 2021-11-10 05:48
Looks like a duplicate of #45939

**Comment by alexbruy** [comment] 2021-11-10 05:49
Duplicates #45939

**Closed by alexbruy** 2021-11-10 05:49 UTC
Labels: Bug
