### ISSUE TITLE
Crash When Adding 3D Map View with Point Cloud 

### ISSUE THREAD

**Issue by tz2436** [qgis/QGIS#42928] opened 2021-04-23 13:26 UTC
**Describe the bug**

After loading the ept.json, I tried to create a New 3D Map View, it immediately crashed

<img width="1112" alt="Screen Shot 2021-04-23 at 9 10 24 AM" src="https://user-images.githubusercontent.com/61794189/115876787-bc46f480-a414-11eb-9299-661b97bb5791.png">

**How to Reproduce**

1. Drag in the ept.json
2. Click on 'View' - 'New 3D Map View'
3. Crash

**QGIS and OS versions**

QGIS version | 3.18.1-Zürich | QGIS code revision | 202f1bf7e5
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.2.1 | Running against GDAL/OGR | 3.2.1
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: Release)
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS Mojave (10.14)

**Additional context**

**Comment by roya0045** [comment] 2021-04-23 14:29
Duplicate of #42830

**Comment by roya0045** [comment] 2021-04-23 14:30
Also please provide the full stack trace, not just an image, preferably in the other issue.

**Comment by gioman** [comment] 2021-04-23 16:43
Closing as duplicate.

**Closed by gioman** 2021-04-23 16:43 UTC
Labels: Bug
