### ISSUE TITLE
Crashing when saving project

### ISSUE THREAD

**Issue by sonia-sorbona** [qgis/QGIS#47788] opened 2022-03-15 09:11 UTC
## User Feedback

I open a new project in QGIS, then before doing anything else I just wanna save the project. In the exactly moment the saving path opens, QGIS crashes.

## Report Details

**Crash ID**: [f8c8e03574c105bb01db510659f46fff3fbc4327](https://github.com/qgis/QGIS/search?q=f8c8e03574c105bb01db510659f46fff3fbc4327&type=Issues)

**Stack Trace**
<pre>
RtlSizeHeap :
NS_FaultTolerantHeap::APIHook_RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:878
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1905
CApartmentActivator::CreateInstance actvator.cxx:2169
CProcessActivator::CCICallback actvator.cxx:1637
CProcessActivator::AttemptActivation actvator.cxx:1524
CProcessActivator::ActivateByContext actvator.cxx:1368
CProcessActivator::CreateInstance actvator.cxx:1268
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1905
CClientContextActivator::CreateInstance actvator.cxx:567
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1957
ICoCreateInstanceEx objact.cxx:1959
CComActivator::DoCreateInstance immact.hxx:385
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

### Steps to reproduce the issue

1. open a new project
2. save project
3. QGIS crashes

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment] 2022-03-15 10:14
@sosorbetto Can you try with a fresh profile to see if the crash persists?

**Comment by sosorbetto** [comment] 2022-03-15 10:53
@Pedro-Murteira  Ok. I changed from the default profile to a new profile and now it's working, thank you! Do you please know why this crash was happening?

**Comment by sosorbetto** [comment] 2022-03-15 11:06
@Pedro-Murteira Ok, thank you for the suggestion. I changed from the default profile to e new profile. The first time it works, I can save without crashing, but then if I close the project and open it again it continues crashing. Also if I create new projects from the scratch they crashes anyway. Do you please know what can be the cause?

**Comment by Pedro-Murteira** [comment] 2022-03-15 14:16
@sosorbetto Unfortunately I do not have a solution I can offer you, but we can leave this ticket open to see if someone has some feedback on the matter.

**Comment by sosorbetto** [comment] 2022-03-15 14:27
@Pedro-Murteira Yeah it sounds good! Thank you for your support.

**Comment by nyalldawson** [comment] 2022-05-18 01:59
Duplicate of https://github.com/qgis/QGIS/issues/34880

**Closed by nyalldawson** 2022-05-18 01:59 UTC
Labels: Project, Bug, Crash/Data Corruption
