### ISSUE TITLE
Grid Overlay labels in main window position problems

### ISSUE THREAD

**Issue by chleidersdorff** [qgis/QGIS#44907] opened 2021-09-01 01:39 UTC
### What is the bug or the crash?

When adding the grid overlay in the main window the lables are correctly displayed until you add the offset. When an offset is added all labels are correctly offset into the canvas except for the bottom ones, they are offset out of the canvas. In addition when choosing the annotation direction as "Horizontal and Vertical" the background styling is not synced properly with the label. See image below for example:

![image](https://user-images.githubusercontent.com/52182284/131597182-0e77fcce-1da9-4b6a-8131-7a5e9de37145.png)

### Steps to reproduce the issue

got to view -> add Decoration -> Grid

Choose "Enable Grid" and "Draw Annotation"

Choose annotation direction: "Horizontal and Vertical"
Style the font with "Background"

### Versions

I am on the latest version but this has been a bug for as long as i can remember in QGIS version 3.

QGIS version
3.20.2-Odense
QGIS code revision
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
BulkVectorExport
changeDataSource
DataPlotly
geometry_paster
latlontools
layout_loader
LoadQSS
loadthemall
MapsPrinter
mapswipetool_plugin
mmqgis
poiexport
processing_wbt
qfieldsync
QGIS3-getWKT
qProf
quick_map_services
SelectWithin
slyr_community
spline
SuperLabeling
db_manager
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It seems to get worse / better with different projections. Not sure thi is a major issue but its been bugging me for some time so I though i would document it. I could not see a reference to this issue in the current issues.

**Comment by agiudiceandrea** [comment] 2021-09-01 13:59
> When an offset is added all labels are correctly offset into the canvas except for the bottom ones, they are offset out of the canvas.

Hi @chleidersdorff, I cannot replicate this issue with QGIS 3.20.2. Are you referring to the grid offset? I see in the provided screenshot that the grid offset is set to 0.

> when choosing the annotation direction as "Horizontal and Vertical" the background styling is not synced properly with the label.

I can replicate the issue. The issue does occur for me even if the grid offset is set to 0.

**Comment by chleidersdorff** [comment] 2021-09-02 23:10
Hi @agiudiceandrea sorry should have been more specific, when i am talking about the offset, i am referring to the labelling not the grid, so in the bottom box for annotation there is something call "distance to map frame" which i simply referred to as offset. If you increase this number the bottom labels move out of the map window not into it. See example below:

![image](https://user-images.githubusercontent.com/52182284/131927304-f87464a3-fc49-4c56-8bf2-d2d58fe7b6e0.png)

**Comment by chleidersdorff** [comment] 2021-09-02 23:15
Also @agiudiceandrea Any Annotation direction other than horizontal means the font background fill does not sync with the label. It seems the font background is always offset to the top right of the label when rotated. The font buffer works as intended so i usually use that instead but sometimes it would look better with a box under the label.

**Comment by agiudiceandrea** [comment] 2021-09-03 18:34
Yes, now it's more clear.
I too can reproduce the first issue for the bottom vertical grid labels, setting a non zero "Distance to map frame".
This first issue seems to me a regression, since it didn't occur in QGIS 3.10.

**Comment by agiudiceandrea** [comment] 2021-09-07 10:57
@chleidersdorff could you please check* if the fix provided with https://github.com/qgis/QGIS/pull/44968 does work for you?

* just go to https://github.com/qgis/QGIS/pull/44968/checks?check_run_id=3532396544, download the "QGIS for Windows 64bit" artifact, extract it and run qgis.exe from QGIS-Portable\bin.

**Comment by chleidersdorff** [comment] 2021-09-08 03:28
@agiudiceandrea I have tested it and it seems to work now and you also fixed the background placement :), however the background does seem to need a offset of Y = -2 to center on the label. See screenshots below:

with no Offset:
![image](https://user-images.githubusercontent.com/52182284/132441750-9c827040-55fa-4224-9d50-f7ae0319f677.png)

With -2 Y offset on the background:
![image](https://user-images.githubusercontent.com/52182284/132441819-11872703-b775-443b-86c6-6d7dca8607cd.png)

**Comment by chleidersdorff** [comment] 2021-09-30 00:49
Hi @gioman and @agiudiceandrea Have you seen my feedback on the fix?

**Comment by agiudiceandrea** [comment] 2021-09-30 06:22
@chleidersdorff the issue reported in this bug report is about the incorrect placement of the annotations when "Distance to map frame" is >0 (this is a regression introduced by https://github.com/qgis/QGIS/pull/37133) and the incorrect placement of the annotations background for annotations with vertical direction (this was an issue since the introduction of the same feature https://github.com/qgis/QGIS/pull/37133). These issues only occur for the map Grid Decoration, while don't occur for the layout Grid map item property.
These issue are addressed by my PR https://github.com/qgis/QGIS/pull/44968 not yet merged.

You are now reporting another annotations background placement behaviour which is present in both the map Grid Decoration and the layout Grid map item property, which is independent by my PR, and which could be changed just setting an offset. So I think you should file another issue report.
Consider however that the users could have already set an offset in their layout to change this background placement behaviour, thus modifying this behaviour will subtly "break" their layouts...

**Comment by chleidersdorff** [comment] 2021-10-01 01:12
@agiudiceandrea thanks for the update. You are correct, I figured it was related and why I mentioned it. I have however also got standard workspaces that have this correction in them and would "break" by fixing it. Thanks for your work on the other issues. I will consider if reporting the background separately will be in people's interest before proceeding.

**Closed** 2021-10-06 06:07 UTC
Labels: Feedback, Bug, Decorations
