### ISSUE TITLE
qgis cannot find/identify a polygon feature by clicking a newly created (multi)polygon part

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#54537] opened 2023-09-10 10:07 UTC
### What is the bug or the crash?

in a new polygon shapefile, after adding a feature, subsequently adding a part to this feature and ending the editing session, the newly added part will not be found by either the (mouse) information tool or the (mouse) selection tool.
Before leaving editing mode, these action still work as expected.
First found in Lima, then did fresh install of LTR Firenze to check. Both showed the same unwanted behavior.
A new profile in Firenze did not solve the issue.

### Steps to reproduce the issue

Open  Qgis (3.28.10 LTR or Lima, presumably other versions as well).
`Layer->Create Layer->New Shapefile Layer` (the type of layer, e.g. geopackage rather than shapefile, is probably irrelevant)
Dialog:
choose a (new) shapefile filename, set geometry type to polygon, crs (in my case) to EPSG:28992 (projected), click OK.
Select the layer in TOC and toggle editing.
`Digitizing toolbar -> Add Polygon Feature`. Create a single, simple (e.g. triangular) polygon, ending digitizing with right click. Fill in an unused ID value and click ok.
Select the new feature.
`Advanced Digitizing -> Add part`. Create a simple part outside the (first part of the) feature, ending again with right click.
Now use information tool on the second part. The new feature with both parts will show up correctly.
End editing session, save results.
Try identifying the feature by clicking the second part. This will fail. Try identifying through clicking the first part; this will work, both parts show up as identified.
Try `properties->Source-> update extents`; this will not help.
`Vector->data management tools->create spatial index`: will not help either.
Save project and reload: will not help.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.10-Firenze | QGIS code revision | e2edb9c468
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.10-Firenze
QGIS code revision
[e2edb9c468](https://github.com/qgis/QGIS/commit/e2edb9c468)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
----------------------------------------------
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.2-Lima | QGIS code revision | c0b8833964
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.2-Lima
QGIS code revision
[c0b8833964](https://github.com/qgis/QGIS/commit/c0b8833964)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by janhec** [comment] 2023-09-10 10:44
I also discovered the cause. The additional parts are stored in counter clockwise sequence, irrespective of the order of digitizing.
This means they are regarded as rings (holes) outside a shell. Test with `Geometry tools -> Check Validity` confirms this and
reversing the sequence (used my own shapefile software) resolved the issue.
I am amazed by this basic error.

**Comment by agiudiceandrea** [comment] 2023-09-10 14:01
> Open Qgis (3.28.10 LTR or Lima, presumably other versions as well).
> `Layer->Create Layer->New Shapefile Layer` (the type of layer, e.g. geopackage rather than shapefile, is probably irrelevant)

@janhec thanks for reporting. The layer format is relevant: the issue happens with a Shapefile layer, but not with a GeoPackage layer.

**Comment by janhec** [comment] 2023-09-10 15:35
I'm not sure we've seen the end of this as a shapefile (implementation?) specific error.
I tried this scenario because I did not succeed in adding (polygon) parts in a postgis edit layer and could not find out why;
right clicking just made the sketch go away.
I hoped I found the cause with trying a simple case (hence shapefile), but perhaps not, also because the behavior is different (vanished sketch vs geometry error). I'll try some additional variants soon (but not right now).

**Comment by janhec** [comment] 2023-09-11 09:18
I'm not sure we've seen the end of this as a shapefile (implementation?) specific error.
I tried this scenario because I did not succeed in adding (polygon) parts in a postgis edit layer and could not find out why;
right clicking just made the sketch go away.
I hoped I found the cause with trying a simple case (hence shapefile), but perhaps not, also because the behavior is different (vanished sketch vs geometry error). I'll try some additional variants soon (but not right now).

**Comment by janhec** [comment] 2023-09-11 09:32
I've checked out adding part with a postgis table. The table has a primary key.
I found the same problem (Warning/error as with @mblesius ). In Firenze (LTR), the operation succeeded.
So it appears that 2 problems exist here.
@agiudiceandrea 
Perhaps, just perhaps, the geopackage driver has a check on the orientation of rings outside the shell, but that is no more than a guess. It is not clear to me that one should want to do such corrections, as at the driver level one cannot be confident about the intention of the ring in question, only about the (non)presence of an error.
Also, but correct me if I'm wrong, I would expect that geo-operations are done within a single context, rather than driver specific.
Reproduction:
Since afaik you can't start a new postgis layer in QGis, I can, if desired, provide my sample as a SQL dump.

**Comment by janhec** [comment] 2023-09-12 10:06
[woonplaats_selectie.zip](https://github.com/qgis/QGIS/files/12585157/woonplaats_selectie.zip)
I added data in sql (postgresql), geopackage and spatialite. All have this issue that adding a part will fail.
The intention was/is to fill the uncovered but enclosed spaces with parts of one of the 3 features (i.c. named 'Leerbroek'),
but there is no indication that the issue is particular to this dataset.
Should I report this as a separate bug not  belonging in the shapefile case with bad geometry?

**Comment by agiudiceandrea** [comment] 2023-09-12 10:43
The tests made on Windows by show that:

- QGIS 3.32 and QGIS dev master branch (GDAL 3.7):

  - with e.g. "Memory" or "GeoPackage" layers of type `MultiPolygon` and `MultiLineString`: the "Add part" tool doesn't allow to add parts and throws the error: "Add part : New part's geometry is empty or invalid."
  - with "ESRI Shapefile" layers of type `Polygon` (which is actually a `MultiPolygon` type): the "Add part" tool allows to add parts but such parts are added as (external) interior rings instead of parts

- QGIS 3.28.10 and QGIS 3.30.3 (GDAL 3.7):
  - with e.g. "Memory" and "GeoPackage" layers of type `MultiPolygon` and `MultiLineString`: no issues
  - with "ESRI Shapefile" layer of type `Polygon`: the "Add part" tool adds the parts as (external) interior rings instead of parts
 
- QGIS 3.28.5 and QGIS 3.30.2 (GDAL 3.6):
  - with e.g. "Memory" and "GeoPackage" layers of type `MultiPolygon` and `MultiLineString`: no issues
  - with "ESRI Shapefile" layer of type `Polygon`: no issues
 
- QGIS 3.22 (GDAL 3.5):
  - with e.g. "Memory" and "GeoPackage" layers of type `MultiPolygon` and `MultiLineString`: no issues
  - with "ESRI Shapefile" layer of type `Polygon`: no issues

**Comment by agiudiceandrea** [comment] 2023-09-26 21:29
The "Add part : New part's geometry is empty or invalid." issue which occurs with QGIS >= 3.32 has been fixed with PR https://github.com/qgis/QGIS/pull/54611.

**Comment by nirvn** [comment] 2023-09-27 02:08
Reported upstream: https://github.com/OSGeo/gdal/issues/8481

**Comment by rouault** [comment] 2023-09-27 13:05
The issue is more in the QGIS OGR provider. I'm on it

**Closed** 2023-09-29 01:07 UTC
Labels: Data Provider, Regression, High Priority, Bug, Digitizing
