### ISSUE TITLE
QGIS 3.14 Raster Histogram discrepency

### ISSUE THREAD

**Issue by joeyfranck56** [qgis/QGIS#38649] opened 2020-09-08 17:29 UTC
I've found that the raster histogram produced in QGIS 3.14 is not the same as older versions of QGIS.  The frequency of values seems to be off for frequencies over 1000.   I thought this was an issue with the raster, but loaded the same raster into QGIS 3.4.5 and the histogram produced is much different.

QGIS 3.4.5
![raster_QGIS345](https://user-images.githubusercontent.com/48452875/92508098-a9f1b080-f1cd-11ea-9d77-a8939efb9c80.PNG)

QGIS 3.14.15
![raster_QGIS31415](https://user-images.githubusercontent.com/48452875/92508815-deb23780-f1ce-11ea-9717-5bdf998a96ca.PNG)

**Comment by gioman** [comment] 2020-09-08 17:35
@joeyfranck56 duplicate of https://github.com/qgis/QGIS/issues/38298 ?

**Comment by joeyfranck56** [comment] 2020-09-08 17:48
> @joeyfranck56 duplicate of #38298 ?

It appears to be the same issue, apologies.

**Closed** 2020-09-08 17:57 UTC
Labels: Bug, Feedback
