### ISSUE TITLE
make_line in Virtual Layer Creator results in Field instead of Geometry

### ISSUE THREAD

**Issue by BW89** [qgis/QGIS#59214] opened 2024-10-25 13:16 UTC
### What is the bug or the crash?

While creating a commuter flow map I discovered a Bug in QGIS 3.38.3 (both on Windows and Linux).
Instead of creating geometry with make_line (no other function tested) in the Virtual Layer Creator a field named make_line(a.geometry,b.geometry) is created, which results in no visible Lines.

![image](https://github.com/user-attachments/assets/d9cdd622-4058-4a07-befd-2eb0d7eff47d)
expected Result, as seen in QGIS 3.34.3, but I have also seen it working in 3.36

![image](https://github.com/user-attachments/assets/e6bda1e6-5a43-4f97-8064-a93df32f0aed)
Result in QGIS 3.38.3: no Lines on the Map, instead a field is added to the attribute Table

Since this worked fine in previous versions of QGIS i am certain that it is a bug.

### Steps to reproduce the issue

1. open Virtual Layer Creator
2. insert commands, that should create lines. for example
`SELECT gem_woh, gem_arb, pend,
       make_line(a.geometry, b.geometry)
FROM pendel_nur_region
JOIN Centroids a ON pendel_nur_region.gem_woh = a.g_id
JOIN Centroids b ON pendel_nur_region.gem_arb = b.g_id
WHERE a.g_id != b.g_id
`
3. add Layer
4. Instead of Lines no Geometry appears

### Versions

3.38.3 on both Windows and Linux

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I tried renaming the field by adding a `as geometry` to the make_line command in the creator, but it did not change

**Comment by nyalldawson** [comment] 2024-10-25 18:59
Duplicate of https://github.com/qgis/QGIS/issues/58644

**Closed by nyalldawson** 2024-10-25 18:59 UTC
Labels: Bug
