### ISSUE TITLE
Field and values list error in field calculator

### ISSUE THREAD

**Issue by MMR100** [qgis/QGIS#34544] opened 2020-02-19 13:14 UTC
Checklist before submitting
- not found in existing issue reports
- tested with a clean new user profile in a new project

Description: 
In the field calculator, in "field and values" tab, when clicking several time on "All unique" or "10 samples", the number of values proposed in the list keeps increasing. 
By clicking on "All unique" and then "10 samples", the list is not updated and remain on "All unique" results.

QGIS Version 3.10.2-A Coruña
OS Windows 7

**Comment by pigreco** [comment] 2020-02-19 13:40
##  I confirm in QGIS 3.10.2-2 OSGeo4W64 win 10

![value](https://user-images.githubusercontent.com/7631137/74839543-b98ad400-5325-11ea-8c15-7639c1bb35d1.gif)

**Comment by obrix** [comment] 2020-02-21 10:04
I confirm the bug is still present in the latest 3.10 release branch. But I cannot reproduce it on master. It might have been fixed.

**Comment by roya0045** [comment] 2020-02-21 14:52
Can someone test on master? I assume that this fix should address this but was maybe not backported? github.com/qgis/QGIS/commit/e73fe50d0af1a17484598e9be1cfc6cd07c21316

**Comment by obrix** [comment] 2020-02-21 15:00
I confirm I can reproduce this bug on release 3.10 branch on Ubuntu 19.10 but not on master branch. It might indeed have been fixed.

**Comment by roya0045** [comment] 2020-02-21 15:28
As this was a feature for the most part I'm not sure if the single line that fixes this should be backported or not. It should be this line only https://github.com/signedav/QGIS/blob/ea912a170c7602f2317303227ca0469ac4ed2426/src/gui/qgsexpressionbuilderwidget.cpp#L505

**Comment by roya0045** [comment] 2020-03-23 21:31
Can someone close this, the fix has been backported. Ty

**Closed** 2020-03-23 21:38 UTC
Labels: Bug
