### ISSUE TITLE
False page format at creation as Geo-PDF

### ISSUE THREAD

**Issue by grafkrako** [qgis/QGIS#37188] opened 2020-06-13 17:04 UTC
**Describe the bug**
I want to create a Geo-PDF in the page format A3 (297 x 420 mm).
The PDF was createt, but in the Adobe Reader the format is not A3 but 1.237,7 x 1750,7 mm. _(see attachment: Test.pdf)_
If I create a Not-Geo-PDF the page format is fine.

**How to Reproduce**
1. Start QGIS
2. Load print layout test.qpt (from attachment)
3. Create a Geo-PDF, additional settings: see attachment: _Settings-Layout.jpg_. The additional setting to Geo-PDF have no bearing)

[Attachments.zip](https://github.com/qgis/QGIS/files/4775032/Attachments.zip)

**QGIS and OS versions**
QGIS 3.12.3 an 3.12.2
Windows 10 (I could reproduce this case in different Windows 10 Versions)
More Informations see in the attachment _Versionsinfo.jpg_

**Comment by nyalldawson** [comment] 2020-06-15 03:08
Duplicate of https://github.com/qgis/QGIS/issues/33465

**Closed by nyalldawson** 2020-06-15 03:08 UTC
Labels: Bug
