### ISSUE TITLE
"Reorder Model Inputs" should also allow to reorder algorithm outputs

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#52767] opened 2023-04-19 07:00 UTC
### Feature description

The processing model designer has an option to "Reorder Model Inputs", which controls the order input parameters are shown in the model gui.
But there seems to be no way to reorder algorithm outputs.  There should be a way.  
And I think it should be in the same gui as the inputs, because sometimes it makes logical sense to show some of the outputs before some of the inputs.  i.e. present things in the same order that the model works - working step by step through the model, first show the inputs of the step and then the outputs of the step, before showing the inputs and outputs of the next step.

### Additional context

See this screenshot - I controlled the order of the r.watershed outputs by initially naming them with a numerical prefix, but if I wanted to make them show up before the outputs of the two r.to.vect steps I can't.
![image](https://user-images.githubusercontent.com/714600/232991728-11635dc6-be03-4acb-ac30-4e0f2c19beed.png)

**Comment by pathmapper** [comment] 2023-04-20 09:27
Maybe duplicate of https://github.com/qgis/QGIS/issues/39412?

**Closed** 2023-04-20 09:37 UTC
Labels: Feature Request, Modeller
