### ISSUE TITLE
Can't copy derived attributes from Identify Results panel

### ISSUE THREAD

**Issue by patrickmaslen** [qgis/QGIS#56816] opened 2024-03-12 03:41 UTC
### What is the bug or the crash?

Derived attributes (e.g. Feature ID, X, Y) cannot be copied from the Identify Results panel in QGIS 3.34.4.  In (e.g.) QGIS 3.22 this could be done.

### Steps to reproduce the issue

1. Add point vector layer (I used a file geodatabase layer)
2. Select that layer in layers panel, select 'identify' tool from toolbar, click on on one of the points in the layer.
3. Go to 'Identify Results' panel, right click on X, click on 'Copy Attribute Value'.
4. Paste into text editor - note that no value appears.

### Versions

QGIS 3.34.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment] 2024-03-12 03:45
Duplicate of https://github.com/qgis/QGIS/issues/55311

**Closed by nyalldawson** 2024-03-12 03:45 UTC
Labels: Bug
