### ISSUE TITLE
Legend Items look pixelized and offset

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#30837] opened 2019-07-20 14:47 UTC
**Describe the bug**

In the layout's legend, some items look pixelized (line patterns, marker parterns. Besides, they also look a bit displaced with the outline. In the following image, on the left, there is a feature in a map, and at the right, the legend.

![image](https://user-images.githubusercontent.com/3607161/61579730-f0cfa300-ab00-11e9-8b32-99dcbdb6dec0.png)

**How to Reproduce**

Create a symbol including:

![image](https://user-images.githubusercontent.com/3607161/61579849-6ee07980-ab02-11e9-87c5-833b076d4d5b.png)

The part of the small offset only happens when I use Outline: Simple line.

If I use a normal fill without fill that no longer happens.

The following project has it all.

https://www.dropbox.com/s/z14u5d9cemmaphw/pixelized_symbol.gpkg?dl=0

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 6749cb3d1f
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version | 11.4 (Ubuntu 11.4-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.2 LTS |   |  

**Additional context**

**Comment by nyalldawson** [comment] 2019-07-20 21:07
Duplicate of https://github.com/qgis/QGIS/issues/16100

**Closed by nyalldawson** 2019-07-20 21:07 UTC
Labels: Bug

**Comment by SrNetoChan** [comment] 2019-07-22 09:59
@nyalldawson Hi!

I think there's a part that is not duplicated. The "Outline: Simple line" seems offset.

![image](https://user-images.githubusercontent.com/3607161/61623739-24304000-ac6f-11e9-84c4-b48f542e9bdd.png)

The above image is the legend of a symbol composed by a Simple fill (red stroke), and an Outline: Simple line (black stroke).

I would expect them to be on top of each other and that the read line is not visible.

This is also visible in the Layers Panel, but not in the map canvas or map outputs.

![image](https://user-images.githubusercontent.com/3607161/61623997-a91b5980-ac6f-11e9-8ccd-52e311b9ddea.png)


 Is this related to the line pattern too?
