### ISSUE TITLE
QGIS's RAM usage while adding layers

### ISSUE THREAD

**Issue by quabes** [qgis/QGIS#32926] opened 2019-11-18 11:11 UTC
Hi there!
I found that QGIS 3.x on Windows has a problem while adding vector layers to the project by Data Source Manager. When I work on my QGIS project (.qgs) it uses about 500MB of ram memory all day long (while editing or adding object on PostGIS layers, there is no problem). But when I try to add some vector or CSV layers, RAM usage get crazy (QGIS uses up to 4GB of RAM memory). But you don't have to add any vector layer - it is enought just to click 'Add vector layer' and press Close (whitout adding anything) and QGIS while rendering map is using more and more RAM memory - after few minutes of moving map there is lack of RAM and QGIS freezes / crashs.
I have checked this on Windows 7 and 10 with fresh QGIS 3.4 - 3.10 and I see it on Ubuntu 18.04 and QGIS 3.8 - just clicking Add ... layer (whitout adding any data) makes QGIS RAM leak, until we close QGIS proces (RAM allocation is still huge after reload project). Maybe it is not visible on small projects (mine is about 5 MB qgs file - many PostGIS layers and raster data like WMS or VRT) but this project on QGIS 2 doesn't have any problems like above. Also if I add vector/raster layers, save them to the project and restart QGIS, everything works fine - it is something wrong with adding layers tool... 
Is there something that you can confirm and find any sollution?
Regards...

**Comment by roya0045** [comment] 2019-11-18 13:04
Out of curiosity, do you have any external plugins that might be active?

**Comment by quabes** [comment] 2019-11-18 13:58
Well I have checked this on clear QGIS 3.4.12 installation and on fresh Windows 10. I will check it on fresh Ubuntu 18.04 but now I see this RAM problem on many my projects... 
I have to check it on simply project whitout labels, symbols based on rules, attributes, ect... 
Is there enyone who can confirm that problem at his projects??

**Comment by roya0045** [comment] 2019-11-18 14:04
Does this occur on old projects only or new/empty projects too?

**Comment by gioman** [comment] 2019-11-18 14:47
> and on fresh Windows 10

the important bit is that no 3rd party plugins must be installed.

**Comment by quabes** [comment] 2019-11-18 20:35
As I said - I have done clean QGIS 3.4.12 installation (from QGIS-OSGeo4W-3.4.12-1-Setup-x86_64.exe) on a fresh Windows 10 x64. No plugins were installed on that host. I have done quick project with few of my postgis data (tables and views) based on random symbology (unique first, then changed for rule based) with some 'advanced' labels (depending on scale, eg. feature1 || '\n' || feature2) - everything that was working well on QGIS 2. 
And I see the same problem ... Of course QGIS with that simple project at start uses les then 300MB of RAM and it is stable (RAM usage not growing while rendering map), but when I click 'Add vector layer' (without adding anything - just click Close button after that) while rendering (by moving or scale map) RAM usage starts grow. Of course not so fast like on my full projects, but I can get 1GB RAM usage under 1 minute of using map :/
I will check it on Ubuntu 18 and QGIS 3, but I would like to ask if anyone of You see something similar at his projects?
Regards!

**Comment by quabes** [comment] 2019-11-19 08:33
I have checked this on fresh Ubuntu 18.04 and QGIS 3.4.13 with 40 vector layers (postgis tables or views, some of them duplicated but with different filter expression) and couple WMS layers - I get the same result: RAM usage is stable (about 300MB) but when I click 'Add vector layer' (whitout adding any layer - just closing that window) RAM usage starts grow - not so dramatic like on my full project, but still QGIS easylly take 1GB in few minutes, of moving on the map...
The project is standard - random symbology, with some labels and layers visabilyty based on scales. All layers contains about 500 000 objects, but in QGIS 2 it had them more - there is no problem while working with them, untill I click 'Add ... layer' buttons in QGIS 3.
Can You help, please!!??

**Comment by roya0045** [comment] 2019-11-19 12:56
Ok so the data manager might be leaking.

**Comment by quabes** [comment] 2019-11-19 13:48
Is that means that you can see it as well? If yes that means I didn't get crazy (I hope;)

**Comment by roya0045** [comment] 2019-11-19 14:04
No I cannot reproduce, I have tested on my old 3.4.0 and nothing leak, but you have it leaking. Maybe @gioman can test more in depth but I have no issues on my end.

**Comment by gioman** [comment] 2019-11-19 17:13
nothing weird here with the latest 3.4 on linux.

**Comment by quabes** [comment] 2019-11-26 06:12
Hi there!
Sorry for late response but I had to prepare a short [movie,](https://youtu.be/568r84IU0uM) showing this problem. My projects works fine all day long (and that is why I don't suspect there is something wrong with them) but when I click ADD LAYER (e.g. vector, but whitout adding anything - I close that window immediately), QGIS starts use more and more RAM memory. This is on fresh Ubuntu 18.04 host and QGIS 3.4.13 - nothing else was installed on that machine.
If you have any sugestions please let me know...

**Comment by quabes** [comment] 2019-12-03 06:12
no one?? really??
for me there is some thing wrong - maybe with my project, but why QGIS is working well until I click this add layer button...?
if you get somethink like on my movie, let me know ...
https://www.youtube.com/watch?v=568r84IU0uM&feature=youtu.be
regards!

**Comment by CarstenRC** [comment] 2020-03-03 07:35
Your video is private - I would like to check it out to see if your problem resembles mine. Can you make it public?

**Comment by quabes** [comment] 2020-03-03 12:29
I tought that noone want to see it.
Now it is public - if you will have any comments, please let me know...
Regards!

**Comment by Pedro-Murteira** [comment] 2022-01-17 15:05
@quabes I can't reproduce this issue using QGIS 3.16.15 and 3.22.2. on fresh windows 10. The RAM usage spikes a little bit after adding a vector and closing the window (which I assume is the expected behaviour) but nothing like you show on the video. Did you by any chance came across this problem in more recent versions of QGIS?

**Comment by quabes** [comment] 2022-01-18 06:44
Hi there - now it works fine (above 3.10). the problem disappear in qgis 3.12 or 3.14 (can't remember), but i have no idea how and what was fixed (i still work on the same project file).
Regards!

**Closed** 2022-01-18 08:16 UTC
Labels: Feedback, Bug
