### ISSUE TITLE
Marker line with custom dash

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28910] opened 2019-01-25 06:46 UTC
Author Name: **Sergey Chernyshov** (Sergey Chernyshov)
Original Redmine Issue: [21092](https://issues.qgis.org/issues/21092)
Affected QGIS version: 3.4.4
Redmine category:symbology

---
Rendering of comlex line symbol ( marker line with custom dash line ) show different incorrect results on different scales. See examples on the pictures. "Scale 1:500" shows correct rendering. Position of marker match the gap of dashed line. "Scale 1:250" - line cross the symbol. "Scale 1:10000" - wrong symbol size. Size of symbol is set in map units. With this scale it must be one pixel only or invisible. I see this problem in both QGIS 2.18 and 3.4 versions.

---

- [500.png](https://issues.qgis.org/attachments/download/14168/500.png) (Sergey Chernyshov)
- [250.png](https://issues.qgis.org/attachments/download/14169/250.png) (Sergey Chernyshov)
- [Font.png](https://issues.qgis.org/attachments/download/14170/Font.png) (Sergey Chernyshov)
- [10000.png](https://issues.qgis.org/attachments/download/14171/10000.png) (Sergey Chernyshov)
- [Line.png](https://issues.qgis.org/attachments/download/14172/Line.png) (Sergey Chernyshov)
- [Symbol.png](https://issues.qgis.org/attachments/download/14173/Symbol.png) (Sergey Chernyshov)

**Comment by nyalldawson** [comment] 2021-01-20 20:26
Can you share a sample project which demonstrates this issue?

**Comment by pjshelton** [comment] 2021-01-27 03:38
[test.zip](https://github.com/qgis/QGIS/files/5877481/test.zip)
Here is a test file and project that on my machine shows differences between the measure used in custom dash vs the measure used in marker line.
![Capture](https://user-images.githubusercontent.com/39154868/105937144-ae493800-60a0-11eb-8529-567a6a95558e.PNG)

It appears that the the sizes for each 'part' of the custom dash is not strictly adhered to.

I am using a projected coordinate system, so 'map units' and 'meters at scale' are the same. 

I expect the original poster was hopping that the start point for the custom dash would be the same point for the marker line.  But with the non uniform lengths of the custom dash and the semi random start point for the "first" point for both the custom dash and marker line given how much of the line is in view, one can not make a pattern that will stay together at any scale and view port.  I suspect that this will also be a issue for #39263

**Comment by pjshelton** [comment] 2021-02-10 22:16
see #26028 for a 2D version of this bug.

Both are likely related to#26749

**Comment by nyalldawson** [comment] 2021-09-24 05:48
Looks like this is fixed now:

![image](https://user-images.githubusercontent.com/1829991/134624570-4bc9b91f-e315-466b-9e0f-951c7e015582.png)

Please re-open if it's still an issue and post steps to reproduce on current versions

**Closed by nyalldawson** 2021-09-24 05:48 UTC
Labels: Symbology, Bug

**Comment by djes** [comment] 2023-01-11 08:33
Hi,
The custom dash doesn't seem to work on QGIS 3.22.14 windows 10

Default continuous line : 
![image](https://user-images.githubusercontent.com/12065874/211755741-dc4da511-8d9f-4bad-aa09-2bd1ebf8b0b0.png)

Custom 1m-1m dash (map unit is in meters) : 
![image](https://user-images.githubusercontent.com/12065874/211755961-bac47fb9-a7a6-448b-b6c5-badb93425420.png)

Custom 1m-2m dash (map unit is in meters) : 
![image](https://user-images.githubusercontent.com/12065874/211756118-c04ebe1c-fc12-4e27-a333-d89289db2592.png)

The demo project :
[CustomDashBug.zip](https://github.com/qgis/QGIS/files/10390223/CustomDashBug.zip)

**Comment by nyalldawson** [comment] 2023-01-11 08:36
@djwa set the "cap style" to "flat"

**Comment by andreasneumann** [comment] 2023-01-11 08:41
@djwa - this is not a bug. It has to do with the "line caps". It adds 2 line caps on both sides and appears like a continuous line.

This is normal an expected.

**Comment by djes** [comment] 2023-01-11 11:17
@andreasneumann @nyalldawson I was not clear enough, the problem is not the cap artefacts, it's the size of the parts : as you see, when I set 1 m. in both, the result is a line. When I set 1 in the first part and 2 in the second, I get something unpredictable.

**Comment by djes** [comment] 2023-01-11 11:22
Thank you !

**Comment by beesuns** [comment] 2025-04-04 05:17
How to customize line symbols within QGIS?
