### ISSUE TITLE
UI issues on datum transformations

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#32936] opened 2019-11-18 18:00 UTC
A bug report has already been issued for various missing datum transformations that appear in an upgrade to QGIS 3.10.0-3 (see #32795). Here I highlight separately 2 UI-related issues in working around these issues manually.

1. A warning on loading the project is (appropriately) displayed, e.g. (in my case) "Cannot use preferred transform between EPSG:26918 and EPSG:1951". However, this warning keeps on appearing at load even when a (non-preferred) datum transformation has been set in Project and Profile CRS settings. I would expect this warning should appear only when no such explicit setting has been made. Once user has chosen a datum transformation it just confuses inexperienced further users.

2. When hitting Details  in this warning, the "Preferred transformation not available" dialog comes up. When hitting Install from folder button..., the installation fails (after the gsb file is located) if the `proj` folder in the user profile directory does not exist yet. It succeeds if the `proj` directory is first manually created, empty. QGIS should silently create it if missing.

I recognize these are glitches coming to light with the proj6 upgrade, and the effort is appreciated. Just highlighting as small stuff that it has brought to light.

**Comment by nyalldawson** [comment] 2019-11-25 06:54
Issue 1 is a duplicate of #30569

**Closed** 2019-11-25 17:59 UTC
Labels: Bug
