### ISSUE TITLE
Bug with inverted polygon rendering on an oriented map 

### ISSUE THREAD

**Issue by REIMSMetropole** [qgis/QGIS#30129] opened 2019-06-07 12:12 UTC
**Description**
When you represent a polygon with inverted polygon and you add a rotation angle to the map canvas in the layout, the shape of the inverted polygon isn't correct. See image in links below.

**How to Reproduce**

1.open a layer with one polygon
2. choose and apply an inverted polygon representation 
3. apply a rotation to the canvas : (-160) 
4. See error -->

**QGIS and OS versions**
Windows10, Qgis 3.4.7. Osgeo installer

**Additional context**
configuration
![](https://framapic.org/ZXcWohitK2PR/zEZPOuEsMO3h)
error
![](https://framapic.org/04PEevepWETd/nDBoDo5VRiUr)
![](https://framapic.org/iML9Rd4rh4TP/bcFjvbD02BIH)
maybe related to https://github.com/qgis/QGIS/issues/29768

**Comment by Gustry** [comment] 2019-06-07 12:29
Already fixed: https://github.com/qgis/QGIS/pull/30069/commits/637ec81b25fb31e36e33a1f920ded4fa989a64e5

**Comment by REIMSMetropole** [comment] 2019-06-07 12:34
The resolution will be in 3.8.0 ? Am I right ?

**Comment by Gustry** [comment] 2019-06-07 13:09
3.4 is still supported and it has been backported https://github.com/qgis/QGIS/commit/820f7927ad6f802ec55634da13d84913db5d9021 so you will find it in 3.4.9 too.

**Comment by Gustry** [comment] 2019-06-07 13:11
Duplicate of https://github.com/qgis/QGIS/issues/26381

**Closed** 2019-06-07 13:47 UTC
Labels: Bug
