### ISSUE TITLE
QGIS 3.6.0 confusing update window

### ISSUE THREAD

**Issue by Komzpa** [qgis/QGIS#30642] opened 2019-07-09 10:50 UTC
1) sends me to issues.qgis.org
2) offers to get 3.8 release, tells you are working on 3.7 and 3.8 is getting released later
![image](https://user-images.githubusercontent.com/810638/60882341-50e85e80-a250-11e9-8223-2b926837266a.png)

**Comment by stev-0** [comment] 2019-07-09 16:34
Not sure this in GUI / UX - looks like it's in the backend. This endpoint is called: https://version.qgis.org/version.txt and it is that which is out of date

**Comment by stev-0** [comment] 2019-07-31 16:32
Pretty sure this can be closed as it is replaced by https://github.com/qgis/QGIS/issues/31019

**Comment by jef-n** [comment] 2019-07-31 21:30
Duplicate of #31019

**Closed by jef-n** 2019-07-31 21:30 UTC
Labels: Bug, GUI/UX
