### ISSUE TITLE
Is there really no way anymore to load entire directory tree of raster tiles as one layer?

### ISSUE THREAD

**Issue by StacktraceException** [qgis/QGIS#53538] opened 2023-06-21 14:22 UTC
### What is the bug or the crash?

The feature is missing. According to a guide I followed; i should be able to load all the directory tree of individual tiles with Layer-> Add Layer ->  Raster -> directory     or Layer -> Add Layer - > Directory  or QGIS should at least ask me if i want to import the entire dir structure when i select a single file with the Raster selection,.

This issue is about QGIS, but I will mix in some struggles I  had trying some workarounds  for better context:

Adding to the struggle: The plugin (TileLoader) that   they say that used to be able to load directories of tiles is deprecated as it does not work with QGIs versions ≤ 3. 

furthermore: Qtiles plugin has a few problems, and only works by downloading layer as a directory tree. It is better to have individual tiles instead of huge multiple GB file, (or can Qgis load only a part of such an image at a time without performance loss?), but gdal_merge.py couldn't merge these files anyway.  It had errors such as:  wrong input parameters for INPUT. 

I have searched through several youtube guides and google search results but they were not relevant and the ones I found do not work   as described above.

Loading each tile as a separate layer is ridiculous, partly because it spams the entire View Panel with thousands of tiles each as their own layer which makes it very unusable.
 
 
 Please reimplement this essential functionality very soon, as without it, amongs other things; it is not possible to download layers from online services, (which is very important obviously to lessen the  burden on the servers, and to stop having to work dealing with their almost unworkably slow speeds).
 
 Some working workaround for now 'll be appreciated, please.

### Steps to reproduce the issue

 Layer-> Add Layer ->  Raster ->  
 
missing import directory tree functionality

try to merge tiles with gdal_merge.py , select input directory
both methods (single vs multiple something) fail.
 

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
Spatia Lite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
gugik_datafeeder
1.0.6
qtiles
1.7.2
db_manager
0.1.20
grassprovider
12/2/99
MetaSearch
0.3.6
processing
12/2/99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment] 2023-06-21 14:41
Hi, 

If there is missing feature, create a feature request, not a bug.

> According to a guide I followed

Which one ?

> The plugin (TileLoader) that they say that used to be able to load directories of tiles is deprecated as it does not work with QGIs versions ≤ 3.

Not QGIS issue, report on plugin repo

> Qtiles plugin has a few problems

Same. Not a QGIS issue, report on plugin repo.

> Please reimplement this essential functionality very soon

Things don't happen "magically". It always needs someone to do the work or contract with someone else to do the work. Once done, it is shared with everybody.

In this case it seems it never seemed important enough for someone to take the initiative.

Note that by opening this feature request, it won't be implemented automagically either, unless someone does it or contracts someone to do the work. It is different with bug reports. Bug reports, esp. the ones that trigger a crash or data corruption are usually addressed if they can be reproduced and fixed.

See also http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ and http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis-a-follow-up/

Feature requests are still welcome though, as they might trigger someone's interest and it can also be discussed with others - and if you contract with someone to do the implementation work for you, you can reference such a feature request.


Easy solution : Create a virtual raster layer 
https://docs.qgis.org/3.28/en/docs/training_manual/rasters/data_manipulation.html#basic-fa-create-a-virtual-raster

**Comment by StacktraceException** [comment] 2023-06-21 14:58
> 

Hi, sorry if the functionality never existed(?), then I would make a feature request instead of thinking it is a bug that it is missing.

regarding your easy solution – it does not seem applicable: I have followed the steps therein and at this step I am lost: 
"In the dialog that appears, click on the … button next to the Input layers parameter and check all the layers or use the Select All button;" but this only chooses layers **that already exist**, instead of choosing directory tree.

please someone have a solution, I have spent the entire day now trying to get success..

**Comment by StacktraceException** [comment] 2023-06-21 15:16
export-> Save as image: Could not allocate required memory for image, another problem here.

**Comment by StacktraceException** [comment] 2023-06-21 15:43
when trying to import a 74mb zip file containing about 120 thousand 2kb tiles created with the  qtiles plugin, qgis just hangs up, even though no cpu nor ram etc is being used.  smaller amount of files worked better..

**Comment by StacktraceException** [comment] 2023-06-21 16:42
I tried to be able to import with latest <3 Qgis version, with that plugin but it could not be found in tge lugin database. After finding out how to install it manually, it is loaded according to the plugin window, but for some reason no plugins are able to be selected anyway,  (even the one installed from repository with the window , which is the official way).

**Comment by StacktraceException** [comment] 2023-06-21 17:00
> 
error:
Incorrect value for INPUT.

**Comment by alexbruy** [comment] 2023-11-10 13:33
Sorry, but it is really hard to understand what is your problem as you mix lots of things there, including plugin issues which are not related to QGIS.

You can select and use all files from a single directory. You can add files from multiple different directories (directory by directory). You can use batch dialog and load all files recursively.

Close as this is not a bug or feature request. Please next time create a separate bugreport or feature request and don't mix everything in one ticket.

**Closed by alexbruy** 2023-11-10 13:33 UTC
Labels: Bug
