### ISSUE TITLE
Multiple selection widget in Processing close the algorithm [OSX]

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#33783] opened 2020-01-14 07:37 UTC
**Describe the bug**
On a OSX with Catalina and QGIS 3.10, algorithms with a multiple selection widget (dissolve, collect geometries, etc) cause the closure of the dialog.

**How to Reproduce**

1. Open the Dissolve algorithm
2. Choose the layer
3. Click on the `...` button to choose the field
4. When clicking on OK of the Multiple Selection Widget the whole algorithm dialog closes without the chance to click on Run or to choose other parameters

**QGIS and OS versions**

QGIS 3.10
OSX Catalina

**Comment by alexbruy** [comment] 2020-01-14 07:43
Does it really closes or just minimized?

Looks like duplicate of #31577

**Comment by gioman** [comment] 2020-01-16 13:53
> Does it really closes or just minimized?
> 
> Looks like duplicate of #31577

it is indeed, just tested on Catalina.

**Closed by gioman** 2020-01-16 13:53 UTC
Labels: Bug, Feedback
