### ISSUE TITLE
PostgreSQL query from PyQGIS wrong results for boolean fields

### ISSUE THREAD

**Issue by giswgjs** [qgis/QGIS#39679] opened 2020-10-28 12:27 UTC
**Describe the bug**
I have a small table structured like this:
![grafik](https://user-images.githubusercontent.com/17158239/97434245-02684300-191f-11eb-9244-6f8102edd7d5.png)

Querying from DB Manager gives expected results:
![grafik](https://user-images.githubusercontent.com/17158239/97434427-49563880-191f-11eb-9cf6-f2904f99d08c.png)

The same query from PyQGIS gives a **different (wrong) result**:
```
>>> c = QgsProviderRegistry.instance().providerMetadata('postgres').connections()['gis (authcfg)']
>>> c.executeSql('select test from public.test_bool')
[[True], [True], [True], [True]]
```
![grafik](https://user-images.githubusercontent.com/17158239/97434890-fb8e0000-191f-11eb-98be-20fff21d51eb.png)

**QGIS and OS versions**

Occurs in `3.10.11`, `3.10.8`

`3.16.0` is NOT affected:
![grafik](https://user-images.githubusercontent.com/17158239/97435276-7eaf5600-1920-11eb-94d3-16fa9c328d84.png)

**Comment by elpaso** [comment] 2020-10-28 14:04
can you please attach the SQL necessary to create the test table and the test rows?

**Comment by giswgjs** [comment] 2020-10-28 14:25
Here it is:
```
create table public.test_bool ( id serial, test boolean);
insert into public.test_bool (test) values (true), (false), (true), (false);
```

and then
`select test from public.test_bool`

for the python statements ref. above.

**Comment by elpaso** [comment] 2020-10-29 06:51
Duplicate of https://github.com/qgis/QGIS/issues/33130 ?

It seems the fix was not backported.

**Comment by giswgjs** [comment] 2020-10-29 07:04
Yes, same issue.

**Comment by gioman** [comment] 2020-11-11 18:51
Closing as duplicate.

**Closed by gioman** 2020-11-11 18:51 UTC
Labels: Bug, Feedback, PyQGIS
