### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by yellow-sky** [qgis/QGIS#44612] opened 2021-08-08 11:52 UTC
### What is the bug or the crash?

The following signatures were invalid: EXPKEYSIG F7E06F06199EF2F2 QGIS Archive Automatic Signing Key (2020) <qgis-developer@lists.osgeo.org>

W: GPG error: https://qgis.org/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG F7E06F06199EF2F2 QGIS Archive Automatic Signing Key (2020) <qgis-developer@lists.osgeo.org>

### Steps to reproduce the issue

apt-key adv --keyserver keyserver.ubuntu.com --recv-key F7E06F06199EF2F2

or 

wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | apt-key add -

### Versions

Ubuntu 20.04
qgis latest

**Comment by yellow-sky** [comment] 2021-08-08 11:55
Documentation links:
https://qgis.org/en/site/forusers/alldownloads.html#quickstart
https://qgis.org/en/site/forusers/alldownloads.html#repositories

**Comment by laszloatoth** [comment] 2021-08-08 13:26
I have the same problem on Ubuntu 20.04

**Comment by agiudiceandrea** [comment] 2021-08-08 20:38
See also https://github.com/qgis/QGIS-Website/issues/928

**Comment by romulusFR** [comment] 2021-08-09 00:40
The key seems to be expired 

```
pub   rsa4096 2020-08-08 [SCEA] [expired: 2021-08-08]
      39877635093F2656019711FAF7E06F06199EF2F2
uid           QGIS Archive Automatic Signing Key (2020) <qgis-developer@lists.osgeo.org>
```

**Comment by gioman** [comment] 2021-08-09 07:23
Do we have a better tracker where to move this (as it is not about QGIS codebase)?

**Comment by jef-n** [comment] 2021-08-09 08:51
Duplicate of qgis/QGIS-Website#928

**Closed by jef-n** 2021-08-09 08:51 UTC
Labels: Bug
