### ISSUE TITLE
QGIS crash on closing

### ISSUE THREAD

**Issue by Meibes** [qgis/QGIS#31021] opened 2019-07-31 12:05 UTC
the crash did not appear on my machine and I'm not able to access the machine for further testing, so consider this feedback. as far as i know qgis was freshly installed and had no plugins

## User Feedback

on closing qgis

## Report Details

*Crash ID*: 41bd556bfb4cb3857ad8b303df49560eb10217ac

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator char const * __ptr64 const * __ptr64 :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

**Comment by roya0045** [comment] 2019-07-31 14:27
Please try with a new/clean QGIS profile and no 3rd party plugins installed.

**Comment by Meibes** [comment] 2019-08-01 06:52
the QGIS profile should be clean because I uninstall QGIS every time before I update to a new QGIS Version, unless the profile doesn't get deleted on uninstall (which would be bad)

I have 2 3rd party plugins installed, "First Aid" and one custom plugin created with Plugin Builder (which is not installed anymore). Normally when there are errors in my code "First Aid" shows the stack trace in a new window. But this window did not open and the QGIS stack trace lists "proj_lpz_dist, QgsCoordinateTransform" and since my plugin only reads attributes I highly doubt that it is responsible for any kind of "proj" or "coordinate" operations, since there is not a single line of code in my plugin that affects projection or coordinates (as far as I know and the pyQGIS cookbook-snippets describe).

**Comment by NathanW2** [comment] 2019-08-01 07:01
Profiles don't get removed between installs because they are user data not
part of the install and work cross-version.

There a few fixes in place to hopefully catch this bug.  Keep updated with
the latest patches and we will see if it's still happening.  First Aid will
only catch Python errors, this one is a hard crash from the C++ code.  We
have known about it and are looking into it.

**Comment by Meibes** [comment] 2019-08-01 08:27
is it possible to add an option like "clean user profiles" to the uninstall?

thank you for explaining the issue, I hope you can solve it!

> 
> Profiles don't get removed between installs because they are user data not part of the install and work cross-version. There a few fixes in place to hopefully catch this bug. Keep updated with the latest patches and we will see if it's still happening. First Aid will only catch Python errors, this one is a hard crash from the C++ code. We have known about it and are looking into it.

**Comment by gioman** [comment] 2019-08-01 10:20
In the meantime closing as its duplicate of other several identical reports.

**Closed by gioman** 2019-08-01 10:20 UTC
Labels: Bug
