### ISSUE TITLE
[Layer panel] - mysterious objects

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#35425] opened 2020-03-28 14:25 UTC
Since **QGIS 3.12** I notice these strange objects in the layer panel, what are they? what are they for?? it's normal??

![image](https://user-images.githubusercontent.com/7631137/77825183-f6f23680-7107-11ea-8265-f0863c38ef3b.png)

**Comment by roya0045** [comment] 2020-03-28 15:04
I'm pretty sure (99%) that this was already reported.

**Comment by pigreco** [comment] 2020-03-29 09:08
> I'm pretty sure (99%) that this was already reported.

I can't find anything, also because I don't know what to look for. :-(

**Comment by gioman** [comment] 2020-03-29 09:42
Duplicate of https://github.com/qgis/QGIS/issues/32029

**Closed by gioman** 2020-03-29 09:42 UTC
Labels: Bug

**Comment by roya0045** [comment] 2020-03-29 09:47
@gioman Thanks gio! I've looked yesterday and couldn't find it back.

**Comment by gioman** [comment] 2020-03-29 09:49
> @gioman Thanks gio! I've looked yesterday and couldn't find it back.

no problem!

**Comment by Gustry** [comment] 2020-03-29 09:56
Thanks. I also tried to find this ticket yesterday. Lesson learned again, screenshots are
not searchable ;-)
It's also in qgis 3.10

**Comment by gioman** [comment] 2020-03-29 09:58
>  It's also in qgis 3.10

@Gustry there was not much discussion (in the mailing lists) about this change: https://github.com/qgis/QGIS/issues/32029#issuecomment-535854462
