### ISSUE TITLE
Possible Geopackage Load Style Bug in QGIS 3.14

### ISSUE THREAD

**Issue by adjeprado** [qgis/QGIS#37419] opened 2020-06-25 19:30 UTC
Hi there, this might be a bug, but might just be a quirk.

Despite being able to save multiple layer styles to a geopackage associated with a same layer, when the layer is later loaded, the styles are not loaded with it (other than the default). I don't know if this was the same behaviour as in previous versions, but it seems counter-intuitive that it is possible to save and name the styles, that they are associated to the layer (field is filled in the f_table_name attribute of layer_styles).

**Comment by gioman** [comment] 2020-06-25 20:17
@adjeprado I cannot confirm on QGIS master on Ubuntu 18.04, or I have not understand how to replicate.

Pleas file tickets following the requested template:



**Describe the bug**


**How to Reproduce**



**QGIS and OS versions**



**Additional context**




also attach sample project/data.

**Comment by Gustry** [comment] 2020-06-25 20:25
Are you sure it's related to 3.14 ?

If I understand correctly, it has been like this for years (QGIS 2 already) for PostgreSQL (so it might true for geopackage too?).
If you save multiple styles for a postgresql layer in the DB, only the default one will be loaded when you add back the layer in QGIS.

I made this plugin a few years ago to overpass this limitation for postgresql : https://github.com/PnGuadeloupe/db-style-manager

Can you explain the issue?

**Comment by adjeprado** [comment] 2020-06-25 20:39
Thanks @gioman, here are more details:

**The bug**
Despite it being possible for multiple styles to be saved to a single layer in a GeoPackage, when the layer is loaded again, only the default style is loaded with it. This is despite the layer being identified in the f_table_name attribute of the layer_styles table. Intuitively, it should be expected that all styles associated with the layer would be loaded when the layer is imported into QGIS.

**How to reproduce the bug**
1. From a vector layer saved as a geopackage access the layer properties -> symbology interface.
2. Create a style of the categorized type (likely applies to other types)
3. Save the current style to the geopackage (Style -> Save Current Style -> Change save style to "In Database (Geopackage)"
4. Name the style
5. Press OK
6. Repeat the process with a different name
7. Note that the two style should appear when the "Style" button is clicked as they are currently loaded and attributed to the layer.
8. Exit the layer properties interface.
9. Re-import the layer (the original layer can remain in the the project).
10. Open the layer properties interface of the newly imported layer and navigate to symbology. Upon clicking on style, only the default style will be loaded, the additional styles will not appear and will need to be manually loaded through "Load style"

**QGIS and OS versions**
QGIS 3.14
OS version Windows 10 10.0.18363 Build 18363

**Additional context**
From original post:  don't know if this was the same behaviour as in previous versions, but it seems counter-intuitive that it is possible to save and name the styles, that they are associated to the layer (field is filled in the f_table_name attribute of layer_styles).

@Gustry I am not sure if this is a bug. As I mentioned in the original post, it may just be a quirk that has been around for longer. I had tried to use this function when I was learning about Geopackages, but assumed that it was my inexperience that was the problem. Now I am relatively confident that this is simply an issue/bug or missing function in QGIS. Perhaps this function was simply not coded in and is a limitation as you point out. It does seem counter-intuitive that QGIS would not do this natively since all the information needed for this behaviour is included in the geopackage. Thanks for the link to your plugin, I will check it out!

**Comment by Gustry** [comment] 2020-06-25 20:48
Yes, so we are indeed talking about the same thing.
It's not a bug, because it has never been coded in QGIS. But I agree, from the user point of view, it might be confusing.
That's why I made this plugin to load all styles automatically.

I haven't checked for geopackage. But for PG, only a single style can be set to default and only this style will be loaded by QGIS. Other styles linked to the layer, but no set as default, won't be loaded.

**Comment by gioman** [comment] 2020-06-25 20:50
>  It's not a bug, because it has never been coded in QGIS. But I agree, from the user point of view, it might be confusing.

@adjeprado then plesae close this and reopen a new one formulating it as a feature request, given that the same does not exist already.

**Closed** 2020-06-26 15:02 UTC
Labels: Bug, Feedback
