### ISSUE TITLE
DXF exported from QGIS 3.xx Crashes AutoCAD 2019 and later

### ISSUE THREAD

**Issue by HectorAlex** [qgis/QGIS#32987] opened 2019-11-21 07:09 UTC
>Opening a DXF no matter how simple when made in QGIS will crash AutoCAD
>Recover before opening still crashes AutoCAD
>Sometimes the recovered data will be stored as a crash backup, others not
>Error is always "FATAL ERROR: Unhandled e0434352h Exception at 75C9A839h"

**Comment by lbartoletti** [comment] 2019-11-21 08:33
I confirm too. I close this ticket since it's a duplicate of https://github.com/qgis/QGIS/issues/30273

You can follow discussion also on the GDAL ticket https://github.com/OSGeo/gdal/issues/1213

**Closed by lbartoletti** 2019-11-21 08:33 UTC
Labels: Bug

**Comment by AlisterH** [comment] 2020-03-29 20:03
Note this is fixed upstream and involved only changes to header.dxf and trailer.dxf
These files can be updated even without a new version of gdal; it would be good to do this in e.g. the Windows package.
