### ISSUE TITLE
QGis 3.16.1 Layout problem using atlas

### ISSUE THREAD

**Issue by Tetranos** [qgis/QGIS#40560] opened 2020-12-11 22:06 UTC
Hi,

With QGis 3.16.1, I've got a layout problem with the legend while creating an atlas.
![About](https://user-images.githubusercontent.com/795919/101959115-fac9d880-3c04-11eb-8d90-6813fcd67148.png)

The legend is left-bottom aligned and the "Only show items inside linked map" is on.

The preview is fine.
![preview](https://user-images.githubusercontent.com/795919/101959121-fbfb0580-3c04-11eb-9054-01e94de3c4e2.png)

But the PDF export is not.
![PDF](https://user-images.githubusercontent.com/795919/101959117-fb626f00-3c04-11eb-821d-89f31e326dc1.png)

Any idea?

**Comment by roya0045** [comment] 2020-12-11 22:10
Duplicate of #37566

**Closed** 2020-12-13 11:17 UTC
Labels: Bug
