### ISSUE TITLE
Topmost group exapands automatically

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS#35134] opened 2020-03-17 07:08 UTC
When a template is loaded, the topmost group is automatically expanded.
Is this behavior by design?

![image](https://user-images.githubusercontent.com/588407/76830796-5312ac00-6826-11ea-90c2-73e26b93590a.png)

**Comment by alexbruy** [comment] 2020-05-26 06:00
Looks like duplicate of #30971.

**Closed** 2020-05-26 06:06 UTC
Labels: Bug, Map and Legend
