### ISSUE TITLE
Third party python libraries LTR version

### ISSUE THREAD

**Issue by PCdurham** [qgis/QGIS#38441] opened 2020-08-24 17:18 UTC
Having issues installing extra python libraries with 3.10LTR.  My usual steps are:

1- Launch OSGEO shell as admin
2- py3_env
3- pip install...

This usually works and it definitly did in 3.4.  But now I get a DLL error: 
_ImportError: DLL load failed: The specified module could not be found._

And then if I return to the shell and try again to install, I get confirmation that the requirement is already satisfied. What has changed since 3.4?

thx

**Comment by jef-n** [comment] 2020-08-24 21:06
Probably a duplicate of #38398.  Verify with qgis-ltr-dev.

**Closed by jef-n** 2020-08-24 21:06 UTC
Labels: Bug
