### ISSUE TITLE
"Default" tool

### ISSUE THREAD

**Issue by ivan-n-gor** [qgis/QGIS#59344] opened 2024-11-06 03:21 UTC
### Feature description

There are sometimes annoying behavior in QGis: when you stop editing, last editing tool remains active, causing the "Layer not editable" message on the next mouse click (or you must always remember this to avoid it). 

It would be nice to introduce some sort of "default" tool (either hardcoded or user selectable) and switch to it after stop editing.

**Comment by agiudiceandrea** [comment] 2024-11-06 08:16
Duplicate of https://github.com/qgis/QGIS/issues/59292.

**Closed by agiudiceandrea** 2024-11-06 08:16 UTC
Labels: Feature Request
