### ISSUE TITLE
printing crash

### ISSUE THREAD

**Issue by flo-caron** [qgis/QGIS#37290] opened 2020-06-18 11:54 UTC
Whenever I try to export a project in PDF of image the application crashes.

I tried to create to create a new profile and fully reinstalled QGis but the problem persists. I also changed the ouput resolution but same result. The problem occures even on blank new files, wherever they are (network share, local driver...)

QGIS Info
QGIS Version: 3.10.6-A Coru�a
QGIS code revision: ec80021f49
[report.txt](https://github.com/qgis/QGIS/files/4798290/report.txt)

Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
[report.txt](https://github.com/qgis/QGIS/files/4798296/report.txt)

Kernel Version: 10.0.18363

_____
**Crash ID**: [ec5cdf17a444767358bd30c774b02d5077747530](https://github.com/qgis/QGIS/search?q=ec5cdf17a444767358bd30c774b02d5077747530&type=Issues)

**Stack Trace**
<pre>
EngGetPrinterDataFileName :
DrvDisableDriver :
GdiPrinterThunk :
__ClientPrinterThunk :
KiUserCallbackDispatcherContinue :
NtGdiOpenDCW :
hdcCreateDCW :
bCreateDCW :
CreateDCW :
QWin32PrintEngine::globalDevMode :
QWin32PrintEngine::QWin32PrintEngine :
qt_plugin_query_metadata :
QPrinterPrivate::initEngines :
QPrinter::QPrinter :
QgsMapRendererTask::prepare qgsmaprenderertask.cpp:458
QgsMapRendererTask::QgsMapRendererTask qgsmaprenderertask.cpp:129
QgsMapSaveDialog::onAccepted qgsmapsavedialog.cpp:538
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:418
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1606
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.6-A Coru?a
QGIS code revision: ec80021f49
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7600

**Comment by gioman** [comment] 2020-06-18 11:59
@flo-caron do you have the "print as raster" option enabled?

**Comment by flo-caron** [comment] 2020-06-19 06:37
I tried with both enabled and disabled, the result is the same. I also updated my graphic card driver. I can successfully export as image but PDF generation still crashes

**Comment by gioman** [comment] 2020-06-19 07:11
> but PDF generation still crashes

@flo-caron this is with the QGIS native tool to export to pdf? have you tried other 3rd party tools? have you tested on a different machine to exclude local issues?

**Comment by flo-caron** [comment] 2020-06-19 07:42
yes it is the tool export pdf  from qgis and the tool export pdf  and the tool print  since the print composer.

**Comment by gioman** [comment] 2020-06-19 13:45
> yes it is the tool export pdf from qgis and the tool export pdf and the tool print since the print composer.

@flo-caron have you tried on a different machine?

**Comment by flo-caron** [comment] 2020-06-22 05:27
yes it 's work on other machine

**Comment by gioman** [comment] 2020-06-22 10:39
> yes it 's work on other machine

@flo-caron so it looks like a local issue, or a QGIS issue that is specific to something in a specific machine. In this second case you must try find what this could be, otherwise we can't really help much...

**Comment by UnknownShadow200** [comment] 2020-06-24 09:28
FYI, the June 9th Windows 10 update [may be the cause of your crashes](https://www.reddit.com/r/techsupport/comments/h0ctsp/chrome_and_edge_both_quit_when_trying_to_print_a/)

Not using this application, but I had problems where any attempt to print would crash in `EngGetPrinterDataFileName`.
Uninstalling that update fixed the crashing for me, but I don't recommend that. (If you read through [KB-4560960](https://support.microsoft.com/en-au/help/4560960/windows-10-update-kb4560960), it mentions that installing [KB-4567512](https://support.microsoft.com/en-au/help/4567512/windows-10-update-kb4567512) should fix issues with certain printers causing errors)

**Comment by gioman** [comment] 2020-06-24 09:59
@UnknownShadow200 thanks for this report.

@flo-caron closing as upstream issue?

**Closed** 2020-07-18 10:00 UTC
Labels: Bug, Crash/Data Corruption, Feedback, Print Layouts
