### ISSUE TITLE
Layer reorder is broken for WMS layers

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#36390] opened 2020-05-12 23:48 UTC
I only tested with WMS layers but the behaviour of WMS layer reordering in the layers list is broken. Dragging a layer to the top of the list will result in it being moved to the bottom of the list:

![layer-reorder-bug](https://user-images.githubusercontent.com/178003/81756275-36f05b80-94b3-11ea-9862-a00ef3bd8d84.gif)

Note also the strange QgsMessageBar notification in the screencast above.

**How to Reproduce**

Add some WMS layers to a project.
Drag a layer from the middle of the list to the top.

Other permutations have the same effect e.g. moving a layer down a few notches sends it to the bottom.

**QGIS and OS versions**

QGIS Version: 5bf120a885 
OS: macOS
Package source: QGIS nightly builds

**Comment by nyalldawson** [comment] 2020-05-12 23:52
@3nids I see the "added from another instance" message here too -- I think this is caused by your recent changes

**Comment by nyalldawson** [comment] 2020-05-15 22:09
Fixed in master

**Closed by nyalldawson** 2020-05-15 22:09 UTC
Labels: Bug

**Comment by timlinux** [comment] 2020-05-18 18:07
Thanks!
