### ISSUE TITLE
QGIS 3.10 crashes when using feature rotate

### ISSUE THREAD

**Issue by tessabeukelaar** [qgis/QGIS#33157] opened 2019-11-29 15:59 UTC
Everytime I try to rotate features in QGIS 3.10 it crashes. 

I use a simple point-shape or created a grid out of lines, which I want to align with an existing polygon. I use the build in tool available in the advanced digitizing set. Even when I use an empty profile and only load a point-shape. I select the features I want to rotate and move my cursor in the direction. As soon as a let go of my mousebutton to let the rotation actually take place, QGIS won't respond anymore and either crashes or needs to be shut down...

**QGIS and OS versions**

QGIS-versie
3.10.0-A CoruÃ±a
QGIS code revisie
6c816b4204
Gecompileerd tegen Qt
5.11.2
Gebruikt nu Qt
5.11.2
Gecompileerd tegen GDAL/OGR
2.4.1
Gebruikt nu GDAL/OGR
2.4.1
Gecompileerd tegen GEOS
3.8.0-CAPI-1.13.1
Gebruikt nu GEOS
3.8.0-CAPI-1.13.1 
Gecompileerd tegen SQLite
3.29.0
Uitgevoerd met SQLite
3.29.0
PostgreSQL Client Versie
11.5
SpatiaLite-versie
4.3.0
QWT versie
6.1.3
QScintilla2 Versie
2.10.8
Gecompileerd tegen PROJ
5.2.0
Gebruikt nu PROJ
Rel. 5.2.0, September 15th, 2018
Versie OS
Windows 10 (10.0)
Actieve plug-ins van Python
FeatureGridCreator; 
geopunt4Qgis; 
mmqgis; 
pdokservicesplugin; 
profiletool; 
QGIS3-getWKT; 
SpreadsheetLayers; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

**Comment by lbartoletti** [comment] 2019-11-29 16:04
Duplicate of https://github.com/qgis/QGIS/issues/32123
Already fixed.

**Closed by lbartoletti** 2019-11-29 16:04 UTC
Labels: Bug

**Comment by tessabeukelaar** [comment] 2019-12-18 13:28
> Duplicate of #32123
> Already fixed.

Sorry, new here. What fixes this exactly? What do I do?

**Comment by Gustry** [comment] 2019-12-18 13:33
Update to 3.10.1
