### ISSUE TITLE
raster merge  error in qgis 3.10

### ISSUE THREAD

**Issue by dufl07** [qgis/QGIS#33515] opened 2019-12-24 20:33 UTC
It seems an error when I tried merge raster using 'Raster-Miscellaneous-Merge'.

**Comment by roya0045** [comment] 2019-12-24 21:53
Too generic, provide more details on the error, and anything else that could be needed to reproduce that error.

**Comment by alexbruy** [comment] 2019-12-26 16:29
There were similar tickets recently, this should be already fixed. Please try latest master or nightly build.

**Comment by agiudiceandrea** [comment] 2019-12-26 19:25
It seems a duplicate of https://github.com/qgis/QGIS/issues/33386

**Comment by gioman** [comment] 2019-12-28 02:09
Closed as duplicate.

**Closed by gioman** 2019-12-28 02:09 UTC
Labels: Bug, Feedback
