### ISSUE TITLE
Color Widget not full size upon first open per instance

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#33324] opened 2019-12-10 22:48 UTC
**Describe the bug**
Per launch of the layer settings menu, the color picker widget will fail to draw fully the first time it is invoked. If invoked again in the same instance, it will work fine.

**How to Reproduce**
1. Open Layer Settings menu
2. Choose a Color Picker widget
3. Note that it is neither full height, nor full width, and certain menu items are not exposed
![image](https://user-images.githubusercontent.com/19295950/70575706-0fe4d500-1b75-11ea-88cd-6d0e21ab4fa4.png)
4. Re-choose the Color Picker widget
5. Note that it behaves properly now
![image](https://user-images.githubusercontent.com/19295950/70575790-36a30b80-1b75-11ea-8de1-e408776e4496.png)
6. Close settings menu
7. Repeat 1-6, and verify behavior is consistent

**QGIS and OS versions**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; DataPlotly; joinmultiplelines; latlontools; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; Polygons_Pile; processing_gnm; qchainage; qconsolidate; QGISSortAndNumber-master; realcentroid; refFunctions; SelectWithin; SplitPolygonShowingAreas; statist; db_manager; processing

**Additional context**  
https://youtu.be/zu5B1xXG6fY

**Comment by Pedro-Murteira** [comment] 2021-11-30 18:39
@Saijin-Naib This is still true on 3.22.1, only on the second try does the color widget appear as a whole, but I am unable to replicate this behaviour with QGIS 3.16.14. This issue might be a regression since I can only replicate it on a later version.

**Comment by nyalldawson** [comment] 2023-05-31 02:24
Fixed by 9e019634097bfb767447d15e5e80ed2bb1371121

**Closed by nyalldawson** 2023-05-31 02:24 UTC
Labels: GUI/UX, Regression, Bug
