### ISSUE TITLE
raster file

### ISSUE THREAD

**Issue by iwa103** [qgis/QGIS#49262] opened 2022-07-07 03:03 UTC
### What is the bug or the crash?

I opened raster file.
When open file, 3.16 can show correctly.
see below.

3.16
![image](https://user-images.githubusercontent.com/77515690/177681117-f1203602-f4a4-4801-9ece-33962733ca60.png)

But 3.26, just same procudure,  can not show　graph legends, just show black and white mode.
 3.26(read raster file)
![image](https://user-images.githubusercontent.com/77515690/177681177-12690a00-3e80-41df-9995-a46dc1a40df1.png)

After close project and re open, can show corrently.
3.26(close project and re open project)
![image](https://user-images.githubusercontent.com/77515690/177681265-9dca7e55-a7d9-478b-9f95-df0c846f5550.png)

### Steps to reproduce the issue

drag and drop rater file, and see graph legends.

### Versions

3.26

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2022-07-07 05:09
Duplicates #47506 ?

**Comment by iwa103** [comment] 2022-07-07 05:27
may be same.
But not fixed yet. still remain 3.26.

**Comment by nyalldawson** [comment] 2022-07-11 07:18
Duplicate of https://github.com/qgis/QGIS/issues/47506

**Closed by nyalldawson** 2022-07-11 07:18 UTC
Labels: Raster, Bug
