### ISSUE TITLE
Crash when filtering parquet file.

### ISSUE THREAD

**Issue by mattadendorff** [qgis/QGIS#52850] opened 2023-04-23 07:06 UTC
## User Feedback

System froze while attempting to filter a geoparquet file generated with Geopandas.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00000da4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

arrow::Array::IsNull :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
QgsSqlExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

1. Generate file with Geopandas dataframe using to_parquet() output function.
2. Drag and drop layer into QGIS
3. Apply filter on layer. 

### Versions

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.18
layer2kmz
1.5.3
mmqgis
2021.9.10
OSMDownloader
1.0.3
qgis-maptiler-plugin
3.2
QuickOSM
2.2.2
topojson_writer
0.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment] 2023-04-23 07:12
Could you provide a sample file to reproduce ?

**Comment by mattadendorff** [comment] 2023-04-23 07:37
Certainly, please find zipped parquet attached. To recreate error with this file:

1. Unzip, drag and drop parquet into QGIS
2. Add filter: "town" = 'Kings Mountain'
3. Zoom in and out, crash occurs at some point in zooming.
[qgis_test.zip](https://github.com/qgis/QGIS/files/11303112/qgis_test.zip)

**Comment by nicogodet** [comment] 2023-04-24 06:48
Confirmed 
Crash after hitting "Test" in filter window.

**Comment by rouault** [comment] 2023-06-01 00:17
duplicate of https://github.com/qgis/QGIS/issues/53301

**Closed by rouault** 2023-06-01 00:17 UTC
Labels: Data Provider, Bug, Crash/Data Corruption
