### ISSUE TITLE
GeoPackage changes modified attribute on close

### ISSUE THREAD

**Issue by Barbers** [qgis/QGIS#44414] opened 2021-07-28 07:03 UTC
### What is the bug or the crash?

I got a layer in a Geopackage which I use as background.
If I open it and close it, without any changes, it still get a new modified attribute.
Since I use a cloud sync this leads to an update of the cloud file every time I close QGis.

### Steps to reproduce the issue

1. Add a Layer form a gpkg into a Qgis
2. Close Qgis without saving
3. modified attribute on gpkg get the current timestamp

### Versions

3.16.8

**Comment by gioman** [comment] 2021-07-28 08:56
Duplicate of https://github.com/qgis/QGIS/issues/23991

workaround: https://github.com/qgis/QGIS/issues/31044#issuecomment-517912023

**Closed by gioman** 2021-07-28 08:56 UTC
Labels: Bug
