### ISSUE TITLE
QGIS raster calculator: better handling of optional parameters and error message

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27380] opened 2018-08-06 17:13 UTC
Author Name: **Giovanni Manghi** (@gioman)
Original Redmine Issue: [19553](https://issues.qgis.org/issues/19553)
Affected QGIS version: 3.7(master)
Redmine category:processing/qgis

---
See attachment.

Tested on QGIS master on Linux.

I guess the "reference layer(s)" option should be made mandatory or the error must be caught.

---

- [Screenshot_20180806_181109.png](https://issues.qgis.org/attachments/download/13074/Screenshot_20180806_181109.png) (Giovanni Manghi)

**Comment by AlisterH** [comment] 2019-05-30 10:12
> On seconds thoughts I think that the very least we can do is to remove the "optional" from the CRS, extent, etc. options... this because they are not optional... if you do not choose CRS,output resolution, extent, etc the tool spits python errors.

Unless something has changed in master, you are missing the point.  The tool doesn't spit errors if you don't choose them but do choose a reference layer.

**Comment by gioman** [comment] 2019-06-03 13:38
> Unless something has changed in master, you are missing the point. The tool doesn't spit errors if you don't choose them but do choose a reference layer.

@AlisterH something changed, because before you got those errors even when selecting the "reference layer". It still baffles me why is needed to choose "that" reference layer (if the expression uses just one input why not using it by default) and especially it bothers me (as user) that if I don't select it then I get error messages about missing parameters that are listed as optional.

**Comment by AlisterH** [comment] 2019-06-03 20:58
> before you got those errors even when selecting the "reference layer"

Well, I don't get them in the current release, and now you are saying you don't in master, so it is working as intended; the original issue appears to be fixed.

**Comment by AlisterH** [comment] 2019-06-04 08:19
> It still baffles me why is needed to choose "that" reference layer (if the expression uses just one input why not using it by default) 

Yes, even if there is more than one input, it would be nice if it tried to use the values for the first layer, or even the intersection of all the layers.

**Comment by gioman** [comment] 2019-06-04 08:51
> Well, I don't get them in the current release, and now you are saying you don't in master, so it is working as intended; the original issue appears to be fixed.

yes, but then needs to be backported to ltr.

**Comment by alexbruy** [comment] 2019-09-15 09:00
Can we close this? As far as I can see now more detailed messages shown.

**Comment by gioman** [comment] 2019-09-17 15:31
> Can we close this? As far as I can see now more detailed messages shown in master and 3.4

yes

**Closed by gioman** 2019-09-17 15:31 UTC
Labels: Bug, Feedback, Processing
