### ISSUE TITLE
Missing bold and italic icons in text format dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#31519] opened 2019-09-01 23:06 UTC
See the following screenshot no bold nor italic icons under style while their data-defined buttons is shown.
![image](https://user-images.githubusercontent.com/7983394/64083285-8758cc00-cd1d-11e9-934c-7d93fae5b5f4.png)

QGIS version: 3.9.0-Master 0c906bf9d90e4aa5a6d934530c8876ae09b7c3fc
Ubuntu 18.04.3 LTS

**Comment by nyalldawson** [comment] 2019-09-02 08:35
Is this a duplicate of #27357?

**Comment by DelazJ** [comment] 2019-09-02 10:22
No. It's just a GUI issue: no icons shown next to their DD buttons. I propose a fix at #31520

**Closed** 2019-09-06 00:28 UTC
Labels: Bug
