### ISSUE TITLE
Intersection function returns wrong result if no overlap 

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#38480] opened 2020-08-28 01:42 UTC
The expression `geom_to_wkt(intersection( geom_from_wkt( 'LINESTRING(3 3, 4 4, 5 5)' ), geom_from_wkt( 'POINT(2 2)' )) )` returns `POINT(0 0)` which is not part of any of the input features

QGIS version | 3.15.0-Master | QGIS code revision | 4e0f64f40a
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Ubuntu 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | db_manager; MetaSearch; processing

**Comment by pigreco** [comment] 2020-08-28 09:01
## OSGeo4W64 win 10

![image](https://user-images.githubusercontent.com/7631137/91542000-75ecd480-e91d-11ea-87cd-7dc3bdb091f5.png)

![image](https://user-images.githubusercontent.com/7631137/91542070-90bf4900-e91d-11ea-856b-880e29e6ae89.png)

The expression `geom_to_wkt(intersection( geom_from_wkt( 'LINESTRING(3 3, 4 4, 5 5)' ), geom_from_wkt( 'POINT(2 2)' )) ) ` return `'Point EMPTY'`

**Comment by DelazJ** [comment] 2020-08-28 09:19
![image](https://user-images.githubusercontent.com/7983394/91544388-f3b1df80-e91f-11ea-97c7-a3c455f05bc5.png)


Version de QGIS | 3.10.7-A Coruña | Révision du code | 7b4ca4c8d0
-- | -- | -- | --
Compilé avec Qt | 5.12.3 | Utilisant Qt | 5.12.3
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.2 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compilé avec SQLite | 3.28.0 | Fonctionne avec SQLite | 3.28.0
Version du client PostgreSQL | 11.3 | Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.1
Compilé avec PROJ | 5.2.0 | Fonctionne avec PROJ | Rel. 5.2.0, September 15th, 2018
Version de l'OS | macOS 10.15
Extensions Python actives | SpreadsheetLayers; gban; QBano; refFunctions; qfieldsync; finddataset; OSMDownloader; MemoryLayerSaver; MapsPrinter; StreetView; arrayplus; processing; db_manager; MetaSearch

**Comment by pigreco** [comment] 2020-08-28 09:36
![image](https://user-images.githubusercontent.com/7631137/91546400-a97e2d80-e922-11ea-9328-3f0b440e5da5.png)

**Comment by gioman** [comment] 2020-08-29 17:21
I can confirm @DelazJ observation, but only on Linux, not on Windows (both with LTR or master).

**Comment by uclaros** [comment] 2020-08-31 13:16
`geom_to_wkt(intersection( geom_from_wkt( 'LINESTRING(3 3, 4 4, 5 5)' ), geom_from_wkt( 'POINT(2 2)' )) )` normally returns `'Point EMPTY'` for me.


QGIS version | 3.15.0-Master | QGIS code revision | df2a311782
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.3 | Running against SQLite | 3.32.3
PostgreSQL Client Version | 12.3 (Debian 12.3-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.1.0 | Running against PROJ | Rel. 7.1.0, August 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | coordinate_capture

**Comment by nyalldawson** [comment] 2020-08-31 23:05
This is expected with 3.10. It's since been fixed, but the changes are WAY WAY WAY too intrusive to permit backporting the fix.

**Comment by gioman** [comment] 2020-09-01 07:41
> This is expected with 3.10

@nyalldawson not sure what do you mean, the wrong result seems to be returned also on master. Or maybe I'm just not understanding the issue.

**Comment by nyalldawson** [comment] 2020-09-01 22:40
@gioman I don't see this on master

**Comment by gioman** [comment] 2020-09-02 00:07
> @gioman I don't see this on master

I do on Linux as also @DelazJ

**Comment by nyalldawson** [comment] 2020-09-02 00:16
It's probably GEOS version related. From what I see above it's seen in GEOS 3.8.0 but not 3.8.1 ?

**Comment by gioman** [comment] 2020-09-02 00:18
> It's probably GEOS version related. From what I see above it's seen in GEOS 3.8.0 but not 3.8.1 ?

good catch, so we should close this?

**Comment by nyalldawson** [comment] 2020-09-02 00:19
I suspect it was https://trac.osgeo.org/geos/ticket/1001 -- so yes, let's close as upstream issue

**Closed** 2020-09-02 00:22 UTC
Labels: Bug, Linux
