### ISSUE TITLE
MySQL connection fails

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28383] opened 2018-11-20 13:15 UTC
Author Name: **steve smith** (steve smith)
Original Redmine Issue: [20563](https://issues.qgis.org/issues/20563)
Affected QGIS version: 3.4.1
Redmine category:data_provider

---
When connecting to Mysql(v 5.7.22 and v 8 ) from QGIS(3.4.1) no features are visible unless a filter is applied to the layer (eg select * from geo_polys).
Then the layer cannot be edited because of the active filter.

---

Related issue(s): #29241 (relates)
Redmine related issue(s): [21424](https://issues.qgis.org/issues/21424)

---

**Comment by xs2ahmed** [comment] 2019-11-02 21:34
I can confirm I can also reproduce this issue on windows 8.1 64 bit.  I installed QGIS 3.10 64 bit and issue can be seen in that as well, I was loading just POINTS from mysql server version 5.7.28. The issue is not a connection issue as the title is misleading, the issue is that QGIS can not render the geometry imported from mysql. I also made a post here on stackexchange about the issue https://gis.stackexchange.com/questions/340548/qgis-is-not-showing-rendering-points-that-are-present-in-mysql-server

**Comment by jgrocha** [comment] 2022-12-14 12:10
This issue is quite old. I'll closed it, since it has no details about the issue.
@bierdosenhalter can you please open a new issue with details about your MySQL connection problem? Please provide enough information to reproduce the problem.

**Closed by jgrocha** 2022-12-14 12:10 UTC
Labels: Data Provider, Bug

**Comment by sinki-blau** [comment] 2023-05-10 09:25
I also have the exact problem. basically when i import the vector layer from MySQL, it is imported successfully but then it could not be rendered on the map. 
When i create a new layer from the SQL connection, points could be shown. 
It could be a rendering issue
