### ISSUE TITLE
QGIS Crashes on exit

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29701] opened 2019-04-19 08:17 UTC
Author Name: **Thomas Koski** (Thomas Koski)
Original Redmine Issue: [21886](https://issues.qgis.org/issues/21886)
Affected QGIS version: 3.4.4
Redmine category:unknown

---
QGIS 3.4 and 3.6 crash 80+% of the time when exiting.  I have tried closing projects and then exiting, which permits the 20% success rate.
The Copy Report button on the crash report window is non-functional.  Thanks.

---

- [QGIS Crash report.txt](https://issues.qgis.org/attachments/download/14822/QGIS%20Crash%20report.txt) (Thomas Koski)

**Comment by nirvn** [comment] 2019-09-14 08:40
Duplicate of #28104

**Closed by nirvn** 2019-09-14 08:40 UTC
Labels: Bug, Crash/Data Corruption, Feedback
