### ISSUE TITLE
Running model freezes QGIS

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#45685] opened 2021-10-27 09:06 UTC
### What is the bug or the crash?

While testing for https://github.com/qgis/QGIS/issues/45676

I discovered that (at least) with the attached project/data

https://github.com/qgis/QGIS/files/7419765/contourtest.zip

and the attached model

https://github.com/qgis/QGIS/files/7424186/contours_from_text_dem.zip

running the model on QGIS 3.22/master (on Windows) leads to a complete freeze. The model runs fine on 3.16.12.

Not sure if is related or not but on a new QGIS profile on 3.22/master, "add model to toolbox" won't result in the model being added to Processing, not even after a restart (works fine on 3.16.12).

### Steps to reproduce the issue

See above.

### Versions

3.22 and master from osgeo4w on Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Due to the seriousness of this bug (if confirmed) I would appreciate if others can check so to exclude a local issue.

**Comment by nyalldawson** [comment] 2021-11-03 00:35
see https://github.com/qgis/QGIS/pull/45128#issuecomment-958529173 -- caused by the update to the sip library

**Comment by nicogodet** [comment] 2021-11-04 07:29
Fixed in OSGeo4W v2 3.22.0-4 and 3.16.12-4

**Closed** 2021-12-13 22:32 UTC
Labels: Processing, Regression, High Priority, Bug
