### ISSUE TITLE
Exporting print layout does not preserve layer blending mode.

### ISSUE THREAD

**Issue by jeremyferris** [qgis/QGIS#58810] opened 2024-09-20 01:24 UTC
### What is the bug or the crash?

In my map and print layout, I have a base DEM set to hillshade and a clipped DEM with pseudocolor and blending mode set to 'multiply' which results in this:
![Canyon-Park-Elevation-Screenshot](https://github.com/user-attachments/assets/c01a49bf-8fdc-42e4-8b38-0dfe7771a5e7)

When I export this, however, the pseudocolor layer does not let the hillshade show through:
![Elevation-Map_0001](https://github.com/user-attachments/assets/0613cda6-b44e-49df-8e94-e2089b6f7a09)

### Steps to reproduce the issue

This behavior has been observed in the past, so I am not sure that it is restricted to rasters, however, to reproduce:

1. Import a DEM or other raster into a project.
2. Either clip that raster or create another layer with the same raster.
3. Set the bottom raster to hillshade
4. set the top layer to pseudocolor and select 'multiply' or 'burn' for the layer blending mode.
5. Create a print layout of the map.
6. Export the map to an image, pdf, etc.
7. Notice that the print does not match the map styling

### Versions

QGIS version
3.38.2-Grenoble
QGIS code revision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
document_management_system
0.3.3
processing_saga_nextgen
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by mblesius** [comment] 2024-09-20 07:42
Are you using label masking for the contour lines? If so, this might be a duplicate of #49488, a known issue with label masking and blend modes.

**Comment by jeremyferris** [comment] 2024-09-20 14:15
I am. You are correct, this seems to be the same issue, thanks for the link. I disabled the mask and the print worked fine. 

Workaround is to use Buffers it is for this type of topo map for now instead of masks.

**Comment by DelazJ** [comment] 2024-09-21 04:54
Duplicate of #49488

**Closed by DelazJ** 2024-09-21 04:54 UTC
Labels: Feedback, Bug, Print Layouts
