### ISSUE TITLE
Crash on closing

### ISSUE THREAD

**Issue by ByronGrant** [qgis/QGIS#30207] opened 2019-06-14 07:10 UTC
h2. User Feedback

Program Crash when closing QGIS 3.4.8

h2. Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.8-Madeira
QGIS code revision: commit:04ee8e0761
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gioman** [comment] 2019-06-14 08:27
Please try with a new/clean qgis profile, no 3rd party plugins installed.

**Comment by Evanilton** [comment] 2019-06-17 16:49
Hi

Same happened to me

Here is the report

h2. User Feedback

I saved a temporary layer and then closed the project. After saving the project, the message saying QGIS crashed appeared

h2. Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63


*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 3.4.8-Madeira
QGIS code revision: commit:04ee8e0761
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

**Comment by jef-n** [comment] 2019-06-17 18:21
Duplicate of #28104

**Closed by jef-n** 2019-06-17 18:21 UTC
Labels: Bug, Crash/Data Corruption, Feedback, High Priority
