### ISSUE TITLE
qgsXYZTilesConnections version="1.0" remove fails

### ISSUE THREAD

**Issue by namotec** [qgis/QGIS#56506] opened 2024-02-23 23:11 UTC
### What is the bug or the crash?

Server services for WMS/WMTS, Vector Tiles and XYZ Tiles can be added via the browser window. Services can be removed via an entry using the right mouse button with "Remove the connection". As a result, the entries under [qgis] and [connections] in the QGIS3.ini are removed (UX: /home/$USER/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini).

It is possible to load a list of server services from an XML file. In the example, 15 entries with ows\items\WMS\connections\items\* are made in QGIS3.ini under [connections].

The error occurs when the entries are to be deleted again. Referer relics remain in the QGIS3.ini file that can only be removed manually.

### Steps to reproduce the issue

XML test example:

```
<!DOCTYPE connections>
<qgsWMSConnections version="1.0">
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="01.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="02.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="03.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="04.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="05.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="06.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="07.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="08.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="09.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="10.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="11.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="12.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="13.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="14.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
    <wms invertAxisOrientation="0" password="" smoothPixmapTransform="0" ignoreGetFeatureInfoURI="0" url="http://localhost:81/cgi-bin/hello-world/qgis_mapserv.fcgi?map=/home/chris/sample.qgz" dpiMode="7" ignoreGetMapURI="0" username="" name="15.ber24.hello_world.Musterprojekt" ignoreAxisOrientation="0"/>
</qgsWMSConnections>
```

[1.WMS&WMTS.Dienste (dummy).xml.zip](https://github.com/qgis/QGIS/files/14390788/1.WMS.WMTS.Dienste.dummy.xml.zip)

### Versions
The bug still exists in 3.36.0-Maidenhead.

<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.36.0-Maidenhead | QGIS-Codezweig | Release 3.36
-- | -- | -- | --
Qt-Version | 5.15.8
Python-Version | 3.12.2
GDAL-Version | 3.8.4
PROJ-Version | 9.3.1
EPSG-Registraturdatenbankversion | v10.098 (2023-11-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | LMDE 5 (elsie)
  |   |   |  
Aktive Python-Erweiterungen
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS-Version
3.36.0-Maidenhead
QGIS-Codezweig
[Release 3.36](https://github.com/qgis/QGIS/tree/release-3_36)
Qt-Version
5.15.8
Python-Version
3.12.2
GDAL-Version
3.8.4
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
LMDE 5 (elsie)

Aktive Python-Erweiterungen
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.34.3-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.12.2
Compiled against GDAL/OGR | 3.8.3 | Running against GDAL/OGR | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | LMDE 5 (elsie)
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS version
3.34.3-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.8
Python version
3.12.2
Compiled against GDAL/OGR
3.8.3
Running against GDAL/OGR
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
LMDE 5 (elsie)

Active Python plugins
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

low priority.

**Comment by pathmapper** [comment] 2024-02-24 14:00
sounds like a duplicate of https://github.com/qgis/QGIS/issues/53321#issuecomment-1817761926

**Comment by namotec** [comment] 2024-02-24 15:56
@pathmapper is right!

**Closed** 2024-02-29 19:18 UTC
Labels: Bug
