### ISSUE TITLE
Qgis crashing after editing vertex *Crash ID*: 150a74d9327ce5a4ceba5df0b1c73c21f96e4dec

### ISSUE THREAD

**Issue by Nikki-kuromi** [qgis/QGIS#32224] opened 2019-10-12 10:28 UTC
## User Feedback

Usually happens when exit from vertex editing

## Report Details

*Crash ID*: 150a74d9327ce5a4ceba5df0b1c73c21f96e4dec

*Stack Trace*
<pre>
QList<QItemSelectionRange>::size :
QAbstractTableModel::index :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QgisApp::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::scrollRect :
QWidgetPrivate::invalidateBuffer_resizeHelper :
QWidget::repaint :
QWidget::repaint :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.11-Madeira
QGIS code revision: 9a8a6d4687
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18362

**Comment by roya0045** [comment] 2019-10-12 11:27
Just to validate, when you are editing the vertex, you have the attribute table open?

**Comment by Nikki-kuromi** [comment] 2019-10-12 11:30
I think yes

**Comment by gioman** [comment] 2019-10-12 11:50
> I think yes

Please try with a new/clean QGIS profile, no 3rd party plugins installed.

**Comment by Nikki-kuromi** [comment] 2019-10-12 11:56
Ok thank you =) i try to remove all 3rd party plugins

**Comment by roya0045** [comment] 2019-10-12 12:02
What was the format of the layer (shp, gpkg, mssql,postgis,etc)?

**Comment by Nikki-kuromi** [comment] 2019-10-12 12:05
there are many .shp, is not important which one i'm using, on the other side i think they are not the best ones because origially they were from a dwg

**Comment by nirvn** [comment] 2019-10-12 13:08
If my memory isn't wrong, I think we had a similar report recently, caused by a plugin.

**Comment by gioman** [comment] 2019-10-13 19:16
> i try to remove all 3rd party plugins

best way it to try with a new QGIS profile. If it persist attach the data and describe the exact steps to replicate.

**Comment by uclaros** [comment] 2019-10-17 11:13
I had similar issues with the vertex tool, it usually involved the vertex editor panel. The vertex tool and vertex editor panel need some lovin as they can crash QGIS in more ways, like when selecting different layers when vertex editor is active.

**Comment by 3nids** [comment] 2019-11-07 12:11
fixed by #32703

**Closed by 3nids** 2019-11-07 12:11 UTC
Labels: Bug, Feedback
