### ISSUE TITLE
Slow opening of a project due to print layouts

### ISSUE THREAD

**Issue by kitzberdo** [qgis/QGIS#51233] opened 2022-12-15 08:14 UTC
### What is the bug or the crash?

Hello,
I have a project with several (currently 90) saved layouts. The project opens very slowly and often stops responding. It also takes a very long time to save.
I have already tried various possible solutions and have noticed that the project loads quickly when I have deleted all layouts. The .qgz-files differ about 7.5 MB in size.
Removing layers, creating a new profile etc had made no difference to the loading speed.
Is there any way to prevent loading of layouts at program startup or are there other ways to fix this problem?
Thanks!

Edit:
In the Windows Task Manager, I can't see a particularly high load on my computer when I start QGIS. The RAM usage was about 5 GB (total available memory is 31 GB) and also the CPU does not show a particularly high load.
### Steps to reproduce the issue

Create print layouts with different styles, contents etc.

### Versions

QGIS-Version
3.28.1-Firenze
QGIS-Codeversion
fde3b8fbb8
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.0
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009  (Actually Win 11 22H2)

Aktive Python-Erweiterungen
AustrianElevation
2.0
CalculateGeometry
0.6.8
DigitizingTools
1.5.1
eu_mapper
0.1
Mergin
2022.6
mmqgis
2021.9.10
PluginLoadTimes
3.0.1
qfieldsync
v4.2.0
qgis-plugin-findreplace-main
1
spline
0.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment] 2022-12-15 12:59
Not sure how this is a bug.

**Comment by kitzberdo** [comment] 2022-12-15 13:42
> Not sure how this is a bug.

I called it a bug because I don't think it's normal behavior for a program to stop responding.

**Comment by roya0045** [comment] 2022-12-15 14:27
There might be a bottleneck sure, now without having access to that project, it's hard to guess if the issue is in your layouts or QGIS. The site of the project means that you have 8mb of compressed settings to unpack and generate to load back your things, which is fairly large.

**Comment by kitzberdo** [comment] 2022-12-15 14:44
Okay, then it would be good to know where the bottleneck is and what a possible workaround would be.
Unfortunately I can't reduce the number of layouts without compromising my work.

**Comment by unacomn** [comment] 2023-01-06 08:01
Have run into the same issue.
It's worth noting that it wasn't present in QGIS 3.16. No matter how many layouts are present, in 3.16 it works normally, as opposed to later versions. It also only seems to happen on Windows, it doesn't happen on Linux for me.
There's also a noticeable slowness, followed by a "not responding" prompt when switching any kind of symbology.  I tried reporting it last year, but I don't think I explained the issue properly. I even made a sample project with the appropriate data.
[Issue.zip](https://github.com/qgis/QGIS/files/10358529/Issue.zip)

**Comment by DelazJ** [comment] 2023-01-12 10:50
> Is it possible to force QGIS not loading the Layouts while opening the project? or somehow make it faster?

@fischerteamplan You can try running the code sample at https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/loadproject.html#using-flags-to-speed-up-things and replacing FlagDontResolveLayers with FlagDontLoadLayouts. what is unclear to me is whether the print layouts are just not loaded at project read time or won't be available in the session at all. Anyway worth a try.

@unacomn Do you have issues with the attached file? I can't see any issue with your file, in 3.22. It quite loads quickly.

https://user-images.githubusercontent.com/7983394/212046775-c1be4902-e36e-4929-858a-b6088dbbed81.mov

**Comment by fischerteamplan** [comment] 2023-01-12 14:36
> @fischerteamplan You can try running the code sample at https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/loadproject.html#using-flags-to-speed-up-things and replacing FlagDontResolveLayers with FlagDontLoadLayouts. what is unclear to me is whether the print layouts are just not loaded at project read time or won't be available in the session at all. Anyway worth a try.

@DelazJ Thank you, but no idea how to do what you explained (have some idea from programming, but not in QGIS environment). I'd appreciate more explamations

**Comment by unacomn** [comment] 2023-01-12 18:46
@DelazJ I'm not certain that the problem shows up on MacOS, that seems to be what you're using. It's not present in Linux either. Though, when changing symbols it does seem to hang a bit as well on your end as well. This is a "lite" version of the problem, if you will, it gets worse if you have more layouts.

**Comment by nyalldawson** [comment] 2023-01-13 00:14
You should open the "Developer/Debugging tools" panel (by hitting F12), and check the Profiler tab - under the "Project Load" category. That will give detailed debugging information about exactly what's causing the slow project layout loading.

**Comment by unacomn** [comment] 2023-01-13 06:34
> You should open the "Developer/Debugging tools" panel (by hitting F12), and check the Profiler tab - under the "Project Load" category. That will give detailed debugging information about exactly what's causing the slow project layout loading.

I had no clue that feature existed in QGIS. It is very useful. And it confirms exactly what I was suspecting. The issue seems to be the Legend component of a layout. It makes sense, since this was the component of layouts that usually was the most slow to respond to changes of symbology. Below you'll see to comparisons of how long it takes to load the same project (this is a production project that I can not share) on both QGIS 2.16 and QGIS 2.28.

![profiling](https://user-images.githubusercontent.com/26759956/212252479-1971e4c2-efb8-4a93-a381-cfab349c5041.png)

Delving further, you can see that the culprit is the Legend component of each layout. It loads 9 to 10 times slower than it did on 3.16. Something changed since version 3.20 in QGIS in the way that the Legend component is handled, at least on Windows 10.

![profiling_legend](https://user-images.githubusercontent.com/26759956/212253214-7ce3519c-e97e-4dbc-b458-6bb3ec47a1a6.png)

**Comment by andreasneumann** [comment] 2023-01-13 07:06
@unacomm - this should probably read 3.16 and 3.28 in your above statements and screenshots - since the debugging tool did not exist in QGIS 2.x

**Comment by kitzberdo** [comment] 2023-01-13 07:13
Same story with me - the loading of the legend is the slow part.
Version 3.28.2:
![image](https://user-images.githubusercontent.com/120191895/212259501-c734ba05-24d5-447a-b13b-ab09bc18fc79.png)

Version 3.16.16:
![image](https://user-images.githubusercontent.com/120191895/212259258-77d76e53-9a24-40d2-8bd4-05025328d502.png)

**Comment by kitzberdo** [comment] 2023-01-13 07:15
> The loading bar gets actually very quickly to 100%, but then remains loading (somehow freezes).

Yeah, I have the same experience

**Comment by fischerteamplan** [comment] 2023-01-13 09:47
> You should open the "Developer/Debugging tools" panel (by hitting F12), and check the Profiler tab - under the "Project Load" category. That will give detailed debugging information about exactly what's causing the slow project layout loading.

thanks. The cause is the legend (in both QGIS 3.22 and 3.28.2)

3.22.10
![image](https://user-images.githubusercontent.com/99815485/212289428-3b0b7893-0965-47fb-a275-e1f8126cdf84.png)

3.28.2
![image](https://user-images.githubusercontent.com/99815485/212289539-a38be1ea-8bb5-48f4-a78e-c269b0a53829.png)

**Comment by nyalldawson** [comment] 2023-01-13 09:51
@fischerteamplan 

Do you have the "filter by map" option enabled on your legend?

**Comment by kitzberdo** [comment] 2023-01-13 09:55
> Do you have the "filter by map" option enabled on your legend?

@nyalldawson at least I have this option enabled

**Comment by fischerteamplan** [comment] 2023-01-13 13:45
> @fischerteamplan
> 
> Do you have the "filter by map" option enabled on your legend?

yes! for that problem (slow Layout View due to filtered legend), found still no solution. https://github.com/qgis/QGIS/issues/51452

**Comment by fischerteamplan** [comment] 2023-01-13 14:15
> > Is it possible to force QGIS not loading the Layouts while opening the project? or somehow make it faster?
> 
> @fischerteamplan You can try running the code sample at https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/loadproject.html#using-flags-to-speed-up-things and replacing FlagDontResolveLayers with FlagDontLoadLayouts. what is unclear to me is whether the print layouts are just not loaded at project read time or won't be available in the session at all. Anyway worth a try.
> 
> @unacomn Do you have issues with the attached file? I can't see any issue with your file, in 3.22. It quite loads quickly.
> 
>  Enregistrement.de.l.ecran.2023-01-12.a.11.35.46.mov

thanks, I see in the "Debugging/Developement Tool" that by running this code, QGIS skip loading Layouts (screenshot attached). But no Project gets oppened! I'd appreciate more explanation.

![image](https://user-images.githubusercontent.com/99815485/212340442-38fff0e7-7275-4efe-aae2-cb75e920b4dc.png)

**Comment by kitzberdo** [comment] 2023-01-30 07:03
I just installed 3.28.3 and 3.22.15. Both versions show (nearly) the same results.
3.28.3
![image](https://user-images.githubusercontent.com/120191895/215408190-3c5a8b09-49cc-4c72-8ce7-2e2a72906bfb.png)

3.22.15
![image](https://user-images.githubusercontent.com/120191895/215409454-8c6c6ad7-f6c8-4072-b957-c96202545616.png)

Is there anything I/we can do to trace the problem? Unfortunately I can't use Version 3.16(.16) because when I tried there were some rendering errors.

**Comment by unacomn** [comment] 2023-01-30 17:11
> I just installed 3.28.3 and 3.22.15. Both versions show (nearly) the same results. 3.28.3 ![image](https://user-images.githubusercontent.com/120191895/215408190-3c5a8b09-49cc-4c72-8ce7-2e2a72906bfb.png)
> 
> 3.22.15 ![image](https://user-images.githubusercontent.com/120191895/215409454-8c6c6ad7-f6c8-4072-b957-c96202545616.png)
> 
> Is there anything I/we can do to trace the problem? Unfortunately I can't use Version 3.16(.16) because when I tried there were some rendering errors.

I've gone back and checked more versions of QGIS, since in production I jumped from 3.16 to 3.22. I can confirm that 3.20RC does not have this issue. I don't have the time at the moment to check if the problem was introduced in one of the minor revisions to 3.20 or if it happened in 3.22 directly. 
If it helps, try 3.20, maybe it doesn't have the problems you're encountering with 3.16, at least until we can get the issue sorted out in a newer version of QGIS.

**Comment by kitzberdo** [comment] 2023-01-31 06:16
@unacomn Thank you very much, I'll give 3.20 a try ;)

**Comment by unacomn** [comment] 2023-01-31 07:44
> @unacomn Thank you very much, I'll give 3.20 a try
> 
> Edit: 3.20.0 as well as 3.20.3 are much faster then 3.22
> 
> 3.20.3: ![image](https://user-images.githubusercontent.com/120191895/215696813-b9055a45-052a-434f-a3a8-f6b0f7fd1b5e.png)

Awesome. Now e just have to figure out what happened between 3.20,3 and 3.22 to cause the legend loading to behave like that.

**Comment by nyalldawson** [comment] 2023-02-01 00:40
Can someone post a sample project here so that I can diagnose?

**Comment by unacomn** [comment] 2023-02-01 05:00
> Can someone post a sample project here so that I can diagnose?
Yes, here you are. It's a project with some points, lines and polygons. You'll notice the difference when loading the project and especially when changing symbology.

[Issue.zip](https://github.com/qgis/QGIS/files/10553482/Issue.zip)

**Comment by nyalldawson** [comment] 2023-02-01 05:29
Thanks @unacomn !

Could you also send a screencast showing how you trigger the slowdown?

**Comment by unacomn** [comment] 2023-02-01 08:46
> Thanks @unacomn !
> 
> Could you also send a screencast showing how you trigger the slowdown?


Hi, I posted a comparisson earlier in the thread. 
https://github.com/qgis/QGIS/issues/51233#issuecomment-1380859353

Note, for some reason it doesn't happen on Linux. On Linux it loads normally and there isn't a problem changing the symbology. On Windows, loading just that sample data takes 2.1 seconds, as opposed to 0.4 seconds on Linux.

**Comment by fischerteamplan** [comment] 2023-02-20 18:35
> The QGIS project highly values your report and would love to see it addressed. However, this issue has been left in feedback mode for the last 14 days and is being automatically marked as "stale". If you would like to continue with this issue, please provide any missing information or answer any open questions. If you could resolve the issue yourself meanwhile, please leave a note for future readers with the same problem and close the issue. In case you should have any uncertainty, please leave a comment and we will be happy to help you proceed with this issue. If there is no further activity on this issue, it will be closed in a week.

as far as I know @nyalldawson is on it

**Comment by kitzberdo** [comment] 2023-03-06 07:10
I just installed QGIS Version 3.30.
Here are the results:
![image](https://user-images.githubusercontent.com/120191895/223042067-735c0853-2214-49dc-b2f2-fd308b7bc7ec.png)

So there are no major differences between Version 3.28 and 3.30.

**Comment by unacomn** [comment] 2023-03-06 15:04
> I just installed QGIS Version 3.30. Here are the results: ![image](https://user-images.githubusercontent.com/120191895/223042067-735c0853-2214-49dc-b2f2-fd308b7bc7ec.png)
> 
> So there are no major differences between Version 3.28 and 3.30.

I don't think the fix is in yet, there's one code review pending. I think the fix will also address that slowness that happens when you type in something in the legend, while the legend is on screen, which I just thought was default behavior, but it turns out it was a bug this whole time.

**Comment by kitzberdo** [comment] 2023-03-07 06:39
@unacomn If I understand correctly the first fix is already implemented in 3.30.
See: https://changelog.qgis.org/en/qgis/version/3.30/#bug-fixes-by-nyall-dawson
![image](https://user-images.githubusercontent.com/120191895/223341867-55d6f3b1-d84f-43c4-8fb1-4ddf05ea43bd.png)

**Comment by nyalldawson** [comment] 2023-03-07 06:42
@unacomn @kitzberdo 

3.30 has some optimisations, but not a complete fix. There's also https://github.com/qgis/QGIS/pull/52115 which greatly speeds up the legend content filtering, and will eventually be backported to the stable 3.30/3.28 releases.

But the "ultimate" fix is https://github.com/qgis/QGIS/pull/52103, which will NOT be backported and will be available for 3.32 only. (It's true risky/intrusive to backport)

**Comment by kitzberdo** [comment] 2023-03-07 06:45
@nyalldawson Thanks for the explanation and fixing the problem! I appreciate it very much!

**Closed** 2023-03-13 18:24 UTC
Labels: Bug

**Comment by kitzberdo** [comment] 2023-06-26 06:44
I just installed version 3.32 and noticed that the project takes just as long to load as it did with version 3.30.3.
I think this is due to the sheer amount of layouts in this project that load at startup (time to write the data to memory)? Can the behavior be changed so that individual layouts are only loaded when I want to change them?

See screenshots below:
Version 3.30.3
![Ladezeit QGIS 3-30-3](https://github.com/qgis/QGIS/assets/120191895/2f016bd8-7a54-47c9-a35c-c19c350f5309)
![Task-Manager 3-30-3](https://github.com/qgis/QGIS/assets/120191895/a5bcfbd3-80b3-4e15-a847-4432cd51e23f)

Version 3.32
![Ladezeit QGIS 3-32-0](https://github.com/qgis/QGIS/assets/120191895/efb4fd09-ac65-4a5d-8349-98bbe3ae79fd)
![Task-Manager 3-32-0](https://github.com/qgis/QGIS/assets/120191895/7887171e-2775-46f1-9eef-c6f35b2f7eb5)

Thanks for your support!

**Comment by unacomn** [comment] 2023-06-27 04:21
I can confirm that the issue hasn't been resolved yet.
Loading projects with a many of print layouts (which have legends) is very slow and changing the symbol of a layer will cause QGIS to hang for a considerable amount of time.

I guess I'll probably have to downgrade back to 3.20 or 3.16 for the foreseeable future.

**Comment by kitzberdo** [comment] 2023-07-04 14:39
@nyalldawson is it possible to re-open this issue?

**Comment by unacomn** [comment] 2023-11-06 07:29
@kitzberdo QGIS 3.34 seems to have properly resolved the issue. Here are examples of it in action on a project with 100+ layouts. Comparing to 3.16 and 3.32. While it's not AS fast as 3.16 it is blindingly speedy compared to everything from 3.22 until today.
![image](https://github.com/qgis/QGIS/assets/26759956/c9843cb0-9674-43a3-a4a2-dbab23f56f3b)
![image](https://github.com/qgis/QGIS/assets/26759956/a20ba114-a4c8-424e-8fdf-c9baeefe310a)
![image](https://github.com/qgis/QGIS/assets/26759956/c07fb587-e59a-4688-8016-c2549a367ace)

**Comment by kitzberdo** [comment] 2023-11-07 06:11
@unacomn Thank you for sharing your results. The same goes with me - 3.34 is considerably faster than previous versions.
