### ISSUE TITLE
Crashing on snapping in meter unit when layer CRS is in degrees

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#28364] opened 2018-11-19 07:20 UTC
Author Name: **rohit singh** (rohit singh)
Original Redmine Issue: [20544](https://issues.qgis.org/issues/20544)
Affected QGIS version: 3.4.1
Redmine category:digitising

---
## User Feedback

It is crashing when using snapping options with tollerance in meter unit.

Very difficult to find the invailid geometry.

## Report Details

*Crash ID*: bb4de561036fcb4116eecc8385eeacde74aa6ee5

*Stack Trace*
```
QgsRubberBand::QgsRubberBand :
QgsRubberBand::asGeometry :
QgsRubberBand::reset :
version :
QMetaObject::activate :
QDockWidget::visibilityChanged :
QDockWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::hideChildren :
QWidgetPrivate::hide_helper :
QWidget::setVisible :
QWidgetPrivate::close_helper :
QWidget::~QWidget :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

```

*QGIS Info*
QGIS Version: 3.4.1-Madeira
QGIS code revision: 383851c597
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17134

**Comment by lbartoletti** [comment] 2021-02-04 09:57
I can't reproduce the bug, but here has been a lot of evolution on these tools since the opening of this issue. Now, when you digitze a vector in wgs84 coordinate the unit is not meter but degree.

I close this ticket, don't hesitate to reopen it if there is still a problem.

**Closed by lbartoletti** 2021-02-04 09:57 UTC
Labels: Bug, Crash/Data Corruption, Digitizing
