### ISSUE TITLE
[3.11.0-Master] Snapping and node editing tool are not working. In later case, unable even to activate a node.

### ISSUE THREAD

**Issue by denchat** [qgis/QGIS#33553] opened 2019-12-30 07:20 UTC
**Describe the bug**

Entire snapping functions are not working, also can not activate a node in node editing mode.

**How to Reproduce**

1. create a polygon layer.
2. try to snap or edit a node.
3. can not snap or activate a node.

**QGIS and OS versions**
3.11.0-43 (OSGeo4W) 64-bit 578f32a9b6
Windows 10 64-bit

```
QGIS version 3.11.0-Master
Compiled against Qt 5.11.2
Compiled against GDAL/OGR 3.1.0dev
Compiled against GEOS 3.8.0-CAPI-1.13.1
Compiled against SQLite 3.29.0
PostgreSQL Client Version 11.5
QWT Version 6.1.3
Compiled against PROJ 6.3.0
OS Version Windows 10 (10.0)
QGIS code revision 578f32a9b6
Running against Qt 5.11.2
Running against GDAL/OGR 3.1.0dev
Running against SQLite 3.29.0
SpatiaLite Version 4.3.0
QScintilla2 Version 2.10.8
Running against PROJ Rel. 6.3.0, January 1st, 2020
This copy of QGIS writes debugging output.
```

**Comment by gioman** [comment] 2019-12-30 12:13
@denchat duplicate of https://github.com/qgis/QGIS/issues/32969 ?

**Comment by denchat** [comment] 2019-12-30 14:39
@gioman Yep. This is the eerily exact issue, yet completely **_crossed platform_**, may I say.

The workaround even also works in Windows though!

You may mark this a dup of #32969, if crossed platform counted.

**Closed** 2019-12-30 14:51 UTC
Labels: Bug, Feedback
