### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by chrishamby** [qgis/QGIS#31553] opened 2019-09-04 16:42 UTC
## User Feedback

was attempting to run a new algorithm in Python based on an export from Processing

## Report Details

*Crash ID*: 529c58c4805abf5110f526075e5cea5171db06f2

*Stack Trace*
<pre>
QObject::thread :
QgsLayoutMultiFrameAddItemCommand::containsChange :
is_exception_typeof :
RtlCaptureContext :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by roya0045** [comment] 2019-09-04 16:47
Could you elaborate on what is this 'new algorithm', it will be hard to provide any assistance without any additional information.

**Comment by nyalldawson** [comment] 2019-09-04 19:09
Most likely your algorithm is running in a background thread yet calling thread unsafe methods. It's not a bug in qgis, it's in your code, so I'm closing this report. Feel free to start a thread on the mailing list or on gis.stackexchange.com and share your code for assistance.

**Closed by nyalldawson** 2019-09-04 19:09 UTC
Labels: Bug, Feedback
