### ISSUE TITLE
QGIS 3.10 SAGA "Raster values to points" does not work

### ISSUE THREAD

**Issue by jmunozrjb** [qgis/QGIS#33284] opened 2019-12-08 16:59 UTC
**Describe the bug**
SAGA tool "Raster values to points" does not work on QGIS 3.10, but it works properly in 3.4.13 Madeira LTR. In 3.10.o La Coruña, instead of calling "shapes_grid" library, it tries to call "io_grid" library, but apparently it cannot find it (my guess). Attached are 3.4 and 3.10 logs.

**How to Reproduce**
Here is the test raster (prueba_raster_to_points_fishnet.txt, in ASCII format)
[prueba_raster_to_points_fishnet.txt](https://github.com/qgis/QGIS/files/3936577/prueba_raster_to_points_fishnet.txt) and the logs of the two qgis versions:
[qgis 3.4 Raster value to points log - worked.txt](https://github.com/qgis/QGIS/files/3936566/qgis.3.4.Raster.value.to.points.log.-.worked.txt)
[qgis 3.10 Raster value to points log - crashed.txt](https://github.com/qgis/QGIS/files/3936567/qgis.3.10.Raster.value.to.points.log.-.crashed.txt)

**QGIS and OS versions**
THE ONE WORKING
QGIS version 3.4.13-Madeira
QGIS code revision QGIS code revision
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 2.4.3
Running against GDAL/OGR 2.4.3
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1 
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 5.2.0
Running against PROJ Rel. 5.2.0, September 15th, 2018

THE ONE CRASHING
QGIS version 3.10.0-A Coruña
QGIS code revision 6ffa89eb3e
Compiled against Qt 5.11.2
Running against Qt 5.11.2
Compiled against GDAL/OGR 3.0.2
Running against GDAL/OGR 3.0.2
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1 
Compiled against SQLite 3.29.0
Running against SQLite 3.29.0
PostgreSQL Client Version 11.5
SpatiaLite Version 4.3.0
QWT Version 6.1.3
QScintilla2 Version 2.10.8
Compiled against PROJ 6.2.1
Running against PROJ Rel. 6.2.1, November 1st, 2019
OS Version Windows 10 (10.0)

**Additional context**

**Comment by gioman** [comment] 2019-12-08 19:18
@jmunozrjb duplicate of https://github.com/qgis/QGIS/issues/32953#issuecomment-555649562 ?

**Closed** 2020-03-02 15:55 UTC
Labels: Bug, Feedback
