### ISSUE TITLE
Crash when editing a feature from a value relation form

### ISSUE THREAD

**Issue by lperozzi** [qgis/QGIS#52034] opened 2023-02-27 10:14 UTC
### What is the bug or the crash?

QGIS 3.22 crashes when attempting to finish editing a feature using a value relation form, while the same process works without issue on version 3.16.

### Steps to reproduce the issue

[Plantage.zip](https://github.com/qgis/QGIS/files/10838494/Plantage.zip)

1. Open Plantage_322.qgz
2. Click on the feature to open the form
![image](https://user-images.githubusercontent.com/6198369/221534670-d9127338-913d-40f5-9559-baf4c9eed822.png)
3. Click on  `add line child feature`
4. Draw a new line 
![image](https://user-images.githubusercontent.com/6198369/221534775-cb7186ea-1559-450b-ae96-7b79451fa43f.png)
5. It crashs when the form is exited

### Versions

Crash ID: [d78755efec5aa492a1cb804d23673db1a38e2b94](https://github.com/qgis/QGIS/search?q=d78755efec5aa492a1cb804d23673db1a38e2b94&type=Issues)

Stack Trace

QWidget::topLevelWidget :
QgsRelationEditorWidget::mapToolDeactivated :
QObject::qt_static_metacall :
QgsMapToolAdvancedDigitizing::deactivate :
QgsMapToolCapture::deactivate :
QgsMapToolDigitizeFeature::deactivate :
QgsMapCanvas::unsetMapTool :
QgsRelationEditorWidget::unsetMapTool :
QObject::qt_static_metacall :
QgsMapToolDigitizeFeature::digitizingCompleted :
QgsMapToolDigitizeFeature::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.16-Bia?owie?a
QGIS code revision: 6f08e4d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lperozzi** [comment] 2023-02-27 13:20
Hi @agiudiceandrea . I just tried with 3.28.3 and I have the same issue.

**Comment by agiudiceandrea** [comment] 2023-02-27 15:04
Thanks @lperozzi. The provided zip files only contains the project, while the layers are missing. Could you provide the missing layers?

**Comment by lperozzi** [comment] 2023-03-01 10:06
On my side, it crashes with the 3.28.2

**Comment by agiudiceandrea** [comment] 2023-03-01 15:58
@elpaso the issue does occur on Windows using QGIS 3.28.3 and the latest QGIS 3.28 nightly build at [05eefc953b2](https://github.com/qgis/QGIS/commit/05eefc953b2) (from OSGeo4W), while it doesn't occur on the same system using the latest available QGIS 3.29.0-Master (MinGW64 build). So, it seems the issue is fixed in master but not in the release-3_28 branch?

**Comment by alexbruy** [comment] 2023-11-03 14:13
Can't reproduce with the latest master (36c53ea14ced0975ecde67027f8468770ebcd67d).

**Closed** 2024-03-18 11:50 UTC
Labels: Forms, Regression, Bug, Crash/Data Corruption, Relations, Widgets
