### ISSUE TITLE
Wrong size of legend symbols when using Geometry generator symbology

### ISSUE THREAD

**Issue by VxTedxV** [qgis/QGIS#36037] opened 2020-04-27 16:20 UTC
I was not able to reopen a closed ticket : #22638

This issue remains in QGis 3.12.1 !

Tested with line geometry : in legend, the line is half screen long before we can read the label !

**Comment by gioman** [comment] 2021-06-14 21:26
Duplicate of https://github.com/qgis/QGIS/issues/33755

**Closed by gioman** 2021-06-14 21:26 UTC
Labels: Bug, Map and Legend
