### ISSUE TITLE
OpenCL Support not detected in mixed CPU/GPU system

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#30931] opened 2019-07-25 15:51 UTC
**Describe the bug**
OpenCL compatible hardware is not detected by QGIS 3.8.1 x64 under Windows 10 1903 x64, despite the presence of two compatible OpenCL hardwares/drivers.

Hardware:
[Intel i7-7800X](https://ark.intel.com/content/www/us/en/ark/products/123589/intel-core-i7-7800x-x-series-processor-8-25m-cache-up-to-4-00-ghz.html)
[AMD Radeon Pro WX 5100](https://www.amd.com/en/products/professional-graphics/radeon-pro-wx-5100)

Drivers:
[Intel CPU Runtime for OpenCL Applications 18.1](https://software.intel.com/en-us/articles/opencl-drivers)
[AMD Radeon Pro Software for Enterprise 19.Q2.1](https://www.amd.com/en/support/professional-graphics/radeon-pro/radeon-pro-wx-x100-series/radeon-pro-wx-5100)
[Vulkan Runtime 1.1.108.0](https://vulkan.lunarg.com/sdk/home#windows)

**How to Reproduce**
Attempt to enable QGIS OpenCL Support from the Settings GUI. Receive this error:
2019-07-25T11:25:41     CRITICAL    Error CL_PLATFORM_NOT_FOUND_KHR initializing OpenCL device: empty

**QGIS and OS versions**

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |  

**Additional context**
![image](https://user-images.githubusercontent.com/19295950/61887885-79b75780-aed0-11e9-97bf-ae24b1bae0a4.png)
QGIS Settings Dialog demonstrating not finding any OpenCL devices

![image](https://user-images.githubusercontent.com/19295950/61888324-517c2880-aed1-11e9-9066-8924489dc2d0.png)
[GPU-Z](https://www.techpowerup.com/download/techpowerup-gpu-z/) Demonstrating working install of AMD OpenCL on system

![image](https://user-images.githubusercontent.com/19295950/61888513-9acc7800-aed1-11e9-9b93-5fa6379e011d.png)
[LibreOffice](https://www.libreoffice.org/download/download/) demonstrating working OpenCL on system

![image](https://user-images.githubusercontent.com/19295950/61888903-6907e100-aed2-11e9-888b-e535c35ee325.png)
[OpenCL Test Tool](https://chapmanworld.com/2019/05/18/opencl-test-tool/) demonstrating both AMD GPU and Intel CPU OpenCL Runtimes are functional and visible.

**Comment by elpaso** [comment] 2019-07-25 16:23
I guess you tried to check the box [ ] enable opencl acceleration, did you?
Due to the fact that it can crash QGIS, the device detection does not take place if the user does not check that checkbox.

**Comment by Saijin-Naib** [comment] 2019-07-25 16:27
Yes, I toggled the check box to enable OpenCL Support. The error message does not populate the bottom part of the window until after you attempt to toggle the check box to enable support.

Is there another/better place for me to be pulling log information from?

**Comment by elpaso** [comment] 2019-07-25 16:55
You can paste the log on https://dpaste.de/ but  there is no way I can test and debug on your machine (even if I had the time to do that). 

There is an endless combination of hardware, drivers, OS versions etc. 
With the help of some other developers we tested a limited set of Nvidia, AMD and Intel cards and drivers on win 10 and they all worked fine, but we've also got some reports of cards not being recognized, sorry for that.

**Comment by Saijin-Naib** [comment] 2019-07-25 17:14
Understood.

I'm still not certain it is a machine issue given that every other software with OpenCL support I've tested works just fine on this machine.

Do you happen to know/remember what cards/configurations wouldn't detect in your earlier testing? Perhaps they were also mixed/multiple OpenCL Runtime/Device environments like this one and somehow the detection doesn't cope with that.

**Comment by elpaso** [comment] 2019-07-25 17:33
It wasn't me to find the undetected devices (or I would have tried to fix it: the main problem here is that I cannot reproduce the issue locally and try to debug and fix it).

There must be some list of tested devices in the previous open CL issues, but I can't find it right now, my only win 10 machine (that I don't use regularly) has an intel integrated card and it worked after installing the intel card drivers.

Anyway, I'm 100% sure that multiple card hw has been successfully tested on windows (IIRC it was a Nvidia+intel)

In any event, you should be able to see some OpenCL related messages in the QGIS logs, the detection procedure does log some debugging information when it fails.

**Comment by Saijin-Naib** [comment] 2019-07-25 18:32
I've attached the log output captured by DebugView against QGIS 3.9-nightly installed via OSGeo4W.

The log covers the launch, initialization, going to Settings, Acceleration, and then toggling OpenCL, ending with the error message generated.

I only see the one line related to OpenCL after I click the checkbox, the same error I captured above.
[BRI5783.LOG](https://github.com/qgis/QGIS/files/3432787/BRI5783.LOG)

**Comment by elpaso** [comment] 2019-07-26 06:04
I see, looks like the detection failed very early: no platform could be found.
Just to be sure, did you try with a clean user profile?

**Comment by elpaso** [comment] 2019-07-26 06:08
also, I don't know how it works on windows, but on Linux you can increase debugging output level by setting the env var `QGIS_DEBUG` to something high (e.g. `6`)

**Comment by Saijin-Naib** [comment] 2019-07-26 13:55
Log-Level 9 on a new/clean profile called DEBUG

Still just the one/same entry in the log regarding CL_PLATFORM_NOT_FOUND_KHR as the above entries. Is it even getting to the point where the code to detect the OpenCL devices is initializing fully? I'd expect to see more information than this in the log about the detection process.

[log.log](https://github.com/qgis/QGIS/files/3436032/log.log)

**Comment by carbonox-infernox** [comment] 2019-08-07 21:51
I have the same problem. Updated my Nvidia driver, checked my Intel iGPU for updates, and installed opencl-intel-cpu-runtime, and QGIS can't find any of them. My log just says:

 `CRITICAL    Error CL_OUT_OF_HOST_MEMORY initializing OpenCL device: empty`

**Comment by stelf** [comment] 2019-08-21 13:09
I can confirm this was encountered on several different systems, all Win10s with different NVidias. The GPU can either not be detected at all or is not subject to selection or when selected, is reverted to Intel's internal GPU.

**Comment by Saijin-Naib** [comment] 2019-08-21 13:19
I have two Win10 x64 Pro machines at home with QGIS 3.8.2 x64, both with the same configuration which also do not work with OpenCL/QGIS at all:
i7-6700k
GTX 1050TI OC
Both with same/latest NVIDIA drivers, both with same Intel CPU OpenCL runtime, both with latest Khronos Vulkan driver.
Both show fully supported OpenCL in GPU-Z, LibreOffice x64, and OpenCL Test (and every other tool I can find) as does my work machine I opened the ticket about.

**Comment by stelf** [comment] 2019-08-22 15:22
I'll post details reg GPUs at my side. thing is that even when the card is listed (and selected in the GUI), after restart, QGIS fails back to the Intel one. 

Tried to update one box that had the GPU listed, but would not select it with NVCleanstall which should basically get the latest driver. Upon installation QGIS did not even find the GPU.

Also tried to go to Graphics Settings and designate that this specific app should use the high performance graphics card (a WIN10 something...). No change in behavior.

I'll try to provide more insight and debug logs should anyone appreciate some.

**Comment by stelf** [comment] 2019-08-23 09:50
okay, so confirmed - GPU not shown or not working on boxes with:

* NVIDIA GeForce GTX 1050 Ti
* NVIDIA GeForce GT 730

not sure bout the benefit of offloading ot GT 370, but the TI should definitely have some nice capabilities

**Comment by elpaso** [comment] 2019-08-24 08:55
I'm working on a new approach for loading OpenLC drivers and adding more debugging messages. Unfortunately I don't have any NVidia box, but I'll provide testing binaries for you to test.

**Comment by elpaso** [comment] 2019-08-27 06:44
Unfortunately we tested the new approach but it proved to be very unstable, so for now I've added some more debugging information that will appear in the logs.

**Comment by stelf** [comment] 2019-08-27 13:03
@elpaso, have you got a custom build you would like us to run/test/log with?

**Comment by elpaso** [comment] 2019-08-28 07:06
@stelf , no but it should be in today's nightly builds, I've committed it directly to master: 
https://github.com/qgis/QGIS/commit/6567e3e6e939d03eb6b9a37d2d0d474cd4c3f024

**Comment by elpaso** [comment] 2019-08-28 07:08
For what it worth, during the Bucharest meeting we've been able to test a win10 installation with GeForce GT 730 + Intel and it was correctly recognized by QGIS. 
@jef-n might be able to provide more details about exactly which driver was installed on the machine.

**Comment by elpaso** [comment] 2019-09-13 08:43
> I'm a bit miffed that I didn't think of this sooner.

Don't be, you just beated me on time, that was what I was going to suggest to try next.

Long story:

1. In order to ship QGIS with OpenCL support we need to link to an OpenCL.dll library, that library is just a loader for the vendor provided OpenCL implementations and it is supposed to be standard and vendor-agnostic.
2. For this reason we are shipping our own version of OpenCL.dll, that library is supposed to be installed on the target system only if there is no OpenCL.dll in the system directory (@jef-n correct me if I'm wrong).
3. For some obscure reason, on some machines, our OpenCL.dll is not able to recognize and load the vendor OpenCL implementations, and this causes the issue "No OpenCL compatible devices were found on your system". In these cases, removing QGIS OpenCL.dll will help, because the vendor provided OpenCL.dll will be used instead.

So, during Bucharest HF (and before that) I tried to look at how other OS projects (libreoffice and blender) handle this problem, their solution is to use a wrapper that loads OpenCL.dll at runtime [1], but unfortunately, that wrapper is not only a bit old but it also uses the `C` API while we are using the `C++` API.

I liked that approach, we would have been able to build QGIS and ship it without linking to and providing an OpenCL.dll, delegating to the target machine the loading (at runtime) of an OpenCL.dll implementation, usually provided by the vendors.

I and @jef-n we spent a lot of time trying to use the same approach for QGIS (first by swithing to `C` API and then by adapting the C++ API to use the `clew` wrapper) but it has proven to be very unstable (crashed) and we had to abandon that approach (also because of lack of time).

I honestly don't know how to proceed now, it's hard for me to find a solutions, mainly because I have never been able to reproduce this issue on my local development machines but also because I'm not a regular windows user or a skilled windows developer (not to mention that my time is a very limited resource).

[1] https://github.com/martijnberger/clew

**Comment by elpaso** [comment] 2019-09-13 08:45
> Following Saijin-Naib's suggestion (thanks!), I deleted C:\OSGeo4W64\bin\opencl.dll
> and it started working better (both 3.8.2 and 3.9-Dev)
> 
> Now, I see all three (3) opencl devices in "options->acceleration", but **only Intel(R) HD Graphics 630 works. If I pick another option it is not retained**,
> even if this is to be found in QGIS3.ini:
> OpenClDefaultDevice=GeForce GTX 1050 Ti|NVIDIA Corporation|OpenCL 1.2 CUDA|GPU
> 

What do you mean with "it is not retained"?
Can you select that in the combo and use it?
Is it just the issue that your choice is not correctly loaded from the settings when you restart QGIS?

It looks like a different issue than the one in this ticket.

**Comment by Roburetto** [comment] 2019-09-13 09:13
"Can you select that in the combo and use it?"
I can select the other two options but apparently I can not use them. Meaning after pressing "OK", when I got back "Intel(R) HD Graphics 630" remains/is always the selected option.

"Is it just the issue that your choice is not correctly loaded from the settings when you restart QGIS?".
Regardless of having OpenClDefaultDevice=GeForce GTX 1050 Ti in QGIS3.ini,  "Intel(R) HD Graphics 630" remains/is always the selected option.

**Comment by stelf** [comment] 2019-09-13 10:53
> If I pick another option it is not retained

this 'not retained' behavior is well known and I've seen it across some systems. the devices are shown but the selection of preferred GPU is not saved/used.

_btw, when is the OpenCL employed, and what are the overall benefits for QGIS of having it (render is faster, algorithms, basically which parts of QGIS work with OpenCL...)? we make a lot of hustle but not much is known of the benefits_

**Comment by elpaso** [comment] 2019-09-13 11:46
See: https://www.itopen.it/opencl-acceleration-now-available-in-qgis/
After that article was written, opencl support was added to:
- hillshade raster renderer
- raster calculator

**Comment by jef-n** [comment] 2019-09-13 13:17
with `opencl-2.0.10-4` the opencl.dll is now removed from `%OSGEO4W_ROOT%\bin` if there is a copy in `%WINDIR%\system32`

**Comment by elpaso** [comment] 2019-09-13 17:12
@stelf for the "opencl preferred device not loaded from settings" please file a separate ticket, btw I cannot reproduce that issue. 
As I mentioned already I only have an Intel machine where I can see two devices, one for GPU and one for CPU and I'm able to store and load  them both (after a QGIS restart).

On my other machine I only have an AMD GPU so I cannot really test the switching.

Btw, I'll add another message in the logs with the name of the active device, for an easier check of what device is actually in use at the moment.

**Comment by Saijin-Naib** [comment] 2019-09-13 18:10
Personal computers:
i7-6700k
GTX 1050TI OC

![image](https://user-images.githubusercontent.com/19295950/64884600-1de79000-d630-11e9-9afd-08bc3e2ed3bf.png)

Deleting the dll gets me the nVidia OpenCL runtime, but curiously, I can't see the Intel CPU runtime on these the same as I can't see it on my work machine with the i7 and Radeon Pro.

**Comment by Roburetto** [comment] 2019-09-14 10:26
> with `opencl-2.0.10-4` the opencl.dll is now removed from `%OSGEO4W_ROOT%\bin` if there is a copy in `%WINDIR%\system32`

Just installed the dev version, no opencl.dll is to be found in C:\OSGeo4W64\bin BUT the version in C:\Windows\System32 WAS REPLACED.

Now I have to reinstall the NVIDIA Driver to get it working...

**Comment by jef-n** [comment] 2019-09-14 20:53
> > with `opencl-2.0.10-4` the opencl.dll is now removed from `%OSGEO4W_ROOT%\bin` if there is a copy in `%WINDIR%\system32`
> 
> Just installed the latest dev version. No opencl.dll is to be found in C:\OSGeo4W64\bin BUT the file with the same name in C:\Windows\System32 WAS REPLACED. Meaning, no device recognized again.

That's not new - opencl.dll was updated before (if the previously installed version was lower).

**Comment by stelf** [comment] 2019-10-07 10:36
@elpaso maybe i can arrange for remote machine with TeamViewer or similar and said GPUs available for testing, should anyone be interested. not an OpenCL expert myself, although I'm able to debug the code if I have the relevant PDBs.

**Comment by Saijin-Naib** [comment] 2019-11-19 14:40
On all three machines I have access to, GPU OpenCL is working just fine, though CPU OpenCL is not visible on any of them.

I suppose this behavior is semi-acceptable, though there might be specific configurations where CPU OpenCL might be more performant than GPU...

**Comment by elpaso** [comment] 2019-11-19 15:02
On one of my machines I can see both (intel) GPU and CPU are available, there is nothing in QGIS code that filters out CPU, I only gave priority on GPU as a default choice, but the user can select a CPU if he wants to.

**Comment by Saijin-Naib** [comment] 2019-11-19 17:27
You're right, something was up with the Intel OpenCL CPU Runtimes. Uninstsall/reinstall and reboot on all three machines resolved it being missing from QGIS.

How it got into that state? Who knows.

**Comment by Saijin-Naib** [comment] 2019-12-13 15:50
I'm not experiencing problems on mixed machines that I have access to anymore.

I think this can be closed, unless anyone else protests?

**Comment by elpaso** [comment] 2019-12-13 15:57
I don't protest :)

**Closed by elpaso** 2019-12-13 15:57 UTC
Labels: Bug
