### ISSUE TITLE
[Feature Merge Tool] Add value list when a manual input is selected by the user for relationnal values

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#37276] opened 2020-06-17 13:15 UTC
**Feature description.**
A dropdown menu would be a nice thing to have, since relationnal values are now translated in the merge tool :

![image](https://user-images.githubusercontent.com/8614223/84902419-16688200-b0ad-11ea-9608-01af138288bf.png)

**Additional context**
I would make the selection much easier for the end user.

**Comment by rnousia** [comment] 2022-09-07 13:47
Is this actually a bug? Found this issue while searching for merge tool issues as our plugin users reported that merge tool is not working well with value map fields. Just tested this with QGIS 3.26.2 so I'll try to add a bit more detailed description about the issue.

The issue is with fields having value map widget configured. It is difficult for the user to merge fields with value mapping especially when other than values from the merged features are needed as 1) the user would not know if the field has a value map and 2) even if the user remembers that it is a field with value mapping, they cannot look up the values from layer properties when the merge tool dialog is open.

Let's say there's a value map widget configured for integer field with human-readable descriptions:
![kuva](https://user-images.githubusercontent.com/12234068/188885204-c2be5dbb-758c-4e6d-b540-b871aa8664ca.png)

User wants to merge 2 features with mapped values "Green" and "Blue".

When using merge tool (and if the user doesn't realize this field has value mapping) writing manually e.g. "Blue" will result error message: "Invalid result : Could not store value 'Blue' in field of type Integer: Value "Blue" is not a number". However, in this situation (where the merged value would be from one of the features's being merged), the correct value can be selected using the merge tool's drop-down menu selecting which feature's attribute to use.

So this doesn't work (manually writing mapped value):
![kuva](https://user-images.githubusercontent.com/12234068/188893264-27651874-60b0-46b3-9176-6bdd0b3b556b.png)

But this would work (writing correct integer):
![kuva](https://user-images.githubusercontent.com/12234068/188894144-b6e9dc83-db26-4e28-93a9-78b4eb6e0452.png)

Or this would work (selecting form merge tool drop-down menu):
![kuva](https://user-images.githubusercontent.com/12234068/188887916-37fef57c-8e25-4f4e-8f64-ee1d745373ab.png)

But if the user needs to select e.g. "Teal", they would need to remember the correct integer value (which they probably don't ever see because of the value mapping) or then edit the feature afterwards to have the new value (I guess this is what our users are currently doing).

Optimally, the merge tool would have the same kind of drop-down menu in merge section that is found from attribute table when editing fields with value mapping.
![kuva](https://user-images.githubusercontent.com/12234068/188893851-e3b4e8b3-d570-4fa6-8965-219d30d2fa0c.png)

So adding this feature (value map support for merge tool) would really speed up using merge tool.

**Closed** 2023-05-23 20:19 UTC
Labels: Feature Request

**Comment by ponceta** [comment] 2023-06-05 12:05
Thank you @3nids !
