### ISSUE TITLE
Bug in the color map / legend management 

### ISSUE THREAD

**Issue by ccoulet** [qgis/QGIS#43005] opened 2021-04-28 08:51 UTC
Defining a color ramp for a project works well in 3.16 but this color ramp is no longer available when I open the project again
Defining the same color ramp in 3.18 and 3.19 doesn't produce the same result as the map is updated accordingly but not the layer selector nor in the legend.

**How to Reproduce**

1. Open a mesh layer
2. Choose the variable and load this color map [example.txt](https://github.com/qgis/QGIS/files/6390332/example.txt)
3. I obtain this result ![image](https://user-images.githubusercontent.com/16309181/116372291-905cb200-a80c-11eb-9eae-40373bbdeb14.png)
4. In the composer, the legend could be added with the right shape and color
5. Save the project
6. Close Qgis
7. Launch Qgis
8. Load the project
9. I obtain this result ![image](https://user-images.githubusercontent.com/16309181/116373647-d6664580-a80d-11eb-9cf0-e21a5365957e.png)
10. The color ramp doesn't exit and in the composer there is no legend available

I also tested in 3.18 and 3.19
at step 3 I obtain ![image](https://user-images.githubusercontent.com/16309181/116374358-7fad3b80-a80e-11eb-9f79-5f6dfe77e63d.png)
The only difference is after saving and opening again, the result stay the same...

**QGIS and OS versions**
`
Version de QGIS
3.16.4-Hannover
Révision du code
654e76b3cb
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
crayfish; 
GeometryShapes; 
gmsh; 
line_profile; 
Mascaret; 
oneatlas-qgis-plugin-1_0_1; 
pluginbuilder3; 
plugin_reloader; 
PostTelemac; 
PreCourlis; 
PreTelemac; 
profiletool; 
qgsAzimuth; 
spline; 
telemac_tools; 
db_manager; 
MetaSearch; 
processing
`

`
Version de QGIS
3.18.0-Zürich
Révision du code
bdef9fb328
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.1.4
Utilisé avec GDAL/OGR
3.1.4
Compilé avec GEOS
3.8.1-CAPI-1.13.3
Utilisé avec GEOS
3.8.1-CAPI-1.13.3
Compilé avec SQLite
3.29.0
Fonctionne avec SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.3.2
Fonctionne avec PROJ
Rel. 6.3.2, May 1st, 2020
Version de l'OS
Windows 10 (10.0)
Extensions Python actives
crayfish; 
GeometryShapes; 
gmsh; 
line_profile; 
Mascaret; 
oneatlas-qgis-plugin-1_0_1; 
pluginbuilder3; 
plugin_reloader; 
PostTelemac; 
PreCourlis; 
PreTelemac; 
profiletool; 
qgsAzimuth; 
spline; 
telemac_tools; 
db_manager; 
MetaSearch; 
processing
`
**Additional context**

**Comment by roya0045** [comment] 2021-04-28 11:52
Can you try with a more recent version of 3.18, 3.18.0 was bugged in some regards.

**Comment by ccoulet** [comment] 2021-04-28 13:18
Hi
i just updated to 3.18.2 and the result is the same.
The color ramp in the layer selector is not in agreement with the color map used in the map.

**Comment by roya0045** [comment] 2021-04-28 13:45
@ccoulet did you clear up the legend entries and reclassified the values with the new ramp?

**Comment by ccoulet** [comment] 2021-04-28 13:58
I follow exactly the step described in my first post but at step 3 I obtain the result described for 3.18

**Comment by gioman** [comment] 2021-04-28 15:36
>  The only difference is after saving and opening again, the result stay the same...

@ccoulet I'm really struggling to understand what is the bug and how to replicate it. Is it in the composer?

**Comment by roya0045** [comment] 2021-04-28 15:46
@gioman canvas, with a mesh layer.

**Comment by gioman** [comment] 2021-04-28 15:47
> @gioman canvas, with a mesh layer.

@ccoulet please attach the mesh layer.

**Comment by gioman** [comment] 2021-04-28 15:47
> @gioman canvas, with a mesh layer.

@roya0045 I still do not understand what the bug is.

**Comment by roya0045** [comment] 2021-04-28 15:49
The legend and displayed map is distinct from the one selected. I suspect this is because the old values were not cleared and reclassified.

**Comment by ccoulet** [comment] 2021-04-28 15:50
@gioman Sorry if I was not as clear as expected!
Let's try again with an exemple
Starting from this file
[f2d_pildepon.zip](https://github.com/qgis/QGIS/files/6393115/f2d_pildepon.zip)
Once unzipped, you should have a file named f2d_pildepon.slf
Open this file as a mesh layer, select the water depth and load this color map
[example2.txt](https://github.com/qgis/QGIS/files/6393146/example2.txt)
You should obtain this result
![image](https://user-images.githubusercontent.com/16309181/116433902-38dd3700-a84a-11eb-80b6-fcf871f80270.png)
You could show the difference in the color in the layer selector and in the map

**Comment by vcloarec** [comment] 2021-04-28 16:01
I can reproduce.
 It is link to the color ramp shader, not mesh layer. Same behavior with raster layer.
For 3.16, with no legend. It is a mesh layer issue that has been fixed for 3.18, and not backport. I look if it is possible to backport.

**Comment by ccoulet** [comment] 2021-04-28 16:23
@vcloarec Thanks for confirming the problem. Is there a solution for 3.18 ?

**Comment by vcloarec** [comment] 2021-04-28 16:42
@ccoulet , if you can use discrete interpolation, the legend is OK. In your text file, replace "INTERPOLATED" by "DISCRETE".

**Comment by vcloarec** [comment] 2021-04-28 16:56
for 3.16 issue, that was normally backport for 3.16.5 (https://github.com/qgis/QGIS/pull/41369), but something went wrong, the fix was not moved and fix was not merged...

**Comment by vcloarec** [comment] 2021-04-28 18:26
@ccoulet , I found an ugly workaround: after loading the text file, double click on the color of a class, change the color, change back the color... the color ramp legend is updated.

There is also the possibility to set the legend like the old one with each colors of the classification, but that was implemented only for raster, not for mesh layer... I fixed it and hope I could it backport to 3.18.

**Comment by vcloarec** [comment] 2021-04-29 03:46
All should be fixed for next release 3.16.7 and 3.18.3

**Closed** 2021-04-29 05:55 UTC
Labels: Bug, Feedback
