### ISSUE TITLE
QGIS 3.12 not handling EPSG 2957 Always defaults to EPSG 2151

### ISSUE THREAD

**Issue by sasklrm** [qgis/QGIS#35876] opened 2020-04-20 15:39 UTC
**Describe the bug**

Setting the default project to EPSG 2957 always goes back to EPSG 2151 which is the deprecated
 predecessor to 2957. Going back to QGIS 3.10 as a test shows that this does not happen in the 3.10 version. 
**How to Reproduce**

**QGIS and OS versions**

**Additional context**

![Error with EPSG 2957 in QGIS 3 12](https://user-images.githubusercontent.com/64027464/79770524-c5c1ec00-82ea-11ea-932a-e4c2db1ce508.JPG)

**Comment by gioman** [comment] 2020-04-20 15:51
@sasklrm please add sample data.

**Comment by gioman** [comment] 2020-04-20 15:51
reminds me of https://github.com/qgis/QGIS/issues/35459 not sure if they are related.

**Comment by sasklrm** [comment] 2020-04-20 17:13
I am definitely not experienced in QGIS or Github.  I read #35459. In GeoPackage it exports and imports properly. So if it is a GDAL issue then the problem remains. I am using the QGIS program which contains GDAL. So is the solution to go back to 3.10 version? The way I see it is that it is a QGIS issue.

**Comment by gioman** [comment] 2020-04-20 17:22
@sasklrm attach sample data.

**Comment by sasklrm** [comment] 2020-04-20 17:30
I don't know what data would show the issue more clearly. The feature I am testing it with is just a line or polygon with no attribute data. The data has an id column - nothing else.  I have added the project files and the information from properties

Here are the project files. There were error messages about the project files when I used the batch process to try to reproject the files to 2957. The prj files seem identical.
FROM THE 2151 FILE
PROJCS["NAD_1983_CSRS_UTM_Zone_13N",GEOGCS["GCS_North_American_1983_CSRS",DATUM["D_North_American_1983_CSRS",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-105.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]

FROM THE 2957 FILE:   SEEMS IDENTICAL
PROJCS["NAD_1983_CSRS_UTM_Zone_13N",GEOGCS["GCS_North_American_1983_CSRS",DATUM["D_North_American_1983_CSRS",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["degree minute second hemisphere",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-105.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]

This is from information in properties

The 2957 case

Name | BBC Network 1 Boundary
-- | --
Path | D:\Jobs\SaskCDA\Blackbird   Creek\QGIS for SCDA\BBC Network 1\BBC Network 1 Boundary.shp
Source | D:/Jobs/SaskCDA/Blackbird Creek/QGIS for SCDA/BBC Network 1/BBC   Network 1 Boundary.shp\|layername=BBC Network 1 Boundary
Storage | ESRI Shapefile
Comment |  
Encoding | UTF-8
Geometry | Polygon (MultiPolygonZ)
CRS | EPSG:2957 - NAD83(CSRS) / UTM zone 13N - Projected
Extent | 722502.7555060090962797,5666736.9698800137266517 :   723388.9466733315493912,5668433.1379065262153745
Unit | meters
Feature count | 1

The 2151 case

Name | Network 1 Boundary CAD 04-2020
-- | --
Path | D:\Jobs\SaskCDA\Blackbird   Creek\QGIS for SCDA\___REIMPORT Blackbird Creek Network Map 001 Final\Shape   Files\Network 1 Boundary CAD 04-2020.shp
Source | D:/Jobs/SaskCDA/Blackbird Creek/QGIS for SCDA/___REIMPORT Blackbird   Creek Network Map 001 Final/Shape Files/Network 1 Boundary CAD   04-2020.shp\|layername=Network 1 Boundary CAD 04-2020
Storage | ESRI Shapefile
Comment |  
Encoding | UTF-8
Geometry | Line (MultiLineStringZ)
CRS | EPSG:2151 - NAD83(CSRS98) / UTM zone 13N - Projected
Extent | 722503.0629303524037823,5666742.0031498344615102 :   723402.7243422616738826,5668428.1897496404126287
Unit | meters
Feature count | 2

**Comment by gioman** [comment] 2020-04-20 17:33
> I don't know what data would show the issue more clearly

@sasklrm this is not the point. But we need to try replicate the issue with the data you are using regardless of how simple they are. Also do not expect us to also have to re-create the data to replicate the issue. So just pick your shapefile/gpkgs/etc, create a zip and attach it here. Thanks!

**Comment by rouault** [comment] 2020-04-20 17:41
This is exactly the same as https://github.com/qgis/QGIS/issues/35459. EPSG:2151 is a deprecated version of EPSG:2957 and currently released versions of PROJ would pick-up EPSG:2151 instead of EPSG:2957.

This will be fixed in the upcoming PROJ 7.0.1 release

With the .prj "FROM THE 2151 FILE"
```
$ projinfo --identify 'PROJCS["NAD_1983_CSRS_UTM_Zone_13N",GEOGCS["GCS_North_American_1983_CSRS",DATUM["D_North_American_1983_CSRS",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-105.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'
[..]
Identification match count: 1
EPSG:2957: 100 %
```

With the .prj "FROM THE 2957 FILE"
```
$ projinfo --identify 'PROJCS["NAD_1983_CSRS_UTM_Zone_13N",GEOGCS["GCS_North_American_1983_CSRS",DATUM["D_North_American_1983_CSRS",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["degree minute second hemisphere",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-105.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'
[...]
Identification match count: 1
EPSG:2957: 100 %
```

Closing as upstream bug

**Closed by rouault** 2020-04-20 17:41 UTC
Labels: Bug, Feedback, Projections/Transformations, Upstream

**Comment by sasklrm** [comment] 2020-04-20 18:30
I went back to version 3.10 and the exports and imports all work exactly as expected. By the way, this is working from data imported from CAD. 

Your argument that "This is exactly the same as #35459. EPSG:2151 is a deprecated version of EPSG:2957 and currently released versions of PROJ would pick-up EPSG:2151 instead of EPSG:2957." does not seem to be correct unless you are saying version 3.10 is not current as a long term release.

**Comment by sasklrm** [comment] 2020-04-20 18:32
How does github work? One person can look for a solution and another person just closes it.

**Comment by gioman** [comment] 2020-04-20 19:24
> does not seem to be correct unless you are saying version 3.10 is not current as a long term release.

@sasklrm 
QGIS relies on several libraries fir data handling, projections, etc. If one version of QGIS ships with one of those libraries that has a bug (but a previous version didn't) the behavior you see is expected.

**Comment by sasklrm** [comment] 2020-04-20 19:25
Thank you

**Comment by gioman** [comment] 2020-04-20 19:26
> How does github work? One person can look for a solution and another person just closes it.

@sasklrm this specific facility of the QGIS repository on Github is not a support forum, is a bug tracker. So reported a suspicious behavior (thanks!) and an informed developer answered commenting that the actual issue is not in QGIS but in a underlying library, so the issue does not make sense to remain open here, as is not a bug in QGIS code.
