### ISSUE TITLE
3.12.0 Lag opening properties windows

### ISSUE THREAD

**Issue by Geologique** [qgis/QGIS#35124] opened 2020-03-17 01:21 UTC
Hi
I have noted in QGIS version 3.12.0-București Code Revision cd141490ec there is a significant lag, of 15 - 30 seconds opening the properties window for shape files when compared to 3.10.3. I have tried local and remotely hosted datasets and the lag is the same. Windows 10.0

**Comment by nyalldawson** [comment] 2020-03-17 01:27
Duplicate of #34942

**Closed by nyalldawson** 2020-03-17 01:27 UTC
Labels: Bug
