### ISSUE TITLE
Word Wrap for checkbox in Identify Tool Panel

### ISSUE THREAD

**Issue by jmonticolo** [qgis/QGIS#33271] opened 2019-12-06 15:18 UTC
**Feature description.**
In the Identify Tool Panel (https://github.com/qgis/QGIS/blob/master/src/ui/qgsidentifyresultsbase.ui), I think it's better to allow word wrapping for the `Auto open form` checkbox (`cbxAutoFeatureForm`).

**Additional context**
The main problem is, with some translations, like in french, this checkbox is translate in "Ouvrir le formulaire automatiquement" and can't be word wrapped (QCheckbox doesn't have this property).

As a result, the panel occupies a large space on the QGIS map canvas (if we leave the dock-panel at its default position).

For this, three solutions :

1- Use an already coded widget : https://github.com/ThiBsc/qtCustomPlugins > CheckBoxWordWrap

2- Code a new QgsCheckBox, whick allows wordwrapping

3- Replace this checkbox with a horizontal layout with a QCheckBox with no text, a QLineEdit and a horizontal spacer for group the QCheckBox with the QLineEdit. And adapt the code, mainly for translate the label and not anymore the text of the QCheckBox.

**Comment by roya0045** [comment] 2019-12-06 15:31
duplicate of #31650

**Comment by jmonticolo** [comment] 2019-12-06 15:59
It's not a duplicate, I don't speak about the form attribute display, just the QCheckbox in the bottom right of this panel :

![identify feature dialog](https://docs.qgis.org/testing/en/_images/identify_features.png)

**Comment by roya0045** [comment] 2019-12-06 16:24
Sorry I it englobed more than only the checkbox but provided more detail about the checkbox.

**Comment by alexbruy** [comment] 2019-12-27 10:15
Duplicates #29546. While description of that ticket is a it cumbersome, the root of the issue is the same.

**Closed by alexbruy** 2019-12-27 10:15 UTC
Labels: Feature Request, GUI/UX
