### ISSUE TITLE
QGIS 3.4.12 Crash when creating new Grass Mapset in Windows Only

### ISSUE THREAD

**Issue by kikislater** [qgis/QGIS#32246] opened 2019-10-14 15:22 UTC
Checklist before submitting

- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [x] Create a light and self-contained sample dataset and project file which demonstrates the issue

If the issue concerns a **third party plugin**, then it **cannot** be fixed by the QGIS team. Please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description). -->

**Describe the bug**
Enable Grass plugin, create new mapset after setting path. 
Path is automatically set with slash like C:/Users/sylvain\grassdata whereas Windows use antislash and path should be C:\Users\sylvain\grassdata 

**How to Reproduce**

1. Go to 'Plugins => GRASS => New Mapset'
2. Follow instruction to create new mapset
3. Choose Path
4. Crash in next step after crash

**QGIS and OS versions**

Version de QGIS | 3.4.12-Madeira | Révision du code | 625767347a
-- | -- | -- | --
Compilé avec Qt | 5.11.2 | Utilisant Qt | 5.11.2
Compilé avec GDAL/OGR | 2.4.1 | Utilisé avec GDAL/OGR | 2.4.1
Compilé avec GEOS | 3.7.2-CAPI-1.11.0 | Utilisé avec GEOS | 3.7.2-CAPI-1.11.0 b55d2125
Version du client PostgreSQL | 10.8 | SpatiaLite Version | 4.3.0
Version de QWT | 6.1.3 | Version de QScintilla2 | 2.10.8
Compilé avec PROJ | 520 | Fonctionne avec PROJ | 5.2.0

**Additional context**

Solve the crash : 
Manually rewrite path of Grass Database with antislash : \

**Comment by gioman** [comment] 2019-10-14 15:45
Duplicate of https://github.com/qgis/QGIS/issues/28148

**Closed by gioman** 2019-10-14 15:45 UTC
Labels: Bug
